### ISSUE TITLE
Decrypt OMEMO file transfer

### ISSUE THREAD

**Issue by Tuxicoman2** [jsxc/jsxc#1001]
Hi,

1/ I send files from Conversations or Dino using OMEMO to JSXC 4.2.1, I expect to be able to open the file from JSXC.
However what I get in JSXC is an URL aesgcm://...
When clicking on the URL, the web browser can't open the file.

2/ I send files from JSXC 4.2.1 using OMEMO to Conversations or Dino. I expect to be able to open the file in Conversations or Dino..
However what I get in Conversations or Dino is an URL aesgcm://... as text message
I can't do anything with that.

**Comment by Tuxicoman2** [comment]
I have the same behavior with 4.2.1-git.2a20ca67 
1/ Even if a new tab is opened when clicking on the link, the browser can't do anything with aesgcm://... url.

**Comment by mightymop** [comment]
This is related to:
https://github.com/jsxc/jsxc/issues/989

**Comment by Tuxicoman2** [comment]
I'm using Dino 0.2.0 on Debian testing and Conversations 2.9.3+fcr From Fdroid

**Comment by Tuxicoman2** [comment]
I inspected a picture sent by Dino through OMEMO.

in plugin/omemo/Plugin.ts,
_decrypted.plaintext_ variable value is 'aesgcm://upload.jesuislibre.net:5281/upload/fQUnFfE0raNWs_bp/figure-fig1.png#e34bbfdc8519e8008fd391ad3dfdde4a786e0baec53194e9ffb97a034a347d26a2cc014bdfac3d108951d423'

Thus we validate the _(decrypted.plaintext.indexOf('aesgcm://') === 0)_ and go into _processEncryptedAttachment()_

We arrive to _attachment.setData(match)_ where _match_ value is 'aesgcm://upload.jesuislibre.net:5281/upload/fQUnFfE0raNWs_bp/figure-fig1.png#e34bbfdc8519e8008fd391ad3dfdde4a786e0baec53194e9ffb97a034a347d26a2cc014bdfac3d108951d423'

I don't see until this point where the attachment data is fetched and decrypted.

**Comment by sualko** [comment]
Thanks for reporting those issues.

1) JSXC sends only encrypted files, but is not able to decrypt them. The reason for this is, that we want to protect the users privacy and don't download any image (similar to most mail clients). @mightymop was working on this lately and maybe we extend his approach a bit further.

2) This is the issue described in #989, but until now I had no time to look into it. We will track the progress there.

I leave this issue open to track the progress for the decrypt attachment feature.

**Comment by Tuxicoman2** [comment]
OK, thanks. 
Maybe just displaying a "not supported yet" message in the UI instead of an URL would be helpful.

**Comment by sualko** [comment]
> Maybe just displaying a "not supported yet" message in the UI instead of an URL would be helpful.

That's probably a good idea.
