### ISSUE TITLE
Connecting to existing XMPP on hosted NC

### ISSUE THREAD

**Issue by Gene-W** [jsxc/jsxc#1016]
My sincere apologies if this is being asked in the wrong place. I have NextCloud hosted on a VPS (Cloudamo) and my XMPP is provided through dismail.de.

I have jsxc configured for external and things seem to be connecting. When I go to personal settings it doesn't allow me to put my @dismail.de username, and when I remove the @dismal.de portion, I am taken to a login screen where no username/password combination logs me in.

Under connection parameters on that screen, it does correctly show "If you like to use your XMPP account with a different client, use s*****g~30@dismail.de as your Jabber ID (JID)."

I did quite a lot of searching and reading, but I just can't seem to find what I am missing. Thank  you for any help.

**Comment by sualko** [comment]
Please use the [issue template](https://github.com/jsxc/jsxc/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), because it provides useful information (especially the js log). Also post a screenshot from your admin config.

**Comment by Gene-W** [comment]
Thank you for your reply and for helping. Template submitted, and I hope I have provided the template information correctly!

**Comment by sualko** [comment]
close this in favor of #1017
