### ISSUE TITLE
Unable to login to jsxc (on hosted Nextcloud)

### ISSUE THREAD

**Issue by Gene-W** [jsxc/jsxc#1017]
### Expected behavior
Log in to JSXC in NextCloud
 
### Actual behavior
Taken to a login screen where no username/password combination (ie, NC login, XMPP login)  logs me in. Presented with "Authentication failed with the chat server. Maybe the password is wrong?"

### Steps to reproduce the behavior
1. Log in to NextCloud
2. Open JSXC slider and click "Online"
3. Enter XMPP username and password into the fields, presented with "Authentication failed with the chat server. Maybe the password is wrong?"

### Environment
- **JSXC version:** 4.2.1
- **Host system and version:**  Nextcloud 20.0.6
- **Browser vendor and version:** Chromium 87.0.4280.141 (Official Build) Arch Linux (64-bit)
- **Any browser plugins enabled?** Keepass XC Browser (all other plugins are disabled on my Nextcloud url)
- **XMPP server vendor and version:** ejabberd (not sure version)
-  
- **Is your XMPP server working with other clients as expected?** 
Yes: Dino, Conversations, Movim, Gajim

#### Javascript

``` 
Refused to execute script from 'https://nordicministries.myusa.cloud/index.php/apps/dashboard/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers	@	Viewer.vue:217

```

#### JSXC

```
Content Security Policy of your site blocks the use of 'eval' in JavaScript
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.

To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.

If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.

⚠️ Allowing string evaluation comes at the risk of inline script injection.
AFFECTED RESOURCES
1 directive
Source code	Directive	Status
/apps/text/js/files.js:6	script-src	blocked
```

#### XMPP

``` 
Unknown
```

#### Host

![Screenshot from 2021-01-28 18-48-04](https://user-images.githubusercontent.com/19363963/106177932-6fe37400-6199-11eb-8396-dcfebdbe5e0d.jpg)
[nmnc-1611855946678.log](https://github.com/jsxc/jsxc/files/5889081/nmnc-1611855946678.log)

Note: I'm quite new with XMPP as well as Nextcloud, but am confident to do things when instructed. Thank you for your development and for your help.

**Comment by sualko** [comment]
Your attached log is missing the interesting information. Usually if you do a right click in the console you can store the whole output in a file. You can also send some test credentials to klaus@jsxc.org.

**Comment by sualko** [comment]
Sorry, I got no mail from you.

**Comment by Gene-W** [comment]
Strange, I sent the welcome email again, hopefully that worked.
