### ISSUE TITLE
Couldn't contact registration server

### ISSUE THREAD

**Issue by jollyman000** [jsxc/jsxc#1022]
request id b703wgiZf96EqxjSkEp7.

Couldn't refister with xmpp server. Saw prev. similar question so tried again with new browser profile, but no joy.

Any suggestions appreciated.

**Comment by sualko** [comment]
@MarcelWaldvogel ping

**Comment by MarcelWaldvogel** [comment]
That should be fixed since long ago, but forgot to reply here, sorry! Can you please check again?

**Comment by jollyman000** [comment]
I thought I wasn't going to hear anything so thanks for looking at this.

Tried again. Got:
   Please report this to our issue tracker and mention the request id QTCk3ueNry2SupILKc5a.

I'm probably doing something stupid here so I apologise in advance. :)

**Comment by sualko** [comment]
Currently our managed backend seams to be down. After we fixed that issue, the registration should work again. Sorry for the inconvenience.
