### ISSUE TITLE
MUC StatusCodeHandler for 307 buggy

### ISSUE THREAD

**Issue by mightymop** [jsxc/jsxc#1025]
### Expected behavior
Show the right nickname in kick message.
### Actual behavior
If a user was kicked the message show the own nickname...
### Steps to reproduce the behavior
1.Log into MUC
2.Kick a user / other admin kicks a user
3.read the message ;)

### Environment
- **JSXC version:** master (4eb4524)

The bug lies on **StatusCodeHandler.ts** in **private 307(room, nickname, data, xdata)**

`nickname: this.getNickname()` 
this.getNickname() allways returns own nickname instead of the kicked user.

btw. the function parameters are all undefined (allways)

**Comment by sualko** [comment]
Thanks for your report. I think the same is true for the other codes as well.
