### ISSUE TITLE
bug running mode production

### ISSUE THREAD

**Issue by ihisoka** [jsxc/jsxc#1026]
### Expected behavior
it should generate chunks and bundles
### Steps to reproduce the behavior
1. run package start script
2.
3.

### Environment
- JSXC lastest
-  jsxc typescript version

#### Javascript
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'minimizer'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
   -> Options object as provided by the user.
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           minimizer: …
         }
       })
     ]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "C:\Windows\System32\cmd.exe /d /c yarn run start" terminated with exit code: 2.

**Comment by ihisoka** [comment]
this line => config.minimizer = [
 to this => config.optimization.minimizer = [

**Comment by sualko** [comment]
Thanks for reporting this and @Fishbowler thanks for the pr. Sorry that it took so long to merge it.
