### ISSUE TITLE
Only a URL is shown when sending images

### ISSUE THREAD

**Issue by tomdeck** [jsxc/jsxc#1029]
Only a URL is shown when sending images

### Expected behavior

When sending images from / to JSXC then the image should be displayed to the end-user

### Actual behavior

Instead of images, only a URL is displayed to the other party in most cases, depending on the client but some other factors as well.

### Steps to reproduce the behavior

My problem is probably the same as #989 or at least is very similar. But I'm ot using encryption.

I tried sending images between different clients:
- Sending between two JSXC instances works when both sides are on-line. But if I log in later / go back to older messages, which were displayed fine in an earlier session then the older images are displayed as links
- Sending between JSXC and Conversations shows links only, in both directions
- Sending between JSXC and Converse.js sometimes works, I haven't yet figured out when. In most cases, Converse.js shows nothing (no sign of a message) when I send a picture from JSXC. And when I send from Converse.js to JSXC then only a link is displayed in JSXC

I tried sending with and without text but that doesn't seem to have any effect.

Sending images between Converse.js and Conversations works in all combinations.
I saw a comment on the #989 issue mentioning privacy and external images; in my case the URL where the JSXC app is available and the URLs passed for the images contain the same protocol/hostname/port so that doesn't look like an external image.

### Environment
JSXC v4.2.1, using the example application
ejabberd-21.04
converse.js: current try-out version on their homepage
Conversations: 2.9.13+fcr from F-droid
Browser version: Tried firefox 78.10 ESR and Falkon 3.0.1
In firefox, I tried these steps with an empty profile as well

#### Javascript

I don't get any javascript errors in the console. The links that are transmitted actually work in the other client so I suppose the upload works as intended.
All POST/PUT requests have a 200 or 201 result code in the console.

#### JSXC
Same situation if I enable debug mode.

#### XMPP
No error entries in the XMPP server log

#### Host
No errors

**Comment by sualko** [comment]
That has been resolved in #973 and will we published with the next release. Thanks for your issue anyway.

**Comment by tomdeck** [comment]
Excellent news, thank you!
