### ISSUE TITLE
a user should be able to select "offline" status, meaning: logout from jsxc

### ISSUE THREAD

**Issue by heupink** [jsxc/jsxc#103]
Currently the only way to logout jsxc is to actually logout the owncloud webinterface. I think that a user should also be able to set himself to "offline", to work in owncloud/SOGo without using the chat interface. Perhaps the last state could even be remembered upon the next logon?

Anyway: thanks for jsxc: great addition to both SOGo and OC!

**Comment by itJunky** [comment]
Yes, it really needed if i need to change account.

**Comment by bugfixxx** [comment]
Hello! I implemented this in my installation (jsxc core):
I added a Logout to the settings in roaster:
jsxc/jsxc.lib.js:
1) within jsxc.gui.template find "roaster:"
in the div "jsxc_menu" add:
<li class="jsxc_logout">%%Logout%%</li>\

2) add "Logout" to the language-variables

3) within the init-function add:
 $('#jsxc_roster .jsxc_logout').click(function() {
        	jsxc.xmpp.logout();
         });

regards, harald

**Comment by itJunky** [comment]
Eaahh thanks :+1:
