### ISSUE TITLE
Upgrade JavaScript XMPP Chat to work with Nextcloud version 21

### ISSUE THREAD

**Issue by greavette** [jsxc/jsxc#1035]
### Expected behavior
Upgraded Nextcloud from 20 to version 21.
jsxc chat was working in Nextcloud 20.0.9.

### Actual behavior
JavaScript XMPP Chat	4.2.1.
Nextcloud says this app is not available for this version of Nextcloud 21.0.2

### Environment
- JavaScript XMPP Chat	version 4.2.1 
- **Host system and version:** Nextcloud 21.0.2
- **Browser vendor and version:** - Google Chrome:  Version 91.0.4472.77

**Comment by sualko** [comment]
We are currently in the beta test phase for NC 21 support. See https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v4.3.0-beta.1
