### ISSUE TITLE
jsxc 0.4.3. no chatbar 

### ISSUE THREAD

**Issue by EmJotGeh** [jsxc/jsxc#1041]
it seems that jsxc is not working after installing 0.4.3. The chat bar (right) is gone. Settings are available. Nextcloud 21.0.3 - Firefox 89.0.2 with and without Addons enabled.

**Comment by sualko** [comment]
I guess you mean 4.3, right?

Can you please use the issue template, and provide your js log (from your browser)?

**Comment by DanScharon** [comment]
can confirm with Nextcloud 20.0.11 (and jsxc 4.3 :wink:)
Login site doesn't even load the alternative buttons to login with or without chat.

console output:

```
16:47:15.576 Uncaught Error: Keys should not be generated without CSPRNG.
    xe https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    71183 https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    __webpack_require__ https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    8118 https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    __webpack_require__ https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    48392 https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    __webpack_require__ https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    62633 https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    __webpack_require__ https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    88156 https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    __webpack_require__ https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    80341 https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    __webpack_require__ https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    <anonymous> https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
    <anonymous> https://my-testcloud.example.com/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=c9e4dc50:2
jsxc.bundle.js:2:1556486
```

**Comment by sualko** [comment]
Thanks for the logs Daniel. Seams like the OTR package is broken on my machine again. I don't know why this happened.

**Comment by sualko** [comment]
I updated the build files and will release a bug fix version tomorrow. Sorry for the inconvenience.

**Comment by EmJotGeh** [comment]
Vielen Dank für das schnelle fixen! Es ist natürlich Version "4.3". :-)  Allerdings muss ich sagen das ojsxc 4.3 sprichwörtlich nicht Rund läuft. Der Button "Anmelden mit Chat" scheint keine funktion zu haben. 
Wenn ich mich ohne Chat anmelde und auf "Online" klicke passiert auch nichts. Der kleine Kreis rotiert aber ojsxc gibt mir keine Online Rückmeldung. Gehe ich aber auf "Gesprächig" scheint sich ojsxc navch ein paar Sekunden zu verbinden. Klicke ich danach wieder auf Online scheint ojsxc tatsächlich auch online zu sein. 

Ich nutze im Moment noch den internal Server.

**Comment by sualko** [comment]
I try to keep Github open for everyone, so I will answer in English. 

I'm sorry that you have trouble with the latest release. Currently I don't have any idea why you are having trouble, but to change that I need all information which is requested by our issue template. Therefore please open a new issue with that information.
