### ISSUE TITLE
Use Electron to make a desktop version of JSXC?

### ISSUE THREAD

**Issue by sunrez** [jsxc/jsxc#1045]
**Describe the solution you'd like**

Have any JSXC developers looked into or thought about using Electron to make a cross-platform "desktop" version of the app available?  I believe this is what RocketChat and ConverseJS are doing as well.

This is important because I am not aware of any "all in one" XMPP / Screensharing / Audio Calling / Video calling application besides the Pade stuff the OpenFire guys are working on (ConverseJS + JitsiMeet).

**Comment by sualko** [comment]
Maybe https://github.com/jsxc/desktop helps you :wink:

**Comment by sualko** [comment]
I'm currently preparing github actions to build a version for every platform, but for some reason I get timeouts from time to time on different os there. If you have time it would be great if you could help: https://github.com/jsxc/desktop/tree/feat-builder
