### ISSUE TITLE
Documentation for pre-commit husky styling?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#1053]
The [documentation](https://jsxc.readthedocs.io/en/latest/development/notes.html#workflow) just mentions that there is a pre-commit check (apparently Husky based).

But since there is no further documentation on the required styling I had to do quite a bit of try & error and guesswork based on some of the existing commit messages to get it to accept a git commit.

This seems like a really unnecessary entry barrier for (newbie) code-contributions and it would be nice if that could be simplified or at least documented somewhere. Thanks!

**Comment by sualko** [comment]
Thanks for the helpful feedback. I guess it's a communication issue, since you can use `yarn fix` to beautify all files.
