### ISSUE TITLE
Problems with BOSH and Openfire

### ISSUE THREAD

**Issue by SilverAngel** [jsxc/jsxc#106]
Hi

I have installed OpenFire as XMPP Server and want du use the Owncloud Version of jsxc baut have a problem with BOSH. When i send a request with the browser (domain.tld:7070/http-bind/?<body%20rid="1"/>) i see that BOSH is working, but within the admin-panel of owncloud i get the error "BOSH server NOT reachable. ...". i use the same host for both owncloud and openfire. Are there any knowen issues with openfire?

**Comment by mdbyambaa** [comment]
I have installed OpenFire as XMPP Server. 

![1](https://user-images.githubusercontent.com/47658181/52844807-6a252d00-3140-11e9-95e5-bac363bddd93.png)
![2](https://user-images.githubusercontent.com/47658181/52844808-6a252d00-3140-11e9-9723-0b9f72d02b67.png)

**Comment by sualko** [comment]
@mdbyambaa I guess your XMPP is not an url and your BOSH url should be the full url visible in your second screenshot. Why are you hiding your url just in one screenshot? And next time please open a new issue.
