### ISSUE TITLE
OMEMO messages from MAM won't be decrypted

### ISSUE THREAD

**Issue by mightymop** [jsxc/jsxc#1079]
### Expected behavior

If i clear the messages and reload them from mam, omemo encrypted messages should be readable again...

### Actual behavior

If i clear the messages and reload them from mam, the body message "I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo" will be shown

### Steps to reproduce the behavior
1. Open chatwindow, verify all omemo devices in the omemo dialog
2. write some omemo encrypted messages
3. clear the chat histody and reload it with the load messages button

### Environment
- **JSXC version:** 4.4.0
- **Host system and version:** 
- **Browser vendor and version:** any
- **Any browser plugins enabled?** all
- **XMPP server vendor and version:** Openfire 4.7.1
- **Is your XMPP server working with other clients as expected?**  yes

**I have looked into the code and it seems the "afterReceiveMessageProcessor", "preSendMessageStanzaProcessor" and "preSendMessageProcessor" from omemo plugin wont be called by the mam plugin** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
If I remember this correctly, this is not possible with omemo, because we can not store all immediat keys.

**Comment by mightymop** [comment]
> If I remember this correctly, this is not possible with omemo, because we can not store all immediat keys.

I think this belongs to later added devices which will get new device ids but in my tests i did neither logged out nor refreshed or deleted the browser cache, so the the device id was not changed... in theory jsxc should be able to decrypt mam messages as new incoming messages

**Comment by sualko** [comment]
To decrypt a message we need the current state of the ratchet which was used to encrypt the message. To save storage and protect the key material, this state is deleted as soon as it's not used anymore. This means we can not decrypt messages at this state (e.g. if the messages are from mam).

**Comment by mightymop** [comment]
Ah okay thx to clarify this

**Comment by mightymop** [comment]
Issue is not a bug, but a feature
close #1079
