### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [jsxc/jsxc#1114]
Hello, it seems, that in past there was an attempt to use continuous localization platform:
https://github.com/jsxc/jsxc/issues/121

But as there is much bigger Nextcloud translators community on Transifex, would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

Thanks :-)

**Comment by p-bo** [comment]
For instance:

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c (se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

**Comment by p-bo** [comment]
Don't worry, it is not rocket science - just open issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). And you will get checklist as for example this: https://github.com/nextcloud/docker-ci/issues/426 and you can ask [rakekniven](https://github.com/rakekniven) if something is unclear to you. Hope it helps :-)

**Comment by p-bo** [comment]
For motivation: This developer at first [was not so fond](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1260663047) of this approach, than [he agreed to try](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1268635618) and at the end, [was very pleased](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1274590428) with result! :-)

**Comment by p-bo** [comment]
Wrong repo (wrong link in Nextcloud app store because Nextcloud app metadata) - should be in https://github.com/nextcloud/jsxc.nextcloud

**Comment by comradekingu** [comment]
@p-bo The problem is what happens when you don't look at the actual translations before declaring victory.
Every single NC project on Weblate is doing better than even the central NC components.
It is a smaller community of users, and the tool itself facilitates drive-by translations.
Thus, size is a metric that works against arriving at quality translations on TX.

nc_money also uses erroneous locales, and if that is TX or not I don't know, but it has no way of changing it or even detecting it.
