### ISSUE TITLE
Connection lost due to roster items

### ISSUE THREAD

**Issue by skupkosk** [jsxc/jsxc#119]
Thanks for this impressive client!
Just discovered issue with disconnects after having contacts from not available XMPP transports. After unregistering from those I was able to remain logged on JSXC. Could be related to issue with strophe.js - not sure.

**Comment by sualko** [comment]
Thanks for reporting. Can you give me an example of an "not available XMPP transport"? Never tried transports before.

I think this is not related to diaspora/jsxc#60.

**Comment by skupkosk** [comment]
Not sure when I will have time to install transports and test with my roster again.

**Comment by sualko** [comment]
With the latest beta release we updated strophejs to the latest release, so you should check if this issue is still valid. If you can confirm that or give an example how to reproduce this, please reopen this issue.
