### ISSUE TITLE
Code organisation

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#121]
The main file has now more than 6000 loc and I feel increasingly uncomfortable with that. 

@dimaursu @Zauberstuhl  What is your though on splitting up the file in there main namespaces (e.g. xmpp, storage, ...) and to create po files for localisation? We could use online translation management systems like [transifex](https://www.transifex.com/) or [weblate](http://weblate.org/) and convert it into json with [grunt-po-json](https://www.npmjs.com/package/grunt-po-json).

@MarcelWaldvogel and I also want to move jsxc to its own organisation to simplify further development and collaboration.

Hopefully we can have a open discussion about those topics.

**Comment by dimaursu** [comment]
It would be a nice idea. It could also be applied to CSS, those files are huge. I will cherry-pick my SCSS changes to a clean branch today, btw. I can split the files up right away.

**Comment by Zauberstuhl** [comment]
That are some interesting points. What do you think about [i18next](http://i18next.com/)? The library supports [json files](https://github.com/diaspora/jsxc/tree/develop/locales), too.

Since diaspora translation is handled by [webtranslateit](https://webtranslateit.com/en), I created also for jsxc a [project](https://webtranslateit.com/en/projects/10365-JSXC).

I could restore the old PR for upstream if that is wanted.

**Comment by sualko** [comment]
@dimaursu That is a great idea.

@Zauberstuhl I will take a deeper look into i18next, looks interesting.

**Comment by sualko** [comment]
i18next solves some of my concerns about large translation files and I would appreciate if you could restore your pull request. 

Is there any change to separate jsxc from diaspora in webtranslateit? It is only for cosmetic reasons. @MarcelWaldvogel What do you think about it?

**Comment by Zauberstuhl** [comment]
@jhass if @sualko is moving to webtransletit there is no need for us to have a separate translation-repo. My suggestion would be; Create a new jsxc-repo and after successful integration into jsxc we should remove the diaspora-jsxc-repo. Objections?

**Comment by jhass** [comment]
I'm sure if we create a jsxc organization and then shoot Eduard a mail, he's able to move it over.

@sualko the main reason we started our own translations is that we need to replace some terminology, most importantly we talk about contacts instead of buddies, would you be okay with inheriting that change then?

**Comment by sualko** [comment]
@jhass The term buddy is only used in the xmpp spec, so I have no problem with that.

I will create a new project on webtranslateit.

**Comment by sualko** [comment]
https://webtranslateit.com/en/docs/faq#move-a-project-to-another-account

**Comment by jhass** [comment]
Yeah, so just create an organization and tell me its ID and I'll shoot Eduard a mail.

**Comment by sualko** [comment]
https://webtranslateit.com/en/organizations/13046

**Comment by sualko** [comment]
Can someone explain the difference between admin and project manager?

**Comment by jhass** [comment]
As admin of the organization you can create new projects and always have manager access to all projects of the organization, although you're not listed as manager in the project.

As project manager you have access to the project settings, can edit all discussions and segments in all languages and so on. It also looks like only managers but not admins can edit project memberships, although that's probably a bug in WTI.

I tend to list myself as project manager, even though I'm organization admin, so people have an easier way to find contact. You can do that as admin by sending yourself a manager invitation from the projects user page.
