### ISSUE TITLE
BOSH

### ISSUE THREAD

**Issue by plberd** [jsxc/jsxc#128]
I have my owncloud at `https://oc.host.me`, a reverse proxy on my webserver that connects to my bosh server `https://oc.host.me/http-bind` and, my xmpp domain is `host.me`

When I set it up on OC8 admin panel, everything is green but, when I try to login the "logging in" popup shows and... that's it. Nothing else happen on my browser, it just stays spinning.

On the server, prosody logs 8 new BOSH sessions assigned it sid (allways different UIDs) and no errors.

I use the same reverse proxy to connect jappix and it works well.

**Comment by sualko** [comment]
I could not detect any problem with my test credentials. Can we close this issue?

**Comment by plberd** [comment]
Yes... close it because my problem has nothing to do with bosh.
I still have issues with the accounts I had before upgrading to OC8. But the one that just got stuck on the login screen (mine) got sort of fixed when I deleted and recreated the OC user. None of the others did that.
After that all other pre-existing accounts are having some troubles but it seems to be something related to the browser. The test user I created for you works flawlessly everywhere. My user doesn't connect on my home pc with firefox, but it does on chromium (which I don't use much) and its working now on firefox at work (where its always on privacy mode). My wife's doesn't work on her browser, but it works on mine. I have to test more, to find exactly what's wrong and what to delete specifically to get ojsxc working.

Thanks for your help!
I'll let you know I find anything worth telling.

**Comment by sualko** [comment]
> I'll let you know I find anything worth telling.

That would be nice.

**Comment by mr-tron** [comment]
I same situation `consider_bosh_secure = true` in prosody.cfg.lua help me.

**Comment by plberd** [comment]
I didn't try that. I just deleted ~/.mozilla on all of my users's environments. That worked, and I still consider bosh... well... the default, I don"t specify that on my config.
