### ISSUE TITLE
Visualize unread messages while tab is in background

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#131]
We could change favicon [1] and/or page title.

We could also show a permanent notification about x unread messages after some time.

[1] http://www.totallycommunications.com/latest/dynamic-favicons-step-by-step-guide/

**Comment by v1r0x** [comment]
How about something as in facebook?
"(n) Chat"
"n new Messages from ...."

**Comment by sualko** [comment]
Something like that, but we have to mention, that we do not bug somebody with notifications.

**Comment by sualko** [comment]
I decided not to display a permanent notification, because it would be hard to find a solution which does not bug somebody and give helpful information at the same time.
