### ISSUE TITLE
Switch from JS to CSS based animation

### ISSUE THREAD

**Issue by dimaursu** [jsxc/jsxc#133]
I've implemented a while ago the animation in pure CSS, simplifying the JS code, and making the animation smoother (about a 3x gain in FPS). 
Are you interested in this? The whole trick involves a checkbox, it's quite simple. 

It might be a bit less flexible than the JS animation, it's a bit harder to get the drawer state (although not that hard, just reading the checkbox value)

https://github.com/diaspora/jsxc/commit/0fb67675e1f67464a0aad2c9054fd3d2eaae8163

**Comment by sualko** [comment]
I think the commit is not enough, there should be more from diaspora/jsxc#63, but that is just an aside.

Are there any disadvantages of this method? Browser support or something like that? I never thought about css performance, but I'm always interested in learning new things (could be useful for #83).

While googling I found http://css-tricks.com/myth-busting-css-animations-vs-javascript/ and therefore https://greensock.com/jquery-gsap-plugin. Do you know gsap? That could boost every animation.

**Comment by sualko** [comment]
> performance improvements are at least 3x, in Firefox benchmarks

How did you perform your benchmarks?

**Comment by dimaursu** [comment]
Chromium and Firefox inspector. The "Timeline" feature shows the FPS and where was the time spent. it was 5 FPS vs 15 FPS during animation (which is still slow, quite far from 60 FPS), but definitely better. The animation was visibly smoother, mainly because of using css `translate` instead of animation on the right property. CSS translations have GPU acceleration, and do not stutter like JS ones.

**Comment by dimaursu** [comment]
http://jankfree.org/ - here are the resources I've learned this stuff. Using greensock to animate a drawer - that's kinda overdoing it, it's not worth it. In terms of browser support, we're pretty much covered: 
http://caniuse.com/#search=translate
this being used for animation (but of course we can provide a css fallback with animation on the right property)
http://caniuse.com/#search=sibling
and a sibbling selector is used to adjust the stiling in relationship with the checkbox, which keeps the state of the drawer. 

One thing that could be a problem - you can't have swipes on a mobile device. That can only be achieved  with JS.

**Comment by sualko** [comment]
Together with #229 and #217 this should be fixed.
