### ISSUE TITLE
Daltonian mode ?

### ISSUE THREAD

**Issue by AugierLe42e** [jsxc/jsxc#137]
This is something that has been requested by diaspora* users. JSXC currently use blue, gray and red colors which are not easy to distinguish by daltonian users. I thought about adding it in diaspora's version of JSXC but it might benefit to upstream too.
Are you interrested by this feature ?

**Comment by sualko** [comment]
It depends on its realization, but in general we are interested in such topics.

Maybe you can write some lines about your ideas.

**Comment by AugierLe42e** [comment]
Idea would have an optin mode for daltonian that would override the CSS rules of colors for connected, disconnected and busy status.

**Comment by sualko** [comment]
Sounds great. Would love to see a PR.

**Comment by AugierLe42e** [comment]
I can see what I can do.

**Comment by sualko** [comment]
#217 should also satisfy daltonian.

![screen shot 2015-11-18 at 14 43 08](https://cloud.githubusercontent.com/assets/2974196/11242551/bf8c736e-8e02-11e5-8d38-24fd3c13baaa.png)
 
What do you think?
