### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by muecke77** [jsxc/jsxc#140]
I am using owncloud 8.02 and ojsxc 1.1.0

Login only works with Chrome or Safari when ojsxc is enabled. With firefox login doesn't work as nothing is happen. Even in the logs does mentioned any hint. This happens to me with a Mac 10 as well as Windows 8.1
Any idea?

-muecke77

**Comment by sualko** [comment]
Sorry, I can not confirm your issue. Can you send some test credentials to klaus@jsxc.org?

**Comment by muecke77** [comment]
Sorry for the late reply. As a matter of fact the behavior depends on the client. I have to clients ( Windows 8.1 and Mac) were the issue exists and on client (Windows 8.1) were is does work without any issues. One think which is obious: After inital load of the login page, the option "login without chat" only shows up with the client were it does work. 
 I will try to find out more details.

**Comment by sualko** [comment]
Do you have any addons installed? Which ff version do you use?

Please send me at least your url to klaus@jsxc.org.

**Comment by muecke77** [comment]
Finally the root cause for that issue seems to be one of my Firefox Add-ons. After a complete fresh install of Firefox (including deleting all settings) everything is working fine, even after are enabled again my add-ons.
