### ISSUE TITLE
how to work with XEP-0313 ?

### ISSUE THREAD

**Issue by stonely2012** [jsxc/jsxc#141]
I'm using ejabberd for my server, jsxc for client.
Jsxc use otr for encrypt message. When i received archive message from server (via ejabberd mod mam), I don't know how to decrypt message, i was try decrypt but archive message has old session and can not decrypt. Can anyone help me?

**Comment by sualko** [comment]
You can not decrypt your messages. If you like to use message archives, you 
have yo disable OTR.

**Comment by stonely2012** [comment]
thanks you very much :)
