### ISSUE TITLE
Stanza Forwarding (XEP-0297)

### ISSUE THREAD

**Issue by robsen2k** [jsxc/jsxc#142]
Iv'e seen that the jsxc forwarding supports. So my question is then i write to users that are logged in and secondly logged in with Xabber, there is no synchronisation.

installed Version of Owncloud is 8
Chatserver is openfire 3.9.3

based on Synology dsm 5

**Comment by robsen2k** [comment]
ok just reading that i have to mark carbon copy

**Comment by robsen2k** [comment]
after i tested with the app conversations the syncronize to jsxc it works but when i test carbon messages from jsxc it didn't work. Carbon copy is marked

**Comment by sualko** [comment]
Can you send some test credentials to klaus@jsxc.org?

**Comment by sualko** [comment]
Any update?
