### ISSUE TITLE
Suggest owncloud username

### ISSUE THREAD

**Issue by v1r0x** [jsxc/jsxc#143]
I hope this is not a duplicate or something already discussed.

On our (owncloud) server we have some rather cryptic names. Therefore it would be great to have some sort of auto completion in the "add friend" dialog.

Example:
If there is a user with the username "p3t3r" and the display name "Peter Parker" it would be great to get his name as suggestion if I type "p3..." or "pa..." or "pe...".
Basically I'd like to have something as in the file sharing dialog.

**Comment by sualko** [comment]
I like your idea and I will try to implement this soon.

**Comment by v1r0x** [comment]
I wrote some sample-code in PHP. Maybe this is helpful ;)

```php
<?php
	$typed = strtolower("V");
	$userarray = array();
	$users = OC_User::getUsers();
	$url = "owncloud.domain.tld";
	foreach ($users as $uid){
		if(strpos(strtolower($uid), $typed) === 0){
			echo $typed . " is in (" . $uid . ")<br/>";
			$userarray[$uid . "@" . $url] = OCP\User::getDisplayName($uid);
		} else if(strpos(strtolower(OCP\User::getDisplayName($uid)), $typed) === 0){
			echo $typed . " is in (" . OCP\User::getDisplayName($uid) . ")<br/>";
			$userarray[$uid . "@" . $url] = OCP\User::getDisplayName($uid);
		}
	}
	print_r($userarray);
?>
```

**Comment by sualko** [comment]
I apologize my delay, but I'm currently busy with #114.

**Comment by v1r0x** [comment]
No need to apologize. MUC is much more important than this issue, but I thought I could share what I coded a couple of months ago.
