### ISSUE TITLE
OwnCloud unavailable after installing jsxc

### ISSUE THREAD

**Issue by masscream** [jsxc/jsxc#144]
Hello,

after installing jsxc to my OC server and enabling it, I have just white page instead of a OC login screen, the only way is to delete the jsxc app folder to make it accessible again. Apache log says nothing but from OC log I can catch following errors:

Error	PHP	js file not found: script:js/jsxc/lib/jsxc.dep.min serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#46	2015-04-01T14:11:34+00:00

Fatal	index	Exception: {"Message":"js file not found: script:js\/jsxc\/lib\/jsxc.dep.min serverroot:\/var\/www\/owncloud","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/templatelayout.php(156): OC\\Template\\ResourceLocator->find(Array)\n#1 \/var\/www\/owncloud\/lib\/private\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\n#2 \/var\/www\/owncloud\/lib\/private\/template.php(118): OC_TemplateLayout->__construct('user', 'files')\n#3 \/var\/www\/owncloud\/lib\/private\/template\/base.php(103): OC_Template->fetchPage()\n#4 \/var\/www\/owncloud\/apps\/files\/index.php(148): OC\\Template\\Base->printPage()\n#5 \/var\/www\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_677', Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/files\/')\n#9 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php","Line":46}	2015-04-01T14:11:

I am using ojsxc 1.1, ownCloud 8.0.2, ejabberd server. Can you advise please?

Thanks

Tomas

**Comment by sualko** [comment]
Did you install jsxc from the app store?

**Comment by masscream** [comment]
I think I made a mistake, I was trying to install it by commands below, which worked for another app (of course with different address). But in this case it does not seem the right option. Now I re-installed it manually by getting the right files from the site and it seems functional. Thanks for your will to help ;)

git clone https://github.com/sualko/ojsxc/
git submodule update --init --recursive
