### ISSUE TITLE
BOSH problem

### ISSUE THREAD

**Issue by lelik9** [jsxc/jsxc#147]
Hello.
I have my owncloud at https://cloud.example.com.
In my apache config i add:
   < Location /http-bind>
      Order allow,deny
      Allow from all
   < /Location>
   RewriteEngine On
   RewriteRule ^/http-bind$ http://localhost:5280/http-bind [P,L]
And when i go to https://cloud.example.com/http-bind/ open BOSH server page
In xmpp config I set BOSH url - /http-bind/ 
In config.php I add:   *'custom_csp_policy' => 'default-src \'self\' https://cloud.example.com/http-bind/; script-src \'self\'  \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *; connect-src *',
  'theme' => '',*
But when I press save, get error: *BOSH server NOT reachable. Please beware of the same-origin-policy (SOP). If your XMPP server doesn't reside on the same host as your OwnCloud (same port/protocol), use the Apache ProxyRequest or modify the content-security-policy (CSP) by defining "custom_csp_policy" in OwnCloud's config.php.*

**Comment by sualko** [comment]
I guess your rewrite rule is wrong. It should be (untested):

```
RewriteRule ^/http-bind/ http://localhost:5280/http-bind/ [P,L]
```

**Comment by lelik9** [comment]
I changed it, but nothing happens

**Comment by sualko** [comment]
You can remove your custom csp policy, because you are on the same host. Which xmpp server do you use? Can you connect with another client via bosh?

**Comment by lelik9** [comment]
Delete csp, but result the same. I using prosody xmpp server. No, i no tried on another client.

**Comment by sualko** [comment]
Please send some test credentials to klaus@jsxc.org.

**Comment by sualko** [comment]
Wrong prosody config.
