### ISSUE TITLE
Using ajax login, the connection is lost after to open two tabs on the same browser

### ISSUE THREAD

**Issue by shaggybb** [jsxc/jsxc#148]
Hello,

I've detected a problem using the ajax login feature  and trying to open a secondary tab in the browser. The message "Master request." is shown in a constant loop (located at  https://github.com/jsxc/jsxc/blob/master/jsxc.lib.js#L4677)

![jsxc_error_with_second_tab](https://cloud.githubusercontent.com/assets/1043952/7112701/b411a6a4-e1cc-11e4-85bb-b89862de4d63.png)

My hipothesis: Maybe the cause is it tries to generate new SID instance due to the fact that the ajax login feature does not use the localStorage's sid. What do you think? Where I am wrong?

**Comment by sualko** [comment]
Currently I can not confirm your issue, because on my Mac with Chrome 41.0.2272.118 everything works fine. So please provide more details about your browser (I guess also chrome), your testing environment (I see VM102 in your log) and progress (do you open the second tab after you logged in?). Please also provide the log from the second tab.

**Comment by shaggybb** [comment]
@sualko 
I'm using ubuntu 14.04 with Chrome 42.0.2311.90 (64-bit)

I will try to explain me better:
### Steps
1 Open Chrome with only one tab (blank page).
2 Load page with jsxc and using AJAX login.
3 Once I am logged, create a duplicated tab of first tab.
4 After logged in on the second tab (see console.log of second tab), the app remain in a loop  displaying"Master request." and the chat does not display in the page.
5 I switch to the first tab, and I have been logged out and jsxc shows me the relogin template.

Here the console log of each tab: 

### First tab 
(The "Master request." and next logs appear after being logged in the jsxc of second tab but does not show in page)
![first_tab_after_logged_in_second_tab](https://cloud.githubusercontent.com/assets/1043952/7199527/ba60a632-e4f5-11e4-9085-a23411b46dd9.png)
### Complete log of second tab
![second_tab_complete_log](https://cloud.githubusercontent.com/assets/1043952/7199529/bc87f30c-e4f5-11e4-82d4-2699c39e74b6.png)

**Comment by shaggybb** [comment]
The VMXX is due to I'm loading jsxc via $.getScript

**Comment by sualko** [comment]
If I got it right, you try to log in with multiple session in one browser. However this is not possible with jsxc, because if you refresh one page jsxc can not know which session it should continue.

**Comment by shaggybb** [comment]
@sualko 

I was confused with the usage of master-slave functions that the jsxc code is using.

To solve multiple tabs problem, I'm working in mix between sessionStorage and localStorage. The idea is to store buddies, chats, resources, windows, members items in the localStorage and the rest in the sessionStorage.

By the moment, I am able to have two tabs with differents sessions but still I need to synchronize the gui interface between them. Each tab is usign window.name to stablish resource, for instance my resource is 'jsxc' + '-' + MD5.hexdigest(navigator.userAgent) + '-' + window.name. 

I hope to have something stable in few weeks.

Can I know some trick to synchronize the gui between tabs? I'm following (more or less) the usage of master-slave code of the project
