### ISSUE TITLE
Weird display text 

### ISSUE THREAD

**Issue by pedrobastosz** [jsxc/jsxc#149]
Hi. I am testing the Client following the instuctions on the example page and everything appears to be OK, except for some buggy characters/texts. 

Have you ever seen anything like that? I tried both Chrome and Firefox. 

By the way, what a great library :)

![buttons02](https://cloud.githubusercontent.com/assets/11931753/7125947/c46854f0-e20b-11e4-94b0-f09501469b69.png)

**Comment by v1r0x** [comment]
You should use Unicode as encoding. I get the same results, if I use something different than Unicode.

**Comment by sualko** [comment]
First of all, thank you for testing jsxc.

v1r0x is right, you should use utf-8.

**Comment by pedrobastosz** [comment]
Thanks a lot V1r0x and sualko for the feedback. Yes, you are right. I set the http meta tag '<meta http-equiv="content-type" content="text/html; charset=UTF-8">' and it works like a charm. Again, nice work out there, the UI part of this library is pretty awesone.
