### ISSUE TITLE
See complete history (XEP-0313)

### ISSUE THREAD

**Issue by v1r0x** [jsxc/jsxc#150]
I really like your app, but there is one thing missing.
I already compiled and installed a new version of ejabberd, to get mod_carboncopy ([XEP-0280](http://xmpp.org/extensions/xep-0280.html)) and mod_mam ([XEP-0313](http://xmpp.org/extensions/xep-0313.html))

I also activated Carbon Copy in jsxc-owncloud Settings.
But I have two problems:
- I can only access the last ~10 messages and not the whole history
- The history of my laptop is only on my laptop and not on my desktop pc

And idea? :)
##

**Comment by sualko** [comment]
1) You can save more than 10 messages if you set <code>numberOfMsg</code> to a higher value (https://github.com/jsxc/jsxc/wiki/Options).

2) XEP-0313 is not yet implemented, but we always appreciate pull requests ;-).

**Comment by v1r0x** [comment]
1) Thanks, didn't see the options. Sorry.
2) I'm currently writing my master thesis, so I don't have much time for other big projects. But if I have the time (and knowledge of xmpp) I'll try to help :)

**Comment by ltsavar** [comment]
I would also like to see this feature :)

**Comment by v1r0x** [comment]
I still couldn't find the correct file to edit these options (I found the options in at least 3 files). Could you give me a hint? :)

**Comment by sualko** [comment]
Add <code>numberOfMsg</code> to the init options in <code>js/ojsxc.js</code>. e.g.

```
...
jsxc.init({
      app_name: 'Owncloud',
      numberOfMsg: 100,
      loginForm: {
...
```

**Comment by jacekgrzybowski** [comment]
+1 for XEP-0313 support

**Comment by nickbroon** [comment]
:+1:

**Comment by julian-d** [comment]
+1 for XEP-0313 support

**Comment by samweisgamdschie** [comment]
same here +1 for XEP-0313!

**Comment by LEDfan** [comment]
Hey, I started working on this a bit. 

Which version of the XEP should we support? Version 0.2 http://xmpp.org/extensions/attic/xep-0313-0.2.html and version 0.3 http://xmpp.org/extensions/attic/xep-0313-0.3.html both has a plugin for Strophe.JS, but there are also version 0.4 and 0.5. 

I have something working with Prosody, which is using version 0.3.

Should it support all versions, or only the latest?

**Comment by DanScharon** [comment]
@LEDfan as Prosody is pretty widespread, I think it should be supported

**Comment by sualko** [comment]
I would go with the latest version, because the [version history](http://xmpp.org/extensions/xep-0313.html#appendix-revs) shows, that there only some clarifications and bug fixes. @LEDfan thank you for working on this.

**Comment by skyfox675** [comment]
@LEDfan how would I setup a pull request for your working version to use with my ejabberd instance?

**Comment by dteleguin** [comment]
@LEDfan, any progress on that? Sorry for bothering, but turns out there is high demand for server-side history in JSXC. Do you need any assistance?

**Comment by niteshhardia** [comment]
Hello, i am interested in server-side history in JSXC, what i have observed that in the same system where history was generated, the history is gone when clearing out cache and cookie of that system, can someone help i am stuck ?

**Comment by singh1114** [comment]
Hello guys,
I want to work on this issue. I have included the latest file from the strophejs-plugins and placed it inside the jsxc/lib/ folder. How to start working on this issue.

https://github.com/strophe/strophejs-plugins/blob/master/mam/strophe.mam.v0.3.js

Now a file strophe.mam.js is in the folder jsxc/lib/. Now I want to include this functionality, for that I have created a file in jsxc/src/ named jsxc.lib.mam.js.

Please help me to get started. If you have any update about the issue please tell.

**Comment by sualko** [comment]
@singh1114 We are really happy that you want to work on this highly desired feature and if you have any questions, don't hesitate to write me an email. The proceeding could be as follows:

1) Fork the project
2) Create a new branch
3) Add the mam plugin as dependency similar to this [commit](https://github.com/jsxc/jsxc/commit/7e2a00a354654ace9849109e3626c27e1a10d643)
4) Create a pull request with the title "[WIP] Message Archive Management (XEP-0313)" so we can discuss features or other questions
5) Get to know [XEP-0313](http://xmpp.org/extensions/xep-0313.html)
6) Think about a policy when do you want to query the archive and write about it in your pr
7) e.g. use the `init.window.jsxc` event to load messages if a window is initialized

Happy coding!

**Comment by Cronetos** [comment]
I was working with Strophe and XEP-0313.
I don't know if helps you but I used a function to retrieve messages from the archive (mostly taken from http://stackoverflow.com/questions/32242088/strophe-mam-how-to-display-the-messages):

    getHistory('user1@jabber-dev.server', 50, '');
    
    function getHistory(userid, count, before){
        var q = {
          onMessage: function(message) {
            var id = message.querySelector('result').getAttribute('id');
            var fwd = message.querySelector('forwarded');
            var d = fwd.querySelector('delay').getAttribute('stamp');
            var msg = fwd.querySelector('message');
            var msg_data = {
                id:id,
                timestamp: (new Date(d)),
                timestamp_orig: d,
                from: Strophe.getBareJidFromJid(msg.getAttribute('from')),
                to: Strophe.getBareJidFromJid(msg.getAttribute('to')),
                type: msg.getAttribute('type'),
                body: msg.getAttribute('body'),
                message: Strophe.getText(msg.getElementsByTagName('body')[0])
            };
    
            var sender = Strophe.getBareJidFromJid(msg_data.from);
    
            $('#history').append(d + ': ' + sender + ' said: ' + msg_data.message + '<br>');
            return true;
          },
    
          onComplete: function(response) {
            console.log(response);
            $('#history').append('Completed.<br>');
            return true;
          }
        };
    
        $.extend(q, {'with': userid, 'before': before, 'max': count});
    
        connection.mam.query(Strophe.getBareJidFromJid(connection.jid), q);
    }

The only problem I had was to request multiple archives at the same time ( see http://stackoverflow.com/questions/41376131/strophe-mam-js-get-multiple-archives)

**Comment by sualko** [comment]
Please test https://github.com/jsxc/jsxc/releases/tag/3.2.0-nightly.1

**Comment by andrey-utkin** [comment]
Wow!

Have tested. In some cases, it works correct. In others, no history appears, and it sometimes doesn't even show a button "Load older messages" (i have tested fetching history with Conversations and it works). Or, just random messages sent by me to buddy appear. but no messages from buddy to me, and these messages are not the last ones.

XMPP server: Prosody trunk.

**Comment by sualko** [comment]
@andrey-utkin Can you try to describe in more detail in which cases this doesn't work, because otherwise I have no indication where the issue could be.

**Comment by andrey-utkin** [comment]
No apparent difference. Some buddies are from Spectrum gateways, but
some of these issues happen also with native Jabber buddies. Currently I
don't see any obvious differentiation.

**Comment by sualko** [comment]
@andrey-utkin Can you send some test credentials to klaus@jsxc.org? And please post your reviews/bugs/etc to the pr issue.
