### ISSUE TITLE
JSXC with jQuery noConflict?

### ISSUE THREAD

**Issue by bugfixxx** [jsxc/jsxc#151]
Hello!
We were looking for our perfect chat client and finally found jsxc - and it was love at first sight! Thank you at this point for the great software! :-)

I implemented jsxc core to our billing system. It was a little bit challenging but I got it running and even got autologin and avatar images working.
I now wanted to implement it into our CMS system (vTiger 6) as well - but got stuck.
vTiger uses jQuery & jQueryUI a lot - with different versions as jsxc does. I get tons of js-errors in firebug and I finally resigned getting it done...

My question:
Do you (or someone) have a jQuery noConflict version of jsxc?
(A version you can implement in another app which highly uses jQuery and does not conflict with it?)

Best regards, Harald

**Comment by sualko** [comment]
I'm glad to hear that you enjoy jsxc.

We already encapsulated the hole library, because SOGo uses prototype and therefore we had some conflicts with the dollar sign.

All you have to do is to replace the default <code>jQuery</code> to your custom jquery version variable. e.g.

```
var custom = $.noConflict(true);

(function($) {
  // jsxc code
}(custom)); // default: jQuery
```

You should do this for jsxc and the strophe.jingle library. Maybe you can also encapsulate the hole <code>jsxc.js</code> and <code>jsxc.dep.js</code> files with:

```
var custom = $.noConflict(true);

(function(jQuery) {
  // jsxc code
}(custom)); // default: jQuery
```

Please also note our [develop](https://github.com/jsxc/jsxc/tree/develop) branch, because we split the jsxc code into multiple files.

**Comment by bugfixxx** [comment]
Hello!
Thank you for your very fast answer.
Unfortunately, I'm not 100% sure which files I have to edit.
Is there a short docu about the folder structure?
In my installation I can find many duplicate files, e.g:
/jsxc/lib/strophe.js and /jsxc/build/lib/strophe.js

Can you give me a short list with files to be edited like mentioned above?
"strophe.jingle" is only here:
 /jsxc/build/lib/strophe.jingle/strophe.jingle.js (the other 3 files also?)

**Comment by sualko** [comment]
For major release we are working on some more detailed developer notes, but in a nutshell <code>build/</code> contains the last ready to use alpha/beta/release build and everything else is for developing.

The following files should be encapsulated depending on your configuration (which files do you include) : 

- jsxc.*.js
- jsxc.dep.js
- lib/strophe.caps.js
- lib/strophe.js
- lib/strophe.jingle/strophe.jingle.*.js

**Comment by sualko** [comment]
Can we close this?

**Comment by bugfixxx** [comment]
i did not get it working...
changed all of those files but always get js errors from my vTiger installation...
so i resigned implementing it :-/

**Comment by sualko** [comment]
Bad to hear. If you try it once again and you have more questions, please write me an email.

**Comment by bugfixxx** [comment]
Would be great to see a special download for this somedays :)

**Comment by xeux** [comment]
@bugfixxx can you point me in a documentation to achieve autologin and user avatars?
