### ISSUE TITLE
Ubuntu 14.04 ejabber2 login failing

### ISSUE THREAD

**Issue by Akendo** [jsxc/jsxc#153]
Hello I just installed today on a server jsxs in addtion to owncloud.

I followed your howto for the ejabberd server and installed all the script. But when login via owncloud no chat is appearing.
A look into the logs displays that ejabberd is receiving an error message:

    I(<0.650.0>:ejabberd_c2s:649) : ({socket_state,ejabberd_http_bind,{http_bind,<0.649.0>,{{127,0,0,1},35560}},ejabberd_http_bind}) Failed authentication 

While I'm able to login via owncloud  without any problem I can't via ejabberd.

    [20-Apr-2015 00:17:02 Europe/Berlin] OC: Authentication failure for tester1

Any suggestion?

**Comment by Akendo** [comment]
I'm running owncloud in version 8.0.2

Ubuntu 14.04 with PHP  5.5.9
ejabberd 2.1.11

`/var/log/ejabberd/oc.log` always returns error messages. 

I put ejabberd in debug mode and was able to see that the client is sending the correct password.
So assume there went soemthing wrong in the script or maybe in the php.ini?

`auth_ejabberd_oc.php`. 

Here is the debug log from `auth_ejabberd_oc.php`

	Apr 20 10:51:03 webservices php: [ejabberd-oc] Reading 43 bytes ... 
	Apr 20 10:51:03 webservices php: [ejabberd-oc] IN: auth:akendo:localhost:*******
	Apr 20 10:51:03 webservices php: [ejabberd-oc] GO: auth:akendo:localhost:********
	Apr 20 10:51:03 webservices php: [ejabberd-oc] data length is : 43
	Apr 20 10:51:03 webservices php: [ejabberd-oc] Command was : auth
	Apr 20 10:51:03 webservices php: [ejabberd-oc] Password is 
	Apr 20 10:51:03 webservices php: [ejabberd-oc] Command : auth:akendo:localhost:1fa68da1f9111f9b1e31c0e3e715db99 ==> 0 
	Apr 20 10:51:03 webservices php: [ejabberd-oc] RE: 
	Apr 20 10:51:03 webservices php: [ejabberd-oc] OUT: 2

And the result in the ejabber log is then:

	=INFO REPORT==== 2015-04-20 10:51:02 ===
	I(<0.635.0>:ejabberd_listener:281) : (#Port<0.1890>) Accepted connection {{127,0,0,1},58526} -> {{127,0,0,1},5280}

	=INFO REPORT==== 2015-04-20 10:51:02 ===
	I(<0.657.0>:ejabberd_http:146) : started: {gen_tcp,#Port<0.1890>}

	=INFO REPORT==== 2015-04-20 10:51:03 ===
	I(<0.635.0>:ejabberd_listener:281) : (#Port<0.1918>) Accepted connection {{127,0,0,1},58528} -> {{127,0,0,1},5280}

	=INFO REPORT==== 2015-04-20 10:51:03 ===
	I(<0.660.0>:ejabberd_http:146) : started: {gen_tcp,#Port<0.1918>}

	=INFO REPORT==== 2015-04-20 10:51:03 ===
	I(<0.659.0>:ejabberd_c2s:649) : ({socket_state,ejabberd_http_bind,{http_bind,<0.658.0>,{{127,0,0,1},58526}},ejabberd_http_bind}) Failed authentication for akendo@localhost

	=INFO REPORT==== 2015-04-20 10:51:33 ===
	I(<0.658.0>:ejabberd_http_bind:506) : Session timeout. Closing the HTTP bind session: "0f3ccbd822aafa25f85f6a2378d3e721bc9cb2c8"


I did run the `auth_oc_user.php` manuel and was able to verify my user.

I fetch the `auth_ejabberd_oc.php` and `auth_oc_user.php` from the github master branch.

	-rwxr-xr-x 1 ejabberd ejabberd  6388 Apr 19 23:13 auth_ejabberd_oc.php
	-rw-r--r-x 1 ejabberd ejabberd  1742 Apr 19 22:28 auth_oc_user.php

Also the user can access the owncloud folder. 

	grep ejabb /etc/group
	www-data:x:33:ejabberd
	ejabberd:x:118:

In the `ejabberd.cfg` I place the external auth:

     {auth_method, external}.
     {extauth_program, "/etc/ejabberd/auth_ejabberd_oc.php" }.

**Comment by v1r0x** [comment]
I had the same (or a similar) problem as you.

I don't know what fixed it, but I had missing rights for group in `/www/owncloud`. To fix this, I set x-bit for group (`chmod -R g+x /www/owncloud/`).

**Comment by Akendo** [comment]
Indeed that seem to fix the problem, the `/var/www/owncloud` was still owned by root.
I guess I missed a `/`. Thank you for the help!
