### ISSUE TITLE
How I can check if connection already exists?

### ISSUE THREAD

**Issue by sattellite** [jsxc/jsxc#154]
I added jsxc scripts to the main template for show roster on each page.
On first connection - all good. On go to the second page - jsxc reconnecting to xmpp server and buddies in roster are doubled. On go to the third page - jsxc reconnecting again and buddies in roster are tripled.
How i can check that the JSXC already have all needed data and it will be automatically restore connection?

In main template I have:

```javascript
jsxc.init({...});
jsxc.xmpp.login(...);
```

**Comment by sualko** [comment]
All you have to do is to call <code>init()</code>. It will check if it is able to reconnect and if this is the case it will do it.

Please also check our [example](https://github.com/jsxc/jsxc/tree/master/example).

**Comment by sualko** [comment]
duplicate of #155
