### ISSUE TITLE
How to integrate JSXC into own app?

### ISSUE THREAD

**Issue by sattellite** [jsxc/jsxc#155]
In my app I including all needed for jsxc scripts into main template. And added this code on each page:

```javascript
jsxc.init({...});
jsxc.xmpp.login(...);
```

For this solution I have hidden inputs with username and password on each page. This is very ugly and non-secure.
How I can automatize login to XMPP after login to app with same credentials on the server side?

Solution with dual-login in examples not for me. I don't want show roster for not authenticated users.

**Comment by sualko** [comment]
You only have to call <code>init()</code>. It will automatically detect if it is able to reconnect. Please also check our [example](https://github.com/jsxc/jsxc/tree/master/example) implementation.

**Comment by sualko** [comment]
Please open only one issue for one problem.

> I don't want show roster for not authenticated users.

What do you mean with that? Roster is only shown, if your xmpp server authenticates the user.

**Comment by sattellite** [comment]
> Roster is only shown, if your xmpp server authenticates the user.

With thah code on login page:

```javascript
    $(function() {
      var settings = {
         xmpp: {
            url: '/http-bind/',
            domain: 'myserver.tld',
            resource: 'web',
            overwrite: true,
            onlogin: true
         }
      };
    
      jsxc.init({
        loginForm: {
          form: '#form',
          jid: '#username',
          pass: '#password'
        },
        logoutElement: $('#logout'),
        checkFlash: false,
        rosterAppend: 'body',
        root: 'http://myserver.tld/jsxc',
        displayRosterMinimized: function() {
          return true;
        },
        otr: {
          debug: true,
          SEND_WHITESPACE_TAG: true,
          WHITESPACE_START_AKE: true
        },
        loadSettings: function(username, password) {
          return settings;
        },
        xmpp: {
          url:      settings.xmpp.url,
          resource: settings.xmpp.resource
        },
        carbons: {
          enable: true
        }
      });
    });
```

Roster is shown with "No connection! relogin"
![2015-04-28-114201_896x443_scrot](https://cloud.githubusercontent.com/assets/322910/7365824/52bb5e82-ed9c-11e4-9a1d-94e0db3ce6a6.png)

**Comment by sattellite** [comment]
Sorry, that was my mistake. I was not attentive. After removing unnecessary options and everything works as expected.

```javascript
displayRosterMinimized: function() {                                                                   
  return true;                                                                                            
}
```
