### ISSUE TITLE
Using SASL Anonymous Authentication (XEP-0175)

### ISSUE THREAD

**Issue by morlbo** [jsxc/jsxc#162]
hi,
how jsxc perform sasl anonymous login trough BOSH?

when a desired resource identifier is accepted by the server. 
eg: chosenuser@anoymous.domain.ltd

when s a desired resource identifier is not accepted, and server overrule the client assigning a resource identifier or when client asking the server to assign the resource identifier server provides? 
eg: 8a908e13e8eb68e06e5a0293723dab71938fd597@anoymous.domain.ltd

can jsxc authenticate with SASL ANONYMOUS when server informs the client of its full JID and scenario doesn't require a password?
tnx

**Comment by sualko** [comment]
Never tried it, but should be possible. Strophejs supports sasl anonymous and jsxc reads his jid from strophejs. Try to set <code>xmpp.jid = null</code> and <code>xmpp.password = null</code> as options  and call <code>jsxc.xmpp.login(null, null)</code>.

As mentioned this is untested and also unsupported. But I would welcome any feedback.

**Comment by sualko** [comment]
I close this, because of inactivity.

**Comment by opiums9** [comment]
Hi, I’m trying to make an anonymous connection to chats, with the possibility of calls, but I don’t have anything left, can you help me?
```
   // AJAX login
   $('#form2').submit(function(ev) {
      ev.preventDefault();

      source = $(this);
      $('#submit2').button('loading');

      jsxc.start($('#username2').val() + '@' + settings.xmpp.domain, null); //anonymus login + chat@conference.domain.tld
   });
```
