### ISSUE TITLE
Login dialog stays on forever on bad password

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#167]
When using the unified login feature in JSXC 2.0.0 for SOGo or ownCloud and entering a wrong password, the "Logging in…" dialog stays there forever. It works OK when the password is correct.

**Comment by sualko** [comment]
At least for owncloud, I can not confirm this. Please send me an email with the links to your installations.

**Comment by sualko** [comment]
I can confirm sogo.

**Comment by MarcelWaldvogel** [comment]
Today, I can no longer reproduce ownCloud. Ignore this part for now.
