### ISSUE TITLE
ownCloud Documents shows white bar when chat is not there

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#169]
- Log in to ownCloud using the "without chat" option
- Go to the Documents app
- Click on a document

Actual result:

- At the right-hand side, there is a white bar the size of the roster bar

Expected result:

- The Document app can use the entire width (which it actually does, if instead of "Login without chat" you first disable the JSXC app)

BTW: After clicking the "hidden roster bar" on the very right, an empty roster with the "not logged in" appears in place of the white bar. When clicking on the roster separator, the roster and the white bar are finally hidden, as expected.

**Comment by sualko** [comment]
Please test 4a7f89ceef6017b8eec8b0b0586b97209a927d00

**Comment by MarcelWaldvogel** [comment]
Works fine, thanks!
