### ISSUE TITLE
Hide Roster 

### ISSUE THREAD

**Issue by beccon4** [jsxc/jsxc#174]
Many parts of the UI fold quite nicely when not in use. It would be nice to be able to stow the roster to recover the horizontal screen space.

**Comment by sualko** [comment]
Please try to click on the left roster border.

**Comment by beccon4** [comment]
Yes - it works! I can stow the roster by clicking on the border and - most importantly - I can still receive text messages and answer calls. That's pretty cool.

Only two minor details for final user pleasure:
- please show an arrow in the middle of the border to actually tell the user that he can make room 
- even more important: please add an (user) option to start the roster in hidden mode. (not many users actually use the chat function all the time - and some don't know or don't want to stow and simply complain :-)  )

**Comment by sualko** [comment]
aedb263d2b2d0d977af442ea02f91513f303f17a adds an resize hint.

![hint](https://cloud.githubusercontent.com/assets/2974196/8353893/430a6e68-1b43-11e5-8108-e146a979b6d8.PNG)
