### ISSUE TITLE
No video on firefox 38.0 - sometimes

### ISSUE THREAD

**Issue by beccon4** [jsxc/jsxc#176]
Calling from Firefox 38.0 sometimes results in a gray canvas. The signalling and WebRTC should be ok though as it is posible to make snapshots which show images of the far side video. (so I suspect that the canvas gets above the image)  It is always the calling side that gets no image.

**Comment by sualko** [comment]
Please check your javascript console (e.g. ctrl+shift+i) for relevant error messages.

**Comment by programacion-web** [comment]
RTCIceServer.url is deprecated! Use urls instead. <unknown>
TypeError: this.peerconnection is null

**Comment by sualko** [comment]
I think this are two independent errors.

1. gray canvas
2. no connection

To 1: Sorry, I can not reproduce your error, but I will have a deeper look at the code. Maybe I find something.

To 2: Firefox changed a lot in there api (e.g. https://hacks.mozilla.org/2015/06/firefox-multistream-and-renegotiation-for-jitsi-videobridge/) and the developer of [strophe.jingle](https://github.com/ESTOS/strophe.jingle/) stopped their development. So I am currently looking for a solution to this, but it is unclear how long this takes.

**Comment by sualko** [comment]
Maybe we can replace strophe.jingle with Jingle.js from [otalk](https://otalk.org/).

**Comment by programacion-web** [comment]
Not only in firefox in chromiun I can not, any ideas?

chromium Version 43.0.2357.81 (64-bit), Linux
![screenshot_2015-06-12_00-03-43](https://cloud.githubusercontent.com/assets/7329190/8122876/1d5a3634-1086-11e5-9a15-9eda95d81beb.png)
![screenshot_2015-06-11_23-53-42](https://cloud.githubusercontent.com/assets/7329190/8122877/1dacb5b2-1086-11e5-947e-e8af3a80250e.png)
![screenshot_2015-06-11_23-52-20](https://cloud.githubusercontent.com/assets/7329190/8122878/1dc0863c-1086-11e5-8b75-63a50890f757.png)
![screenshot_2015-06-12_00-08-08](https://cloud.githubusercontent.com/assets/7329190/8122899/6b181d3c-1086-11e5-957b-54fc8f4db6ff.png)

**Comment by sualko** [comment]
I just want to let you know, that I am working on this right now, but it is complicated and frustrating...

**Comment by sualko** [comment]
I performed some cross tests with Chrome 42 and Firefox 38 with one NAT and everything seems to work now. If you still have an issue with video calls, please reopen this issue.
