### ISSUE TITLE
Jitsi Integration

### ISSUE THREAD

**Issue by beccon4** [jsxc/jsxc#177]
Chatting between Jitsi and Jsxc works, OTR also seems to work pretty good (I was able to authenticate the client and to send and receive messages - I had an "OTR error has occured" and unreadable messages - but the second attempt worked fine.

What doesn't work (and I don't know if it is supposed to do so) is calling.
- there is no way to call Jitsi from Jsxc - it simply says "no video telephony support"
- calling Jsxc from Jitsi results in an incoming call which I can answer - but that's it. It sticks there calling and showing the funny bubbles.
I know, that Jitsi implemented WebRTC compatibility.

**Comment by sualko** [comment]
Jitsi is only compatible with WebRTC if you use their Videobridge.

Direct calls are not possible, because Jitsi uses ZRTP and WebRTC DTLS-SRTP.

Videobridge will be hopefully supported/tested with #15.
