### ISSUE TITLE
Messages with accents (&Ccedil, for example) are bugging on the receiver

### ISSUE THREAD

**Issue by pedrobastosz** [jsxc/jsxc#180]
Hi, I already had problems with chartset but I resolved then all putting the attribute 'charset=UTF-8' both in JS and HTML (Thanks to you @sualko ). But I am still having problems when I send messages from JSXC. I tested other clients (PSi and Psi+) and it works fine (So its not a XMPP server related issue).

![error on message sent](https://cloud.githubusercontent.com/assets/11931753/7919540/695ec7e4-086f-11e5-8752-903bb4840676.png)

I have set some of jsxc.js code to set to brazilian language:

(...)
 $.i18n.init({
                lng: lang,
                fallbackLng: 'pt-BR',
(...)

Could you tell me what I am missing or doing wrong?

I'm using JSXC 2.0.0-beta2.

(EDIT: Forgot to thanks again for this worderful library)

**Comment by sualko** [comment]
Mh, I can not confirm your issue in oc or the example with Pidgin or Psi+ installed on Ubuntu and Mac.

![screen shot 2015-06-03 at 10 55 22](https://cloud.githubusercontent.com/assets/2974196/7956272/20cd24dc-09df-11e5-8a47-2f176d612d7d.png)

Can you send me two test accounts to klaus@jsxc.org?

**Comment by pedrobastosz** [comment]
Unfortunately I have not yet a public server, I'm testing on my own machine or through LAN. I'm using Windows 8.1 for both server and client. Tested in Chrome and Firefox. I have another task here in the company I work for this week, I'll be back on this next week and will be able to provide more useful information. Thanks for so short feedback.

**Comment by pedrobastosz** [comment]
Hi again. Today I have everything working from a server with Openfire in linux (Ubuntu Desktop 14.10) and it looks like the bug does not occur. I think it was a server side configuration mistake (I think it was the default language).

You can close this issue if you want. Thanks again.

**Comment by sualko** [comment]
I am glad to hear that everything works as expected.
