### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by kevinkk525** [jsxc/jsxc#181]
I followed the tutorial and got the service running, etc..
When I try to login from OC with correct OC credentials it does nothing. If insert a wrong password, it tells me that the password was incorrect. So what am I doing wrong? 
Obviously there is a connection to ejabberd and the authentication should work but I don't know where the error is. 

Running Owncloud 8.0.3, Ubuntu 14.04, ejabberd from ubuntu

**Comment by sualko** [comment]
Please post your jsxc settings from the oc admin page.

**Comment by kevinkk525** [comment]
BOSH URL: domain.de:5280/http-bind/
XMPP domain: domain.de
xmpp resource: 
TURN URL: numb.viagenie.ca
TURN USERNAME: username
Turn Credential: pass
Turn Secret:
Turn TTL:

of course domain.de and username/pass are different.

**Comment by sualko** [comment]
If you save these settings, does it say "BOSH server reachable"?

Please send some test credentials to klaus@jsxc.org.

**Comment by kevinkk525** [comment]
No it does not say that although I did all steps in "setup apache". I later even added the csp-policy with changed domain to owncloud config without an effect. 
It seems that OC can't communicate with ejabberd as nothing is written to the logs. 
The password answer I was talking about is probably the step inside OC before contacting ejabberd.
My domain.de:5280/http-bind/ is working correctly though.

If it helps I can send you some test credentials although I do not know what you hope to find in OC.
I could also send the config although it should be as in tutorial (except the domain change).

OC is only accessible by https while the domain.de:5280/http-bind/ is only accessible by http.

**Comment by sualko** [comment]
The problem is that your bosh server is not reachable because of an csp violation.

If you did the "setup apache" your BOSH url should be <code>/http-bind/</code>.

**Comment by sualko** [comment]
Any update?

**Comment by kevinkk525** [comment]
Sorry for the late update:
I figured out that the apache setup did not work because my server uses plesk, therefore i had to edit the /var/www/vhosts/system/httpd.conf file instead of the one in the tutorial.
after that the connection to the bosh server worked.

But now authentication fails all the time. I'm using the authentication scripts provided and edited the config for ext-auth. Log only sais failed authentication for  user@domain.
Is the domain important or can it be anything from localhost to github.com?

**Comment by kevinkk525** [comment]
Broke the problem down to permission problem. If I execute the auth_oc_user.php as user ejabberd I get a permission error reading my lib/base.php in the OC directory. weird thing is ejabberd belongs to the group psacln as well as the OC directory and everything in it. group psacln has full write/read/execute access to that directory but I still get a permission error: "PHP Fatal error: require_once(): Failed opening required 'var/www/vhosts/domain/lib/base.php' (include_path='.:') in /etc/ejabberd/auth_oc_user.php on line 32".

**Comment by kevinkk525** [comment]
Had to add ejabberd to the group psaserv and now the script auth_oc_user.php returns 1 in console executed as ejabberd. So this definitely works now, as well as the connection to the bosh server but I still get the message "wrong password?" in OC...
ejabberd.log: "Failed authentication for use@localhost"
oc.log: "Authentication failure for user"
Credentials were definitely correct and work in OC and console.

**Comment by kevinkk525** [comment]
any idea or not even reading this anymore? I still have that problem even with 8.1...

**Comment by sualko** [comment]
> any idea or not even reading this anymore?

Sorry, I forgot to reopen this issue.

Did you add your domain as host to your ejabberd config? Can you login with any other bosh capable xmpp client, like pidgin?

**Comment by kevinkk525** [comment]
Tried it today with pidgin: no success, with accounts like Kevin K@localhost it does not even work because pidgin has a problem with that, but using a user like kevin@localhost works for pidgin but it still does not login. I do get an "Authentication failure for kevin" in the oc.log.

I tried the exact setup on a raspberry pi, just to be sure it's not an issue with some plesk permission error or similar. BOSH URL reachable etc... login not possible, not from owncloud and not with pidgin, authentication failure all the time.

Executing following command line as ejabberd on both systems returned a 1 for correct credentials:
./auth_oc_user.php /var/www/owncloud/ test 1234

that should prove that authentication actually should work or did i get that wrong?
So the funny thing is looking at auth_ejabberd_oc.php in function checkpass() an entry to the log is only added if the return value is not 1. This script executes exactly the command i executed as user ejabberd and that returned 1. So maybe something wrong during getting the password and user? But that would not explain why this script works for many people...

messages.log says this:
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] Reading 25 bytes ... 
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] IN: auth:test2:localhost:*******
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] GO: auth:test2:localhost:********
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] data length is : 25
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] Command was : auth
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] Password is 
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] Command : auth:test2:localhost:81dc9bdb52d04dc20036dbd8313ed055 ==> 0 
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] RE: 
Jul 21 20:59:20 raspberrypi php: [ejabberd-oc] OUT: 2

Interesting is also that if i let pidgin not save my password it will ask for it but then takes forever logging in and the BOSH server terminates the connection after a while with no entry in oc.log or messages. If I let it save the password it gives a log entry.

**Comment by sualko** [comment]
Please try to remove the <code>md5</code> function in https://github.com/jsxc/jsxc.owncloud/blob/master/auth_ejabberd_oc.php#L158 to see, if the script gets the right password. 

Never thought about it, but this script should only work with SASL-PLAIN. If I have time I will investigate this.

**Comment by sualko** [comment]
You could also add the following to line https://github.com/jsxc/jsxc.owncloud/blob/master/auth_ejabberd_oc.php#L188

```
$this->logg("/etc/ejabberd/auth_oc_user.php '$oc_root' $user $pass");
```

**Comment by kevinkk525** [comment]
Thanks. It somehow fixed itself... more or less.
I changed the syslog location to write to the oc.log as this was somehow not working (or not findable anywhere) with plesk.
also executing "./auth_oc_user.php /var/www/vhosts/domain/owncloud/ test 1234" gave me an error that I am not allowed to write to the config file. As soon as I changed the write permission of config.php for the group, the command worked. and i was able to login. 
On my RaspberryPI it somehow fixed itself. I was playing around with additional logging when suddenly it worked. But reversing the changes and restarting ejabberd did not change anything...

Now the only questions i still have: If i have a username like "Kevin K" i can't log in.
Log says:
Jul-2015 13:34:26 Europe/Berlin] '[ejabberd-oc] ' Reading 37 bytes ... 
[22-Jul-2015 13:34:26 Europe/Berlin] '[ejabberd-oc] ' IN: auth:Kevin Koeck:localhost:*******
[22-Jul-2015 13:34:26 Europe/Berlin] '[ejabberd-oc] ' GO: auth:Kevin Koeck:localhost:********
[22-Jul-2015 13:34:26 Europe/Berlin] '[ejabberd-oc] ' data length is : 37
[22-Jul-2015 13:34:26 Europe/Berlin] '[ejabberd-oc] ' Command was : auth
[22-Jul-2015 13:34:27 Europe/Berlin] '[ejabberd-oc] ' Password is 1
[22-Jul-2015 13:34:27 Europe/Berlin] '[ejabberd-oc] ' Command : auth:Kevin K:localhost:8d5c79c1bfg73ce85652df374d900cb ==> 1 
[22-Jul-2015 13:34:27 Europe/Berlin] '[ejabberd-oc] ' RE: 
[22-Jul-2015 13:34:27 Europe/Berlin] '[ejabberd-oc] ' OUT: 2

That means the auth script works but ejabberd has  problem with a username that has a space in it and does not work correctly. Any way to fix this?

Another problem is with calls, i can call someone but the other person does not receive the call, both on firefox. Everything else now works. Thanks for your help, maybe you can add those special things neccessary for plesk users to your wiki.

**Comment by sualko** [comment]
Did you ever see an email address with a space? Same goes original for xmpp, but there is a XEP which adds this functionality. See #196.
