### ISSUE TITLE
Login not work with OTP Plugin

### ISSUE THREAD

**Issue by DarkPringles** [jsxc/jsxc#185]
For more security i have added the OTP Plugin (https://apps.owncloud.com/content/show.php/One+Time+Password+Backend?content=159196) to have the 2FA on my owncloud (8.0.4). Once i entered valid credentials and a one time password, the jsxc do not get any auth request and the chat is not visible.

Please try to fix it, to get this awsome plugin working with more security.
##

**Comment by sualko** [comment]
I think this is obsolete. See also #436
