### ISSUE TITLE
Latest release zip is invalid

### ISSUE THREAD

**Issue by sbrl** [jsxc/jsxc#187]
The latest release (2.0.1) is an invalid zip file. I had to repack it with 7-zip before my server would accept it.

**Comment by sbrl** [comment]
Upon further inspection it appears that the `settings.php` was invalid. This causes an empty settings.php to be extracted after repacking, thus making the app invisible to owncloud.

**Comment by sualko** [comment]
What do you mean with invalid and which zip file? I tried [1] and [2] on OSX and Ubuntu, but no error occurred.

[1] https://github.com/jsxc/jsxc.owncloud/releases/download/v2.0.1/ojsxc-2.0.1.zip
[2] https://apps.owncloud.com/content/show.php/?content=162257

**Comment by sbrl** [comment]
I am talking about [2] in that list. By invalid I mean that my ubuntu server spits out the following when I :

```
~$ unzip ojsxc.zip
Archive:  ojsxc.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ojsxc.zip or
        ojsxc.zip.zip, and cannot find ojsxc.zip.ZIP, period.
```

**Comment by sualko** [comment]
Sorry, I can not confirm your issue even on a ubuntu 12.04 server. Please try to redownload the archive.

**Comment by sbrl** [comment]
Oops! It looks like I forgot to follow redirects in cURL when I was downloading. Thanks anyway :)
