### ISSUE TITLE
Error Message: Deine Nachricht wurde nicht gesandt, da der Kontaktstatus einseitig ist.

### ISSUE THREAD

**Issue by alve89** [jsxc/jsxc#188]
I have no clue why this error message is appearing. I have (for testing purposes) two users in the same domain. I'm not able to send messages from A to B but I'm able to send messages from B to A.

**Comment by alve89** [comment]
Is it correct, that both contacts need to add them as contact into their contacts list?

**Comment by sualko** [comment]
I guess it is not, but jsxc requires it currently. I will check the documentation once again and if I find no reason for this limitation, I will close this issue with a patch.

**Comment by alve89** [comment]
Alright, thanks. Unfortunately I have a lot of trouble with adding contacts with your app. Also the alias name is not taken over into the contact list after re-adding someone (applying his request).

**Comment by sualko** [comment]
Can you open a new issue for that? It is easier to organise. Thanks.
