### ISSUE TITLE
Bug: Multiple contact add-requests are not show in ownCloud

### ISSUE THREAD

**Issue by alve89** [jsxc/jsxc#189]
If a person wants to add me into his contact list, I get the notification on the right bottom corner of the browser (a "1" with orange background). But if there are more than one requests, the newer than the first are not shown.

**Comment by alve89** [comment]
Update: Only in Chrome, not in Safari (both on Mac OS).

**Comment by sualko** [comment]
Do you get multiple requests from one person, or multiple?

**Comment by alve89** [comment]
Requests from multiple people.

**Comment by sualko** [comment]
Mh, I can not confirm this behaviour with the same setup. Please open your javascript console and look for errors.

**Comment by sualko** [comment]
Did you find any errors?

**Comment by alve89** [comment]
No, I didn't (in none of the browsers I used: Chrome, Firefox, Safari). It worked sometimes and sometimes not but there didn't appear any errors.

**Comment by sualko** [comment]
Do you have still problems with v2.1.0?

**Comment by alve89** [comment]
No, there are no problems yet. Thank you!
