### ISSUE TITLE
Bug: Adding new contacts doesn't work properly

### ISSUE THREAD

**Issue by alve89** [jsxc/jsxc#190]
Unfortunately I have a lot of trouble with adding contacts with your app (sometimes it is working, sometimes not). Also the alias name is not taken over into the contact list after re-adding someone (applying his request).

**Comment by sualko** [comment]
I can confirm that sometimes the alias is not saved correctly, but adding new contacts works every time for me. Please check your javascript console for warnings.

**Comment by sualko** [comment]
Did you get any additional information about the behaviour? Any steps to reproduce your error?

**Comment by sualko** [comment]
Please test our new beta release, maybe your issue is solved.

https://www.jsxc.org/blog/2015/07/21/v2.1.0-beta1-released/

**Comment by sualko** [comment]
How does it look like here? Is this issue still valid with 2.1.0?

**Comment by alve89** [comment]
No, I can't see problems here neither. Thank you.
