### ISSUE TITLE
BOSH server NOT reachable error despite BOSH server on same host.

### ISSUE THREAD

**Issue by Catmaster** [jsxc/jsxc#194]
I have my owncloud server on https://localhost/owncloud, and a prosody ssl BOSH server on https://localhost:5281/http-bind which is proxied via apache to https://localhost/http-bind.

Accessing https://localhost/http-bind gives no apache errors, and at least appears to work.
However, upon entering /http-bind/ into the settings at https://localhost/owncloud, the app throws the usual "BOSH server NOT Reachable..." error. 

If I had to guess, this has to do with some mismatched SSL certs as `curl -i https://localhost/http-bind/` yields `curl: (51) SSL: certificate subject name 'ubuntu.ok.cox.net' does not match target host name 'localhost'`.

Here is my prosody config, pardon the mess: http://hastebin.com/buyupihapi.lua
Here is my default-ssl.conf: http://hastebin.com/aloyasajew.hs

Please let me know if I can provide anything else to fix this issue, I've been trying forever.

**Comment by sualko** [comment]
Try the non-ssl bosh, because inter-device communication does not need to 
be encrypted.

**Comment by Catmaster** [comment]
It said that it required it to be on the same protocol, so I took that to mean that it required it to use SSL if the owncloud enforced https. In any case, non-ssl bosh does not work either.

As before, localhost/http-bind/ (non-SSL), is available and does not throw any apache errors when accessed directly. However, owncloud is continuing to say that the server is not reachable.

**Comment by sualko** [comment]
Please try an alternative client like pidgin to verify that bosh is working for you.

> It said that it required it to be on the same protocol

All proxy traffic in a ssl vhost is encrypted, so there is no problem with using the non-ssl bosh connection.

**Comment by Catmaster** [comment]
I'll let you know what I find. I tried ejabberd before but was having the same issue.

**Comment by sualko** [comment]
Did you find the error, or did you break off?

**Comment by Catmaster** [comment]
There wasn't an error, I was just being stupid. I changed the XMPP domain to localhost and the bosh server is now reachable.
