### ISSUE TITLE
Broken Authentication? -Owncloud 8.1 upgrade related?

### ISSUE THREAD

**Issue by Catmaster** [jsxc/jsxc#195]
I haven't had time to continue setting up jsxc on my server until just recently, but it seems that authentication is broken. For the record, I am using Prosody instead of ejabberd.

I enabled all of the required modules and put the required settings into Prosody, I even left the scripts in the ejabberd folder in case there were any path conflicts. This does not work however, and not only is unified authentication broken on Owncloud, but Prosody can't seem to create users via this method either. Running `sudo prosodyctl adduser dirtyspaceman@mystha.net` for example, yields: `Error while waiting for result from auth process: unknown error`.

As an alternative, I tried using internal_hashed as the login method. Despite this, authentication still fails via ojsxc.

BOSH is reachable (i solved my issue from before, I misunderstood what BOSH domain meant and I felt stupid so i closed the issue). Additionally, as per your advice from before, I used pidgin to double check if my bosh server is reachable, and it is.

It is worth noting (though you probably already know), that ojsxc is not considered "compliant" by owncloud 8.1. I ran the owncloud app code compliance checker and it gave me this: http://turl.ca/dswvmg

If you don't feel like clicking the link:

`Analysing /var/www/owncloud/apps/ojsxc/templates/settings.php
 1 errors
    line   22: == - is discouraged
Analysing /var/www/owncloud/apps/ojsxc/ajax/getsettings.php
 3 errors
    line    9: != - is discouraged
    line   26: == - is discouraged
    line   38: != - is discouraged
Analysing /var/www/owncloud/apps/ojsxc/ajax/getUsers.php
 2 errors
    line    6: OC_User - static method call on private class
    line    8: OC_User - static method call on private class
App is not compliant`

This may or may not lead to authentication issues, I have no idea.

Let me know if I can provide anything (such as my prosody.lua.cfg) to help solve this issue.

EDIT: I am closing this issue because I do not want to waste the dev's time trying to fix my problem. On the off chance that this isn't an isolated incident and someone else is having the exact same issue, feel free to email me at jakekasaf@gmail.com.

**Comment by sualko** [comment]
> but Prosody can't seem to create users via this method either

Did you try my ejabberd owncloud script? As the name suggests this only works with ejabberd.

> I used pidgin to double check if my bosh server is reachable, and it is.

If I got this right, you have solved our prosody authentication issue. Is this right?

> This may or may not lead to authentication issues, I have no idea.

I think not, because it is working on my test installation, but thank you for that hint.

> Let me know if I can provide anything ... to help solve this issue.

Please check your javascript console, prosody and owncloud log for relevant entries.

**Comment by Catmaster** [comment]
auth_ejabberd_oc.php correct? Yes, i've tried that. Prosody can run external ejabberd scripts as they are similar in structure. The main difference is that Prosody's authentication is line based while ejabberd's is length prefixed. As such, Prosody supplies an option to externally run ejabberd scripts. This is taken from my config:
`authentication = "external"
external_auth_protocol = "ejabberd"
external_auth_command = "/etc/ejabberd/auth_ejabberd_oc.php"`

No, prosody authenticates fine, it is JSXC that isn't working. I can connect to my prosody server with pidgin, but not with JSXC.

I have checked my prosody and owncloud log repeatedly trying to solve this. The only relevant thing to pop up was "failed authentication" in the owncloud log. I'll try looking at the javascript console but I'm not hopeful that I'll find anything.

**Comment by sualko** [comment]
Please send some test credentials to klaus@jsxc.org.

**Comment by Catmaster** [comment]
Sent.
