### ISSUE TITLE
[XEP-0106] Jid Escaping (JSXC won't work, if a JID contains U+0040 (@))

### ISSUE THREAD

**Issue by Sebijk** [jsxc/jsxc#196]
How to reproduce this problem:

Add a jid that contains \40. JSXC show this as an empty contact. if you reload the site, the contact list is empty.

---

Wie kann man das Problem reproduzieren:

Man fügt eine JID hinzu, die \40 enthält. JSXC zeigt diesen Kontakt leer an (ohne Nutzername). Wenn man die Seite dann neulädt, ist die ganze Kontaktliste aufeinmal leer.

Wenn man Transports nutzt, könnte dies ärgerlich sein.

**Comment by sualko** [comment]
JSXC does not implement [XEP-0106](http://xmpp.org/extensions/xep-0106.html), but I leave this issue open until it does.

If you have time and some javascript skills, please feel free to implement it.

**Comment by AdamN1** [comment]
Hi,
from what i understood \40 means character @ 
So without support for XEP-0106 nobody who uses xmpp transport can use jsxc client,
am i right?

**Comment by sualko** [comment]
I would say you can not use transports which use non-allowed characters.

**Comment by AdamN1** [comment]
user@transport@xmpp.domena.pl isn't this default format for transport ?
i have own xmpp server(prosody) i'm doing something wrong?

**Comment by Sebijk** [comment]
Hello,

Default is legacylogin@transport.xmppdomain.tld. And this works.

But some Networks (like StudiVZ/Lokalisten/classic Facebook XMPP) have as login an emailaddress. And this have the format email\40domain.tld@transport.xmppdomain.tld.

**Comment by sualko** [comment]
According to [XEP-0100](http://www.xmpp.org/extensions/xep-0100.html#addressing) this is not required.

> i'm doing something wrong?

No, we only have to implement xep-0106.

---

@Sebijk 32 seconds... :D

**Comment by Sebijk** [comment]
> So without support for XEP-0106 nobody who uses xmpp transport can use jsxc client,
am i right?

If the user use an xmpp transport, which have the format email\40domain.tld@transport.xmppdomain.tld, the user cannot use JSXC (only a few contacts will show after login and empty contact list by reload or navigating).

**Comment by AdamN1** [comment]
my contact has the form -100004873180883\40chat.facebook.com@xmpp.justnet.pl
i think that '-100004873180883\40chat.facebook.com' this is conntact and this is "xmpp.justnet.pl" transport address

**Comment by sualko** [comment]
Please try to replace the string in <code>jsxc.js</code> or <code>jsxc.min.js</code> according to https://github.com/jsxc/jsxc/commit/087e5c819cf8d425e8c69b4ac5933c776ce34bf2

**Comment by AdamN1** [comment]
works great
