### ISSUE TITLE
invalid SID 

### ISSUE THREAD

**Issue by BenJaziaSadok** [jsxc/jsxc#197]
I'm getting invalid SID error for an unknown reason. This is a little frequent.
Any possible suggestion?

**Comment by sualko** [comment]
Please give some more information. Which version? In which environment (owncloud, sogo, ...)? Where do you get this error? What does your xmpp log say? Which xmpp server are you using?

**Comment by BenJaziaSadok** [comment]
Jsxc core on Openfire 3.10.0, The xmpp log did not show any error

**Comment by sualko** [comment]
Sorry, but I can not help without more information.

> Which version? In which environment (owncloud, sogo, ...)? Where do you get this error?

What does frequent mean? What do you do before you get this error?

**Comment by sualko** [comment]
Maybe strophe/strophejs#76 is related.
