### ISSUE TITLE
Annoying linebreak in files app

### ISSUE THREAD

**Issue by davodego** [jsxc/jsxc#198]
With activated xmpp app the path in files app has an annoying linebreak.
The "New" and Upload button jumps in the middel of the screen to an new line. The path follows when its is in the half of the screen.
Then the files path is behind the buttons.

With deactivatet xmpp app all goes well.

Config:
OC 8.1
xmpp app 2.0.1
php 5.4
Debain 7 server

Has somebody any idea to solve this?
![oc_xmpp_filespath](https://cloud.githubusercontent.com/assets/6584744/8867997/157fbe08-31d2-11e5-96bf-3aeb3d73154b.jpg)

**Comment by sualko** [comment]
Please try the above commit and close this issue if it satisfies you.

**Comment by davodego** [comment]
Works, thanks.

**Comment by davodego** [comment]
No, sorry, it was a misstake. I did't noticed that the sidebar isn't now visible anymore.
I made the changes in the ojsxc.js. The annoying linebreak is gone but the xmpp sidebar too.
So it dont work

**Comment by sualko** [comment]
Can you post a screenshot?

**Comment by davodego** [comment]
![oc_xmpp_filespath-2](https://cloud.githubusercontent.com/assets/6584744/8872054/4786a68c-31fa-11e5-9b71-62cbfa602ef2.jpg)
My ojsxc.js ist differnt from this one in the link.
line 24,25,25 is

24 */
25function onRosterToggle(event, state, duration) {
26 "use strict";

I found the parts shonw in "fix control width" and changed them.

**Comment by sualko** [comment]
You have to change it at two positions. Please also try to logout and in
again.

**Comment by davodego** [comment]
Sorry again. I was to fast. I commented the old lines with "//" out. But I forget line 24, so xmpp was disabled completly. 
When I searched for the two positions I noticed and commented the old line 24 out.
It works now.
Thanks again and closed.
