### ISSUE TITLE
ojsxc: "TypeError: event.target.closest is not a function apps.js:61"

### ISSUE THREAD

**Issue by anonimal** [jsxc/jsxc#206]
When clicking on any of the wheel icons, attempting to change presence status, or attempting to add an emoticon, the following error is thrown:

<code>TypeError: event.target.closest is not a function apps.js:61</code>

As a result, there is no longer any functionality with those items: they will simply not respond.

Firefox 31.8.0
ojsxc v2.1.0

**Comment by anonimal** [comment]
Note: this does not appear to be an issue with the regular (non-ownCloud) implementation of jsxc.

**Comment by sualko** [comment]
<code>apps.js</code> belongs to owncloud core, so this error should also occur if you click on the owncloud menu. Is that right?

Why do you use such an old ff?

**Comment by sualko** [comment]
Should be fixed with owncloud/core#17490. Please test and close this issue on success.

**Comment by anonimal** [comment]
Ah, I remember overlooking that OC menu issue a little while ago, thanks for pointing that out.

@sualko I should've mentioned, this is with <a href="https://www.torproject.org/">Tor Browser</a> 4.5.3 and that's why the FF build is an older one.

Ok, now tested with a fresh pull of OC and jsxc tagged v2.1.0: works great! Thanks.
