### ISSUE TITLE
NS_ERROR_NOT_AVAILABLE

### ISSUE THREAD

**Issue by souperk** [jsxc/jsxc#208]
Hello, I have already sent an relative e-mail to the mailing list, but I thought it may be inactive so I decided to post here also.

I am trying to integrate jsxc to smf (http://www.simplemachines.org/).

With the help of my little javascript and php knowledge I managed to write the following code.

	if(!empty($user_settings['passwd'])) {
	echo '<script>  
	
	if(!jsxc.xmpp.conn)
	{
        jsxc.init({xmpp: {url:\'/http-bind\' } , root:\'/forum\'});
        jsxc.xmpp.login(\''. $user_settings['member_name'] . '@poke.lagos.p4u.gr\', \'' . $user_settings['passwd'] . '\');
	}</script>';
 </script>

Using firebug i noticed that most of the times I reload there is entry in console about an NS_ERROR_NOT_AVAILABLE in jsxc.dep.js . The times, it does not show up it tries to connect to bosh and stops at Connected = null . I have tested the connection with the example you provided (after I altered example.js) and it works fine.

I think the problem is at the "if(!jsxc.xmpp.conn)" I use it check if there is already another connection active. Is there a better way to do so?

**Comment by sualko** [comment]
Today I received your message as a bounce. Not completely sure why this happened, but our mailing list is definitively not inactive.

You have to call <code>jsxc.init</code> even if you have a valid connection, otherwise jsxc will not work. Please post also the complete error message including line number.

**Comment by souperk** [comment]
I apologise for my impatience and thank you for the fast reply!

I changed the code as recommended (I cleared the php code to make it easier to read):
```javascript
        jsxc.init({xmpp: {url:'/http-bind' } , root:'/forum/jsxc'});
        if(!jsxc.xmpp.conn)
        {
                jsxc.xmpp.login(jid, password); 
        }  
```
The problem still persists. Exact console output is 

```
This appears to be Firefox                        jsxc.dep.js (line 24263)
NS_ERROR_NOT_AVAILABLE: 
_context.drawImage(_img, 0, 0, _w, _h);           jsxc.dep.js (line 32979)
```
message is ```NS_ERROR_NOT_AVAILABLE: _context.drawImage(_img, 0, 0, _w, _h);``` in jsxc.dep.js line 32979. Note every sometime (i didn't manage to count but it should be around 2 minutes) the console log is something like 
```
This appears to be Firefox jsxc.dep.js (line 24263)
New connection jsxc.min.js (line 14)
CONNECTING: null jsxc.min.js (line 14)
POST http://poke.lagos.p4u.gr/http-bind 200 OK 4ms	jsxc.dep.js (line 4460)
POST http://poke.lagos.p4u.gr/http-bind 200 OK  6ms	jsxc.dep.js (line 4460)
POST http://poke.lagos.p4u.gr/http-bind 200 OK  2ms	jsxc.dep.js (line 4460)
POST http://poke.lagos.p4u.gr/http-bind 200 OK  2ms	jsxc.dep.js (line 4460)
POST http://poke.lagos.p4u.gr/http-bind 200 OK  3ms	jsxc.dep.js (line 4460)
POST http://poke.lagos.p4u.gr/http-bind 200 OK  3ms	jsxc.dep.js (line 4460)
CONNECTED: null jsxc.min.js (line 14)
```

Also, I tested with chromonium browser and works fine.

**Comment by sualko** [comment]
Do you have a favicon?

**Comment by souperk** [comment]
SMF uses by default a favicon. I am trying now to disable it. I will report back when I am able to disable and test.

Also, I note that chrome seems to work.

**Comment by sualko** [comment]
I thought this error would appear, because you have no favicon.

Definitely the error is thrown from https://github.com/ejci/favico.js/, maybe you can open there an issue and ask if they have any idea.

**Comment by souperk** [comment]
Actually I fixed it by changing the line 32979 of jsxc.dep.js from

```javascript
_context.drawImage(_img, 0, 0, _w, _h);
```
to

```javascript
_img.onload = function(){_context.drawImage(_img, 0, 0, _w, _h);};
```

Also, is _img.onload set somewhere else? Because, if so I need to use some kind of eventlistener (It is also better programming practice but anyway).

**Comment by sualko** [comment]
Please open upstream [ejci/favico.js](https://github.com/ejci/favico.js/) a pull request, because jsxc.dep.js concatenates only all dependencies.

**Comment by souperk** [comment]
Ok I created an issue recommending the change. I will close this issue. 

Thank you very much for your help!
