### ISSUE TITLE
All users appear offline Owncloud 8.1.1 Ejabberd

### ISSUE THREAD

**Issue by MelonSmasher** [jsxc/jsxc#211]
All users appear to be offline, though messages are still sent.

Using owncloud 8.1.1 and ejabberd, to get around the CSP issue with 8.1.1 I am proxying the bosh url through nginx. Any ideas?

**Comment by MelonSmasher** [comment]
Just realized that a user will not get the contact request until they've logged out and then logged in. Is this expected behaviour?

**Comment by sualko** [comment]
> Is this expected behaviour?

Definitely not, but this fits to your offline problem. Can you describe it in more detail please? Does this occur for every user? What happens if you change your presence? Did you try it with an other xmpp client, like pidgin? Which jsxc and browser version do you use?

**Comment by sualko** [comment]
I could  reproduce your error on a new installation. The initial presence stanza is not send, so you do not get any contact request.
