### ISSUE TITLE
Owncloud and integration of external users (eg. LDAP)

### ISSUE THREAD

**Issue by jperville** [jsxc/jsxc#213]
I am running owncloud 8.1 using the LDAP backend for authentication, and trying to make owncloud jsxc (version 2.1.2) work with my setup.

After reading #171, I configured ejabberd to use LDAP authentication first, then fallback to external authentication. This allowed my owncloud LDAP users to authenticate successfully and see the ojsxc tab in their interface (in /var/log/ejabberd/oc.log I can see lines like this `/etc/ejabberd/auth_oc_user.php '/var/www/owncloud' 'testuser' 'XXXXX'` returning '1')

Then I tried to add a first contact by entering the LDAP username (eg. 'myuser') in the Username field of the Add Contact box. I noticed that owncloud autocompleted the username and replaced it with an UUID which is the internal "name" of my LDAP user inside the owncloud database (as seen when in the "users" management interface as owncloud administrator); owncloud configured the LDAP username I first typed as the contact's "alias", which I thought was correct behavior for a newbie user like me.

However, I could not send any messages to any user, even to my own, currently logged user. All attempts at sending message would fail with the following error message in the chat box: `Your message was not send because of an error`.

In `/var/log/syslog` I could read:
```
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] Reading 66 bytes ... 
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] IN: isuser:0b4c2989-ca83-48f3-a4e2-bd8012e315a7:*******
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] GO: isuser:0b4c2989-ca83-48f3-a4e2-bd8012e315a7:********
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] data length is : 66
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] Command was : isuser
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] Command : isuser:0b4c2989-ca83-48f3-a4e2-bd8012e315a7 ==> 1 
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] RE: 
Aug 30 07:57:05 xxx-vm php: [ejabberd-oc] OUT: 2
```

After checking the source of `auth_ejabberd_oc.php`, I figured out that the jabber client is really trying to send a message to user `0b4c2989-ca83-48f3-a4e2-bd8012e315a7`, and that the external script was being called to check for existence of this UUID user. I then modified the external authenticator script to uppercase the user name to `0B4C2989-CA83-48F3-A4E2-BD8012E315A7` and voila, the messages are sent successfully (in other words, `/etc/ejabberd/auth_oc_user.php '/var/www/owncloud' 'test' '0b4c2989-ca83-48f3-a4e2-bd8012e315a7'` returns '1'). But somehow, my LDAP users always remain offline (even if I log as them; no notification is ever received).

Thinking about it more, my external LDAP owncloud users never login to the ejabberd using their owncloud UUID (they authenticate with their LDAP user name). So to make the chat work, I just need to add the contacts in the Add Contact box using the `myuser@owncloud.domain` form. And this works, my users gets notifications and can exchange messages.

Now my question: is there any way to NOT have the "Add Contact" windows replace the logins I typed with the owncloud user UUID but with login@domain instead? This behavior, even if it "makes sense" (for owncloud internal users) is very difficult to explain to computer-illiterate users.

Thank you in advance.

**Comment by sualko** [comment]
>  I configured ejabberd to use LDAP authentication first, then fallback to external authentication.

Why? I recommend to use ldap directly for performance and stability reasons.

> is there any way to NOT have the "Add Contact" windows replace the logins I typed with the owncloud user UUID but with login@domain instead?

There is currently no option for that, but you can just remove the complete <code>getUsers</code> function from [ojsxc.js#L232](https://github.com/jsxc/jsxc.owncloud/blob/master/js/ojsxc.js#L232).

**Comment by jperville** [comment]
Thanks for quick answer @sualko .. External auth script was for playing but in the end I will use LDAP only. Will also try to disable the auto completion feature as you suggest.

**Comment by sualko** [comment]
Please close this issue, if the fix works for you. Have fun.

**Comment by jperville** [comment]
I ended up writing the following patch:

```patch
diff --git a/js/ojsxc.js b/js/ojsxc.js
index 49d0792..078ffca 100644
--- a/js/ojsxc.js
+++ b/js/ojsxc.js
@@ -242,7 +242,9 @@ $(function() {
 
          return ret;
       },
-      getUsers: function(search, cb) {
+      // Julien: disable getUsers callback, autocomplete is useless and broken
+      // with LDAP external users; see https://github.com/jsxc/jsxc/issues/213
+      xgetUsers: function(search, cb) {
          $.ajax({
             type: 'GET',
             url: OC.filePath('ojsxc', 'ajax', 'getUsers.php'),
```

Thank you for the suggestion to disable the autocomplete hook @sualko .
