### ISSUE TITLE
UX: Chat settings dialog

### ISSUE THREAD

**Issue by mdik** [jsxc/jsxc#215]
I have problems understanding the Settings dialog of the chat side bar:

* On login: On login what?
* Priority: What does "0" mean?
* Carbon copy: What does that mean?

**Comment by thetaxevader** [comment]
bump!

I agree, clearer settings!

**Comment by sualko** [comment]
Done.

![screenshot from 2016-01-13 14 49 08](https://cloud.githubusercontent.com/assets/2974196/12296114/ed73003e-ba05-11e5-8eee-ad5621817891.png)
