### ISSUE TITLE
Some pictures & emoticons not loading

### ISSUE THREAD

**Issue by masscream** [jsxc/jsxc#218]
Hello,
I've been using ojsxc in combination with OC some time, but since some moment (I believe it had to be some upgrade of OC or ojsxc) some of the pictures e.g. buttons, control panels and emoticons disappeared. Although they do not display, their blank place is still functional as they would normally be there. I checked the file locations on a server - all emoticons are on their places and I was not moving, changing nor deleting any of directories or configuration files. Also the rights and owner of the files are the same but despite that some are appearing and some not. Has anybody same issue? I've been using OC 8.1.1 and ojsxc 2.1.2 Thanks

http://i61.tinypic.com/dzk0eu.png

**Comment by sualko** [comment]
This is maybe related to #201, please check and post the output of your js console (ctrl+shift+i).

**Comment by sualko** [comment]
Any update?

**Comment by masscream** [comment]
Hello,
 
no, not really. I agree with your opinion that it may be related with the other issue with OC 8.1. Nowadays the problem still persists.
 
T.
 
______________________________________________________________
> Od: Klaus <notifications@github.com>
> Komu: "jsxc/jsxc" <jsxc@noreply.github.com>
> Datum: 17.09.2015 10:56
> Předmět: Re: [jsxc] Some pictures & emoticons not loading (#218)
>
Any update?

**Comment by sualko** [comment]
What is the output of your js console?

**Comment by masscream** [comment]
Where do I find such thing? OC log?
 
______________________________________________________________
> Od: Klaus <notifications@github.com>
> Komu: "jsxc/jsxc" <jsxc@noreply.github.com>
> Datum: 17.09.2015 12:03
> Předmět: Re: [jsxc] Some pictures & emoticons not loading (#218)
>
What is the output of your js console?

**Comment by sualko** [comment]
It the developer console of your browser. Try to press ctrl+shift+i.

**Comment by masscream** [comment]
It took me some time to find out how it exactly works, on the JS page there are no errors / no info contained, but on CSS there is something. See attached.
 
______________________________________________________________
> Od: Klaus <notifications@github.com>
> Komu: "jsxc/jsxc" <jsxc@noreply.github.com>
> Datum: 17.09.2015 12:22
> Předmět: Re: [jsxc] Some pictures & emoticons not loading (#218)
>
It the developer console of your browser. Try to press ctrl+shift+i.

**Comment by sualko** [comment]
You either send the attachment to klaus@jsxc.org or you have to use the github webinterface to publish your attachment.

**Comment by masscream** [comment]
wow, I got even more errors after I reloaded the page...
 
______________________________________________________________
> Od: Klaus <notifications@github.com>
> Komu: "jsxc/jsxc" <jsxc@noreply.github.com>
> Datum: 17.09.2015 12:34
> Předmět: Re: [jsxc] Some pictures & emoticons not loading (#218)
>
You either send the attachment to klaus@jsxc.org <klaus@jsxc.org> or you have to use the github webinterface to publish your attachment.
—
Reply to this email directly or view it on GitHub <https://github.com/jsxc/jsxc/issues/218#issuecomment-141039092>.


Unknown pseudo-class or pseudo-element 'full-screen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3628:4
Unknown pseudo-class or pseudo-element 'full-screen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3632:6
Unknown pseudo-class or pseudo-element '-webkit-full-screen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3635:4
Unknown pseudo-class or pseudo-element '-ms-fullscreen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3645:4
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3650:4
Unknown pseudo-class or pseudo-element '-webkit-full-screen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3654:6
Unknown pseudo-class or pseudo-element '-ms-fullscreen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3658:6
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector.
 jsxc.oc.css:3660:6
Error in parsing value for 'width'.  Declaration dropped.
 jsxc.oc.css:3826:9
Unknown property '-moz-box-shadow'.  Declaration dropped.
 multiselect.css:22:16
Unknown property '-moz-border-radius'.  Declaration dropped.
 jquery-tipsy.css:5:52
Unknown property 'zoom'.  Declaration dropped.
 chosen.css:6:6
Expected declaration but found '*'.  Skipped to next declaration.
 chosen.css:7:2
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:17:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 chosen.css:26:10
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:27:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:28:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:30:20
Unknown property '-moz-border-radius'.  Declaration dropped.
 chosen.css:33:23
Unknown property '-moz-background-clip'.  Declaration dropped.
 chosen.css:35:25
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:40:20
Error in parsing value for 'background'.  Declaration dropped.
 chosen.css:103:61
Error in parsing value for 'background'.  Declaration dropped.
 chosen.css:104:61
Error in parsing value for 'background'.  Declaration dropped.
 chosen.css:106:61
Unknown property '-moz-border-radius'.  Declaration dropped.
 chosen.css:117:23
Unknown property '-moz-background-clip'.  Declaration dropped.
 chosen.css:119:25
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:133:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:134:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:136:20
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:167:20
Unknown property '-moz-border-radius'.  Declaration dropped.
 chosen.css:175:23
Unknown property '-moz-background-clip'.  Declaration dropped.
 chosen.css:177:25
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 chosen.css:181:10
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:182:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:183:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:185:20
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:188:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 chosen.css:200:10
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:201:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:202:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:204:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:205:20
Expected color but found 'top'.  Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:206:36
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 chosen.css:259:10
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:260:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:261:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:263:20
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:317:20
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:324:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 chosen.css:327:10
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:328:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:329:20
Error in parsing value for 'background-image'.  Declaration dropped.
 chosen.css:331:20
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped.
 chosen.css:335:32
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped.
 chosen.css:336:32
Unknown property '-moz-box-shadow'.  Declaration dropped.
 chosen.css:349:20
Error in parsing value for 'background'.  Declaration dropped.
 chosen.css:389:62
Error in parsing value for 'background'.  Declaration dropped.
 chosen.css:390:62
Error in parsing value for 'background'.  Declaration dropped.
 chosen.css:392:62
Unknown property '-moz-box-shadow'.  Declaration dropped.
 jquery.miniColors.css:11:16
Unknown property '-moz-border-radius'.  Declaration dropped.
 jquery.miniColors.css:14:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 jquery.miniColors.css:73:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 jquery.miniColors.css:84:19
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.miniColors.css:113:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 versions.css:21:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 versions.css:33:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 firstrunwizard.css:25:9
Expected 'none', URL, or filter function but found '"alpha(opacity=40)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:156:9
Expected 'none', URL, or filter function but found '"alpha(opacity=75)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:163:9
Expected 'none', URL, or filter function but found '"alpha(opacity=85)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:169:9
Expected 'none', URL, or filter function but found '"alpha(opacity=90)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:176:9
Expected 'none', URL, or filter function but found '"alpha(opacity=40)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:185:9
Expected 'none', URL, or filter function but found '"alpha(opacity=75)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:220:9
Expected 'none', URL, or filter function but found '"alpha(opacity=90)"'.  Error in parsing value for 'filter'.  Declaration dropped.
 jquery.mCustomScrollbar.css:227:9
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:118:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:119:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:121:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:122:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:145:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:146:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:148:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:149:13
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:247:19
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:256:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:257:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:259:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:260:13
Error in parsing value for 'background-image'.  Declaration dropped.
 mediaelementplayer.css:266:19
Error in parsing value for 'background-image'.  Declaration dropped.
 mediaelementplayer.css:267:19
Error in parsing value for 'background-image'.  Declaration dropped.
 mediaelementplayer.css:268:19
Error in parsing value for 'background-image'.  Declaration dropped.
 mediaelementplayer.css:270:19
Unknown property '-moz-background-size'.  Declaration dropped.
 mediaelementplayer.css:273:21
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:292:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:293:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:295:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:296:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:304:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:305:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:307:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:308:13
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:320:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:358:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:417:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:428:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:470:19
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:492:19
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:496:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:497:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:499:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:500:13
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:514:19
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:518:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:519:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:521:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:522:13
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:553:19
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:614:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:615:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:617:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:618:13
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 mediaelementplayer.css:620:9
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:642:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:643:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:645:13
Error in parsing value for 'background'.  Declaration dropped.
 mediaelementplayer.css:646:13
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
 mediaelementplayer.css:648:9
Unknown property '-moz-border-radius'.  Declaration dropped.
 mediaelementplayer.css:806:19
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 upload.css:36:73
Unknown property 'user-select'.  Declaration dropped.
 upload.css:75:12
Unknown property 'user-select'.  Declaration dropped.
 upload.css:86:12
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 mobile.css:43:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 mobile.css:50:9
Error in parsing value for 'display'.  Declaration dropped.
 mobile.css:74:10
Error in parsing value for 'display'.  Declaration dropped.
 mobile.css:76:10
Error in parsing value for 'display'.  Declaration dropped.
 mobile.css:77:10
Unknown property '-moz-box-shadow'.  Declaration dropped.
 files.css:79:16
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:159:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:170:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:205:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:422:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:433:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:451:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:519:8
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:571:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:589:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:598:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:605:9
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.
 files.css:660:9
Unknown property 'appearance'.  Declaration dropped.
 files:1:7167
Unknown property '-moz-border-radius'.  Declaration dropped.
 files:1:14233
Error in parsing value for 'background-image'.  Declaration dropped.
 files:1:19546
Unknown property '-moz-box-shadow'.  Declaration dropped.
 files:1:21595
Unknown property '-moz-box-shadow'.  Declaration dropped.
 files:1:21850
Unknown property '-moz-box-shadow'.  Declaration dropped.
 files:1:22803
Error in parsing value for 'height'.  Declaration dropped.
 files
Error in parsing value for 'top'.  Declaration dropped.
 files

**Comment by sualko** [comment]
I see nothing that explains your issue. Can you send me some test credentials to klaus@jsxc.org?

**Comment by sualko** [comment]
I can confirm your issue and it is related to #201.
