### ISSUE TITLE
Favico.js not found

### ISSUE THREAD

**Issue by LEDfan** [jsxc/jsxc#219]
I'm using dev version of JSXC in ownCloud. I have run `git submodule update --recursive` and `grunt` inside the js/jsxc directory. However the favico.js code isn't found.

I can't find the file in this repository either but it is defined in the `dep.js` file. Manually placing the `favico.js` file inside `js/jsxc/lib/favico.js` fixs the problem.

**Comment by sualko** [comment]
Try <code>bower install</code>.

**Comment by LEDfan** [comment]
Solves the problem... Thanks again.
