### ISSUE TITLE
Broken IE logins on version 2.1.2 with OC 8.1

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#221]
Unfortunately my users are reporting broken IE logins again with version 2.1.2. I'm running OC 8.1 and can confirm this happens on IE 8 and 10. The Owncloud login box is broken (unclickable), and the link to log in without chat is missing. The tests were done with a fresh install of Windows 7 in a virtual machine that had no other modifications done.  That should rule out any cookie or caching issues.  

My recommendation is to move the link beside the normal button and make that one a "log in WITH chat" button, and leave the normal button untouched so that if you break IE again, IE users can still log in to the rest of OC. I also think it would look nicer with 2 buttons rather than a button and a link.

Hoping it's not troublesome to fix this issue.

Anyway, thanks for a fantastic product!  It has become a cornerstone in my owncloud deployment!

**Comment by sualko** [comment]
The emulator of IE11 shows only some silly output. Can you please check your js console (press F12) for any erros?

**Comment by Luticus** [comment]
Absolutely, I'll have that to you in just a second. I'm installing updates to Windows at the moment so It'll take just a minute while it reboots :)

**Comment by Luticus** [comment]
Expected identifier, string or number  jsxc.dep.js?v=815db9e3c6b8a0d7bf23552a85a64317, line 6879 character 2
  Expected identifier  jsxc.js?v=815db9e3c6b8a0d7bf23552a85a64317, line 5038 character 30
  'jsxc' is undefined  ojsxc.js?v=815db9e3c6b8a0d7bf23552a85a64317, line 130 character 4


That's what I get from the js console.

**Comment by sualko** [comment]
Ok, same silly output. The line 6879 looks like this:

```
/**
	 * Delete the given entry for roomJid.
	 *
	 * @param {string} roomJid - The JabberID of the chat roomJid you want to remove
	 * @param {function} [success] - Callback after success
	 * @param {function} [error] - Callback after error
	 * @param {boolean} [notify=false] - True: notify all subscribers
	 */
	delete: function(roomJid, success, error, notify) {  //line 6879
		this.connection.sendIQ($iq({
			type : 'set'
		}).c('pubsub', {
			xmlns : Strophe.NS.PUBSUB
		}).c('retract', {
			node : Strophe.NS.BOOKMARKS,
			notify: notify || false
		}).c('item', {
			id: roomJid
		}), success, error);
	}
```

And therefore this error does no make any sense at all, but I will investigate this tomorrow.

**Comment by sualko** [comment]
Which was the last working version?

**Comment by sualko** [comment]
Unbelievable... There are multiple problems, but one of the most annoying one is, that IE10 does not like comments starting with <code>@</code>, but only under [certain circumstances](http://www.pjgalbraith.com/ie-conditional-compilation-and-todo/). I removed the <code>@</code> in the build packages (bda4267def1becbeedfbd4a00284756b35fb5f6e), so IE10 should work now.

[c02b4b6](https://github.com/jsxc/jsxc.owncloud/commit/c02b4b6a2d97a75bc9f5c0748758522bff074291) disables jsxc if an error occurs, but for reference here are some more bugs:

- IE does not like <code>catch</code> as function. [webrtc/adapter#L222](https://github.com/webrtc/adapter/blob/master/adapter.js#L222)
- IE does not like reserved keywords as properties. [strophe/plugins#L103](https://github.com/strophe/strophejs-plugins/blob/master/bookmarks/strophe.bookmarks.js#L103)

So IE8 is currently not supported, but in my pov this is completely ok. What do you think @Luticus and @MarcelWaldvogel ?

**Comment by Luticus** [comment]
Well for me the only reason I want IE support at all is because many times my line of work will cause me to have to use a computer system that has some crazy old IE that I can't upgrade and due to the security policy on the computer, I can't install alternative browsers.  That's why if you don't want to support old versions of IE (which I totally understand) then just disable the plugin on error or whatever so you don't break the rest of Owncloud.  I'd still miss chat :), but at least I wouldn't be completely locked out of my system in this case.  My browser of choice tends to be Firefox running on Debian so for me personally, I don't tend to notice the problem until one of my users tells me about it.  Unfortunately they are often limited by their work computers as well.  

One of the biggest reasons I love the chat system integrated with Owncloud so much is that when I'm stuck on some god awful computer that won't let me install software, it doesn't matter.  I can just go to my Owncloud and still chat securely over 443.

**Comment by Luticus** [comment]
As for your questions about the last working version.  I'm not 100% on that because I don't personally use IE unless I'm forced lately.  I *think* 2.1.1 worked because I remember pointing this out before when I was running 2.1.0 and being told that the issue was fixed.  I remember testing it and being happy that it worked.  So maybe 2.1.1?

**Comment by sualko** [comment]
> just disable the plugin on error 

This is what https://github.com/jsxc/jsxc.owncloud/commit/c02b4b6a2d97a75bc9f5c0748758522bff074291 does. ;-)

**Comment by Luticus** [comment]
Final note.  Thank you for c02b4b6.  I implemented your code in my current build and it works fantastically.  My experience so far tells me that I wouldn't recommend you worry too much about supporting IE8 as OC itself doesn't seem to work too well with it.  It'll load but the theme engine is all broken and some of the apps either have trouble working, or don't work at all.  IE10 works well though.

Thanks again!  Definitely appreciate the developer interaction!
