### ISSUE TITLE
what I had to change from the installation instructions

### ISSUE THREAD

**Issue by select** [jsxc/jsxc#222]
on https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud) it states 

*Now copy the auth_ejabberd_oc.php and auth_oc_user.php from ojsxc to /etc/ejabberd/ and adjust owner and permission.*

I also need to change `auth_ejabberd_oc.php` 
```
$oc_root = '/var/www/MY DIRECTORY/';
```

and in the `/etc/ejabberd/ejabberd.cfg`
```
%% Hostname
{hosts, ["localhost", "127.0.0.1", "cloud.myserver.com", "myserver.com"]}.
```

**Comment by select** [comment]
I think the `{hosts, [ ... "127.0.0.1"` resolved the bosh connection problem in the OwnCloud admin and  $oc_root made the login work. Before I always got "Could not authenticate" messages.

**Comment by sualko** [comment]
The changes in <code>auth_ejabberd_oc.php</code> are related to #46. The second changes were not required in my installations, but if it works... 

Thanks for reporting anyway. I will update the wiki asap.
