### ISSUE TITLE
wiki lighttpd instructions

### ISSUE THREAD

**Issue by select** [jsxc/jsxc#223]
I use lighttpd and could not find the insturctions in the wiki so here is what I added to my `/etc/lighttpd/lighttpd.conf`

```
server.modules += ( "mod_proxy" )
proxy.server = (
  "/http-bind" => (
    ( "host" => "127.0.0.1", "port" => 5280 )
  )
)
```

This is the general way to do this, activate mod_prox and then set up the proxy connection. Since I have OwnCloud running under a subdomain my configuration looks a bit different.

In the `lighttpd.conf` i added the module 
```
server.modules = (
       ...
      "mod_proxy"
     ...
)
...
# include all files that are under vhosts
include_shell "cat /etc/lighttpd/vhosts/*.conf"
```

and in my vhosts/myserver.conf
```
$HTTP["host"] == "cloud.myserver.com" {
        server.document-root = "/var/www/owncloud/"
        server.errorlog = "/var/log/lighttpd/owncloud.error.log"
        accesslog.filename = "/var/log/lighttpd/owncloud.access.log"
        proxy.server = (
                "/http-bind" => (
                        ( "host" => "127.0.0.1", "port" => 5280 )
                )
        )
}
# always redirect to https 
$HTTP["scheme"] == "http" {
    $HTTP["host"] == "cloud.myserver.com" {
            url.redirect = (".*" => "https://cloud.myserver.com$0")
    }
}
```

I can now connect with pidgin XMPP to myOCuser@cloud.myserver.com

Maybe it would be nice to integrate this information into the wiki, to get others setup faster.

**Comment by sualko** [comment]
I changed the wiki to public and now you should be able to add your information to:

https://github.com/jsxc/jsxc/wiki/Prepare-lighttpd

I think this will come handy for a lot of users. Thanks for your work. If you have no time or energy to convert this issue in a wiki post, please let me know.

**Comment by select** [comment]
I'll work on it during the weekend, and since the damn lighttpd is super unstable I'll switch to nginx where I can write also instructions ;)

**Comment by select** [comment]
Added instructions for lighttpd and nginx.

**Comment by sualko** [comment]
Thank you a lot.
