### ISSUE TITLE
Automatically add all OwnCloud users as friends

### ISSUE THREAD

**Issue by select** [jsxc/jsxc#224]
Is it possible to automatically add all OwnCloud users as friends? It's a bit difficult to explain all my uses that they need to add me as a friend, when they can see me on the platform already. 

Furthermore it would be even better if all users would join a default chat room.

Looking forward to hear your thoughts on that.

**Comment by sualko** [comment]
> Is it possible to automatically add all OwnCloud users as friends?

Shared roster is the key word. For prosody checkout [mod_groups](http://prosody.im/doc/modules/mod_groups) and for ejabberd [mod_shared_roster](https://www.ejabberd.im/ejabberd-0.9).

> Furthermore it would be even better if all users would join a default chat room.

This is some kind of tricky, because room information is saved in the users private storage, but it should be possible to write some lines of code to do this. Give me some time to figure it out.

**Comment by sualko** [comment]
```
$(document).on('attached.jsxc', function(){
   var room = 'your-room@conference.yourconfserver';
   if(jsxc.gui.roster.getItem(room).length === 0){
      jsxc.muc.join(room, Strophe.getNodeFromJid(jsxc.xmpp.conn.jid));
   }
});
```

This is untested, but if it satisfies you, please close this issue.

**Comment by select** [comment]
Fantastic I'll try all this during the weekend. This makes me really happy since it worked all so smooth and this really makes the project perfect!

**Comment by select** [comment]
The code for autojoining a room, worked quite good. I added it to the beginning of `owncloud/apps/ojsxc/js/ojsxc.js`. The only annoyance is, that if the room was empty so far it asks how the room should be created, I choose default all the time. To prevent this i join the room with my phone client and it should always be there since it keeps it all the time.

**Comment by select** [comment]
With the shared roster I tried to follow the instructions for ejabbered (the client I chose from the tutorial in the wiki :D) but even though I added 
```
{mod_shared_roster, []},
```
to the config and set my host I can not see the shared roster section in the webadmin (which was a bit tricky to reach since I have to do a portforward to my server). Do I need to set virtual hosts in ejabberd? Any other hint how to make this work. Wouldn't it also be possible to do this from the JS client? In the future do I have to add all new people manually to the shared roster in the ejabberd webadmin? ... a lot of questions, thanks for your support already, I really appreciate it.

**Comment by sualko** [comment]
> The only annoyance is, that if the room was empty so far it asks how the room should be created, I choose default all the time.

Maybe you should try "Change" and create a persistent room ;-).

> I can not see the shared roster section in the webadmin

Mh, I remember that it was a little bit tricky to get it running. I check my config this evening and maybe I find a hint for you.

> Wouldn't it also be possible to do this from the JS client?

I think not.

> do I have to add all new people manually to the shared roster in the ejabberd webadmin?

No, there is a keyword, which adds every user to your shared roster. For more advanced setups, I recommend to use ldap groups.

**Comment by sualko** [comment]
Please restart your ejabberd service and afterwards you should find the "Shared Roster Groups" under "Virtual Hosts" > "YOUR HOST".

From the manual: 

> The special member directive <code>@all@</code> represents all the registered users in the virtual host; which is only recommended for a small server with just a few hundred users. The special member directive <code>@online@</code> represents the online users in the virtual host.

**Comment by select** [comment]
Ah ok so I'll have to create a virtual host first. Thanks, i'll try.

**Comment by select** [comment]
Ok maybe I can not see any virtual hosts in the webadmin is because I have not created an admin in ejabberd, trying this now but not sure how.

**Comment by select** [comment]
ha jackpot
```
{acl, admin, {user, "myname", "cloud.example.com"}}. <- did not help (maybe because i tunneld with ssl to localhost)
{acl, admin, {user, "myname", "localhost"}}. <- got me admin access
```

**Comment by select** [comment]
Ok one step further, I created a shared roster group "all" and set members `@all@`. This did not help much but when I added members `@online@` I could see at least online members. I think this has to do with the fact that when I look at the vhost table on the webadmin it shows me 

Host	| Registered Users	| Online Users
cloud.example.org	| 0	| 4

Which I guess results in the fact that we are using external authentification. If you go more hints on how to push this further so everybody can see also offline people it would be nice, I'll try to. So far this is already quite good.

**Comment by select** [comment]
Even though this post (https://www.ejabberd.im/node/3313) is old it seems this is the bottom of the line. External auth does not support registering users. Not quite want to give up put my attention span for tonight is over.

**Comment by select** [comment]
Ok one last addition, manually adding users that everybody should be friends with works. 

I'll add some documentation in the wiki in within a week or so if you like.

**Comment by sualko** [comment]
> External auth does not support registering users.

That was also my assumption and I see no way to change that.

> I'll add some documentation in the wiki in within a week or so if you like.

Always. Thank you in advance.

**Comment by sualko** [comment]
I close this issue, but if you have time I would appreciate a wiki article about this topic a lot.
