### ISSUE TITLE
Debug Turn Server

### ISSUE THREAD

**Issue by beccon4** [jsxc/jsxc#225]
Video calling works just fine as long both ends are at the same LAN. Calls from a cellular (natted) line cause a "jingle_reason_failded-transport) error (ICE_connection_failure) I installed turnserver on an Ubuntu 14.04 (the one from the repos - turnserver.org), created an user+password and entered them into Owncloud's oxsc. No avail, no log files to look into. Is there a way to increase verbosity (or even getting TURN to work)

Using tcpdump I can see packets going back and forth to the turnserver - but no avail. Here the config - unfortunately turnserver is not very verbose in it's complaints

```
##
# TurnServer configuration file.
#


## Public IPv4 address of any relayed address (if not set, no relay for IPv4).
## To have multiple address, separate addresses with a comma
## (i.e. listen_address = { "172.16.0.1", "172.17.0.1" }).
listen_address = { "199.199.199.199" } # my server's public IP

## Public IPv6 address of any relayed address (if not set, no relay for IPv6).
## To have multiple address, separate address with a comma
## (i.e. listen_addressv6 = { "2001:db8:1::1", "2001:db8:2::1" }).
#listen_addressv6 = { "2001:db8::1" }

## UDP listening port.
udp_port = 3478

## TCP listening port.
tcp_port = 3478

## TLS listening port.
tls_port = 5349

## TLS support.
tls =  false

## DTLS support. It is an experimental feature and is not defined in TURN
## standard.
dtls = false

## Maximum allocation port number.
max_port = 65535

## Minimum allocation port number.
min_port = 49152

## TURN-TCP support.
turn_tcp = false

## TURN-TCP buffering mode:
## - true, use userspace buffering;
## - false, use kernel buffering.
tcp_buffer_userspace = true

## TURN-TCP maximum buffer size.
tcp_buffer_size = 32768

## Daemon mode.
#daemon = true 

## Unprivileged user.
## If you want to use this feature create a system user.
## On Linux: adduser --system --group turnserver
unpriv_user = turnserver

## Realm value.
realm = "domain.org"

## Nonce key.
nonce_key = "hieKedq"

## Max relay per username.
max_relay_per_username = 50 # war 5

## Allocation lifetime.
allocation_lifetime = 1800

## Allocation bandwidth limitation (in KBytes/s).
## 0 value means bandwidth quota disabled.
bandwidth_per_allocation = 1024

## Restricted user bandwidth (in KBytes/s).
## 0 value means bandwidth limitation disabled.
restricted_bandwidth = 1024

## Denied addresses.

# disallow relaying to localhost
denied_address {
  address = "127.0.0.1"
  mask = "8"
  port = 0
}

# disallow relaying to ip6-localhost
denied_address {
  address = "::1"
  mask = "128"
  port = 0
}

#denied_address {
#  address = "10.1.4.0"
#  mask = 24
#  port = 0
#}

## Certification Authority file.
ca_file = "/etc/ssl/certs/ca-certificates.crt"

## Server certificate file.
cert_file = "/etc/turnserver/ssl/server.crt"

## Private key file.
private_key_file = "/etc/turnserver/ssl/server.key"

## Account method.
account_method = "file"

## Account file (if account_method = file).
account_file = "/etc/turnserver/turnusers.txt"

## mod_tmpuser.
mod_tmpuser = false
```

**Comment by sualko** [comment]
WebRTC debugging is tricky, because if e.g. your turn authentication fails, you get no notification. I use Wireshark to detect issues with my turnserver, but this [gist](https://gist.github.com/ibc/3a10b27812d99c8abd1b) should also work for ff.

You can also use this [site](https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/trickle-ice/index.html) to verify that your configuration and credentials are correct. If so you should see some <code>relay</code> candidates.

Please close this issue if you could solve your problem.

**Comment by sualko** [comment]
Any update? Otherwise I will close this issue to keep everything clean.

**Comment by sualko** [comment]
via email

**Comment by pitojax** [comment]
I also have the same issue when implement jsxc on web.
On the same lan the video calling works fine but on different networks it fails. I have ubuntu 15.04 and using ejabberd server. 

ICE_connection_failure
Call terminated: jingle_reason_failed-transport.
Call terminated: jingle_reason_failed-transport.

I see they are talking about TURNSERVER and i have no experience with that. I have not even installed it at all. Could that be the problem?
Please help if you have face such an issue.

thanks

**Comment by sualko** [comment]
@pitojax You need a TURN server to bypass NAT. For testing you can use the free service of http://numb.viagenie.ca.

@beccon4 Since you are now a TURN expert, you may want to write an article in our [wiki](https://github.com/jsxc/jsxc/wiki) about this topic ;-).

**Comment by pitojax** [comment]
which turnserver do i install? CoTurn, or ? I have ubuntu 15.04.
Also i want to enable file transfer and how to show Avatars for the profiles on the roaster with jsxc library?

Thanks

**Comment by andrey-utkin** [comment]
>  if e.g. your turn authentication fails, you get no notification

How TURN auth is supposed to happen? Where should I specify TURN credentials (?) in JSXC?

Currently I have set up JSXC from fresh git master, messaging work (although disconnects very quickly), but calls don't work, even within localhost through different browser sessions. Server is Prosody 0.10.

**Comment by sualko** [comment]
@pitojax Sorry, but messages in closed issues get lost very quickly.

> How TURN auth is supposed to happen? Where should I specify TURN credentials (?) in JSXC?

@andrey-utkin Please check [RTCPeerConfig](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js#L219). If you figured it out, we would be happy to see an wiki article about it.

> although disconnects very quickly

Please open an issue for that, if you need help (consider the [contributor guide](https://github.com/jsxc/jsxc/wiki/Contributor-Guide)).
