### ISSUE TITLE
No Emoticons

### ISSUE THREAD

**Issue by davodego** [jsxc/jsxc#226]
Hi,
after the update to 2.1.4 I have no emoticons. After type the letters (e.g. :D ) nothing is shown but a emtpy space. 

OC 8.1.3
Debian 7
Firefox
JS Console output:
Diese Website hat eine ungültige Strict-Transport-Security-Kopfzeile angegeben.[Weitere Informationen] gear_grey.svg
Diese Website hat eine ungültige Strict-Transport-Security-Kopfzeile angegeben.[Weitere Informationen] Zarafa_logo_transparent.png
Ungültige URI. Laden der Medienressource  fehlgeschlagen. webapp
Diese Website hat eine ungültige Strict-Transport-Security-Kopfzeile angegeben.[Weitere Informationen] zarafa.php
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.

**Comment by sualko** [comment]
Duplicate of #218.
