### ISSUE TITLE
feature request for OMEMO Encryption (XEP-0384)

### ISSUE THREAD

**Issue by muzirian** [jsxc/jsxc#228]
Request for adding support for omemo encryption http://conversations.im/xeps/multi-end.html

_References (edited by @sualko):_
[XEP-0384: OMEMO Encryption](https://xmpp.org/extensions/xep-0384.html)
[omemo.js](https://github.com/cryptocat/cryptocat/blob/master/src/js/omemo.js) (cryptocat/cryptocat#178)
[libaxolotl.js](https://github.com/joebandenburg/libaxolotl-javascript)
[libsignal-protocol-javascript](https://github.com/WhisperSystems/libsignal-protocol-javascript)
[OMEMO quickstart quide](https://gist.github.com/iNPUTmice/e3fe475752e39b40ea87ae5ed73b3e01)

**Comment by samweisgamdschie** [comment]
There is discussion in progress, as you can see here https://github.com/anurodhp/Monal/issues/9  if you guys want to implement this awesome feature!

**Comment by GreenLunar** [comment]
See also OMEMO.js at https://github.com/cryptocat/cryptocat/issues/178

**Comment by herbsmn** [comment]
This really should move forward.

**Comment by MarcelWaldvogel** [comment]
I agree. Pull requests welcome.

**Comment by bertzi** [comment]
is there something new about it?

**Comment by DanScharon** [comment]
OMEMO has a kind of soft dependency on #150

**Comment by DanScharon** [comment]
OMEMO is now published as XEP-0384: https://xmpp.org/extensions/xep-0384.html

**Comment by sualko** [comment]
We have now a student which is working on this as part of his bachelor thesis. So stay tuned. We expect first public results around August.

**Comment by misandrist** [comment]
@sualko Hey hey, if there's anything I could do to help him (without of course ruining his chances at a good thesis) I'd love to help out.

Thanks!

**Comment by sualko** [comment]
@misandrist Thanks for your offer. Of course we need some reviewers after his work is done and it is great that there is some interest in this.

**Comment by misandrist** [comment]
I'd love to review it, absolutely.

Thanks!

**Comment by lweddewer** [comment]
Any progress related to this topic?

**Comment by sualko** [comment]
> We expect first public results around August.

It will probably be September and we are hopping that we get a first working version in jsxc by end of the year.

**Comment by Rafaelrico77** [comment]
Its September now. Are they any news related to this topic ?

**Comment by sualko** [comment]
We are not as far as we thought and additionally there are some license issues which slow down the integration further. I guess I can give more details in 2-3 weeks.

**Comment by Technowix** [comment]
7 weeks later... something ? ^^'

**Comment by Shokodemon** [comment]
@Technowix it is nearing completion, im writing the XML parsing bits and will be making sure it all works soon, should be done by end of the year at most (i don't see it taking 6 more weeks, 6 is a hard max).

**Comment by ajs124** [comment]
So, half a week more to go @Shokodemon?

**Comment by Shokodemon** [comment]
@ajs124 no, longer than that. i have had health issues which delayed this work, but i am doing my best to catch up. it won't take much longer. i will post when it's ready.

**Comment by sualko** [comment]
:loudspeaker: Good news: We have a working :tada: Omemo plugin for the upcoming 4.0 (tested with gajim). It's not yet committed to the repo, because the Signal Lib is licensed under GPL and therefore we have to release it as separate plugin, but I think this should be no big deal. I will give you a heads up if we release the first alpha version.

**Comment by Technowix** [comment]
Woot, nice job!

**Comment by muzirian** [comment]
awsum, great work

**Comment by codekain** [comment]
i am very excited to hear that

**Comment by cloehle** [comment]
If this is now fully implemented and tested it should also be changed at [omemo-top](https://github.com/bascht/omemo-top/blob/master/_data/clients/jsxc.yml)

**Comment by Echolon** [comment]
If you say so

https://github.com/bascht/omemo-top/pull/175
