### ISSUE TITLE
Owncloud 8.2 does not show login button

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#231]
After upgrading to 8.2 the login screen only shows the log in dialogue boxes and the link "login without chat" it does now show the normal login button.

There is a workaround where if you fill out the dialogue and just press enter it will log in with chat as if the user clicked the login button.  

Not sure what's going on, this occurs even after disabling my custom theme.

I have seen this behavior in both Firefox and IE10

**Comment by sualko** [comment]
Please post a screenshot, because in oc 8.2 there is no classic login button. Only an arrow on the password field.

**Comment by Luticus** [comment]
HAH, now I feel goofy.  That's definitely what's going on here.  I looks awfully confusing now for people not expecting that change because now they just see username/password and "log in without chat" which looks broken in my opinion.  That little arrow is kinda easy to miss :).  I suppose this is not a bug after all.  

Thanks!
