### ISSUE TITLE
IE10 user types message and presses enter to send, then chat loses focus

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#232]
In chat while using IE10, if a user types a message in chat and then presses enter to send the message, the user must then click on the chat windows again to continue typing and sending messages.  Once a message is sent in IE10 the chat box goes dark and loses focus.  The user must then click it to enable it again.

**Comment by sualko** [comment]
I will investigate this.

**Comment by Luticus** [comment]
Awesome!  Thanks!
