### ISSUE TITLE
User State always Offline (fresh OwnCloud Install 8.1.1 with ejabberd)

### ISSUE THREAD

**Issue by dotnetcomgazio** [jsxc/jsxc#233]
I can chat with them but when I change my status (online/chat...) nothing in my friends list.

I see that:
https://github.com/diaspora/jsxc/issues/124

And I can't made video call (Chrome)

**Comment by sualko** [comment]
> User State always Offline

I am sorry, but I am not familiar with the Diaspora version, because it has some modifications. You have to wait until Zauberstuhl or someone else is debugging this behaviour.

> And I can't made video call (Chrome)

Most of the time this occurs if your turn server configuration is missing or incorrect.
