### ISSUE TITLE
Example throws the error: "ReferenceError: cb is not defined"

### ISSUE THREAD

**Issue by annando** [jsxc/jsxc#234]
I downloaded the source code of the version 2.1.4. In the index.html in the example folder I set the values for "root" and "domain" according to my system and called the index.html in my browser. Whenever I try to login with the left or right example login then the console of my Firefox (41.0.2) is throwing the error "ReferenceError: cb is not defined" in line 31:
https://github.com/jsxc/jsxc/blob/master/example/js/example.js#L31

**Comment by sualko** [comment]
Please test the fix and any report is appreciated.

**Comment by annando** [comment]
It is working fine. Thanks for the quick fix.
