### ISSUE TITLE
Connection with srv

### ISSUE THREAD

**Issue by rototom** [jsxc/jsxc#235]
Currently I cant login to my xmpp server (bosh connection works like a charm).
Possibly I have problems with my prosody not runnig with standard ports?
I use srv entries to connect with clients and other servers without problems.

**Comment by sualko** [comment]
I do not get your question, because jsxc does not use any srv records. Is this a general question?

**Comment by sualko** [comment]
Any update?

**Comment by rototom** [comment]
It magically seems to work now.
Changed nothing, but I think the server rebooted once.
