### ISSUE TITLE
Jsxc for Hubzilla from the Federation Network

### ISSUE THREAD

**Issue by royalterra** [jsxc/jsxc#236]
Will be a very good idea have a JSXC plugin for Hubzilla (Hubzilla is  A free Social Network Style of Diaspora or friendica ) can be check the project in :+1: 

and the Github Code: https://github.com/BlaBlaNet/BlaBlaNet
In the section Addon: https://github.com/redmatrix/hubzilla-addons there and other XMPP Chat but the code is from Friendica Network and not support Video Conference. With also the problem the user need to have a XMPP account and have knowledge for configuration.

The Idea is to have JsXc us Chat Client with the next features:
1.- In Admin section the administrator Setup the XMPP server configurations
2.- Every time a user Register in the web is automatically also create a XMPP account user not need to Setup any configurations .
3.- The seam of the Old Chat Plugin is in Hubzilla repository the system check if any users in the Friend list have a Jabber account and add the user to his roster. 

##

**Comment by royalterra** [comment]
HI @sualko I make one admin account for you in one Hubzilla Hub just in case you like to test hubzilla us admin possible you got a email  if not I am in Jabber . You can contact me for the url, user and password

**Comment by sualko** [comment]
Thanks, I got an email.

**Comment by royalterra** [comment]
@sualko any chances we can start looking for this plugin

**Comment by sualko** [comment]
Nope sorry. We are currently under heavy development for v3.0.

**Comment by rodneyrod** [comment]
So would this be possible to also integrate with some sort of VOIP service, like Jingle?

**Comment by sualko** [comment]
JSXC supports video calls and file transfer via Jingle and WebRTC.

**Comment by royalterra** [comment]
Yes @sualko but when we can start with this development I can provide a server for test with one HUb already install basically we need to change any of the actual xmpp cha have Hubzillat with your code .

**Comment by royalterra** [comment]
This post is now to long open. We go to release a Hubzilla Fork call Blablanet 3.0 and include by defect JSXC I will offer a Reward in bountysource.com for any one interest in participate in this issue.  Blablanet 3.0 will be release at the end of the month in geditlab.com bounty redward for JSXC blablanet 3.0 I will offer in bountysource.com

**Comment by royalterra** [comment]
OK That is now very long time is this post here . I will offer a Reward pay with Bounty Bounce to the person Make this Plugin for Hubzilla there already a converse plugin sure will be easy make the modifications

**Comment by royalterra** [comment]
250$ To the developer change the Converse  code of Hubzilla plugin to JSXC any one interest contact me back. Possibel like that I will can solve this ticket front 2015 now we are near 2017 and I an hurry

**Comment by sualko** [comment]
@royalterra Maybe it is a good idea to raise this bounty at https://www.bountysource.com/issues/28126328-jsxc-for-hubzilla-from-the-federation-network, so the handling would be easier.

**Comment by sualko** [comment]
@royalterra if your offer ist still valid, please send me an email to klaus@jsxc.org

**Comment by royalterra** [comment]
Hi @sualko I will not raise in BountySource with Hubzilla because I am making a fork go to use also to MongoDB us Database. Everything is my Job and Pay developers for help me . The code will be Open Source in Blablanet Social Network is also in Bounty Source . Now the offer is open I will write you now if you are interest

**Comment by royalterra** [comment]
Like I say to you in private we have disconnected front Hubzilla  now if you can do in https://github.com/BlaBlaNet/BlaBlaNet  you are welcome the offer is OPen and the Cash
