### ISSUE TITLE
Problem ojsxc on ./js/jsxc/lib/jsxc.dep.js

### ISSUE THREAD

**Issue by vaheed** [jsxc/jsxc#237]
if (service.indexOf("ws:") === 0 || service.indexOf("wss:") === 0 ||

>>>>

null is not an object (evaluating 'service.indexOf')
Connectionjsxc.dep.js:2079

**Comment by vaheed** [comment]
Uncaught TypeError: Cannot read property 'indexOf' of null

jsxc.dep.js?v=b85e31bd68ec87e7110acb33f1d89241:2030

**Comment by sualko** [comment]
You should provide some more information. E.g. how looks your config?
