### ISSUE TITLE
no version for ownCloud 8.2

### ISSUE THREAD

**Issue by schiesbn** [jsxc/jsxc#238]
would be great if you could upload a new version to the app store which works with ownCloud 8.2.

**Comment by royalterra** [comment]
owncloud 8.2 still no work perfect . I not see the point I go to downgrade to the previous version

**Comment by sualko** [comment]
@schiesbn I wanted to wait until the 3.0 release is ready, but I think you are right I should create a bug fix release for 8.2

@royalterra What do you mean?

**Comment by royalterra** [comment]
@sualko 
The last version of owncloud have several problems with MYSQL and bookmarks and other options not work for some users. is not a problem I meet alone there few post in owncloud forums .
I solve some problems using MARIADB last version but bookmarks not work in fresh installations other users have also some issues with the new version of php5.

**Comment by sualko** [comment]
Can you test the latest release?

https://github.com/owncloud/jsxc.chat/releases/tag/v2.1.5

I will announce it tomorrow, if no show stopper occurs.
