### ISSUE TITLE
"Error: Error setting badge. Message:" On  message reception

### ISSUE THREAD

**Issue by nitmir** [jsxc/jsxc#242]
Sometimes, on message reception (from a pidgin client or jsxc client) I get the following stack trace : 
```
function jsxc.xmpp.onMessage()  - error -  Error: Error setting badge. Message:
Trace de la pile :
Favico/badge/_readyCb@https://genua.fr/jsxc/build/lib/jsxc.dep.js:34723:12
Favico/badge@https://genua.fr/jsxc/build/lib/jsxc.dep.js:34727:5
jsxc.gui.unreadMsg@https://genua.fr/jsxc/build/jsxc.js:3264:10
jsxc.gui.window.postMessage@https://genua.fr/jsxc/build/jsxc.js:4317:10
jsxc.xmpp.onMessage@https://genua.fr/jsxc/build/jsxc.js:1708:10
Strophe.Handler.prototype.run@https://genua.fr/jsxc/build/lib/jsxc.dep.js:1846:22
Strophe.Connection.prototype._dataRecv/<@https://genua.fr/jsxc/build/lib/jsxc.dep.js:2811:29
Strophe.forEachChild@https://genua.fr/jsxc/build/lib/jsxc.dep.js:858:17
Strophe.Connection.prototype._dataRecv@https://genua.fr/jsxc/build/lib/jsxc.dep.js:2799:9
Strophe.Bosh.prototype._onRequestStateChange@https://genua.fr/jsxc/build/lib/jsxc.dep.js:4346:17
 Error setting badge. Message:
```

After that, I'm still able to send messages, but I do not receive any message from any client.

**Comment by sualko** [comment]
Can you reproduce it? If yes, how?

**Comment by nitmir** [comment]
Well it's very strange. I've wander a bit in other issue and see one (#208) about favicon. I add a favicon and now it's working.
Otherwise, just after login everything work. If I reload the page (and thus use some cached jid, sid, rid to attach the bosh session), on the next incoming message, I get the traceback above.

Maybe it has to do with the number of undread messages displayed inside the favicon of the window.

**Comment by sualko** [comment]
So you get the error only if you have no favicon?

**Comment by nitmir** [comment]
yes
