### ISSUE TITLE
ejabberd.cfg deprecated, now replaced by ejabberd.yml

### ISSUE THREAD

**Issue by HLFH** [jsxc/jsxc#245]
Hi,

In [your documentation](https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04), you are talking about ejabberd.cfg file, but ejabberd.cfg is now deprecated and has been replaced by ejabberd.yml.

Please update the [Wiki](https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04).

[Ejabberd yaml conf file format](http://docs.ejabberd.im/admin/guide/configuration/#config-file-formatting)
[Ejabberd legacy conf file](http://docs.ejabberd.im/admin/guide/configuration/#legacy-configuration-file)

**Comment by nitmir** [comment]
Hum, the purpose of a wiki is that you can edit it yourself, no ?

**Comment by HLFH** [comment]
Yes, until I find the solution, I'll keep this issue open.

**Comment by HLFH** [comment]
@nitmir I found the solution. I'll update the wiki quickly.

**Comment by nitmir** [comment]
cool ^^

**Comment by HLFH** [comment]
@nitmir I renamed the page to `Install ejabberd (owncloud) | Ubuntu 12.04` and I created [another wiki page related to ArchLinux and the updated ejabberd.yml configuration file](https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-ArchLinux).
