### ISSUE TITLE
Create No-Video-Call-Possible icon

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#248]
Currently if the peer does not support any video calls the video icon has only less opacity than normal. I think a cancelled icon would be much nicer.

**Comment by nitmir** [comment]
In case of multiple open tabs, on instances stating that "I am the slave" the video icon is not visible : 
![capture d ecran de 2015-11-23 16-05-11](https://cloud.githubusercontent.com/assets/5030463/11339951/263a887e-91fc-11e5-9588-de6fe784d994.png)

The first times I encounter that it was quite confusing. Maybe a special icon with a tootip and an action to get focus on the master would be nice.

**Comment by sualko** [comment]
I totally agree with you. We should handle this case better. Do you have any idea for such an special icon?
