### ISSUE TITLE
Roster issue connecting OpenFire

### ISSUE THREAD

**Issue by Gummikavalier** [jsxc/jsxc#250]
Hi,

First of all thank you for the very promising web chat application.

I'm not very versed with XMPP, but after some troubleshooting I've come to conclusion that I seem to have some kind session initialization or cleaning issue with BOSH and ojsxc.

I have a setup with XMPP running on a separate OpenFire server.
Owncloud and ojsxc are running on their own server.

At first ojsxc did work properly. I was using chat from one location/session.

However, later when I changed sessions and browsers few times, the client got stuck and shows an empty roster. Sometimes it shows people in it, but they are offline while I can confirm that they should be online. The amount of people in the roster seems to vary too, missing lots of people, even if it is set to show full user list including offline contacts.
This happens with freshly started Firefox and Chrome browsers after the initial success, with no other browser session open in any location. It seems to me that the server seems to think that there is still something going on with the closed sessions and does not provide a fresh one. If that makes sense.

Jappix web client that also uses BOSH does not seem to suffer from the same problem. With Jappix I can clean the situation by shutting down all the browsers and starting from scratch. With ojsxc I have to restart OpenFire to get the client working again.

It is quite clear that it is OpenFire that gets confused in handling the data to the client, but is it possible that ojsxc does not "reinitialize" the user's session to OpenFire properly when it starts a new session?

Thank you! :)

**Comment by sualko** [comment]
> is it possible that ojsxc does not "reinitialize" the user's session to OpenFire properly when it starts a new session?

What does new session mean for you?

Please describe every single step to reproduce your issue. E.g. 1) login with username, password and resource. 2) Reload page 3) Logout 4) ...

> I changed sessions

Which session? Browser? BOSH? ...

**Comment by Gummikavalier** [comment]
Yes, I've no idea how bosh handles these things so I used the term session in broadest sense.

I noticed this problem when I moved from work to home to a different computer. I now did a test in the same location with three different computers, one remote server, a laptop and a desktop.
I witnessed the problem both with latest Firefox and Chrome.

The problem is replicable simply by following these steps:

1. Login in owncloud with ojsxc, and see that you are connected to XMPP server. Everything is working. All users, including offline, are visible.
Log out from owncloud. Close the browser.

2. Connect to owncloud from different computer and different IP address. Check the contacts list again. Everything may still be in order.
Log out from owncloud. Close the browser.

3. Again connect to owncloud from a third computer and again from a different IP address. Login succeeds but the the roster list is empty, or contains only some of your contacts. All of them are offline and stay offline regardless of their true status (checked the statuses directly on XMPP server console).

4. If you don't see the problem yet, repeat doing this between these three computers couple of times more. For me it happens every three or four browser restarts and logins.

5. From this on, any of the three computers ojsxc clients start having the same problem.
Closing and restarting the browser does not help, but restarting OpenFire does.
Before restarting OpenFire, if you have Jappix web client configured to use the same BOSH url, you can test and notice that it does not exhibit the same problem.

**Comment by Gummikavalier** [comment]
Eventually I got the problem with Jappix too, so this must be mostly an OpenFire issue. I suspect some kind of timeout when the contact list is long enough. My account has 300 contacts.

I'll first see if I can find anything regarding this in OpenFire.

**Comment by Gummikavalier** [comment]
Ok, this probably didn't come as a surprise to you...

I did my homework about how BOSH is not stateful connection type and to counter that, the proxy/reverseproxy setup on the XMPP server is must. I was fooled when it seemed to work fine without the proxy at first, and thought that proxy configuration is needed for same origin reasons on the ownCloud side.

I close the case and sorry for the trouble. :)

**Comment by sualko** [comment]
> and sorry for the trouble. :)

No Problem. I am happy, that you could figure this out on your own and that this is no jsxc issue.
