### ISSUE TITLE
oc update changes rights to oc config.php ejabberd login stops working

### ISSUE THREAD

**Issue by select** [jsxc/jsxc#251]
After updating Oc my complete xmpp stopped working due to to login script not beeing able to confirm the login via oc anymore. 

I know this is not a direct issue of jsxc but I got it all working from the instructions here. 

Is there something we can do to improve this issue?

**Comment by tedbarth** [comment]
I recently installed jsxc on owncloud 8.2.1. Though i have other problems the login works.
Please check the rights of owncloud folder. They might have been corrected by the update.

**Comment by sualko** [comment]
After each update oc updates permissions of config.php. So please compare these with the ones from the instruction.

**Comment by sualko** [comment]
Any update?
