### ISSUE TITLE
Can't store buddies nor start conversation

### ISSUE THREAD

**Issue by tedbarth** [jsxc/jsxc#252]
I've managed to get XMPP, login via Owncloud accounts and Bosh URL to work. I even managed to chat with an oc user by starting a conversation from out pidgin.

My problem is that no buddies can be added. Sometimes a buddy symbol got added to the roster but it is lost when logged in again. Most of the time just nothing happens when adding users. The added person even doesn't get any authentication message and no messages received from a pidgin user when offline appears when going online again in owncloud.
Even if I manage to get a buddy into the roster (cant reproduce now) the messages sent to it wont reach through.

jsxc for owncloud 2.1.5
ownCloud 8.2.1 (stable)
ejabberd from Ubuntu 14.04 repositories
Used this guide to install it: https://github.com/jsxc/jsxc/wiki/Install-ojsxc-(owncloud)

Any idea? Some rights problem?
What information do you need?

**Comment by sualko** [comment]
Are you able to add contacts in pidgin?

Can you send some test credentials to klaus@jsxc.org?

**Comment by sualko** [comment]
Any update?
