### ISSUE TITLE
can't compatible with php7???

### ISSUE THREAD

**Issue by xieqiwen1993** [jsxc/jsxc#253]
server owncloud 8.2.1
PHP7
Nginx

enable  Owncloud Xmpp Client and setting   BOSH url / XMPP domain   is fine;

but  can't  login  Chat .  
when login   the reply
" Authentication failed with the chat server. Maybe the password is wrong? "

log display : 
PHP Startup: apm: Unable to initialize module Module compiled with module API=20141001 PHP compiled with module API=20151012 These options need to match at Unknown#0

this API=20141001  possible  the php5.5-5.6   extention  setting。。。。

**Comment by xieqiwen1993** [comment]
my nginx config

  location /http-bind {
                proxy_pass http://127.0.0.1:5280;
}

**Comment by sualko** [comment]
Please test your authentication with an other XMPP Client with BOSH support like Pidgin. Make sure to use BOSH as connection type.
