### ISSUE TITLE
owncloud ejabberd error: extauth script has exitted abruptly with reason 'normal'

### ISSUE THREAD

**Issue by bertzi** [jsxc/jsxc#254]
Hello,

I get this error message every second a couple of times. 
the error must be from the auth script cause when i change the auth_methode from external to internal the error stops.
{auth_method, external}.
{extauth_program, "/etc/ejabberd/auth_ejabberd_oc.php"}.
i have installed ojsxc like its described here: https://github.com/jsxc/jsxc/wiki/Install-ojsxc-%28owncloud%29
i have set owner and permission like this
```
-rwxr--r--   1 ejabberd ejabberd 108443 Dez 28 20:55 auth_ejabberd_oc.php
-rwxr--r--   1 ejabberd ejabberd  54055 Dez 28 20:55 auth_oc_user.php
-rw-------   1 ejabberd ejabberd  17243 Dez 31 13:15 ejabberd.cfg
```
i have set the loginglevel to debug but cant see anything strange.
i can login to owncloud only if i klick on "login without chat. if i go the "normal" way it hangs on "login - please wait".
Owncloud 8.2 runs on ubuntu server 14.04 with apache and ejabberd server.
can you help me solve this issue?
regards

**Comment by sualko** [comment]
Please check https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04 specially the part of the permissions of the oc config file.

**Comment by bertzi** [comment]
sorry i dont get it
as you can see the permissions are set as its described.

**Comment by sualko** [comment]
Please post permissions of <code>OWNCLOUD/config/</code> and the result of <code>groups ejabberd</code>.

**Comment by bertzi** [comment]
/var/www/owncloud/config# ls -al
drwxrwxr-x  2 www-data www-data  4096 Dez 28 18:13 .
drwxrwxr-x 15 www-data www-data  4096 Jan 10 12:10 ..
-rw-r-----  1 www-data www-data   921 Jan  5 22:16 config.php
-rwxrwxr--  1 www-data www-data 36586 Dez 21 13:46 config.sample.php
-rwxrwxr--  1 www-data www-data   225 Dez 21 13:46 .htaccess

groups ejabberd
ejabberd : ejabberd www-data

**Comment by sualko** [comment]
There you go: [Install ejabberd](https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04) says

```
sudo chmod -R g+w /var/www/OWNCLOUD_DIR
```

but for your <code>config.php</code> the group write flag is missing. This is a common problem after every oc update, for what I don't have a solution yet.

Happy chatting!

**Comment by sualko** [comment]
I added a note to the ejabberd guide for this annoying bug.

**Comment by gurussia** [comment]
the same here. extauth:loop:137 extauth script has exitted abruptly with reason 'normal' nextcloud
