### ISSUE TITLE
jsxc 2.1.5 and ownCloud 8.2.1: JavaScript minify mistakes

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#255]
I'm running ojsxc 2.1.5 and ownCloud 8.2.1 on Ubuntu 14.04 LTS. After enabling the chat, ownCloud stops working (no more Ajax operations, no login, no nothing).

I've tracked it down to the minify process in the ownCloud asset pipeline, which translates

``` javascript
a++ // or a--
b *= expression // or -=, +=, /=
```

into

``` javascript
a++b*=expression
```

(after variable renaming); i.e., the semicolon is missing.

How can this be fixed?
##

**Comment by MarcelWaldvogel** [comment]
The above examples are from `ojsxc+/js/jsxc/lib/jsxc.dep.js`. In `ojsxc/js/jsxc/lib/strophe.jinglejs/strophe.jinglejs-bundle.js`, it also happens in the following constructs:

```javascript
        var taskComplete = function () {
            remainingTasks--
            _each(listeners.slice(0), function (fn) {
                fn();
            });
         };
 ```
and
```javascript
                } else if (c <= 32 || c === 47 /* / */ || c === 62 /* > */) {
                    tagName = endRecording()
                    pos--
                    state = STATE_TAG
                }
                break
            case STATE_IGNORE_TAG:
```

**Comment by sualko** [comment]
I think this should be reported to https://github.com/owncloud/core. 

Interesting article about pipelining and performance in owncloud: https://github.com/owncloud/core/issues/17693

**Comment by sualko** [comment]
Was this fixed in the meantime?

**Comment by MarcelWaldvogel** [comment]
Kinda. The asset pipeline was removed from Nextcloud in 2016-06-15 nextcloud/server#215 because it led to bugs. The recommendation is that apps provide their own minified JS/CSS instead.
