### ISSUE TITLE
Video chat window cannot be closed

### ISSUE THREAD

**Issue by thetaxevader** [jsxc/jsxc#256]
When trying to start a video chat a window opens and it tries to connect (which fails by the way, but havn't fully troubleshot yet). This window (ie. a 'soft' window on the current html page/tab) lacks ability to close... no 'x' and clicking outside it does nothing... u have to close the entire tab to get back into owncloud...

**Comment by nitmir** [comment]
When I click on "hang up" it closes the 'soft' window.

**Comment by thetaxevader** [comment]
Well then I guess the "connection fails" bit is more important... I guess if the connection doesn't go through, then it goes into some sort of infinite loop and the "hang up" button is useless... so it should have some sort of "abort" button that closes the window, like an "x" button...

**Comment by sualko** [comment]
This should be obsolete through https://github.com/jsxc/jsxc/pull/217#issuecomment-146181304
