### ISSUE TITLE
Login to XMPP after logging into ownCloud

### ISSUE THREAD

**Issue by thetaxevader** [jsxc/jsxc#257]
Before I could get XMPP to login correctly, the entire login process to ownCloud was halted. Yes, you could use the "login without chat", but I think a better solution would be to first log into ownCloud, and then log into XMPP. So basically your ownCloud window loads with the XMPP sidebar visible, but you not yet logged into XMPP, THEN it starts logging into XMPP (just like when you re-login to XMPP when/if you drop that connection). 

This would make login into ownCloud quicker (you don't need that extra login progess bar) and there is no risk of temporarily breaking the ownCloud login (while I saw the "login without chat" option, my parents who are tech-illiterate, did not... which is probably gonna be the case for many peoples friends etc)

**Comment by sualko** [comment]
> I think a better solution would be to first log into ownCloud, and then log into XMPP

This is not possible, because jsxc reuses the login credentials to authenticate against the xmpp server.

> there is no risk of temporarily breaking the ownCloud login

This is on the list for v3.0. I leave this issue open, until it is done.
