### ISSUE TITLE
[ojsxc] UUID is used when trying to add a contact rather than the login name

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#258]
In our scenario we are using ownCloud with LDAP auth. As UUID within ownCloud the LDAP attribute `uid` is chosen which differs from the login name being used (attribute `cn` in our case).

When I try to add a new contact in ojsxc and click on a result of the autosuggest results the oC-internal UUID (`uid`) is inserted rather than the login name (`cn`), which is not the intended behaviour.
##

**Comment by sualko** [comment]
> Bad news for you: Nope, login names are not stored centrally and backends also 
do not offer a way to look up login names. Also I fail to see a cheap or new 
solution (other than  requiring the LDAP admin to also include the login name 
attributes in the user search attributes and just use the user search to 
accomplish the task). 

>The share dialog, for instance, is also looking up users like this.

From https://mailman.owncloud.org/pipermail/devel/2016-January/001982.html

**Comment by DanScharon** [comment]
in our case `cn` is already among the user search attributes, but that still leaves you to map the `uid` to the `cn` (or another search or login attribute for other setups, like `mail`).

**Comment by DanScharon** [comment]
would it be possible to use `displayName2`?
See https://github.com/owncloud/core/pull/22102

**Comment by DanScharon** [comment]
looks good
