### ISSUE TITLE
Verification (question/answer) of otr session doesn't show question or input for answer

### ISSUE THREAD

**Issue by efelon** [jsxc/jsxc#259]
jsxc version 2.1.5
used with owncloud 8.2.2
browser: firefox 40.0.2 and internet explorer 11.0.9600.18097

When jsxc should be verified with question/answer by another user, only a textbox (and message within the chat) is displayed:
```
Verification

Authenticating a contact helps ensure that the person you are talking to is really the one they claim to be.
```
Starting a question/answer verification from jsxc works.

**Comment by sualko** [comment]
I can confirm your issue and it will be fixed with the next release.
