### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by schickel007** [jsxc/jsxc#26]
Hi,

1st, my setup:
Ubuntu 13.10 server
Apache 2.4.6
Owncloud 6.0.2
ejabberd 2.1.10

I follow your installation-steps and after entering BOSH url to /http-bind/ and XMPP domain localhost - Save settings I get: BOSH Server reachable

=> everything seems fine

But I have 2 issues:
1. Chat-Window say: No connection, Log in (I've translated ;))
If I try to log in, a new window appear with:
Username: {{my_jid}}
Password:
If I put my OC password in, login failed. With my username and password also login failed.
1. After loging out, I can't log in anymore. I also see the hint with mod_proxy and mod_proxy_http, but adding this in the ejabberd.cnf under modules, ejabberd don't start.

Can you tell me, what is wrong and what I must do, to make it done?

**Comment by hguru** [comment]
can't connect logging with openfire (username and password) but, the bosh url is reachable

**Comment by sualko** [comment]
@hguru Why do you post to such an old issue? Please open a new issue with detailed information about your version and config.

**Comment by hguru** [comment]
now solve

**Comment by hguru** [comment]
Do the android version exist ?
