### ISSUE TITLE
[ownCloud app] please get rid of sass

### ISSUE THREAD

**Issue by DeepDiver1975** [jsxc/jsxc#262]
Within owncloud we prefer not to use js and css preprocessors in order to keep the technical level not that high for new contributors.

Please move over to pure css - THX

https://github.com/owncloud/jsxc.chat/tree/master/scss

**Comment by sualko** [comment]
Sorry, but I cannot give up a technology, which simplifies my life as a developer in such a big way. 

I think also e.g. the guys from Diaspora would be upset if we move back to css. It is also a huge benefit for an app like jsxc to use variables in css to generate custom styles for different host systems.
