### ISSUE TITLE
[ownCloud app] build guide would be great as well

### ISSUE THREAD

**Issue by DeepDiver1975** [jsxc/jsxc#263]

**Comment by sualko** [comment]
Currently we have only our [developer notes](https://github.com/jsxc/jsxc/wiki/Developer-notes) and a makefile #220 for the core. But you are right, we should improve the developer documentation.

**Comment by sualko** [comment]
I updated our developer notes and added a Makefile to jsxc.owncloud. I think this is currently enough, but PR and wiki articles are always welcome.
