### ISSUE TITLE
[ownCloud app] enable travis and write tests

### ISSUE THREAD

**Issue by DeepDiver1975** [jsxc/jsxc#264]

**Comment by sualko** [comment]
Duplicate of #191.

But hints and experiences in how to do js testing in a peer to peer scenario are always welcome.

**Comment by LEDfan** [comment]
@DeepDiver1975 I'm preparing some unit tests for the PHP backend, can you link the repo (in organization) with travis?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I'm preparing some unit tests for the PHP backend, can you link the repo (in organization) with travis? tnx

done - thx

**Comment by pmgouveia** [comment]
a docker image with a browser installed, chromium or firefox...

then run the tests in the docker image..

https://chimp.readme.io/docs/cucumberjs

I don't known how to make it possible running the tests with two browsers open or how-to change between tabs...
