### ISSUE TITLE
Authentication failure for...

### ISSUE THREAD

**Issue by HLFH** [jsxc/jsxc#265]
I did : 

1. https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-ArchLinux
2. https://github.com/jsxc/jsxc/wiki/Prepare-nginx
3. https://github.com/jsxc/jsxc/wiki/Install-ojsxc-(owncloud)
Then:

Bosh url: https://dhautefeuille.eu/http-bind/
XMPP domain: dhautefeuille.eu
TURN Url: numb.viagenie.ca
TURN Username: myemail@gmail.com
TURN Credential: mysuperpassword

I'm using ownCloud 8.2.2 and ArchLinux, nginx, PHP 7 with PHP-FPM, MariaDB, Redis.

But I got Authentication failure: 
`
"received data response:
[0,0]
2016-01-19 14:54:40.064 [info] <0.711.0>@ejabberd_c2s:wait_for_feature_request:774 ({socket_state,ejabberd_http_bind,{http_bind,<0.710.0>,{{127,0,0,1},45554}},ejabberd_http_bind}) Failed authentication for HLFH@dhautefeuille.eu from 127.0.0.1
2016-01-19 14:54:40.064 [debug] <0.712.0>@ejabberd_http_bind:prepare_response:900 OutPacket: [{xmlstreamelement,{xmlel,<<"failure">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[{xm
lel,<<"not-authorized">>,[],[]}]}}]
2016-01-19 14:54:40.064 [debug] <0.712.0>@ejabberd_http_bind:send_outpacket:1042  --- outgoing data ---
<body xmlns='http://jabber.org/protocol/httpbind'><failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/></failure></body>`

I don't know what to do...

My ownCloud user is HLFH.

**Comment by sualko** [comment]
Did you add dhautefeuille.eu to the hosts of ejabberd?

**Comment by HLFH** [comment]
@sualko Yes, this is `ejabberd.yml` https://gist.github.com/HLFH/ccc792366ba8db20148a

And dhautefeuille.eu.conf:

```nginx
upstream php-handler {
    server unix:/var/run/php-fpm/php-fpm.sock;
}
server {
    listen 80;
    server_name dhautefeuille.eu;
    return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name dhautefeuille.eu;
    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /etc/letsencrypt/live/dhautefeuille.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dhautefeuille.eu/privkey.pem;
    ssl_protocols TLSv1.2;
    ssl_ciphers EECDH+AESGCM:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 1d;
    # Diffie-Hellman parameter for ECDHE ciphersuites
    ssl_dhparam /etc/ssl/nginx/dhparam.pem;
    ssl_ecdh_curve secp384r1;
    # Add headers to serve security related headers
    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;
    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/letsencrypt/live/dhautefeuille.eu/chain.pem;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    # Path to the root of your installation
    root /usr/share/webapps/owncloud/;
    # set max upload size
    client_max_body_size 10G;
    fastcgi_buffers 64 4K;
    # Disable gzip to avoid the removal of the ETag header
    gzip off;
    # Uncomment if your server is build with the ngx_pagespeed module
    # This module is currently not supported.
    #pagespeed off;
    rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
    rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
    rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;
    index index.php;
    error_page 403 /core/templates/403.php;
    error_page 404 /core/templates/404.php;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README) {
        deny all;
    }

    location / {
        # The following 2 rules are only needed with webfinger
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
        rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
        rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
        try_files $uri $uri/ /index.php;
    }

    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true;
        #Avoid sending the security headers twice
        fastcgi_pass php-handler;
        fastcgi_intercept_errors on;
        fastcgi_read_timeout 1000;
    }
    # Adding the cache control header for js and css files
    # Make sure it is BELOW the location ~ \.php(?:$|/) { block

    location ~* \.(?:css|js)$ {
        add_header Cache-Control "public, max-age=7200";
        # Add headers to serve security related headers
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        # Optional: Don't log access to assets
        access_log off;
    }
    # Optional: Don't log access to other assets

    location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|swf)$ {
        access_log off;
    }

    location /http-bind {
        proxy_pass http://127.0.0.1:5280;
    }
}
```

**Comment by sualko** [comment]
Sorry, I should consider to implement jsxc/jsxc#46. Please adjust the value of <code>$oc_root</code> in <code>auth_ejabberd_oc.php</code>.

**Comment by HLFH** [comment]
In `auth_ejabberd_oc.php`, this is my: `$oc_root = '/usr/share/webapps/owncloud/';`

` '/usr/share/webapps/owncloud/` is where my ownCloud webapp is located. Btw, my ownCloud data is located in `/srv/http/data`. I guess I have nothing to change. And apparently, https://github.com/jsxc/jsxc/issues/46 should be fixed to fix my issue, if I understand well.

**Comment by sualko** [comment]
> And apparently, #46 should be fixed to fix my issue, if I understand well.

No, #46 is only an improvement.

Does the following return 1?

```
sudo -u ejabberd auth_oc_user.php /usr/share/webapps/owncloud/ HLFH@dhautefeuille.eu PASSWORD
```

**Comment by HLFH** [comment]
```bash
[root@arch-server ~]# sudo -u ejabberd /etc/ejabberd/auth_oc_user.php /usr/share/webapps/owncloud/ HLFH@dhautefeuille.eu mysuperpassword
Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory

See https://doc.owncloud.org/server/8.2/go.php?to=admin-dir_permissions
```

Should I give write access to the config directory to the user `ejabberd`? `ejabberd` is in the `http` group, but it does not seem to be sufficient, so, for that purpose, should I add `ejabberd` in the ACL related to the config folder?

**Comment by sualko** [comment]
After each update, oc removes the group permission from the config file. Just rerun

```
sudo chmod -R g+w /usr/share/webapps/owncloud/config
```

**Comment by HLFH** [comment]
Thanks. I now got the issue: Data directory (/srv/http/data) not writable by ownCloud

**Comment by sualko** [comment]
Try to fix your permissions. Is ejabberd really in the http group? Is your webserver really running as user http? Is your data folder owned by the group http?

**Comment by HLFH** [comment]
Is ejabberd really in the http group? Yes
Is your webserver really running as user http? Yes, http user with nginx webserver
Is your data folder owned by the group http? Yes

```bash
setfacl -Rdm u:ejabberd:rwx /srv/http/data/
setfacl -Rm u:ejabberd:rwx /srv/http/data/
setfacl -Rdm g:ejabberd:rwx /srv/http/data/
setfacl -Rm g:ejabberd:rwx /srv/http/data/
```

No more issues. Solved. Thanks a lot!!
