### ISSUE TITLE
Error with Owncloud 8.2.2

### ISSUE THREAD

**Issue by Ludovicis** [jsxc/jsxc#267]
I have this problem with the last owncloud package:

Uncaught TypeError: Cannot read property 'indexOf' of nullStrophe.Connection @ jsxc.dep.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:2030jsxc.xmpp.login @ jsxc.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:941jsxc._onMaster @ jsxc.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:562jsxc.otr._createDSA @ jsxc.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:7114jsxc.otr.createDSA @ jsxc.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:7102jsxc.onMaster @ jsxc.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:514
jquery.min.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:6 XHR finished loading: GET "http://XXX/index.php/apps/files/ajax/getstoragestats.php?dir=%2F".send @ jquery.min.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:6x.extend.ajax @ jquery.min.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:6x.(anonymous function) @ jquery.min.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:6x.extend.getJSON @ jquery.min.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:6Files._updateStorageStatistics @ files.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:28Files.updateStorageStatistics @ files.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:50FileList.updateStorageStatistics @ filelist.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:1415(anonymous function) @ files.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:343(anonymous function) @ eventsource.js?v=37b3e45c9b85f1b59411dbbf10f2f6ec:144

Anybody can explain to me why i have this error ?
Thanks,

**Comment by sualko** [comment]
Did you set bosh url in admin settings?

**Comment by Ludovicis** [comment]
Thanks sualko for your help, before i could use without problem Xmpp owncloud plugin. But with the last version of ownclood i can't. 
And yes i have set Bosh in admin setting the test of save is good...
How can i help you to debug my XMPP plugin install ?

**Comment by Ludovicis** [comment]
Thanks sualko (klaus) for your help, before i could use without problem
Xmpp owncloud plugin. But with the last version of ownclood i can't.
And yes i have set Bosh in admin setting the test of save is good...
How can i help you to debug my XMPP plugin install ?
I use also the last OpenFire server (Version 4) maybe before i used 3.10.3

2016-01-21 14:01 GMT+01:00 Klaus <notifications@github.com>:

**Comment by sualko** [comment]
Easiest option would be to send me some test credentials to klaus@jsxc.org.

**Comment by sualko** [comment]
ping @Ludovicis

**Comment by Ludovicis** [comment]
Hello Klaus,

Sorry for the delay, my job take a lot of time...
I have test your last jsxc owncloud plugin and i have again an error :(
My openfire config
[image: Images intégrées 1]

My owncloud setting
[image: Images intégrées 2]

My apache configuration

ServerAdmin webmaster@localhost
DocumentRoot /var/www/owncloud
<Directory /var/www/owncloud/>
        Options +FollowSymLinks
        AllowOverride All
        order allow,deny
        allow from all
</Directory>

ProxyPass /http-bind/ http://cloud:7070/http-bind/
ProxyPassReverse /http-bind/ http://cloud:7070/http-bind/

a list of module
[image: Images intégrées 3]

I don't understand why i have not the tchat icon in the right top corner of
owncloud... I have got it at the beginning, just after the application
installation. But now i have no more this icon.

In openfire i have create group user and i have put some user in this group.
But not the all user for the test, same result with all user

P.S: Sorry for my poor english ;)

2016-02-02 12:58 GMT+01:00 Klaus <notifications@github.com>:

**Comment by Ludovicis** [comment]
I have also this error in my apache log when i save the java xmpp client
setting in admin page:
[authz_core:error] [pid 29058] [client 192.0.0.215:46571] AH01630: client
denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

Maybe my setting is not saved...

2016-02-03 10:31 GMT+01:00 Ludovic Tourtelier <ltourtelier@gmail.com>:

**Comment by Ludovicis** [comment]
PHP Fatal error:  require_once(): Failed opening required '/var/www/owncloud/apps/ojsxc/appinfo/../vendor/autoload.php' (include_path='/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/apps/ojsxc/appinfo/app.php on line 37

**Comment by sualko** [comment]
Did you try the latest package? https://github.com/owncloud/jsxc.chat/releases/tag/v3.0.0-beta1b Because in the first beta package the vendor folder was missing.

Btw are you using oc asset pipelining? #255

**Comment by Ludovicis** [comment]
Yes i use the last update 
I copy the jsxc.chat-master in apps
right rwxr-x--- www-data to the directory
i rename jsxc.chat-master to ojsxc 
And i active the app in admin panel and error in apache.log:
in /var/www/owncloud/apps/ojsxc/appinfo/app.php on line 37
I have no more access to my owncloud, blanck page

**Comment by sualko** [comment]
As usual you have to download <code>ojsxc-3.0.0-beta1b.zip</code> or use the content of the build folder.

**Comment by Ludovicis** [comment]
with the content of the build folder directly in ojsxc, no blanck page in owncloud and no more error in app.php line 37...
But when i save the xmpp configuration in owncloud admin panel, i have this error:
AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

I know than this error it's not the fault of xmpp plugin

**Comment by sualko** [comment]
> AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

It is only a test from owncloud to ensure, that the data folder is not accessible from the internet.

> With admin or other user no tchat application in top right corner in owncloud

Btw are you using oc asset pipelining (#255)? This is my last idea, why jsxc fails in our installation.

**Comment by Ludovicis** [comment]
Thanks for your help sualko
With and without oc asset pipelining no tchat...
in config.php:
  'asset-pipeline.enabled' => false,
or 
  'asset-pipeline.enabled' => true,

**Comment by Ludovicis** [comment]
sualko if you have the time to take the hand on my server ? can you share with me in private your mail adress, please

**Comment by Ludovicis** [comment]
in firefox 43.0.4

16:49:09,868 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create1 jsxc.dep.js:8371:3

if i follow the link http://x/apps/ojsxc/js/jsxc/lib/jsxc.dep.js?v=794568d0e6a93897ee92fa732600270b
i got the tchat application in right top corner...

**Comment by sualko** [comment]
Thought you are not able to send me some test credentials, because it is only available in your intra net? My mail address is still klaus@jsxc.org.
