### ISSUE TITLE
[Discussion] How to implement presence 

### ISSUE THREAD

**Issue by LEDfan** [jsxc/jsxc#269]
In this issue I would like to discuss several things about the presence implementation. 

## XMPP

So if I understand correctly precense in XMPP works this way:
 - you have 6 statuses which the user can choose (online, offline, away, chatty, extended away and do not disturb). I though that you could set a custom state, but it looks like this isn't implemented in JSXC. (looks good to me :P )
 - when you start a chat session (i.e. opening ownCloud) the XMPP server (owncloud) sends the presence of all users with the following stanza: 
````
<body xmlns='http://jabber.org/protocol/httpbind'><presence xmlns='jabber:client' from='user@host' to='user@host' type='unavailable'/></body>
```` 
 - a user can change it's current state via the UI, the client sends it's state to the server via:
````
<body rid='' xmlns='http://jabber.org/protocol/httpbind' sid=''><presence xmlns='jabber:client'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://jsxc.org/' ver='u2kAg/CbVmVZhsu+lZrkuLLdO+0='/><show>chat</show></presence></body>
````
 - when a user logs in, the client sends it current state via:
````
<body xmlns='http://jabber.org/protocol/httpbind' ><presence xmlns='jabber:client'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='' ver='u2kAg/CbVmVZhsu+lZrkuLLdO+0='/></presence></body>
````
````
<body rid='' xmlns='http://jabber.org/protocol/httpbind' sid=''><presence xmlns='jabber:client'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://jsxc.org/' ver='u2kAg/CbVmVZhsu+lZrkuLLdO+0='/><show>dnd</show></presence></body>
````
 - only the client keeps track of a user current state (so logging into a new client change the user's current state)
 - there is a subscription model where the user can choose which of the user's presence he wants to keep track
 - @sualko is it possible for a user to login at one server multiple times simultaneous? If I try with ownCloud, the last logged in session is master and the other connections are logged out.

## Implementation in ownCloud
 -  I would assume/hard code that all users are subscribed to each other.
 - We would need a place to store someone's presence. A database is always available so we should start with that. Basically we only need to store a field `user` and a field `presence`. Then when a user opens a connection it sends the presence of all other users, fetched from this table. 
 - like with the locking mechanism we could use Memcache for this too. This wouldn't be too hard since it's just a key/value. Will all memcache backends keep this information for long enough time? So when someone restart PHP and is using APCU is the information than gone? Same with a reboot. @DeepDiver1975 @MorrisJobke @PVince81 do you know this? :smiley: EDIT:
 - redis and memcache are persistent, xcache and apc(u) not. I think the best option would be to let the user decide. If he is using redis/memcache there isn't a risc and when he is using apcu/xcache there is a small risc. (and it's only for online state not very important imo)

@sualko is my understanding of the XMPP presence correct?

**Comment by DanScharon** [comment]
>  @sualko is it possible for a user to login at one server multiple times simultaneous? If I try with ownCloud, the last logged in session is master and the other connections are logged out.

that is part of the XMPP Core definition and is handled via the 'resource': https://xmpp.org/rfcs/rfc6120.html#bind

> We would need a place to store someone's presence. A database is always available so we should start with that

please no. 
Things like that are handled via PubSub ([XEP-0060](https://xmpp.org/extensions/xep-0060.html)) and PEP ([XEP-0163](https://xmpp.org/extensions/xep-0163.html) and [XEP-0207](https://xmpp.org/extensions/xep-0207.html)). Please have a careful look especially into XEP-207.
This means that you don't need an additional persistence layer as this data is stored on the XMPP-Server.

**Comment by LEDfan** [comment]
Thanks for your reaction.

> that is part of the XMPP Core definition and is handled via the 'resource': https://xmpp.org/rfcs/rfc6120.html#bind

Of course, I forgot about the resource.... But in our situation there would be only one resource at the moment. (ownCloud itself) So not a problem for now.

> please no. 
I understand that it isn't ideally. But we are implementing a very simple XMPP (actually sort of combination with BOSH since it only supports HTTP) server in PHP. So we can use the JSXC client and not have to worry about client side technology (in the browser). This means we have no running server or daemon. Only direct PHP requests. The goal of this is to have an instant working chat solution. If a large installation wants a good chatting server it will install something like ejabberd.

We also need a database table for broadcasting messages etc. (not ideally again)

**Comment by sualko** [comment]
> you have 6 statuses which the user can choose...

Correct.

> when you start a chat session (i.e. opening ownCloud) the XMPP server (owncloud) sends the presence of all users with the following stanza:

Nope.  The server sends the presence only after you send your initial presence to the server. http://xmpp.org/rfcs/rfc6121.html#presence-initial

> a user can change it's current state via the UI, the client sends it's state to the server via:

In general yes, but there is  an exceptions: Unavailable presence is indicated through the type attribute. Please not that you should forward all child elements (e.g. the c element is optional).

> when a user logs in, the client sends it current state via:

jup

> only the client keeps track of a user current state

yes

> there is a subscription model where the user can choose which of the user's presence he wants to keep track

yes

> is it possible for a user to login at one server multiple times simultaneous?

yes, but only in two different browsers.

> I would assume/hard code that all users are subscribed to each other.

agree

> We would need a place to store someone's presence. A database is always available so we should start with that. Basically we only need to store a field user and a field presence.

Agree. You should add a <code>last_active</code> field, because most users do not use the logout button ;-).

> like with the locking mechanism we could use Memcache for this too.

You are the expert ;-).

> please no.

I think you got this point wrong.

**Comment by LEDfan** [comment]
@sualko for the `last_active` field, this should be updated every time the user connects to the server, right?
After how many seconds should the user set the state of a user to offline? In the BOSH XEP I read
> If the connection manager has responded to all the requests it has received within a session and the time since its last response is longer than the maximum inactivity period, then it SHOULD assume the client has been disconnected and terminate the session without informing the client. If the client subsequently makes another request, then the connection manager SHOULD respond as if the session does not exist.
> If the connection manager did not specify a maximum inactivity period in the session creation response, then it SHOULD allow the client to be inactive for as long as it chooses.

But since we assume there is already a BOSH connection (and don't use rid/sid) the client don't provide this.

**Comment by sualko** [comment]
> connection manager did not specify a maximum inactivity period in the session creation response

The server is providing this information. But this just btw.

I think a common value for this timeout is 30 minutes, so after this time your implementation should mark the user as offline and announce it to all users which have a valid subscription for that user (as far as you support subscriptions at the moment) and are online.

**Comment by LEDfan** [comment]
Okay thanks again!

**Comment by LEDfan** [comment]
> I think a common value for this timeout is 30 minutes, 
Isn't this a lot of time? I read in the standard that the client should create a new request as soon as another request closes. Since with every request we update the last_active this would mean that if a users closes his session 30 minutes later he will be marked offline.

**Comment by nitmir** [comment]
Prosody disconnect inactive bosh session with the following message : "Disconnected: BOSH client silent for over 60 seconds"

**Comment by nitmir** [comment]
In fact, It seems that the client can choose the delay with the wait attribute of the body tag cf https://xmpp.org/extensions/xep-0124.html section 7.1
1min seems more reasonable to me to detect disconnected client because or network failure or just because they closed their browser.

**Comment by sualko** [comment]
Now I had some time to read XEP-0124 and I found 3 timeouts:

- **wait** "This attribute specifies the longest time that the connection manager is allowed to wait before *responding* to any request". It is the maximum time for the long-polling request.

- **inactivity** "the client SHOULD make a new request as soon as possible" .... "The RECOMMENDED time would be a little more than the number of seconds for a comfortable network round trip". This is the time @LEDfan was asking for. 

- **maxpause** "If a client encounters an exceptional temporary situation during which it will be unable to send requests to the connection manager for a period of time greater than the maximum inactivity period (....), then the client MAY request a temporary increase to the maximum inactivity period by including a 'pause' attribute in a request." This would be an additional feature.

The wait value is chosen from the client (e.g. Strophe uses 60 sec). Inactivity and maxpause is chosen from the server (e.g. ejabberd uses 30 and 120 sec).

**Comment by LEDfan** [comment]
So a good time would be to use `sleep_time * max_cycles + 5`? I.e. if the server sleeps 1 second and does this 10 times the timeout would be 15 seconds.

**Comment by sualko** [comment]
Just use 30 seconds. I don't know what max_cycles is, but 30 seconds should be good enough.

**Comment by sualko** [comment]
owncloud/jsxc.chat#19 was merged
