### ISSUE TITLE
Log in JSXC with phonegap

### ISSUE THREAD

**Issue by nasanchez** [jsxc/jsxc#270]
I'm trying to log in to my openfire server with a phonegap app. It works well in a navigator but the same code in phonegap app always is at Strophe state CONNECTING.

Anybody knows what happens?

**Comment by nasanchez** [comment]
I'm sorry, it was a server problem.

**Comment by sualko** [comment]
Happy that you could resolve your issue. Maybe you want to tell us a little about your project, because I am very interested in this topic. In my opinion there is no good mobile xmpp client and therefore jsxc could maybe step into this gap.

**Comment by nasanchez** [comment]
Thanks for your interest! I'm trying to add JSXC chat to my phonegap app. This app shows several KPI's and the objective is let the users to talk about the graphs or tables that they are watching in the app through the JSXC chat. Is just for this that I want to integrate it in the same app. 

In addition, I want to develope another functionalities as a registry or send images and video with JSXC. If you want to talk about this, you can write me at this email: natalia.sanchez@industrylabs.biz

**Comment by sualko** [comment]
> I want to develope another functionalities as a registry

There is already an open issue for that #178. Feel free to create a pr for that.

>  or send images and video

The next major release (beta is coming this week) will contain file transfer via webrtc.
