### ISSUE TITLE
Assign minimum required oc version

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#272]
We should check the minimum required oc version for jsxc and assign it in info.xml. Lowest maintained oc version is currently 7.0, but only until [2016-05](https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule).

We should also get rid of all legacy styles and conditions, like jsxc.oc.lte6.scss.

**Comment by sualko** [comment]
With oc 7 I get <code>Identifier "OCP\IConfig" is not defined.</code> in the new internal server implementation. Now we have 2 choices:

- create an extra version for oc 7 without internal server
- drop support for oc 7

@MarcelWaldvogel @DanScharon @LEDfan What do you think?

**Comment by sualko** [comment]
oc 8.0 fails in <code>appinfo/routes.php(33)</code> with

```
strtoupper() expects parameter 1 to be string, array given at /var/www/owncloud-8.0/lib/private/appframework/routing/routeconfig.php#79

Routing requirement for "_method" cannot be empty.
```

**Comment by DanScharon** [comment]
4 months until EOL is quite short, so I'd say drop support for oc 7

**Comment by LEDfan** [comment]
I don't think there are many people who are interested in this app and are running oC7. So I would say to drop the support.

@sualko I'll try to run the unit/integration tests via travis on 8.0, 8.1,8.2 and master. (Not sure if it's possible).

**Comment by sualko** [comment]
@LEDfan That would be great. 

Currently jsxc will break oc 8.0, because it doesn't accept an array as verb:
```
array('name' => 'http_bind#index', 'url' => '/http-bind', 'verb' => array('GET', 'POST'))
```
Post should be enough or not?
```
array('name' => 'http_bind#index', 'url' => '/http-bind', 'verb' => 'POST')
```
(btw http-bind requests fails anyway with an internal server error)

**Comment by sualko** [comment]
Ok, we drop support for Owncloud 7 and below.

**Comment by MarcelWaldvogel** [comment]
Dropping OC7 is fine with me. If there is a big demand (which I doubt), we can reconsider. 
Beste Grüsse,
-Marcel Waldvogel
(kurz&bündig da mobil)
