### ISSUE TITLE
Update OC App Metadata

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#274]
This issue is intended to collect all missing or outdated data in [info.xml](https://doc.owncloud.org/server/8.0/developer_manual/app/info.html):

- &lt;requiremin> version (#272) (replace &lt;require>)
- &lt;documentation>
- &lt;repository>
- &lt;dependencies> @LEDfan this should be your part :smiley:

**Comment by sualko** [comment]
ping @LEDfan

**Comment by LEDfan** [comment]
The app is tested (unit and integrations) to work with PHP 5.4 and later, PHP 7,  ownCloud from 8.0 and `pgsql`, `mysql`, `sqlite`. So that shouldn't be a problem. 
For parsing the XML we use sabre-xml, which requires https://github.com/fruux/sabre-xml/blob/master/composer.json#L9-L12 . So that would be:
````
<lib min-version="2.6.20">libxml</lib>
<lib>xmlreader</lib>
<lib>xmlwriter</lib>
<lib>dom</lib>
````

**Comment by LEDfan** [comment]
Note that as long as you include the vendor directory there shouldn't be a problem with the requirement of the library. Note that the `require-dev` dependencies aren't needed in the build package. (https://github.com/owncloud/jsxc.chat/blob/master/composer.json#L5)  Which will save a bit of package size. :P Use the `--no-dev` flag for this.

**Comment by sualko** [comment]
So we do not need the following?
```
<lib min-version="2.6.20">libxml</lib>
<lib>xmlreader</lib>
<lib>xmlwriter</lib>
<lib>dom</lib>
``` 
Do we require any special cache backend? I guess not, because we use database as fallback.

> Note that the require-dev dependencies aren't needed in the build package. 

Good point.

Are you fine with a new beta release tomorrow?

**Comment by LEDfan** [comment]
```
<lib min-version="2.6.20">libxml</lib>
<lib>xmlreader</lib>
<lib>xmlwriter</lib>
<lib>dom</lib>
````
We still needs this, but I don't think this would be a problem since I guess core needs this to.
