### ISSUE TITLE
Send file dialog blocks chat windows after canceling

### ISSUE THREAD

**Issue by efelon** [jsxc/jsxc#277]
ojsxc 3.0.0-beta1

- Open a new Chat window
- Select "Send file" from chat window menu
- Select "Cancel"
 - "Select file" dialog within chat window blocks further operation

**Comment by sualko** [comment]
While there is no clean way to detect if the user cancels the file chooser, I added a close handler to the overlay:

![screen shot 2016-02-10 at 10 46 01](https://cloud.githubusercontent.com/assets/2974196/12943761/a30145e4-cfe3-11e5-8c7c-ccf6ac320875.png)
