### ISSUE TITLE
Newline character of incoming messages are not interpreted in chat window

### ISSUE THREAD

**Issue by efelon** [jsxc/jsxc#278]
3.0.0-beta1 and before

The newline character "\r\n" are correctly displayed in the ojsxc debug log but not in the chat window.

Although sending a newline is not supported, couldn't it be possible to display them for incoming messages?

p.s. offtopic
Isn't it possible to enter a newline in ojsxc with a key combination like "alt"+"enter" or "ctrl"+"enter"?

**Comment by sualko** [comment]
I think this is related to [XEP-0071](http://www.xmpp.org/extensions/xep-0071.html).

Commit 60b3318 displays line breaks, but sending is out-of-scope for 3.0. Maybe someday this will be possible, so this issue stays open.

**Comment by efelon** [comment]
Thanks a lot, sualko. I already assumed that sending is on a total different page.

Btw. I really like the new design of the current beta version. I'm using it on a daily bases.

**Comment by sualko** [comment]
I am glad that you like the new design and thanks for reporting issues.
