### ISSUE TITLE
Error on receiving files

### ISSUE THREAD

**Issue by nasanchez** [jsxc/jsxc#279]
I have an error on receiving files but I don't have idea about how to solve it. Anyone can help me?

This is the error:
Uncaught (in promise) Failed to set local answer sdp: Called in wrong state: STATE_INPROGRESS

**Comment by sualko** [comment]
Please provide more information, like:

- Which file type?
- Across NAT?
- TURN configuration?
- Can you reproduce this?
- Any [debug](https://github.com/jsxc/jsxc/wiki/Debugging) messages?
- Which jsxc version?
- line of error?

**Comment by vishalvp1980** [comment]
I have also faced the same problem, but while sending file from Chrome, for Mozilla it works fine.

The console shows message as follows.

**Uncaught (in promise) Failed to set remote answer sdp: Offer and answer descriptions m-lines are not matching. Rejecting answer.
(anonymous function) @ jsxc.dep.js:20365**

**Comment by sualko** [comment]
Probably this is an error in the jingel lib https://github.com/otalk/jingle.js/. I will check that.

**Comment by sualko** [comment]
Which browser versions do you use?

**Comment by vishalvp1980** [comment]
Sorry for the delayed response, I use Chrome version 49

**Comment by nasanchez** [comment]
On my case, new version solved it. Thanks!

**Comment by vishalvp1980** [comment]
Which version of Chrome, i am facing the same issue on Chrome 49.

**Comment by nasanchez** [comment]
It works for me on Chrome 49

**Comment by sualko** [comment]
Latest version is 50.0.2661.86. Please test and verify if this solves your issue.

**Comment by sualko** [comment]
Can we close this issue?

**Comment by nasanchez** [comment]
Yes, it's all ok for me
