### ISSUE TITLE
owncloud websocket support

### ISSUE THREAD

**Issue by royalterra** [jsxc/jsxc#280]
There 100 of tickets about issues with Http-bind and really I not have idea what goin on I can connect easy with any vhost in my server but not in owncloud . Some times disconnect when you change any link inside owncloud and not coming back if you not do re-login. can be a good idea if we have websockets support easy to configure easy for works

**Comment by MarcelWaldvogel** [comment]
Most of the problems are about

* users not reading the documentation
* ownCloud having changed the content-security-policy with almost every version (the other JSXC plugins have not had these problems)

Neither will not be resolved with WebSockets. However, ownCloud has recently added APIs for CSP which allow this to be resolved for the upcoming 3.0 release of JSXC (currently in beta). 

(And yes, we are aware of WebSockets and its advantages and therefore will continue to consider it if an appropriate XMPP WebSockets library becomes available.)


Viele Grüsse,
-Marcel Waldvogel
(kurz&bündig, da mobil)

**Comment by royalterra** [comment]
I believe there few Websocket library open source one really very important feature is missing is option in administration  to remove login with jscx and login just like that with chat.  And will be perfect add the class.jabber.php for in case the user is not in the xmpp server simple create the user with the password use for login. That I believe will make perfect JSXC in owncloud 

The issue logout after change screen in Owncloud I see is only with Google Chrome I not have that issue in Firefox

**Comment by sualko** [comment]
Strophe.js supports already websockets, but this is not suitable for uninterrupted browsing among pages.

> Some times disconnect when you change any link inside owncloud and not coming back if you not do re-login.

Please try your latest [beta build](https://github.com/owncloud/jsxc.chat/releases) and report any bugs in a new issue. See also our [reporting bugs guide](https://github.com/jsxc/jsxc/wiki/Contributor-Guide).
