### ISSUE TITLE
No Video with example ?

### ISSUE THREAD

**Issue by shikka** [jsxc/jsxc#281]
HI
I've tried your provided example (v3.0.0 Beta 2), but can't get a working video stream only Audio (Firefox 39/43). Is there something that I'am missing or is that not implemented yet ? 

Thanks

Log from Connection: 

[webrtc.txt](https://github.com/jsxc/jsxc/files/139108/webrtc.txt)

Seems like the connection works.

ok, it's caused by this function in jsxc.lib.webrtc

   $('#jsxc_webrtc .jsxc_videoContainer').toggle(function() {
      $('#jsxc_webrtc .jsxc_controlbar').css('opacity', '1.0');
   },

**Comment by sualko** [comment]
Sorry I am currently busy and will investigate your issue if I have more time.

Did you the test over NAT or just in your local network?

**Comment by shikka** [comment]
No problem, only in my local network. I think it's only a css issue. 

I just commented these 
$('#jsxc_webrtc .jsxc_videoContainer').toggle(function() {
$('#jsxc_webrtc .jsxc_controlbar').css('opacity', '1.0');
},

lines out and everything is working.

**Comment by sualko** [comment]
Please uncomment those lines and test again, because this could not be the root of your issue. It only shows or hides the control bar.

**Comment by tristan-k** [comment]
I'm also struggeling with this issue. I'm running ownCloud 8 with Version 3.0.
