### ISSUE TITLE
groupchat message handler is removed in presence of messages without ID

### ISSUE THREAD

**Issue by francescomilizia** [jsxc/jsxc#282]
Hello,
I noticed that the function jsxc.muc.onGroupchatMessage throws an exception if the received message does not have the 'id' attribute.
Here is an example of message sent by openfire to set the subject of a chatroom:

`<message xmlns="jabber:client" type="groupchat" from="room1@conference.ac-fmmilizia" to="user2@ac-fmmilizia/myresource">
<subject>mySubject</subject>
<delay xmlns="urn:xmpp:delay" stamp="2016-02-23T08:51:03.535Z" from="room1@conference.ac-fmmilizia"/>
</message>`

In the following code, if the 'id' is undefined, the method jsxc.Message.getDOM will fail invoking the replace operation.

```
onGroupchatMessage: function(message) {
      var id = $(message).attr('id');
      if (jsxc.el_exists(jsxc.Message.getDOM(id))) {
         // ignore own incoming messages
         return true;
      }
    ... 
    ...
}

jsxc.Message.getDOM = function(uid) {
   return $('#' + uid.replace(/:/g, '-'));
};
```

This error will cause the groupchat message handler being removed from the handler chain managed by Strophe, and than no other groupchat messages can be processed.

According to the XML schema found at http://xmpp.org, the id attribute is declared as "optional", so I think this is a bug of the message handler implementation.

Can you confirm my analysis?

Thank you.

**Comment by sualko** [comment]
You are right. It is not required, only recommended by [XEP-0045](xmpp.org/extensions/xep-0045.html).

Great report btw.
