### ISSUE TITLE
chat not visible if webrtc is disabled in firefox

### ISSUE THREAD

**Issue by kas70** [jsxc/jsxc#284]

**Comment by sualko** [comment]
Sorry, we need a little more information. Please describe your issue as detailed as possible.

**Comment by kas70** [comment]
I tried the chat on sechat.org. If you disable webrtc in firefox (`media.peerconnection.enabled`) the chat-bar is not visible any more.

**Comment by sualko** [comment]
Probably this should be addressed to https://github.com/otalk/jingle.js/, but I will check it next week.

**Comment by kas70** [comment]
thanks;)

**Comment by sualko** [comment]
I can not reproduce this behaviour and I also do not know, why someone would disable this option. Your issue should be reported to https://github.com/diaspora/jsxc, because I have no glue which version they currently using.
