### ISSUE TITLE
messages not showing on receiver's side

### ISSUE THREAD

**Issue by wojciech-kochanowski** [jsxc/jsxc#286]
We are trying to integrate your module in our application. So far we've been using version 1.1.0 and it worked fine. Now, we've decided to move to v3.0.0-beta2 and we're experiencing some issues: When a person A writes a message to person B, the receiver sees a message window popping up, but when he opens it, there is no message inside. 
There are no JS errors in the console, signing in and presence notifications work fine. 
XMPP server is ejabberd 2 community

**Comment by sualko** [comment]
Can you try to clear your localStorage? Just execute <code>localStorage.clear()</code> in your js console. Please [enable debugging](https://github.com/jsxc/jsxc/wiki/Debugging) and post the output of your js console.

**Comment by wojciech-kochanowski** [comment]
Can't say what was the problem here, but after setting everything up once again, it works fine. Thanks for the reply!

**Comment by sualko** [comment]
Please report if this occurs again.
