### ISSUE TITLE
Please provide demo deployment

### ISSUE THREAD

**Issue by andrey-utkin** [jsxc/jsxc#289]
It would be very handy if you provided demo mode so that anybody could use your webapp deployment to login to their own XMPP account on any XMPP server, just using their WebSocket or BOSH URL. Just like e.g. https://tryit.jssip.net or https://legastero.github.io/jingle-interop-demos/stanzaio/

Thanks.
##

**Comment by sualko** [comment]
Good idea. I will add such a demo to jsxc.org in the next days or weeks.

**Comment by extremeshok** [comment]
We would be willing to provide(sponsor) a vps for the demo.

Contact me admin-at-extremeshok-dot-com

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by sualko** [comment]
I think we can run this on our own server, because it is only a html page. But thank you for this offer anyway.

**Comment by mathiasertl** [comment]
I (from jabber.at) second this. We're currently looking into possibilities for a webchat solution, and JSXC is on the short list. That would make the decision making easier :-)

**Comment by sualko** [comment]
I updated the example, so you can insert your own bosh url and domain. Just download it from https://github.com/jsxc/jsxc/tree/master/example and open <code>index.html</code> in your favourite browser. If I have time, I will also upload it to our homepage.

![screen shot 2016-05-04 at 11 56 21](https://cloud.githubusercontent.com/assets/2974196/15010956/744229aa-11ef-11e6-9992-ea476eb907be.png)

**Comment by TwentyOneSolutions** [comment]
So there is no online demo?  Or links to some sites that use JXSC?  

It would be much easier to evaluate the project and compare it to other XMPP clients instead of  downloading the library and running the examples.  

Don't get me wrong -- I will download the project now and try it out, but it'd be nice to be able to do online first.

**Comment by sualko** [comment]
Can you test https://www.jsxc.org/example/? This was not officially announced yet, so a good test would be helpful.

**Comment by devluxg** [comment]
Did you actually test this @sualko ?  It's hard coded to connect to https://www.jsxc.org/http-bind/ even if you change the domain.  It looks like https://www.jsxc.org/http-bind/ is throwing a 404.

**Comment by ChristianTacke** [comment]
Do you plan to have a public xmpp MUC for user discussions?
That might also be a good use case for a demo deployment?

**Comment by wokawoka** [comment]
Hello,
I'm trying to test the demo using the credentials written in the page (user demo1 to demo5, password demo) but I can't log-in properly.

**Comment by sualko** [comment]
@wokawoka sorry for the inconvenience, I fixed it. Next time, please open an separate issue.

**Comment by wokawoka** [comment]
@sualko thanks for fixing it. Sorry, I'm relatively new to github so I'm still getting used to it. But why this issue is still open if a demo deloyment already exists since a while?

**Comment by sualko** [comment]
It's not open, it's closed, but you can still add comments.
