### ISSUE TITLE
Webcam active after hanging up

### ISSUE THREAD

**Issue by wojciech-kochanowski** [jsxc/jsxc#290]
When I end a video conference, the webcam remains turned on. That doesn't seem right and very safe. Is there a way to force the camera and microphone shutdown on hanging up?

**Comment by sualko** [comment]
>  processes for detaching source devices and so on have to be done on MediaStreamTrack anyway.

https://developers.google.com/web/updates/2015/07/mediastream-deprecations#stop-ended-and-active

Should be gone if we stop each track individually. Thanks for reporting.

**Comment by sualko** [comment]
Should be fixed with #283.
