### ISSUE TITLE
Retrieving messages from ejabberd server 

### ISSUE THREAD

**Issue by daryllchu** [jsxc/jsxc#291]
Firstly, love the project!

Understand currently that messages are stored locally. How do we retrieve messages from the ejabberd server instead? That is to say, all messages will come and go to the ejabberd server?

**Comment by sualko** [comment]
Sorry, I don't get your question. Are you looking for somthing like https://xmpp.org/extensions/xep-0136.html?

**Comment by daryllchu** [comment]
Sorry I didn't explain clearly. Was wondering how do we pull real time messages that are store in the ejabberd server? Meaning, we should be able to see all messages that transacts with the server instead of just those that are stored locally

**Comment by sualko** [comment]
It's not much clearer... We use BOSH to communicate with our chat server. Hope this answers your question.
