### ISSUE TITLE
Video/Voice in new tab

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#292]
Would it be possible to make the video/voice calling features open in a new tab rather than taking up and locking down the entire owncloud interface?  This way I could still use owncloud while in voice/video.  Under the current set up it seems impossible to chat or use any other owncloud features during a call.

Thanks,  love the new version 3 by the way!

**Comment by sualko** [comment]
This is currently not supported, but you can work in a second owncloud tab as usual. Just open a new tab, enter your oc url and here you go.
