### ISSUE TITLE
Troubles with initiating video call for the 2nd time

### ISSUE THREAD

**Issue by wojciech-kochanowski** [jsxc/jsxc#294]
I've stumbled upon an issue with video calls in your app: for the first time it works fine, but after ending a call, there's no way to connect again. After some debugging I've found out, that the hangUp method is being called right after the connection is established. Calling $(document).off('cleanup.dialog.jsxc'); after hanging up seems to do the trick. I'll just leave it here for your consideration :)

**Comment by sualko** [comment]
> I'll just leave it here for your consideration :)

Thank you. I will investigate this and a possible fix will be in the next bug fix release.

**Comment by nasanchez** [comment]
With this fix it works for me on the first call, but not on second call, yes on third call, not on fourth call and successively.
