### ISSUE TITLE
Problem hiding offline users by default

### ISSUE THREAD

**Issue by francescomilizia** [jsxc/jsxc#295]
Hello,
I've noticed a strange behaviour if you set the hideOffline option true by default: you can show offilne users from the user menu but you are not more able to hide them again.
Searching though the code I've found that you can not override a default boolean value set to 'true' with your local setting. In fact the following function

```
jsxc.options.get = function(key) {
         if (jsxc.bid) {
            var local = jsxc.storage.getUserItem('options') || {};
            return local[key] || jsxc.options[key];
         }
         return jsxc.options[key];
};

```

returns always true if the `jsxc.options[key]` is true.
I think it should return the `jsxc.options[key]` value only if  `local[key]` is undefined.

Is the `jsxc.options.hideOffline` property intended for define a default behaviour while initializing the chat client?

Thank you.

**Comment by sualko** [comment]
You are right. This will be changed in the next bug fix release.

> Is the jsxc.options.hideOffline property intended for define a default behaviour while initializing the chat client?

Yes, but I think we have to document it in jsxc.options.js. Thank you for pointing this out.

**Comment by sualko** [comment]
HideOffline is already documented in [jsxc.lib.options.js#L151](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js#L151).
