### ISSUE TITLE
Cant login to Openfire Server

### ISSUE THREAD

**Issue by DrGanmon** [jsxc/jsxc#296]
Hello,

1st, my setup:
Ubuntu 14.04.4 server
Owncloud 9.0.0
openfire 4.0.1 on a different server
Reverse Proxy via Nginx (https)
I follow your installation-steps and after entering BOSH url and Save settings I get: BOSH Server reachable

=> everything seems fine

but the console says: 
"jsxc.js?v=7d495d3…:8266 Unable to create user prefix"

and i cant login to the XMPP (testet it with different accounts) :( 

What am I doing wrong?

**Comment by sualko** [comment]
> "jsxc.js?v=7d495d3…:8266 Unable to create user prefix"

This is just a debug message. No reason to worry :-).

Do you use the same password for your XMPP and OC accounts? Is your jid in the format of OC_USERNAME@YOUR_DOMAIN?

**Comment by DrGanmon** [comment]
> Do you use the same password for your XMPP and OC accounts? Is your jid in the format of OC_USERNAME@YOUR_DOMAIN?

Nope, User, Password and Domains are different and yes i used the jid in the right Format.

**Comment by sualko** [comment]
> Nope, User, Password and Domains are different

That is the reason why it is not working. You need the same password and the above jid schema to use your own XMPP server. Otherwise you could also try our experimental internal server.

**Comment by DrGanmon** [comment]
wy i can insert login credentials if im forced to use the same as the oncloud does?
