### ISSUE TITLE
messages encrypt 

### ISSUE THREAD

**Issue by thfree** [jsxc/jsxc#297]
It switches automatically encrypt messages with the first shipment, between clients owncloud. This is not good.

Testing:
owncloud 8.2 & owncloud 9.0
jsxc 3.0.0

**Comment by sualko** [comment]
>  This is not good.

I see it differently, but you can disable this behavior by adding <code>otr: {SEND_WHITESPACE_TAG: false},</code> to the init options in [ojsxc.js#L148](https://github.com/owncloud/jsxc.chat/blob/master/js/ojsxc.js#L148).

**Comment by thfree** [comment]
I am using your own Jabber server with ssl and when I have more than one device, it turns out the mess in the history of communications.

But thanks for the tip as a force to disable it.
It would be nice if you had a separate option ruled this element.
