### ISSUE TITLE
Video chat

### ISSUE THREAD

**Issue by thfree** [jsxc/jsxc#299]
Video chat
and it did not work, even on the local network.
Errors were only in the browser:

1
```
jsxc.dep.js?v=1c180ba…:20277
Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed URL
```
2 
```
Refused to load media from 'blob:https%3A//cloud.thfree.ru/af7ba549-0034-4d7a-8a7b-b1814459118a' because it violates the following Content Security Policy directive: "media-src *".
```

**Comment by sualko** [comment]
How does your TURN url looks like? Which oc version do you use?

**Comment by thfree** [comment]
owncloud 8.2 & 9.0
jsxc 3.0.0

http://TURN/
login pass

**Comment by sualko** [comment]
That is no valid turn address. Use only your hostname as turn url. Maybe this should be pointed out in the admin options. Your second error results from the very restrictive oc csp, should not occur in oc 9.0, but I will check that.

**Comment by thfree** [comment]
Thank you, but after you deploy your TURN server, the problem has exhausted itself. But the question remains, in the local network data will also be going through TURN? where same-p2p ...

**Comment by sualko** [comment]
> in the local network data will also be going through TURN?

No. It is only used if your peers are behind a symmetric NAT. To detect such cases a STUN server is always required for video calls. You find more information in this [article](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT).

**Comment by thfree** [comment]
Thank you.

**Comment by thfree** [comment]
Own STUN server can be specified only by editing the code?

**Comment by sualko** [comment]
A TURN server is also working as a STUN server, so no need to edit the code. I meant a TURN server is optional and a STUN server mandatory.
