### ISSUE TITLE
many notifications

### ISSUE THREAD

**Issue by thfree** [jsxc/jsxc#301]
During the tests I have accumulated a lot of notifications, but there is no possibility to close them all at once.
OC 8.2
JSXC 3.0.0
##

**Comment by sualko** [comment]
![screenshot from 2017-01-20 15-11-53](https://cloud.githubusercontent.com/assets/2974196/22152357/d53575cc-df22-11e6-8775-00cf0b8d3334.png)

**Comment by thfree** [comment]
Wow, cool. Thank you!
