### ISSUE TITLE
File transfers not working

### ISSUE THREAD

**Issue by xexpanderx** [jsxc/jsxc#302]
Hi,

File-transfers is working between other clients such as Pidgin (even if a user is outside LAN) but not Owncloud. I can see that someone tries to transfer a file (filename is showing) but I cannot click on it or otherwise download it.

File-transfer is working if users are on the same LAN in Owncloud. I checked the js-console and no errors are throwned. 

I use HTTPS for my Owncloud.

My setup:
Owncloud: 8.2.3
Javascript XMPP Chat: 3.0.0
Prosody: 0.9.1
Firefox 44.0.2
TURN-server: http://numb.viagenie.ca
BOSH UR: https://example.com:5281/http-bind

**Comment by xexpanderx** [comment]
I now created my own TURN-server with TLS-support.

It works but still same problem with file-transfers.

I've opened several ports in my NAT:
443
3478
3479
5349
5348

I have 5348 and 5349 ports enabled in TURN. 5349 is the TLS-port.

Again, between Pidgin clients it works. But not with Owncloud. I've tested Chrome, Chromium and Firefox.

**Comment by mehdi-belkhayat** [comment]
Hi,
For your information, i did the following tests : 
File Transfers are not working when connected from my three devices (DSL1 DSL2 and LTE)
But they are working, when the three devices are in the same network
May be this would help ...

**Comment by xexpanderx** [comment]
Hi,

That is what I wrote in the first message, I can transfer files if users are in same network (LAN). But external users cannot transfer files.

Maybe something is blocked within my router/NAT, but I cannot tell how. I have no idea how to debug this one.

**Comment by sualko** [comment]
To transfer files your need to specify at least a STUN server, better an TURN server. Please ensure that you entered only the TURN hostname (e.g. turn.example.com) and no port or anything else.

Please check the following information sources for errors:

- js console
- chrome://webrtc-internals (chrome) or about:webrtc (FF)
- traffic via wireshark

**Comment by mehdi-belkhayat** [comment]
Hi xexpanderx,
indeed, i just installed my set of test thins morning and i wanted to precise it before running deeper tests : the first test was with no IDS or firewall and ran ok

-->Here is test 2 :
the second test was with little snitch (firewall IDS) activated : 
he asked me to validate the stun (see the image) 
![stun2](https://cloud.githubusercontent.com/assets/18006248/13952712/bcd27cce-f02f-11e5-810a-fc4ebdd87e72.png)

as i was obliged to validate to go further, the file transfer was announced but did not work : there was no link to download.

once the firewall learned the stun rule, and i had no action to validate again, the other file transfers worked, even with a 154 Mo file sent.

Klaus, is it possible that a delay could cause the problem of the file transfer not in the same network ?
a latency configuration to add may be ?

**Comment by mehdi-belkhayat** [comment]
Here is test 3 :
With etherape on my ubuntu trusty, i try to visualise data flows from file transfer and it seems that the stun protocol resolves the ip adresse of the remote machine, but it tries to send the file directly to it, without going through the remote router, as shown in the picture 
![stun3](https://cloud.githubusercontent.com/assets/18006248/13961746/cf3230be-f055-11e5-8db0-fdbd54191159.png)
May be that explains the start of the transfer and the filename, but the absence of data.

**Comment by sualko** [comment]
> Klaus, is it possible that a delay could cause the problem of the file transfer not in the same network ?
a latency configuration to add may be ?

I am not aware of any option in the webrtc specification. Sorry.

> May be that explains the start of the transfer and the filename, but the absence of data.

The negotiation of connection parameters and the transfer of the filename are done via jingle, anything else is up to the browser.

I am sorry that I can not help you guys, but webrtc is difficult to handle. I will try to update [jingle.js](https://github.com/otalk/jingle.js) in the next release and maybe your bugs have already been fixed.

**Comment by mehdi-belkhayat** [comment]
Thanks for the answer.

Now i installed my own turn server for the tests, but i don't know where to change it in the files.

Can you help me on this one ?

**Comment by sualko** [comment]
@mehdi-belkhayat You can change your turn settings in the oc admin section.

**Comment by mehdi-belkhayat** [comment]
Thanks Klaus,

I have seen that. But i do not use JSXC with owncloud.
i use the core version to embed in my website.
i 've found stun parameters in /build/jsxc.min.js
but i dont have the attended results though.

**Comment by sualko** [comment]
No need to change the source. You can pass your turn configuration as parameter of ``jsxc.init`` to jsxc. See [jsxc.lib.options.js#L246](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js#L246) for a list of possible configuration options.

**Comment by mehdi-belkhayat** [comment]
Many Thanks Klaus.

**Comment by sualko** [comment]
Can we close this issue, or do you still have problems with file transfer?

**Comment by mehdi-belkhayat** [comment]
Hi Klaus, i did not test yet.
But yes you can.
Gooday
