### ISSUE TITLE
Without the camera does not take a video

### ISSUE THREAD

**Issue by thfree** [jsxc/jsxc#303]
Tested calls.
1 user (camera, microphone)
2 user (microphone)

Call from (1) to (2) video work.
Call from (2) to (1) only the voice.

owncloud 8.2 & 9.0
jsxc 3.0.0
FF 45

**Comment by sualko** [comment]
Can you test with chrome?

**Comment by thfree** [comment]
chrome <> chrome
Testing:
android 5
windows 10, 7,
ubuntu 15.10.

I have in the chrome is no video capture, a gray screen. The FF is normal.
![image](https://cloud.githubusercontent.com/assets/13134495/13977826/541352fe-f0dd-11e5-9ca9-f6ce9d2502a8.png)

Subjectively, the chrome has no description at the beginning of the problem.

**Comment by sualko** [comment]
Sorry for the delay, but I can not reproduce your issue. If I call from a pc (2) without webcam to a pc (1) with webcam and microphone it looks like this on 1:

![screen shot 2016-04-06 at 13 17 16](https://cloud.githubusercontent.com/assets/2974196/14314885/45e828bc-fbfa-11e5-9065-1e2326bd113f.png)

Maybe #294 is related.
