### ISSUE TITLE
Download and use own avatar from vcard

### ISSUE THREAD

**Issue by xeux** [jsxc/jsxc#304]
I have some users with user avatars using XEP-0054 http://xmpp.org/extensions/xep-0054.html

Scenario 1: If I log in my roster comes without avatars, when I login with another user in my roster with JSXC it comes online but avatar still in default.

Scenario 2: If I do the same one log in in JSXC and one using Pidgin, it loads the last connected user avatar.

Scenario 3: If I login one account using AstraChat (Android App) it brings all my roster avatars.

Maybe I have to set a parameter to JSXC to always load user avatars?

Also in the scenario 2, the user avatar loaded just works in that browser, I used Firefox, if I login in Chrome the user avatar is default again.
##

**Comment by sualko** [comment]
User avatars are only loaded if a presence information with [caps](http://xmpp.org/extensions/xep-0115.html) is received.

> Scenario 1: If I log in my roster comes without avatars, when I login with another user in my roster with JSXC it comes online but avatar still in default.

JSXC is not able to provide an avatar, so this is the expected behaviour.

> Scenario 2: If I do the same one log in in JSXC and one using Pidgin, it loads the last connected user avatar.

This should be right.

> Maybe I have to set a parameter to JSXC to always load user avatars?

This is not implemented, because with big contact lists this would result in bad performance.

**Comment by xeux** [comment]
@sualko I saw JSXC working with avatars when used with ownCloud, to make that possible, what could I do? use caps XEP-0115?

**Comment by sualko** [comment]
JSXC is only partial working with avatars. If the other client provides an avatar, jsxc will display it. But we are currently unable to provide an avatar by ourself. The oc version uses oc avatars as an fallback, if no xmpp avatar is available. I hope I could answer all your questions.

**Comment by mhchu** [comment]
> JSXC is only partial working with avatars. If the other client provides an avatar, jsxc will display it. But we are currently unable to provide an avatar by ourself.
Having just read this statement, I fear that my attempts at getting avatars to work on JSXC this weekend was in vain. Does this statement mean that if I run a website and deploy only JSXC as the website's client, there is no way to show avatars other than the colored circle with the first letter of the user's name? Or have I misunderstood the statement? Thanks!

**Comment by MarcelWaldvogel** [comment]
Right now, you need another client to set an avatar. But you are welcome to submit a pull request which adds avatar upload (from file, from URL (e.g. gravatar) or from the ownCloud avatar)

**Comment by xeux** [comment]
@sualko @mhchu @MarcelWaldvogel In my case is not about upload the avatar using JSXC the user already have an avatar, if both users are using JSXC online it does not display the avatar. If I understand Klaus, using other client bring the avatars. Also brings avatars if using caps XEP-0115?

Please Klaus, confirm me if using XEP-0115 and login users only with JSXC will display the avatars?

**Comment by sualko** [comment]
A client has to announce that there is a avatar available, see [XEP-0153](http://www.xmpp.org/extensions/xep-0153.html#bizrules-presence) for details. To fix your issue, we have to download our own avatar and calculate the sha-1 value of its binary. This is the tricky part, but it could be probably done, see http://stackoverflow.com/questions/17819820/how-to-get-correct-sha1-hash-of-blob-using-cryptojs. If you are interested in implementing, please open a new pull request to discuss the details.

**Comment by backstageel** [comment]
Is there an option to use custom avatars as a fallback?

My app already provides avatars, and i want to use those avatars as JSXC avatars.

**Comment by sualko** [comment]
@backstageel You can use the option [defaultAvatar](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js#L177), for an example look at the [config](https://github.com/owncloud/jsxc.chat/blob/master/js/ojsxc.js#L165) of the owncloud app.

**Comment by sualko** [comment]
Something like the following could work:

```
var vCard = $(stanza).find("vCard > PHOTO");
var img = vCard.find('BINVAL').text();
var content = Base64.decode(img.split("\n").join(""));
aid = CryptoJS.SHA1(content);
```

originally posted in #514 by @eLFuvo.
