### ISSUE TITLE
Owncloud JavaScript Xmpp Client Config

### ISSUE THREAD

**Issue by sammy498** [jsxc/jsxc#305]
Hi,

I have created an owncloud through virtualbox and have followed the installation for the plug in chat. I am now at the final stage of filling in the configuration within the admin section of owncloud:
BOSH url
XMPP domain
XMPP resource etc etc

I have my BOSH url as http://localhost:5280/http-bind/ which i believe to be correct (please correct me if this is wrong)
However, I am having great difficulty working out what the XMPP domain is seeing as I am running it off virtualbox. I have tried my ip address but this doesn't seem to work. 
I am fairly new to this do any help would be much appreciated 
Thank you very much!

**Comment by sualko** [comment]
> I have my BOSH url as http://localhost:5280/http-bind/ which i believe to be correct 

If you click save, it will give you response if the server is reachable or not.

> I am having great difficulty working out what the XMPP domain is seeing

It depends on your XMPP server configuration. Normally "localhost" should work out of the box.
