### ISSUE TITLE
Question Mark

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#307]
I've noticed that when ever I send only a lone question mark (?) symbol I get the reply back "42" which doesn't seem to come from the person i'm chatting with.  Not sure where that's coming from.

If it helps I'm using the openfire 4.0.1 chat server, jxsc 3, and Owncloud 9.

**Comment by DanScharon** [comment]
congrats, you just found an easter egg ;)

**Comment by Luticus** [comment]
I thought that might be the case.  ;)

Joe McEntire
getjoe@live.com

On Mar 30, 2016, at 3:07 AM, Daniel Scharon <notifications@github.com<mailto:notifications@github.com>> wrote:

congrats, you just found an easter egg ;)

**Comment by Luticus** [comment]
Unfortunately, while the answer to life, the universe, and everything is awesome?  I use the single ? character a lot :).  If anyone else want's to disable the easter egg like I did you can do so by commenting out the line numbers:  4939 to 4945 in the file  ../owncloud/apps/ojsxc/js/jsxc/jsxc.js

**Comment by MarcelWaldvogel** [comment]
@sualko @DanScharon How about the following logic:

* The easter egg sets a variable easterEggDisabled = false in options/localStorage on first use (and will check it in the future)
* If easterEggDisabled is set, display it as an on/off option in the settings dialog

So we can both have the egg and (b)eat it
