### ISSUE TITLE
"Error: this app cannot be enabled because it makes the server unstable"

### ISSUE THREAD

**Issue by docplastic** [jsxc/jsxc#309]
While trying to install "JavaScript XMPP Chat 3.0.0" (either by clicking the install button, or by downloading the .zip file and hand installing it), on OwnCloud version: 9.0.0.19, I always get the error:
  "Error: this app cannot be enabled because it makes the server unstable".
This OwnCloud is running on Ubuntu 14.04.4 with PostgreSQL 9.5.2 and in the same server I have a Prosody XMPP server 0.9.10 installed.

**Comment by sualko** [comment]
@LukasReschke Any idea, why this happen?

**Comment by docplastic** [comment]
I do not know if the following helps:

Although running "php occ -vvv app:enable ojsxc" shows no visible errors, it is always followed by the following error in the Nginx v.1.8.1 web server logs:

  [error] 29903#0: *4559 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 106349 bytes) in /var/www/owncloud/3rdparty/patchwork/jsqueeze/src/JSqueeze.php on line 586" while reading response header from upstream, client: 192.0.2.9, server: oc.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "oc.example.com"

So, it seems that enabling ojsxc calls JSqueeze.php and it triggers some kind of memory allocation bug.

**Comment by sualko** [comment]
Do you have asset pipelines activated? Maybe related #255.

cc @LEDfan

**Comment by LEDfan** [comment]
Like @sualko noted, the error you are reporting is because PHP want to use more memory than configured in `php.ini`. It looks like this happens when ownCloud is minifying the JS of JSXC.

You could try setting a higher `memory_limit` in php.ini.

I guess when you set a reasonable value, and still don't work this an issue for ownCloud core. As a workaround disable  'asset-pipeline.enabled' via   `'asset-pipeline.enabled'` => true in `config.php`

**Comment by sualko** [comment]
Should be probably <code>'asset-pipeline.enabled' => false</code>.

**Comment by docplastic** [comment]
@sualko Problem solved by removing the 'asset-pipeline.enabled' => true line (as you suggested).
@LEDfan Increasing php's memory_limit just to deal with Owncloud's internal idiosyncrasies/bugs (#255 and #17693) just does not feel right to me. 
Thank you all, I am closing this issue.
