### ISSUE TITLE
Master requests go on and on

### ISSUE THREAD

**Issue by wojciech-kochanowski** [jsxc/jsxc#310]
Hello
Today I looked into my js console and saw something like this: 
![master_request](https://cloud.githubusercontent.com/assets/17614251/14251033/446f66c8-fa81-11e5-83c0-632d75da88f7.jpg)
Those logs keep coming in and as they are all saved into jsxc.log (right?), my browser gets slower every second. Turns out it happens from time to time, but I haven't been able to find out, what causes this. Everything else in the chat works fine, messages are being sent, same for presence info.
Any ideas what might be the cause of this?

**Comment by sualko** [comment]
Please provide some more information, like browser version, jsxc version, host application (sogo, owncloud, ...) and so on.

> Any ideas what might be the cause of this?

Do you have multiple tabs open?

**Comment by wojciech-kochanowski** [comment]
I'm using ejabberd2, jsxc is v3.0.0 and I'm usuallu using Chrome 49.0.2623.110 although I've heard of the same issue with firefox. 

> Do you have multiple tabs open?

Yes, and I tend to close them and open new in random order. Could that be the case?

**Comment by sualko** [comment]
> Yes, and I tend to close them and open new in random order. Could that be the case?

Yes this could be the case. I will try to fix that in the next release.

**Comment by wojciech-kochanowski** [comment]
Ok thanks. Any quick fix would also be appreciated as I'm being pressured into making this work fast ;) . I've noticed that commenting out
`jsxc.debug('Master request.'); 
jsxc.storage.ink('alive');`
doesn't really solve the issue - the browser still gets killed, only a little slower ;)

**Comment by khanhmas** [comment]
Make sure u only login once !!!

**Comment by wojciech-kochanowski** [comment]
> Make sure u only login once !!!
I'll check on that, thanks. What is the best way to check if I'm logged in? I'm using 
`jsxc.xmpp.conn && jsxc.xmpp.conn.authenticated`
but sometimes, even though it returns true, I can't see the roster. That's when I call login again. Is there a better way I can restore the roster in those cases?

**Comment by khanhmas** [comment]
In jsxc, most of the data is saved in localStorage. This is my workaround :
if (!jsxc.storage.getItem('rid') || !jsxc.storage.getItem('sid') || !jsxc.storage.getItem('jid')) {
        jsxc.xmpp.login(<username>, <password>);
      }

**Comment by wojciech-kochanowski** [comment]
After some fiddling I might have found the reason for this behavior. Turns out, problem lied in the "onlogin" attribute for the init function. Honestly, I couldn't find any onformation on what it actually does; in the source code, there's a comment that it is deprecated, but for some reason it is still in the examples provided with the package. 
Anyway, if it is set to true, it calls the login function every time you open a new tab, no matter how you try to avoid it. Setting it to false and handling the authentication by myself seems to be the answer for this issue.

**Comment by sualko** [comment]
> but for some reason it is still in the examples provided with the package. 

Ups, maybe you forget to update your example. I will fix that in the next days.

Please post a snippet of your jsxc and login code. My read is that you login on every page load.

**Comment by sualko** [comment]
Please provide the code of your login calls and jsxc.init stuff. I guess you still login multiple times.

**Comment by sualko** [comment]
@khanhmas You should use ``jsxc.start`` instead of ``jsxc.xmpp.login``.

I added a master check in ``jsxc.start``, so your issue should no longer occur.

**Comment by sualko** [comment]
Please test 9095b9f25787080fa5273ebe3f87a5d50f2a04e7, there you find a build version in the build folder.

**Comment by khanhmas** [comment]
Ok, thanks you.

**Comment by sualko** [comment]
Any update?

**Comment by khanhmas** [comment]
I updated the latest fix but sometimes, the problem still persists.

I tried to log in and log out with 1 or 2 users with different browsers, muti-tabs, and at certains moments, it produced the erreurs.
![error1](https://cloud.githubusercontent.com/assets/8402110/15177659/75f5467e-1771-11e6-9840-e2672c178cf1.jpg)

**Comment by sualko** [comment]
> You should use jsxc.start instead of jsxc.xmpp.login.

Do you?

**Comment by khanhmas** [comment]
I also tested with jsxc.start but it found that jid is null (Cannot read property 'jid' of null in line 2736) in the "slave" tab when i invoked the "updateAvatar" method.

**Comment by sualko** [comment]
Can you try to change line 2736 to

```
var ownJid = (jsxc.xmpp.conn) ? jsxc.xmpp.conn.jid : jsxc.storage.getItem('jid');

// workaround for https://github.com/strophe/strophejs/issues/172
if (Strophe.getBareJidFromJid(jid) === Strophe.getBareJidFromJid(ownJid)) {
```

**Comment by sualko** [comment]
I found an issue if connection is lost due to a xmpp error and I am working on a solution, but it feels fragile. Maybe I have to rewrite the tab communication part, but I try to avoid that...

**Comment by orszaczky** [comment]
I noticed that when I did a fresh login, 'Master request.' kept spinning like crazy (every ms or so). If I reloaded the page, without logging out, this stopped, and it only logged 'check master' (about every 2s).

https://github.com/jsxc/jsxc/commit/6fe2d802fdabca52293688e60ca028842ca2c5c1 fixed the problem for me.
