### ISSUE TITLE
Call terminated: jingle_reason_defined

### ISSUE THREAD

**Issue by victoredwardocallaghan** [jsxc/jsxc#316]
Hi,

I am testing this library locally with a couple of laptops using FF as the browser. For whatever reason when I try to get one machine to call another they both seem to start the call, both ask to accept and then the recipient's web cam LED flashes for a second then I get "Call terminated: jingle_reason_defined" in the chat window. On some random occasions a call will establish but the video stream is unidirectional. My gut feeling is there a race condition on the end-point source descriptor but I really have no idea in truth..

Look forward to hear from you.
Kind Regards,
Edward.

**Comment by sualko** [comment]
Do you have a turn server configured? Any helpful information in you js console?

**Comment by sualko** [comment]
I close this issue, because it seems to be a duplicate of the more active #329.

**Comment by sualko** [comment]
Sorry, it is a different issue.

**Comment by sualko** [comment]
To analyse this issue, I need the answers to the following questions:

> Do you have a turn server configured? Any helpful information in you js console?

**Comment by sualko** [comment]
I close this issue, because I have not enough information to debug your bug.
