### ISSUE TITLE
Bug when destroying a room

### ISSUE THREAD

**Issue by khanhmas** [jsxc/jsxc#317]
I am using ejabberd 16.03 XMPP server and  jsxc 3.0

I was using Chrome and Opera, the Chrome, member, joins the room created by Opera, owner (or vice versa). When the owner destroys the room, the room is still opened in the "membered" browser.

P/S : In addition, the ownNicknames in the localStorage of "membered" browser wasn't deleted except the "ownered" browser.

**Comment by sualko** [comment]
> the room is still opened in the "membered" browser.

That is the right behavior, but you should get an system message. What happens if you send a message?

**Comment by khanhmas** [comment]
If I send a message, it says such as "This room is no longer exist".

By the way, I modified the jsxc source code for removing the window in the "membered" browser.

**Comment by sualko** [comment]
> If I send a message, it says such as "This room is no longer exist".

This is no bug, it is a feature. The user has still the possibility to read all old messages or even unread messages.
