### ISSUE TITLE
"Online" status bug in a room

### ISSUE THREAD

**Issue by khanhmas** [jsxc/jsxc#319]
I am using ejabberd 16.03 XMPP server and  jsxc 3.0

There are some bugs about the "online" status when the users (member, owner) are in a room. For example, the members and the owner's status is offline whereas they are talking together.

P/S : I tested, maybe, the jsxc.gui.window.open(<room jid>) would help refresh the status.
##

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32742137-online-status-bug-in-a-room?utm_campaign=plugin&utm_content=tracker%2F728128&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F728128&utm_medium=issues&utm_source=github).

**Comment by sualko** [comment]
I could reproduce your issue and it is implemented incorrectly. It will be fixed with #447, but it will need some more testing. Stay tuned.

**Comment by sualko** [comment]
#447 was merged.
