### ISSUE TITLE
[ojsxc] Enabled ojsxc force oc language to english

### ISSUE THREAD

**Issue by v1r0x** [jsxc/jsxc#320]
I've set language in oc to german. After activating the chat app the language in oc is english. The option in the personal panel is still set to german, but the strings are in english.
I'm using the latest oc (9.0.1) and ojsxc (3.0.0). Also had the problem in oc 9.0.0, but didn't know where it came from.

**Comment by sualko** [comment]
Sorry, I can not reproduce your issue. Maybe you can try to set your language to english and afterwards back to german.

**Comment by v1r0x** [comment]
already tried it, but it is still english. I'll have a look at the log and let you know if there is something related to this.

**Comment by v1r0x** [comment]
Couldn't find anything in the owncloud log, but it looks like it is not related to ojsx(c). Also happens after enabling the [music app](https://github.com/owncloud/music).
Just for the record: Happens only in firefox (at least not in chromium).

**Comment by sualko** [comment]
You can maybe report this issue to https://github.com/owncloud/core/issues

**Comment by v1r0x** [comment]
Just for the record: Had to add english language in the firefox settings as language (default is german). Very weird, but now everything is german again :)
