### ISSUE TITLE
Duplicate roster items

### ISSUE THREAD

**Issue by vladb** [jsxc/jsxc#321]
Using JSXC 3.0 with ejabberd 2.1.11 with mod_roster_odbc, I'm getting duplicated items in the buddy list (up to 4 dupes). Setup is standard as per installation instructions:

`
$(function() {
   jsxc.init({
      root: '/footyboot/jsxc/jsxc/',
      xmpp: {
         url: '/http-bind/',
      }
   });
   
   jsxc.xmpp.login('user@domain.com', 'password');
});
`

**Comment by khanhmas** [comment]
Make sure you only logged in once.

**Comment by vladb** [comment]
Doesn't jsxc.xmpp.login catch that case? In any way, how do you recommend checking if the user is already logged in? Cheers.

**Comment by khanhmas** [comment]
Cf to this issue : https://github.com/jsxc/jsxc/issues/310. This is my workaround : 
if (!jsxc.storage.getItem('jid') || !jsxc.storage.getItem('sid') || !jsxc.storage.getItem('rid')) {
jsxc.xmpp.login(username, password);
}
Cheers.

**Comment by sualko** [comment]
<code>jsxc.xmpp.login</code> should be called only once and not on every tab and after every page request. <code>jsxc.init</code> attaches a connection by itself.
