### ISSUE TITLE
Issue while intergrating with Primefaces

### ISSUE THREAD

**Issue by javauser1234** [jsxc/jsxc#326]
Hello,
Yesterday I was trying to integrate JSXC with my application. I'm using Primefaces and when I'm trying to include JSXC, even after succesfull xmpp login, the chat/roster window is not appearing.

After some debugging, found out that If I include jquery and jquery-ui js and css files, everything works.
But the issue is, Primefaces already includes these files, and some of the functionalities are not working if I include jquery, jquery-ui separately.

Any workaround is greatly appreciated.

**Comment by sualko** [comment]
Mh, which jquery version do you use? Can you provide an example page, or some source code? You can send this information also directly via email to klaus@jsxc.org, if you have any privacy concerns.

**Comment by javauser1234** [comment]
Sure! Here you go,
I'm having a jsf page "Profile.jsf". In the head tag I have included 
```
<script src="/resources/js/jquery.min.js"></script>
<script src="/resources/js/jquery.ui.min.js"></script>
<script src="/resources/js/jquery.slimscroll.js"></script>
<script src="/resources/js/jquery.fullscreen.js"></script>
<script src="/resources/js/jsxc.dep.js"></script>
<script src="/resources/js/jsxc.js"></script>

<link href="/resources/css/jquery-ui.min.css" media="all" rel="stylesheet" type="text/css" />
<link href="/resources/css/jsxc.css" media="all" rel="stylesheet" type="text/css" />
```
And 
```
<script>
$(function() {
   jsxc.init({
      root: '/Main',
      xmpp: {
         url: 'http://localhost:7070/http-bind/'
      }
   });
   jsxc.xmpp.login('<my jid>','<my password>');
});
</script>
```
Server: Glassfish v3
If I don't include the jquery.min.js and jquery-ui.min.css, It is not working. If included, some of the Primefaces components are not working (For eg. DateTimePicker etc).

Please let me know if you need any further details.

**Comment by sualko** [comment]
Please check your primefaces jquery version. Check also for errors in your javascript console and in which order all javascript files are loaded.

**Comment by javauser1234** [comment]
Just updated my comments. 
Primefaces is internally using 1.8.10 version of jquery I believe.

**Comment by javauser1234** [comment]
Unfortunately, DateTimePicker is one of the components that is not working is I include my own jquery. There may be others which I yet to find out. 
Does it makes sense to check each and every css class between Primefaces and external jquery build? Because I'm afaraid it might break some functionalities if I failed tregression test the whole application.

**Comment by javauser1234** [comment]
Appreciate if there is any workaround? I really need to integrate it in our project and test it out. 

Thanks!

**Comment by sualko** [comment]
Without any error message, I have no glue why this is not working. Maybe you can send me a test url to klaus@jsxc.org.

**Comment by javauser1234** [comment]
I don't have my app set up in a public domain so was not able to provide you with a test URL. But I had set the debug to true, and below is what I got from dev console. Not sure if it is of any help.

```
currentLng set to: en
check master
New connection
CONNECTING: null
> <body rid=​"1637652063" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"concorde-pc" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
< <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" from=​"concorde-pc" authid=​"50e02170" sid=​"50e02170" secure=​"true" requests=​"2" inactivity=​"30" polling=​"5" wait=​"60" hold=​"1" ack=​"1637652063" maxpause=​"300" ver=​"1.6">​<stream:features>​…​</stream:features>​</body>​
> <body rid=​"1637652064" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"50e02170">​…​</body>​
< <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1637652064">​<challenge xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​…​</challenge>​</body>​
> <body rid=​"1637652065" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"50e02170">​…​</body>​
< <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1637652065">​<success xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​cnNwYXV0aD0xMDk4YzRmODkyNDZhZTYxYjM0NGVjNGI3ZjAxMWQ3MA==​</success>​</body>​
> <body rid=​"1637652066" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"50e02170" to=​"concorde-pc" xml:lang=​"en" xmpp:restart=​"true" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
< <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​<stream:features>​…​</stream:features>​</body>​
> <body rid=​"1637652067" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"50e02170">​…​</body>​
< <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1637652067">​<iq xmlns=​"jabber:​client" type=​"result" id=​"_bind_auth_2" to=​"concorde-pc/​50e02170">​…​</iq>​</body>​
> <body rid=​"1637652068" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"50e02170">​…​</body>​
< <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1637652068">​<iq xmlns=​"jabber:​client" type=​"result" id=​"_session_auth_2" to=​"concorde@concorde-pc/​50e02170">​</iq>​</body>​
CONNECTED: null
close dialog
I am master.
> <body rid=​"1637652069" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"50e02170">​</body>​
I am master.
```

**Comment by sualko** [comment]
```
$(function() {
   jsxc.init({
      root: '/Main',
      xmpp: {
         url: 'http://localhost:7070/http-bind/'
      }
   });
   jsxc.xmpp.login('<my jid>','<my password>');
});
```

<code>jsxc.init</code> tries to attach a previous connection, and <code>jsxc.xmpp.login</code> does the same, so this doesn't work.  Add <code>loginForm: {ifFound: false}</code> to your init options and try again.

**Comment by javauser1234** [comment]
Thanks for your reply.
With my current settings, it does work if I include the `jquery.min` and `jquery-ui` js files included in the zip file in my jsf page.
But since Primefaces already bundles these jquery files, adding another version breaks the primefaces components.

**Comment by sualko** [comment]
Sorry, but I can't help you. I am not a primefaces expert, but maybe jquery noconflict is activated. Try:

```
<script>
jQuery(function() {
   jsxc.init({
      root: '/Main',
      xmpp: {
         url: 'http://localhost:7070/http-bind/'
      }
   });
   jsxc.xmpp.login('<my jid>','<my password>');
});
</script>
```

There are multiple questions about jquery and primefaces in the internet, maybe some answer helps you:

http://stackoverflow.com/questions/25508564/how-to-solve-a-conflict-with-primefaces-jquery
http://stackoverflow.com/questions/5457292/jquery-conflicts-with-primefaces
http://stackoverflow.com/questions/22321345/jquery-and-primefaces-conflict

**Comment by javauser1234** [comment]
Not an issue.I will try with `jQuery` instead of `$` and let you know the result.
Needless to mention, jsxc is awesome!

**Comment by sualko** [comment]
Can we close this?

**Comment by javauser1234** [comment]
Yes you may. I tried with `jQuery` but aparently still having the issue.
