### ISSUE TITLE
owncloud how disable auto encript chat?

### ISSUE THREAD

**Issue by gwynnbleiidd** [jsxc/jsxc#327]
During talk, in a chat the closed lock, with it it is impossible to send messages. I so understand that a problem with SSL of prosedy.

 Whether there is opportunity by default to switch off it? I viewed settings, but I didn't find.

**Comment by sualko** [comment]
Did you ask, how you can disable otr? In this case set <code>jsxc.options.otr.enable = false</code>.

**Comment by gwynnbleiidd** [comment]
Where there is this setup, in files didn't find.

**Comment by sualko** [comment]
No need to modify the source. Just add <code>otr: {enable: false}</code> to your init options.
