### ISSUE TITLE
Multi-tab problems

### ISSUE THREAD

**Issue by khanhmas** [jsxc/jsxc#328]
There are some problems when it comes to multi-tab (unable to load avatars into a room, unable to create chat room... as a slave),

How can i synchronize the master's chat rooms in a slave tab ?
##

**Comment by sualko** [comment]
> How can i synchronize the master's chat rooms in a slave tab ?

Currently this is not possible, but we will work on that.

**Comment by sualko** [comment]
**TODO:**
- [ ] sync muc rooms
- [ ] join muc room
- [x] logout

**Out of scope:**
- video calls

Is anything missing?

**Comment by rasos** [comment]
XEP 0313 sync 
XEP xxxx [omemo](https://conversations.im/xeps/multi-end.html)

**Comment by devendrawebdeveloper** [comment]
Do you have any update on it?
I am also facing issue with multitabs.

**Comment by devendrawebdeveloper** [comment]
Hi,

Can you please provide any update here?
I am using your package thats good for me but users facing issue with multi tab problem and complaint me.

Thank you

**Comment by sualko** [comment]
Currently I have no time for enhancements. If you have issues similar to #310, try 9095b9f25787080fa5273ebe3f87a5d50f2a04e7.

**Comment by devendrawebdeveloper** [comment]
Okay but just i am facing multi tab issue if you help me or instruction for solution .it will use full for us.

**Comment by devendrawebdeveloper** [comment]
Can you please provide some idea about it?

**Comment by MarcelWaldvogel** [comment]
@sualko is currently busy finishing his thesis (deadline). We are sorry that this might delay any activity for a few weeks, but please accept our sincere apologies.

**Comment by devendrawebdeveloper** [comment]
Any update or take more time? I have no idea about session .If you help me then i will manage.

**Comment by devendrawebdeveloper** [comment]
Hello sualko,

It is little urgent for me.if you have some time thats okay for me.If you are busy then NP.
Please help us for solve this issue.

**Comment by MarcelWaldvogel** [comment]
He's busy finishing his master's thesis. Sorry!
(And this is the part of the code and spec that his knowledge is needed)

**Comment by MarcelWaldvogel** [comment]
I am very sorry for the delay and I can understand your frustration. As I mentioned, the person knowing most about the tab code, has been very busy and traveling during the past month.

I cannot vouch for it, but I hope he will be able to spend some time next week on JSXC, hopefully also on the tab code.

**Comment by sualko** [comment]
@devendrawebdeveloper Your behavior is very impolite. This is an open source community-driven client without any paid developers. If you like to have a feature you either have to wait, raise a bounty (on bountysource), pay a developer or implement it by yourself.

I am doing as fast as I can, but sometimes I have different priorities (on features or even on other things than jsxc in my spare time).

**Comment by sualko** [comment]
With the commit above, muc windows should look and behave the same in all tabs. Sadly I was not able to get the "join chat" to work in all tabs, because it requires a more generic solution which is to much for the next bug fix release. It will probably go into one of the next feature releases.

**Comment by Majaspic** [comment]
Is this problem fixed or not ?

**Comment by devendrawebdeveloper** [comment]
It is not fixed.

**Comment by diegobill** [comment]
:+1:

**Comment by krunalinnovify** [comment]
@devendrawebdeveloper have you fixed and any solution for Multi Tab, if you have ?

**Comment by sualko** [comment]
This issue is solved in the upcoming 4.0.
