### ISSUE TITLE
Videocall problem

### ISSUE THREAD

**Issue by nasanchez** [jsxc/jsxc#329]
I have a problem with videocall. When I do a call for the first time, It works perfectly but when I hangup the call and try to do another call and my contact accepts the call, it falls down and show this error on my chat: Call terminated: jingle_reason_undefined.

**Comment by sualko** [comment]
Maybe a duplicate of #294? Please test the fix or try to reload your page.

**Comment by nasanchez** [comment]
I'm sorry but I can't find the fix...Where is it?

**Comment by sualko** [comment]
Easiest way would be to reload your page, before you call an other person. Otherwise you have to add <code>$(document).off('cleanup.dialog.jsxc');</code> in the <code>hangUp</code> method, but I had no time to add and test it yet.

**Comment by nasanchez** [comment]
I tried to add `$(document).off('cleanup.dialog.jsxc'); ` but my problem persists

**Comment by sualko** [comment]
Does a page reload fix your issue?

**Comment by nasanchez** [comment]
If I reload the page manually all it's ok, but I don't like to do this because the effect to the user is ugly and if the user has a slow connection it could be a little problem because the page could reload slowly.

Reloading the page is the only way to resolve this?

**Comment by sualko** [comment]
No, the fix is in #294. I guess you use the minified version, or inserted the snippet to the wrong file. Please wait for the next bug fix release.
