### ISSUE TITLE
Login via PHP session

### ISSUE THREAD

**Issue by Cronetos** [jsxc/jsxc#330]
Hi,

my problem is that I  can not use the dual login mentioned on the homepage because the xmpp credentials are not the same as on my website. Credentials for the xmpp server could be accessed from the session.
In https://github.com/jsxc/jsxc/wiki/Install-jsxc "getturncredentials.json" file is mentioned in the ajax folder. I would assume that this returns the credentials to the xmpp server. However on the rest of the page this file is not mentioned anymore and my question is, how can I login with the credentials provided by getturncredentials.json or any similar file? Do I have to pass them to the jsxc.init function?
If I understood the BOSH service correctly it is used to not log in on every page refresh and to use the same session again. So one solution would be to call it only once after a login to my website? Is there a more complete example to incorporate jsxc into another website?

Sorry if these are very basic questions. I hope you know what I mean. Thank you in advance.

**Comment by sualko** [comment]
Please checkout our example provided at https://github.com/jsxc/jsxc/tree/master/example

Especially <code>loadSettings</code> and prebind login.

> However on the rest of the page this file is not mentioned anymore

That is right. I review the installation guide. Thanks for mentioning it.

**Comment by Cronetos** [comment]
I actually had a look at it before but did not see the correct syntax in there. After reading it again I see now how to do it and I should be fine. So thank you very much.
