### ISSUE TITLE
Cannot get owncloud 9.0 to work with ejabbered

### ISSUE THREAD

**Issue by joe-liberty** [jsxc/jsxc#331]
Hi there, I did follow your directions but owcloud 9.0 fails to communicate with Bosh URL. I can get to bind URL right from a web browser so I do not know what the issue is. I do not even know where to start as I followed directions step for step. Running Ubuntu 14.04. Also note that I disable external authentication because of issues with not being able to register. Thanks!

OWNCLOUD CONFIG:

[ejabberd.txt](https://github.com/jsxc/jsxc/files/247961/ejabberd.txt)

```
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'ipaddress',
    1 => 'ipaddress',
  ),
  'datadirectory' => '/Backup_Storage/Owncloud_Public/oc-data',
  'overwrite.cli.url' => 'http://ipaddress/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'foo',
'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'server.com',
  'mail_smtphost' => 'mail.foo.com',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'updatechecker' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'sojourner_j',
'mail_smtppassword' => 'foo',
);
```

OWNCLOUD VIRTUAL HOST:

```
 <IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@localhost

		DocumentRoot /var/www/owncloud

		# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
		# error, crit, alert, emerg.
		# It is also possible to configure the loglevel for particular
		# modules, e.g.
		#LogLevel info ssl:warn

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		# For most configuration files from conf-available/, which are
		# enabled or disabled at a global level, it is possible to
		# include a line for only one particular virtual host. For example the
		# following line enables the CGI configuration for this host only
		# after it has been globally disabled with "a2disconf".
		#Include conf-available/serve-cgi-bin.conf

		#   SSL Engine Switch:
		#   Enable/Disable SSL for this virtual host.
		SSLEngine on

		#   A self-signed (snakeoil) certificate can be created by installing
		#   the ssl-cert package. See
		#   /usr/share/doc/apache2/README.Debian.gz for more info.
		#   If both key and certificate are stored in the same file, only the
		#   SSLCertificateFile directive is needed.
		SSLCertificateFile	/etc/ssl/certs/ssl-cert-snakeoil.pem
		SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

		#   Server Certificate Chain:
		#   Point SSLCertificateChainFile at a file containing the
		#   concatenation of PEM encoded CA certificates which form the
		#   certificate chain for the server certificate. Alternatively
		#   the referenced file can be the same as SSLCertificateFile
		#   when the CA certificates are directly appended to the server
		#   certificate for convinience.
		#SSLCertificateChainFile /etc/apache2/ssl.crt/server-ca.crt

		#   Certificate Authority (CA):
		#   Set the CA certificate verification path where to find CA
		#   certificates for client authentication or alternatively one
		#   huge file containing all of them (file must be PEM encoded)
		#   Note: Inside SSLCACertificatePath you need hash symlinks
		#		 to point to the certificate files. Use the provided
		#		 Makefile to update the hash symlinks after changes.
		#SSLCACertificatePath /etc/ssl/certs/
		#SSLCACertificateFile /etc/apache2/ssl.crt/ca-bundle.crt

		#   Certificate Revocation Lists (CRL):
		#   Set the CA revocation path where to find CA CRLs for client
		#   authentication or alternatively one huge file containing all
		#   of them (file must be PEM encoded)
		#   Note: Inside SSLCARevocationPath you need hash symlinks
		#		 to point to the certificate files. Use the provided
		#		 Makefile to update the hash symlinks after changes.
		#SSLCARevocationPath /etc/apache2/ssl.crl/
		#SSLCARevocationFile /etc/apache2/ssl.crl/ca-bundle.crl

		#   Client Authentication (Type):
		#   Client certificate verification type and depth.  Types are
		#   none, optional, require and optional_no_ca.  Depth is a
		#   number which specifies how deeply to verify the certificate
		#   issuer chain before deciding the certificate is not valid.
		#SSLVerifyClient require
		#SSLVerifyDepth  10

		#   SSL Engine Options:
		#   Set various options for the SSL engine.
		#   o FakeBasicAuth:
		#	 Translate the client X.509 into a Basic Authorisation.  This means that
		#	 the standard Auth/DBMAuth methods can be used for access control.  The
		#	 user name is the `one line' version of the client's X.509 certificate.
		#	 Note that no password is obtained from the user. Every entry in the user
		#	 file needs this password: `xxj31ZMTZzkVA'.
		#   o ExportCertData:
		#	 This exports two additional environment variables: SSL_CLIENT_CERT and
		#	 SSL_SERVER_CERT. These contain the PEM-encoded certificates of the
		#	 server (always existing) and the client (only existing when client
		#	 authentication is used). This can be used to import the certificates
		#	 into CGI scripts.
		#   o StdEnvVars:
		#	 This exports the standard SSL/TLS related `SSL_*' environment variables.
		#	 Per default this exportation is switched off for performance reasons,
		#	 because the extraction step is an expensive operation and is usually
		#	 useless for serving static content. So one usually enables the
		#	 exportation for CGI and SSI requests only.
		#   o OptRenegotiate:
		#	 This enables optimized SSL connection renegotiation handling when SSL
		#	 directives are used in per-directory context.
		#SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		#   SSL Protocol Adjustments:
		#   The safe and default but still SSL/TLS standard compliant shutdown
		#   approach is that mod_ssl sends the close notify alert but doesn't wait for
		#   the close notify alert from client. When you need a different shutdown
		#   approach you can use one of the following variables:
		#   o ssl-unclean-shutdown:
		#	 This forces an unclean shutdown when the connection is closed, i.e. no
		#	 SSL close notify alert is send or allowed to received.  This violates
		#	 the SSL/TLS standard but is needed for some brain-dead browsers. Use
		#	 this when you receive I/O errors because of the standard approach where
		#	 mod_ssl sends the close notify alert.
		#   o ssl-accurate-shutdown:
		#	 This forces an accurate shutdown when the connection is closed, i.e. a
		#	 SSL close notify alert is send and mod_ssl waits for the close notify
		#	 alert of the client. This is 100% SSL/TLS standard compliant, but in
		#	 practice often causes hanging connections with brain-dead browsers. Use
		#	 this only for browsers where you know that their SSL implementation
		#	 works correctly.
		#   Notice: Most problems of broken clients are also related to the HTTP
		#   keep-alive facility, so you usually additionally want to disable
		#   keep-alive for those clients, too. Use variable "nokeepalive" for this.
		#   Similarly, one has to force some clients to use HTTP/1.0 to workaround
		#   their broken HTTP/1.1 implementation. Use variables "downgrade-1.0" and
		#   "force-response-1.0" for this.
		BrowserMatch "MSIE [2-6]" \
				nokeepalive ssl-unclean-shutdown \
				downgrade-1.0 force-response-1.0
		# MSIE 7 and newer should be able to use keepalive
		BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

	</VirtualHost>
<IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</IfModule>

# ProxyPass /http-bind/ http://localhost:5280/http-bind/
# ProxyPassReverse /http-bind/ http://localhost:5280/http-bind/

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

FORWARDING VIRTUAL HOST: 

```
<VirtualHost *:80>
DocumentRoot "/var/www/owncloud"
<Directory "/var/www/owncloud">
allow from all
Options None
Require all granted
</Directory>
RedirectPermanent / https://ipaddress/owncloud
</VirtualHost>
```

**Comment by sualko** [comment]
You commented out the <code>ProxyPass</code>, so you probably running in any kind of csp issue. You should get more information if you save your jsxc options in ownclouds admin panel.

Just as a sidenote, you should never reveal your ownclouds passwordsalt and secret.

**Comment by joe-liberty** [comment]
Hey thx...... Oh shoot! I forgot to erase salt secret. It is just a test environment. I will try out your suggestion and get back with you. Thx for your help.

**Comment by joe-liberty** [comment]
Hey sualko.....I did save configuration but when I do this and try to login to Owncloud via web ui it just sets there and does nothing after I enter my password. I had to go in on occ command line and disable jsxc in order to be able to login back in via web ui. When I did setup openfire and I was able to communicate with via BOSH URL but it was not registering users properly so I thought ejabberd was more official and according to your instructions I installed it. It has been challenging to try and get this thing to work thus far. It must be something simple.

**Comment by sualko** [comment]
You need the same user/password combination in oc and ejabberd.

> You should get more information if you save your jsxc options in ownclouds admin panel.

Which information do you get?

**Comment by joe-liberty** [comment]
Hey Klaus....thanks for checking up on me. It could not contact BOSH server due to a cross-domain issue but I encountered some other issues. Ejabberd quit running for some reason and will not start back up. It says it is in use by another instance and I am not sure how to eliminate this problem: 


****_**_{error_logger,{{2016,5,10},{18,49,59}},"Protocol: ~tp: the name ejabberd@foo seems to be in use by another Erlang node",["inet_tcp"]}**
_
{error_logger,{{2016,5,10},{18,49,59}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.21.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.104>,<0.18.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,756}],[]]}
{error_logger,{{2016,5,10},{18,49,59}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[[ejabberd,shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2016,5,10},{18,49,59}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2016,5,10},{18,49,59}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2016,5,10},{18,49,59}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}

Crash dump was written to: /var/log/ejabberd/erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k

**Comment by joe-liberty** [comment]
Checking forums for this trouble to see what is going on because I tried quite a few suggestions. This IS NOT an issue with JSXC. I will post back when I make more progress

**Comment by joe-liberty** [comment]
I configured Openfire and I am able to connect via pidgin. I set up Proxy via Apache2. I still cannot connect using Owncloud though. I am getting this message:

**BOSH server NOT reachable or misconfigured.

Cross domain request was not possible. Either your BOSH server does not send any Access-Control-Allow-Origin header or the content-security-policy (CSP) blocks your request. Starting from Owncloud 9.0 your CSP will be updated in any app which uses the appframework (e.g. files) after you save these settings and reload.The savest way is still to use Apache ProxyRequest or Nginx proxy_pass.**

I have no idea why it is doing this if I can connect with Pidgin. Pidgin did not like "localhost" in BOSH url but if I replace "localhost" with the server ip address it works. Any ideas?

**Comment by sualko** [comment]
> The savest way is still to use Apache ProxyRequest or Nginx proxy_pass

**Comment by joe-liberty** [comment]
There is something screwed up royally with this server. It fails on "**BOSH server NOT reachable or misconfigured.
Cross domain request was not possible. Either your BOSH server does not send any Access-Control-Allow-Origin header or the content-security-policy (CSP) blocks your request. Starting from Owncloud 9.0 your CSP will be updated in any app which uses the appframework (e.g. files) after you save these settings and reload.The savest way is still to use Apache ProxyRequest or Nginx proxy_pass.**"

I can ping localhost and domain with no problem. It does not like my hostname for some reason. Pidgin does not like it either. Can only connect with pidgin using ip address to BIND. Pulling my hair out on this one. Proxy requests made no difference. I do not get much time on here as I am working long hours and weekends. Thanks for your help
