### ISSUE TITLE
[Question] How connect a client with the new internal Server?

### ISSUE THREAD

**Issue by Mannshoch** [jsxc/jsxc#334]
I read that this addon come with an integrated Server.

How could I connect the App [Conversations](https://f-droid.org/repository/browse/?fdfilter=conversations&fdid=eu.siacs.conversations) - [Github](https://github.com/siacs/Conversations) with this Server?
Do I need an Other App?

**Comment by MarcelWaldvogel** [comment]
The internal server is used as a starting position to have an app which works immediately. It is a minimal implementation of XMPP, just enough to run JSXC. It is not meant as a replacement for a real server and isn't such a replacement, either. If you would like to scale (adding clients, creating a federation, adding features, …), you set up a real server. Ejabberd or Prosody are not hard to set up.

**Comment by Mannshoch** [comment]
Thanks for the answer. 
I'm Limited on php and Perl (no ssh access) because of the Provider I have.

Please add this Info to the hint about the implemented Server.
