### ISSUE TITLE
Token-based authentication to the XMPP backend

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#337]
In some web applications, especially when using a single-sign-on mechanism, JSXC does not have access to the password. However, there might be a trust relationship between the web application and the XMPP server, e.g., because they are under the same management.

Then, the desirable user experience of [dual login](https://github.com/jsxc/jsxc/blob/master/example/dev.html#L71) cannot be achieved.

An alternative, requested in this enhancement, would be as follows:
1. The web application and the XMPP server share a secret, a name for that app (and secret), and a session lifetime
2. Login happens only to the "normal" web application, not to JSXC
3. On login or any (re-)authentication, JSXC --- in the manner of Kerberos --- asks the web application backend for a ticket to pass to XMPP server
4. The web backend verifies that this request comes from an authenticated session and returns the appropriate ticket
5. JSXC passes the ticket as a password substitute to the XMPP server
6. The XMPP server verifies the ticket as if it were a password.

Possible ticket format is based on a `(format, appname, username, validity, authenticator)` tuple:

``` JavaScript
format = "tv1";
validity = now() + lifetime;
info = format + '\0' + appname + '\0' + username + '\0' + validity;
ticket = base64(info + '\0' + hex(HMAC(secret, info));
```
##

**Comment by sualko** [comment]
Implemented in https://github.com/jsxc/xmpp-cloud-auth and https://github.com/nextcloud/jsxc.nextcloud/commit/775528d0334b89229c37f3609e067eff0db077ae
