### ISSUE TITLE
Windows stays open after logged out

### ISSUE THREAD

**Issue by ismatkurt** [jsxc/jsxc#338]
Hello, I added jsxc to my existing angular project. It works well, there is no problem until logging out, 
Although I added logoutelement in init, after user exit from my app chat windows stays open. But actually jsxc logged out certainly.

```
jsxc.init({
   logoutElement: $('#logout'),
```

Thanks for help

**Comment by sualko** [comment]
Please try our latest nightly build and change your config to the following:

```
jsxc.init({
   logoutElement: '#logout',
```

I had a similar issue with the sogo version and fixed it in https://github.com/jsxc/jsxc/commit/3a29d2a96cd3f4e15c7041026189cbdf864c7291.
