### ISSUE TITLE
ownCloud: chat panel stays open after logout

### ISSUE THREAD

**Issue by cptMikky** [jsxc/jsxc#340]
When user logs out of ownCloud, the chat panel and conversations remain open and functional, although somewhat graphically dissorted. Reloading the logout/login page helps.

This might be related to #338 but circumstances are a bit different.

Using version from app.owncloud from May 14, 2016 with ownCloud 9.0.2.2, installed via ownCloud admin interface.

**Comment by sualko** [comment]
Should be fixed in the latest [beta release](https://github.com/jsxc/jsxc/releases/tag/v3.0.1-beta2)
