### ISSUE TITLE
Maximum 10 MUCs ?

### ISSUE THREAD

**Issue by khanhmas** [jsxc/jsxc#342]
Actually, i only can create 10 rooms maximum, when i create the 11th, the server sends the error code 503 service-unavailable.
##

**Comment by MarcelWaldvogel** [comment]
What is your setup? Which XMPP server do you use?

**Comment by khanhmas** [comment]
I'm using ejabberd as a XMPP server. I forgot to mention that I could create more than 10 rooms via command line.
Below is the config concerning MUC :
access:
  muc: 
    all: allow
  muc_admin: 
    admin: allow
  muc_create: 
    local: allow
modules:
  mod_muc: 
    ## host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_muc_admin: {}

**Comment by sualko** [comment]
> the server sends the error code 503 service-unavailable

Please check your server log and report corresponding messages. I don not see any obviously reason, why jsxc should prevent the creation of more than 10 rooms.

**Comment by khanhmas** [comment]
I checked the server log for the corresponding messages and here they are :

[debug] <0.15285.3>@mod_http_bind:process:68 Incoming data: <body rid='621916642' xmlns='http://jabber.org/protocol/httpbind' sid='c8bbf60ac220d8dfb743071de79c83016ed21aca'><iq from='akhanh@xmpp.ceo-vision.com/example' to='a2@conference.xmpp.ceo-vision.com' type='get' xmlns='jabber:client' id='45402eaf-5658-40b0-9674-36fe0884eae1:sendIQ'><query xmlns='http://jabber.org/protocol/disco#info'/></iq></body>

[debug] <0.15285.3>@ejabberd_http_bind:parse_request:1114 --- incoming data ---
<body rid='621916642' xmlns='http://jabber.org/protocol/httpbind' sid='c8bbf60ac220d8dfb743071de79c83016ed21aca'><iq from='akhanh@xmpp.ceo-vision.com/example' to='a2@conference.xmpp.ceo-vision.com' type='get' xmlns='jabber:client' id='45402eaf-5658-40b0-9674-36fe0884eae1:sendIQ'><query xmlns='http://jabber.org/protocol/disco#info'/></iq></body>
 --- END ---

[debug] <0.30327.1>@ejabberd_router:do_route:351 route
        from {jid,<<"a2">>,<<"conference.xmpp.ceo-vision.com">>,<<>>,<<"a2">>,<<"conference.xmpp.ceo-vision.com">>,<<>>}
        to {jid,<<"akhanh">>,<<"xmpp.ceo-vision.com">>,<<"example">>,<<"akhanh">>,<<"xmpp.ceo-vision.com">>,<<"example">>}
        packet {xmlel,<<"iq">>,[{<<"type">>,<<"error">>},{<<"to">>,<<"akhanh@xmpp.ceo-vision.com/example">>},{<<"from">>,<<"a2@conference.xmpp.ceo-vision.com">>},{<<"id">>,<<"45402eaf-5658-40b0-9674-36fe0884eae1:sendIQ">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/disco#info">>}],[]},{xmlel,<<"error">>,[{<<"code">>,<<"404">>},{<<"type">>,<<"cancel">>}],[{xmlel,<<"item-not-found">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]},{xmlel,<<"text">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[{xmlcdata,<<"Conference room does not exist">>}]}]}]}

[debug] <0.15469.3>@ejabberd_http_bind:prepare_response:900 OutPacket: [{xmlstreamelement,{xmlel,<<"iq">>,[{<<"from">>,<<"a2@conference.xmpp.ceo-vision.com">>},{<<"to">>,<<"akhanh@xmpp.ceo-vision.com/example">>},{<<"type">>,<<"error">>},{<<"id">>,<<"45402eaf-5658-40b0-9674-36fe0884eae1:sendIQ">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/disco#info">>}],[]},{xmlel,<<"error">>,[{<<"code">>,<<"404">>},{<<"type">>,<<"cancel">>}],[{xmlel,<<"item-not-found">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]},{xmlel,<<"text">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[{xmlcdata,<<"Conference room does not exist">>}]}]}]}}]

[debug] <0.15469.3>@ejabberd_http_bind:send_outpacket:1042  --- outgoing data ---
<body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' from='a2@conference.xmpp.ceo-vision.com' to='akhanh@xmpp.ceo-vision.com/example' type='error' id='45402eaf-5658-40b0-9674-36fe0884eae1:sendIQ'><query xmlns='http://jabber.org/protocol/disco#info'/><error code='404' type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Conference room does not exist</text></error></iq></body>
 --- END ---

[debug] <0.15469.3>@ejabberd_http_bind:parse_request:1114 --- incoming data ---
<body rid='621916643' xmlns='http://jabber.org/protocol/httpbind' sid='c8bbf60ac220d8dfb743071de79c83016ed21aca'><presence from='akhanh@xmpp.ceo-vision.com/example' to='a2@conference.xmpp.ceo-vision.com/akhanh' xmlns='jabber:client'><x xmlns='http://jabber.org/protocol/muc'/></presence></body>
 --- END ---


[debug] <0.30327.1>@mod_muc:start_new_room:710 MUC: open new room 'a2'


[info] <0.15565.3>@mod_muc_room:init:123 Created MUC room a2@conference.xmpp.ceo-vision.com by akhanh@xmpp.ceo-vision.com/example


[info] <0.15565.3>@mod_muc_room:close_room_if_temporary_and_empty:1143 Destroyed MUC room a2@conference.xmpp.ceo-vision.com because it's temporary and empty


[info] <0.15565.3>@mod_muc_room:terminate:836 Stopping MUC room a2@conference.xmpp.ceo-vision.com


[debug] <0.15285.3>@ejabberd_http_bind:prepare_response:900 OutPacket: [{xmlstreamelement,{xmlel,<<"presence">>,[{<<"from">>,<<"a2@conference.xmpp.ceo-vision.com/akhanh">>},{<<"to">>,<<"akhanh@xmpp.ceo-vision.com/example">>},{<<"type">>,<<"error">>}],[{xmlel,<<"x">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/muc">>}],[]},{xmlel,<<"error">>,[{<<"code">>,<<"503">>},{<<"type">>,<<"cancel">>}],[{xmlel,<<"service-unavailable">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]}]}}]


[debug] <0.15285.3>@ejabberd_http_bind:send_outpacket:1042  --- outgoing data ---
<body xmlns='http://jabber.org/protocol/httpbind'><presence xmlns='jabber:client' from='a2@conference.xmpp.ceo-vision.com/akhanh' to='akhanh@xmpp.ceo-vision.com/example' type='error'><x xmlns='http://jabber.org/protocol/muc'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></presence></body>

**Comment by sualko** [comment]
Could you resolve your issue?

**Comment by khanhmas** [comment]
Yes, i resolved it, that was about the XMPP's configuration.

Thanks you very much. We can close this issue.
