### ISSUE TITLE
Installation Guide and Example Do Not Work

### ISSUE THREAD

**Issue by isapi** [jsxc/jsxc#343]
The installation guide at https://github.com/jsxc/jsxc/wiki/Install-jsxc seem to miss many details and does not work.

I've followed the steps but nothing happens.

I've also tried the example but that does not work either.  I am using BOSH at port 7070 but there is no way to specify that, and even when I tried to hard code it in example.js the requests seem to go to the URL without port 7070.  IMO a port number should be configurable in the example page.

**Comment by sngyai** [comment]
You should config your nginx like this: [https://github.com/jsxc/jsxc/wiki/Prepare-nginx](url)
or [https://github.com/jsxc/jsxc/wiki/Prepare-apache](url) if you use apache.

**Comment by TwentyOneSolutions** [comment]
Thank you for your reply.

Why do you force the use of a web server?  It should be very simple to add
a port rather than force everyone to set up port forwarding.

**Comment by MarcelWaldvogel** [comment]
That's due to the interplay between web browser security restrictions (same origin etc.) and what is currently supported by BOSH implementations.

**Comment by sualko** [comment]
@TwentyOneSolutions The installation guide illustrates how you can use an other port, so where exactly is your issue?

```
xmpp: {
         url: 'http://localhost:5280/http-bind/',
```
