### ISSUE TITLE
RTCPeerConfig seems doesn't work

### ISSUE THREAD

**Issue by sngyai** [jsxc/jsxc#345]
Hi,
Sorry for disturbing.
File-transfer and Video calling are working if users are on the same LAN. Calls from a cellular (natted) line cause a "jingle_reason_failded-transport) error (ICE_connection_failure), like described in [225](https://github.com/jsxc/jsxc/issues/225) and [302](https://github.com/jsxc/jsxc/issues/302). I've read these issues carefully, but I still don't know how to config an iceServer, here is my config:

```
RTCPeerConfig: {
      /** Time-to-live for config from url */
      ttl: 3600,

      /** [optional] If set, jsxc requests and uses RTCPeerConfig from this url */
      url: null,

      /** If true, jsxc send cookies when requesting RTCPeerConfig from the url above */
      withCredentials: false,

      /** ICE servers like defined in http://www.w3.org/TR/webrtc/#idl-def-RTCIceServer */
      iceServers: [
        {url: 'stun:stun.l.google.com:19302'},
        {url: 'stun:stun.anyfirewall.com:3478'},
        {url: 'turn:turn.bistri.com:80', credential: 'homeo', username: 'homeo'},
        {url: 'turn:turn.anyfirewall.com:443?transport=tcp', credential: 'webrtc', username: 'webrtc'}
      ]
}
```

these options were added in `jsxc.init`, but it doesn't seems to work, whether connect to my own ejabberd 16.04 server or  `https://conversejs.org/http-bind`(which provides BOSH connection)with the domain 'jabber.at'.
I also tried to use `{url: 'stun:stun.services.mozilla.com'} `and  `{url: 'stun:aa'} ` which is purposely misspelled, but got same result as before: video calling and file transfer worked very good  if users are on the same LAN. but did not work when they are not in the same LAN.
So I was wondering whether my config is correct.
Many thanks.

**Comment by sualko** [comment]
According to [w3.org](https://www.w3.org/TR/webrtc/#rtciceserver-dictionary) you should use ``urls``instead of ``url``. After changing your settings you should relogin. Please also check your javascript (strg+shift+I) and webrtc console (chrome://webrtc-internals or about:webrtc).

**Comment by sngyai** [comment]
Many thanks, though I finally turn to XEP-0363 myself.

**Comment by sualko** [comment]
Can we close this issue?

**Comment by sngyai** [comment]
Yes, thanks a lot
