### ISSUE TITLE
Doesn't work with unicode  passwords

### ISSUE THREAD

**Issue by balping** [jsxc/jsxc#346]
Hi!

I'm using version 3.0.0 with owncloud 9 and ejabberd on ubuntu 14.04

When a user password contains some non-english characters, it's unable to log in.

Example:  user with the single character password `e` is able to log in to the chat, while with password `é`, not.

I've been debugging a bit and it seems that the password is lost somewhere before [this point](https://github.com/owncloud/jsxc.chat/blob/master/auth_ejabberd_oc.php#L140). It's somehow not passed.
##

**Comment by sualko** [comment]
If I get it right, this issue is only related to the external auth script, isn't it?

**Comment by balping** [comment]
Yes. Sorry if it wasn't clear.

**Comment by sualko** [comment]
Maybe you want to test the new authentication script nextcloud/jsxc.nextcloud#4
