### ISSUE TITLE
Frustration getting things to work

### ISSUE THREAD

**Issue by BruceJustice** [jsxc/jsxc#348]
Hello, this question might sound primitive but I'm more of a user than developer, trying to get this work.

I am having some problems with the JSXC application for the OwnCloud. The raster is not even there, although sometimes it will pop up saying that I have to re-login. I got this working on my previous OwnCloud installation, but now as I reinstalled it, doesn't work. When I click the "Relogin" button, I get a message saying that an Authentication Error occurred and I might have forgotten my password. But to be honest with you, I have tried all of the possible usernames/passwords and still nothing. I tried logging in with my Android device, the raster is displayed a bit more often there than on PC, but it is also asking me to Relogin.

To make my configuration clear:
I have set-up the OwnCloud 9.0.3 on GoDaddy Hosting account with PHP 5.6 and it is working fine. I have created an account and verified my domain on hosted.IM for an XMPP server. The server url as well as BOSH is recognized and working well. TURN details are also entered as they should be. I tried many different versions of usernames and passwords, none of them worked. Also, I was switching between "Internal (Experimental)" and "External" configurations but nothing helped.

Please help, I don't know what to do but I really want to get this working, your app would help so much for my project! Thanks

**Comment by sualko** [comment]
Please open your JS console (ctrl+shift+I) and report any error.

**Comment by gzdncs** [comment]
Did you get this to work?

**Comment by sualko** [comment]
I close this issue, because it is not enough information provided.
