### ISSUE TITLE
Support XEP-0363 HTTP_Upload

### ISSUE THREAD

**Issue by tigre-bleu** [jsxc/jsxc#349]
http_upload is supported by Conversations in Android, Monal in iOS and OSX as well as Gajim for Linux and is proposed standard xep-0363.

This is a very useful XEP for asynchronous picture sharing (Send picture while receiver is offline)

I would like to deploy a web chat for our users, but I have currently found no web client supporting this XEP.

Does Jsxc team plan to support http upload in the future?
##

**Comment by sngyai** [comment]
Five steps:
1. Discover if the server support this feature, get **_uploadUrl_**
2. Send iq get to take a slot
```
<iq to='**_uploadUrl_**' id='z5lZD-169' type='get'>
	<request xmlns='urn:xmpp:http:upload'>
		<filename>Screenshot_20160705-151011.png</filename>
		<size>919453</size>
	</request>
</iq>
```
when response like:
```
<iq from=**_uploadUrl_** to='user@server/Resource' id='cjSHO-147' type='result'>
    <slot xmlns='urn:xmpp:http:upload'>
        <put>http://serverhost:5443/upload/d7cecb32f78b57adf553a22b568bdfc0b336c55b/dEGAFXJlUWq75eJFoJIq3jtS2Uv5eCxgaCOeA2YP/Screenshot_20160705-151011.png</put>
        <get>http://serverhost:5443/upload/d7cecb32f78b57adf553a22b568bdfc0b336c55b/dEGAFXJlUWq75eJFoJIq3jtS2Uv5eCxgaCOeA2YP/Screenshot_20160705-151011.png</get>
    </slot>
</iq>

```
3. Put the file to the **_put_** you got in step 2.(I used AJAX put)
4. Send **_put_** as a regular message to another user
5. The other user got **_put_** and download it from the server
These are not that hard to deal, you can acomplish it yourself, GOOD LUCK!

**Comment by MarcelWaldvogel** [comment]
Can you provide a pull request?

**Comment by sngyai** [comment]
I am new to Javascript and my code is rather ugly.

**Comment by MarcelWaldvogel** [comment]
So it would be a great chance to practice. Make a start and we can help you improving.

**Comment by sngyai** [comment]
I have done what you told me. You may check my pull request.
By the way, this is the first time I create pull request on Github.

**Comment by MarcelWaldvogel** [comment]
Thank you very much and congratulations to your first pull request!
I am not a JavaScript expert either, but I hope @sualko can have a look at it soon. To me, the code already looks rather skillful.
From the GUI patch, it looks like your code does not fall back to the old transfer mode if the server does not support HTTP upload. Could you add this?

**Comment by sngyai** [comment]
Thank you. I've done it. Please check it out.

**Comment by tigre-bleu** [comment]
Nice to see this this topic taking off so fast!

**Comment by kitschkite** [comment]
Still no other browser client with XEP-0363 support, would be nice to see jsxc first out!

**Comment by pmehul55** [comment]
@sngyai  Can you please help out for image upload in xmpp ejabberd server in swift or objective language ?

**Comment by shravanteegala** [comment]
How i can Add the XMPP Extension XEP-0363 for Asynchronous image sharing and File upload in
my IOS XMPP Project.
When i try to Add the module In Objective-c rep-0363 Header not found.
Please help me.

**Comment by MarcelWaldvogel** [comment]
Please do not hijack unrelated issues.
