### ISSUE TITLE
Problems with Prelogin

### ISSUE THREAD

**Issue by workdreamer** [jsxc/jsxc#350]
I am using xmppPrebind to conect to the server.
If i attach the piece of code from Prelogin, so this is not doing anything.
If i attach the piece of code of AJAX Prelogin

It opens the chat menu, but i don't have any bind of settings, and it doesn't load my roster contacts.

Any help would be useful.
##

**Comment by sualko** [comment]
Sorry for the very late response. Please provide some of your example code and report all related messages in your js console.

**Comment by sualko** [comment]
Please reopen this issue if needed.
