### ISSUE TITLE
Apache ProxyPass for BOSH url

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#353]
Hello, 

I apoligize in advance as I see there are many issues already posted with my same content. 

I have followed your post regard proper apache setup to remove the port from the BOSH URL. Though it appears to take a bit longer before displaying the error, the same error still shows:

BOSH server NOT reachable or misconfigured.

Cross domain request was not possible. Either your BOSH server does not send any Access-Control-Allow-Origin header or the content-security-policy (CSP) blocks your request. Starting from Owncloud 9.0 your CSP will be updated in any app which uses the appframework (e.g. files) after you save these settings and reload.The savest way is still to use Apache ProxyRequest or Nginx proxy_pass.

Reading thru your other posts, this my CORS headers are messed up. Below is my virtual host configuration with headers to try to mitigate the CORS issues. I am hoping that you could help point me in the right direction!

`VirtualHost *:80
  ServerAdmin webmaster@localhost
  ServerName im.greysky.me
  ProxyRequests off
  
  ProxyPass /http-bind/ http://localhost:5280/http-bind/
  ProxyPassReverse /http_bind/ http://localhost:5280/http-bind/
  
  <Location /http-bind>
    Order allow,deny
	Allow from all
  </Location>
  Header always set Access-Control-Allow-Origin: "*"
  Header always set Access-Control-Max-Age "1000"
  Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
  Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
/VirtualHost`

Thank you!

**Comment by skyfox675** [comment]
Resolved, Ended up using ARR 3.0 with IIS 8.5 with a virtual host for /http-bind/ on the IIS server hosting owncloud, terminating SSL at IIS. Then changed the BOSH URL to HTTPS to have secure resources.

Great app, will recommend and use for a long time to come!

**Comment by sualko** [comment]
> Great app, will recommend and use for a long time to come!

We are proud that you enjoy jsxc. If you have further questions, please write me an email, or open a issue.

**Comment by cdmlb** [comment]
I wish skyfox675 would of wrote a tutorial for this lol.

Trying to find things online and testing it out does not seem to work for me.

I'm using IIS10, ARR3, and UrlReWrite2.
Plus I'm trying to get this working with Roundcube Webmail.
My IIS and php install work. So does my Roundcube and my ejabberd install.

My issue is to do with the virtual host, proxy binding, etc.
As soon as I do a IIS binding on domain.com:5280 and try to run ejabbered on the same port which is not really possible because it makes one or the other fail, since you can't really have two things on the same port. So I tried like domain.com:5281 bosh to and from domain.com:5280 but no go.

**Comment by sualko** [comment]
@cdmlb I'm sorry, but we can't give you advice, because we use the LAMP stack.

**Comment by skyfox675** [comment]
@cdmlb sorry for the delayed response, been a dark month and haven't worked on things in a while, just getting back in the swing!

Ok so! I can't give you just the IIS portion of my implementation as I have a few layers at play but I'll do my best.

Your first goal should be to have all required "resources" served under the same domain _and_ port. Per CORS documentation, together the IP/DNS Name and Port form an Origin. A change in Origin will invoke the browser CORS protection. To keep your life easier, I suggest keeping all resources under your single DNS Name and port 443.

For my enviroment, all SSL termination is preformed by DMZ'ed HAProxy servers. Without diving too much into their configuration here is the basic idea.

1. Browser request (http)

2. HAProxy responds 301 Moved Permanently (to https) and Modifies the following headers:
- Add Strict-Transport-Security:\ max-age=31536000;\ includeSubDomains;\ preload
- Remove ^Server:.*$
- Remove ^X-Powered-By:.*$
- Remove ^X-AspNet-Version:.*$

3. SSL cipher suite and SSL tuning is done between browser and HAProxy once the SSL connection is established, The request is forwarded via HTTP to the IIS cluster for further processing.

4. The IIS servers receive http://example.com/bosh, the bindings match example.com and port 80.

5. I don't use virtual directories, /bosh is a subfolder in the example.com site's root containing only a web.config

6. The important section (pretty much all of it lol) of the web.config is as follows:
`<system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" enabled="true" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://internalserver:internalport/bosh/{R:1}" />
                    <serverVariables>
                        <set name="ORIGINAL_HOST21" value="{HTTP_HOST}" />
                        <set name="HTTP_X_FORWARDED_PROTO" value="https" />
                        <set name="HTTP_X_FORWARDED_PORT" value="5443" />
                        <set name="HTTP_X_FORWARDED_HOST" value="example.com" />
                    </serverVariables>
                </rule>
            </rules>
            <outboundRules>
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1" enabled="true">
                    <match filterByTags="A, Form, Img" serverVariable="RESPONSE_Location" pattern="^http://[^/]+/(.*)" />
                    <action type="Rewrite" value="http://{ORIGINAL_HOST21}/{C:1}/{R:1}" />
                    <conditions>
                        <add input="{ORIGINAL_HOST21}" pattern=".+" />
                        <add input="{URL}" pattern="^/(bosh)" />
                    </conditions>
                </rule>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                    <preCondition name="IsRedirection">
                        <add input="{RESPONSE_STATUS}" pattern="3\d\d" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
        <httpErrors errorMode="DetailedLocalOnly" />
        <directoryBrowse enabled="false" />
    </system.webServer>`

7. Important note, even though in the web.config you have specified "set name="ORIGINAL_HOST21" value="{HTTP_HOST}" you must in the IIS GUI create the variable of the same name in the example.com site, otherwise this will cause odd 5XX errors.

8. Repeat for all /urls that you want to bring under the same domain.

Hope that helps, this allowed me to not need to modify CORS headers as all resources origins are the same domain as seen by the client's browser.

**Comment by cdmlb** [comment]
Wow @skyfox675 thanks for the info. I understood most of all you wrote, because I implemented some of these things. A few things you put I will implement too. Thanks for the teachings.

I'm using IIS for asp.net and php with MS-SQL and MySQL, so far that all works great.

Using BIND9 for DNS, works great.

Decided to install Apache to do the proxy stuff but still playing around with IIS with the Application Routing and URL Rewrites. Problem with IIS I found was if you do virtual host / bindings the port can't be used on the same network card, makes the program crash since two programs want to listen and not share the port, but with Apache no issues for using same ports for virtual host / binding.

Let's Encrypt is awesome for certs but I still have some road to go on the xmpp and jsx for encryption.

For xmpp setup ejabberd and decide to use jsxc because I have hMailServer with Roundcube webmail setup and there's a plugin for jsx for roundcube.

And lots more stuff lol.

Thank you.

**Comment by sualko** [comment]
@cdmlb it would be awesome if you could share your new knowledge with the community and write a little [wiki article](https://github.com/jsxc/jsxc/wiki) about the setup with IIS.

**Comment by cdmlb** [comment]
@sualko can I? You going to let me? Sweet!

**Comment by sualko** [comment]
Sure you can. Everyone can edit the wiki pages. If you have an issue, just write a message.

**Comment by cdmlb** [comment]
@sualko @skyfox675 thanks.

https://github.com/jsxc/jsxc/wiki/Using-JSXC-on-Windows-with-IIS
