### ISSUE TITLE
Feature request to add typing notifications

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#355]
Hello all, 

I would like to inquire about the possibility to add a new feature to support typing notifications to each chat window! 

Not sure how difficult this would be, I am very new to this platform, so please be gentle :)

**Comment by DanScharon** [comment]
related to #9

**Comment by sualko** [comment]
I would say this is a duplicate of #9. If you would like to start working on this, please open a pull request with the title "XEP-0085: Chat State Notifications [WIP]" to discuss the details.
