### ISSUE TITLE
Test installation missing styles

### ISSUE THREAD

**Issue by fcer** [jsxc/jsxc#356]
Hi.

I'm trying to set-up a test installation of jsxc. I can login and messages are delivered; everything works great, except some controls are displayed incorrectly... I think I'm missing some css, but I included all there is in the css folder. What am I missing?

This is my test .html

```
<html>
<head>
	<title>JSXC Test</title>
	<link href="css/jsxc.css" media="all" rel="stylesheet" type="text/css" />
	<link href="css/jquery-ui.min.css" media="all" rel="stylesheet" type="text/css" />
	<link href="css/magnific-popup.css" media="all" rel="stylesheet" type="text/css" />
	<script src="lib/jquery.min.js"></script>
	<script src="lib/jquery.ui.min.js"></script>
	<script src="lib/jquery.slimscroll.js"></script>
	<script src="lib/jquery.fullscreen.js"></script>
	<script src="lib/jsxc.dep.js"></script>
	<script src="jsxc.min.js"></script>
	<script src="index.html.js"></script>
</head>
<body>
	<button id="ShowLogin">Open Box</button>
</body>
</html>
```
And this is the custom index.html.js:

```
$(function() {
	jsxc.init({
		loginForm: {
			form: '#form',
			jid: '#username',
			pass: '#password'
		},
		logoutElement: $('#logout'),
		root: '/js-xmpp/jsxc',
		xmpp: {
			url: 'http://localhost:7070/http-bind/',
			domain: 'localhost'
		}
	});
	$(document).on('ready.roster.jsxc', function(){
	   $('#content').css('right', $('#jsxc_roster').outerWidth() + parseFloat($('#jsxc_roster').css('right')));
	});
	$(document).on('toggle.roster.jsxc', function(event, state, duration){
	   $('#content').animate({
	      right: ((state === 'shown') ? $('#jsxc_roster').outerWidth() : 0) + 'px'
	   }, duration);
	});
	$('#ShowLogin').click(jsxc.gui.showLoginBox);
});
```
And this is how it looks in my browser:

![jsxc_screenshot](https://cloud.githubusercontent.com/assets/20867431/17452914/87f69da6-5b31-11e6-84ff-87384a017ce0.JPG)

**Comment by sualko** [comment]
I can only see that the "closing X" is missing. Is there anything else, because this X is the [multiplication sign](https://en.wikipedia.org/wiki/Multiplication_sign) and requires UTF-8.

**Comment by fcer** [comment]
Yeah the "x" was one thing... a charset fixed it. And actually there was another issue with the font of the text in the chat window and the user names. I was able to fix it by adding a link to the bootstrap.min.css that's included in the example you provide in the source... but shouldn't that css be included in the "core" files too? Without it the app looks very different...

Without the css:
![without bootstrap_css](https://cloud.githubusercontent.com/assets/20867431/17484954/6007ab90-5d49-11e6-85a3-41fed54c0941.jpeg)

With the css:
![with bootstrap_css](https://cloud.githubusercontent.com/assets/20867431/17484953/5ff9f4aa-5d49-11e6-8839-a9a319026c91.jpeg)

**Comment by xZak47** [comment]
Hello Fcer, can you contact me please? I will propose you an offer for JSXC integration and propose you to design your chat

Thanks

**Comment by sualko** [comment]
@fcer bootstrap.min.css is optional, so it is not included in the core css file.
