### ISSUE TITLE
How can upload avatar?

### ISSUE THREAD

**Issue by devendrawebdeveloper** [jsxc/jsxc#357]
Hello,

I have install jsxc.It is working fine but I am missing something.How can I upload user avatar?

Thankyou

**Comment by sualko** [comment]
Avatar upload is currently not supported. It was also requested in #304, so I close this issue as duplicate.

**Comment by MarcelWaldvogel** [comment]
FYI: An avatar uploaded with another client will be honored by JSXC.

(Pull request with an upload code is appreciated.)
