### ISSUE TITLE
How enable send files

### ISSUE THREAD

**Issue by cirovargas** [jsxc/jsxc#364]
How i can enable jsxc to send files? 

Acctualy the send file option is disabled

**Comment by cirovargas** [comment]
When i login, the option send file is disabled. If i refresh the page throws this error:

jsxc.js:9056 Uncaught TypeError: Cannot read property 'caps' of null

**Comment by MarcelWaldvogel** [comment]
Which XMPP Server (Software, plugins) do you use?

**Comment by cirovargas** [comment]
O peneire. Im using spark as desktop client.  On spark the file send works fine

**Comment by cirovargas** [comment]
Openfire

**Comment by sualko** [comment]
Currently file transfer is only supported between jsxc clients, so it is disabled if you chat with a spark client.
