### ISSUE TITLE
HTTPS ?

### ISSUE THREAD

**Issue by emma3138** [jsxc/jsxc#365]
Hi,

I'm including jsxc on my intranet
My intranet is a HTTP**S** site

I have a problem during the connexion to jsxc :
Blocage du chargement du contenu mixte actif (mixed active content) « http://chat.XXX.fr:7070/http-bind/

How can i do ? Is it possible to have a HTTPS for  http://chat.XXX.fr:7070/http-bind/ ?

Thanks

**Comment by MarcelWaldvogel** [comment]
Yes, this is even the recommended setup. You need to talk to your XMPP server admin to have this set up (or tell you the access parameters).
(One option for minimum changes on the XMPP server, run stunnel in server mode on another port of the XMPP server, say 7071, and have it decrypt everything and forward it to the existing BoSH port.

**Comment by joergmschulz** [comment]
For me this is a bit confusing now.
When I run ejabberd, the default is to have all data encrypted on the existing bosh port.
But, tonight I saw that jsxc cannot connect to this encrypted port - it relies on it to be unencrypted.
So far so good - what about the data that are transferred via this unencrypted channel: Will the /private/communications be encrypted and only the unencrypted communication unencrypted?
Would, if jsxc could connect to bosh in an encrypted way, even the communication metadata be encrypted?

**Comment by MarcelWaldvogel** [comment]
There are (in general) up to four transport connections, all of which can be encrypted, if HTTPS (first three) or XMPP-S2S+STARTTLS (last one) is selected. They hide the identity and contents of the data from someone snooping the network.

1. The browser connection to the web application (configured in the application/its web server)
1. The browser connection to BoSH (often to the same host and with the same protocol as above; configured in the application settings, in this case ownCloud admin panel)
1. If the above connection is to the same host, a proxy connection from there to the real BoSH server (configured in the web server's proxy configuration).
1. When the chat is to someone on another server, the XMPP server-to-server connection (s2s), which is typically encrypted, when both servers support STARTTLS encryption.

I do not know, which setup you have there and which of those connections you mean (probably, 2 or 3 above).

Besides these transport connections, where the admin has to activate them, there is end-to-end encryption using [OTR](https://en.wikipedia.org/wiki/Off-the-Record_Messaging) (currently supported by JSXC) and [OMEMO](https://en.wikipedia.org/wiki/OMEMO) (not yet supported). This can be enabled/disabled by the user and adds an additional layer of security, hiding the contents to the server.

**Comment by joergmschulz** [comment]
Yes, I'm talking about 2&3. So, in a https environment, the apache proxy traffic to the BoSH server will be unencrypted, but, because it is a proxy, the traffic between the end user and the NC or OC server will stay encrypted (connection 1). Thank you for clarifying.

**Comment by MarcelWaldvogel** [comment]
All of them can be encrypted, if you configure them correctly. Which one are you having trouble with configuring?

**Comment by joergmschulz** [comment]
When I enable TLS for the BoSH server of ejabberd, the ojsx admin in NC tells me the connection cannot be established. I proxy it using the http proxy like documented; when I disable TLS the connection is established.  This might be related to the fact that the apache test environment I used yesterday is http only, and I didn't configure the proxy correctly to handle https. If you say that it is possible to leave tls enabled in the ejabberd BoSH server, I probably need another go at the apache proxy configuration?

**Comment by MarcelWaldvogel** [comment]
Yes, I have HTTPS enforced for all connections that are not only within the same machine.

(I have only enabled S2S STARTTLS and keep it optional; but probably now the vast majority of XMPP servers supports S2S with STARTTLS, so it could be enforced)

**Comment by joergmschulz** [comment]
answer is easy: If you have a Non-SSL server (which nobody should have, anyway), you must disable tls for your BoSH server. Else keep it enabled and everything works out fine. Thanks for clarifying!
