### ISSUE TITLE
Refreshing and Reconnect

### ISSUE THREAD

**Issue by rauljuarez** [jsxc/jsxc#366]
Hi, im trying to use the client, and the idea is that im sending the params, once my user is logged into my site, so i got a connection ok. The thing is that the user might be able to chat or not, but im loosing the connection once the timeout expires. How do i maintain a connection always present on the site, with my XMPP server.
I got thios behaviour with my iOS and Android App and i woulkd like to have the same.

Also, once im connected and i refresh the browser, i loose the connection. 
##

**Comment by sualko** [comment]
Which timeout and what do you mean with "the user might be able to chat or not"? Please provide also a snippet from your jsxc login code.
