### ISSUE TITLE
Owncloud 9.1.0, ojsxc 3.0.0 prevents login on Firefox.

### ISSUE THREAD

**Issue by noci2012** [jsxc/jsxc#368]
Having the Chat app enabled there is a lot of logging like: 
{"reqId":"xxxxxxxxxxxxxx","remoteAddr":"127.0.0.1","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/xxxxxxxxxx\/htdocs\/apps\/ojsxc\/ajax\/getSettings.php#53","level":3,"time":"2016-09-12T12:56:35+00:00","method":"POST","url":"\/index.php\/apps\/ojsxc\/ajax\/getSettings.php","user":"--"}

Logon through Firefox just hangs there, (I would not expect this to be called from the logon page of owncloud, ie. no credentials have been validated yet.)
For some reason Chromium does get past this a little more, just other modules like calandar with shared calendars from someone else fail to work.

Disabling the "Java Script XMPP Chat" app lets firefox login, also the calendar starts working again and  even for shared calendars.
##

**Comment by sualko** [comment]
Did you configure jsxc correctly? Can you login to your xmpp server via jsxc? Does the "login without chat" link work?

**Comment by sualko** [comment]
Please test our latest [beta release](https://github.com/jsxc/jsxc/releases/tag/v3.0.1-beta2) it should fix at least the login issue.

**Comment by noci2012** [comment]
it seems to work.... did check with firefox whith problems yet.
