### ISSUE TITLE
Inline CSS (and images)

### ISSUE THREAD

**Issue by mathiasertl** [jsxc/jsxc#369]
We have been (finally) experimenting with providing a JSXC installation on https://jabber.at. In its current state, JSXC is unsuitable for us at least because of its use of inline CSS (and to a lesser extend, inline images). We use a CSP header and I definitely don't want to disable that header for a webchat, the one place were there is actually use-generated input and users might suffer from XSS attacks.

 Looking through the issues, there seem to be some issues related to CSP and owncloud already. But I cannot find any ongoing effort to remove inline CSS. Is there anything of the sort planned?

**Comment by sualko** [comment]
> Is there anything of the sort planned?

No, because inline css is required e.g. to center a modal or resize the chat window. I also see, beside some very special css injection attacks, no real security in removing inline styles. But I am open for discussions.

**Comment by mathiasertl** [comment]
Why exactly is this necessary? Note that you can still resize height/width of elements using javascript, e.g. with jQuery:

```
$("select").height("300px");
```

works with CSP. As for the dangers of CSS injection, read e.g. [this](http://stackoverflow.com/questions/718611/css-injection-whats-the-worst-that-can-happen) Stackoverflow ticket.

**Comment by sualko** [comment]
Awesome! I always thought that a csp without ``style: unsafe-inline`` would block all style attributes even those attached with e.g. jQuery (what ``$.height`` actually does), but that's not the case :flushed:. As style attributes are only rarely used it should be no big deal to remove/replace them. Maybe I can also get this in 3.0.1.

As a side note: Very interesting stackoverflow link. I was only aware about some crazy animation css hijacking stuff.

**Comment by mathiasertl** [comment]
@sualko Since we have a site that uses a super-strict CSP header: tell me what jquery functions you want tested and I'll draw up a test page. I did test this myself with `$.height`, but that way we can be (more) sure...

**Comment by sualko** [comment]
Thanks for the offer. I ran some tests by myself and it looks like like that dom changes are not blocked, but you can test this further with ``$.css`` if you like.
