### ISSUE TITLE
login only from /settings/personal

### ISSUE THREAD

**Issue by v10star** [jsxc/jsxc#370]
Hi, 
i'm total new to owncloud & jsxc.
I've setup a new vm on ubuntu 16.10 with lamp package, owncloud 9 latest build with jsxc plugin and  basic configuration with domain & url bosh, successfully tested with another ubuntu 16.10 vm with ejabberd 16.08.
Dns name of owncloud & ejab vm are managed with local split-horizon' dns running on win12 host, but i don't think the problem is related to this, in fact i have the login problem im internal and external scope.
Atm, i've created OC users with same credentials of ejab but i can't login: i can bypass with "no chat access". If i try to login after, from main page, i'm getting "connecting...." but no access to ejab server. In ejab accesslog no connection were  established: only if i go to user personal settings i can login and chat with other contacts.

for me, this is strange. If there is a solution i will be appreciate

thanks
##

**Comment by MarcelWaldvogel** [comment]
Does the Apache you use for OC proxy BOSH to the ejabberd? (See CORS instructions)

**Comment by v10star** [comment]
url config says to me pass; i've followed this istructions at https://github.com/jsxc/jsxc/wiki/Prepare-apache, verified if ejab 16 need additional setups for cors but apparently not and i still have the same problem.

in the OC log i saw this line after evey failed logim:

Error 	PHP 	Invalid argument supplied for foreach() at /var/www/owncloud/apps/ojsxc/ajax/getSettings.php#53

**Comment by v10star** [comment]
damn! with IE works straighfully! The problem is only with Firefox that bring to php error reported before

**Comment by MarcelWaldvogel** [comment]
I can't help you right now; we probably need @sualko's expertise, who
is away for the next two weeks. Can you wait that
long?##SELECTION_END##

**Comment by sualko** [comment]
Can you send me some test credentials to klaus@jsxc.org? Would be the easiest option to debug your issue.

**Comment by v10star** [comment]
i'm gonna provide to you asap, thanks

**Comment by v10star** [comment]
sent! 👍

**Comment by sualko** [comment]
fixed via mail.
