### ISSUE TITLE
version in  bower.json is not updated

### ISSUE THREAD

**Issue by pravi** [jsxc/jsxc#371]
it is still 3.0.0-beta1. Please update it so rails-assets.org will get it too.
##

**Comment by pravi** [comment]
https://rails-assets.org/#/components/jsxc shows latest available version as 2.0.1 only.

**Comment by sualko** [comment]
I updated [bower.json](https://github.com/jsxc/jsxc/blob/master/bower.json#L3) accordingly. Does this fix your issue?
