### ISSUE TITLE
WIKI is outdated

### ISSUE THREAD

**Issue by enoch85** [jsxc/jsxc#373]
The instructions in the Wiki isn't working for Ubuntu 16.04.1. 

Does anyone have updated instructions?

**Comment by MarcelWaldvogel** [comment]
Which part are you having trouble with?

**Comment by enoch85** [comment]
I changed it, it was the config.cfg, it's config.yml instead.

But I can't get it to work, followed the instructions and I get this in Ubuntu 16.04.1:

```
Sep 29 16:37:39 nextcloud audit[61669]: AVC apparmor="DENIED" operation="exec" profile="/usr/sbin/ejabberdctl" name="/etc/ejabberd/auth_ejabberd_oc.php" pid=61669 comm="sh" requested_mask="x" denied_mask="x" fsuid
Sep 29 16:37:39 nextcloud audit[61670]: AVC apparmor="DENIED" operation="exec" profile="/usr/sbin/ejabberdctl" name="/etc/ejabberd/auth_ejabberd_oc.php" pid=61670 comm="sh" requested_mask="x" denied_mask="x" fsuid
Sep 29 16:37:39 nextcloud audit[61671]: AVC apparmor="DENIED" operation="exec" profile="/usr/sbin/ejabberdctl" name="/etc/ejabberd/auth_ejabberd_oc.php" pid=61671 comm="sh" requested_mask="x" denied_mask="x" fsuid
Sep 29 16:37:39 nextcloud audit[61672]: AVC apparmor="DENIED" operation="exec" profile="/usr/sbin/ejabberdctl" name="/etc/ejabberd/auth_ejabberd_oc.php" pid=61672 comm="sh" requested_mask="x" denied_mask="x" fsuid
```

**Comment by sualko** [comment]
cfg or yml is not related to your used ejabberd version and not os version. I will update the wiki accordingly in the next days, but thank you for mentioning this. See also https://blog.process-one.net/switch-ejabberd-configuration-to-yaml/ for further information.

Please check your file permissions and test it with ``su ejabberd -c /etc/ejabberd/auth_ejabberd_oc.php``.

**Comment by enoch85** [comment]
I ditched it and have no testing rig setup anymore. But IIRC there where no issues with that command, it showed me nothing (=it worked).
