### ISSUE TITLE
preventing jsxc from loading in one specific window (SOGO)

### ISSUE THREAD

**Issue by FrancisVenturini** [jsxc/jsxc#375]
Hi, 
how can I control jsxc in one specific window?  For example, in windows with class "popup" I would like to prevent jsxc from loading. Can you give me a tip on where is the code to change that?

Thank you

**Comment by sualko** [comment]
I do it like this: https://github.com/jsxc/jsxc.sogo/blob/master/js/sjsxc.js#L106

If this fixes your issue, please close it.
