### ISSUE TITLE
different username than the one from owncloud

### ISSUE THREAD

**Issue by tristan-k** [jsxc/jsxc#376]
Is it possible to login with a different username than the one from owncloud?

For example: My JID is  `mail@domain.tld` but my owncloud username is `domain`. Right now I'm unable to login with the username `domain`, the only way I could use jsxc is to create a new owncloud user with the username `domain` and migrate all my data OR create a new JID which matches the username from owncloud. It's pretty inflexible this way.
##

**Comment by MarcelWaldvogel** [comment]
There are two options:

1. System-wide: If the email addresses of the users match the JIDs, the admin can enable "Prefer mail address to loginName@xmppDomain"
2. Per user: In the hamburger menu at the bottom of the JSXC Roster, there is a "Settings" entry. Unless the admin has forbidden user overrides, each user can change their JSXC parameters there, including username.

**Comment by tristan-k** [comment]
This is not available in my v3.0.0 release.

**Comment by MarcelWaldvogel** [comment]
Oh, indeed, that has not yet made it into the public release. You can find the pull request in owncloud/jsxc.chat#26 (no need to rebuild the entire sources, just apply the patch)

@sualko Please merge the PR

**Comment by tristan-k** [comment]
Thanks. That worked.
