### ISSUE TITLE
OJSXC not working

### ISSUE THREAD

**Issue by gzdncs** [jsxc/jsxc#378]
I have a functional openfire server with bosh enabled (tested with converse.js).
When I log into Owncloud I don't see the chat icon and the chat doesn't work.
When I click "Log in without chat" I see this:
Firefox
http://i1268.photobucket.com/albums/jj577/gzdncs1/Workspace%201_003_zpshmv7m2h6.png
Chromium
http://i1268.photobucket.com/albums/jj577/gzdncs1/Workspace%201_005_zpsgrngi59z.png
I tried some things like changing the server and it doesn't matter if I use internal or external, it won't work.
I know the server configuration is ok because I receive the message "BOSH Server reachable." and sometimes the chat works.
When it works and I logout of Owncloud/Nextcloud I can still use the chat but I couldn't take a screenshot of that.
I was using owncloud 8, then I moved to owncloud 9, then I moved to Nextcloud. (Always the same behavior)
I use debian 8
I am using apache2, mysql.
I installed ojsxc by downloading the compressed file and via "+ Apps".
I think this could be a configuration problem but I see the same behavior with XAMPP in a different debian.
Nextcloud log:
http://i1268.photobucket.com/albums/jj577/gzdncs1/Workspace%201_006_zpselb32yo0.png

**Comment by sualko** [comment]
Mh strange behaviour, because I am unable to reproduce your issue. Can you add a debug message in line 745?

```
console.log('loginForm.form 2',  jsxc.options.loginForm.form);
var form = jsxc.options.loginForm.form.off('submit');
```

And maybe in line 330:
```
var submits = [];
console.log('loginForm.form 1',  jsxc.options.loginForm.form);
```

An easy fix would be to change line 745 to the following, but that should not be necessary and points to an another, maybe bigger, issue.

**Comment by gzdncs** [comment]
I made some changes and I had no luck:
I added this in line 330:
`         var submits = [];
         alert("loginForm.form 1 before log");
         console.log('loginForm.form 1',  jsxc.options.loginForm.form);
         alert("loginForm.form 1 after log");`

and I didn't get not even the alerts.

And in line 745:
`      alert("loginForm.form 2 1");
      console.log('loginForm.form 2',  jsxc.options.loginForm.form);
      alert("loginForm.form 2 2");
      var form = jsxc.options.loginForm.form.off('submit');`
I get the alerts and the log is:
`#body-login form`

I will try to find more info.

**Comment by sualko** [comment]
> I didn't understand: 

:laughing: I forgot the corresponding line of code.

```
var form = $(jsxc.options.loginForm.form).off('submit');
```
Can you add a ``console.trace('loginForm.form');`` before that line and post the complete output?

**Comment by sualko** [comment]
Sorry, no need to post the output from ``console.trace``, because I read over that you are facing this issue with the "login without chat" link. It should be enough to change line 745.

**Comment by sualko** [comment]
I could completely reproduce your issue. After executing ``jsxc.storage.removeItem('sid')`` you should see the chat icon again, but I will work on a more complete fix.

**Comment by gzdncs** [comment]
After working a lot on this, I guess the problems are caused due to several users within the same browser.
`jsxc.storage.removeItem('sid')` fixed the problems.
The best thing to do is avoid more than one user in one browser, otherwise there will be several, several problems.
Thanks a lot man.

**Comment by sualko** [comment]
Please test the latest [beta release](Maybe we can include this in the v3.0.1 beta?), because it fixes your issue which is caused by some other fixed logout issues.

>  I guess the problems are caused due to several users within the same browser.

Multiple users are supported, but not simultaneously.

**Comment by gzdncs** [comment]
I will try this:
https://github.com/owncloud/jsxc.chat/tree/master/build
and let you know.
Thanks!

**Comment by gzdncs** [comment]
I uploaded a 20 minute video with all the steps I followed, please let me know if this can help us.
https://www.youtube.com/watch?v=Elq61urmlDY
Thanks man!

**Comment by sualko** [comment]
> Should I close this and open a new issue?

Yes, please open another issue.

> I uploaded a 20 minute video

Great work. Thank you. I will check it and add it to the next release announcement.
