### ISSUE TITLE
Once enabled jsxc - no links or buttons work

### ISSUE THREAD

**Issue by zh85** [jsxc/jsxc#380]
I am new to owncloud and all so bare with me if I missed something.  I have a working version of owncloud 9.1.1, on apache 2.4.18 on xubuntu 16.04.  I am using ojsxc 3.0.0.  I have installed a few different apps with no issues but when I install jsxc all links and images become useless, I suppose a javascript issue?  Once installed login no longer works, nothing.  Basically stuck on the page I was last on or at login screen as those do not work either.  I have tried it on both Firefox and Chrome (both latest versions), tried on windows 10, linux mint, ubuntu.

Only thing I am doing that is different then normal owncloud install is the fail2ban mod.  What could cause this?  I have no idea where to look and searching online has not showed anyone with similar issues.  Any thoughts?

Consol in chrome shows this...
<Uncaught SyntaxError: Unexpected identifier>
##

**Comment by zh85** [comment]
`Uncaught SyntaxError: Unexpected identifier`

**Comment by sualko** [comment]
I need to know the line number which triggers this error, but we had similar issues which should be solved in the next bug fix release. It would great if you could test it and report back if it is working for you.

https://github.com/owncloud/jsxc.chat/releases/tag/v3.0.1-beta1

**Comment by sualko** [comment]
Any update?

**Comment by zh85** [comment]
I just turned it off for the time being, I haven't had time to mess with it much.  Sorry.  I will try to get around to updating it to the beta today or tomorrow.

**Comment by sualko** [comment]
If there is an update, please reopen this issue.
