### ISSUE TITLE
Obey navigator.languages?

### ISSUE THREAD

**Issue by ChristianTacke** [jsxc/jsxc#381]
Hi,

I am using 3.0.0 with chromium on Linux.

jsxc is talking english, although I have german preferred.
I noticed:
* navigator.languages = ["de-DE", "de", "en-US", "en"]
* navigator.language = "en-US"

I don't know exactly, why this difference is there.
Anyway: What about checking the languages list also in jsxc?

**Comment by sualko** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) marks ``navigator.languages`` as experimental technology and says: "the value of navigator.language is the first element of the returned array". So no need to use this in jsxc from my pov.

In your case you are probably using an English UI, which Chrome [reflects](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) in his ``navigator.language`` property.

You can force German with the following command (executed in your javascript console):

```
jsxc.storage.setItem('lang', 'de')
```

**Comment by ChristianTacke** [comment]
Well, *I can* execute that in a javascript console, but a normal user probably can't.
So what will a normal user do?

**Comment by sualko** [comment]
You are probably right. It is a small change, should also work for firefox or ie users and increases usability.

**Comment by ChristianTacke** [comment]
Another option would be to have an entry in Settings for the user to choose the language. I can't say, what is better.

**Comment by sualko** [comment]
Please check and verify.

**Comment by ChristianTacke** [comment]
The diff looks good to me (I am not a js developer though). Maybe add a small comment about it being an experimental thing in browsers?

I will test this when the next (beta) release .zip is online (because that's the simplest way on my deployment tooling).

**Comment by sualko** [comment]
Next beta release is out. Happy testing.

**Comment by ChristianTacke** [comment]
Yeah, just updated to 3.0.1-beta2.
Works! Great!
