### ISSUE TITLE
Internal chat not working on Windows 10 (64bit)

### ISSUE THREAD

**Issue by ungesundes-halbwissen** [jsxc/jsxc#382]
I have a Nextcloud 10 (beta) instance running with 
JavaScript XMPP Chat 3.0.0 installed. Being on shared hosting I run the internal chat.

As long as I open NC on Windows 7 machines, all works flawlessly. but opening NC on my Windows 10 box results in the Chat app not being opened. Operating as Administrator or regular user does not make any difference.

As both PCs are on the same network I suspect it being a problem with Windows 10 as it is the only difference I can spot. But how on earth that might be is beyond me :-(

If you need any output logs please let me know in detail, where to acquire them :-)

John
##

**Comment by sualko** [comment]
Please test our latest [beta release](https://github.com/owncloud/jsxc.chat/releases/tag/v3.0.1-beta2) and report possible errors from your JavaScript console.

**Comment by MarcelWaldvogel** [comment]
What browsers are you using on the two boxes##SELECTION_END##?

**Comment by ungesundes-halbwissen** [comment]
Thanks for taking the time to reply to both of you. I run the latest Firefox on both PC's. I'll try these beta tomorrow and report back afterwards. Please allow 20 hours to reply.

John

**Comment by ungesundes-halbwissen** [comment]
Hi again,

got it working now. I have installed the recommended beta but I guess, the main problem was in front of the screen once more...

For what it's worth: please consider to make the username not case-sensitive.

The problem was, that I registered user "john" in Nextcloud but did not pay attention when logging in. Nextcloud accepts logging as "John" (note the capital J) but the chat app seems to struggle with the differing spelling (as one might expect with *ix systems)
Nonetheless it remains a bit awkward that the basic system disregards case-sensitivity while a module does not.

Long story cut short: problem solved, but please consider to add some non-unix-style-consistency here (I did my best not to write about fixing a bug, as you will have noticed ;-))

John

**Comment by sualko** [comment]
@LEDfan Can you make the username not case-sensitive?

**Comment by LEDfan** [comment]
Thanks @ungesundes-halbwissen for finding this issue :)

@sualko I'll fix this. I hope to do it tonight :)
