### ISSUE TITLE
Room_creation change is not working

### ISSUE THREAD

**Issue by devendrawebdeveloper** [jsxc/jsxc#383]
Hello,

I am using new beta but some things are not working.

Room_creation change the default room configuration change button are not working.
![jsxcerror](https://cloud.githubusercontent.com/assets/4918366/19426869/97080d88-945d-11e6-9eac-bc5316c37ec9.png)

Also if i entered password when creating room after that join room with other user and insert any password.they are able to join room with any password not same as room admin password.

**Comment by MarcelWaldvogel** [comment]
Prosody does not honor the password on room creation. This is a known problem. We might consider including a workaround, even though it is ugly.

**Comment by devendrawebdeveloper** [comment]
So we can not create private room or password protected room?

**Comment by MarcelWaldvogel** [comment]
Sure. Create it first "normal" and then change the properties.

**Comment by devendrawebdeveloper** [comment]
I am trying to change  the properties, it gives above image error.

**Comment by sualko** [comment]
Please provide steps to reproduce your error. Which xmpp server do you use? Do you find any errors in your xmpp server log? Please post the payload of the request (including answer) which triggered this error.

**Comment by devendrawebdeveloper** [comment]
Hello,
I am using openfire 4.0.2,
Please find attachment.
![openfire admin console log viewer 2016-10-17 19-13-48](https://cloud.githubusercontent.com/assets/4918366/19440070/1b381ec8-949e-11e6-9bd7-fa0084115ca1.png)

Room is created successfully after join, they provide option for select button "Default " and "change" 
When i click on change nothing happened,or click on default then give error.

**Comment by sualko** [comment]
This error message is related to an openfire plugin called ``clustering`` and I am unsure how this could be related to jsxc. I am no openfire expert and I have no time to fix your infrastructure. Please test with a different xmpp client and make sure that your xmpp server is running properly.
