### ISSUE TITLE
OJSXC not working after re log in or when surfing within owncloud.

### ISSUE THREAD

**Issue by gzdncs** [jsxc/jsxc#384]
I installed the latest beta version of OJSXC from https://github.com/owncloud/jsxc.chat/tree/master/build
After logiing out of Nextcloud or when I go to "Users" or to "Admin" the chat icon disappears. The only thig that makes the chat come back is to log out ang log in using the "Log in without chat" option.

I have the same behavior in all versions of OJSXC the difference I found is that I can log in with the beta version. Previous versions don't allow me to log in using "Log in without chat" and I have to execute `jsxc.storage.removeItem('sid');` in the console and then I can log in.

You can watch this behavior in this one and a half minute video:
https://youtu.be/Fp_VcS-rNVA
The complete video of that installation is here (20 min aprox.):
https://youtu.be/Elq61urmlDY
##

**Comment by sualko** [comment]
Do you have the notifications app enabled? Try to disable it. If this doesn't help, please post the output from ``sudo -u www-data ./occ app:list`` and your js console.

**Comment by gzdncs** [comment]
Thanks a lot for your answer.
Saddly, it didn't work. I found out that my `root` user was the owner of the ojsxc app so I changed it to www-data and its group also. Then I tried to restart apache, my computer and everything but it didn't work. This is the output of that command now:
![workspace 1_020](https://cloud.githubusercontent.com/assets/20095783/19562054/e396c818-96a8-11e6-8d92-93b2b9056000.png)
I am attaching the output of my console when I click on the "Log in" arrow:
[OJSXC Log.txt](https://github.com/jsxc/jsxc/files/541817/OJSXC.Log.txt)
I am using Firefox because chromium ahows almost no logs.
I managed to stop the loading and found this logs with firebug:
![workspace 1_021](https://cloud.githubusercontent.com/assets/20095783/19562452/60d723da-96aa-11e6-9f93-6c89974d6dee.png)
I don't know what I am missing but let me know if I can do something else.
Bests!

**Comment by sualko** [comment]
Following my list of enabled applications, maybe you can try to enable just these and check if it is working:

```
Enabled:
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_sharing: 1.1.0
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - notifications: 0.3.0
  - ojsxc: 3.0.1-beta2
  - provisioning_api: 1.1.0
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```

You could also enable debugging for jsxc and see if you get any helpful information: https://github.com/jsxc/jsxc/wiki/Debugging

**Comment by tedd77** [comment]
Hello,

I have a on my installed nextcloud 10.0.1

The system configuration is : 

1. Nextcloud 10.0.1
2. OpenLDAP
3. Openfire
4. OJSXC version 3.0.1 official not beta

Should I use the internal Chat everything work fine.
Should I enable the Bosh server I sometimes can login but only once and then no way to login again with same user.
I can login with chat disabled at any time.
There is no way that chat can accept user and password.

On openfire I can see every change I make for a user from LDAP phpldapadmin.
I suspect that OJSXC still has a bug somewhere.

**Comment by gzdncs** [comment]
I disabled everything, tried enabling almost the same apps. Nothing worked, I will try to debug but I don't know how :D Thanks a lot anyway.
Please let me know if I can give you my private address and maybe you can help me somehow.
I will be working on it.
Thanks!

**Comment by sualko** [comment]
@gzdncs Can you test the latest build?

**Comment by sualko** [comment]
I could probably reproduce your issue on the installation from @tedd77. Please open your js console and execute `jsxc.log`. Does it show something like "xmpp.url required for login"?

**Comment by gzdncs** [comment]
Working on it as we speak. Thanks!

**Comment by gzdncs** [comment]
Yes, you are right!
It doesn't work yet but I receive that message.
![screenshot_2016-11-04_08-57-17](https://cloud.githubusercontent.com/assets/20095783/20006183/d320c8b0-a26c-11e6-9137-b9ecd4456168.png)
Thanks man!

**Comment by sualko** [comment]
Please check if your xmpp domain in the admin settings has no spaces before or after.

**Comment by gzdncs** [comment]
I verified it and it doesn't have spaces.
![screenshot_2016-11-04_09-09-02](https://cloud.githubusercontent.com/assets/20095783/20006554/6783f8a0-a26e-11e6-91f7-136c5b85b2e4.png)
Please remember that if I "Log in without chat" I see the chat icon and I can connect it.
![screenshot_2016-11-04_09-11-16](https://cloud.githubusercontent.com/assets/20095783/20006591/a2a042cc-a26e-11e6-881b-ef9490540134.png)

**Comment by sualko** [comment]
I mean in your owncloud/nextcloud settings. Sorry for this confusion.

**Comment by gzdncs** [comment]
lol, no worries and no spaces:
![screenshot_2016-11-04_09-16-26](https://cloud.githubusercontent.com/assets/20095783/20006775/7ba97070-a26f-11e6-912f-16ea7ce6e216.png)

**Comment by sualko** [comment]
Closed? By purpose?

Can you take a screenshot of your localStorage after unsuccessful login? You find it your developer tools (ctrl+shift+i) under Application/Storage.

**Comment by sualko** [comment]
One more point: Why do you use "localhost" as your xmpp domain in the admin settings, when you set it to "virtualmin" in your openfire settings?

**Comment by gzdncs** [comment]
Great catch, trying both things now.
To change localhost to virtualmin didn't work.
Didn't mean to close it.

**Comment by gzdncs** [comment]
![screenshot_2016-11-04_09-29-10](https://cloud.githubusercontent.com/assets/20095783/20007109/268f2b78-a271-11e6-8773-17da15eaee6c.png)

**Comment by gzdncs** [comment]
Last line didn't show up in the previous image.
![screenshot_2016-11-04_09-31-31](https://cloud.githubusercontent.com/assets/20095783/20007188/8481d2c6-a271-11e6-97cf-dfcdc0494e11.png)

**Comment by sualko** [comment]
Probably a typo. I see an entry for the domain "vitualmin". Please check your oc/nc admin settings once again :laughing:.

**Comment by gzdncs** [comment]
Indeed, I changed localhost to virtualmin and left it with virtualmin.

**Comment by gzdncs** [comment]
Should I change it back?

**Comment by sualko** [comment]
Execute `localStorage.clear()` in your console and make a screenshot after a oc login.

**Comment by gzdncs** [comment]
Here it is:
![screenshot_2016-11-04_10-56-15](https://cloud.githubusercontent.com/assets/20095783/20010110/56bac9ea-a27d-11e6-98e6-854f128495d0.png)
The content of the long line is:
{"xmpp":{"url":"/http-bind/","jid":null,"domain":"vitualmin","password":null,"sid":null,"rid":null,"overwrite":false,"onlogin":true,"resource":"","username":"admin"},"serverType":{"0":"e","1":"x","2":"t","3":"e","4":"r","5":"n","6":"a","7":"l"},"loginForm":{"enable":true,"jid":"#user","pass":"#password","onConnecting":"quiet","onConnected":"submit","onAuthFail":"submit","attachIfFound":true,"ifFound":"force","startMinimized":false}}

**Comment by sualko** [comment]
As I said: You probably have a typo in your XMPP domain somewhere. The first cell says `jsxc:admin@virtualmin:options` and the second `jsxc:admin@vi_tualmin:options`.

**Comment by gzdncs** [comment]
I will verify this in all my environments.
In case this is happening everywhere, what should I do?
Thanks a lot!
Awesome catch!

**Comment by gzdncs** [comment]
I changed all of them and now I am using the same name of the XMPP server and everything is working smoothly.
Thanks a lot my friend, for your time and patience with this noob.
