### ISSUE TITLE
JSXC uses an old lib of i18next

### ISSUE THREAD

**Issue by mmoqui** [jsxc/jsxc#385]
Currently jsxc uses the version 1.7.7 of i18next. This version of i18next defines the i18n variable that is attached to $ and this is in conflict with other JQuery i18n libraries (like jquery i18n properties which is used by our application).

It should be nice either to update the i18next dependency to its latest version (in which it defines I18n (and no more i18n)) or to attach i18n to the jsxc context.
##

**Comment by sualko** [comment]
> attach i18n to the jsxc context

Do you have an idea how to do this?

> update the i18next dependency to its latest version

We should definitely do this, but this will not go into the next prepared release.

**Comment by mmoqui** [comment]
An idea is to use AMD for doing: jsxc.i18n = require('i18n'); (for example)
There is an AMD variant of i18next but I don't know the importance of the work.

**Comment by mmoqui** [comment]
Thanks for your work. Pretty done.
