### ISSUE TITLE
Question: Which event fires after everything is loaded/connected/idle?

### ISSUE THREAD

**Issue by ChristianTacke** [jsxc/jsxc#388]
Version: 3.0.1-beta2
Variant: standalone

It wasn't obvious to me, which event is fired after everything is loaded, connected, etc. That is: If this event fires, jsxc is idle and only waits for the user. It does not wait for the network or anything else. This event should only fire once on page load.
##

**Comment by sualko** [comment]
There is currently no such event, but you can use ``cloaded.roster.jsxc``. It fires after the roster is loaded, but before all windows are restored. There is also ``restoreCompleted.jsxc``, but this event is not fired if the connection is established for the first time. Maybe we should add such an event in the refactoring process of v4.

**Comment by ChristianTacke** [comment]
Is `cloaded.roster.jsxc` also fired if jsxc did not even try to connect to a server (for example, because I am using `jsxc.gui.showLoginBox`).

**Comment by sualko** [comment]
No. It is only fired, if the roster was loaded. But feel free to open a pull request which adds such an event.

**Comment by sualko** [comment]
JSXC has now two new events: `stateChange.jsxc` and `stateUIChange.jsxc`. 

Hopefully there is a [state](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.js#L88) which satisfies you :laughing:.
