### ISSUE TITLE
Function to cleanup all cookies/storage?

### ISSUE THREAD

**Issue by ChristianTacke** [jsxc/jsxc#389]
Version: 3.0.1-beta2
Variant: standalone

Is there a function to cleanup all the cookies and (local)storage?
For example when using jsxc on a public computer, you don't want to leave your last messages behind for the next user…

**Comment by MarcelWaldvogel** [comment]
Most browsers have a "clear recent history" option, which does this and more for all the sites and apps that you may have been using.

**Comment by ChristianTacke** [comment]
@MarcelWaldvogel Thanks for the heads up! I was too focused on solving this locally, that I forgot about more general points.

In my case a `localStorage.clear()` at the right point helped.
