### ISSUE TITLE
SOGO v3 Beta Send File not working

### ISSUE THREAD

**Issue by lookingdown** [jsxc/jsxc#392]
Is running jsxc on SOGO v3 w. nginx and prosody.. send file not working "Send File" link in menu is inactive and has a line over it..  Tried with Chrome 2 Chrome / Chrome 2 IE,  etc.. 
All other clients handles Send file / File transfer fine.. connected to prosody..
Is it something that I am missing (required extra config ?) or is it simply not working on SOGO.. ?
Thanks for a great application..
Cheers
Johan 
##

**Comment by sualko** [comment]
There are multiple ways to transfer files in xmpp and both clients have to support the same xep to actually send/receive a file. Which was your peer client?
