### ISSUE TITLE
MUC: OTR white space tags?

### ISSUE THREAD

**Issue by ChristianTacke** [jsxc/jsxc#394]
Version 3.0.1-beta2/standalone

MUCs do not support OTR (yet?).
But jsxc sends the trailing whitespace tags in MUCs.
Many other clients actually display that whitespace at the end. It's enough whitespace to trigger a linebreak.
Confirmed by setting `otr: { SEND_WHITESPACE_TAG: false }`

**Comment by sualko** [comment]
> MUCs do not support OTR (yet?).

That's right and therefore a bug in jsxc. I will fix it asap.
