### ISSUE TITLE
Faild during the start

### ISSUE THREAD

**Issue by perldev** [jsxc/jsxc#395]
VM352 jsxc.js:721
jidToBid: function(jid) {
      return Strophe.unescapeNode(Strophe.getBareJidFromJid(jid).toLowerCase());
   },

   /**
##

**Comment by sualko** [comment]
Sorry, but this is a cheek. If you want help, you have to provide at least the information requested in our [contributor guide](https://github.com/jsxc/jsxc/blob/master/CONTRIBUTING.md).
