### ISSUE TITLE
With the release 3.0.1 some issues not resolved

### ISSUE THREAD

**Issue by tedd77** [jsxc/jsxc#396]
Hello,
Beta2 with owncloud + LDAP + Openfire was working fairly fine with some exceptions.
Release 3.0.1 is not working with Nextcloud, openfire, and LDAP.
I was able to login once and that was it.
In order to login to nextcloud I have to select without chat enabled else I cannot access to Nextcloud (this is similar to the behavior of version 3.0.0)
Once logged in (with chat disabled) if I try to login from within Nextcloud to the chat server also fails (endless waiting).

Could you please advise how to overcome this situation ?

**Comment by ChristianTacke** [comment]
(I am not a maintainer, just having some random thoughts)

- Could you note, what browser you are using? Is it different on another browser?
- On Firefox and Chromium, you can open the Console using Ctrl-Shift-I and clicking on "Console". Are there any interesting errors visible there maybe?

**Comment by tedd77** [comment]
@ChristianTacke 
Thank you for your message

yes there is an error 

Should I try to access my site with https:
JQMIGRATE: Migrate is installed, version 1.4.0
POST https://192.168.xx.xx/http-bind/ 403 (Forbidden)sendFunc @ jsxc.dep.js?v=bc1faa0…:4813_processRequest @ jsxc.dep.js?v=bc1faa0…:4825_throttledRequestHandler @ jsxc.dep.js?v=bc1faa0…:4977_onIdle @ jsxc.dep.js?v=bc1faa0…:4603_onIdle @ jsxc.dep.js?v=bc1faa0…:3669

With http:

JQMIGRATE: Migrate is installed, version 1.4.0
login:118 GET http://192.168.xx.xx/core/img/loading-dark.gif 404 (Not Found)
loading-dark.gif:1 GET http://192.168.xx.xx/core/img/loading-dark.gif 404 (Not Found)
jsxc.dep.js?v=bc1faa0…:4813 POST http://192.168.xx.xx/http-bind/ 403 (Forbidden)sendFunc @ jsxc.dep.js?v=bc1faa0…:4813_processRequest @ jsxc.dep.js?v=bc1faa0…:4825_throttledRequestHandler @ jsxc.dep.js?v=bc1faa0…:4977_onIdle @ jsxc.dep.js?v=bc1faa0…:4603_onIdle @ jsxc.dep.js?v=bc1faa0…:3669


should I directly type   http://myipaddress/http-bind/ or https://,yipaddress/http-bind/

no errors are found in console.

Hope the above with trigger a solution. once again thank you.

**Comment by tedd77** [comment]
Update:

I was able to have one user works, not sure how but I did execute the following command in the Chrome console : jsxc.storage.removeItem('sid');

in my example : the user is called user22 , and myhost ip is in the range of 192.168.xxx.xxx
I can see the tchat windows and the list of users 1 login over 3 times .
Most of the times when I login I do not see the tchat, a page refresh does not solve it.
Then if I do the following command in the console : jsxc.storage.removeItem('sid');
the refresh will display the tchat icon but not logged in. Despite that now I can type my user and password and it works normally.

Should I try to login with same user and password from somewhere else different ip , I get the following error in the working session's console :  POST https://192.168.xx.xx/http-bind/ 403 (Forbidden)
At this stage in both sessions the tchat is in logout mode.
No way that I could make the login successful with the other ip terminal , and in the primary working ip a simple logout and login will fix the tchat session.
I could reproduce this 2 times only. 

On the same browser Chrome and same ip, trying to use another username will fail. to make it work first need to login to nextcloud with chat disabled then execute the following command : jsxc.storage.removeItem('sid');
a login to tchat will now work.
I tried all my users on the same chrome page they all work in the following manner;
1. Login without chat
2.  once logged in , login to chat with same user and password.

Only for one user I can sometimes login and get the chat working without furthers steps to do.
The login takes much longer than that without chat which is very fast. but again it bugs 1 over 3 times no chat icon.
So for this I adopted the 2 stage login, 1st without chat and second login to chat from within Nextcloud.

I tried with another user from another subnet ip, surely always with the command jsxc.storage.removeItem('sid'); being executed I could see for 2 seconds that user went online then immediately in the console the famous message 403 forbidden and after that no way that I could have that user login to tchat.

I hope my experiment will help the developer to enhance and provide a solution or even tell me what am I doing wrong?

**Comment by sualko** [comment]
I am unable to reproduce your issue on my development and production server. There are a few things you should consider and test:

- Don't try to login multiple users simultaneously in one browser (even if spread across multiple tabs)
- What is the value of `jsxc.storage.removeItem('sid')`?
- Is `jsxc.version === "3.0.1"`?
- Try to clear your complete local storage (`localStorage.clear()`).
- Check your openfire log.
- Enable [jsxc debugging](https://github.com/jsxc/jsxc/wiki/Debugging).

Maybe related to #384.

**Comment by tedd77** [comment]
@sualko 

Thank you for your reply and efforts.

Q. Don't try to login multiple users simultaneously in one browser (even if spread across multiple tabs)
A. I am not doing that, I was using different browsers (one session per browser), now I am using different computers one per user. but still exact same error.

Q, What is the value of jsxc.storage.removeItem('sid')?
A. When i execute the command jsxc.storage.removeItem('sid'); I get undefined

Q.    Is jsxc.version === "3.0.1"? 
A. Yes

Q.    Try to clear your complete local storage (localStorage.clear()).
A.  I did , the effect is the same as the removeitem and the command output is also undefined.

Q.     Check your openfire log.
A.      Do not know what to check

Q.    Enable jsxc debugging.
A.    How ?

**Comment by sualko** [comment]
> When i execute the command jsxc.storage.removeItem('sid'); I get undefined

Sorry, c+p error. Should be `jsxc.storage.getItem('sid')`. Call it before you remove the item.

> Do not know what to check

Your xmpp server log.

If your test installation is reachable through the internet, you could send me credentials for two test accounts to klaus@jsxc.org.

**Comment by tedd77** [comment]
@sualko 

Q. jsxc.storage.getItem('sid'). Call it before you remove the item.
A. null

XMPP server log 
Error.log and debug.log there is nothing about today's activities

info log
2016.11.03 22:25:01 org.jivesoftware.openfire.http.HttpSessionManager - Closing idle session: client11@nextcloud101/nextcloud

**Comment by sualko** [comment]
Ok we figured out, why we got the 403. It was the evasive apache module.
