### ISSUE TITLE
BOSH connectivity problem (OC+OpenFire+Apache)

### ISSUE THREAD

**Issue by adeel109** [jsxc/jsxc#397]
I really like the feature and wanted it available in my production server.

so I made a test owncloud and XMPP chat servers prior putting it to my production.

---------------------------------------------
**Server1**: 192.168.5.30 owncloud 9.0.4 on NGINX
**Server2:** 192.168.5.31 Openfire XMPP + Apache
---------------------------------------------
Enabled JavaScript Xmpp Client plugin in OC
I have enabled BOSH from openfire.
---------------------------------------------

when i test BOSH on browser

http://192.168.5.31:7070/
it shows
Openfire HTTP Binding Service

which means its working good.
i tested Openfire on Spark etc and works good.
----------------------------------------------

i added following in httpd.conf file on Openfire 192.168.5.31 server

<Location /http-bind>
Order allow,deny
Allow from all
</Location>
ProxyPass /http-bind/ http://192.168.5.31:5280/http-bind/
ProxyPassReverse /http-bind/ http://192.168.5.31:5280/http-bind/

I restarted httpd service
-----------------------------------------

---> Now when i try to connect from OC, it lost.

In OC - admin i gave as bellow

* XMPP domain = 192.168.5.31
* BOSH URL = /http-bind/

the rest of all fields are empty

it gives me error as bellow

BOSH server NOT reachable or misconfigured.

Your server responded with "404 Not Found". Please check if your BOSH server is running and reachable via https://192.168.5.30/http-bind/.

i have allowed following ports on BOSH server

ports: 80/tcp 5222/tcp 9090/tcp 9091/tcp 3306/tcp 7777/tcp 7070/tcp

Please let me know if anyone can give me any clue.

Thanks a lot.

**Comment by tedd77** [comment]
Hello ,

ProxyPass /http-bind/ http://192.168.5.31:7070/http-bind/
ProxyPassReverse /http-bind/ http://192.168.5.31:7070/http-bind/

Openfire bosh ports are 7070 and 7443 unless you have changed them...

**Comment by adeel109** [comment]
Hi, 
Many Thanks for reply, 
I have checked using these ports but no luck. 

any other clue if i am missing anything?

Regards

**Comment by tedd77** [comment]
well in my case I have 
ProxyPass /http-bind/ http://127.0.0.1:7070/http-bind/
ProxyPassReverse /http-bind/ http://127.0.0.1:7070/http-bind/

Working fine, at least the bosh side but the app ojsxc 3.0.1 is not yet working fine.

**Comment by sualko** [comment]
You need to add the proxy configuration to your owncloud vhost (192.168.5.30) with port 7070. For example:

```
<Location /http-bind>
Order allow,deny
Allow from all
</Location>
ProxyPass /http-bind/ http://192.168.5.31:7070/http-bind/
ProxyPassReverse /http-bind/ http://192.168.5.31:7070/http-bind/
```

**Comment by tedd77** [comment]
@sualko  could you please assist in this post ? https://github.com/jsxc/jsxc/issues/396

**Comment by sualko** [comment]
@tedd77 Please don't mess up other issues. I will answer your issue, if I had time to test your setup.

**Comment by adeel109** [comment]
Thanks for the tip Sualko
yes i didnt gave this code in owncloud.

i am using NGINX in OC not apache and im not sure which file to add above script.
Any clue?
I have looked around, NGINX looks like would have different syntax for the above code.

**Comment by sualko** [comment]
Check out our very cool [wiki](https://github.com/jsxc/jsxc/wiki) :smirk:.

**Comment by adeel109** [comment]
Thanks for the wiki tip
Sorry Sualko, when I put following script in OC .conf file it still gives no luck. 

[root@cloud ~]# vim /etc/nginx/conf.d/virtual.conf
server {
#       ...
        location /http-bind {
                proxy_pass http://192.168.5.31:7070;
                proxy_set_header Host $host;
                tcp_nodelay on;
        }
}

after doing above
**on OC portal when I put following:**
* XMPP domain = 192.168.5.30
* * BOSH url = /http-bind/

**it gives me error as bellow**
BOSH server NOT reachable or misconfigured.
Your server responded with "404 Not Found". Please check if your BOSH server is running and reachable via https://cloud.fortesecurities.co.uk/http-bind/.


**and when i put as bellow**
* XMPP domain = 192.168.5.30
* * BOSH url = /

**it gives error as bellow**
BOSH server NOT reachable or misconfigured.
Invalid XML received. Maybe https://cloud.fortesecurities.co.uk/ was redirected. You should use an absolute url.

I have allowed all following ports so there should not any block.
 ports: 5223/tcp 80/tcp 5222/tcp 9090/tcp 9091/tcp 3306/tcp 7777/tcp 7443/tcp 7070/tcp

any Idea where is the loop?

**Comment by sualko** [comment]
One question: Is `192.168.5.30` a domain, or an ip address? Because the field label says "XMPP domain".

**Comment by adeel109** [comment]
i have allocated a domain with public IP. 
so now it is as bellow
chat.arrox.co.uk = 192.168.5.31
cloud.arrox.co.uk=192.168.5.30

the problem is still there.

you can try opening if from your end if you want.

**Comment by adeel109** [comment]
i have created admin account on both servers with your name 
sualko
sualko

**Comment by sualko** [comment]
Never post credentials! Send such things via email to klaus@jsxc.org. I changed the password from the oc account, but I am unable to login into openfire.

**Comment by adeel109** [comment]
ok. i will email you

**Comment by sualko** [comment]
http://chat.arrox.co.uk:7070/http-bind/ is not reachable. Sorry, I am really willing to help you, but server administration is not easy and I can not setup everyone's environment. Please try to understand the basics of xmpp and bosh. Read some tutorials and afterwards, if you have further questions, please leave here a message.

**Comment by adeel109** [comment]
yes, i understand that, otherwise there would be million requests to setup.

i have checked, the port was blocked from firewall i have opened
