### ISSUE TITLE
Co

### ISSUE THREAD

**Issue by lambetdelta** [jsxc/jsxc#398]
### Good day, I have a small problem and ask for your help, this is what happens: When a user leaves the chat, this closes all private conversations, in doing so, to the people who had private conversations shows them the next message: "Your contact closed the private conversation you should do the same", now, if the person comes back to chat and anyone with who held a conversation will send a message, the chat does not allow it, will show the warning: "Please send your message wasnt end your private conversation," the question is: how close a user a private conversation without leaving the chat?
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38941136-co?utm_campaign=plugin&utm_content=tracker%2F728128&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F728128&utm_medium=issues&utm_source=github).

**Comment by sualko** [comment]
Please use some points in your sentence, because your issue is very hard to understand.

**Comment by lambetdelta** [comment]
I solved, my mistake to alter the code
