### ISSUE TITLE
Password prompt for Chatroom

### ISSUE THREAD

**Issue by khanhmas** [jsxc/jsxc#399]
Hello,
I am using ejabberd 16.04 as XMPP server. If a password-protected chatroom is created, the users can even join the room without entering the password.

Any helps would be appreciated. Thanks you very much.

##
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39023825-password-prompt-for-chatroom?utm_campaign=plugin&utm_content=tracker%2F728128&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F728128&utm_medium=issues&utm_source=github).

**Comment by sualko** [comment]
Did you create that room with jsxc? Did you check, if it works, if you create that room with an other xmpp client?

**Comment by khanhmas** [comment]
Yes, i created that room with JSXC (Join chat). In fact, when i click join,
i don't see any replied stanza from xmpp server.
Otherwise, when i test with jitsi-meet (another xmpp client), the server
did send some stanza responses, but it contains something like muc_public
instead of muc_passwordprotected.

**Comment by sualko** [comment]
I could reproduce your issue. I think it is not possible to create password protected instant rooms, so we have to slightly change the ui.
