### ISSUE TITLE
Integrate File Transfer

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#4]

**Comment by itJunky** [comment]
Yes, we want it!

**Comment by plberd** [comment]
I'd love that!
Specially if compatible with the way Conversations (an Android XMPP client) does them. Up until now, jsxc shows me an incoming call when Conversation users send me a file.

**Comment by sualko** [comment]
I guess Conversations use [XEP-0234](https://xmpp.org/extensions/xep-0234.html) and that is the reason why you see a file transfer as an incoming call. This should be fixed with the migration to [jingle.js](https://github.com/jsxc/jsxc/commit/efcff4f0bef8ed6282bc111041740c377250569d). 

I think we also go with XEP-0234, because jingle.js implemented it already and we "only" have to make some ui adjustments and file processing. ;-)
