### ISSUE TITLE
Patch: Improve focus for showLoginBox

### ISSUE THREAD

**Issue by ChristianTacke** [jsxc/jsxc#401]
Version: 3.0.1/standalone/Chromium

Multiple issues/improvements:
- `.focus` on Chromium works only after a small delay for newly shown elements, it seems. At least some web search suggests that and focusing for the loginbox works only with the delay
- I think, `.one` should be used instead of `.on`: The `showLoginBox` method can be called multiple times and the event only needs to be attached for that exact occassion.
- If the username is empty, it's probably nicer to focus it instead of the password.

I can't say, if something should be refactored for this?

```diff
--- jsxc.js.orig	2016-10-28 13:29:02.000000000 +0200
+++ jsxc.js	2016-11-12 11:57:43.047668708 +0100
@@ -2861,8 +2861,14 @@
     */
    showLoginBox: function() {
       // Set focus to password field
-      $(document).on("complete.dialog.jsxc", function() {
-         $('#jsxc_password').focus();
+      $(document).one("complete.dialog.jsxc", function() {
+         setTimeout(function() {
+           if ($("#jsxc_username").val().length === 0) {
+             $("#jsxc_username").focus();
+           } else {
+             $('#jsxc_password').focus();
+           }
+         }, 50);
       });
 
       jsxc.gui.dialog.open(jsxc.gui.template.get('loginBox'));
```

**Comment by sualko** [comment]
Good catch. Can you open a pull request for this change?

**Comment by ChristianTacke** [comment]
I can do that.
BUT I don't want to setup a complete devel env now, so I can patch this into the git und create a nice commit for it, but I wont be able to actually test it. If that's helpful, let me know.

**Comment by sualko** [comment]
> I can do that.

Great. Do it :+1:, because then you will appear in the list of contributors.

**Comment by ChristianTacke** [comment]
Okay, will do.
