### ISSUE TITLE
How to enable audio call only when web cam in not avilable

### ISSUE THREAD

**Issue by sikkandar** [jsxc/jsxc#403]
I have used jsxc client for chatting purpose. It's really good for chatting with people and user free. Video call is working when system has audio device and webcam, but what i need is if webcam is not available in system it will connect as audio call. how to implement it in jsxc client. if audio call already exists in jsxc please guide me how to enable and use.

**Comment by sualko** [comment]
There is a open issue for voice-only calls #6. If you are interested in implementing this, please leave a message.

**Comment by sikkandar** [comment]
what  i understood from this is, Voice only calls not available in jsxc client. am i right?

**Comment by sualko** [comment]
Not available yet :wink:

**Comment by sikkandar** [comment]
ok thanks. Am waiting.
