### ISSUE TITLE
External user is not view a chat

### ISSUE THREAD

**Issue by allhq** [jsxc/jsxc#404]
Hi! (Sorry my bad english. :( )

I use the owncloud and ojsxc(Internal). 
External user plugin: https://apps.owncloud.com/content/show.php/user_sql?content=155512

Owncloud user is view a chat button: 
Extrenal user is can't view a chat button:
(pls see my screenshot)

Why?

Many thanx
Mezo

![noown](https://cloud.githubusercontent.com/assets/14159653/20392250/42f8a5bc-acd7-11e6-9229-700b87b9b32e.png)
![own](https://cloud.githubusercontent.com/assets/14159653/20392249/42f65e9c-acd7-11e6-9c2d-1cc4091b834c.png)

**Comment by sualko** [comment]
cc @LEDfan

**Comment by allhq** [comment]
I found a problem. The problem is a name
My username syntax: ASD_USER USER ----> Can't view
The problem character: "_" " " "/"

**Comment by LEDfan** [comment]
Hi @allhq what version of JSXC are you running? I'm asking because almost the same issue was solved in 3.0.1.

**Comment by allhq** [comment]
Yes i using a JavaScript XMPP Chat 3.0.1

**Comment by sualko** [comment]
@allhq I am sorry, but LEDfan is currently busy and therefore we are not able to provide a patch for your issue in the moment. Please stay tuned.

**Comment by allhq** [comment]
Any news? :(

**Comment by sualko** [comment]
The following characters are not allowed as part of the username (see [RFC 6122](https://tools.ietf.org/html/rfc6122)):

- All whitespace characters (which reduce to U+0020, also called SP)
- U+0022 (")
- U+0026 (&)
- U+0027 (')
- U+002F (/)
- U+003A (:)
- U+003C (<)
- U+003E (>)
- U+0040 (@)

See #501 for more information.
