### ISSUE TITLE
Webrtc problem

### ISSUE THREAD

**Issue by PegasusGo** [jsxc/jsxc#405]
hello

I was testing videocall with a friend who's using chrome and me too, but we have always this errors : 
Appel terminé: jingle_reason_failed-transport.
Appel terminé: jingle_reason_failed-transport.
ICE_connection_failure

Why ?

Thanks

**Comment by sualko** [comment]
To less information: https://github.com/jsxc/jsxc/wiki/Contributor-Guide

Se also #402

**Comment by PegasusGo** [comment]
we lack TURN configuration

**Comment by sualko** [comment]
What do you mean? Please write an complete sentence.
