### ISSUE TITLE
Connection is lost when closing the page for a few minutes

### ISSUE THREAD

**Issue by khanhmas** [jsxc/jsxc#407]
Hello,

As the title says, i'll have some issues about the auto-disconnection if i close the tab for a few minutes. When i come back to the page with the new tab, the connection is lost.

I attempt to use the "disconnected.jsxc" event to try to reconnect by the login function but it always disconnect after that due to CONNFAIL: item-not-found , CONNFAIL: improper-adressing, CONNFAIL: undefined.

Any helps would be appreciated. Thank you

**Comment by sualko** [comment]
Increase the inactive time of your xmpp server.
