### ISSUE TITLE
When page refresh the chat window doesn't visible

### ISSUE THREAD

**Issue by sikkandar** [jsxc/jsxc#411]
Hi,

The chat window does not visible when page refresh. I have received the message twice in console like "I am master, Connection already authenticated" Please help me to solve this isssue. After login the chat window visible only once. After moving to any page it doesn't visibe. My application is fully based on anguarjs. I have append the chat window in my application div.

My init function is like this

```
 jsxc.init({
	      loginForm: {
	         form: '#loginForm',
	         jid: '#username',
	         pass: '#password'
	      },
	      logoutElement: $('#logout'),
	      rosterAppend: '#sociallivechat',
	      root: window.location.pathname.replace(/\/[^/]+$/, "/") + (window.location.pathname.match(/dev\.html/) ? '../dev' : '../build'),
	      displayRosterMinimized: function() {
	         return true;
	      },
	      loadSettings: function(username, password, cb) {
	         cb(settings);
	      },
	      xmpp: {
	         url: settings.xmpp.url
	      }
	   });
```

After success of login in my website i can start jsxc like below

 jsxc.start(login_username + '@' + domain,login_password);

**Comment by sualko** [comment]
Angular is a bit tricky. You have to make sure, that `jsxc.init` is called after `#sociallivechat` is visible.

>  I have received the message twice

You only need to call `jsxc.start` on startup, afterwards jsxc tries to restore the previous connection after a page refresh.

**Comment by sikkandar** [comment]
I am doing like that only, jsxc.start call at only once throughout the application. but how to restore the previous connection after a page refresh

**Comment by sikkandar** [comment]
I have fixed this. Thanks.
