### ISSUE TITLE
Any chance of multiple login on different browsers?

### ISSUE THREAD

**Issue by niteshhardia** [jsxc/jsxc#412]
is there any way we can do a multi-login?

**Comment by MarcelWaldvogel** [comment]
Can you give more detail? Multiple browsers (and private browsing mode) have different copies of localStorage and can therefore operate independently, also as a separate user.

**Comment by niteshhardia** [comment]
@MarcelWaldvogel  Klaus helped me on that issue and it worked charmingly for me.
