### ISSUE TITLE
Top-right chat icon disappears on mobile version of SOGo

### ISSUE THREAD

**Issue by popindavibe** [jsxc/jsxc#414]
Hello,
I am very happy with JSXC on SOGo (version 3.2), however I've been running after the chat panel every time I use it from my phone. Vertical bar is challenging to grasp, but is the only possibility because the icon on top is not there on mobile screen size.
This is reproducible with Firefox _responsive_ mode, if I lower from a higher resolution the chat icon stays (say 360x640), but if then I reload the page on the small format, chat icon disappears and never comes back.
On the phone it never shows the chat icon.

**Comment by sualko** [comment]
Thanks for reporting. It was a stupid bug.
