### ISSUE TITLE
bookmarking several group chats in ejabberd

### ISSUE THREAD

**Issue by mmoqui** [jsxc/jsxc#420]
We use ejabberd as XMPP server (last version, 16.09) and we have encountered a problem when a user bookmarks several chat rooms: the adding of a new group chat into the user's bookmarks in ejabberd replaces the previous bookmarked group chat.

After looking for an explanation on a such strange behavior in the Web, I found the [answer in slashdot](http://stackoverflow.com/questions/31680158/ejabberd-bookmarks-replacing-previous-bookmarks). It appears the [XEP-0048 Bookmarks](http://xmpp.org/extensions/xep-0048.html) and [XEP-0163 PEP](http://xmpp.org/extensions/xep-0163.html) aren't enough accurate to disambiguate how the server should behave when bookmarking a group chat.

In order to fit to this behavior of ejabberd, it should be nice to change JSXC so that bookmarking a new group chat is done by updating the whole remote conference bookmark instead of just adding the new room into it. (But effectively, this  new behavior has to be checked with other XMPP servers like OpenFire for example.)

**Comment by mmoqui** [comment]
In order to fix this problem with strict XMPP servers like ejabberd, I've updated the Strophe Bookmark plugin. See PR [#119](https://github.com/strophe/strophejs-plugins/pull/119).
(I hope the Strophe plugin isn't abandoned and my PR will be merged.)

**Comment by mmoqui** [comment]
My PR is merged :-)

**Comment by mmoqui** [comment]
I pushed also a PR to fix also the deletion of a group chat bookmark according to the new way the bookmarks are now added: PR [#120](https://github.com/strophe/strophejs-plugins/pull/120)
Nevertheless, it isn't yet merged.

**Comment by sualko** [comment]
I think this is no bug, it is more a flaw in the [XEP-0048](http://xmpp.org/extensions/xep-0048.html), because it only specifies how a bookmark element has to look like, but does not say how this has to be stored. So it is more an client than a server issue.

Personally I prefer the use of multiple pub-sub nodes, because the handling is easier. Anyway until the second pr is not merged, I can not update jsxc.

**Comment by mmoqui** [comment]
> Personally I prefer the use of multiple pub-sub nodes, because the handling is easier.
Yes, I agree. Nevertheless, currently, this way doesn't work with all the XMPP servers whereas the "one node for all bookmarks" way seam to work with any XMPP servers. 

I hope my PR in the Strophe Bookmark plugin will be merged (I'm stupid to not have fixed the deletion with the adding at the same time!)

**Comment by sualko** [comment]
> he "one node for all bookmarks" way seam to work with any XMPP servers

It's not an issue with the xmpp server. It is an issue in way xmpp clients interpret the xep.

**Comment by mmoqui** [comment]
Ok, the [PR #120](https://github.com/strophe/strophejs-plugins/pull/120) is merged
