### ISSUE TITLE
Nextcloud 11, fix app version

### ISSUE THREAD

**Issue by enoch85** [jsxc/jsxc#423]
You need to fix the versions for Nextcloud 11.

![deepinscreenshot20161215130821](https://cloud.githubusercontent.com/assets/4511254/21223467/955851ee-c2c7-11e6-8dde-e78d7585d0f3.png)

Please attend this asap. I have customers that need this chat. 

Thank you!

**Comment by enoch85** [comment]
Also you could upoad it directly in the new Nextcluoud app store: https://apps.nextcloud.com/

**Comment by sualko** [comment]
Do you know if this is already an error in nc 11?

**Comment by enoch85** [comment]
Yes, the screenshot is from Nextcloud. @sualko

**Comment by sualko** [comment]
Ok, but this is only a warning and does not to be fixed immediately.

**Comment by enoch85** [comment]
Well, you can't activate the app if the version isn't fixed. This app doesn't even show up in the new Nextcloud appstore actually. I added it manually.

**Comment by sualko** [comment]
Ah ok, this are 2 different error message. Try to add `<nextcloud min-version="8" max-version="11">` to `appinfo/info.xml` below the owncloud tag. I will try to publish an updated version asap.

**Comment by enoch85** [comment]
Yup, that solved it. Now it works.
