### ISSUE TITLE
jsxc.dep.js:5523Uncaught ReferenceError: $build is not defined(…)

### ISSUE THREAD

**Issue by daedeloth** [jsxc/jsxc#429]
Hi there,

I'm trying to figure out why I get this error in my app:
jsxc.dep.js:5523Uncaught ReferenceError: $build is not defined(…)

I think the files are loaded in correct order, and yet jsxc.dep.min throws an error.

Live version (developent):
http://dev.quizwitz.com/

Any ideas?

(Also, is there an IRC / chat channel for jsxc?)

**Comment by sualko** [comment]
Which version of jsxc do you use? Do you use any third-party libraries beside jsxc? 

> Live version (developent):

Sorry, I don't see this error on this site.

**Comment by daedeloth** [comment]
Sorry I changed the way it's loaded, and then I disabled it for now :)
I was loading it through requirejs, and there is loads of external libraries.
I couldn't find any bower config to get it working, even though the order in which the scripts were loaded was the same as the script tags. But I guess the problem was loading the scripts after page load.

I still need to figure out how to properly / beautifully integrate jsxc in our project. I love the xmpp setup, but I feel like I don't have enough control on how the interface looks.

**Comment by sualko** [comment]
StropheJS tries to register some functions (like $build) in the global namespace, so I guess there is your issue, but I have no time to analyse this further.

> feel like I don't have enough control on how the interface looks.

What do you mean exactly?

**Comment by daedeloth** [comment]
Sorry didn't have much time to work on this one. I'll send some examples asap, but the gist of it is that I want to disable features that are confusing for regular internet users. I want to offer something as simple to use as Facebook messenger, and right now I don't feel like that is possible.

Also the way the requirements are included will probably conflict with my own libraries, but I'm not sure how to solve that for now :)

**Comment by sualko** [comment]
> I want to disable features that are confusing for regular internet users

What do you think is confusing for regular internet users? Because we also want to simplify as much as possible.
