### ISSUE TITLE
Two contact lists/chat windows shown w/ collabora online

### ISSUE THREAD

**Issue by rev138** [jsxc/jsxc#435]
When running ojsxc from the nextcloud app store, if you open a document in collabora you end up with two contact lists and all of your chat windows are duplicated as well. I assume this is because it's a frame-in.

I am experiencing this with Nextcloud 11.0.0 and the latest build of the collabora docker image.

![screenshot from 2017-01-09 15-25-27](https://cloud.githubusercontent.com/assets/1538633/21782104/40ecc99c-d680-11e6-97fe-2ae8be597eea.png)

**Comment by sualko** [comment]
Can you provide me an test account? If yes, send credentials to klaus@jsxc.org.

**Comment by rev138** [comment]
Sent. Thanks for the quick response.
