### ISSUE TITLE
Owncloud/Nextcloud chat available on U2F verification screen

### ISSUE THREAD

**Issue by itay-grudev** [jsxc/jsxc#436]
I am using the U2F verification plugin on my Nextcloud installation and i encountered the following problem.

The sidebar with chat windows are available on the U2F verification screen. It shouldn't be available until the login procedure has concluded.

The guys from nextcloud/twofactor_u2f said that it's not an issue on their side.

**Comment by sualko** [comment]
cc @rev138

**Comment by sualko** [comment]
> It shouldn't be available until the login procedure has concluded

Why?

The problem is, that we need the chat at least in the background to prevent timeouts. A hacky untested solution could be to following:

```
if (jsxc.storage.getItem('jid') && $('#logout').length === 0) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.setUserItem('roster', 'hidden');
  jsxc.storage.setItem('u2f', true);
} else if (jsxc.storage.getItem('jid') && jsxc.storage.getItem('u2f')) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.removeUserItem('roster');
}
```

Just add it to `js/ojsxc.js` before `jsxc.init` is called.

**Comment by sualko** [comment]
Was my hack working?

**Comment by itay-grudev** [comment]
I'm sorry. I'll attempt it, but I can't now. Leave the issue open and I'll give you feedback when I try it.

**Comment by jarbro** [comment]
+1

**Comment by sualko** [comment]
@jarbro can you test the proposed fix?

**Comment by jarbro** [comment]
@sualko I just implemented the code above.  Did not seem to make a difference.  To be sure, see where I entered it below to be sure I put it in the correct spot.

/apps/ojsxc/js/ojsxc.js
` if (jsxc.storage.getItem('jid') && $('#logout').length === 0) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.setUserItem('roster', 'hidden');
  jsxc.storage.setItem('u2f', true);
} else if (jsxc.storage.getItem('jid') && jsxc.storage.getItem('u2f')) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.removeUserItem('roster');
}

   jsxc.init({
      app_name: 'Nextcloud',`

**Comment by sualko** [comment]
Can you post a screenshot, because I have no installation with u2f.

**Comment by jarbro** [comment]
![chrome_2017-02-09_11-25-29](https://cloud.githubusercontent.com/assets/3271673/22792394/9166d97e-eeba-11e6-943a-bc6acdab7c27.png)

**Comment by sualko** [comment]
That should not be recognized by an normal user, but you can simple add `$('#jsxc_roster').hide()` to the first if block.

**Comment by jarbro** [comment]
Like this?
'''
jsxc.storage.setUserItem('#jsxc_roster').hide()');

'''

**Comment by sualko** [comment]
Nope :-), just like this:


```
if (jsxc.storage.getItem('jid') && $('#logout').length === 0) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.setUserItem('roster', 'hidden');
  jsxc.storage.setItem('u2f', true);
  $('#jsxc_roster').hide();
} else if (jsxc.storage.getItem('jid') && jsxc.storage.getItem('u2f')) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.removeUserItem('roster');
}
```

**Comment by jarbro** [comment]
The roster scrollbar is still visible on the TOTP screen.

**Comment by sualko** [comment]
Make sure that you load the site not from your browser cache. Most browsers force a complete refresh with ctrl+shift+R.

**Comment by jarbro** [comment]
This was done on two different browsers.  Firefox private window and Chrome incognito.

**Comment by sualko** [comment]
Sorry I'm a fool, I tried to hide something which was not there. Second attempt:

````
if (jsxc.storage.getItem('jid') && $('#logout').length === 0) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.setUserItem('roster', 'hidden');
  jsxc.storage.setItem('u2f', true);
  $(document).on('ready.roster.jsxc', function(){
    $('#jsxc_roster').hide();
  });
} else if (jsxc.storage.getItem('jid') && jsxc.storage.getItem('u2f')) {
  jsxc.bid = jsxc.jidToBid(jsxc.storage.getItem('jid'));
  jsxc.storage.removeUserItem('roster');
}
```

**Comment by jarbro** [comment]
Roster still shows up hidden with the ability to expand.

**Comment by sualko** [comment]
If I have time, I will install my own u2f. This way it makes no more sense.

**Comment by sualko** [comment]
Please test https://github.com/nextcloud/jsxc.nextcloud/pull/5/commits/242c6e95086d94db9c8ab5ad9065c6099b249466
