### ISSUE TITLE
Secure messaging between smartphone and JSXC 

### ISSUE THREAD

**Issue by slormin** [jsxc/jsxc#437]
Hi, working on a project to enable instant messaging between users both using smartphone and jsxc, we've reach the point of encryption.

We've seen that if a secure message is sent from web to an smartphone, we receive the encrypted message, and we don't know how exactly the encryption is generated to implement the decryption in the smartphone end, and see the decrypted message in the APP.

Any kind of help is highly apprecciated.
Thanks.

**Comment by sualko** [comment]
Did you implement an android xmpp client? Is it open source?

Jsxc uses [Off-The-Record messaging](https://otr.cypherpunks.ca) for encryption, which is implemented in javascript by [this library](https://github.com/arlolra/otr).
