### ISSUE TITLE
How to handle lost connection

### ISSUE THREAD

**Issue by neochiai** [jsxc/jsxc#439]
Hi
I am using JSXC 3.0.1, and have noticed that the client connection is sometimes lost, apparently at random times (might be a network instability). Is there some configuration that can be used to handle these lost connections ? 
Thanks
Eduardo

**Comment by sualko** [comment]
Which backend do you use? External or Internal?

**Comment by neochiai** [comment]
I am using an external Openfire 4.0.2 server through http.

**Comment by sualko** [comment]
Try to increase the bosh inactivity time.
