### ISSUE TITLE
Wordpress - login crashes in firefox

### ISSUE THREAD

**Issue by UlrichBoehm** [jsxc/jsxc#441]
Hey all,
when you try to login in wordpress, the jsxc script crashes without error/warning. Nothing happens. Form won't be submitted.

Best regards

**Comment by UlrichBoehm** [comment]
Hey all,
here the solution for wordpress login in firefox:
Within jsxc.getPrefix (at line 8389) you need to change
`
jsxc.trace('Unable to create user prefix');
`
to
`
jsxc.debug('Unable to create user prefix');
`

Now you can login and everything works just fine.

Best regards.

**Comment by sualko** [comment]
That's odd, because there was never (at least a year) a `jsxc.trace`. See [jsxc.lib.storage.js#L25](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.storage.js#L25). Where did you download the source files?

**Comment by UlrichBoehm** [comment]
You are right. I meant `console.trace` not `jsxc.trace`. So you need to replace
`console.trace('Unable to create user prefix');`
with
`console.debug('Unable to create user prefix');`
to fix it.

Best regards

**Comment by sualko** [comment]
Which version of ff do you use? Because `console.trace` should be part of firefox since version 10, see https://developer.mozilla.org/en-US/docs/Web/API/Console/trace

**Comment by UlrichBoehm** [comment]
I'm using current version (50.1.0). I know the console.trace command. 
But I can't explain, why the script crashes at this line. There is no error message. It just stops working.
