### ISSUE TITLE
Jingle File Transfer

### ISSUE THREAD

**Issue by neochiai** [jsxc/jsxc#442]
Hi
I am trying to implement file transfer between an Android device and a web client using JSXC 3.0.1 on the web application. On the Android device i am using the Conversations app.  However, when a file is sent from Conversations an error occurs in JSXC, as below. Apparently the "s5b" and "ibb" transport types are not currently supported in JSXC, is that right ?
Thanks
Eduardo

Error trace in the chrome console:
---------------------------------------
jsxc.dep.js:19632 Uncaught TypeError: Cannot read property 'sctp' of undefined
   at Object.exports.toMediaSDP (https://localhost:8080/jsxc/lib/jsxc.dep.js:19632:22)
   at https://localhost:8080/jsxc/lib/jsxc.dep.js:19610:26
   at Array.forEach (native)
   at Object.exports.toSessionSDP (https://localhost:8080/jsxc/lib/jsxc.dep.js:19609:14)

**Comment by sualko** [comment]
> Apparently the "s5b" and "ibb" transport types are not currently supported in JSXC, is that right ?

That is right. But the next release of jsxc will support http upload.

**Comment by diegobill** [comment]
@sualko , Is it possible to transfer files between Conversations client and JSXC client using XEP-0234: Jingle File Transfer? I am asking this because the XEP-0363: HTTP File Upload does not support access control. That means everyone who knows the URL SHOULD be able to access it and my Conversations client are on the internet.

**Comment by diegobill** [comment]
I am getting this error when the Conversations client try to transfer a file to JSXC client via jingle (webrtc):

´´´
jsxc.dep.js:14540 Uncaught TypeError: Cannot read property 'algo' of undefined
´´´

It happens because offer is undefined here:

```
    onSessionInitiate: function (changes, cb) {
        var self = this;

        this._log('info', 'Initiating incoming session');

        this.state = 'pending';

        this.pc.isInitiator = false;

        var desc = changes.contents[0].application;


        this.receiver = new FileTransfer.Receiver({hash: desc.offer.hash.algo});
        this.receiver.on('progress', function (received, size) {
            self._log('info', 'Receive progress ' + received + '/' + size);
        });
        this.receiver.on('receivedFile', function (file) {
            self.receivedFile = file;
            self.maybeReceivedFile();
        });
        this.receiver.metadata = desc.offer;

        changes.contents[0].application = {
            applicationType: 'datachannel'
        };

        this.pc.handleOffer({
            type: 'offer',
            jingle: changes
        }, function (err) {
            if (err) {
                self._log('error', 'Could not create WebRTC answer');
                return cb({condition: 'general-error'});
            }
            cb();
        });
    },
```

**Comment by diegobill** [comment]
When I put a default value to JSXC code, like this:

```
this.receiver = new FileTransfer.Receiver({hash: (desc.offer.hash ? desc.offer.hash.algo : "sha-1")});
```

I receive the error mentioned by @neochiai : 

```
jsxc.dep.js:32417 Uncaught TypeError: Cannot read property 'sctp' of undefined
```

**Comment by MarcelWaldvogel** [comment]
HTTP Upload is secure *when the URL contains enough entropy*. Then, it is not easier to guess the URL than to fake a certificate, hack your password, or spoof your connection. My understanding is that all current HTTP Upload servers create strong random URLs. So nobody besides the involved parties can learn the URL.

So I do not see how URL guessing should be a security concern. (There are other aspects related to security, but they are being addressed as well.)

**Comment by neochiai** [comment]
Hi, i am still getting the same error in the lastest version, using the online demo https://www.jsxc.org/example/login.html. 
Error when receiving file upload from Conversations app on Android device:
jsxc.dep.js:15498 Uncaught TypeError: Cannot read property 'algo' of undefined
    at FileTransferSession.onSessionInitiate (jsxc.dep.js:15498)
    at jsxc.dep.js:16301
    at jsxc.dep.js:17565
    at process (jsxc.dep.js:17531)
    at Item.run (jsxc.dep.js:29076)
    at drainQueue (jsxc.dep.js:29046)
