### ISSUE TITLE
jingle_reason_failed-transport ERROR

### ISSUE THREAD

**Issue by cpresario** [jsxc/jsxc#444]
Hi!,

I received an error when I started a video call: 
`jingle_reason_failed-transport.`

It happens when users are in a different network, if they are in same network everything is fine.
I have debugged the network and it fails in 'Binding request'.

Hope you can help me.
Regards

**Comment by cpresario** [comment]
I set up a turn server because I was behind multiple firewalls. Then, everything is fine.

**Comment by andrey-utkin** [comment]
@cpresario could you please share where exactly you put your TURN server's address in JSXC sources?

**Comment by sualko** [comment]
@andrey-utkin You don't have to put it in the sources, because it is configurable and like all other options, you can pass [them](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js#L258) to the `jsxc.init` function.

**Comment by diegobill** [comment]
@cpresario , can you pass your jsxc configs to TURN server? My configs does not work in issue #583
