### ISSUE TITLE
Jsxc bookmark not stored in ejabberd 16.09

### ISSUE THREAD

**Issue by peterhoth** [jsxc/jsxc#445]
Hi I am using the latest "jsxc v3.0.1 - 2016-10-28" with ejabberd 16.09 in CentOS 6

I used gajim to create a room and used a user to bookmark and auto join the room. This is the result from the ejabberd server when i checked the bookmark:

> $ ./ejabberdctl private_get user2 mychat.com storage storage:bookmarks
> `<storage xmlns='storage:bookmarks'><conference minimize='1' jid='myroom@conference.mychat.com' autojoin='1' name='myroom'><nick>user two</nick></conference></storage>`
> $

I used another user to join the same room with jsxc and checked on bookmark and auto join at the jsxc form when joining the room. However, when i checked at ejabberd:

> $ ./ejabberdctl private_get user1 mychat.com storage storage:bookmarks
> `<storage xmlns='storage:bookmarks'/>`
> $

When i used user2 to login using jsxc and join the room, i did not get the nickname "user two". It was showing "user2" instead.

It seems to me that the bookmark is stored in the local storage in the browser.

What did i miss ?

**Comment by sualko** [comment]
There are two issues: The first one is described in #420. The second I found is that the [bookmark plugin](https://github.com/strophe/strophejs-plugin-bookmarks) sends pubsub requests only without `to` attribute. This means those request go directly to the domain part of your jid. If you pubsub server is registered under a different name, those requests will fail. I try to fix this in the next release.

**Comment by sualko** [comment]
The fix for this will go into the next bug fix release, because the plugin has some additional changes and we have currently feature freeze.

**Comment by sualko** [comment]
Can you execute the following in your javascript console after the client is ready?

```
jsxc.xmpp.bookmarks.remote()
```

It should return `true`.
