### ISSUE TITLE
Image thumbnail shows white when file transfer from Chrome to Firefox

### ISSUE THREAD

**Issue by PeterEdens** [jsxc/jsxc#449]
I have a chat user logged in to Chrome and one in Firefox, both latest versions, and when I transfer a jpg from chrome to firefox it shows a white thumbnail.  I can download the image from the chat window and it shows correctly on my pc.  Files transferred from Firefox to Chrome show the thumbnail correctly.

Also when I transfer a png I don't get the hand cursor allowing me to download the image, for jpg I do.

**Comment by sualko** [comment]
Can you try the latest beta release? Please also check your javascript console (Ctrl+Shift+I).

**Comment by PeterEdens** [comment]
This problem occurs using the latest beta release, in the javascript console it shows errors about the type text/html not being supported so possibly the mimetype for the thumbnail is wrong?

**Comment by sualko** [comment]
Please enable [debugging](https://github.com/jsxc/jsxc/wiki/Debugging) and post relevant messages here on github.

**Comment by PeterEdens** [comment]
I ran the command to enable debugging but it showed 'undefined' in the command window.  Looking at the html of the element it looks like a base64 string is used for the thumbnail but this resolves to a white image:

<img alt="preview" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAPklEQVR4nO3BMQEAAADCoPVPbQsvoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKcBnKQAAaZ1lY4AAAAASUVORK5CYII=" title="1.jpg">

If I send the same image from Firefox to Chrome the above preview contains a longer base64 string for the image data and shows the thumbnail correctly.

**Comment by sualko** [comment]
Does this issue still persist, because I am not able to reproduce this in v3.2.0.

**Comment by PeterEdens** [comment]
No I cannot reproduce the issue either, it works fine now in 3.2.0.
