### ISSUE TITLE
http upload not detected on prosody

### ISSUE THREAD

**Issue by ChristianTacke** [jsxc/jsxc#450]
jsxc: 3.1.0-beta
prosody: 0.9.7-2+deb8u3 (Debian/stable)

jsxc does not detect the http upload settings properly on prosody.

* The call to `disco.items("jabber.example.org")` only returns the extra services on prosody (in my case the MUC service: `conferences.jabber.example.org`), but not the main jid of the server (`jabber.example.org`). The http upload service is on the main jid.
* I don't know, whether this behaviour violates any RFC/XEPs. If so, we can recheck with the prosody team, if this has been fixed in a later version.
* Running `disco.info("jabber.example.org")` returns the proper info that also contains the http upload elements.

If this does not violate any RFC/XEPs, I suggest to first check the main jid of the server and then the jids in `disco.items`.

**Comment by sualko** [comment]
Do you mean fqdn with "main jid"?

**Comment by sualko** [comment]
I think I got it :smile:

**Comment by sualko** [comment]
Please test and verify.

**Comment by ChristianTacke** [comment]
Yes, works! Thanks!

Small problem:

    discover http upload service
    query jabber.example.org for upload service
    http upload service found on jabber.example.org
    Variable httpUpload doesn't exist. It was created.
    query conference.jabber.example.org for upload service

It queries conference, despite having already found something.

Possible patch:
```text/x-diff
--- /tmp/jsxc.js        2017-02-06 13:49:09.023337819 +0100
+++ jsxc.js     2017-02-06 13:45:12.464115732 +0100
@@ -11772,6 +11772,10 @@
 jsxc.xmpp.httpUpload.queryItemForUploadService = function(jid, cb) {
    var self = jsxc.xmpp.httpUpload;
 
+   if (self.ready) {
+      jsxc.debug('Already found upload service, not querying ' + jid);
+      return;
+   }
    jsxc.debug('query ' + jid + ' for upload service');
 
    self.conn.disco.info(jid, null, function(info) {
```

Let me know, if you want me to create a PR for this.

**Comment by sualko** [comment]
Thanks for the hint.
