### ISSUE TITLE
JSXC seems to try to force OTR use

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#453]
I'm not sure if it's JSXC doing this or not, but I *think* it is.

Seems whenever someone chats in the web interface JSXC keeps trying to enable otr, even when I'm not manually clicking the lock.  Was hoping someone else had any ideas, could investigate, verify that I'm the only one with this problem.

**Comment by MarcelWaldvogel** [comment]
All current JSXC releases announce their ability to do OTR. Then, probably, the other side tries to switch it on. The current Beta no longer does so. Can you test with it? (3.1.0 should be released any day now)


Viele Grüsse,
-Marcel Waldvogel
(kurz&bündig)

**Comment by Luticus** [comment]
I'll give it a shot.  Looks like only beta1 is available for owncloud at the moment and I just realized this issue thread is for the general jsxc.  I have installed beta1 and will test it out and see if it gets rid of this issue.

**Comment by MarcelWaldvogel** [comment]
It is a generic JSXC issue, so this is the right place to discuss. Please reopen this issue if necessary.

**Comment by Luticus** [comment]
I will do that.  Thanks for your help.


Thanks,

Joe McEntire
getjoe@live.com
On Feb 14, 2017, at 2:38 AM, Marcel Waldvogel <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #453<https://github.com/jsxc/jsxc/issues/453>.
