### ISSUE TITLE
Integrate into ownCloud/Nextcloud activity section

### ISSUE THREAD

**Issue by tyrann0us** [jsxc/jsxc#454]
Hi!
I really like ojsxc, thanks for it!
I'm wondering if it's possible to integrate the plugin to the activity section of ownCloud/Nextcloud?
What I think about is something like the option to get an email notification if you received a message while beeing offline.
That would be really great!
Thanks.

**Comment by MarcelWaldvogel** [comment]
The problem is the chat is only active when you are in the browser.

You may however use any other XMPP client to access your messages. See https://omemo.top/ for some clients under active development. (This currently requires the use of an external XMPP server.)

**Comment by sualko** [comment]
This would only be possible for the internal xmpp server, but this is currently out of scope. Sorry.
