### ISSUE TITLE
Nextcloud password must match xmpp password

### ISSUE THREAD

**Issue by gjedeer** [jsxc/jsxc#455]
I wasted a lot of time figuring out why I can't log in to my XMPP server even though all the settings look correct. Then I stumbled upon this:

```
if(!empty($_POST['password']) && !empty($_POST['username'])) {
   $currentUser = \OC::$server->getUserManager()->checkPassword($_POST['username'], $_POST['password']);
} else if (OCP\User::isLoggedIn()) {
   $currentUser = \OC::$server->getUserSession()->getUser();
}
```

Commented that out to let the XMPP server do its own authentication and suddenly I could log in!

```
//if(!empty($_POST['password']) && !empty($_POST['username'])) {
//   $currentUser = \OC::$server->getUserManager()->checkPassword($_POST['username'], $_POST['password']);
/*} else*/ if (OCP\User::isLoggedIn()) {
   $currentUser = \OC::$server->getUserSession()->getUser();
}
```

This is very confusing. At the very least, jsxc should show a message like "Your nextcloud password needs to be the same as your XMPP password" if this check fails. Even better if it was possible to disable this behavior without editing the code.

**Comment by sualko** [comment]
- You are right for the dual-login (nextcloud + xmpp) you need the same password for both services.
- To allow login with different credentials via the login box we probably have to switch the if cases.
- And we should definitely document this behavior better in the installation manual.

**Comment by ITwrx** [comment]
i don't know if i'm understanding the situation properly b/c i'm just trying to set it up for the first time but it seems that the desired xmpp users' creds must match the nextcloud users' creds (every user!). if so, this is highly undesirable from my perspective. 

why should login into nextcloud even be tied to jsxc or be prevented b/c chat login doesn't work. that makes no sense to me. the chat interface (inside nexcloud!) can complain all it wants about creds not being correct or anything else in it's proper domain, but having two different login links/buttons/methods seems like the wrong approach. I don't want any nextcloud app jacking with nextcloud session/login, period.

secondly, using the nextcloud creds can be an option(?) but shouldn't be mandatory, and i would argue, not default. I fully expected to be able to designate xmpp user creds (or allow the users to enter their xmpp creds. preferably the admin's option.) for any desired nextcloud xmpp user.  It's shocking that jsxc expects to get nextcloud admin user creds, for instance.  Also, should i have nextcloud users type their long nextcloud passwords into whatever crazy xmpp app on whatever possibly compromised computer they decide to use one day? or maybe i should weaken all the nextcloud passwords so they're easier to type or to match the xmpp server that's already setup with users? 

I really hope this can be changed. This looked to be a nice app and very useful integration, but not at the session level.

thanks

**Comment by MarcelWaldvogel** [comment]
a) Most of our users do have some form of unified accounts.
b) If we don't do it then, we have to store the passwords in persistent storage, which we consider to be extremely unpleasant.

Our goal is to work toward tokens between the servers; stay tuned.

**Comment by ITwrx** [comment]
thanks for the info.
Out of curiosity, why is storing a hash of an xmpp password in the database considered unpleasant?
 
Will look forward to the token implementation. Is there a issue i should track for that?

**Comment by MarcelWaldvogel** [comment]
Storing of a hash does not work, as the password has to be presented to
the XMPP server on login, not just the hash. (And if the hash was
enough to impersonate, then storing the hash would be unpleasant as
well.)
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jsxc/jsxc
> ","title":"jsxc/jsxc","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jsxc/jsxc"}},"updates":{"snippets":
> [{"icon":"PERSON","message":"@ITwrx in #455: thanks for the
> info.\r\nOut of curiosity, why is storing a hash of an xmpp password
> in the database considered unpleasant?\r\n \r\nWill look forward to
> the token implementation. Is there a issue i should track for
> that?"}],"action":{"name":"View
> Issue","url":"https://github.com/jsxc/jsxc/issues/455#issuecomment-
> 280245697"}}}

**Comment by dteleguin** [comment]
@MarcelWaldvogel, speaking of tokens, is there any design decision made yet? Are you going to invent something, or rather use an existing token-based framework like OAuth / OpenID Connect?

I remember @sualko once has voiced this idea under #427, please see my [comment](https://github.com/jsxc/jsxc/issues/427#issuecomment-268864449) there.

**Comment by MarcelWaldvogel** [comment]
We were planning to start with something light, intended for servers under the same administration. Our requirement is to create a BOSH session based on a Shibboleth/SAML login.

It is intended as a shim layer between a pair of servers trusting each other. Later, SAML token passing is envisioned. We haven't thought yet about how oAuth might play into this, but we plan to spend some time on this in the next few weeks.

**Comment by 9662** [comment]
I reckon this is why my installation (fresh from 20 minutes ago) is not working. Any idea how long commit 206d092 may take to appear in new installations (from within nextcloud, not via git)? I'll try again in a couple of weeks.

**Comment by sualko** [comment]
@9662 Probably end of the week, but this only allows login from the login box. No dual login!

**Comment by 9662** [comment]
@sualko Cheers. Did not understand very well what you meant by

>  this only allows login from the login box. No dual login!

but never mind, I'll give it another try in a couple weeks. Thanks for the good work! 👍
