### ISSUE TITLE
http upload not detected on ejabberd

### ISSUE THREAD

**Issue by PeterEdens** [jsxc/jsxc#457]
I am using jsxc for nextcloud version 3.1.1 with ejabberd 16.01 and I am trying to send an image to the conversations app on Android but jsxc does not detect http upload support in the ejabberd server.  I am seeing in the web console "192.168.0.211 does not support http upload" but the conversationsn app detects http upload in ejabberd and is able to send files to jsxc which appear as links.  Conversations seems to query upload.192.168.0.211 to get the http upload feature but jsxc does not do this.

**Comment by MarcelWaldvogel** [comment]
Numeric IP addresses are not really supported by JSXC (nor XMPP). Can you try with a host name?

**Comment by PeterEdens** [comment]
I tried it with a hostname and the same result "host-211.mydomain.com does not support http upload"

**Comment by sualko** [comment]
Just to inform you, I could reproduce your issue.

**Comment by PeterEdens** [comment]
Thanks, this fix resolves the discovery.
