### ISSUE TITLE
BOSH server NOT reachable or misconfigured.

### ISSUE THREAD

**Issue by fedex29** [jsxc/jsxc#458]
Hello! 

I've configured an ejabberd and a openfire server on different servers, but I could not get it to work inside owncloud

The error message is:

"Cross domain request was not possible. Either your BOSH server does not send any Access-Control-Allow-Origin header or the content-security-policy (CSP) blocks your request. Starting from Owncloud 9.0 your CSP will be updated in any app which uses the appframework (e.g. files) after you save these settings and reload.The savest way is still to use Apache ProxyRequest or Nginx proxy_pass."

In openfire i change crossdomainpolicy.xml opening and allowing everything but without success

I tried in old versions, and in the newest from owncloud and jsxc (relased yesterday)

System:
Digital Ocean droplet, ubuntu 16.04, 1 cpu 1 gb RAM, 30 GB ssd

Can you please help me?

**Comment by himbeere** [comment]
I'm having the same issue. Not able to connect to a remote or even a local ejabberd listening on 5280 http-bind. Is there anything i can do to debug that?

thanks and cheers

**Comment by himbeere** [comment]
I even see the connection attempt from nextcloud jsxc.

```
2017-02-15 21:13:54.449 [info] <0.495.0>@ejabberd_http:init:158 started: {p1_tls,{tlssock,#Port<0.7790>,#Port<0.7791>}}
2017-02-15 21:13:54.663 [info] <0.456.0>@ejabberd_listener:accept:333 (#Port<0.7792>) Accepted connection ::FFFF:nice.ip:59818 -> ::FFFF:nice.ip:5280
```

**Comment by sualko** [comment]
Maybe you are using a wrong xmpp domain. Please beware that the xmpp domain is not required to be your hostname of the xmpp server.

**Comment by fedex29** [comment]
I can resolve the bosh conection with openfire, but after login, the icon dissaperd from the panel

**Comment by sualko** [comment]
@fedex29 Please check your javascript console.

**Comment by fedex29** [comment]
This is the result:
![image](https://cloud.githubusercontent.com/assets/9285331/23022747/3935cf18-f431-11e6-8ad0-5f91c2c0d06b.png)

**Comment by himbeere** [comment]
It seems i found a setting which enables me to contact the locally running ejabberd. Now i get the login window. But login does not work at the moment. I use username@xmppdomain as username and the passwort i set with ejabberctl. Any hints?

thanks and cheers

**Comment by sualko** [comment]
@himbeere Please beware that we require to use the same password for nextcloud and xmpp. Please also check if your xmpp server is probably configured for bosh with another xmpp client like pidgin.

**Comment by fedex29** [comment]
I solved the problem!

i change the xmpp domain from localhost to my domain and it works ok!

Thanks!

**Comment by himbeere** [comment]
Is the username also required to be the same? Here is how it looks right now. Not able to login.
![bildschirmfoto 2017-02-16 um 15 03 25](https://cloud.githubusercontent.com/assets/631865/23024194/4fa9049a-f459-11e6-80da-f1f8da06f0e9.png)

**Comment by himbeere** [comment]
In the console answer section i get: "{"result":"noauth"}". So it's an ejabberd issue now?

**Comment by ColdSphinX** [comment]
Hi, I had a similar problem running the xmpp server on a different subdomain.
Solution for apache: `Header edit Content-Security-Policy "^(.*connect-src )(.*)$" "$1https://jabber.example.com:7443 $2"`

**Comment by stone212** [comment]
@fedex29 

> i change the xmpp domain from localhost to my domain and it works ok!

You mean in the XMPP server apache2 config here:

`RewriteRule ^/http-bind$ http://localhost:5280/http-bind [P,L] `

or somewhere else?

**Comment by fedex29** [comment]
> @fedex29
> 
> > i change the xmpp domain from localhost to my domain and it works ok!
> 
> You mean in the XMPP server apache2 config here:
> 
> `RewriteRule ^/http-bind$ http://localhost:5280/http-bind [P,L] `
> 
> or somewhere else?


308/5000
This I did 2 years ago, so I do not remember much ... but recoured having changed the apache configuration itself, also enabling a proxy to redirect the port.
But try changing localhost for the exact domain

My memory wanted to forget the amount of hours dedicated to solve the problem 🤓
