### ISSUE TITLE
Documentation lacking for file transfer and video call

### ISSUE THREAD

**Issue by Majaspic** [jsxc/jsxc#459]
There's no documentation for video stuff. And I don't know what to do about file transfer stuff. No documentation for that feature either.

Can you please provide it ? When I send a file to someone, he didnt receive anything everytime

**Comment by sualko** [comment]
There is some documentation about [WebRTC](https://github.com/jsxc/jsxc/wiki/WebRTC-how-to) and [file transfer](https://github.com/jsxc/jsxc/wiki/File-transfer), but I think this can definitely be improved. We always appreciate contributions :wink:.
