### ISSUE TITLE
ejabberd/owncloud auth script cleanup

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#46]
The ejabberd/owncloud auth script has two issues which could be cleaned up:
1. It exec()s a new PHP process for every auth request → Integrate `auth_oc_user.php` into `auth_ejabberd_oc.php` (either by merging the file or by including it at run time)
2. The configuration part should not be inline, but included at run time from a file in `/etc`
##

**Comment by sualko** [comment]
The script is deprecated, so no need to clean up anything.
