### ISSUE TITLE
not able to login to nextcloud anymore after enable jsxc

### ISSUE THREAD

**Issue by himbeere** [jsxc/jsxc#462]
Hello Devs.

Suddenly i'm not able to login anymore to my nextcloud. Here is the log message:

```
{"reqId":"\/mmC6EvPINMMGEujbC\/+","remoteAddr":"100.100.100.100","app":"PHP","message":"Undefined offset: 1 at \/var\/www\/nextcloud.dev\/htdocs\/apps\/ojsxc\/ajax\/getSettings.php#58","level":3,"time":"2017-02-16T08:40:04+00:00","method":"POST","url":"\/index.php\/apps\/ojsxc\/ajax\/getSettings.php","user":"--","version":"11.0.1.2"}
```

After deleting apps\/ojsxc i can login again.

cheers
t.

**Comment by sualko** [comment]
This message is just an info and will not prevent the login. You are not able to login because your configuration is wrong, as seen in #458, but you should be able to login with the "Login without chat" link.
