### ISSUE TITLE
jsxc_avatar set to greyscale with .jsxc_oneway

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#467]
Curious as this only happens with one contact:
I am probably missing something as my guess is this is a feature to indicate I am missing from their roster or something along those lines. 

```
element.style {
    background-color: rgb(85, 93, 246);
    color: rgb(255, 255, 255);
    font-weight: bold;
    text-align: center;
    line-height: 36px;
    font-size: 21.6px;
}
jsxc.css:3945
.jsxc_oneway .jsxc_avatar {
    /* -webkit-filter: grayscale(100%); */
    /* filter: grayscale(100%); */
}
```

Thanks!

**Comment by sualko** [comment]
Yes you are right. This is intended behavior, because xmpp uses a two way subscription. So this means you or your contact is not subscribed to the other.
