### ISSUE TITLE
Chat State Notifications

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#468]
Just upgraded to 3.1.1 this morning, only odd bit I've seen thus far:

Incoming chat states from another resource (in my case Conversations on android) appear to work, but chat states between two JSXC resources do not.

Also, I found that when the chat state is displayed, it will either be at the top of the conversation or inline with messages if the JSXC resource sends a message(s) while the other resource is still "composing"

Would it be possible to set a fixed position for the chat state messages in the bottom either to the left or center?
Thanks for the great app!
-Skyfox
![capture](https://cloud.githubusercontent.com/assets/4504420/23270223/c84a7230-f9b8-11e6-853f-ebbe6e7cef50.PNG)

**Comment by skyfox675** [comment]
I was able to track this down to a possible issue with my Web server's cache post upgrade and stale user caches. 

This is now working as expected, and I must say really awesome!

Please feel free to close if you are unable to replicate the initial reported issue.

Thanks,

-Skyfox

**Comment by skyfox675** [comment]
Here is a more useful use case for what I am seeing.
![capture](https://cloud.githubusercontent.com/assets/4504420/23369054/b0c5c2ca-fcd5-11e6-83e7-a5e24b51bee2.PNG)

Thanks,

-Skyfox

**Comment by sualko** [comment]
> Would it be possible to set a fixed position for the chat state messages in the bottom either to the left or center?

We already tried it and together with the message is was overlaying incoming messages. If you have a better idea, please feel free to open a pull request for that.

**Comment by sualko** [comment]
![screenshot from 2017-03-20 17-27-44](https://cloud.githubusercontent.com/assets/2974196/24109993/9441f146-0d92-11e7-890f-fbcea6885380.png)
