### ISSUE TITLE
Message to new contact

### ISSUE THREAD

**Issue by komantsev** [jsxc/jsxc#470]
Hi! I use jsxc client with my OpenFire server.
I have 2 users (ivan001, ivan002).
Both users is online (**is important**).

Ivan002 (I2) adds ivan001 (I1) to contact list and sends him a message.
I1 received 2 notifications: add contact request and message from unknown user.
I1 clicks first notification and adds I2 to contact list.
I1 clicks second notification, accept request but he don't view a message from I2.
Messages from I1 to I2 is successfully delivered, but from I2 to I1 - not.

Page refresh (F5) fix this bug.

Here is video: https://www.youtube.com/watch?v=IuC3l1mIzZA

**Comment by sualko** [comment]
Thanks for reporting. Can you check the javascript console from your right browser window?

**Comment by komantsev** [comment]
Right window:
> State changed to INITIATING
> jsxc.js:185 State changed to PREVCONFOUND
> jsxc.js:185 check master
> jsxc.js:185 I am master.
> jsxc.js:185 State changed to ESTABLISHING
> jsxc.js:185 Try to attach
> jsxc.js:185 SID: 45l4wz5qvz
> jsxc.js:185 ATTACHED: null
> jsxc.js:185 UI State changed to INITIATING
> jsxc.js:185 Request server capabilities
> jsxc.js:185 UI State changed to READY
> jsxc.js:185 DSA key loaded
> jsxc.js:185 State changed to READY
> jsxc.js:185 Waiting for server capabilities
> jsxc.js:185 [ERROR] [XMPP] 404 remote-server-not-found
> jsxc.js:185 close dialog
> jsxc.js:185 Update file transfer icons for ivan001@pushtip.com
> jsxc.js:185 webrtc.initWindow
> jsxc.js:185 Update file transfer icons for ivan001@pushtip.com
> jsxc.js:185 Presence (ivan001@pushtip.com): online
> jsxc.js:185 Update file transfer icons for ivan001@pushtip.com
> jsxc.js:185 Presence (ivan001@pushtip.com/example): online
> jsxc.js:185 Update file transfer icons for ivan001@pushtip.com
> jsxc.js:185 Update file transfer icons for ivan001@pushtip.com
> jsxc.js:185 Auto approve contact request, because he is already in our contact list.
> jsxc.js:185 close dialog
> jsxc.js:185 Update file transfer icons for ivan001@pushtip.com
> 

Left window:

> jsxc.min.js:13 State changed to INITIATING
> jsxc.min.js:13 State changed to PREVCONFOUND
> jsxc.min.js:13 check master
> jsxc.min.js:13 I am master.
> jsxc.min.js:13 State changed to ESTABLISHING
> jsxc.min.js:13 Try to attach
> jsxc.min.js:13 SID: 2k8bkadisn
> jsxc.min.js:13 ATTACHED: null
> jsxc.min.js:13 UI State changed to INITIATING
> jsxc.min.js:13 Request server capabilities
> jsxc.min.js:13 UI State changed to READY
> jsxc.min.js:13 DSA key loaded
> jsxc.min.js:13 State changed to READY
> jsxc.min.js:13 Waiting for server capabilities
> jsxc.min.js:13 close dialog
> jsxc.min.js:13 close dialog
> jsxc.min.js:13 Presence (ivan002@pushtip.com): online
> jsxc.min.js:13 Presence (ivan002@pushtip.com/example): online
> jsxc.min.js:13 close dialog
> jsxc.min.js:13 Update file transfer icons for ivan002@pushtip.com
> jsxc.min.js:13 webrtc.initWindow
