### ISSUE TITLE
when webRTC is disabled alt-login won't show up

### ISSUE THREAD

**Issue by pmgouveia** [jsxc/jsxc#471]
On firefox 51.0.1 
when setting
media.peerconnection.enabled to false in about:config

jsxc fails to load
```
ReferenceError: mozRTCPeerConnection is not defined[Learn More]  jsxc.dep.js:35076:5
ReferenceError: emojione is not defined[Learn More]  jsxc.js:2640:7
State changed to INITIATING  jsxc.js:185:10
TypeError: jsxc.options is undefined[Learn More]
```

btw.. webRTC is leaky 
https://browserleaks.com/webrtc

**Comment by sualko** [comment]
Hey, the [strophe.jinglejs](https://github.com/sualko/strophe.jinglejs/blob/master/strophe.jinglejs.js) lib uses a webrtc adapter which changed his name, so we got no announcements about updates anymore. Really crazy... [webrtc-adapter-test](https://www.npmjs.com/package/webrtc-adapter-test) and [webrtc-adapter](https://www.npmjs.com/package/webrtc-adapter) link to the same repo, but only one is updated.

**Comment by sualko** [comment]
a6de6d6843e9f498356d0003e652f9309462af6d should fix this
