### ISSUE TITLE
can't build from source

### ISSUE THREAD

**Issue by pmgouveia** [jsxc/jsxc#472]
when running
`grunt build`
I get this error:

```
Running "sass:dist" (sass) task
>> Error: File to import not found or unreadable: ../lib/magnific-popup/src/css/main.
>>        Parent style sheet: /home/bodymind/devel/git/jsxc/scss/_dep.scss
>>         on line 1 of scss/_dep.scss
>> >> @import "../lib/magnific-popup/src/css/main";
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.
```

**Comment by pmgouveia** [comment]
https://github.com/jsxc/jsxc/wiki/Developer-notes

**Comment by pmgouveia** [comment]
I run
`npm install`
`node_modules/bower/bin/bower install`
`node_modules/grunt/bin/grunt build`

and I get
`bower sinon#*                                                        EHTTP Status code of 404`

**Comment by sualko** [comment]
sinon is only used by a dependency of jsxc for testing, so this should be no issue and most of the time such a bower 404 is only temporary.

**Comment by pmgouveia** [comment]
ei,

now i get

`$ grunt build
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:files" (jshint) task
>> 15 files lint free.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "sass:dist" (sass) task
>> Error: File to import not found or unreadable: ../lib/bootstrap/assets/stylesheets/bootstrap/variables.
>>        Parent style sheet: /home/bodymind/devel/git/jsxc/scss/_dep.scss
>>         on line 5 of scss/_dep.scss
>> >> @import "../lib/bootstrap/assets/stylesheets/bootstrap/variables";
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.


$ npm --version
4.2.0
$ node --version
v7.5.0

what are u using?

**Comment by sualko** [comment]
Is there a file called `_variables.scss`?

It's probably more an sass issue:

```
$ sass --version
Sass 3.4.22
$ npm --version
3.5.2
$ node --version
v4.2.6
```

**Comment by pmgouveia** [comment]
hmm 
`lib/bootstrap` folder is empty.. I installed sass now... it should be added as a devDependency ! ;) 
its cool not to use `npm install -g `because of this.. then you end up not knowing if your package.json is missing something.

```bash
$ ls scss/
_buddylist.scss  _colors.scss  _dep.scss  emoticons.scss  _jsxc.scss  jsxc.scss  _modules.scss  _muc.scss  _roster.scss  _state.scss  _webrtc.scss  _window.scss
```

cleaned everything and rebuild.. same error. I dunno much about sass :|

**Comment by sualko** [comment]
`lib/bootstrap` is a submodule.
