### ISSUE TITLE
Call never reaches callee 

### ISSUE THREAD

**Issue by andrey-utkin** [jsxc/jsxc#473]
## Callee never notices that there's a call for them.

Caller watches spinner forever.

> Which jsxc version number do you use?

git master eeab8355e54582cf610f9091160f8c951faf6bfb

I have updated from git several times in last few weeks, so this seems to be
constant state of affairs.

> In which system do you use jsxc? (e.g. owncloud, sogo, ...)

example login page

> Can you reproduce your issue? If yes, how?

See below

> Which browser and browser version do you use?

Google Chrome Version 57.0.2987.13 dev (64-bit)

Same with Firefox 51.0 (64-bit)

> Do you have any browser plugins enabled?

In Chrome, no.

> Do you see any errors in your javascript console?

jsxc.dep.js:4809 POST https://dev.decent.im/http-bind/ 504 (Gateway Time-out)

Setup:

I run my own XMPP server (dev.decent.im) based on Prosody from upstream
hg trunk (changeset 7909:428d4abee723 of Feb 20 at the moment). mod_bosh is
enabled, nginx forwards BOSH connections to https 5281 port as follows
(conforming to JSXC recommendations):

```
location /http-bind {
	proxy_pass  https://localhost:5281/http-bind;
	proxy_set_header Host $host;
	proxy_buffering off;
	tcp_nodelay on;
}
```

I open two Chrome sessions: one regular and one incognito. In both, I navigate
to https://dev.decent.im/jsxc/example/ , set XMPP server to dev.decent.im and
BOSH URL to /http-bind/ , and log in using Box Login widget (others don't
work as they produce POST request to login.html which is static page).

I log in as users andrey.utkin@dev.decent.im and andrey.utkin.2@dev.decent.im
. They have each other in roster and can message each other. When I make call
between them, it never passes. I have read the note that JSXC's default STUN
server, stunprotocol.net, has banned Russia and Ukraine, but I'm in the UK at
the moment. From chrome://webrtc-internals it seems like STUN processing
accomplishes, however I am ready to provide more info on that on request.

I suspect there may be something wrong with XMPP connection via HTTP proxied
by nginx. See combined logs in jsxc_call.log, and browser console logs in
caller.js_log and callee.js_log .

Note these messages - probably that is what's wrong, but I have no idea what
to do about that.

```
==> /var/log/nginx/dev.decent.im.error_log <==
2017/02/27 23:16:00 [warn] 31562#0: *1015 upstream server temporarily disabled while reading response header from upstream, client: 188.221.179.100, server: dev.decent.im, request: "POST /http-bind/ HTTP/1.1", upstream: "https://[::1]:5281/http-bind/", host: "dev.decent.im", referrer: "https://dev.decent.im/jsxc/example/"
2017/02/27 23:16:00 [error] 31562#0: *1015 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 188.221.179.100, server: dev.decent.im, request: "POST /http-bind/ HTTP/1.1", upstream: "https://[::1]:5281/http-bind/", host: "dev.decent.im", referrer: "https://dev.decent.im/jsxc/example/"
```

In clients' browser console, I see such messages:

```
jsxc.dep.js:4809 POST https://dev.decent.im/http-bind/ 504 (Gateway Time-out)
```

still it seems the clients are somewhat resilient to these errors, as later
buddies presence updates happen and are logged to console.

Thanks in advance for any help with this.

Also, a quick question - is mailing list actually a thing? I've subscribed to it only to see that archive is empty, which discouraged me from posting there.

[jsxc_call.log.txt](https://github.com/jsxc/jsxc/files/805331/jsxc_call.log.txt)
[callee.js_log.txt](https://github.com/jsxc/jsxc/files/805330/callee.js_log.txt)
[caller.js_log.txt](https://github.com/jsxc/jsxc/files/805332/caller.js_log.txt)

**Comment by sualko** [comment]
That's a beautiful report. Thanks for that. :+1: 

Currently my assumption is that this is not directly related to any NAT/WebRTC issue, because the call notification should appear before any WebRTC connection is established.

If I have time I will check your logs and see if I can find anything. Please remind me if I don't respond in a couple of days.

**Comment by andrey-utkin** [comment]
No changes. Do I need to recompile combined JS files or do anything like that?

**Comment by andrey-utkin** [comment]
If anybody could share a pair of credentials for another JSXC deployment, I'd test it. I am also happy to provide credentials from the setup I am testing this on.

**Comment by sualko** [comment]
https://www.jsxc.org/example/

**Comment by andrey-utkin** [comment]
In  order to try https://www.jsxc.org/example/ out, I need XMPP accounts on jsxc.org. My browsers (FF, Chrome) can't connect to dev.decent.im BOSH server, I suppose it's browsers restrictions, because on my server's side I didn't put such restrictions.

**Comment by MarcelWaldvogel** [comment]
Actually, you do (to some extent ;-) ), by not telling Prosody to allow cross-site BOSH requests.

You can enable this by adding `cross_domain_bosh = true` to your Prosody configuration. See https://prosody.im/doc/modules/mod_bosh

**Comment by sualko** [comment]
> You can use demo1 to demo5 with password demo to test JSXC (XMPP domain: jsxc.org, BOSH url: /http-bind/).

:wink:

**Comment by andrey-utkin** [comment]
@sualko thanks for pointing to credentials, there's too much text on that page for me to notice there's extra paragraph with it :) With these credentials, calls work.

@MarcelWaldvogel you must be right. Not being keen on BOSH, I assumed that since I proxy BOSH requests through nginx, prosody sees requests as coming from localhost and is fine with that.

BTW connecting to my BOSH server from https://www.jsxc.org/example/ fails because actual requests go to jsxc.org/http-bind/, jsxc.org seems to be hardcoded, and this was previously reported: https://github.com/jsxc/jsxc/issues/289#issuecomment-233209683

**Comment by andrey-utkin** [comment]
Unfortunately I fail to isolate the issue to browser vs server-side because I cannot connect to my BOSH/XMPP server using https://www.jsxc.org/example/ page and same way cannot connect to jsxc.org using my deployment of JSXC. I get such error when testing BOSH URL:
```
BOSH server NOT reachable or misconfigured.
Host unknown: jsxc.org is unknown
```

**Comment by MarcelWaldvogel** [comment]
@sualko Maybe there should be a (server-side) test whether the BOSH server used has the appropriate CORS settings activated? At least on the example domain, so users can verify the correct configuration.

**Comment by andrey-utkin** [comment]
@sualko could you also please update https://www.jsxc.org/example/ to latest version from git and/or take a note which version was previously deployed?

**Comment by sualko** [comment]
I updated and fixed the example. Please close this issue, if your original problem is solved.

**Comment by andrey-utkin** [comment]
No, it is not fixed in my setup.

From looking into `chrome://webrtc-internals`, nothing happens after `icegatheringstatechange` in my setup. In case of JSXC, it is followed by `setRemoteDescription` and other interesting stages.

**Comment by andrey-utkin** [comment]
I see that jsxc.min.js hasn't been updated lately, but it is downloaded when JSXC example page is opened. I've asked about this [earlier in this thread](https://github.com/jsxc/jsxc/issues/473#issuecomment-283745848), maybe this is why I see no changes?

> Do I need to recompile combined JS files or do anything like that?

**Comment by sualko** [comment]
The example is updated to 3.1.1 and not to the latest nightly. And yes you have to build your own version if you like to use the latest git version. If you run `make` there should be a new folder called `dev` which holds all desired files.

**Comment by andrey-utkin** [comment]
Thanks. Built it all, replaced build/ contents with dev/ contents, modified example/index.html as follows. The issue persists.

```
diff --git a/example/index.html b/example/index.html
index 1567b96..b04417d 100644
--- a/example/index.html
+++ b/example/index.html
@@ -27,7 +27,7 @@
    <script src="js/bootstrap.min.js"></script>
 
    <!-- jsxc library -->
-   <script src="../build/jsxc.min.js"></script>
+   <script src="../build/jsxc.js"></script>
 
    <!-- init script -->
    <script src="js/example.js"></script>
```

**Comment by andrey-utkin** [comment]
When calling from demo*@jsxc.org to my accounts, my account session sees incoming call dialog box and call setup is attempted (though no success here). But when I call just between my accounts, there's no dialog on callee side.

**Comment by andrey-utkin** [comment]
Could you please reveal which XMPP server and maybe possible companion modules of it you use on  jsxc.org?

**Comment by jngexact** [comment]
Was wondering if it was ever figured out what was causing this issue? 

I'm seeing the same behavior of my setup, although I'm using ejabberd on Windows (on an Azure VM, if that makes a difference). My javascript logs (on caller and callee) are almost exactly the same as the one attached to this issue.

I also compared the javascript logs on caller and callee when using https://www.jsxc.org/example/ (which DOES work), and the log is the same. Everything looks OK, with the exception that the caller never receives the prompt.

Funnily enough, when my caller is in 'calling' mode, both caller and callee can still 'chat' via text. :-P

**Comment by sualko** [comment]
We found a bug in our strophejs.jingle library, which causes an issue with outgoing jingle stanzas. I hope the fix work for you, otherwise reopen this issue. Sorry for the inconvenience.

**Comment by andrey-utkin** [comment]
Thanks for heads up, will test soon.

**Comment by andrey-utkin** [comment]
It indeed works now with latest master. Thanks again!
