### ISSUE TITLE
relogin not working (with nextcloud app)

### ISSUE THREAD

**Issue by ArnY** [jsxc/jsxc#474]
I am running nextcloud 11.0.2 and ojsxc 3.1.1. When logging in nextcloud the initial jsxc login works as expected (i'm online, roster is full and I can chat) but if I disconnect, get disconnected or if autologin is disabled, reloging doesn't work. The modal window shows up, clicking on connect trigger message "Authentication failed with the chat server. Maybe the password is wrong?" but nothing's actually passed to the bosh url.

javascript console shows:

POST https://xxxxxx/index.php/apps/ojsxc/ajax/getSettings.php
(parameters are right, my userid and password are properly passed to the url)
(response : {"result":"noauth"})
[WARN] No settings provided

**Comment by sualko** [comment]
Should be fixed with https://github.com/nextcloud/jsxc.nextcloud/commit/206d092a999b563dd3f36e48e5dcd88a3493d587. Please test and verify.

**Comment by ArnY** [comment]
nextcloud/jsxc.nextcloud@206d092 does the trick, thanks!

**Comment by ArnY** [comment]
Actually, is the modal window asking for the credentials usefull there? Shouldn't the link just reconnects the user with the credentials provided by nextcloud?

**Comment by sualko** [comment]
> Shouldn't the link just reconnects the user with the credentials provided by nextcloud?

Nextcloud is not able to provide any credentials, because only the hash of them is saved. That's the reason why the user needs to enter his credentials again, but we are working on a token based solution. Stay tuned.
