### ISSUE TITLE
jsxc disconnects while loading roster when roster is huge (with nextcloud app)

### ISSUE THREAD

**Issue by ArnY** [jsxc/jsxc#475]
I'm running nextcloud 11.0.2 and ojsxc 3.1.1.

My roster is huge, around 1000 contacts. When logging in on nextcloud, jsxc connects, starts loading the roster (and firefox temporarily freezes under the load, but i'm used to that with js xmpp clients) then jsxc disconnects. 

In the firebug console:

> 
> (40)  TypeError: $div.imageplaceholder is not a function
> $div.imageplaceholder(user);
> ojsxc.j...16efb01 (line 220, col 22)
> 
> too much recursion
> jquery....16efb01 (line 2, col 28641)
> 
> DISCONNECTING: null
> jsxc.js...16efb01 (line 185)
> 
> DISCONNECTED: undefined
> jsxc.js...16efb01 (line 185)
> 
> disconnected
> jsxc.js...16efb01 (line 185)
> 
> State changed to SUSPEND
> jsxc.js...16efb01 (line 185)

**Comment by sualko** [comment]
> I guess my roster is exceptionnally large...

I agree :laughing:.

#478 could improve or even fix this and what we also observed is that loading all avatars at the beginning is a performance killer for large rosters. So this should also be changed.
