### ISSUE TITLE
can't access preferences when offline

### ISSUE THREAD

**Issue by ArnY** [jsxc/jsxc#476]
I'm running nextcloud 11.0.2 with ojsxc 3.1.1.

My roster's too big to be loaded when loging in nextcloud. I'd like to turn off jsxc's autostart or hide offline contacts, but unfortunately jsxc disconnects while loading the roster (cf #475) so the settings are not accessible and I can't do anything. Shouldn't the setting be available even though the client is not connected?

**Comment by sualko** [comment]
Yes that's right. We already talked about this and this would be a great starter issue :wink:.
