### ISSUE TITLE
Can't find ejabberd auth files for *cloud

### ISSUE THREAD

**Issue by wargreen** [jsxc/jsxc#479]
Hello,
I try to install a new ejabberd server following the wiki, but i can't find auth_ejabberd_oc.php and auth_oc_user.php in the repo.

Thank you

**Comment by ctillmann** [comment]
Hey there,

have a look [here](https://github.com/nextcloud/jsxc.nextcloud/issues/2).

Cheers

**Comment by sualko** [comment]
@ctillmann :+1:

**Comment by ctillmann** [comment]
@sualko I actually wanted to do exactly the same as @wargreen 
Is there any way to get an old file or to get it working in some way? I'd much appreciate that!
I would totally be fine with some bugs.

**Comment by sualko** [comment]
Sure: https://github.com/nextcloud/jsxc.nextcloud/tree/4ef6bd26fb661d285f86128751cce5935d918982

**Comment by ctillmann** [comment]
Excellent. Much appreciated!
