### ISSUE TITLE
Login button on Firefox 51.0.1 not working

### ISSUE THREAD

**Issue by Caliandroid** [jsxc/jsxc#481]
as soon as i activate the JavaScript XMPP Chat 3.1.1 on nextcloud 11.0.2,
the login button (of Nextcloud) does not work anymore.

I was able to log in via Chromium and deactivated the chat app, now the login button works again.

**Comment by Quix0r** [comment]
Same issue here when the plugin is enabled, if it is disabled, it works. LAst working Nextcloud version was 10. Maybe API has changed?

**Comment by sualko** [comment]
Is your bosh server working? Errors or warnings in your js console?

**Comment by Quix0r** [comment]
Yes, Bosh is working. Low on time due to employment in RL and family at home.

**Comment by Quix0r** [comment]
Please keep it longer open, people do have a RL ...

**Comment by sualko** [comment]
> Please keep it longer open, people do have a RL ...

I know, but this issue has not enough information, I can't reproduce it and was idle for 2 weeks. We have to keep the issue tracker clear, otherwise we will lose track of it. And please answer my questions:

> Errors or warnings in your js console?

See also: https://github.com/jsxc/jsxc/wiki/Contributor-Guide

**Comment by Quix0r** [comment]
Okay, I retest it now, you require some JavaScript console messages (if some are there) and maybe some network requests?

**Comment by Quix0r** [comment]
I noticed, 11.0.2 is out. I update it before I test it, okay? I'm on `stable` "branch".

**Comment by Quix0r** [comment]
Found 3 errors in console:
1:
```
ReferenceError: mozRTCPeerConnection is not defined
https://cloud.mxchange.org/apps/ojsxc/js/jsxc/lib/jsxc.dep.js?v=0013c86bfb0ee8f93deb773ad4950a8a
Line 35076
```
2:
```
ReferenceError: emojione is not defined
https://cloud.mxchange.org/apps/ojsxc/js/jsxc/jsxc.js?v=0013c86bfb0ee8f93deb773ad4950a8a
Line 2640
```
3:
```
TypeError: jsxc.options is undefined
https://cloud.mxchange.org/apps/ojsxc/js/jsxc/jsxc.js?v=0013c86bfb0ee8f93deb773ad4950a8a
Line 256
```

**Comment by Quix0r** [comment]
If I disable it with `$ ./occ app:disable ojsxc` I can login again. If this app remains enabled, the login button is grayed out.

**Comment by sualko** [comment]
I guess you disabled peerconnections, because in #471 was the same error message. The next release should fix your issue.

**Comment by Quix0r** [comment]
Okay, maybe it (WebRTC?) is disabled here due to privacy concerns? Then how can you fix it?

**Comment by sualko** [comment]
Read the issue.
