### ISSUE TITLE
[nextcloud] layout gets (partly) destroyed with ojsxc

### ISSUE THREAD

**Issue by DJCrashdummy** [jsxc/jsxc#483]
as @raimund-schluessler illustrated at https://github.com/nextcloud/tasks/pull/59#issuecomment-283470081 in nextcloud with the ojsxc-app installed, enabled and opened, the main window gets cut off when nextcloud opens a sidebar. his guess is, that ojsxc-app _overwrites some css properties_...

i can confirm this issue using Nextcloud 11.0.2.7, JavaScript XMPP Chat 3.1.1, accessed via Firefox 51.0.1 and Midori 0.5.11 on Linux- and Windows-systems. and this effect appears in several apps exact the same way...
i found also an other behavior: in the calender-app if the chat-window is open and after that the sidebar is opened to edit an entry, the main-window slides to the left, but the sidebar sticks to the right and is hidden by the ojsxc-window:
![kalender - testcloud - 2017-03-07](https://cloud.githubusercontent.com/assets/26110463/23676248/65263130-037c-11e7-9987-09aa7727706c.png)

**additional** i have to mention, that the settings-icon at the left bottom corner can't be clicked anymore with ojsxc enabled (also in several apps)! - clicking on the text works as it should, but the icon not... and this is especially bad for some apps which only have the icon.
with a bit fiddling around you can click in the no-man's-land right above the icon to access the settings.

**Comment by sualko** [comment]
Thanks for reporting. Please test and verify both fixes.

**Comment by DJCrashdummy** [comment]
thanks for responding and taking action so quickly!

since i'm new to github i'm not 100% sure that i've done everything right: i downloaded the zip from the _fix-layout_ branch, uploaded it via ftp and enabled it in nextcloud...

i'm not sure which bugs should be fixed; the only difference i noticed is that the bottom left icon is clickable, but the layout issues as mentiond in https://github.com/nextcloud/tasks/pull/59#issuecomment-283470081 and the special one in the calendar app still persist.

**Comment by sualko** [comment]
It's not that easy, but i packed you a nightly: [ojsxc-3.2.0-fixlayout.0308.tar.gz](https://github.com/jsxc/jsxc/files/828070/ojsxc-3.2.0-fixlayout.0308.tar.gz)

**Comment by DJCrashdummy** [comment]
ok... thank you very much!

some things i noticed with this nightly:
- [x] as already mentioned previously, the bottom left settings-icon is clickable.
- [ ] when the ojsxc-window is closed, the bar to trigger the ojsxc-window is placed direct over the scrollbar.
_for me it is not a big deal because i use the wheel/pad for scrolling, but in general i don't think this is a good idea. - i'm thinking more in the other direction: is the ojsxc-bar (in nextcloud) really necessary, since there is the button in the top bar?_
- [ ] when the ojsxc-window is opened, still approximately 20% of the scrollbar are overlapped.
- [ ] the general overlapping https://github.com/nextcloud/tasks/pull/59#issuecomment-283470081 still persists.
- [x] but the editing-window in the calendar-app is now moved wit the ojsxc-window! ;-)

_by the way: how do i get the nightlies with the fixes i should test, if you didn't pack a nightly for me? (just with the terminal and git or is it also possible via the website?)_

**Comment by sualko** [comment]
I will merge the pr, because on my screen it's not looking too bad:

![screenshot from 2017-03-14 12-50-00](https://cloud.githubusercontent.com/assets/2974196/23899294/e04ebc32-08b4-11e7-9b51-5445f8652d73.png)

I think with the new nc contact bar/dropdown we have to rethink our contact list anyway.
