### ISSUE TITLE
RFE: Allow control by/within groups in NextCloud

### ISSUE THREAD

**Issue by putt1ck** [jsxc/jsxc#486]
Would be really useful in some scenarios (think schools, but also can see other uses e.g. cross-organisation project teams) if access to chat, and who you can chat with, could be limited by Nextcloud group. This would include:

enabling access to the chap app based on group membership;
being able to limit chat to within a group or within and between enabled groups (including federated where/when relevant);

Latter feature possibly only available is using internal Jabber server, but limiting access to the  chat client by group possible for internal or external Jabber server.

**Comment by MarcelWaldvogel** [comment]
If it is for control, then it won't work, as users will still be able to connect to the XMPP server with other clients.

Also, I believe that several external servers have functions to limit communications. I would find that a more appropriate place.

If it is for convenience, then activating the app only for certain groups might be an option. Probably should be rather simple; pull requests welcome.

**Comment by sualko** [comment]
As Marcel said, this would only be possible for the internal server and I think there is already an issue #306  for that.
