### ISSUE TITLE
ojsxc not Nextcloud 11.0.2 compliant

### ISSUE THREAD

**Issue by gibberfishinc** [jsxc/jsxc#487]
Nextcloud 11.0.2 seems to have a few bones to pick with ojsxc 3.1.1. I'm not sure if any of these actually impact functionality.

> # sudo -u www-data php occ app:check-code ojsxc
> Analysing /opt/nextcloud/apps/ojsxc/appinfo/application.php
>  1 errors
>     line  142: == - is discouraged
> Analysing /opt/nextcloud/apps/ojsxc/ajax/getSettings.php
>  1 errors
>     line   10: OCP\JSON - Static method of deprecated class must not be called
> Analysing /opt/nextcloud/apps/ojsxc/ajax/getTurnCredentials.php
>  1 errors
>     line    4: OCP\JSON - Static method of deprecated class must not be called
> Analysing /opt/nextcloud/apps/ojsxc/ajax/setAdminSettings.php
>  2 errors
>     line    4: OCP\JSON - Static method of deprecated class must not be called
>     line   14: OC_JSON - Static method of deprecated class must not be called
> Analysing /opt/nextcloud/apps/ojsxc/ajax/setUserSettings.php
>  1 errors
>     line    3: OCP\JSON - Static method of deprecated class must not be called
> Analysing /opt/nextcloud/apps/ojsxc/ajax/getUsers.php
>  2 errors
>     line    4: OCP\JSON - Static method of deprecated class must not be called
>     line   24: OCP\Config - Static method of deprecated class must not be called
> App is not compliant
>

**Comment by sualko** [comment]
Thanks for reporting. We are aware of these issues, but they don't impact functionality. Currently we have no time to switch to the app framework, which would supersede these errors.
