### ISSUE TITLE
Firefox 52 does not need a screen sharing whitelist anymore

### ISSUE THREAD

**Issue by rugk** [jsxc/jsxc#488]
See https://wiki.mozilla.org/Screensharing

**Comment by cpresario** [comment]
Hi, I put screenMediaExtension but where is that option?

**Comment by sualko** [comment]
@rugk Thank you for this information. If we have time we will reflect this change in JSXC.

**Comment by sualko** [comment]
@cpresario this commit should fix also your issue.
