### ISSUE TITLE
Chat without owncloud login

### ISSUE THREAD

**Issue by davodego** [jsxc/jsxc#49]
English:
On owncloud login screen I take the complete JabberID (user@jabber.server.tld/resource) for login and not the Owncloud username (user). So the owncloud login fails but the XMPP app login works and the chat sidebar is visible and chat ist working.

German:
Wenn ich beim Owncloud Login statt meines Benutzernamens (user) die Komplette JabberID (user@jabber.server.tld/resource) angebe, schlägt der Onwcloud login fehlt, aber der XMMP Chat geht. Die Sidebar öffnet sich, die Kontakte werden angezeigt und Chat ist möglich.
![oc-xmmp](https://cloud.githubusercontent.com/assets/6584744/3354819/c01cba48-faa9-11e3-90d0-842bdd45879c.png)

**Comment by WMP** [comment]
I have this same after logout from owncloud.

**Comment by beccon4** [comment]
When my user changes his password then there is no way to connect to XMPP. Owncloud asks for login - but unless Owncloud and Jabber passwords are identical - login fails. I have checked "Allow User to owerwrite XMPP settings." - no avail. What is this option for whatsoever?

**Comment by sualko** [comment]
@beccon4 How is this related to this issue? Please open for every concern a separate issue.

**Comment by beccon4** [comment]
ok
