### ISSUE TITLE
Odd TURN issue.

### ISSUE THREAD

**Issue by Luticus** [jsxc/jsxc#490]
I have a turn server set up (self hosted) and when any two users try to connect up via voice/video chat it works fine showing "user <1019632348:Username>" correctly in the logs.  Oddly though when my user tries it it fails and my username appears blank in the log.  "user <>"

I am using the nextcloud jsxc app.

My question is where does it pull that username info from to submit it to the turn server?  I've scoured my database and can't figure out what's different between my account and accounts that work.  

My account is using LDAP but so are other working accounts.  As far as I know my account is the only one that doesn't work.

**Comment by sualko** [comment]
Try to clear your browser history/cache or try the private mode in your favorite browser.

**Comment by Luticus** [comment]
Seems to have worked.  Looks like it may be an issue with Vivaldi.  Firefox was fine.
