### ISSUE TITLE
feature request / suggestion - OMEMO encryption

### ISSUE THREAD

**Issue by megacar** [jsxc/jsxc#494]
Dear jsxc team,
Thank you for the great work with your web xmpp client. I'm using it integrated in owncloud.

Are you planning to support OMEMO encryption? it is supported by Conversations and ChatSecure Android and IOS clients, by Gajim PC client and so on.

It should be far superior to OTR, better for multi client scenarios etc..

thanks,
regards,
Vanja

**Comment by MarcelWaldvogel** [comment]
Yes, see #228

**Comment by sualko** [comment]
At the top is also a search field :wink:

**Comment by megacar** [comment]
We couldn’t find any code matching 'omemo' 
search is not really working

**Comment by sualko** [comment]
It's working quite good, as you can see in the following screenshot:

![screenshot from 2017-03-20 10-18-16](https://cloud.githubusercontent.com/assets/2974196/24093937/ae03997c-0d56-11e7-905b-c9826346ca95.png)
