### ISSUE TITLE
Voice channel

### ISSUE THREAD

**Issue by Majaspic** [jsxc/jsxc#495]
Hi

Why not making a voice channel system like Discord?

**Comment by sualko** [comment]
No time, no money :wink:. See also #6

**Comment by sualko** [comment]
cc @72Zn

**Comment by konzeptplus-gmbh** [comment]
@sualko any chance you will reconsider this? I would found this. :-)

**Comment by sualko** [comment]
Did you mean "fund"? I am currently busy, but if you like you can send an offer to klaus@jsxc.org.
