### ISSUE TITLE
Audio chat date

### ISSUE THREAD

**Issue by Majaspic** [jsxc/jsxc#499]
Hi

Do you have a date or a month for audio chat release ?

Thanks

**Comment by MarcelWaldvogel** [comment]
No, but patches are always welcome.
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jsxc/jsxc
> ","title":"jsxc/jsxc","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jsxc/jsxc"}},"updates":{"snippets":
> [{"icon":"DESCRIPTION","message":"Audio chat date
> (#499)"}],"action":{"name":"View
> Issue","url":"https://github.com/jsxc/jsxc/issues/499"}}}
