### ISSUE TITLE
[XEP-0106] Unallowed chars in username

### ISSUE THREAD

**Issue by Broatcast** [jsxc/jsxc#501]
It's a known problem that unallowed chars in the username like a space for example will crash the functionaltiy of jsxc, i looked a lot over the source but i'am a php dev and dont have any plan about js.

Meanwhile many app's exist where are chars allowed in user/login name which are not allowed in the xmpp protocol. But it's ontemporary and not able to disallow or modify this apps to use this chars. Like boards, blogs and other webapps.
For me i'am currently dev a plugin for integrate jsxc into [MyBB](https://mybb.com) the plugin work great and i love the idea behind making xmpp great again and use it for webchats in apps.

So i looked into the code of jsxc (very clean by the way ;)) and try to find a global point for the username to do something like a replace. But my js skills like i sayed are realy crap. Then i thinked about how to solve this problem globaly.

My idea at this point is to create an option with a char that get placed where the unallowed chars are, this give the ability for any user/admin who integrate jsxc in his app to decide for his own to replace all bad chars with an "_" for example.

This option should be optional settable in the init, for example:

```js
var settings = {
    xmpp: {
      url: '/http-bind/',
      domain: 'example.com',
      resource: 'example.com',
      overwrite: true,
      onlogin: true,
      replacebadchars: '_'
    }
  };
```

Now jsxc know to replace all unallowed/bad chars with the '_'.

I hope you understand my suggestion. And sry for my bad english.

**Comment by sualko** [comment]
[XEP-0106](https://xmpp.org/extensions/xep-0106.html) is probably the more standard way and there is already a function in the underlying XMPP lib for that (`Strophe.escapeNode`). While we are using the bare jid as identifier at multiple points, I am afraid that this would lead to side effects. I will consider this for 4.0.
