### ISSUE TITLE
Messages sent doesn't arrive with IMAP authentification 

### ISSUE THREAD

**Issue by TheNextFlo** [jsxc/jsxc#503]
Hello,
I am using jsxc Version 3.1.1 on a Nextcloud Installation with the Internal xmpp Server. The user Authentication by Nextcloud is over IMAP. So my issue is when I am sending a Message from "Test1@example.de" to "Test2@example.de" and the other way it doesn't arrive. And I can't find any Error message about this in the Logs. The only thing I have found was in the MySQL Database:

 | 410 | Test1@example.de | Test2 | <message to="Test2" from="Test1@example.de" type="chat" xmlns="jabber:client" id="58d3e4500e6d1-msg"><composing xmlns="http://jabber.org/protocol/chatstates"></composing></message>
                          |
| 411 | Test1@example.de | Test2 | <message to="Test2" from="Test1@example.de" type="chat" xmlns="jabber:client" id="58d3e450ec385-msg"><body xmlns="jabber:client">sdfsdfsdfs</body><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active></message>            |
| 412 | Test1@example.de | Test2 | <message to="Test2" from="Test1@example.de" type="chat" xmlns="jabber:client" id="58d3e45a361b7-msg"><body xmlns="jabber:client">dfdsfsdf</body><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active></message>              |
| 413 | Test2@example.de | Test1 | <message to="Test1" from="Test2@example.de" type="chat" xmlns="jabber:client" id="58d3e45a363f3-msg"><body xmlns="jabber:client">fsdfsdf</body><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active></message>               |

How could this issue be fixed?
Greetings TheNextFlo

**Comment by sualko** [comment]
cc @LEDfan

**Comment by TheNextFlo** [comment]
Ok, i'm sorry it wasn't a bug. The IMAP authentication how i used is just uncompatible with the XMPP RFC 6122 definition.

**Comment by MarcelWaldvogel** [comment]
Can you be more specific? Maybe we can deal with this somehow? (Or, at least, others running into the same problem will know how to deal with it.)

**Comment by sualko** [comment]
I assume we can close this issue. If you could be more specific that would be great.

**Comment by TheNextFlo** [comment]
So over IMAP Authentication every user has as exanple the user name: name@Web.de and can log on with his email password. 
But in the xmpp adress creation the adress of the server will be extended at the name with a @ between.
So in my example it would be "name@Web.de@server". So in this case the xmpp server will filter the server adress through a regEXP in Javascript out and as sign for that it is used the @ but in my case it gives two @. The second @ with the adress of the destination server is ignored and only the first @ is be used but under the adress of the first @ ( in my case web.de) is not a xmpp server running. So my reflection was to write a regEXP which can see both @ and organize the first @ as name and the second as server adress.
But i am not sure i that could function or is the right way to solve this problem.
