### ISSUE TITLE
[nextcloud] New users can't add contacts

### ISSUE THREAD

**Issue by wargreen** [jsxc/jsxc#506]
Hi,
with 3.2.0 beta in nextcloud, new users can't add any contacts.
The extauth.log file show "2017-04-06 16:28:54,639 INFO: Receive operation isuser" at each try, but nothing more happen in any logs.

Old users can add theses users and tchat.

**Comment by sualko** [comment]
I copied your issue to the corresponding repo. Thanks for reporting.
