### ISSUE TITLE
MUC Configure and Ejabberd

### ISSUE THREAD

**Issue by Digonly** [jsxc/jsxc#508]
The combination of ejabberd 17.03 with the nextcloud app caused an error when trying to configure a created multi-user chatroom.
Below a super tiny fix in this file: [jsxc.lib.muc.js](https://github.com/jsxc/jsxc/blob/81d84a02b9624e09885d1521526a30e27786c6b1/src/jsxc.lib.muc.js#L1576)

Change line 1576:
`for (j = 0; j < self.values; j++) {`
to:
`for (j = 0; j < self.values.length; j++) {`

`self.values` was an array in my case so correctly looping over it requires the length instead of the array itself.

I read the contributor guide, but could not find the develop branch.
Therefore a link to the commit containing this fix: [click me!](https://github.com/Digonly/jsxc/commit/fdc570b6ee8e69576159737c960021419bcaf5cf).

Should I make a pull request on another branch?

**Comment by MarcelWaldvogel** [comment]
Please submit a pull request on the master branch.
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jsxc/jsxc
> ","title":"jsxc/jsxc","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jsxc/jsxc"}},"updates":{"snippets":
> [{"icon":"DESCRIPTION","message":"MUC Configure and Ejabberd
> (#508)"}],"action":{"name":"View
> Issue","url":"https://github.com/jsxc/jsxc/issues/508"}}}
