### ISSUE TITLE
Change from localStorage to sessionStorage in jsxc.lib.storage.js

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#512]
Thought.. regarding possibly moving from localStorage to sessionStorage as to purge on navigating away from domain or on window close. This could assist in a more securely disposing of message history on session close.

Thanks,
Skyfox675

**Comment by sualko** [comment]
The actually change would be easy, but I would prefer to give the user the change to choose between booth storages. Probably a "I am at a public computer" button would be nice. Maybe this goes into the 4.x branch.
