### ISSUE TITLE
ojsxc / nextcloud: connection issues to bosh server prevent user login

### ISSUE THREAD

**Issue by joergmschulz** [jsxc/jsxc#516]
Using ojsxc on nextcloud can prevent user login when the configured BOSH server is not available:

How to reproduce: 
- create a working configuration
- prevent a connection to the BOSH server
- try to login
result: endless spinning wheel. User can only login when he clicks on the barely visible 'login without Chat' text.

As soon as there is a connection to the BOSH server it mostly works; in Safari, the browser cache sometimes prevents a login for longer times afterwards.

This is reproducible with all browsers in my reach (windows; Safari; chrome; Iridium; firefox).

**Comment by sualko** [comment]
Thanks for reporting.

**Comment by joergmschulz** [comment]
have installed the fix, but / sorry to say: the spinning wheel still spins endlessly until... the xmpp server is available again.

**Comment by sualko** [comment]
Did you ran the build script? Because all files in `src/` are concatenated in one file.

**Comment by sualko** [comment]
Sorry, my fault. This is indeed not true for the `ojsxc.js` script.

**Comment by joergmschulz** [comment]
Pretty sure I have the most recent version on my local test env now; compiled the stuff (yes, downloaded all that npm; I get used to that once). The behaviour is better: When the passwords don't match or the chat serve denies login, login to nextcloud works. But when chat is down, login doesn't work at all (NC 11.0.3).
Console displays: Failed to load resource: the server responded with a status of 503 (Service Unavailable) for some minutes. When I restart the chat server the login process continues.

**Comment by sualko** [comment]
I could reproduce your issue including the 503, but with the fix the login continues. Can you add a `console.log` inside the log function to see if this gets called and the if condition match?

**Comment by joergmschulz** [comment]
Ups, this would mean I have to code PHP ? That’s not my line of capabilities. Do you have a suggestion what to add where?

**Comment by sualko** [comment]
No php, just javascript. Extend the fix like this and post the javascript log:

```
...
Strophe.log = function(level, msg) {
                console.log(level, msg);
                if (level === 3 && /^request id/.test(msg)) {
...
```

Thanks for your effort.

**Comment by joergmschulz** [comment]
:-( with this fix, it works. Good. But,  at some place, the console log is cleared and the log output is not visible.
> 
> console.log(level, msg);
>

**Comment by sualko** [comment]
Sorry, I don't get it. This "fix" was no fix, it was just some debug output. I will release a new beta until Monday and it would be great if you could test this new build at time.

**Comment by joergmschulz** [comment]
Great, I look forward to the new beta and will test it as soon as I see it. Maybe I did something wrong in the instattlation in the fist attempt.
