### ISSUE TITLE
Video Chat issue

### ISSUE THREAD

**Issue by karu321** [jsxc/jsxc#518]
We are using 	v3.2.0-beta.1 and using example folder for chat . Chat is runnig perfectly but video not running and i want to integrate jsxc with wordpress and using ejabberd server for chating purpose ..

**Comment by sualko** [comment]
I need some information about your setup (LAN, WAN, NAT, config, etc.) and error messages e.g. in your javascript console. Btw. there is a how to for wordpress in our [wiki](https://github.com/jsxc/jsxc/wiki/Install-jsxc-(WordPress)).

**Comment by karu321** [comment]
@sualko my server is on public IP (direct) and config file is below attached ..
[ejabberd.pdf](https://github.com/jsxc/jsxc/files/963999/ejabberd.pdf)

**Comment by sualko** [comment]
Sorry, you don't provide enough information and your archive is corrupt. Why do you submit an archive anyway?

**Comment by karu321** [comment]
Video is possible from ejabberd  server or not ?? @sualko PLz Hlp me !!!

**Comment by DanScharon** [comment]
@karu321 video is completely independent from server side (i.e. ejabberd)
