### ISSUE TITLE
Add nc contact menu integration

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#519]
see nextcloud/server#3233, example integration nextcloud/contacts#173

**Comment by DanScharon** [comment]
unfortunately, when the login part differs from the UUID (e.g. when using LDAP with a differing login attribute) the chat bubble still uses the UUID as local part within the JID, despite enabling "Prefer mail address to loginName@xmppDomain" in the jsxc admin settings. Could you have a look into that?
