### ISSUE TITLE
Shared roster - reload on new user

### ISSUE THREAD

**Issue by ph4r05** [jsxc/jsxc#520]
Hello! We would like to propose a minor feature request. 

Our use-case:
- We use ejabberd as an external XMPP server for OJSXC. 
- ejabberd uses external auth plugin you wrote - NextCloud is the auth backend (thanks for the plugin btw!)
- our goal is each NextCloud user having all other NextCloud users in the roster included automatically. Once new user is added to NextCloud, he should appear in everybody's roster immediately. We use mod_shared_roster for this.
- Mod shared roster is using `@all@, @online@` variables. 

The problem is once a new NextCloud user appears (lets call him David), ejabberd/mod_shared_roster does not send roster update to the connected clients so connected client cannot see the new NextCloud user in their rosters. They need to re-login to fetch the new roster. After that they can see David because share roster is "recomputed" on roster query.

But we noticed ejabberd sends David's presence notification to the client even though the roster update is not sent. 

It would be great if jsxc has an option which would allow roster reload / query the roster when a presence notification is received for somebody who is currently not in the roster.

(Another alternatives we see is to modify mod_shared_roster (erlang, complicated) to push the change)

Thanks for opinion!

**Comment by sualko** [comment]
Sounds more like a bug in the shared roster module. I am sorry, but we will not change the behavior of jsxc, because it would be not standard conform. If you open a issue at ejabberd, it would be super cool if you could post here a link to it.

Btw. it would be awesome to have a module which would pull those groups from nextcloud. Any volunteers :wink:?

**Comment by ph4r05** [comment]
I see, implementing this on the client side may sound a bit non-standard. 

Personally I would be more than happy if this gets fixed on the server side, it would be much cleaner by design and it would work also with another XMPP clients. 

I submitted an issue to ejabberd:
https://github.com/processone/ejabberd/issues/1706

If ejabberd community won't fix this I think I will still go with the client side modification rather than messing with erlang server code :)

Thanks for the reply!
