### ISSUE TITLE
Hide disconnected users

### ISSUE THREAD

**Issue by Jacq** [jsxc/jsxc#522]
It seems that hiding disconnected users is not working.
Css class toggle is ok but the css is not matching the rosteritem.
Current roster item are:
```
<li class="jsxc_rosteritem" data-bid="......" data-type="chat">
   <div class="jsxc_avatar jsxc_statusIndicator jsxc_offline" data-status="offline" ...
   ...
   ...
</li>
```

So the jsxc_rosteritem is not hide with the css:
```
  #jsxc_buddylist.jsxc_hideOffline .jsxc_rosteritem[data-status='offline'] {
    display: none; }
```
as data-status="offline" is never a part of jsxc_rosteritem but of its div child. data-status should be added to li parent items instead of div.
Cheers

**Comment by sualko** [comment]
Thanks for reporting, I will fix it asap.
