### ISSUE TITLE
User session not found - error code 503

### ISSUE THREAD

**Issue by smilexcasper** [jsxc/jsxc#523]
When the end user is not logged in and I try to send messages I get the error:
`Your message was not send because of an error`
![error](https://cloud.githubusercontent.com/assets/10852358/25989424/bff19c56-3704-11e7-8748-2651a74badab.png)
response /http-bind/
`<body xmlns='http://jabber.org/protocol/httpbind'><message xml:lang='en' to='abogdanov@bingo-dev.ru/181473147433257603378' from='jabberadmin@bingo-dev.ru' type='error' xmlns='jabber:client'><paused xmlns='http://jabber.org/protocol/chatstates'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>User session not found</text></error></message></body>`

**Comment by MarcelWaldvogel** [comment]
The sender or the recipient is not logged in?

**Comment by smilexcasper** [comment]
recipient

**Comment by sualko** [comment]
Do you use the external auth script for ejabberd or prosody?

**Comment by smilexcasper** [comment]
I'm using an example
https://github.com/jsxc/jsxc/tree/master/example

**Comment by sualko** [comment]
Ok, but I don't see the issue, because jsxc is just displaying the error message from your xmpp server. Please fix your xmpp server setup and reopen the issue if it still persists.

**Comment by smilexcasper** [comment]
Maybe you can tell me what I need to correct?

**Comment by sualko** [comment]
No sorry, I don't have time to fix your xmpp server setup.

**Comment by smilexcasper** [comment]
Well, is this a server error? That he writes about the fact that there is no session, when you just fill out the messages without even sending it

**Comment by smilexcasper** [comment]
How do I turn off error messages?
