### ISSUE TITLE
Doesn't work with NextClould from the official EPEL repository

### ISSUE THREAD

**Issue by adundovi** [jsxc/jsxc#524]
I prefer to install services like NextCloud/ownCloud from repositories due to a consistent update strategy, syslog and so on. I use a NextCloud package from [EPEL](https://admin.fedoraproject.org/pkgdb/package/rpms/nextcloud/).

Unfortunately, JSXC downloaded from [here](https://apps.nextcloud.com/apps/ojsxc) doesn't work with a NextCloud instance deployed in the above mentioned way. The problem lies in conflicting vendor packages:
```
2017/05/12 21:39:21 [error] 11804#11804: *5837496 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare Sabre\Uri\resolve() (previously declared in /usr/share/php/Sabre/Uri/functions.php:23) in /var/lib/nextcloud/apps/ojsxc/vendor/sabre/uri/lib/functions.php on line 92" while reading response header from upstream, client: 89.164.199.70, server: cloud.example.com, request: "GET /status.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "cloud.example.com"
```

Can you make the autoloading feature more robust to handle cases where user already has required libraries?

**Comment by sualko** [comment]
cc @LEDfan

**Comment by nirjhar** [comment]
Any luck on this? Please help.

**Comment by LEDfan** [comment]
I just had a look at this, The problem is that the EPEL package is using another autoload mechanism (a Symfony component) instead of Composer. Normally Nextcloud uses composer for it's dependencies, which this app depends on (since composer won't load a dependency twice IIRC). 

Can you test https://github.com/nextcloud/jsxc.nextcloud/pull/17 please.

**Comment by adundovi** [comment]
The fix works for me. Tnx.

As this is only a workaround, should we treat the issue as a bug in Symfony and report it there?

**Comment by nirjhar** [comment]
@adundovi can you please tell what to do? I am still stack.

**Comment by adundovi** [comment]
@nirjhar 
1. Download the addon and untar it in your addons folder:
https://github.com/nextcloud/jsxc.nextcloud/releases/download/v3.2.0-beta.2/ojsxc-3.2.0-beta.2.tar.gz
2. And replace the line
```
require_once __DIR__ ."/../vendor/autoload.php";
```
with
```
if (!class_exists("\\Sabre\\Xml\\Version")) {
    require_once __DIR__ . "/../vendor/autoload.php";
}
```
in file `appinfo/app.php` of the addon that you have just unpacked.

Or you can use git to do everything automatically if you prefer.
