### ISSUE TITLE
Http upload message sent from jsxc to Conversations app does not get received

### ISSUE THREAD

**Issue by PeterEdens** [jsxc/jsxc#526]
Send an http-upload file message from jsxc to conversations and it is not received because the body tag is not the first under the message tag.
```
<message type="chat" xmlns="jabber:client" id="1494550262068:msg" to="admin@domain" from="peter@domain/45701948953295201063820572430078852969999701042805870553"><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><a href="https://domain/chat-files/c5b0c01d2c83150b096a76694fc9305120bf1ec4/k4JHM4Y4y44wiCmTP5HOcXX2uGHiZT1nLbgJKtkT/ejabberd.yml" data-name="ejabberd.yml" data-size="16375" data-type="" xmlns="http://www.w3.org/1999/xhtml">https://domain/chat-files/c5b0c01d2c83150b096a76694fc9305120bf1ec4/k4JHM4Y4y44wiCmTP5HOcXX2uGHiZT1nLbgJKtkT/ejabberd.yml</a></body></html><request xmlns="urn:xmpp:receipts"/><active xmlns="http://jabber.org/protocol/chatstates"/></message>
```

To ensure the message is received the `<body>` tag should be before the `<html>` tag.

**Comment by sualko** [comment]
Can you post the faulty stanza?

**Comment by PeterEdens** [comment]
Sorry I forgot to add the code tags around the message, I have edited the post.

**Comment by sualko** [comment]
According to [rfc6121](https://tools.ietf.org/html/rfc6121#section-5.2), "the `<body/>` element [...] is normally included but is OPTIONAL". From my point of view this looks like a valid stanza, except that it has some [forbidden](https://xmpp.org/extensions/xep-0071.html) `data-` attributes, but those get usually just ignored by clients.

Just found [XEP-0231: Bits of Binary](https://xmpp.org/extensions/xep-0231.html) which could replace those faulty `data-` attributes. Not sure if this goes into the forthcoming release, but it will definitely find his way into jsxc.

**Comment by fancycode** [comment]
The corresponding issue in Conversations might have additional information: siacs/Conversations#2481

Would be great if the interoperability for sending files could be improved.

**Comment by sualko** [comment]
Thanks for the additional information. We will fix it in the next bug fix release.
