### ISSUE TITLE
File transfer - Could not upload file

### ISSUE THREAD

**Issue by smilexcasper** [jsxc/jsxc#527]
Which jsxc version number do you use?

> last version

    Which browser and browser version do you use?

> Firefox 53.0.2

    Do you have any browser plugins enabled?

> firebug

    Do you see any errors in your javascript console?

> "[WARN] error while uploading file to https://192.168.1.200:5443/upload/5627c20b7457729e75b7a9bebf297dfa7d641042/QEY1K1jOw3YF0AvLLg6KPMx8UbqbTe64HBwy0uEl/error.png"

Can not send file
![file](https://cloud.githubusercontent.com/assets/10852358/26061578/fe23568e-3990-11e7-874e-a4d940ec0de8.png)

Config:
    port: 5443
    module: ejabberd_http
    tls: true
    certfile: 'CERTFILE'
    request_handlers:     
      "upload": mod_http_upload    
modules:
  mod_http_upload:
    docroot: "/var/www"
    put_url: "https://192.168.1.200:5443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"

**Comment by sualko** [comment]
https://github.com/jsxc/jsxc/wiki/Contributor-Guide

Section "Report a bug".

**Comment by smilexcasper** [comment]
i edit issues

**Comment by sualko** [comment]
Any errors in your ejabberd log? Can you upload images with other clients, like conversations?

**Comment by sualko** [comment]
It's probably not working, because your browser can't validate the certificate. Try to use a domain and a valid certificate.

**Comment by ismailmohammed** [comment]
hi please help me on below issue.
while file transfer I am getting below error.
**[WARN] error while uploading file to https://mydomain:5443/upload/9f8ec7cecb62f79de8143254c128083e4e9a16f2/vLsYL4N1SpVBmhhSWEsa3wdGrKtF3L1d9qeaPMNz/matrix.PNG**
please help me on this..
thanks in advance
