### ISSUE TITLE
Send File feature in Chat room

### ISSUE THREAD

**Issue by peterhoth** [jsxc/jsxc#535]
Is there anyone looking into implementing the new Send File (http_upload) feature in MUC ?

**Comment by peterhoth** [comment]
Managed to change the jsxc.css file to get it to work: 
:

> 
> .jsxc_windowItem.jsxc_groupchat.jsxc_normal .jsxc_fingerprints, .jsxc_windowItem.jsxc_groupchat.jsxc_normal .jsxc_verification, .jsxc_windowItem.jsxc_groupchat.jsxc_normal .jsxc_transfer, .jsxc_windowItem.jsxc_groupchat.jsxc_normal .jsxc_video, .jsxc_windowItem.jsxc_groupchat.jsxc_normal .jsxc_sendFile {
>   display: 1; }
> 
> 

:

**Comment by sualko** [comment]
I think it's a bad idea to just enable the button, because it is hidden for a reason :wink:. We need to modify `src/jsxc.lib.fileTransfer.js` to force http upload. I will look into this as soon as I have time.
