### ISSUE TITLE
OJSXC chat icon disappears

### ISSUE THREAD

**Issue by Billybobjoe13245** [jsxc/jsxc#536]
Once I log into the chat, the icon disappears, but when I log out, it works.

**Comment by sualko** [comment]
We need some more information to help you. Please checkout https://github.com/jsxc/jsxc/wiki/Contributor-Guide for guidance.

**Comment by Billybobjoe13245** [comment]
I'm running on Nextcloud, Ubuntu 16.04.
Apache2. OJSXC V. 3.20

**Comment by Billybobjoe13245** [comment]
Sorry, accidentally commented that incomplete. But I use OJSXC version 3.2.0. I use chrome, latest, I'm not sure what version.

**Comment by sualko** [comment]
Sorry, you don't provide enough information to help you.

**Comment by Billybobjoe13245** [comment]
I'm in school right now, not at my computer, I tried to provide as much info as I can at the moment. I need this issue fixed, I'll provide any info you want after school.
