### ISSUE TITLE
MUC Group Chat Not Supported In The Example?

### ISSUE THREAD

**Issue by Jovxx** [jsxc/jsxc#537]
Hi, 

I just started working on jsxc to serve as a client to the MongooseIM server i have set up.

I used the available example to try and understand the workings of the program but I don't seem to be able to start or join a group chat.
![capture](https://cloud.githubusercontent.com/assets/28798332/26338837/f2a05714-3fb5-11e7-95f0-c5e3ba880068.PNG)

Is there anyway to enable MUC / Group Chat?

Any advice would be greatly appreciated.
Thank you!

**Comment by sualko** [comment]
Please check, if muc is supported by and enabled on your xmpp server.

**Comment by Jovxx** [comment]
Yup it has been enabled and I have tested it using Pidgin and Jabber

**Comment by sualko** [comment]
Please clear your local storage (`localStorage.clear()` in your js console) and enable [debugging](https://github.com/jsxc/jsxc/wiki/Debugging), afterwards try again and what for errors or other useful information in your js console.

**Comment by Jovxx** [comment]
I have tried clearing local storage and reloading but doing so results in authentication failure / not being logged in and hence unable to see the chat & contacts screen at all.
![image](https://cloud.githubusercontent.com/assets/28798332/26432888/9b2587de-4131-11e7-84aa-64c5606ac9d9.png)

Without clearing local storage and reloading the page using location.reload(), I got this message
![image](https://cloud.githubusercontent.com/assets/28798332/26432874/8339a81c-4131-11e7-9f78-29ff47b347fa.png)

**Comment by Jovxx** [comment]
I have tried clearing local storage and reloading but doing so results in authentication failure / not being logged in and hence unable to see the chat & contacts screen at all.

![](https://cloud.githubusercontent.com/assets/28798332/26432888/9b2587de-4131-11e7-84aa-64c5606ac9d9.png)

I also tried reloading the page using location.reload() without clearing storage and got this

![](https://cloud.githubusercontent.com/assets/28798332/26432874/8339a81c-4131-11e7-9f78-29ff47b347fa.png)

**Comment by sualko** [comment]
Please preserve the log after page refresh or use the ajax/box login to get more information and post it here.

**Comment by Jovxx** [comment]
Hi! I have managed to solve the issue over the weekend. 
Thanks for your assistance!

**Comment by MarcelWaldvogel** [comment]
Could you provide a quick description of how you solved to problem, in
case anyone else runs into the same problem?
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jsxc/jsxc
> ","title":"jsxc/jsxc","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jsxc/jsxc"}},"updates":{"snippets":
> [{"icon":"PERSON","message":"@Jovxx in #537: Hi! I have managed to
> solve the issue over the weekend. \r\nThanks for your
> assistance!"}],"action":{"name":"View
> Issue","url":"https://github.com/jsxc/jsxc/issues/537#issuecomment-
> 304609423"}}}

**Comment by Jovxx** [comment]
I looked through my XMPP server's configuration again and realized the configuration for the MUC host was set to muc.localhost.
However, I was using a different host to host JSXC as I needed a host that supports Anonymous Login.

By adjusting the XMPP server's configuration (host = "muc.@HOST@") it solved the issue.
