### ISSUE TITLE
Adding Jsxc client inside own web page

### ISSUE THREAD

**Issue by rnagpure372** [jsxc/jsxc#540]
Hi 
sorry, this is right place to share my post or not?

I am new to jsxc client. I added jsxc client in our website successfully. but jsxc window show right of the corner of web page. my requirement is that the jsxc client window want inside div tag of my webpage in center position. 

 for example

`
       <html>
          <body>
            <div id="content" align="center"></div>
         </body>
     </html>
` 

but I am not able to add jsxc client window inside a div tag of my website anybody can help.
thanks in advanced

**Comment by sualko** [comment]
Did you notice the `rosterAppend` option? Just set it to `#content` and the roster (contact list) will be within your div element. Of course you probably have to adjust the css.

**Comment by rnagpure372** [comment]
Thank you very much @sualko
