### ISSUE TITLE
Gui does not appeae correctly

### ISSUE THREAD

**Issue by karanikn** [jsxc/jsxc#542]
Nextcloud 12
version 12.0.0.29
php version 7.0.15

Broswer Google Chrome Version 59.0.3071.71 (Official Build) beta (64-bit) (disabled all addons)

JavaScript Xmpp Client as Internal (Experimental)
![2017-05-26_122253](https://cloud.githubusercontent.com/assets/1959460/26488995/39cbf652-420e-11e7-8bbf-1b580dd64467.jpg)
![2017-05-26_122325](https://cloud.githubusercontent.com/assets/1959460/26488996/39cdb5e6-420e-11e7-8567-5120eafa6903.jpg)

**Comment by sualko** [comment]
Which language does your browser use? Do you see any errors in your js console?

**Comment by sualko** [comment]
I can confirm your issue with a Greek browser and will fix it asap. If you have time it would be cool if you could improve the [Greek translation](https://webtranslateit.com/en/projects/10365-jsxc/locales/en..el/strings) :wink: .

**Comment by karanikn** [comment]
Hello,
I tested it with Google Chrome Version 59.0.3071.71 (Official Build) beta (64-bit) (disabled all addons) **English version.**
Same problems with Greek Language Chrome.

I will try to help with the translation in Greek language. 
tnx

**Comment by sualko** [comment]
> I will try to help with the translation in Greek language

Thanks man, great work :+1:
