### ISSUE TITLE
Can't detect participant itself joined or not

### ISSUE THREAD

**Issue by pmehul55** [jsxc/jsxc#543]
XMPPRoom Class
open var isJoined: Bool { get }

above property always return false result while check participant itself is joined into group or not

here it is my code please help

    func getRoomObject(roomJid : String) -> XMPPRoom {
        
        let xmppRoomMemoryStorage = XMPPRoomMemoryStorage()
        let xmppJid = XMPPJID(string: roomJid)
        let xmppRoom = XMPPRoom.init(roomStorage: xmppRoomMemoryStorage, jid: xmppJid)
        xmppRoom?.activate(self.appDelegate.xmppStream)
        return xmppRoom!
    }

     let mucRoomObject = GroupChatDataController.sharedInstance.getRoomObject(roomJid: 
     rosterInfo.jid!)

    if (appDelegate.xmppStream?.isAuthenticated())! && !mucRoomObject.isJoined {
               /// Here is always condition true //   
    }

**Comment by sualko** [comment]
How is this related to jsxc?
