### ISSUE TITLE
XEP-0215 support for STUN/TURN/ICE server configuration

### ISSUE THREAD

**Issue by puuu** [jsxc/jsxc#545]
[XEP-0215](https://xmpp.org/extensions/xep-0215.html) describes how a client can discover STUN/TURN/ICE servers over XMPP.

I have running coturn with TURN REST API credential for authentication. [Here](https://github.com/andyet/otalk-server/blob/50d5d385f8d81fd133c4f880ee8873b1273ee867/mod_turncredentials/mod_turncredentials.lua) is a prosody module that provides XEP-0215 and support TURN REST API credential.

Would be nice if jsxc would support this.

I use the following javascript code in my config and it seems to work:
```javascript
(function($) {
   "use strict";
function xmpp_getTurnCrendentials() {
    var ttl = (jsxc.storage.getUserItem('iceValidity') || 0) - (new Date()).getTime();
    if (ttl > 0) {
        // credentials valid
        jsxc.xmpp.conn.jingle.setICEServers(jsxc.options.get('RTCPeerConfig').iceServers);
        window.setTimeout(xmpp_getTurnCrendentials, ttl + 500);
        return;
    }	
    jsxc.xmpp.conn.sendIQ(
        $iq({type: 'get', to: jsxc.xmpp.conn.domain})
            .c('services', {xmlns: 'urn:xmpp:extdisco:1'}).c('service', {host: 'turn.' + jsxc.xmpp.conn.domain}),
        function (res) {
	    jsxc.debug('ice servers receiving by xmpp extdisco');
            var iceServers = [];
	    var ttl = 86400;
            $(res).find('>services>service').each(function (idx, el) {
                el = $(el);
                var dict = {};
                switch (el.attr('type')) {
                case 'stun':
                case 'stuns':
                    dict.urls = el.attr('type') + ':' + el.attr('host');
                    if (el.attr('port')) {
                        dict.urls += ':' + el.attr('port');
                    }
                    iceServers.push(dict);
                    break;
                case 'turn':
                case 'turns':
                    dict.urls = el.attr('type') + ':';
                    if (el.attr('username')) {
                        dict.username = el.attr('username');
                    }
                    dict.urls += el.attr('host');
                    if (el.attr('port') && el.attr('port') != '3478') {
                        dict.urls += ':' + el.attr('port');
                    }
                    if (el.attr('transport') && el.attr('transport') != 'udp') {
                        dict.urls += '?transport=' + el.attr('transport');
                    }
                    if (el.attr('password')) {
                        dict.credential = el.attr('password');
                    }
                    if (el.attr('ttl') && el.attr('ttl') < ttl) {
                        ttl = el.attr('ttl');
                    }			
                    iceServers.push(dict);
                    break;
                }
            });
            if (iceServers[0].urls && iceServers[0].urls.length > 0) {
                jsxc.debug('ice servers received');
		
                var peerConfig = jsxc.options.get('RTCPeerConfig');
                peerConfig.iceServers = iceServers;
                jsxc.options.set('RTCPeerConfig', peerConfig);
		
                jsxc.xmpp.conn.jingle.setICEServers(iceServers);
		
                jsxc.storage.setUserItem('iceValidity', (new Date()).getTime() + 1000 * ttl);
            } else {
                jsxc.warn('No valid url found in first ice object.');
            }
        },
        function (err) {
            console.warn('getting turn credentials failed', err);
            console.warn('is mod_turncredentials or similar installed?');
        }
    );
}

$(document).ready(function() {
    $(document).on('attached.jsxc', xmpp_getTurnCrendentials);
});
}(jQuery));
```

**Comment by sualko** [comment]
That looks awesome. I wasn't aware of this cool module. If I have time I will integrate this snippet for sure. Thanks for your work.

**Comment by sualko** [comment]
Just to inform you, your proposed prosody [module](https://github.com/andyet/otalk-server/blob/50d5d385f8d81fd133c4f880ee8873b1273ee867/mod_turncredentials/mod_turncredentials.lua) doesn't announce his ability to support XEP-0215, so this is not working with my pull request. The [turncredentials module](https://hg.prosody.im/prosody-modules/file/tip/mod_turncredentials/mod_turncredentials.lua) from prosody adds `urn:xmpp:extdisco:1` as feature but doesn't allow fine grained configuration. I will see if I can get a patched version of otalk into upstream, otherwise I will create a separate repo.

Personal note: 
- https://tools.ietf.org/html/draft-uberti-behave-turn-rest-00
- https://xmpp.org/extensions/xep-0215.html

**Comment by diegobill** [comment]
I try this RTCPeerConfig TURN config but video call does not working: Issue #583

**Comment by sualko** [comment]
You find the updated module in this [mod_turncredentials.lua gist](https://gist.github.com/sualko/ab73ca6043d9101e971d7f5685a0e670). I also wrote an email to the prosody developers, so hopefully we will see this in the official source some time soon.

**Comment by skug67** [comment]
Is there an ETA for pushing this change to jsxc for SOGo (v3)?  I've been beating my head against a wall trying to get STUN/TURN configured correctly (I can't tell if I'm still supposed to be using ajax/getturncredentials.php or directly editing sjsxc.config.js -- but neither seems to be working) and figure this might help....

**Comment by sualko** [comment]
We will update jsxc for SOGo with the next stable release.

>  figure this might help....

It helps if your server supports XEP-0215.

> I can't tell if I'm still supposed to be using ajax/getturncredentials.php or directly editing sjsxc.config.js -- but neither seems to be working

Both should work. If you use tokens your should use an ajax endpoint. Btw. you can use my new [favorite site](https://test.webrtc.org) to test your STUN/TURN server.
