### ISSUE TITLE
XEP-0049 supported by Jsxc (Prosody mod_group_bookmarks ) ?

### ISSUE THREAD

**Issue by Mariick** [jsxc/jsxc#546]
Hi,
It seems that Jsxc only work with XEP-0048 for managing bookmarks, however on Prosody XMPP server i only found one plugin which do bookmarking but with XEP-0049 (private XML).

Can you confirm me if this statement is true, and if there are an alternative ?
Thanks

**Comment by sualko** [comment]
XEP-0048 just describes how to store bookmarks in pubsub, so this also works with prosody. Also check out http://prosody.im/doc/xeplist

**Comment by Mariick** [comment]
[Im not the only one complaining](https://github.com/jsxc/jsxc/issues/417) about issues with Prosody >= 0.9 and mod_group_bookmarks (autojoin rooms ) with Jsxc (works with Gajin and converse.js) , it's very painfull..

However i choose an other way to doing this, is it ok to manually join muc at each page load (it's an SPA) with this  : 
`
jsxc.muc.join(room, nickname, null, name, null, false, true);
`
Because i try and have some weird behavior (sometimes the room is not injected in jsxc's roster (not visible) but in console log i see that the room is joined (presence)).

Thanks
