### ISSUE TITLE
http upload not working / put URL can only be virtual domain (part after @ of jid)

### ISSUE THREAD

**Issue by mikerhyner** [jsxc/jsxc#548]
At least with ejabberd, http_upload is not working / has weird auto-detection behaviour, at least together with ejabberd as XMPP server. We have activated mod_http_upload, and set put_url to our jabber hostname that all virtual domains have to use. But in that case, JSXC somehow won't detect ability to use http_uload (file upload stroke trough on a offline user). When we set put_url to "https://@HOST:5443/upload", JSXC seems to detect the feature (file upload active on an offline user), gets a slot for upload, but then (obviously, as that FQDN points to the webserver of the domain) is not able to upload to that URL, "Could not upload file" is displayed within chat window.

Msgs. within browser console:

```
Send file via http upload
"slot received, start upload to https://<domain.tld>:5443/upload/dbc14916945dcfcb09581d9a887944d5aa5454f4/4seYDPJERfH15cZimOR8uxineuBQMUHLJKnTU6TS/images.jpeg"
"[WARN] error while uploading file to https://<domain.tld>:5443/upload/dbc14916945dcfcb09581d9a887944d5aa5454f4/4seYDPJERfH15cZimOR8uxineuBQMUHLJKnTU6TS/images.jpeg"
```

When using another XMPP client that supports HTTP upload, in my case Gajim with its "HttpUpload" plugin, http upload works fine with our ejabberd configuration (file will be uploaded to the jabber server, the other side gets the download link to the uploaded file, and is able to download it).

Expected behaviour: It should be possible to include jabber server FQDN within put_url as needed, and JSXC should detect that as a valid URL and thus allow for http_upload. I'm quite sure, then http upload will work, as JSXC will connect to the proper FQDN where ejabberd's http_upload module is listening on port 5443.

**Comment by mikerhyner** [comment]
Supplement: Even if I trick the javascript by setting the hostname <domain.tld> to the IP-Address of the jabber server within local hosts file (so the script will reach the jabber server), I get the same error message.

**Comment by sualko** [comment]
Probably an issue with the cors header. Checkout https://github.com/jsxc/jsxc/wiki/File-transfer, specially the first :warning:.

**Comment by mikerhyner** [comment]
Tried to work-around this by using apache mod_proxy to set the Allow-Origin Header (because ejabber'd won't in our situation). Set the following within virtual host config (as you proposed within wiki):
        <Location /upload/>
           # Allow cross site requests
           Header always set Access-Control-Allow-Origin "*"
           Header always set Access-Control-Allow-Headers "Content-Type"
           Header always set Access-Control-Allow-Methods "OPTIONS, PUT, GET"
           RewriteEngine On
           # modify status code of preflight request
           RewriteCond %{REQUEST_METHOD} OPTIONS
           RewriteRule ^(.*)$ $1 [R=200,L]
        </Location>

But this also results in an error situation:
`[WARN] The xmpp server responded with an error of the type "cancel"`

**Comment by sualko** [comment]
> as you proposed within wiki

This was proposed for prosody, so you have to adjust this to your setup. If you find a nice solution, it would be great if you could update the wiki page.

**Comment by mikerhyner** [comment]
I will if we really could that make to work..

**Comment by mikerhyner** [comment]
I have the following within ejabberd.log:
`<body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' from='upload.konzeptplus.ch' to='mike@konzeptplus.ch/19978751982639386801496918411751209' type='error' id='ecc68318-58ac-4b6f-892d-176e0b3f559b:sendIQ'><request xmlns='urn:xmpp:http:upload'><filename>Wi-Fi Logo-50.png</filename><size>1163</size></request><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>No s2s connection found</text></error></iq></body>
`
But no clue why...
