### ISSUE TITLE
Multi tabs - upload in one of them, attachment not sync in others ( fix proposal )

### ISSUE THREAD

**Issue by Mariick** [jsxc/jsxc#549]
When you have several tabs opened and upload a file in one of them, the others get stuck with a loading message.
This behavior seems happen because of the `history = null;` at the begining of method `jsxc.Message.prototype.save`, (to avoid message duplicate or useless reprocessing in slaves ?), to solve this i simply add a property `uploadImg:true` in the message descriptor created in the function `jsxc.fileTransfer.fileSelected`, so in `jsxc.Message.prototype.save` i simply check if this variable exist before set to null history :  
```
if(typeof this.uploadImg == "undefined")
    history = null;
```

**Comment by sualko** [comment]
Sorry, I can't reproduce your issue. What do you mean with "get stuck"? Can you post a screenshot, or any messages in your js console?
