### ISSUE TITLE
"Room_creation" dialogue broken in nextcoud app

### ISSUE THREAD

**Issue by rev138** [jsxc/jsxc#552]
I have ojsxc 3.2.1 running in Nextcloud 12.0.0, backed by ejabberd. When I create a new MUC room, I'm presented with a "Room_creation" dialogue asking if I want to change the default configuration. The "Change" button does nothing. The "Default" button brings up the settings form, but it doesn't seem to apply any changes.

It would seem to me that "Change" should bring up the settings form, and "Default" should bypass this and create the room with the default settings.

![screenshot from 2017-06-12 09-14-38](https://user-images.githubusercontent.com/1538633/27035777-969d8dba-4f50-11e7-926a-e337e72c88b9.png)

**Comment by sualko** [comment]
> It would seem to me that "Change" should bring up the settings form, and "Default" should bypass this and create the room with the default settings.

That's right. I will have a look at it.

**Comment by sualko** [comment]
It was a classic copy+paste error. Thanks for reporting.
