### ISSUE TITLE
Integrate jsxc without loginform

### ISSUE THREAD

**Issue by rheman** [jsxc/jsxc#554]
Hi every. 
I really apprecitate you app. You did great and amazing  job.
I would like to integrate you app to my existing web application without login form; thus I want to set every setting in the source.
I am using the following code in my index.html but the user is still not connected to the chat and I dont know what's wrong.
Could someone help me ??

```
jsxc.init({
      
      root: '/jsxc/',
      displayRosterMinimized: function() {
         return true;
      },
      loginForm: {
         enable: false
      },
      xmpp: {
         url: 'https://10.22.1.124:5280/http-bind/',
         domain: 'esfam.auf.org',
         overwrite: true
      }
   });
  
  var username = 'puewe';
  var password = 'pessek12';

  var jid = username + '@esfam.auf.org';
  jsxc.start(jid , password);
```

**Comment by sualko** [comment]
Please see https://github.com/jsxc/jsxc/wiki/Contributor-Guide#report-a-bug and answer the relevant questions.

**Comment by rheman** [comment]
Thanks a lot ...

**Comment by vannysaini** [comment]
Hi, i have checked ur code, its working but problem is that, at first time its not show rosterlist, but when i click on again or refresh this page then roster list will show. i think you have to call this fucntion on any event trigger. if you find any other solution then let me  know too.

**Comment by rheman** [comment]
Hi vannysaini
I am still looking for a solution. Please how can I call my function on any event trigger ??
Best regard

**Comment by vannysaini** [comment]
Hi rheman, 
 just remove this line in your function:
displayRosterMinimized: function() {
         return true;
 }

it will show open window by default.
see below code:
jsxc.init({
      
      root: '/jsxc.example/jsxc',
	  logoutElement: $('#logout'),
      loginForm: {
         enable: false
      },
	  rosterAppend: 'body',
      xmpp: {
         url: '/xmpp-httpbind/',
         domain: 'localhost',
         overwrite: true
      }
   });
  
  var username = 'asmita';
  var password = 'asmita';

  var jid = username + '@localhost';
  jsxc.start(jid , password);

now it will work fine.

**Comment by rhemandaddy** [comment]
Thanks a lot

**Comment by vannysaini** [comment]
welcome. now please close this issue.

**Comment by rhemandaddy** [comment]
Hi vannysaini
I am trying to integrate the chat client to my web site. But I have the following javascript error 

ReferenceError: Strophe is not defined
 /mod/jsxc_chat/jsxc/lib/jsxc.dep.js:5519
ReferenceError: emojione is not defined
 /mod/jsxc_chat/jsxc/jsxc.min.js:14

Can you know what's wrong with my source code ??

**Comment by sualko** [comment]
As it seems that this issue is resolved, I close it.

**Comment by vannysaini** [comment]
please check your code properly, because i have also intergrate now, its working fine.
