### ISSUE TITLE
STUN server not used on filetransfer

### ISSUE THREAD

**Issue by mikerhyner** [jsxc/jsxc#555]
When trying to transfer a file, and no HTTP file transfer is possible, a STUN server won't be used when clients are on different networks (not the same LAN). When clients are on the same network, transfer works. Peer I sen't a file to (receiving side) only sees an incoming file event, but cannot download ifile sent. On sending side, get the message within JS console:
ICE failed, add a STUN server and see about:webrtc for more details

When I go to "about:webrtc" on sending side, below ICE statistics there's only:
```
192.168.101.212:35978/udp(host)	10.128.160.30:39466/udp(host)	failed	9115005270282354000		
192.168.101.212:35978/udp(host)	194.230.159.138:39466/udp(serverreflexive)	failed	7241540810645045000	

```
And I can't see any stun server involved and within protocol section.

But the interesting thing is, that when using video chat function with the same peer (not on the same network), STUN will be used and communication works perfectly!

Within "about:webrtc", I got this below ICE statistics:
```
Lokaler Kandidat Externer Kandidat ICE-Status Priorität Nominiert Ausgewählt
192.168.101.229:60634/udp(host) 10.128.160.30:48319/udp(host) failed 9115005270282354000
192.168.101.229:60634/udp(host) 194.230.159.138:48319/udp(serverreflexive) inprogress 7241540810645045000
213.213.163.30:60634/udp(serverreflexive) 194.230.159.138:48319/udp(serverreflexive) succeeded 7241540809772646000 true true
					10.128.160.30:9/tcp(host) 
```

And within protocol section there can be seen one of the configured STUN server involved:
STUN-CLIENT(n7z6|IP4:213.213.163.30:60634/UDP|IP4:194.230.159.138:48319/UDP(srflx(IP4:192.168.101.229:60634/UDP|stun.l.google.com:19302)|a=candidate:1871324864 1 UDP 1686052607 194.230.159.138 48319 typ srflx raddr 10.128.160.30 rport 48319 generation 0 )): Received response; processing

Note: I'm using jsxc roundcube plugin (which is on version 3.0.1 only), and this release seems not to have implemented httpUpload functionality yet, so I'm forced to use WebRTC method for filetransfer there. But also on the most current build 3.2.1, when httpUpload is configurative turned off or not available on xmpp server, the same problem as described persists.

Can you shed some light on that or tell me what I need to configure that STUN/TURN servers will also be used for FileTransfers? 

Thank you in advance & greets
Mike Rhyner / konzeptplus GmbH

**Comment by sualko** [comment]
Thanks for reporting and the detailed information. I will have a look at this.

**Comment by sualko** [comment]
I opened upstream a pull request for this: https://github.com/otalk/jingle.js/pull/36
