### ISSUE TITLE
in one to one chat, one user get disconnect after 5 min

### ISSUE THREAD

**Issue by vannysaini** [jsxc/jsxc#557]
Hi,

is anyone face this type of problem, in one to one chat, one user get disconnect after 5 min.
please provide me solution.

**Comment by sualko** [comment]
> is anyone face this type of problem

No. Please check your server logs and configuration.

**Comment by vannysaini** [comment]
Hello Sir,

is it possible i have installed openfire on different domain and my website
files are working on different domain. is they both can communicate?

*my openfire server is on: *http://185.37.226.102:9090/
*my website in which i want to use chat application that is on this server:*

http://suffitechh.com/weflirts

**Comment by sualko** [comment]
>  is they both can communicate?

Should be no problem.

**Comment by vannysaini** [comment]
actually sir, when i m  register new user on my website, i m also register
to openfire, but at that time new user not get register on openfire. my url
is:

http://server.quizo.net:9090/plugins/restapi/v1/users/ravisaini.

 http://185.37.226.102 <http://185.37.226.102:9090/>
:9090/plugins/restapi/v1/users/ravisaini.

i have tried with ip as well as domain name  but now work:

**Comment by sualko** [comment]
Please try to get your work done by your own. I have to time and don't want to fix your work assignment.
