### ISSUE TITLE
add buddy into his rosterlist automatically

### ISSUE THREAD

**Issue by vannysaini** [jsxc/jsxc#558]
Hi Everyone,

sorry  i dont know why to put my question, so i m asking here, is anyone can tell me how to add buddy into rosterlist automatically. i have a website like facebook and i want my user friends is added automatically into his roster list when he is doing chatting. but i dont know what code should i need to write to add buddies into his roster list. can anyone help me? it will be very thankful.

**Comment by MarcelWaldvogel** [comment]
If you use an external XMPP server (recommended), it probably has a "shared roster" function. That should solve your problem.

**Comment by vannysaini** [comment]
will u pls tell me which one external XMPP server, i should used?

**Comment by sualko** [comment]
> Please try to get your work done by your own. I have to time and don't want to fix your work assignment.

**Comment by sualko** [comment]
https://stackoverflow.com/questions/11360759/efficient-external-rostering-with-mysql-and-ejabberd

**Comment by vannysaini** [comment]
Hi, i m trying to work done by myself, but if i get some issues or problems that i can discusses on forms.. if you don't want to answer my questions just leave it, not completion sir.
