### ISSUE TITLE
ReferenceError: Strophe is not defined

### ISSUE THREAD

**Issue by rhemandaddy** [jsxc/jsxc#561]
Hi 
I am trying to integrate the jsxc to my web site. But I have the following javascript error

ReferenceError: Strophe is not defined
/mod/jsxc_chat/jsxc/lib/jsxc.dep.js:5519
ReferenceError: emojione is not defined
/mod/jsxc_chat/jsxc/jsxc.min.js:14

Can you know what's wrong with my source code ??

**Comment by sualko** [comment]
You probably built your own version and forgot to install all dependencies. This could be done by executing

```
git submodule update --init
npm install
bower install
```

or 

```
make
```

**Comment by rhemandaddy** [comment]
Hi.
I did what you told, and after running make I have the following errors:
git submodule update --init
npm install
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> iltorb@1.3.1 install /home/pessek/Documents/jsxc/node_modules/iltorb
> node-pre-gyp install --fallback-to-build

/usr/bin/env: ‘node’: No such file or directory
npm WARN install:iltorb@1.3.1 iltorb@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:iltorb@1.3.1 spawn ENOENT

> node-sass@4.5.2 install /home/pessek/Documents/jsxc/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN grunt-html-convert@0.0.2 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-prettysass@0.2.3 requires a peer of grunt@~0.4.0 but none was installed.
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.5.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.5.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pessek/Documents/jsxc/npm-debug.log
Makefile:4: recipe for target 'install' failed
make: *** [install] Error 1

I am working under ubuntu 16.04.2

**Comment by sualko** [comment]
[Fix](https://stackoverflow.com/questions/30281057/node-forever-usr-bin-env-node-no-such-file-or-directory) your node installation or use the packed version from [releases](https://github.com/jsxc/jsxc/releases) or the `build` folder.
