### ISSUE TITLE
Window left side

### ISSUE THREAD

**Issue by diegobill** [jsxc/jsxc#563]
Hello,

Is there a option or easy way to put the gui (chat window list, roaster, ...) in the left side (align to left too) of my app that uses jsxc?

Thank you.

**Comment by sualko** [comment]
> Is there a option or easy way

Not yet, but you could adjust the stylesheets to fit your needs.

**Comment by diegobill** [comment]
I changed this file but this was not enough:

```
git diff scss/_window.scss
diff --git a/scss/_window.scss b/scss/_window.scss
index 0afb829..8e7a156 100644
--- a/scss/_window.scss
+++ b/scss/_window.scss
@@ -1,17 +1,14 @@
 #jsxc_windowList {
     position: fixed;
     bottom: 28px;
-    right: 210px;
     left: 0;
     z-index: 50;
     transition: right 0.5s;
 
     &.jsxc_roster_hidden {
-        right: 10px;
     }
 
     @media (min-width: 768px) {
-        clip: rect(-10000px, 10000px, 30px, 30px);
     }
 
     > ul {
@@ -20,7 +17,6 @@
         margin: 0;
         position: absolute;
         bottom: 0;
-        right: 0;
         height: 44px;
         overflow: visible;
         white-space: nowrap;
@@ -138,7 +134,6 @@
     bottom: -284px;
     top: auto;
     left: 0;
-    right: 0;
     height: auto;
     background-color: $window_bg;
     z-index: 80;
```

In some situations the chat window does not align to the left.

Can you help me to adjust the stylesheets?

**Comment by sualko** [comment]
Just removing all right properties is probably not enough, I would suggest to replace them with `left`. Sadly I have no time to test this by myself.
