### ISSUE TITLE
Unable to load previous message seized when I change de browser

### ISSUE THREAD

**Issue by rheman** [jsxc/jsxc#566]
Hi everyone.
I am using the latest release of jsxc and I have a disfocntionnement.

**USE CASE.**
User demo1 uses a browser from location 1 to send messages to user demo2.
when user demo1 logout and connects from another browser, previous messages it sends to user demo2 are not loaded.

I think this behavior is not normal. But I dont know what's wrong.

Best regard.

**Comment by sualko** [comment]
Do you mean you don't see the history of exchanged messages? Supports your server mam?

**Comment by rheman** [comment]
Yes I don't see the history of exchanged messages. I am using ejabberd as server..

**Comment by sualko** [comment]
You have to enable mam support, like described in https://blog.process-one.net/ejabberd-15-06/
