### ISSUE TITLE
Question: JSXC chat windows in vertical pile?

### ISSUE THREAD

**Issue by jsxcdummy** [jsxc/jsxc#568]
Hi,
is it possible to order/slide the chat windows not horizontally but vertical?
Eg. the first chat window opens still left of the rooster but the second above the first and so on ...

If not possible - any hints, any suggestions where to change the code?

thanks.

jsxcdummy

**Comment by sualko** [comment]
> is it possible to order/slide the chat windows not horizontally but vertical?

I guess it is possible, but not supported by jsxc.

> If not possible - any hints, any suggestions where to change the code?

Should be possible with pure css. So a good starting point is the folder `scss/`.
