### ISSUE TITLE
Roster groups (external Jabber server) should be configurable in JSXC admin settings

### ISSUE THREAD

**Issue by mejo-** [jsxc/jsxc#571]
Hello,

it would be awesome if admins could configure roster groups in JSXC.

In our particular case, we'd like to list all Nextcloud users (except 'admin') in the rosters by default. Is there a way to do this?

I know that I can define roster groups in Prosody, but that's not a solution as new users are not added by default, right?

**Comment by sualko** [comment]
I think shared roster is what you are looking for. https://prosody.im/doc/modules/mod_groups

**Comment by mejo-** [comment]
To my understanding, it's not possible to list *all* users (with exceptions) using `mod_groups`, so that list would need to be maintained manually, right?

**Comment by sualko** [comment]
I guess this is right, but you could create a cron job which generates those groups for you.
