### ISSUE TITLE
No "Join Chat" option in gear icon

### ISSUE THREAD

**Issue by rainolf** [jsxc/jsxc#572]
Nextcloud 12...my xmpp server is muc capable.

I can add contact but "Join Chat" function is not present.

Please see my screenshot

Thanks

![joinchat](https://user-images.githubusercontent.com/2652556/27689205-c78bb84e-5cdd-11e7-9e9a-33cd467e2552.png)

**Comment by sualko** [comment]
I guess this is the follow up from https://help.nextcloud.com/t/no-join-chatrooms-button/14720/, so where is the requested information from our "report a bug" section?

**Comment by rainolf** [comment]
i will provide u soon...thanks

**Comment by rainolf** [comment]
Which jsxc version number do you use? -> 3.2.1
In which system do you use jsxc? nextcloud 12
Can you reproduce your issue? If yes, how? -> Yes, just making a call and verifying that a stun session isn't created.
Which browser and browser version do you use? -> Firefox 54 / OS Ubuntu (Same with Chromium)
Do you have any browser plugins enabled? -> No
Do you see any errors in your javascript console (ctrl+shift+I)? -> onaddstream is deprecated! Use peerConnection.ontrack instead.  jsxc.dep.js:34333
close dialog  jsxc.js:183:10
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.  jsxc.dep.js:14690:23
Which messages appear in your javascript console if you enable debugging? -> 
See below:

          JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
State changed to INITIATING  jsxc.js:183:10
i18next: languageChanged en  jsxc.dep.js:48154:7728
i18next: initialized Object { debug: true, initImmediate: true, ns: Array[1], defaultNS: Array[1], fallbackLng: Array[1], fallbackNS: false, whitelist: false, nonExplicitWhitelist: false, load: "all", preload: false, 19 more… }  jsxc.dep.js:48154:7728
State changed to PREVCONFOUND  jsxc.js:183:10
check master  jsxc.js:183:10
undefined  content.js:2:5
I am master.  jsxc.js:183:10
State changed to ESTABLISHING  jsxc.js:183:10
Try to attach  jsxc.js:183:10
SID: 9747d4e5-14f9-4aaa-b2e9-bfdb8800d671  jsxc.js:183:10
ATTACHED: null  jsxc.js:183:10
Discover muc service  jsxc.js:183:10
UI State changed to INITIATING  jsxc.js:183:10
discover http upload service  jsxc.js:183:10
Send presence <presence xmlns='jabber:client'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://jsxc.org/' ver='G/rfI1/RTuKm1AiGJmgrWL7dEm0='/></presence>  jsxc.js:165:13
Update file transfer icons for lboffo@debortoli.lan  jsxc.js:183:10
webrtc.initWindow  jsxc.js:183:10
Update icon lboffo@debortoli.lan  jsxc.js:165:13
UI State changed to READY  jsxc.js:183:10
DSA key loaded  jsxc.js:183:10
State changed to READY  jsxc.js:183:10
> <body rid="233382209" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
> <body rid="233382210" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168
onUserMediaSuccess  jsxc.js:183:10
media ready for outgoing call  jsxc.js:183:10
close dialog  jsxc.js:183:10
i18next::translator: missingKey en translation No_video_signal   jsxc.dep.js:48154:7728
[Webrtc] Initiate call  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Changing session state to: pending  jsxc.js:165:13
onaddstream is deprecated! Use peerConnection.ontrack instead.  jsxc.dep.js:34333
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Discovered new ICE candidate jsxc.js:165:13
> <body rid="233382211" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Discovered new ICE candidate jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: ICE end of candidates  jsxc.js:165:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
> <body rid="233382212" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
> <body rid="233382213" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
[JINGLE][log:debug] 8743c03a-4fba-4b68-b5b0-6c2db870f075: session-info  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Outgoing session is ringing  jsxc.js:165:13
[Webrtc] ringing...  jsxc.js:165:13
> <body rid="233382214" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
> <body rid="233382215" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
[JINGLE][log:debug] 8743c03a-4fba-4b68-b5b0-6c2db870f075: session-accept  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Changing session state to: active  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Stream added  jsxc.js:165:13
[Webrtc] Remote stream for session 8743c03a-4fba-4b68-b5b0-6c2db870f075 added.  jsxc.js:165:13
[Webrtc] Use remote video device.  jsxc.js:165:13
[Webrtc] No remote audio device  jsxc.js:165:13
> <body rid="233382216" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
[JINGLE][log:debug] 8743c03a-4fba-4b68-b5b0-6c2db870f075: transport-info  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Changing connection state to: connecting  jsxc.js:165:13
connection state for 8743c03a-4fba-4b68-b5b0-6c2db870f075 connecting  jsxc.js:165:13
> <body rid="233382217" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
> <body rid="233382218" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
[JINGLE][log:debug] 8743c03a-4fba-4b68-b5b0-6c2db870f075: session-terminate  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Terminating session  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Stream removed  jsxc.js:165:13
[Webrtc] Remote stream for undefined removed.  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Changing connection state to: disconnected  jsxc.js:165:13
connection state for 8743c03a-4fba-4b68-b5b0-6c2db870f075 disconnected  jsxc.js:165:13
[JINGLE][log:info] 8743c03a-4fba-4b68-b5b0-6c2db870f075: Changing session state to: ended  jsxc.js:165:13
[Webrtc] call terminated lboffo@debortoli.lan/Gabby Chat Europefailed-transport  jsxc.js:165:13
close dialog  jsxc.js:183:10
i18next::translator: missingKey en translation jingle_reason_failed-transport jingle_reason_failed-transport  jsxc.dep.js:48154:7728
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.  jsxc.dep.js:14690:23
Invalid URI. Load of media resource  failed. files
> <body rid="233382219" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">  jsxc.js:1094:13
[JINGLE][log:error] Unknown session  jsxc.js:165:13
> <body rid="233382220" xmlns="http://jabber.org/protocol/httpbind" sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671">  jsxc.js:1097:13
< <body sid="9747d4e5-14f9-4aaa-b2e9-bfdb8800d671" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">
Do you have any related entries in your XMPP server log or your host system (e.g. nextcloud, sogo, ...)? Seems not

**Comment by sualko** [comment]
`XML Parsing Error: not well-formed` sounds interesting. Can you debug this further or send me some test credentials to klaus@jsxc.org?

**Comment by rainolf** [comment]
Sure,
how can i debug and give you the right info?

2017-06-30 10:28 GMT+02:00 Klaus <notifications@github.com>:

**Comment by rainolf** [comment]
do u need tets credential for my site?do you need admin one or standard
user?

2017-06-30 11:06 GMT+02:00 rainolf <rainolf@gmail.com>:

**Comment by rainolf** [comment]
done....
https://cloud-europe.dbgroup.net

Username: klaus
Password: jsxc.org

In order to login on jsxc chat
Username: klaus@dbgroup.net
Password: jsxc.org

Regards

PS:
if u can also see what "Join Chat" feature is not visible it would be great.

Thanks

2017-06-30 11:08 GMT+02:00 rainolf <rainolf@gmail.com>:

**Comment by sualko** [comment]
FYI: fixed via email. The was an error in the server config.

**Comment by rainolf** [comment]
I've save debug in firefox.

as far as i can see is something like:

STUN-CLIENT(srflx(IP4:192.168.43.184:39666/UDP|stun-europe.dbgroup.net:5349)):
Received response; processing

Unrecognized attribute: 0x802b

Unrecognized attribute: 0x802c

STUN-CLIENT(srflx(IP4:192.168.43.184:47010/UDP|stun-europe.dbgroup.net:5349)):
Received response; processing

ICE(PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#)):
peer (PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#):default)
has no stream matching stream 0-1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#)
aLevel=1

ICE(PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#)):
peer (PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#):default)
no streams with non-empty check lists

ICE(PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#)):
peer (PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#):default)
no streams with pre-answer requests

ICE(PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#)):
peer (PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#):default)
no checks to start

ICE-PEER(PC:1498820713719191 (id=886 url=
https://cloud-europe.dbgroup.net/index.php/apps/files/?dir=/&fileid=337#):default)/CAND-PAIR(Ff9y):
setting pair to state FROZEN: Ff9y|IP4:
192.168.43.184:39666/UDP|IP4:172.20.4.53:60810/UDP(host(IP4:192.168.43.184:39666/UDP)|a=candidate:0
1 UDP 2122252543 172.20.4.53 60810 typ host generation 0 )


Attached log.

Do u see any error on client side?Because seems that STUN has been
contacted....




2017-06-30 13:01 GMT+02:00 Klaus <notifications@github.com>:

**Comment by Skrappjaw** [comment]
How was this fixed? You said it was a config file issue. I'm having the same problems.

**Comment by sualko** [comment]
If I remember correctly the muc service was configured correctly. Please try muc with another xmpp client.
