### ISSUE TITLE
Manually change language in settings?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#573]
Would be nice to have an option to manually change the language in the settings.

User case scenario:
Log in to your nextcloud from a public computer during holidays. Browser settings are a foreign language you can't understand thus chat will be difficult to use. Right now, there seems to be no way to prevent language switching.

An admin option to prevent language switching in general and just allow english might be a nice-to-have feature as well.

**Comment by MarcelWaldvogel** [comment]
You mean a configuration option where the encompassing web site may
tell the JSXC plugin which languages to use (instead of the browser
language autodetection)?

**Comment by poVoq** [comment]
Yes that could also be an option, but I was rather thinking of a simple drop-down menu where you can select on of the available languages. Of course it would have to be easy to find so that even if the interface is in a different language one can easily navigate to the setting and change it.

**Comment by panpansh** [comment]
Hey, we can force it to use english language ?
Best regards.

**Comment by sualko** [comment]
> Hey, we can force it to use english language on 3.4 ?

Sure, just pass the following options to `jsxc.init`:

```
/** Default language */
defaultLang: 'en',

/** auto language detection */
autoLang: false,
```
