### ISSUE TITLE
Sample configuration for Wordpress integration?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#576]
This is a nice tutorial for using JSXC in wordpress:
https://github.com/jsxc/jsxc/wiki/Install-jsxc-(WordPress)

However I am wondering if it could include some sample configurations for a typical Wordpress installation or if anyone could share their sample? I am not yet sure how exactly it is supposed to get the registered users and log-in automatically.

I have a Wordpress website that syncs its users with a Nextcloud installation (shared sql_auth DB) with JSXC integrated (not yet 100% working but almost there). So I assume it would be nice if the same XMPP chat could also be used by the registered users when visiting the Wordpress site.

Thanks a lot!

**Comment by MarcelWaldvogel** [comment]
As you also have a Nextcloud backend, I would suggest having the XMPP server using [XMPP Cloud Auth](https://github.com/jsxc/xmpp-cloud-auth/), which comes with [full-fledged installation instructions](https://github.com/jsxc/xmpp-cloud-auth/wiki). If there are any WordPress questions that you could answer or that would need updating to get things running more smoothly for other users, please let us know!

**Comment by poVoq** [comment]
Yes that is what I am trying to set up (almost there, will post an issue with the remaining problem on the XMPP Cloud Auth repo). The problem is that I don't know much on Wordpress user interaction and the above tutorial isn't that clear on it either. So an example of an actually working configuration would be nice to have as reference.
