### ISSUE TITLE
Does not recognize self in MUC

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#577]
If you are joining a MUC with the JSXC internal and an external XMPP client the same time (but the same XMPP account) only the messages from the JSXC client are shown on the right side as "self".

This is not a big issue, but probably a bit confusing as your messages look like someone else wrote them on first glance.

**Comment by sualko** [comment]
If you join a semi-anonymous room two times, there is no way to detect that you are the same user, because your jid is not broadcasted. So this is a protocol and no jsxc issue.

**Comment by Ppjet6** [comment]
It can be done if one uses [MSN](https://wiki.xmpp.org/web/Multi-Session_Nicks), if not, too bad for the user. And this is only an issue in semi-anonymous MUCs
