### ISSUE TITLE
Support extensionless screenshaing in Firefox 52+

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#579]
See: https://wiki.mozilla.org/Screensharing

Looks like an extension isn't needed anylonger and in fact the sample code linked uses a deprechiated extension format that can not be used anymore.

**Comment by sualko** [comment]
Was fixed in #488, but I think we missed to update the [wiki entry](https://github.com/jsxc/jsxc/wiki/Screen-sharing).
