### ISSUE TITLE
Somewhat Slack like MUC interface (possible code inside)?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#582]
There are some website XMPP muc chats that are somewhat Slack/advanced IRC like (Candy/Kaiwa etc.), but none of them seems to be in really active development or working as nicely as JSXC. The muc feature of JSXC is also quite ok, but feels more like a chat-window that a modern collaboration chat.

So what if JSXC would also include a embeddable Slack like muc chat, but with all the advantages of XMPP?

As I said, the existing options are maybe not the right places to look (although adapting Kaiwa might work), rather it seems promising to look at the two modern IRC webinterfaces with the user-interface written in javascript, i.e. "The Lounge" or maybe even better "Convos". See:
https://convos.by
https://thelounge.github.io

The UI of Convos seems better adapted for JSXC and on their github page they claim that it is modular enough to also support other protocols (like XMPP?), see: https://github.com/Nordaaker/convos

Just an idea, so feel free to close this if one of the devs is interested in this :)

**Comment by sualko** [comment]
Thanks for your feature request. JSXC isn't meant as a full screen application, so I think this doesn't fit to the goals of this project. As you said there are specialized applications for this kind of thing and maybe you can bring one of them back to life. I don't mean the MUC interface is perfect and so if you like to improve it, we always appreciate pull requests :wink:.
