### ISSUE TITLE
Calling from Android app: Failed to set remote answer sdp: Offer and answer descriptions m-lines are not matching. Rejecting answer.

### ISSUE THREAD

**Issue by PeterEdens** [jsxc/jsxc#585]
I am trying to call an android app I am working on from jsxc and when I send the answer I get an error from jsxc:

Failed to set remote answer sdp: Offer and answer descriptions m-lines are not matching. Rejecting answer.

The Session Description for the answer is:

v=0
o=- 1500876249205 1500876266185 IN IP4 0.0.0.0
s=-
t=0 0
a=msid-semantic: WMS *
m=audio 1 UDP/TLS/RTP/SAVPF 111 103 9 0 8 105 13 110 113 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:a8GS
a=ice-pwd:GgfdYqaOPClWN6Z8gR3oPH
a=fingerprint:sha-256 8F:45:B1:51:A5:19:D8:79:B1:0D:BD:00:38:47:EB:A2:37:15:62:21:5D:7C:7A:B5:D8:F8:E3:66:26:81:4E:3F
a=sendrecv
a=mid:audio
a=msid:ARDAMS ARDAMSa0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3286066724 cname:2gc3oCS6/i6rqJc6
a=ssrc:3286066724 msid:ARDAMS ARDAMSa0

Any help you can provide is appreciated.  I am using Chrome 59 on the PC and I saw there was a similar problem for file transfer.

**Comment by sualko** [comment]
I suggest to ask this the guys from https://github.com/otalk/jingle.js/
