### ISSUE TITLE
Multiple Users in one browser

### ISSUE THREAD

**Issue by shazvan275** [jsxc/jsxc#587]
i am working in the project where multiple user will use the same browser i need to integrate jsxc in that. so i got a problem its showing a first logged in user to all other user in same browser if i opened in other browser its working file . so how can in handle session for every user in multiple tabs of single browser

thanks in advance

sorry for my bad english

**Comment by MarcelWaldvogel** [comment]
The core of JSXC is designed such that all tabs show the same state and content. So this is not something we will be going to change.

If you just need two users, you can log in one user in a *Private browsing tab*, which is essentially a second browser instance. I am not aware of a simple way to get more virtual browsers.

As a side note: If multiple users are using the same machine at essentially the same time, probably performing the same duties, would it be an option of using a function account shared between all those users? Or on a Linux machine, have all users log in into their separate accounts, and then switching to their account with Alt-Ctrl-F1 etc.?
