### ISSUE TITLE
language is undefined when generating capability verification

### ISSUE THREAD

**Issue by SproulDog** [jsxc/jsxc#588]
### Expected behavior
The capability verification string should be configurable with a valid language member (possibly via jsxc.options)

like (at) https://xmpp.org/extensions/xep-0115.html#ver-gen-simple

### Actual behavior
'lang' is undefined when generating capability verification

The issue does not seem to pose any functional problems between two JSXC clients, but other clients may have issues validating the capability based on the identity (jitsi/smack seems to throw a capability warning as an example). I suspect this (in part) is preventing some clients from reliably discovering the features of JSXC clients.

Specifically, addIdentity: function(category, type, name, lang) does not appear to have the the lang member populated. 

example: jsxc.xmpp.conn.disco.addIdentity('client', 'web', 'JSXC');

As a result, the capability verification hash is calculated with the content 'undefined' in place of the language member.

Expanding on this ... say a jitsi client queries a chrome/windows JSXC client for capability like this:

```
<iq id="GzJDi-1199" to="pokee@example.com/wm-tchromev59.0" type="get" from="poker@example.com/jitsi-3kgbfcu" xmlns="jabber:client">
<query xmlns="http://jabber.org/protocol/disco#info" node="http://jsxc.org/#G/rfI1/RTuKm1AiGJmgrWL7dEm0="></query></iq>
(which equates to the typical chrome feature/identity set but with the identity language as 'undefined')

```
The identity portion returned from the discovery is missing the language (eg):
```
<identity category='client' type='web' name='JSXC'/> <-- no lang qualifier (but the checksum has one - albeit 'undefined')
<feature var='http://jabber.org/protocol/caps'/>
.... brevity .....
<feature var='urn:xmpp:receipts'/>
```

So, obviously the lang specified for the identity of the disco response should match the verification hash/checksum also.

or perhaps just change to this:
jsxc.xmpp.conn.disco.addIdentity('client', 'web', 'JSXC','');
:-)
### Steps to reproduce the behavior
This requires setting a breakpoint in addIdentity when a client connects/logs in.
I guess the reproduction steps are not so much relevant as much as a suggestion that the language member can be accessible/configurable and be applied to the checksum (as well as the underlying advrtised identity). 

### Environment
- **JSXC version: jsxc v3.2.1 - 2017-06-01 
- **Host system and version: JSXC Core
- **Browser vendor and version: Chrome/Any
- **Any browser plugins enabled?  N/A
- **XMPP server vendor and version: N/A (generic/client only/minor problem)
- Is your XMPP server working with other clients as expected? Yes - although we have made the server implementation accomodate it by assuming a lang qualifier of 'undefined' where identity is JSXC/BOSH.

Thanks

**Comment by sualko** [comment]
Thanks for reporting. I will add your second workaround and also open a pr in the [related lib](https://github.com/strophe/strophejs-plugin-disco).
