### ISSUE TITLE
ownCloud string not changed to Nextcloud

### ISSUE THREAD

**Issue by DiGGeR2** [jsxc/jsxc#589]
### Expected behavior
Limited functionality only: No clients besides JSXC in **Nextcloud**, no multi-user chat, no server-to-server federations.

### Actual behavior
Limited functionality only: No clients besides JSXC in **ownCloud**, no multi-user chat, no server-to-server federations.

### Steps to reproduce the behavior
1. Login with the Admin account
2. Go to "Admin" menu
3. Choose Internal and read the text

**Comment by sualko** [comment]
Thanks for reporting!
