### ISSUE TITLE
Missing app icon in the left navigator in the Admin menu

### ISSUE THREAD

**Issue by DiGGeR2** [jsxc/jsxc#590]
### Expected behavior
App Icon in Admin Menu

### Actual behavior
No app icon in Admin Menu

### Steps to reproduce the behavior
1. Login with the Admin account
2. Go to "Admin" menu
3. No icon in the left navigator

**Comment by sualko** [comment]
Fixed in https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v3.3.0-beta.1

**Comment by DiGGeR2** [comment]
Hello, wow cool thanks :)
