### ISSUE TITLE
Internet Explorer (pre-Edge) fails to load sxc v3.3.0-beta.1 (Object.assign is not available)

### ISSUE THREAD

**Issue by SproulDog** [jsxc/jsxc#593]
Some feedback for v3.3.0-beta.1 (thanks) 
### Expected behavior
In current releases, IE browsers work as expected (and even beyond) without WebRTC. ie: Chat functions work fine.
### Actual behavior
v3.3.0-beta.1 includes some additional references to Onject.assign (which is not available in IE-PreEdge). and therefore prevents JSXC from loading/functioning. As best I can tell, a small newly refactored code block has been introduced and this is causing the exception (and follow on effects).

### Steps to reproduce the behavior
1. Attempt to use the mentioned beta release with IE 11 or earlier

### Environment
- **JSXC version:  v3.3.0-beta.1 
- **Host system and version: Any (Windows 8, etc)
- **Browser vendor and version:** IE Pre-Edge
- **Any browser plugins enabled? N/A 
- **XMPP server vendor and version:* N/A 
- **Is your XMPP server working with other clients as expected? Yes

### Logs

jsxc v3.3.0-beta.1 - 2017-07-27
....\jsxc\lib\jsxc.dep.js(38122):

```
// Shimming starts here.
...
 var options = Object.assign({ <---Object.Assign is not available on ie-pre edge
    shimChrome: true,
    shimFirefox: true,
    shimEdge: true,
    shimSafari: true,
  }, opts);
```
The effect is that jsxc will not raise an exception (and will fail to load) on Internet Explorer (Pre-Edge).

**Comment by sualko** [comment]
I think it's the same issue as in #584 and it was [probably fixed](https://github.com/webrtc/adapter/commit/aeb2527cf84e9449b9f51ed8f13ac8b6471fa06f) in the third-party library. I will update it and include in the next beta release. Thanks for pointing this out.
