### ISSUE TITLE
cross domain http image upload

### ISSUE THREAD

**Issue by shazvan275** [jsxc/jsxc#595]
when i try to upload file from cross domain am getting this error
`XMLHttpRequest cannot load http://192.168.2.235:5280/upload/ec7fcf7902c2576c7e6bca6aaa4a80cde0a32395/ypJBd6DG7Uvo8NjutmUGHocpHC513WUI2Y0yfeMM/cc.png. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:50644' is therefore not allowed access.`

and my config yml is:

mod_http_upload:
    docroot: "@HOST@/upload"
    put_url: "http://@HOST@:5280/upload"
    get_url: "http://@HOST@:5280/upload"
    thumbnail: false
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "Content-Type"

port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
      "/upload": mod_http_upload
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    register: true
    captcha: false
thanks...

**Comment by sualko** [comment]
Please see https://github.com/jsxc/jsxc/wiki/File-transfer and use next time the provided template.

**Comment by MarcelWaldvogel** [comment]
I have noticed as well that apparently the `custom_header`s are not obeyed by ejabberd for http_upload. My workaround was to use the Apache proxy I had in place anyway to add these headers unconditionally. (You can check this in your browser's console).

Would you mind asking the ejabberd community and post the result here?

**Comment by shazvan275** [comment]
#1899

**Comment by shazvan275** [comment]
https://github.com/processone/ejabberd/issues/1899
