### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by aronovgj** [jsxc/jsxc#596]
### Expected behavior
Registration should complete

### Actual behavior
Error:

```
Sorry we couldn't complete your registration.

too many values to unpack

Please report this to our issue tracker and mention the request id dhNWcOt6BM4Z2pFSe6Hn.
```

### Steps to reproduce the behavior
1. Install 3.3.0-beta.1
2. Activate
3. Select "Managed"
4. Click register

### Environment
- 3.3.0-beta.1
- Nextcloud 12.0.0
- Firefox 

Saw [this](https://www.jsxc.org/managed.html), installed immediatelly.
Not sure if I get how it is supposed to work. I don't need anything but the app and I don't need to enter any further information into any field, right?

**Comment by sualko** [comment]
Thanks for testing and reporting. We will look into this asap.

**Comment by sualko** [comment]
Does your username contain any other characters than a-z0-9? Are they upper-/lowercase?

**Comment by aronovgj** [comment]
No, all lower case latin letters.

**Comment by aronovgj** [comment]
Yep, new error:

```
Sorry we couldn't complete your registration.

Could not perform internal changes part 2. Please try again later or contact support@jsxc.org

Please report this to our issue tracker and mention the request id vPt8rXtJNuFUepEAsitt.
```

**Comment by sualko** [comment]
Sorry for the burden, but try again.

**Comment by aronovgj** [comment]
```
Congratulations! You got your own XMPP server. Please log out and in again.
```

Thanks!
