### ISSUE TITLE
Invite someone to a MUC chat room

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#599]
I did not find an option to invite someone to a room, neither in the roster nor in the room window. This would make adoption easier for converts from other chat systems.

**Comment by sualko** [comment]
@shazvan275 https://www.bountysource.com/issues/47922568-invite-someone-to-a-muc-chat-room :wink:

**Comment by sualko** [comment]
This is actually a duplicate of #341.
