### ISSUE TITLE
NExtcloud openfire and staying logon problem

### ISSUE THREAD

**Issue by indemio** [jsxc/jsxc#601]
Hi. I am new here. Some problem with clean installation of jsxc on nextcloud. All versions is actual. When i pushing any button like "Activity" or "Settings" jsxc just logout and i must relogin over and over and over. Seems like all settings is fine, i see roster and can send messages to my contats. But if i will follow in galery, jsxc will logout too. Sorry for my poor english.

**Comment by sualko** [comment]
Please use the provided issue template and reopen this issue afterwards.
