### ISSUE TITLE
Installing 

### ISSUE THREAD

**Issue by DwijadasDey** [jsxc/jsxc#603]
Hi
I am trying to run example jsxc app by downloading the [example](https://github.com/jsxc/jsxc/tree/master/example) in the web root.  

I have edited index.html to include the XMPP (ejabberd) URL and domain. The users can login to the ejabberd server using pidgin.
..................
..................
jsxc.init({
  loginForm: {
    form: '#form',
    jid: '#username',
    pass: '#password'
  },
  logoutElement: $('#logout'),
  loadSettings: function() {
    return xmpp: {
      url: 'chat.demohost.com:5280/http-bind/',
      domain: 'chat.demohost.com',
      resource: 'example',
      overwrite: true,
      onlogin: true
    };
  },
............................
............................
Once i access the login page, i get the following message "Checking status ..........You are not logged in! Maybe your password was wrong. Back" I donot find any log data being appended to the ejabberd server(16.09).

Shall i edit/configure few more parameters ?

Regards

**Comment by sualko** [comment]
First of all use the provided issue template. Second you have to prepend http or https to your xmpp URL.

**Comment by DwijadasDey** [comment]
Prepended https to the xmpp URL. Now BOSH server is not reachable since i could not add the port (ejabberd 5280) somewhere. 

Also if run the JSXC in a localhost, is it possible to place a remote BOSH URL ? Where should i configured the BOSH URL ? I have placed the BOSH URL and the domain in jsxc-master/example/js/example.js but still getting the above error.
....................
....................
var settings = {
      xmpp: {
         url: 'https://chat.demohost.com:5280/http-bind/',
         domain: 'chat.demohost.com',
         resource: 'example',
         overwrite: true
      }
   };
.........................
.........................
![screenshot-chat demohost com-2017-08-12-21-08-09](https://user-images.githubusercontent.com/12824049/29242095-f2878658-7f75-11e7-85c2-d495d1112590.png)

**Comment by MarcelWaldvogel** [comment]
The installation [wiki recommends](https://github.com/jsxc/jsxc/wiki/Prepare-apache) using a proxy to deal with Cross-Origin Resource Sharing (CORS). For further information on CORS problems and solutions, see the other (closed) issues here.

**Comment by DwijadasDey** [comment]
Thank you for the suggestions. I have enabled and configured the proxy as described in the wiki but i have the following issue at the moment. 

> [Sun Aug 13 04:56:40.874472 2017] [proxy:debug] [pid 3801] proxy_util.c(2418): [client x.x.x.x:8596] AH00947: connected /http-bind/ to x.x.x.x:5280, referer: http://chat.demohost.com/jsxc-master/example/index.html
> [Sun Aug 13 04:56:40.877397 2017] [proxy:debug] [pid 3801] proxy_util.c(2884): AH02824: HTTP: connection established with x.x.x.x:5280 (x.x.x.x)
> [Sun Aug 13 04:56:40.877544 2017] [proxy:debug] [pid 3801] proxy_util.c(3051): AH00962: HTTP: connection complete to x.x.x.x:5280 (x.x.x.x)
> [Sun Aug 13 04:56:40.877923 2017] [proxy_http:error] [pid 3801] (20014)Internal error (specific information not available): [client x.x.x.x:8596] AH01102: error reading status line from remote server x.x.x.x:5280, referer: http://chat.demohost.com/jsxc-master/example/index.html
> [Sun Aug 13 04:56:40.878033 2017] [proxy_http:debug] [pid 3801] mod_proxy_http.c(1324): [client x.x.x.x:8596] AH01105: NOT Closing connection to client although reading from backend server x.x.x.x:5280 failed., referer: http://chat.demohost.com/jsxc-master/example/index.html

May be it is apache problem.

The error in the browser when i access the index page of example application =>
![screenshot-chat demohost com-2017-08-13-10-48-05](https://user-images.githubusercontent.com/12824049/29246363-0514323c-7fe7-11e7-9340-3a8efc10c53e.png)

Also link seems to be missing => For further information on CORS problems and solutions, see the other (closed) issues **here.**

**Comment by MarcelWaldvogel** [comment]
There are tons of CORS problems solved in the past 602 issues here. No link was meant to be included.

[More detailed installation instructions are here](https://github.com/jsxc/xmpp-cloud-auth/wiki) (the first parts are independent of the external authentication and mostly independent of Nextcloud).

**Comment by DwijadasDey** [comment]
Thank you @MarcelWaldvogel . The wiki has everything to configure jsxc. I have configured it with letsencrypt and reverse-proxy. Earlier i had tried without SSL but eventually realized "ejabberd cannot deal with separate private key/certificate files" so according to the [wiki](https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd) , copied certificates to the /etc/ejabberd and it was done. 
![screenshot ch-2017-08-13-16-23-16](https://user-images.githubusercontent.com/12824049/29250562-d7bccea0-8033-11e7-9fea-6ffedce31d43.png)
Thanks everyone  @sualko @MarcelWaldvogel @fancycode @mmoqui @Zauberstuhl
