### ISSUE TITLE
Video chat in JSXC

### ISSUE THREAD

**Issue by Arora11** [jsxc/jsxc#606]
I have configured an XMPP and turn server for video chat. Where should i place the JAVA script code for the the example JSXC application. Hard to find any proper step by step/ documentation for the same.

**Comment by sualko** [comment]
Jup, https://github.com/jsxc/jsxc/wiki/WebRTC-how-to could be enhanced. If you have time it would be great if you could add some notes on how to configure video calls. Meanwhile you find the desired information in https://github.com/jsxc/jsxc/blob/e56a1410f523fa07ac00884223755162bcf4b3d5/src/jsxc.lib.options.js#L244

**Comment by Arora11** [comment]
Right ! As i am configuring the JSXC example apps, in which file should i place the options as i don't find any file by the name 'jsxc.lib.options.js'.  I have used /jsxc-master/example/js/example.js file to pass the following parameters.
.................
.................
xmpp: {
         url: '/http-bind/',
         domain: 'chat.mydomain.org',
         resource: 'example',
         overwrite: true
      }
................
...............

Shall i place  the options in the same file ?

**Comment by sualko** [comment]
All entries in `jsxc.lib.options.js` can be passed as init option to jsxc. Meanwhile I updated the wiki page.
