### ISSUE TITLE
message history problems in owncloud

### ISSUE THREAD

**Issue by m1cka** [jsxc/jsxc#609]
Hello,
i noticed  problem with Message history loading in owncloud (9)+JSXC (3.2.1).
JSXC  setting Message history -> enabled.

after  refreshing page (f5) part of conversations  disappear, if  making  log out -> login, is possibility  dont find any messages.
if you clean browser cache, all msg  are lost.
if browser is leaved  without  logout or etc. after few hours , msg  disappier

in android app xabber, history is working fine.

### Environment
- **JSXC version:**  3.2.1
- **Host system and version:** centos 7, owncloud 9
- **Browser vendor and version:**  latest chrome
- **Any browser plugins enabled?**  no
- **XMPP server vendor and version:** ejabberd-16.09
- **Is your XMPP server working with other clients as expected?**  we use xabber app in android, history working

**Comment by MarcelWaldvogel** [comment]
[ejabberd does not support XEP-0313 (Message Archive Management, mam:2)](https://github.com/processone/ejabberd/issues/1762), which our XMPP library (Strophe) relies on.

However, in [jsxc.nextcloud 3.3.0-beta.2, released earlier today](https://github.com/nextcloud/jsxc.nextcloud/releases/tag/3.3.0-beta.2), we include a workaround for this. It's not perfect, as mam:1, the intermediate protocol supported by ejabberd, is not providing a unique id which we rely on. So there might be some message reordering and duplication (between stuff in JSXC's browser cache and data fetched from the archive) issues. However, basic access of the archive should work.

Please try [the beta](https://github.com/nextcloud/jsxc.nextcloud/releases/tag/3.3.0-beta.2) and reopen this issue if the problem persists.

**Comment by MarcelWaldvogel** [comment]
Oops, I just read that you are using ownCloud 9. We stopped supporting ownCloud, as nobody was requesting ownCloud support since February. So it could well be that JSXC 3.3 has problems with ownCloud. If that is the case, I do suggest to consider a transition to Nextcloud and upgrade to NC 12.

**Comment by m1cka** [comment]
Tnx, for info, i will try to prepare  new instance.
