### ISSUE TITLE
Couldn't parse the response. Response code: 500

### ISSUE THREAD

**Issue by xpilgrim** [jsxc/jsxc#611]
### Expected behavior
Register on the server
### Actual behavior
registration failed
### Steps to reproduce the behavior
1. click on "register"
2.
3.

### Environment
- **JSXC version:** 3.3.0
- **Host system and version:**   Nextcloud 12.0.0
- **Browser vendor and version:** Firefox 55.0.2 (64-Bit)
- **Any browser plugins enabled?** Privacy Badger

#### Javascript

```
          XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: 
Zeile Nr. 1, Spalte 120:  (unbekannt):1:120
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: 
Zeile Nr. 1, Spalte 120: (unbekannt):1:120
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: 
Zeile Nr. 1, Spalte 120:
```

#### JSXC

```TypeError: jsxc.xmpp.conn is null[Weitere Informationen]  jsxc.js:12289:7
	jsxc.xmpp.httpUpload.init jsxc.js:12289:7
	<anonym> jsxc.js:12575:6
	dispatch https://alpha-lab.de/nextcloud/core/vendor/core.js:3:6414
	add/r.handle https://alpha-lab.de/nextcloud/core/vendor/core.js:3:3224
	trigger https://alpha-lab.de/nextcloud/core/vendor/core.js:3:5572
	a.event.trigger https://alpha-lab.de/nextcloud/core/vendor/core.js:7:7849
	trigger/< https://alpha-lab.de/nextcloud/core/vendor/core.js:3:11534
	each https://alpha-lab.de/nextcloud/core/vendor/core.js:2:2880
	each https://alpha-lab.de/nextcloud/core/vendor/core.js:2:845
	trigger https://alpha-lab.de/nextcloud/core/vendor/core.js:3:11513
	changeUIState jsxc.js:1064:6
	init jsxc.js:2781:6
	onSlave jsxc.js:684:6
	onStorage jsxc.js:9767:12
```

#### Admin Panel

```Sorry we couldn't complete your registration.

Couldn't parse the response. Response code: 500

Please report this to our issue tracker and mention the request id oTITfWpNjnDfQUILKYsh.
```

**Comment by sualko** [comment]
Sorry for the inconvenience. We are currently working on a solution.

**Comment by sualko** [comment]
@xpilgrim @stanelie can you try it again?

**Comment by stanelie** [comment]
Registration worked.
However, the user roster is empty. After manually adding users, messages are not going through. I guess I should start a new ticket?

**Comment by sualko** [comment]
> Registration worked.

Huray :tada: 

> I guess I should start a new ticket?

I can't reproduce this, so a new ticket would be great.

**Comment by xpilgrim** [comment]
Congratulations! You got your own XMPP server. Please log out and in again.

Thanks!

**Comment by stanelie** [comment]
If I switch back to the internal XMPP server, and back to JSXC, do I have to re-register again? Because I now get a "Couldn't reach the registration server" if I try to do that.

**Comment by sualko** [comment]
No you don't have to redo the registration, but I can reproduce your issue and I guess it's a side effect of my fix.

**Comment by sualko** [comment]
The registration server should be reachable again.
