### ISSUE TITLE
Local FR correction suggestion

### ISSUE THREAD

**Issue by sedenion** [jsxc/jsxc#612]
Hi, there is some error and not realy undestandable fr translations, here are suggestions for correction:

--- Correction --- :
"relogin": "Reconnexion"
"Secret": "Secret"
"you_have_only_a_subscription_in_one_way": "Votre abonnement n'est qu'à sens unique."
"Should_we_notify_you_": "Dans le futur, devons-nous vous notifier des nouveaux messages ?"
"On_login": "À la connexion"
"Reject": "Rejeter"
"Accept": "Accepter"
"Enable": "Activer"
(in "muc_moderated":) "description": "Seules les personnes avec \"voix\" sont autorisés à envoyer des messages"
(in "muc_semianonymous":) "description": "Votre identifiant Jabber n'est visible que par les administrateurs de ce salon"
"changed_subject_to": "__nickname__ a changé le sujet du salon en \"__subject__\""
"setting-explanation-carbon": "Avec la copie carbone activée, votre serveur XMPP enverra une copie à ce client de tous les messages entrants qui vous sont destinés, même si ils ne lui sont pas directement addressés."
"setting-explanation-login": "Si cette option est activée, le tchat commencera dès que vous vous connecterez."
"setting-explanation-priority": "Si vous êtes connecté plusieurs fois avec le même compte, votre serveur XMPP enverra les messages au client ayant la plus haute priorité."

-- Addition for MAM feature --- :
"Message_history": "Historique des messages",
"setting-mam-enable": "Voulez-vous être capable de retrouver les anciens messages stockés depuis le serveur ?"

-- Not sure about these --- :
For this one, the translation depend on the context (which i cannont find). If "keys" stands for keyboard's keys, the last word should be "touches", otherwise, the last word must be "clefs".

"Not_one_of_our_latest_keys": "Ce n'est pas l'une de nos dernières clefs",

**Comment by DiGGeR2** [comment]
(in "muc_moderated":) "description": "Seules les personnes avec "voix" sont autorisé**e**s à envoyer des messages"

**Comment by MarcelWaldvogel** [comment]
Merci beaucoup pour vos corrections. Vous pouvez changer les traductions vous-mêmes: https://github.com/jsxc/jsxc/wiki/Contributor-Guide#translate-jsxc-into-your-language

**Comment by MarcelWaldvogel** [comment]
I have included your suggestions in WeTranslateIt
