### ISSUE TITLE
online status of users which are actually offline

### ISSUE THREAD

**Issue by ace02000** [jsxc/jsxc#613]
### Expected behavior
working status of users in the list
### Actual behavior
I see a lot of online users in my list which are offline at this time.
If I'm using another XMPP Client (like Pidgin), I see the right status of users.

### Steps to reproduce the behavior
1. log in to nextcloud
2. look at the XMPP user list
3. the problem remains if I logout/login again

### Environment
- **JSXC version:**   JavaScript XMPP Chat 3.3.0
- **Host system and version:** Nextcloud 11.0.4 (stable)
- **Browser vendor and version:** Firefox 52 ESR
- **Any browser plugins enabled?** Adblock Plus
- **XMPP server vendor and version:** ejabberd 16.09 / Debian 9
- **Is your XMPP server working with other clients as expected?** YES

**Comment by sualko** [comment]
I think you stumbled over a bug which was introduced with the use of cached roster. We will try to fix it asap.

**Comment by ace02000** [comment]
Will you also fix it in the nextcloud plugin?

**Comment by sualko** [comment]
Yes of course. The Nextcloud app is just an wrapper around jsxc.
