### ISSUE TITLE
MAM message loading issues in Nextcloud+JSXC 3.3.0

### ISSUE THREAD

**Issue by piti-diablotin** [jsxc/jsxc#618]
Hi there.

Thanks for your very nice work. I really appreciate all the efforts you do for the community.
I would like to report 2 issues actually related to MAM support which I know is still experimental.

1) When MAM enabled, the messages loaded from the server are not the last ones but far older like from june or july. 

2) When MAM enabled, a line with "load older messages" appears at the top of the dialog box, and the last line of the discussion is behind the input message box. Therefore one cannot read the last message sent or received. If I disable the "height" style from the css of the div having the class slimScrollDiv then the last message of the discussion appears and the box is "one message" heigher.

I hope this can help improving you great job !

Cheers

**Comment by dehnhardt** [comment]
I can confirm the second point. I see the same behavior in my instance. 
For point one, I don't have enough data yet to trace the behavior.

**Comment by MarcelWaldvogel** [comment]
@piti-diablotin What XMPP server do you use? *ejabberd* does not (yet) support the current MAM standard `mam:2` which is needed to make loading reliable. But nevertheless, it shouldn't be that bad.

There will probably be no fix within the next two weeks (sorry!), but after that, we will look at it immediately.

**Comment by dehnhardt** [comment]
I use ejabberd.

**Comment by cidious** [comment]
I confirm that.
This is my thread on the Nextcloud Help on last message hidden issue:
https://help.nextcloud.com/t/the-last-message-is-hidden-in-the-history/19124/9

Also I confirm the History issue (1st point in the report).

**Comment by piti-diablotin** [comment]
@MarcelWaldvogel Indeed I use ejabberd,, but as cidious I don't have any problem with conversations.

**Comment by sualko** [comment]
1. I removed the padding and therefore this issue should be solved. The "load more" text is now an overlay, but I think this is fine.

2. I can't reproduce this behavior, but I set a limit for received mam messages and maybe this is required for some servers to get all mam pages in descendant order, as [XEP-0059](https://xmpp.org/extensions/xep-0059.html#last) says "The requesting entity MAY ask for the last page in a result set by including in its request an empty <before/> element, and the maximum number of items to return."

**Comment by piti-diablotin** [comment]
Hi 
Could you give me some hints ont how to build the app ? So far, I've cloned the git master branch and see a makefile. I run make on my ubuntu 16.04 server and it failes with
>npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
>
>npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/install.js

**Comment by dehnhardt** [comment]
I just removed/added the changes manually to the css. It seems that the problem is fixed. I will test some more during the weekend.

**Comment by sualko** [comment]
@piti-diablotin Probably your node installation is to old. I use 7.10.1 and npm 5.3.0.

@dehnhardt Thanks for your feedback. I am glad that this works for you.
