### ISSUE TITLE
Could not complete registration

### ISSUE THREAD

**Issue by john-2000** [jsxc/jsxc#619]
Sorry we couldn't complete your registration.

Couldn't parse the response. Response code: 500

Please report this to our issue tracker and mention the request id klEBfHFZBSXrIwsfOtR5.

System is Ubuntu 17.04 Nextcloud 12.0.1 jsxc 3.3.0

Please let me know if I can help with anything else

**Comment by MarcelWaldvogel** [comment]
Thanks for the feedback. I found (and solved) a problem. Hopefully this was the one. Can you try again?

**Comment by plumps** [comment]
As @john-2000 I am supposed to post the request id fO0R0sHAbRy93UbWNx8O

**Comment by john-2000** [comment]
My problem was fixed thanks!!!

**Comment by MarcelWaldvogel** [comment]
@plumps Thanks for reporting. The error message is

```Could not obtain certificate. Due to a popularity surge, jsxc.ch may have run into a rate-limit imposed by our certificate authority.```

Working on a workaround

**Comment by MarcelWaldvogel** [comment]
It works again since a few days; so you can try again now. I'm still working on a more permanent solution. Leaving this issue open until then.

**Comment by MarcelWaldvogel** [comment]
The long-term solution should be in place. Please let me know if anything weird happens (it is hard to test the live corner cases with Let's Encrypt).

**Comment by plumps** [comment]
It worked. 👍
