### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Invalid SID value.)

### ISSUE THREAD

**Issue by felipehertzer** [jsxc/jsxc#620]
ERROR: "Failed to load resource: the server responded with a status of 404 (Invalid SID value.)"

There would have to be a way to handle this error by making a request in a url with prebind that returns a new value for sid.

This error happens when there is a time without accessing the chat, or sometimes it disconnects. And I would like that instead of providing the relogin option, I would like to consult via ajax the prebind.

Or if you have some way of handling this problem to force it to generate new sid and rid values. Anyone have an idea how I could do it?

**Comment by sualko** [comment]
Just listen for the `disconnected.jsxc` event and do whatever you want like prebind, reconnection and so on.
