### ISSUE TITLE
how to use jsxc with react native

### ISSUE THREAD

**Issue by deounix** [jsxc/jsxc#622]
I'm trying to create Android & IOS app with reactNative and I don't know how to import jsxc with my project.

1. Is there any DefinitelyTyped for JSXC ?
2. How can I do that?

**Comment by sualko** [comment]
> Is there any DefinitelyTyped for JSXC ?

We are working on a [rewrite of JSXC]() with Typescript, but currently we don't have any type files.

> How can I do that?

I have no experience with react, but there is a issue (strophe/strophejs#115) for our used XMPP library, which maybe helps you.
