### ISSUE TITLE
Multi user chat?

### ISSUE THREAD

**Issue by Reventl0v** [jsxc/jsxc#623]
Hello,

I'm trying to use the multi user chat with jsxc, and the example code given on the master branch. It works well, still, it seems the multi user chat feature is not there, in the menu.

Am I missing something? (i'm using prosody as my server).

Related screenshot: https://ptpb.pw/foeK.png

Thanks

**Comment by sualko** [comment]
Did you enable MUC in prosody? Does it work with other clients? And please use the issue template, because it's there for a reason!

**Comment by Reventl0v** [comment]
Oh, I thought I didn't need to enable the MUC in prosody to join the rooms of other servers. After enabling it, it works. Sorry about the issue template, I thought it was trivial enough to avoid using it. Thank you for your answer.
