### ISSUE TITLE
Roster is not updated after change in nextcloud users

### ISSUE THREAD

**Issue by Nils160988** [jsxc/jsxc#625]
### Expected behavior
Changes of the user list (creation, deletion) is pushed to the chat contacts list.

### Actual behavior
If nextcloud users are created, they should show up in other users contacts list (chat on the right)
Same goes for deleted users which should disappear.
If the new user logs in, no or only very few of the existing contacts are shown.

It is working with the jsxc-version which was provided here (https://github.com/nextcloud/jsxc.nextcloud/pull/33#issuecomment-330857118).

### Environment
- **JSXC version: 3.3.0
- **Host system and version: Ubuntu 16.04. LTS, Nextcloud 12.0.3
- **Browser vendor and version: Firefox 55.0.2
- **XMPP server vendor and version: internal

### Logs
No related log entries found

**Comment by LEDfan** [comment]
@Nils160988 I found the problem. Can you test the build archive attached to the PR https://github.com/nextcloud/jsxc.nextcloud/pull/71 please?

**Comment by Nils160988** [comment]
@LEDfan Thanks for the archive. I tested it and seems to fix the issue partly. Now, a newly created user shows up within the contact window of old users. Still, when logging into the new users account, not all of the old users are shown.

**Comment by LEDfan** [comment]
@Nils160988 thanks for testing and your patience! 
The usernames which aren't show in the rosters, does they contain a character of the following list: `^`, `"`, `&`, `'`, `/`, `:`, `<`, `>`, `@`, or whitespace?

**Comment by Nils160988** [comment]
@LEDfan No problem and thanks for your work on this! Yes, you are right. The users, which are not shown do all contain whitespace, so this is problem some problem with escaping of this special characters.

By the way, if a user is deactivated by the administrator, it is still shown in the roster, which is probably not intended. This might be changed here as well.

**Comment by LEDfan** [comment]
@sualko this issue is caused by the https://github.com/jsxc/jsxc/commit/3aa3f9dd987b5903f56120155dd2ad5e382182f1 commit. Is there any way to disable this validation if using the internal backend? Apparently NC supports these chars.

**Comment by LEDfan** [comment]
> By the way, if a user is deactivated by the administrator, it is still shown in the roster, which is probably not intended. This might be changed here as well.

Good catch, this is now also solved in https://github.com/nextcloud/jsxc.nextcloud/pull/71, thanks!

**Comment by sualko** [comment]
I am sorry, but we currently doesn't support jid escaping (#501), but it's coming with the rewrite (#581). So stay tuned.

**Comment by LEDfan** [comment]
@sualko okay, if I find some time in the weekend, I can replace the offending characters at the server-side (as long as the JID's are unique en identifiable by the internal server it should work), this won't cause the name to shown up weird IIRC.

**Comment by LEDfan** [comment]
@Nils160988 I have made a new fix at https://github.com/nextcloud/jsxc.nextcloud/pull/71 and uploaded a new release. Could you give this a test and see if the users now correctly show up? Thanks!

**Comment by Nils160988** [comment]
Thanks for the fix, @LEDfan. It seems to work, but now, all old contacts (only those with spaces) show up twice in the contact list.
My guess is, that the old entries as well as the new ones with escaped spaces are displayed. If I create a new user, everything is fine.
Deleting the app, even manually dropping the tables "oc_ojsxc_presence" and "oc_ojsxc_stanzas" in the nextcloud database and reinstalling did not help to clean this up.
Do you have any advice how to clean the contact list?

**Comment by sualko** [comment]
@Nils160988 did you try to logout and in again? This caching behavior should be probably an javascript issue. If it occurs only on your machine an `localStorage.clear()` in your js console should fix the issue.l

**Comment by Nils160988** [comment]
Worked :)
