### ISSUE TITLE
Do we have any ready themes/skins for the chat UI?

### ISSUE THREAD

**Issue by vickyjain05** [jsxc/jsxc#626]
Hi All,

has anyone changed the UI of JSXC? I know the HTML and jsxc.css files can be altered, but I just wanted to know if there are any ready themes/skins available which I can just plug and play.

thanks

**Comment by MarcelWaldvogel** [comment]
I am not aware of any. Feel free to provide some modifications (and maybe even an easy way to plug them in).

**Comment by sualko** [comment]
As Marcel said, if you create a new skin it would be awesome if you could share it with the community.
