### ISSUE TITLE
Can't add contacts to contact list

### ISSUE THREAD

**Issue by cato1011** [jsxc/jsxc#627]
### Expected behavior
User shows up in contact list

### Actual behavior
Dialog closes, nothing happens

### Steps to reproduce the behavior
1. Create user 1 ... 10
2. Log in with user 1
3. Try to add user 3 to contact list

### Additional Information
When using the internal server, i'm facing the same problem. Also some users had some contacts,  but after deleting a contact it could not be added again.
I tried to refresh the roster via 
```
php occ ojsxc:refresh-roster
```
, but still the contacts are missing and i can't add one.

### Environment
- **JSXC version: 3.3.0
- **Host system and version: Ubuntu 16.04 / Nextcloud 12.0.3
- **Browser vendor and version: Apple Safari v.11 / Google Chrome Version 61.0.3163.100 / Mozilla Firefox 56.0 (64-Bit)
- **Any browser plugins enabled? No 
- **XMPP server vendor and version: Managed by jsxc (same problem before with internal)
- **Is your XMPP server working with other clients as expected? idk

#### Javascript
 No

#### JSXC

```
close dialog
```

#### XMPP
 idk

#### Host
 No

**Comment by MarcelWaldvogel** [comment]
When you select "Show offline contacts" in the JSXC bottom-right "burger" menu, does your new contact show up?

If not, this works correctly (but probably not as user-friendly as it should): Most XMPP clients (including JSXC) treat contacts whose presence you are not allowed to see the same as offline contacts and hide them by default. Once your peer authorizes you to see their presence, they then pop up in the roster.

At least this is what I just reproduced in the setting you described.

**Comment by cato1011** [comment]
I added some additional information.

Switching between "Show / Hide offline contacts" has no effect.

What I also noted is, that when i run the refresh roster command. The message "You have no contacts in your contact lists, add a new contact" appears n-times with n = number of users.

**Comment by MarcelWaldvogel** [comment]
One more try: Please log out of Nextcloud, open the JavaScript console, type `localStorage.clear()`, reload, and log in again. Does it work then?

If it does not work: Would you allow me to look into the server settings (including roster) for debugging purposes? If so, please provide me with your JID (by mail to marcel@jsxc.ch).

**Comment by cato1011** [comment]
Thank you very much! All contacts are showing up.

**Comment by MarcelWaldvogel** [comment]
So it was the `localStorage.clear()`? @sualko Do you have any hint at where the `localStorage` information can be misunderstood in your code?

**Comment by sualko** [comment]
> Do you have any hint at where the localStorage information can be misunderstood in your code?

No sorry. I already tried to reconstruct this issue and reviewed the code, but I didn't find anything.

**Comment by clumsycat** [comment]
Hi, I have the same issue but the `localStorage.clear()` won't work.
Environments: Nextcloud 12.0.3.3 in docker, JS XMPP app in internal mode.
Logs: Nextcloud log is normal, After I set `jsxc:debug=true` chrome.console has no error message. There all "http-bind" messages.

**Comment by sualko** [comment]
@clumsycat it's not possible to add contacts in internal mode

**Comment by clumsycat** [comment]
@sualko oops, I have no idea about that. 
Maybe u could add some description in documents, Since I literally working on this for 2 days. QAQ
