### ISSUE TITLE
Can't recursively clone jsxc

### ISSUE THREAD

**Issue by LEDfan** [jsxc/jsxc#628]
When trying to clone JSXC:

```
error: Server does not allow request for unadvertised object 5ab4a0148972324f3527433b961f3ce1db7e2697
Fetched in submodule path 'js/jsxc/lib/otr', but it did not contain 5ab4a0148972324f3527433b961f3ce1db7e2697. Direct fetching of that commit failed.
Failed to recurse into submodule path 'js/jsxc'
```

This is also breaking the Travis builds: https://travis-ci.org/nextcloud/jsxc.nextcloud/jobs/281849608

The fun thing is however that on the Github (web) the commit is there: https://github.com/sualko/otr/commit/5ab4a0148972324f3527433b961f3ce1db7e2697

@sualko any idea, maybe you force pushed something to that repo? Thanks!

**Comment by sualko** [comment]
I'm apologize for the trouble. I "cleaned" the fork, because all my pr were merged, but forgot to update the reference.
