### ISSUE TITLE
Question regarding Service Discovery

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#631]
@sualko 
Question regarding Service discovery:
For successful discovery of HTTP-Upload Service, the XEP-0363 calls for upload.example.tld. Will JSXC support a format of https://example.tld/upload

Looking to avoid dealing with CORS where possible :)

Thanks,
-Skyfox675

**Comment by sualko** [comment]
You mean for an upload slot? Yes sure. JSXC tries to upload your file to every url provided by the upload service.
