### ISSUE TITLE
Project submodule is broken

### ISSUE THREAD

**Issue by victorbrjorge** [jsxc/jsxc#632]
Hello,

I'm planning to become a contributor to this project since it's helping me a lot with a new project I'm working on. However, when I try to build the dev environment I get an error with the submodule js/jsxc/lib/otr.

It looks like the commit the main module tries to checkout to doesn't exist in the submodule. When I hit make in the main project I get the following message error: "Unable to checkout '5ab4a0148972324f3527433b961f3ce1db7e2697' in submodule path 'js/jsxc/lib/otr".

Doing a little bit of research I found out that this submodule can be found in two differents repositories: https://github.com/sualko/otr and https://github.com/arlolra/otr. I've tried to use both of them, but neither has the commit in question.

Thanks in advance.

**Comment by sualko** [comment]
I messed up the otr repo, but it was already fixed in  481314f. Sorry for the inconvenience.
