### ISSUE TITLE
Emoji container failing to wrap - 3.3.0

### ISSUE THREAD

**Issue by skyfox675** [jsxc/jsxc#633]
### Expected behavior
Previous version 3.1.0 displayed Emoji "selector" icons wrapping as a more efficient use of UI space.

### Actual behavior
3.3.0 Emoji "selector" icons are a single vertical list, left aligned to the container causing chat window to need to be resized to display all choices.

### Steps to reproduce the behavior
1. Working JSXC implementation of 3.1.0
2. Upgrade to 3.3.0
3. Open a new chat window, and open Emoji selector.

### Environment
- **JSXC version:3.3.0 
- **Host system and version: Windows Server 2016/IIS10.0/ARR3.0, HAProxy 1.7
- **Browser vendor and version: Chrome v61.0.3163.79 (Official Build x64)
- **Any browser plugins enabled? HTTPSEverywhere
- **XMPP server vendor and version: Ejabberd 17.09
- **Is your XMPP server working with other clients as expected? Yes, working with Conversations and Chat-secure

### Logs
N/A

#### Javascript
jquery.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
each @ jquery.min.js:2
each @ jquery.min.js:2
on @ jquery.min.js:3
bind @ jquery.min.js:4
(anonymous) @ jquery.slimscroll.js:272
each @ jquery.min.js:2
each @ jquery.min.js:2
slimScroll @ jquery.slimscroll.js:85
init @ jsxc.js:4517
open @ jsxc.js:4714
(anonymous) @ jsxc.js:4051
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
jquery.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
each @ jquery.min.js:2
each @ jquery.min.js:2
on @ jquery.min.js:3
bind @ jquery.min.js:4
(anonymous) @ jquery.slimscroll.js:280
each @ jquery.min.js:2
each @ jquery.min.js:2
slimScroll @ jquery.slimscroll.js:85

init @ jsxc.js:4517
open @ jsxc.js:4714
(anonymous) @ jsxc.js:4051
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
jquery.slimscroll.js:394 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

#### JSXC
![capture3](https://user-images.githubusercontent.com/4504420/31624819-8df5bca6-b269-11e7-95f5-0c45f46c5b2e.PNG)

#### XMPP
N/A

#### Host
N/A

**Comment by sualko** [comment]
I am sorry, but I can't reproduce your issue. You probably have some interfering css on your page. If you send me some test credentials to klaus@jsxc.org, I would check that.

![6db112eb-ae58-4fdf-900c-02553c470cf9](https://user-images.githubusercontent.com/2974196/31707599-11181046-b3ed-11e7-8ea5-5c319c7bb005.png)
