### ISSUE TITLE
The text of the chat is hidden under the message input line.

### ISSUE THREAD

**Issue by sosed213** [jsxc/jsxc#634]
The text of the chat is hidden under the message input line.

All works well but the last messages are hidden under the message input line.
Clearing the history or changing the size of the chat window temporarily solves the problem.

There may be a problem with CSS or JavaScript.

Checked on Google Chrome, Mozilla.

**Comment by sualko** [comment]
Thanks for your report. This issue was already fixed in cdd397ee754db1705b6c3ec010cc18274c897778 and will be shipped with the next release.
