### ISSUE TITLE
Error When trying to integrate jsxc to my website without login form

### ISSUE THREAD

**Issue by rheman** [jsxc/jsxc#635]
Hi everyone.  I have the following setting.

**Environment**
**JSXC version** : 3.3.1
I **am using jsxc in my web site.**
**Browser**: Chrome & Firefox

I am trying to integrate jsxc to  my existing web application without login form; thus I set every setting in the source. I am using the following code in my example.js file the I included the example.js file to my
index.html.
My example.js file looks as followed.

```
$(window).on('load', function()  {
      jsxc.init({
      rosterAppend: 'body',
      root: 'https://pessek-chat.esfam.org/mod/pessek_chat/jsxc/',
      displayRosterMinimized: function() {
         return true;
      },
      logoutElement: $('#logout'),
      loginForm: {
         enable: false
      },
      xmpp: {
         url: 'https://ejabberd-esfam.auf.org:5280/http-bind/',
         domain: 'pessek.esfam.org',
         overwrite: true
      }
   });
   var username = 'piwal';
   var password = 'pessek12';
   var jid = username + '@pessek.esfam.org';
   jsxc.start(jid , password);
});
```

But when I try to use my website I have the following error in my javascript console.
- In firefox I have the following
```
TypeError: jsxc.storage is undefined       jsxc.min.js:13:2349

```
- In chrome I have the following
```
Uncaught TypeError: Cannot read property 'hasSupport' of    jquery.min.js:2 
undefined
    at Object.init (jsxc.min.js:13)
    at HTMLDocument.<anonymous> (example.js:7)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```
![jsxc_error](https://user-images.githubusercontent.com/4598772/31882982-21855602-b7f1-11e7-8c29-f0f21087674f.png)

I dont know what's wrong. Could someone help me ??
Best regard

**Comment by sualko** [comment]
Which jquery version do you use? Can you try again with the unminified version? It's easier to debug.

**Comment by rheman** [comment]
Hello..
I am using jquery 3.1.1
Still have the same error..

**Comment by sualko** [comment]
Can you post the trace with the unminified version? Is your example integration public reachable, so that I could test it?

**Comment by rheman** [comment]
My example is not public reachable..

**Comment by rheman** [comment]
Please what do you mean by " trace with the unminified version" ?

**Comment by sualko** [comment]
I mean the error in your js console, because it's a nightmare to debug a minified js file.

**Comment by rheman** [comment]
I have the following in my js console.
ReferenceError: emojione is not defined[Learn More]  jsxc.js:2564:7
	<anonymous> https://esfam-elgg.auf.org/mod/pessek_chat/jsxc/jsxc.js:2564:7
	<anonymous> https://esfam-elgg.auf.org/mod/pessek_chat/jsxc/jsxc.js:18:2

TypeError: jsxc.storage is undefined    jsxc.js:243:11

init https://esfam-elgg.auf.org/mod/pessek_chat/jsxc/jsxc.js:243:11
	<anonymous> https://esfam-elgg.auf.org/mod/pessek_chat/jsxc/example.js:11:7
	j https://esfam-elgg.auf.org/mod/pessek_chat/jsxc/lib/jquery.min.js:2:29946
	g/</k< https://esfam-elgg.auf.org/mod/pessek_chat/jsxc/lib/jquery.min.js:2:30262

**Comment by sualko** [comment]
Did you forget to include the `jsxc.dep.js` file?

**Comment by rheman** [comment]
No I have included it..

**Comment by sualko** [comment]
Could you fix your issue?
