### ISSUE TITLE
JavaScript Xmpp Client - registration error

### ISSUE THREAD

**Issue by SISolutions** [jsxc/jsxc#637]
Ubuntu 14.04
Apache
php 5.6
NC 12.0.3

Registration
Sorry we couldn't complete your registration.

Your Nextcloud server cannot be used because host part in apiUrl must only contain lower case a-z, 0-9, and from &quot;.-&quot;

Please report this to our issue tracker and mention the request id CuHqCyZaBLcRSSWXUPxM.

In order to create a managed XMPP server for you, we will send the following information to our registration server. The set-up process will take about 20-30 seconds.
API URL  **https://my.ncserver.gr:port/index.php/apps/ojsxc/ajax/externalApi.php**
Secure API token  **removed for privacy reasons**
Your user id **removed for privacy reasons**

**Comment by MarcelWaldvogel** [comment]
We currently only support HTTPS servers running on the default port, 443. I have updated the error message to reflect this.

If you think we should support this, we would like two suggestions from you (and others):
1. What is your reason to use non-default ports?
1. Should we differentiate between instances on the same host, but with differing ports? Or should a later registration on the default port be able to take over the setup from a non-default port? How should multiple non-default-ports on the same host be handled? Why?
1. We currently try to create an XMPP domain of the form `principal-name.jsxc.ch`, where `principal-name` is the first part of a user-assigned domain, in your case `ncserver`. Should we just assign the name `ncserver` to the first entry with a port applying from there? A later registration would then get `ncserver<random-digits>.jsxc.ch`. Or should we reserve the nicest name for the default port? Why?

Getting some opinions there might help us make the policy decisions necessary to support different ports.

BTW: The API URL hostname that is in the logfile is different. Did you change this for privacy reasons or was the error message actually like that (with the exception of the `port` part, obviously)?

**Comment by SISolutions** [comment]
1. Many reasons (enterprise policy, not know port for less attacks,etc...) especially for a company.
2. differentiate between instances on the same host, but with differing ports to be more easy to manage.
3. reserve the nicest name for the default port for practical reasons and because people tend to forget easy.

BTW i didnt change anything and i really dont know what i could change for this to happen.

Thank you.

**Comment by SISolutions** [comment]
Well? 
Will i have a reply?

**Comment by MarcelWaldvogel** [comment]
Thanks for the reminder. With the start of the semester here, everything has been busy.

1. I do not think security by obscurity is a good idea. It is better to ensure that things do work as they should anyway. Switching to a globally reachable XMPP service (whether maintained yourself or using our managed service) also means that your membership will be exposed. BTW: Does federated sharing work at all when using non-standard ports?
1. I would prefer multiple instances to have a different DNS name, as this will create less confusion (and also fewer inter-instance problems)  (or, if you must, a different path)
1. We currently have a policy that when the path changes, but the secret stays the same, this is not considered a new registration, but a parameter change. Should we use this policy across ports as well?

Refusing alternate ports has been a deliberate design decision. But we are considering changing this design decision; but first need to know what the new design should look like before we jump the gun.

**Comment by SISolutions** [comment]
well?

**Comment by SISolutions** [comment]
any progress ?

**Comment by MarcelWaldvogel** [comment]
No answers to my questions yet, so no data to make a decision.

**Comment by SISolutions** [comment]
the things you are asking i dont know the answers. 
I just would like to use the app/service with a different port as i said and with a specific url name (or at least my provider to point an ip to that url).

**Comment by sualko** [comment]
> We currently only support HTTPS servers running on the default port, 443

I think we will not change this in the near future, so I close this issue.
