### ISSUE TITLE
SSL & reverse proxy

### ISSUE THREAD

**Issue by kintovt** [jsxc/jsxc#638]
Centos 7
Docker container with NextCloud version 12.0.3
JavaScript XMPP Chat version 3.3.1

Docker container works under apache via http.

On host machine i have apache reverse ssl-proxy.

Letsencrypt certificates for nextcloud.mydomain.com, that used by ssl-proxy, locates on host machine.

In NextCloud config i set  
"overwritehost"  => "nextcloud.mydomain.com",
"overwriteprotocol" => "https",
to avoid "apiUrl must start with https://" error when i try to register managed server.

But now i have certificate verify failed error.

I think that error root is in proxy.
Is there some elegant way to use managed server through ssl-proxy?

Here is last request id with error OJZg3GV63KkXMXyqf8Gl.

**Comment by MarcelWaldvogel** [comment]
It seems that your server (the reverse proxy) is only returning the server's certificate itself; the intermediate Let's Encrypt certificate is missing. Add the following line to the Apache configuration (assuming the default `letsencrypt`/`certbot` setup):

```apache
SSLCertificateFile /etc/letsencrypt/live/nc.***.**/chain.cer
```
You can verify this by entering your host name (`nc.***.**`) into https://www.ssllabs.com/ssltest/ . It returns `This server's certificate chain is incomplete. Grade capped to B.`

**Comment by MarcelWaldvogel** [comment]
As it seems that both Firefox and Chromium nowadays include that intermediate certificate, I extended the OS list of trusted certificates.

I cannot currently test this, as your site is down (I assume you are updating the configuration).

**Comment by MarcelWaldvogel** [comment]
Manual registration works now; assuming it should work for you as well.

**Comment by kintovt** [comment]
Thanks a lot! You 100% right! Trouble was in missed chainfile. 
Fixed by adding to apache configuration file this line:

`SSLCertificateChainFile /etc/letsencrypt/live/nc.***.**/fullchain.pem`

Thanks again for extremly fast and competent help!
