### ISSUE TITLE
Problem registering

### ISSUE THREAD

**Issue by darkidris** [jsxc/jsxc#639]
On registering in my nextcloud integration, I go this message:

Sorry we couldn't complete your registration.

Your Nextcloud server cannot be used because hostname 'www.rotherhamunderground.com' doesn't match either of '*.secure-secure.co.uk', 'secure-secure.co.uk'

Please report this to our issue tracker and mention the request id bkmPTu3G7hN3wI7MlTWu

Any ideas?

**Comment by MarcelWaldvogel** [comment]
Sorry for the delay. When connecting to https://www.rotherhamunderground.com, my browser and [Qualys SSLtest](https://www.ssllabs.com/ssltest/analyze.html?d=www.rotherhamunderground.com) show the same error. So you need to configure your certificate on the web server correctly.
