### ISSUE TITLE
ojsxc has script error after logging out

### ISSUE THREAD

**Issue by sabberworm** [jsxc/jsxc#640]
If log out of Nextcloud and open a public share URL on the same server, I don’t get any files listed because a TypeError in ojsxc.js is stopping script execution.

When I clear the local storage, the same page works fine and the error goes away.

The difference seems to be that, in the latter case, the serverType is not known so the script will request `apps/ojsxc/settings/servertype` and get a 401 Unauthorized response. Since there is no error handler, this error is silently ignored and no further script execution takes place.

The former case, however, will trigger the script error: the script will know the serverType (`0` for the internal backend) from local storage and call `startInternalBackend`. `startInternalBackend` uses `OC.currentUser.toLowerCase`. However, `OC.currentUser` is null, hence the TypeError.

In my opinion, ojsxc should bail much earlier when it finds out `OC.currentUser` is null and not even try to initialize itself…

### Steps to reproduce the behavior
1. Log into a nextcloud instance that has ojsxc enabled
2. Share a folder using a link
3. Log out
4. Open the shared link

### Expected behavior

The folder contents are displayed.

### Actual behavior

The nextcloud script listing the files is never executed because script execution is aborted by the TypeError in ojsxc.js.

Clearing the local storage fixes the issue.

### Environment
- **JSXC version:** v3.3.1 - 2017-10-20
- **Host system and version:** Nextcloud
- **Browser vendor and version:**  Firefox 56
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** nextcloud ojsxc internal
- **Is your XMPP server working with other clients as expected?** Yes

#### Javascript
```
TypeError: OC.currentUser is null
```

**Comment by tgressly** [comment]
+1

**Comment by sualko** [comment]
Thanks for your detailed error report :+1:. Can you test the fix and report back if it works for you?

**Comment by sabberworm** [comment]
@sualko I don’t have any experience in nextcloud plugin development… Could you tell me how to get the unreleased plugin and install it?

**Comment by sualko** [comment]
Just replace the `js/ojsxc.js` file in your `ojsxc` folder with the one from the repo.
