### ISSUE TITLE
Only allow chat with one user and hide the right bar

### ISSUE THREAD

**Issue by matheusfillipe** [jsxc/jsxc#641]
I am trying to use jsxc as a store support chat, since with a xmpp client on my phone i can always be available. I've been trying to figure out how to hide the whole right bar that comes by default with jsxc core and add a default bookmark and chat with the a given user to anyone who starts using the chat.

I hope I was clear enough.

**Comment by DanScharon** [comment]
Hi,

regarding the default bookmark: If you are using prosody as xmpp server you can use [`mod_default_bookmarks`](https://modules.prosody.im/mod_default_bookmarks.html).

**Comment by matheusfillipe** [comment]
Thanks DanScaron, this pretty much solves the problem. Now how can I fade away with the roster pannel and always shows this default bookmarked contact chat?

**Comment by matheusfillipe** [comment]
Well I have a weird behavior with jsxc. When i send a contact request or message from pidgin to my jsxc logged test user i get it. I set on prosody a motd to be send from my admin user and bookmarked the user using default bookmarks but it doesnt work on the jsxc interface. I dont see any user on the roster pannel, even after loggin out and in again or creating more test users, and they dont get the motd. 
I guess it has something  to do with prosody maybe? Some bosh configuration? Or does jsxc blocks those somehow?

**Comment by MarcelWaldvogel** [comment]
@matheusfillipe Could you please open a separate issue for the contact
request problem? Thanks!
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jsxc/jsxc
> ","title":"jsxc/jsxc","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jsxc/jsxc"}},"updates":{"snippets":
> [{"icon":"PERSON","message":"@matheusfillipe in #641: Well I have a
> weird behavior with jsxc. When i send a contact request or message
> from pidgin to my jsxc logged test user i get it. I set on prosody a
> motd to be send from my admin user and bookmarked the user using
> default bookmarks but it doesnt work on the jsxc interface. I dont
> see any user on the roster pannel, even after loggin out and in again
> or creating more test users, and they dont get the motd. \r\nI guess
> it has something  to do with prosody maybe? Some bosh configuration?
> Or does jsxc blocks those somehow?\r\n"}],"action":{"name":"View
> Issue","url":"https://github.com/jsxc/jsxc/issues/641#issuecomment-34
> 3691556"}}}

**Comment by poVoq** [comment]
Regaring your original question... a customer support chat like this with most of the XMPP functionality hidded away will be much easier (right now) to set up with https://conversejs.org
(Sorry for linking to the competition ;) )

**Comment by MarcelWaldvogel** [comment]
@poVoq Any path to XMPP salvation is a good path ;-)

**Comment by sualko** [comment]
Currently we have not enough man power to implement this feature, but contributors are always welcome.
