### ISSUE TITLE
How to install JSXC as standalone application?

### ISSUE THREAD

**Issue by doobry-systemli** [jsxc/jsxc#642]
Hi there,

we would love to use JSXC as a standalone web application - not integrated into another web app. Is JSXC meant to be used that way at all? We managed to build a index.html with the login mask and it somehow works, but a few things just don't work that well:

* Seems like you don't provide a tarball that includes all required files. E.g. the application requires jquery and other JS files that aren't shipped with your tarball. Or did we miss something here?
* JSXC only uses a very small amount of the browser window, which certainly is on purpose and very nice if used as Jabber integration to other webapps. Are there easy steps to widen the chat windows to the browser width or at least notable portions of it?

Looking forward to your response. Would be awesome if we could use JSXC as stanalone Webjabber client. We used to provide Webjabber using [Jappix](https://github.com/jappix/jappix), but that project is abandonned and doesn't support many modern Jabber Extensions.

If JSXC is not intended to be used as standalone Webjabber client, do you have any recommendations what to use instead?

**Comment by sualko** [comment]
> Is JSXC meant to be used that way at all?

Not initially, but it can be used that way. We are currently developing a mobil and desktop version, which is basically a standalone version of JSXC. Therefore we are currently developing a fullscreen template and so on. If you are interested in this, please have a look at the specific pr #581.

> Seems like you don't provide a tarball that includes all required files. E.g. the application requires jquery and other JS files that aren't shipped with your tarball. Or did we miss something here?

That's right. JQuery is not included, but it's in the repo. Just have a look at the example folder.

**Comment by doobry-systemli** [comment]
Thanks a lot @sualko for your response. I'm delighted to learn about PR #581. We'll certainly take a look at it.

About the JQuery inclusion ... it would be great if you would provide a tarball that is able to be run out of the box as standalone web application. Probably you'll do that anyway after the PR has been merged.
