### ISSUE TITLE
external service discovery for ice server retrieval namespace

### ISSUE THREAD

**Issue by puuu** [jsxc/jsxc#643]
@sualko I was testing your external service discovery (#567) implementation with sjsxc-3.3.0-beta.1 for SOGo 3 and the `mod_turncredentials.lua` from your [gist](https://gist.github.com/sualko/ab73ca6043d9101e971d7f5685a0e670).
Thank you for integrating #545 !

Unfortunately, the detection is not working.

I think, we messed up with the namespace of extdisco. The `mod_turncredentials.lua` module use `urn:xmpp:extdisco:1` and `jsxc.lib.webrtc.js` is using [`urn:xmpp:extdisco:2`](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.webrtc.js#L36) and [`urn:xmpp:extdisco:1`](https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.webrtc.js#L140).

I am not familiar with namespaces, but reading the [XEP-0215](https://xmpp.org/extensions/xep-0215.html), IMHO it should be `urn:xmpp:extdisco:2`. Not sure why the prosody module use `urn:xmpp:extdisco:1`.

 After changing this [line](https://gist.github.com/sualko/ab73ca6043d9101e971d7f5685a0e670#file-mod_turncredentials-lua-L33) of `mod_turncredentials.lua` to `module:add_feature("urn:xmpp:extdisco:2");` jsxc can receive the iceServers.

**Comment by sualko** [comment]
Good catch. I will bump the namespace in both files to `urn:xmpp:extdisco:2`, because all changes from 1 to 2 are optional.

**Comment by sualko** [comment]
Can you test the changes?

**Comment by puuu** [comment]
jsxc: Version 3.3.2 on SOGo 3 (I simply replaced the `js/jsxc` folder with the 3.3.2 release)
mod_turncredentials.lua: latest version from [gist](https://gist.github.com/sualko/ab73ca6043d9101e971d7f5685a0e670)

On javascript console (new session without previous cookies):
```
> jsxc.options.get('RTCPeerConfig').iceServers.length
< 1
> jsxc.webrtc.init()
< undefined
jsxc.js:183 ice servers receiving by xmpp extdisco
jsxc.js:183 set ice servers
jsxc.js:183 Variable RTCPeerConfig doesn't exist. It was created.
> jsxc.options.get('RTCPeerConfig').iceServers.length
< 6
```

Looks good. Thanks.

**Comment by sualko** [comment]
:tada: :+1: 

Thanks for testing. Btw. it would be awesome if you could open a pr to update jsxc in the sogo version.
