### ISSUE TITLE
Login failure when password includes French characters

### ISSUE THREAD

**Issue by Mickael-Blanchard** [jsxc/jsxc#644]
JSXC: 3.3.1
browser: Firefox 57.0 64-bit
jQuery: 3.1.1

Hi,

The problem is very simple to describe: when I try to login from JSXC, with a password containing some accentuated characters like 'é', 'à', 'è', 'ù', etc., it fails.
I don't see any related warning or error message in the FF console.
I have no problem with non-web clients like Pidgin, Miranda-NG.

Feel free to ask details or any test, of course.

Thank you! :)

**Comment by sualko** [comment]
I could reproduce your issue and will try to fix it asap. It's probably an issue with the underlying XMPP library, but I'm not totally sure.

**Comment by sualko** [comment]
Good news: This was already fixed in the related lib :tada:

**Comment by Mickael-Blanchard** [comment]
Great news, thank you.
In France, we could say: "packed, it's weighed" :)
