### ISSUE TITLE
Locales with country codes are not recognized

### ISSUE THREAD

**Issue by dteleguin** [jsxc/jsxc#646]
### Expected behavior
Browser locale should be automatically picked up, if supported by JSXC.

### Actual behavior
Locales with country codes are not picked up:
```
bn-BD
hu-HU
nl-NL
pt-BR
sv-SE
tr-TR
vi-VN
zh-TW
```

### Steps to reproduce the behavior
1. Set browser language to one of the above (important: it should be on the top of the list of languages in both Firefox and Chrome)
2. Open/reload JSXC and log in (in fact, the bug manifests even in the modal login box)
3. If any of the above locales has been chosen, the interface will show in English (fallback) instead.

### Environment
- **JSXC version:** 3.3.2
- **Host system and version:** standalone 3.3.2, RoundCube 1.3.3 + jsxc.roundcube 3.3.2
- **Browser vendor and version:** Firefox 57, Chromium 62
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** (not relevant)
- **Is your XMPP server working with other clients as expected?** (not relevant)

#### Javascript

(no errors)

#### JSXC

```
i18next: languageChanged pt
jsxc.dep.js:50773:7728
i18next: initialized 
Object { debug: true, initImmediate: true, ns: […], defaultNS: […], fallbackLng: […], fallbackNS: false, whitelist: false, nonExplicitWhitelist: false, load: "all", preload: false, … }
i18next::translator: missingKey pt translation
```
(the language has been set to Brazilian Portuguese) 

#### XMPP

(no related entries)

#### Host

(no related entries)

**Comment by sualko** [comment]
Thanks for reporting. I guess it's related to the [grunt-merge-data](https://www.npmjs.com/package/grunt-merge-data) task.
