### ISSUE TITLE
App not available anymore on Owncloud ?

### ISSUE THREAD

**Issue by Kidlike** [jsxc/jsxc#647]
I was following your [wiki for installing to owncloud](https://github.com/jsxc/jsxc/wiki/Install-ojsxc-(owncloud)), but if I'm not mistaken JSXC doesn't exist anymore on the owncloud market.

In case this is helpful : [owncloud_config_report_20171213.json.txt](https://github.com/jsxc/jsxc/files/1555107/owncloud_config_report_20171213.json.txt)

**Comment by Wohlstand** [comment]
Also, OwnCloud 10 tells me that app requires 9.2 and lower version, and I have found that OC version is in the "[OwnCloudArchive](https://github.com/owncloudarchive/jsxc.chat)" which is sad...

**Comment by sualko** [comment]
You are right. JSXC is only available for Nextcloud, because we didn't get any love from the Owncloud developer/community back in the days and therefore we decided to stop development. Sorry.

**Comment by Wohlstand** [comment]
Okay, I see, I have checked out what is a NextCloud thing: I didn't knew that it is created by original developer of OwnCloud who gone away from the OwnCloud Inc company...

I would to move to NextCloud, but I need to check it out how it will work and will it have same or better functionality than OwnCloud now... I see that there are providing Android app for free while pre-built OwnCloud is paid and I always compiling it by myself from sources to use it on my devices.

**Comment by sualko** [comment]
Some things which changed for me since I switched to Nextcloud on multiple instances:

- I never had to wait for the first bug fix release, because if Nextcloud releases a version it's stable.
- Updates run without issues. No googling and fixing stuff by hand.
- All "business" apps are free now.
- They care about contributors.

**Comment by Kidlike** [comment]
Alright, all that is good and fare :)

Thanks for the information.

Maybe put a warning in the wiki to mention that it only works up to 9.2, and after that only nextcloud is supported.
