### ISSUE TITLE
NextCloud 12.0.4 enable Ojsxc hang infinite

### ISSUE THREAD

**Issue by Kiwy404** [jsxc/jsxc#648]
### Expected behavior
Enable OJSXC app on NC 12.0.4 without infinite hang

### Actual behavior
After upgrading NC 12.0.3 to 12.0.4 reenable OJSXC (latest version) hang infinitely (from both the NC Admin GUI or via the occ command)
### Steps to reproduce the behavior
1. Setup NC 12.0.3 
2. Install OJSXC 3.3.2 
3. Configure internal server XMPP
4. Upgrade to NC 12.0.4
5. Try to reenable OJSXC app (all others app are ok, just OJSXC which hang infinitely) 

### Environment
- **JSXC version:**  3.3.2 
- **Host system and version:**  Debian 7 -NC 12.0.4
- **Browser vendor and version:**  Chrome/Firefox
- **Any browser plugins enabled?**  -
- **XMPP server vendor and version:**   NO XMPP server only the internal OJSXC internal server
- **Is your XMPP server working with other clients as expected?**  -

No logs are produced in nextcloud.log

**Comment by sualko** [comment]
Can you purge the folder and try to install it via the app store?

**Comment by Kiwy404** [comment]
I **rm -rf** the **apps/ojsxc** folder and then reinstall the app via app store, always the same infinite hang.

We have noticed this log entry in nextcloud.log :  

``
{"reqId":"PGOEwsYvQGwM18K4oesC","level":3,"time":"2017-12-15T13:53:39+00:00","remoteAddr":"x.x.x.x","user":"administrateur","app":"no app in context","method":"GET","url":"\/index.php\/settings\/admin","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\OJSXC\\\\Settings\\\\Section! Class OCA\\\\OJSXC\\\\Settings\\\\Section does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#1 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#2 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#3 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(289): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#4 \\\/var\\\/www\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(133): OC\\\\Settings\\\\Manager->getAdminSections()\\n#5 \\\/var\\\/www\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(72): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('server')\\n#6 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('server')\\n#7 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#9 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#10 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('AdminSettingsCo...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/cloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#14 \\\/var\\\/www\\\/cloud\\\/index.php(48): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.94 Safari\/537.36","version":"12.0.4.3"} ``

**Comment by Kiwy404** [comment]
We solved this issue by removing ojsxc plugin, dropping manually **oc_ojsxc_stanzas** and **oc_ojsxc_presence** tables and flushing ojsxc app config related data from **oc_appconfig** table ( not flushed/dropped by uninstalling via nextcloud uninstall button), then reinstall the ojsxc plugin, if it can help other peoples.

**Comment by sualko** [comment]
@Kiwy404 thanks for the update. Maybe @LEDfan has time to look into this.
