### ISSUE TITLE
the user are always leaving the room whenever go-offline

### ISSUE THREAD

**Issue by devendrawebdeveloper** [jsxc/jsxc#649]
I would to build a gourpchat app. I use the muc. but I found what I really need is the group-chat, not a room-chat.
the user will always leave the room then go-offline, even I set it the the room-member.
and when the user go-online again, it not goto the same room auto.

does that any solution or hooks for this?

**Comment by sualko** [comment]
There is no other group chat in xmpp than a room. I think the issue should be fixed with #645.
