### ISSUE TITLE
Archived messages are not render properly on chat box

### ISSUE THREAD

**Issue by mkjain554** [jsxc/jsxc#650]
Expected behavior

Chat archiving functionality coming from backend properly,And render On the chatBox

Actual behavior
Steps to reproduce the behavior
1. Clicking on the Load more messages
2. In network i can see all the message coming from backend is ok and I can can see the xml having all the messages,But when its going to render on the chatbox its misses some messages its happen the same when I am tried again to load.
3. Conclusion is that some message are not rendering in the chat box. 

 Environment
- JSXC version: v3.2.1 - 2017-06-01 
- Host system and version:
- Browser vendor and version: Chrome(Version 51.0.2704.103 (64-bit))/Firefox
- Any browser plugins enabled: NO
- XMPP server vendor and version: Openfire 4.1.4 (XMPP)
- Is your XMPP server working with other clients as expected?: On android/IOS its working fine they are using some other libraries for chat.

#### Javascript
```
No Errors found in Console
```

Thanks in advance.
Its Urgent

**Comment by mkjain554** [comment]
Can anyone help me out....Help will be appreciated.

**Comment by ashish-jain-mp** [comment]
Facing same issue. Anyone please update on this major issue.

**Comment by mkjain554** [comment]
Hi Team please acknowledge.....So I can go further or Change the Library.

**Comment by vSudeep** [comment]
Hi Did you get the solution

I think their are lots of issue in the Chat archiving as well its not a complete package.So I think you can try some other XMPP library there are lots of stable library there.Go for other Library.

**Comment by karanSingla23** [comment]
Hello Guys, I am also looking for the solution.

**Comment by sualko** [comment]
First of all this is a community project and stuff like

> Its Urgent

is not helpful and polite at all. We are mainly students or academic staff members doing this in our free time, so be patient if nobody reply in a week or so.

I'm sorry that you face some issues with mam, but 

1. mam is marked as experimental 
2. you don't provide enough information. Which stanzas are transfered? How can i reproduce the issue? Does it happen with other xmpp servers? Etc.

I close this issue until you provide the desired information.
