### ISSUE TITLE
Translations improvement

### ISSUE THREAD

**Issue by smassonnat** [jsxc/jsxc#652]
Hello,

We've been using JSXC library in an International context, and some of our users reported misleading translations.

Here those that have been reported to us : 
- "has come online" (EN translation for _has come online_), seems to have a sexual connotation. 
- "Kamer" (NL translation for _Room_), appears to mean something similar to "bed room" instead of a normal room.

(Please don't ask me what our customers are thinking !! :-) )

So I've been wondering, if those might be replaced by something more meaningfull:
- has come online => is now online
- Kamer => chatroom (it seems it is not translated  from english)

Regards

**Comment by sualko** [comment]
Thanks for the hints. It would be awesome if you could change those strings on [webtranslateit](https://webtranslateit.com/en/projects/10365-jsxc) by yourself.

**Comment by smassonnat** [comment]
Hi !
Sorry about my late answer.
I did the NL translation, but I was not able to update the english one , cause it is already completed.

Regards

**Comment by sualko** [comment]
I updated your role and I hope you are now able to update also the English translation.

**Comment by smassonnat** [comment]
Thanks, I've just updated it :)

Will those new translations be part of the next JSXC release ?

Regards

**Comment by sualko** [comment]
:tada: Thanks a lot.

> Will those new translations be part of the next JSXC release ?

Sure.
