### ISSUE TITLE
nextcloud - populate list with organization users

### ISSUE THREAD

**Issue by Thatkookooguy** [jsxc/jsxc#655]
### Expected behavior
when registering to your own chat server, all organization contacts disappeared from the list. users need to add them manually
### Actual behavior
should add all organization contacts automatically or have an option to do that
### Steps to reproduce the behavior
1. enable plugin from app store
2. register to a managed (beta service) server type
3. contacts are suddently empty in the chat sidebar

### Environment
- **JSXC version:** 
- **Host system and version:** NextCloud
- **Browser vendor and version:** Version 63.0.3239.108 (Official Build) (64-bit)
- **Any browser plugins enabled?** no. run on incognito
- **XMPP server vendor and version:** jsxc.ch/managed.
- **Is your XMPP server working with other clients as expected?** didn't check other clients

**Comment by MarcelWaldvogel** [comment]
Happy New Year! Sorry for the inconvenience, will look into this shortly.

**Comment by MarcelWaldvogel** [comment]
We had a database issue which I hope should be fixed now. Could you please try again?

**Comment by freakyc** [comment]
I'm not sure when I registered on the managed server if it was before or after the database issue you mentioned, so I did a re-register today and the user list doesn't add auto-populate like the internal server did.  I'm not sure if it's supposed to and actually prefer that it doesn't automatically add my admin account, but I thought I'd add my experience with it.

**Comment by Thatkookooguy** [comment]
@freakyc I agree there should be an option to change this in the preferences.
As an admin, I don't care. But for new users I add to my server, not all of them are tech savvy and I think some of them find this a little odd.

maybe have an option that if a user is part of a group, you can set certain groups (like their teamates) as the default added chat contacts

**Comment by olegbolden** [comment]
Let me continue this discussion. 
After I turned my server type from internal to managed I have to add newly created users of Nextcloud to all accounts that have always been registered before.
When using internal jabber server new user was automatically added to the list for all users and his own list populated with these users automatically. Now with managed server every existent user should add new contact manually. Moreover, Full name of newly added user is not processed by managed server, so if I need to change Full name of some account I can not change his/her name in one place - every member of our company should change Full name of the corresponding Nextcloud account manually.
I wonder why all existent users from various groups were added to managed server when I just created it in admin panel, but newly added Nextcloud users are not processed at all on myserver.jsxc.ch ?
May be there are some synchronization for this?
It is very inconvenient to set all up in company wtih even 30-40 members.

**Comment by MarcelWaldvogel** [comment]
The service authentication backend, ]`xcauth`](https://github.com/jsxc/xmpp-cloud-auth), does support managing shared roster groups (and full names) based on Nextcloud groups.

Our managed server uses this. But somehow it currently does not do what it should. I'm investigating.

PS: Full names will usually only be set once, so the user can change it.

**Comment by MarcelWaldvogel** [comment]
Sorry for not being clear: Please log in with a user.

When a user logs in:
1. the roster groups (s)he is in are updated based on the Nextcloud groups and
1. the user's full name is set if it has not previously been set to anything useful (i.e., neither the empty string, the username, nor the JID).

**Comment by olegbolden** [comment]
Strange but group synchronization stopped working again...

**Comment by MarcelWaldvogel** [comment]
I see a lot of HTTP '500' error codes when the managed server is trying to access the groups of the user logging in, starting at 13:47 UTC. Can you check your (Nextcloud, Web server) logs?

(The authentication requests immediately before that are successful.)

If you do not want to see that information on GitHub, you can also send mail to `marcel@jsxc.ch`.

**Comment by olegbolden** [comment]
I revealed some more problems wtih user and group management.

1) If I eventually add myself to contact list (just by mistake or importing userlist with myself inside from some messenger) I cannot delete myself from contact list. And I can send messages to myself :)
2) If I delete group admin was added to before deletion, this group is not deleted from admins roster. This deleted group is not visible by other users as expected.
3) If I delete some user within Nextcloud and create another user with the same name I see old Full Name and can read old messages of deleted user. This happens most probably because user is not actually deleted from JSXC server.

**Comment by MarcelWaldvogel** [comment]
To the different items:

1. **Full name change**: `xcauth` now supports this and it has been deployed on the managed server. On the next login of that user or anyone in any of his groups, the name should be changed.
2. **User deletion**: The next time any of his group buddies log in, the deleted user should disappear from the shared rosters (*not* from the manually added rosters; if you want that, [jsxc.nextcloud](https://github.com/nextcloud/jsxc.nextcloud/issues) would need to be involved and it's not going to be pretty.
3. **Self in roster**: This addition was done in JSXC, not another XMPP app? Then please [create an issue in jsxc.nextcloud](https://github.com/nextcloud/jsxc.nextcloud/issues).
4. **Delete group admin**: I do not understand what you mean here. Could you please [create a more descriptive issue in jsxc.nextcloud](https://github.com/nextcloud/jsxc.nextcloud/issues)? Thanks!
5. **Re-create user**: The *old full name* part should be fixed. And yes, there is no real deletion yet. See **User deletion** above.

I am sorry to ask you to create these issues, but separating it (and explaining it in more detail, for **Delete group admin**) helps us to fix it. It is already confusing now to have multiple itemized lists in multple comments.

I hope that at least the *Full name* part is working fine for you now. And we will do our best to address the other issues.

**Comment by MarcelWaldvogel** [comment]
After creating the new issues, could you please close this issue? Thanks!

**Comment by olegbolden** [comment]
@MarcelWaldvogel ,
I'm really happy to prove that most needed items 1, 2 and 5 now working flowlessly for users!!!
Thank you for your time!
As for the rest couple of issues I'll create separate ones to continue with.
