### ISSUE TITLE
second line call bug

### ISSUE THREAD

**Issue by usanjar** [jsxc/jsxc#656]
hello there,

when two people are having a video call and 3 person calls in it goes on hold but the video disappears from firs two and when the 3rd person hangs up the call everyone's call ends.

### Environment
- **JSXC version:** v3.3.2 
- **Browser vendor and version:** chrome 63
- **xmpp server:** ejabberd

#### Javascript
no error, warning clear console.

**Comment by MarcelWaldvogel** [comment]
Running under Nextcloud?

**Comment by usanjar** [comment]
no pure jsxc library, xmpp ejabberd server

**Comment by sualko** [comment]
This will be fixed in the next major version. Sorry for your inconvenience.

**Comment by usanjar** [comment]
ok, thank you.
