### ISSUE TITLE
Customization of UI & file transfer in JSXC with xmpp

### ISSUE THREAD

**Issue by poojapradhan** [jsxc/jsxc#657]
Hi , I am new to xmpp ejabbard, How to customize UI of jsxc, not getting the chat window html code. I have use jsxc-3.3.2 version downloaded from site. How to make it full page. How to do file transfer? Can you please guide or provide links to refer.  Thanks in advance.

**Comment by sualko** [comment]
You can update the style via your own stylesheet file. For file transfer see our [wiki page about file transfer](https://github.com/jsxc/jsxc/wiki/File-transfer). Full page is coming with 4.0.

**Comment by mdbyambaa** [comment]
Hi, i am too new on jsxc. how can i customize some menu and features (remove some menu etc)
