### ISSUE TITLE
Chat pannel hidde some important button (File, Galerie, Mail, Deck)

### ISSUE THREAD

**Issue by DiGGeR2** [jsxc/jsxc#659]
### Expected behavior
Don't hidde certain button when the Chat pannel is displayed

### Actual behavior
Chat pannel hidde some important icones on a lot of other app
- File app = Galerie button on the top right is hidden by the chat pannel,
- Galerie = 3 top right button are hidden by the chat pannel,
- Mail = send button bottom right is hidden when the chat pannel is open,
- Deck = 3 top button on the top right are hidden + a strange pannel is displayed, 

### Steps to reproduce the behavior
1. Open one of these app : File, Galerie, Mail or Deck
2. Display/Hidde chat pannel
3. Some button are hidden by chat apennel

### Environment
- JSXC version: 3.3.2
- Host system and version: Nextcloud 12.0.4
- Browser vendor and version: Chrome 63

**Comment by sualko** [comment]
Can someone post some screenshots?

**Comment by DiGGeR2** [comment]
Hello,

here are screetshots.

The most annoying is in mail application (send button hidden)
The wired error display is in deck
In the Gallery app, the but is minor but exist

Thanks to correct that if you can :)

![deck-chatpanelclosed](https://user-images.githubusercontent.com/1783500/35809988-887f77ca-0a8a-11e8-8d19-3d22b8fd0acf.PNG)
![deck-chatpanelopen](https://user-images.githubusercontent.com/1783500/35809989-889a22d2-0a8a-11e8-82ea-09ddce2eed0b.PNG)
![gallery-chatpanelclosed](https://user-images.githubusercontent.com/1783500/35809990-88b80b62-0a8a-11e8-96b7-0630bc04fa55.PNG)
![gallery-chatpanelopen](https://user-images.githubusercontent.com/1783500/35809991-88d108a6-0a8a-11e8-92e8-ff29da9cc91d.PNG)
![mail-chatpanelclosed](https://user-images.githubusercontent.com/1783500/35809992-88eab800-0a8a-11e8-834a-c6ab1c9c6c8a.PNG)
![mail-chatpaneopen](https://user-images.githubusercontent.com/1783500/35809995-8940baf2-0a8a-11e8-8ca0-2af62927bbf3.PNG)
