### ISSUE TITLE
How to integrate with Django?

### ISSUE THREAD

**Issue by k0fi** [jsxc/jsxc#660]
Hello, I'd like to integrate jsxc to an existing Django site, but could not find any documentation/tutorial about that, so I appreciate if you could provide a guide to do so.

**Comment by MarcelWaldvogel** [comment]
I don't know Django myself, so there is little I can do on the actual topic. But you might want to look at the [generic integration instructions](https://github.com/jsxc/jsxc/wiki/Install-jsxc) or check how the other integrations work.

**Comment by poVoq** [comment]
Starting point and / or alternative:
https://github.com/TracyWebTech/django-conversejs

**Comment by sualko** [comment]
We are sorry, that we can't provide you with a step-by-step guide, but we don't have enough man power. If you find a way to integrate jsxc into Django we would be glad if you could add an entry to the wiki.
