### ISSUE TITLE
Not all messages are delivered to android client

### ISSUE THREAD

**Issue by m1cka** [jsxc/jsxc#663]
### Expected behavior

we are using  jsxc chat plugin  in nexcloud, and when  we are sending  messages to android app (xabber) not all messages are delivered.

![image](https://user-images.githubusercontent.com/5598270/35261907-f3d84a80-001a-11e8-81c0-a9a679e850fb.png)

### Actual behavior
sometimes sending 8 messages, delivering 1-4 and 6-8.

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:* JavaScript XMPP Chat 3.3.2
- **Host system and version:** nexcloud 12.0.3
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:* ejabberd 17.06
-  OS: centos 7
-  backend : Mysql 5.7
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
Is only the check mark missing, or is the message not delivered at all? Please [enable debugging](https://github.com/jsxc/jsxc/wiki/Debugging) and post a dump of your js console.
