### ISSUE TITLE
Zentyal SOGo Setup - Need Help

### ISSUE THREAD

**Issue by adityateche** [jsxc/jsxc#664]
Hi there, I just install Zentyal with SOGo web email. Can someone please guide me how can I configure jsxc with my SOGo web email. I am newbie to linux yet.'
I am running : Version: 3.2.10.20170914-1 in Zentyal Server.

Thanks in advance !

**Comment by MarcelWaldvogel** [comment]
The [wiki article](https://github.com/jsxc/jsxc/wiki/Install-sjsxc-(SOGo)) doesn't help?
