### ISSUE TITLE
Cannot register a server

### ISSUE THREAD

**Issue by identworx** [jsxc/jsxc#666]
Hi,

i cannot register a server because we get the following error message:

Sorry we couldn't complete your registration.
Couldn't parse the response. Response code: 500
Please report this to our issue tracker and mention the request id BYb15JH12caMSuMpQ6qV.

System:
Ubuntu 16.04.3 LTS (GNU/Linux 4.13.0-26-generic x86_64)
Nextcloud 12.0.4

Any ideas?

Thanks in advance!

// Bastian

**Comment by MarcelWaldvogel** [comment]
Nice issue number for the devillish(?) bug I had introduced with the last "improvement". Sorry for you to run into it; it should be fixed now. Can you try again?
