### ISSUE TITLE
How to trigger a javascript function after successful connection

### ISSUE THREAD

**Issue by vickyjain05** [jsxc/jsxc#669]
I have a function called setupAvatar(), I want to trigger it once the connection is successful. I am using the below JS code to log the user in

jsxc.start('jid', 'somehash');

I am trying the below, but it did not work:
jsxc.start.xmpp.connected(setupAvatar);

**Comment by sualko** [comment]
You can listen for the `connected.jsxc` event like this `$(document).on('connected.jsxc', YOUR_FN)`. Maybe also the ` defaultAvatar` option is interesting for you:

https://github.com/jsxc/jsxc/blob/47319f55b3cd42f0e4c80363c9eecebc533e91b4/src/jsxc.lib.options.js#L171-L177
