### ISSUE TITLE
[Nextcloud] Undefined index: loginForm

### ISSUE THREAD

**Issue by theonlytruth** [jsxc/jsxc#671]
### Expected behavior
- no error logs

### Actual behavior
- error in nextcloud logs every time I open my options menu:
Undefined index: loginForm at /var/www/html/nextcloud/apps/ojsxc/settings/personal.php#22

### Steps to reproduce the behavior
1. Install JavaScript XMPP Chat  App
2. Open options menu of nextcloud
3. See logs of nextcloud

### Environment
- **Host system and version:** Nextcloud 13.0.0
- **Browser vendor and version:** Firefox
- **Server-OS:** Ubuntu 16.04

#### Host

``` Undefined index: loginForm at /var/www/html/nextcloud/apps/ojsxc/settings/personal.php#22 ``` 

It would be nice if those error logs wouldn't appear.

**Comment by sualko** [comment]
This has been already fixed in https://github.com/nextcloud/jsxc.nextcloud/commit/b3ac678d3b02f022f8315ad8f7991c50c2365bdf

**Comment by bazsodombiandras** [comment]
Keep getting this several times per minute in the log of Nextcloud 14:

Undefined index: externalConnectable at /var/www/html/nextcloud/apps/ojsxc/templates/settings/personal.php#36
