### ISSUE TITLE
BOSH server NOT reachable or misconfigured

### ISSUE THREAD

**Issue by basildane** [jsxc/jsxc#674]
### Expected behavior
Plugin connects to BOSH server

### Actual behavior
Error message:
Cross domain request was not possible. Either your BOSH server does not send any Access-Control-Allow-Origin header or the content-security-policy (CSP) blocks your request. Starting from Owncloud 9.0 your CSP will be updated in any app which uses the appframework (e.g. files) after you save these settings and reload.The savest way is still to use Apache ProxyRequest or Nginx proxy_pass.

### Steps to reproduce the behavior
1. Install plugin into NextCloud
2. Configure plugin: BOSH url: http://jabber.dmz.aquila.local:5280/http-bind/
3. Update NextCloud Apache2 site, add:
    ProxyPass /http-bind/ http://jabber.dmz.aquila.local:5280/http-bind/
    ProxyPassReverse /http-bind/ http://jabber.dmz.aquila.local:5280/http-bind/

### Environment
- **JSXC version:** 
3.3.2
- **Host system and version:** 
NextCloud 13.
- **Browser vendor and version:** 
N/A
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
ejabberd
- **Is your XMPP server working with other clients as expected?** 
Yes working.  I also installed pidgin and wireshark and verified that I'm connecting via BOSH.

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by MarcelWaldvogel** [comment]
The `ProxyPass` statements are on the *Nextcloud* `<VirtualHost>`? And you can connect with *Pidgin* to that BOSH URL (not only to the one you proxy to, `jabber.dmz.aqula.local`?

**Comment by basildane** [comment]
Yes, I put that ProxyPass line on the NextCloud :80 vhost and restarted Apache2.
Yes, I can login with Pidgin to http://jabber.dmz.aquila.local:5280/http-bind/

And to verify that I checked it with WireShark.
My xmpp domain is aquilatech.com.  The local address here is just for internal operations.  It is open to both servers.

**Comment by sualko** [comment]
Yes, it's not working, because you are not using your proxy. So your bosh url in the admin settings should be `/http-bind/`.

**Comment by basildane** [comment]
This is what I have...

 -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
      "/http-bind": mod_bosh
    web_admin: true
    http_bind: true
    register: true
    captcha: false

**Comment by basildane** [comment]
It just occurred to me that "So your bosh url in the admin settings should be /http-bind/" may be referring to the cloud configuration?

So I tried putting /http-bind/ into the url for Bosh on NextCloud.

That returns: 
Invalid XML received. Maybe https://cloud.aquilatech.com/http-bind/ was redirected. You should use an absolute url.

**Comment by basildane** [comment]
I now understand you.  This works.  Thanks for the explanation.

**Comment by sualko** [comment]
You are welcome

**Comment by gerroon** [comment]
@basildane 

I am having almost the same issue. How did you resolve this?

**Comment by basildane** [comment]
I had to explicitly list my proxy in the apache2 config file.
Add to 000-ssl.conf

                ProxyPass /http-bind/ http://jabber.dmz.aquila.local:5280/http-bind/
                ProxyPassReverse /http-bind/ http://jabber.dmz.aquila.local:5280/http-bind/

**Comment by MarcelWaldvogel** [comment]
@gerroon What happens if you go to the "external" HTTP-BIND URL in your browser?

**Comment by sahalshn** [comment]
I am facing CORS issue  Access to XMLHttpRequest at 'localhost:5280/http_bind' from origin 'http://localhost:4200' has been blocked by CORS policy: Cross origin requests are only supported for protocol.
'http://localhost:4200' this is an angular application trying to connect xmpp using node-xmpp-client

**Comment by sualko** [comment]
> this is an angular application trying to connect xmpp using node-xmpp-client

So I suggest, you open an issue in the angular or node-xmpp-client repository. :man_facepalming:

**Comment by sahalshn** [comment]
> node-xmpp-client

Do you have sample project using node-xmpp-client
