### ISSUE TITLE
CONNFAIL: item-not-found

### ISSUE THREAD

**Issue by NeemitShastri** [jsxc/jsxc#675]
Hi,
  we are using jsxc client, while connecting it fails and show following error,

We are already connected and authenticated
CONNFAIL: item-not-found
XMPP connection failed: item-not-found
DISCONNECTED: item-not-found
Try to relogin
I am not able to relogin

**Comment by sualko** [comment]
Please use the issue template.

**Comment by MarcelWaldvogel** [comment]
Followed-up on #676
