### ISSUE TITLE
CONNFAIL: item-not-found

### ISSUE THREAD

**Issue by NeemitShastri** [jsxc/jsxc#676]
### Steps to reproduce the behavior
- after login into jsxc it shows error as mentioned below in javascript(chrome console),
if i clear localstorage then it works and after sometime then it disconnects with the same error

### Environment
- jsxc 3.3.2
- Amazon (aws)
- Chrome  64 
- No Browser plugin enabled 
- ejabberd 17.04 
- other clients are working properly with ejabberd 

#### Javascript (chrome console) 
CONNFAIL: item-not-found
jsxc.js?380500:183 XMPP connection failed: item-not-found
jsxc.js?380500:183 DISCONNECTED: item-not-found
jsxc.js?380500:183 Try to relogin
jsxc.js?380500:183 I am not able to relogin

#### JSXC
after enabling debug mode it gives following error and disconnects :-

`<body xmlns="http://jabber.org/protocol/httpbind" type="terminate" condition="item-not-found"/>`

**Comment by sualko** [comment]
There are multiple reasons for this error message, but your log is to short to determine the exact one. Also your steps to reproduce the issue could be a little bit more verbose. To make a long story short, please provide more logs and information about how the reproduce the issue.

**Comment by NeemitShastri** [comment]
we had changed some code related to vcard which was causing problem rolled back it is working fine, thanks for your help :)
