### ISSUE TITLE
Placeholder avatars in chat differ from nextcloud

### ISSUE THREAD

**Issue by kort3x** [jsxc/jsxc#678]
### Expected behavior
Contacts with no profile picture should show same placeholder avatar as nextcloud

### Actual behavior
In chat first letter of _username_ is shown while in nextcloud the first letter of _full name_ is shown

### Environment
- **JSXC version:**
3.3.2
- **Host system and version:** 
nextcloud 13.0.0

**Comment by sualko** [comment]
Should be fixed in https://github.com/nextcloud/jsxc.nextcloud/commit/1c69ef1b1fa3ad24e4036ad04905458dd72d75c0. If you have time to test this small fix, we would be happy to hear from you.
