### ISSUE TITLE
Managed Server Registration failed

### ISSUE THREAD

**Issue by gt2416** [jsxc/jsxc#679]
Hi, when I try to register for a managed server using nextcloud I get the error

"Cannot find your host xxxxx.home: [Errno -2] Name or service not known ... "
Request ID: a3LjlLdFAom7kgMC9twB

I believe this is because the API key is using my default server name which is a internal dns name.
I have certs for my external dns to access nextcloud but my server name is internal.
I was wondering if there was a way I could change that part of the api url, if that would work.
"https://xxx.home/index.php/apps/ojsxc/ajax/externalApi.php"

The xxxx.home is the problem I think.

**Comment by MarcelWaldvogel** [comment]
The managed server needs to be able to reach your Nextcloud based on your domain name. This does not appear to be name entered in the global domain name system.

**Comment by gt2416** [comment]
Ok if I added a seccond domain name to my config file would that work ?

**Comment by sualko** [comment]
You probably have to access your Nextcloud via the public reachable DNS entry.

**Comment by gt2416** [comment]
^ Yes I do. Is that a problem ?
