### ISSUE TITLE
Passwordless Authentication (CAS, Shibboleth, …)

### ISSUE THREAD

**Issue by headstorm21** [jsxc/jsxc#680]
Hello,

I have a small configuration problem and I hope you can help me.

I developed a php application on laravel 5 and I installed JSXC to offer my users a chat.
I use an openfire server for the xmpp protocol and an apereo jasig server for the CAS authentication, the xmpp server already accepts the CAS connections.
With JSXC, I can currently connect my users with plain text authentication but don't know how to configure JSXC for CAS authentication.

I thank you in advance for your help.

**Comment by MarcelWaldvogel** [comment]
When access to the password is inconvenient or impossible, you can use the time-limited tokens https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Protocol.md#time-limited-token, the preferred way of using the accounts in JSXC for Nextcloud.

I hope this option suits you as well.

**Comment by MarcelWaldvogel** [comment]
[Here is PHP code that generates the token](https://github.com/jsxc/xmpp-cloud-auth/blob/master/xclib/tests/generateTimeLimitedToken). Create a secret with at least 128 bits entropy, e.g. with `uuidgen -r` or (from PHP) with [`random_bytes()`](http://php.net/manual/en/function.random-bytes.php) or the [compatibility implementation](https://github.com/paragonie/random_compat). In Nextcloud, we use:

```php
$apiSecret = \OC::$server->getSecureRandom()->generate(23);
```

Anyone with access to that secret can impersonate anyone in the chat, so keep it tight.

BTW: We always love to hear how JSXC is used. Would you mind telling us a little bit more? (also to marcel@jsxc.ch, if you prefer)

**Comment by headstorm21** [comment]
Hello,

Thank you for your reply. I'm sorry for this late response, but I don't understand how to set up the authentication you describe. I don't use nextcloud / owncloud, I use a php application developed by myself under Laravel.

Thank you for your help.

**Comment by sualko** [comment]
Please have a look at the linked protocol. It should solve your issue.

**Comment by Layenzz** [comment]
Hello,
I have the same problem with my laravel app, i use OpenFire as XMPP server, indeed, i tryed to use your answer, but i can't connect, i have my token generate with this :

```
public function generateUser($node, $domain, $secret, $ttl = 60 * 60, $time = null)
    {
        if (!isset($time) || $time === null) {
            $time = time();
        }
        $jid = $node. '@' . $domain;
        $expiry = $time + $ttl;
        $version = hex2bin('00');
        $secretID = substr(hash('sha256', $secret, true), 0, 2);
        $header = $secretID.pack('N', $expiry);
        $challenge = $version.$header.$jid;
        $hmac = hash_hmac('sha256', $challenge, $secret, true);
        $token = $version.substr($hmac, 0, 16).$header;
        // format as "user-friendly" base64
        $token = str_replace('=', '', strtr(
            base64_encode($token),
            'OIl',
            '-$%'
        ));
        return $token;
    }
```

My call to generateUser() :

```
if(!isset($_SESSION['chatKey'])){
            $_SESSION['chatKey'] = $this->generateUser(Cas::getUser(), '[myDomain]', random_bytes(128), null, null);
        }
```

And my html page :

```
var username = "{{ $uid }}";
var password = "<?php if(isset($_SESSION['chatKey'])) echo $_SESSION['chatKey']; ?>";
var jid = username + '@[myDomain]';
jsxc.start(jid , password);
```

But i have to connect manually with jsxc's interface, do you have suggestions or ideas ? @MarcelWaldvogel @sualko 

Thanks.

**Comment by sualko** [comment]
Does OpenFire supports saslauthd? Because you can't just replace your password with the token.

**Comment by Layenzz** [comment]
Hi, first, thank for your answer, second, OpenFire doesn't support saslauthd, it just support :
```
 CRAM-MD5
 DIGEST-MD5
 GSSAPI
 JIVE-SHAREDSECRET
 SCRAM-SHA-1
 PLAIN
```

Do you have any suggestion ?

**Comment by sualko** [comment]
> Do you have any suggestion ?

Use the same authentication backend for your XMPP server and webapplication, or switch to another XMPP server which is supported by our authentication script.
