### ISSUE TITLE
huge amount of error messages: Undefined index: loginForm at...

### ISSUE THREAD

**Issue by xpilgrim** [jsxc/jsxc#682]
### Actual behavior
huge amount of error messages in nexcloud log:
`Undefined index: loginForm at /var/w...l/nextcloud/apps/ojsxc/settings/personal.php#22`
I've connection issues of the desktop client. I don't know if here is a interconnection.

### Environment
- **JSXC version:** jsxc.ch/managed.
- **Host system and version:** NC 13
- **Browser vendor and version:** Chrome 
- **Is your XMPP server working with other clients as expected?** yes

#### Javascript

```JQMIGRATE: Migrate is installed, version 1.4.0
jsxc.js:183 State changed to INITIATING
jsxc.js:183 Try to relogin
jsxc.js:183 I am not able to relogin
jsxc.js:183 State changed to SUSPEND
DevTools failed to parse SourceMap: https://...nextcloud/core/vendor/purify.min.js.map
```

**Comment by sualko** [comment]
This has already be fixed in https://github.com/nextcloud/jsxc.nextcloud/commit/b3ac678d3b02f022f8315ad8f7991c50c2365bdf and it's unlikely that this influences your desktop connection.
