### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [jsxc/jsxc#683]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?
- https://www.jsxc.org/features.html

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by sualko** [comment]
It's possible for sure :smile_cat:. If you like you can help us and open a pull request at https://github.com/jsxc/jsxc.org

**Comment by Neustradamus** [comment]
@sualko: It will be good for 4.0?

**Comment by Neustradamus** [comment]
Currently, we have not all versions supported, not easy to update it.

**Comment by sualko** [comment]
Most XEP versions are now shown in the settings dialog. If you like you can extract that information and make a pull request on https://github.com/jsxc/jsxc.org for the feature page.
