### ISSUE TITLE
Managed (Beta service) registration failed

### ISSUE THREAD

**Issue by webmaisterpro** [jsxc/jsxc#685]
I've tried to register to Beta service in the last 2 days, but all attempts failed. Can you assist me please?

### Actual behavior

Sorry we couldn't complete your registration.

Couldn't reach the registration server

Please report this to our issue tracker and mention the request id DSiijjahAe315Lo4SkQp.

### Steps to reproduce the behavior
1. Managed service
2. Acknoledged bete service TOS
3. Registration failed 

### Environment
- **JSXC version:**  3.3.2
- **Host system and version:**  NextCloud 13.0.1
- **Browser vendor and version:**  Mozilla 59.0.1
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by MarcelWaldvogel** [comment]
I cannot confirm this on our side. Also, several users have had success registering in the past few days. The registration process talks to https://xmpp.jsxc.ch/registration . Could it be that this is blocked by your firewall or similar? Do the logs say anything more?

**Comment by MarcelWaldvogel** [comment]
(Pointing your web browser at that URL will result in a HTTP/400 error with content `{"message": "Registration Parameter Error: Missing parameters"}`. That is ok, as the web browser does not specify all the information. Other errors are for real.)

**Comment by webmaisterpro** [comment]
Here are the last few entries in NextCloud.log file:

{"reqId":"WrOGY1Z8ZAGGJORdfOYbPQAAAAw","level":3,"time":"2018-03-22T10:33:07+00:00","remoteAddr":"1.2.233.207","user":"kalseo","app":"PHP","method":"GET","url":"\/cloud\/index.php\/settings\/admin\/ojsxc","message":"Undefined index: loginForm at \/home\/synencrypt84\/public_html\/cloud\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"WrOGaEkXa6B5f0G7-OLP9AAAAAI","level":3,"time":"2018-03-22T10:33:13+00:00","remoteAddr":"1.2.233.207","user":"kalseo","app":"PHP","method":"POST","url":"\/cloud\/index.php\/apps\/ojsxc\/managedServer\/register","message":"file_get_contents(): https:\/\/ wrapper is disabled in the server configuration by allow_url_fopen=0 at \/home\/synencrypt84\/public_html\/cloud\/apps\/ojsxc\/lib\/DataRetriever.php#18","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"WrOGaEkXa6B5f0G7-OLP9AAAAAI","level":3,"time":"2018-03-22T10:33:13+00:00","remoteAddr":"1.2.233.207","user":"kalseo","app":"PHP","method":"POST","url":"\/cloud\/index.php\/apps\/ojsxc\/managedServer\/register","message":"file_get_contents(https:\/\/xmpp.jsxc.ch\/registration?rid=QNzINTRn10ZpuvnbHqZd): failed to open stream: no suitable wrapper could be found at \/home\/synencrypt84\/public_html\/cloud\/apps\/ojsxc\/lib\/DataRetriever.php#18","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"WrOGaEkXa6B5f0G7-OLP9AAAAAI","level":2,"time":"2018-03-22T10:33:13+00:00","remoteAddr":"1.2.233.207","user":"kalseo","app":"no app in context","method":"POST","url":"\/cloud\/index.php\/apps\/ojsxc\/managedServer\/register","message":"RMS: Abort with message: Couldn't reach the registration server","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}

**Comment by webmaisterpro** [comment]
After changing  

allow_url_fopen = On

The registration was successful. The first attempt timed out, but the 2nd worked like a charm! 
Thank you!

**Comment by MarcelWaldvogel** [comment]
I am glad it works now. Enjoy!

We use Let's Encrypt to create the certificates on the fly. They seem to be a bit slow this morning (certificate issuance can take about one minute); I already told them. (You can reregister as often as you want, it reuses all the state that was previously established.)

@sualko Can you include a comment about the `php.ini` change into that error message? And increase the timeout?

**Comment by MarcelWaldvogel** [comment]
@sualko Is there a reason that `allow_url_fopen` should make a difference? JSXC client is not using `fopen()` for the registration, is it?

**Comment by sualko** [comment]
> JSXC client is not using fopen() for the registration, is it?

`file_get_contents` is a wrapper for `fopen`. I'm not aware of any different solution.
