### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable - php 7.2

### ISSUE THREAD

**Issue by si458** [jsxc/jsxc#686]
### Expected behavior

no errors

### Actual behavior

count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/ojsxc/lib/newcontentcontainer.php#36

count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/ojsxc/lib/Controller/HttpBindController.php#181

### Steps to reproduce the behavior
1. install php 7.2 and nextcloud
2.
3.

### Environment
- **JSXC version:** nextcloud
- **Host system and version:** nextcloud 3.0.1
- **Browser vendor and version:** any
- **Any browser plugins enabled?** nope
- **XMPP server vendor and version:** javascript - built in
- **Is your XMPP server working with other clients as expected?** no

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
cc @LEDfan
