### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ismailmohammed** [jsxc/jsxc#691]
HI,

Can't we login in two different tabs with two different logins? when I am doing getting error
Cannot read property 'caps' of null

Please help.

**Comment by MarcelWaldvogel** [comment]
JSXC syncs the state over all tabs going to the same site to provide a coherent user interface. If you need to log in with multiple accounts *for testing*, use
* Multiple browsers (e.g. Firefox+Chromium)
* "Private Browsing"
* "Container Tabs" in Firefox

If you need to log in with multiple accounts *in production*, you should also consider using a native XMPP client.

**Comment by ismailmohammed** [comment]
ok thanks, I will use multiple browsers for testing.
