### ISSUE TITLE
JSXC Register new user into XMpp server

### ISSUE THREAD

**Issue by ismailmohammed** [jsxc/jsxc#692]
Hi,
I am using Core jsxc V3.3.1.

Is there any function or code available for registering new user into XMPP server. as of now, I am creating a user on the server and testing in JSXC client. 

I want to integrate jsxc into my web application. where we already have SQL authentication to my web application after validating I want to authenticate XMPP server then open the side view of jsxc, how to do this?

Please help me.
Thank you.

**Comment by MarcelWaldvogel** [comment]
JSXC does not directly do that. There are two ways to do it, that come to mind:
* Use the same user backend for both the XMPP server and the web application. (The traditional way)
* Configure the XMPP server to ask the web application whether a particular user exists.

The former is what I would recommend if you design the system from scratch; especially when using LDAP as the backend (or something else both sides support).

The latter is what we use in the Nextcloud app: We include a [hook](https://github.com/nextcloud/jsxc.nextcloud/blob/master/lib/Controller/ExternalApiController.php) in Nextcloud, where the XMPP server can ask for user existence, password correctness, and optionally group information. There is a [Protocol description](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Protocol.md) available and a [server-side implementation](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Protocol.md).
