### ISSUE TITLE
JSXC RELOGIN ISSUE

### ISSUE THREAD

**Issue by sunstar20** [jsxc/jsxc#694]
HI,

I have integrated ejabberd chat client in our project by integrating core jsxc. 

Even after logging as admin, chat roster is not open at times and the message is shown often to relogin. Could you please help.

Thanks in advance

![image](https://user-images.githubusercontent.com/12511931/38451511-be33bd10-3a4e-11e8-9416-0b2615df740a.png)

**Comment by sualko** [comment]
Please use the issue template.
