### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by Tennekh** [jsxc/jsxc#699]
### Expected behavior
I'd like to register for the managed beta service directly from Nextcloud.
### Actual behavior
Your Nextcloud server cannot be used because [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590). Please report this to our issue tracker and mention the request id Tv67PxqTE4xUkgQED3uE.

The problem seems to be that I use a self-signed SSL certificate?

### Steps to reproduce the behavior
1. Nextcloud
2. Settings
3. JavaScript Xmpp Client
4. Managed (Beta Service)
5. I acknowledge that this is a beta service offered by the Federated Communication Association without any warranty whatsoever.
6. Register

### Environment
- **JSXC version:** 3.3.2
- **Host system and version:**  Nextcloud 13.0.2
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
We support only valid certificates, because with letsencrypt.org it's super easy to get one.
