### ISSUE TITLE
Nextcloud integration, Burger menu hidden

### ISSUE THREAD

**Issue by aicherm** [jsxc/jsxc#704]
Hey,
not sure if this is the right place since this is related to the Nextcloud implementation.

- Background details:

I'm using an external server via BOSH. The BOSH server URL is different from my Nextcloud URL as well as from my ejabberd domain. (Different subdomains)
Also my username/password differs from the Nextcloud settings.
Nextcloud 13.0.2
JavaScript XMPP Chat	3.4.0
Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)

- Admin settings:

Prefer mail address to loginName@xmppDomain FALSE
Allow user to overwrite XMPP settings TRUE

- Bug

When I want to login I open the speech bubble on top and a sidebar opens. It looks the following:
![screenshot from 2018-05-23 20-30-28](https://user-images.githubusercontent.com/876811/40444270-28298b5c-5ec9-11e8-884d-89b18e408a14.png)
(Its german: No connection. New registration)
As you can see there is not burger menu button at the bottom. jsxc_bottom is missing and therefore I cannot access the settings menu where I have to set my XMPP domain name.
There is this entry in the css file:
`  #jsxc_roster.jsxc_noConnection > .jsxc_bottom {
    display: none; }`
I cannot connect since I can't change my domain settings, but I cannot change it since I'm not connected. It's a deadlock here.
The workaround is to go into the developer tools of the browser, remove the line from the CSS file. Do the settings, reload the site and login.

Cheers,
Moritz

**Comment by sualko** [comment]
Thanks for taking the time to fill a bug report. I have good news for you: We already fixed this in the upcoming 4.0. So stay tuned and sorry that this will not be backported to 3.x.

![5b8fe388-9a7b-4375-9184-ce36b542ccc2](https://user-images.githubusercontent.com/2974196/40660135-6dcfdbd0-6350-11e8-995d-64f350cc6067.png)
