### ISSUE TITLE
Room File Transfer, File not receiving by other group members

### ISSUE THREAD

**Issue by ismailmohammed** [jsxc/jsxc#705]
Hi,

1. Please help me on file transfer in the group. I am able to send and receive the files in One - one chat.
But when it comes to group chat, If I send a file in a group then I am able to see a success message in the console but other group members are not receiving the file. I able to chat in group level only file transfer issue.

here is the ejabberd config file,

mod_http_upload:    
    max_size: infinity
    service_url: "https://api.ASDFG.net/api/UserProfiles/JabberUpload"   
    thumbnail: false # otherwise needs the identify command from ImageMagick installed
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
      "Access-Control-Allow-Headers": "Authorization"
      "Access-Control-Allow-Credentials": "true"    
  mod_http_upload_quota:
     max_days: 30  

Below is the message from the console.

**Send file via http upload
slot received, start upload to https://api.ASDFG.net/api/UserProfiles/PutJabberFile?jid=ismail@asdfg.com&fileName=ejabberedlogin.txt
file successful uploaded**

2. Unable to do video call. When i call other personal he is able to receive the call when he clicks on accept incoming call button we are getting this error **Media failure: An unknown error occurred. (NotReadableError).**

Thanks in advance.
Regards,
Md.Ismail

**Comment by sualko** [comment]
First of all: One report = one issue and please use the issue template. So I close this issue and please open a new one if you like.

[The description](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) for the NotReadableError says the following:
> Although the user granted permission to use the matching devices, a hardware error occurred at the operating system, browser, or Web page level which prevented access to the device.

**Comment by ismailmohammed** [comment]
Thank you sualko and sorry for not following format will do it from next time

**Comment by ismailmohammed** [comment]
Hi sualko,

Please help me on file transfer in the group. I am able to send and receive the files in One - one chat.
But when it comes to group chat, If I send a file in a group then I am able to see a success message in the console but other group members are not receiving the file.  

here is the ejabberd config file,

mod_http_upload:
max_size: infinity
service_url: "https://api.ASDFG.net/api/UserProfiles/JabberUpload"
thumbnail: false  
custom_headers:
"Access-Control-Allow-Origin": "*"
"Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
"Access-Control-Allow-Headers": "Authorization"
"Access-Control-Allow-Credentials": "true"
mod_http_upload_quota:
max_days: 30

Below is the message from the console.

Send file via http upload
slot received, start upload to https://api.ASDFG.net/api/UserProfiles/PutJabberFile?jid=ismail@asdfg.com&fileName=ejabberedlogin.txt
file successful uploaded 

Please help us looking for your response asap.
Thanks in advance.
Ismail.

**Comment by sualko** [comment]
Enable debugging and post a more detailed log.

**Comment by ismailmohammed** [comment]
Hi sualko,

Thanks for your response.

After my investigation I found that in **localStorage** we have member object which contains the group details, here I found that other group members JID's are NULL because of this reason other groups members not receiving anything when file transferred. I have fixed that issue now other members are receiving a message but not files for download.

I am Saving the files in S3 so we are getting S3 link for download as below.

![image](https://user-images.githubusercontent.com/10510073/41905770-c1376396-7959-11e8-8d9a-033ef4625af0.png)

but in one- one chat we are receiving files as below, I need same way like below in group chat for download.

![image](https://user-images.githubusercontent.com/10510073/41905841-ef261068-7959-11e8-9d65-5c6f0110d184.png)

Please help me where and what I am missing.

I am using jsxc for my web application.

Thank you.
Ismail.

**Comment by sualko** [comment]
As far as I understand you, the file transfer (url transfer) is working, but you don't see the preview. Is that right?

**Comment by sualko** [comment]
This should be easy to fix, it will be part of the next bug fix release. Stay tuned.

**Comment by ismailmohammed** [comment]
Thank you
