### ISSUE TITLE
Status of sogo integration

### ISSUE THREAD

**Issue by jas01** [jsxc/jsxc#706]
Hi.
Don't know if it's the right place to ask a question, if it's not, very sorry.

I would like to know the status of jsxc integration with sogo, is it abandonned project, useless (don't need anything to integrate with sogo), etc. If I ask it's because the project stop a 3.3.0 beta1. Seem very strange.

Regards

**Comment by sualko** [comment]
As there was not much love from the sogo community and due to limited time we decided to stop the sogo development. We would really appreciate if there were a volunteer to maintain the sogo version :wink:.
