### ISSUE TITLE
Client is not working after update to NC v13.0.2 / IMAP User Authentication

### ISSUE THREAD

**Issue by BMTTeam** [jsxc/jsxc#707]
### Expected behavior
Users are using their emails as username and are authenticated against IMAP server
### Actual behavior
After upgrade of NC to v13.0.2 and jsxc v3.4.0, front page is not working (Internal Server Error).
### Steps to reproduce the behavior
1. Enable jsxc with NC v13.0.2
2. Open NC URL
3. To restore NC operation, disable jsxc app from command line using "occ"

### Environment
- **JSXC version:*3.4.0* 
- **Host system and version:*NextCloud v13.0.2* 
- **Browser vendor and version:*Firefox 59.0.2 (64bit)* 
- **Any browser plugins enabled?*AdBlocker for Facebook, Mining Blocker, Enhancer for Youtube* 
- **XMPP server vendor and version:*the basic installation, that came with the app* 
- **Is your XMPP server working with other clients as expected?*N/A* 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
This has already been fixed in https://github.com/nextcloud/jsxc.nextcloud/commit/0508c9b2a3ae8756df1a912d83f93b633b4b110d and will be shipped with the next release. Sorry for the inconvenience.

**Comment by sualko** [comment]
Thanks for the confirmation :+1:
