### ISSUE TITLE
JSXC example never logs in despite BOSH server reachable

### ISSUE THREAD

**Issue by truenicoco** [jsxc/jsxc#710]
### Expected behavior

Open JSXC app, list my buddies, chat…

### Actual behavior

Stays stuck on *Connecting…*

### Steps to reproduce the behavior

1. Create an account on my XMPP server nicoco.fr
2. Go to [the JSXC example app](https://www.jsxc.org/example/)
3. Enter nicoco.fr as the domain https://nicoco.fr:5281/http-bind as the BOSH url
4. Try to log in

### Environment

- **JSXC version:** 3.4.0
- **Host system and version:** Debian Stretch, up-to-date
- **Browser vendor and version:** Firefox 60.0.1 (also tried with chomium from debian repos)
- **Any browser plugins enabled?**  Doesn't work even when they are all disabled
- **XMPP server vendor and version:** prosody 0.10.2, mod_bosh, https through nginx reverse proxy
- **Is your XMPP server working with other clients as expected?**  Yes

### Notes

Everything seems to be working according to the logs. The example app even displays:

> BOSH Server reachable.

Unfortunately, something seems to block the login process. One of prosody devs tried the app on his own instance and it worked, and I couldn't find what was different in his case.

#### Javascript

Nothing

#### JSXC

```
jsxc.enableDebugMode()
undefined
State changed to ESTABLISHING
jsxc.js:183:9
New connection
jsxc.js:183:9
CONNECTING: null
jsxc.js:183:9
> 
<body rid="1838547901" xmlns="http://jabber.org/protocol/httpbind" to="nicoco.fr" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh">
jsxc.js:1221:12
< 
<body xmlns:stream="http://etherx.jabber.org/streams" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh" ver="1.6" inactivity="60" requests="2" polling="5" secure="true" hold="1" from="nicoco.fr" authid="3d09d44e-e095-43c4-9fec-37c7266019c6" wait="60" sid="3d09d44e-e095-43c4-9fec-37c7266019c6" xmlns="http://jabber.org/protocol/httpbind">
jsxc.js:1218:12
> 
<body rid="1838547902" xmlns="http://jabber.org/protocol/httpbind" sid="3d09d44e-e095-43c4-9fec-37c7266019c6">
jsxc.js:1221:12
< 
<body sid="3d09d44e-e095-43c4-9fec-37c7266019c6" xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind">
jsxc.js:1218:12
> 
<body rid="1838547903" xmlns="http://jabber.org/protocol/httpbind" sid="3d09d44e-e095-43c4-9fec-37c7266019c6">
jsxc.js:1221:12
```

#### XMPP: prosody.log

```
Jun 18 10:50:51 mod_bosh	info	New BOSH session, assigned it sid '3d09d44e-e095-43c4-9fec-37c7266019c6'
```

#### Nginx

```
138.96.203.17 - - [18/Jun/2018:10:53:16 +0200] "POST /http-bind HTTP/1.1" 200 148 "https://www.jsxc.org/example/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

No error in any log I could find.

**Comment by sualko** [comment]
Your XMPP server returns an empty answer or to be precise didn't advertise any SASL authentication mechanism (or is there something missing in your log):

```
<body xmlns:stream="http://etherx.jabber.org/streams" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh" ver="1.6" inactivity="60" requests="2" polling="5" secure="true" hold="1" from="nicoco.fr" authid="3d09d44e-e095-43c4-9fec-37c7266019c6" wait="60" sid="3d09d44e-e095-43c4-9fec-37c7266019c6" xmlns="http://jabber.org/protocol/httpbind">
```

Btw I just saw that I missed to update the example to the latest version, so please try again.

**Comment by truenicoco** [comment]
Thanks a lot for helping me investigate this. This is probably a misconfiguration on the prosody side but I guess the debug logs for JSXC should mention something is wrong…

I had already tried the latest github version locally. I just tried again on the official  website, just to make sure, but as expected, the behaviour is the same.

I'm looking into this SASL authentication mechanism advertising on the prosody/nginx side…

**Comment by sualko** [comment]
Even if we use an older version (1.2.14), there is a discussion in the strophejs repository https://github.com/strophe/strophejs/issues/299 about a similar issue. Maybe it's helpful.

**Comment by truenicoco** [comment]
While trying to fix this, I now have a different issue and I can't figure out why but this looks like something is wrong on the JSXC side:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nicoco.fr:5281/http-bind/. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Nothing seems wrong on the nginx/prosody side:

```
$ curl -v https://nicoco.fr:5281/http-bind/
[...]
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
< Access-Control-Expose-Headers: Content-Length,Content-Range
[...]
```

**Comment by sualko** [comment]
This message is coming from your browser, so this is no issue with JSXC. On my last try I got the following:

```
Failed to load https://nicoco.fr:5281/http-bind/: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
```
The header looks like this:
```
Request URL: https://nicoco.fr:5281/http-bind/
Request Method: POST
Status Code: 200 OK
Remote Address: 213.32.90.179:5281
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Range
Access-Control-Max-Age: 7200
Connection: keep-alive
Content-Length: 657
Content-Type: text/xml; charset=utf-8
Date: Wed, 20 Jun 2018 10:27:02 GMT
Server: nginx/1.10.3
```

**Comment by truenicoco** [comment]
This is odd. Anyway, I had no problem connecting with converse.js, so I'm still thinking this is JSXC related. Let me know if you want more informations on my configuration or logs.

**Comment by MarcelWaldvogel** [comment]
> ```
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Origin: *
> ```

@truenicoco Could it be that in your NGINX configuration you have a statement akin to Apache's
```Apache
Header always set Access-Control-Allow-Origin *
```
(which, despite its description, does not delete a preexisting header of the same name)? Then you should remove them.

**Comment by truenicoco** [comment]
I fixed that in prosody config by setting cross_domain_bosh and consider_bosh_secure to false, since it's in fact nginx that handles this.

I realized that conversejs in fact uses its own BOSH endpoint https://conversejs.org/http-bind/ so I guess my BOSH endpoint is after all the problem, as @sualko pointed out:

> Your XMPP server returns an empty answer or to be precise didn't advertise any SASL authentication mechanism (or is there something missing in your log)

I am trying to get some help from the prosody channel but without success so far…

**Comment by truenicoco** [comment]
So, JSXC was not responsible at all, I apologize.

For the record, I had to leaver consider_bosh_secure to true, since I'm reverse proxying with nginx… Sorry for the trouble and thank you for your time.
