### ISSUE TITLE
How can we implement this package in angular 5

### ISSUE THREAD

**Issue by iAakashTomar** [jsxc/jsxc#711]
can we implement this package in angular 5? if yes then how?
please help

**Comment by iAakashTomar** [comment]
okay let me read 👍

**Comment by MarcelWaldvogel** [comment]
@MarcelWaldvogel on behalf of @jsxc-bot: You are welcome! ;-)

https://github.com/jsxc/jsxc/wiki has more information than the issues jsxc-bot mentioned. We are not into Angular, but if you have any specific questions, we'll try our best.

**Comment by iAakashTomar** [comment]
I am able to implement jsxc with the help of javascript via this link:- https://github.com/jsxc/jsxc/wiki/Install-jsxc
but I want to implement jsxc into my angular 5 project. if you can help then it would be great for me :)
thanks

**Comment by iAakashTomar** [comment]
thanks for the help.
working now

**Comment by iAakashTomar** [comment]
thanks for the help.
working now

**Comment by khaled1211** [comment]
@iAakashTomar  can you help me tp implement jsxc on my angular project!!!have you tutoriels!!documentaion!!
