### ISSUE TITLE
 没，没，  v    靠靠靠n

### ISSUE THREAD

**Issue by feikiss** [jsxc/jsxc#712]
### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by feikiss** [comment]
sorry, my baby clicked the keyboard randomly and send it out somehow...(Her's first bug report in the internet since come to the world ;-) -_-

**Comment by sualko** [comment]
I think he/she is probably our youngest contributor :tada:
