### ISSUE TITLE
Upload from Nextcloud and jscx is not working

### ISSUE THREAD

**Issue by Thomas301263** [jsxc/jsxc#713]
### Expected behavior
Uploads should be possible between 2 clients on the same xmpp server
### Actual behavior
Uploads are working between 2 android clients with conversations. Upload is working from an android client to nextcloud jsxc client but not from nextcloud jsxc to another client. 
Here I am getting on the web page of nextcloud  "Verbindung zum Server verloren"

### Steps to reproduce the behavior
1. Install Ubuntu 18.04 Kernel 4.15.0-23
2. Install PHP 7.2, Mariadb 10.1.29, nginx 1.14.0, letsencrypt
3. Install Nextcloud 13.0.4
4. setting up nginx shown here
https://www.c-rieger.de/nextcloud-13-nginx-installation-guide-for-ubuntu-18-04-lts/
5. Getting letsencryt certificate with multidomains   domain, xmpp.domain, pubsub.domain, upload.domain, conference.domain
6. Installing ejabberd 18.01
7. Configure ejabberd.yml

### Environment
- **JSXC version:** 
3.4.1
- **Host system and version:** 
ubuntu 18.04 Nextcloud 13.0.4
- **Browser vendor and version:** 
Firefox 61.0.1
- **Any browser plugins enabled?** 
NO
- **XMPP Server** 
Ejabberd 18.01
- **Is your XMPP server working with other clients as expected?** 
XMPP is working at all with android clients.

#### Javascript

```NO
```

#### JSXC

```
I do not understand how to work with Javascript Console
```

#### XMPP

ejabberd.log 

2018-07-15 14:49:52.409 [info] <0.432.0>@mod_http_upload:create_slot:573 Got HTTP upload slot for user@domain/90842573950253000771026 (file: Squirrel.jpg)
2018-07-15 14:49:52.475 [info] <0.294.0>@ejabberd_listener:accept:302 (<0.533.0>) Accepted connection X.X.X.X:46996 -> X.X.X.X:5280
That means the upload is started cause (file: Squirrel.jpg) was the file I tried to send.
```

#### Host
<!-- Do you have any related entries in your host system log? -

```
[ejabberd.txt](https://github.com/jsxc/jsxc/files/2195723/ejabberd.txt)

nginx access.log

X.X.X.X - - [15/Jul/2018:14:54:42 +0200] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
X.X.X.X - - [15/Jul/2018:14:54:53 +0200] "POST /http-bind/ HTTP/2.0" 200 115 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
X.X.X.X - - [15/Jul/2018:14:54:53 +0200] "POST /http-bind/ HTTP/2.0" 200 603 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"

All files were send internal between the same XMPP server

**Comment by MarcelWaldvogel** [comment]
Downloading from JSXC works, I presume.

The difference between a native client (e.g. Conversations) and a web-based client is that the browser will enforce [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policies. So the web server (ejabberd) must send [the appropriate headers](https://github.com/jsxc/jsxc/wiki/File-transfer). If you proxy ejabberd BOSH through nginx, also nginx might add the headers instead.

**Comment by sualko** [comment]
Please post your js log. There should be a CORS or Same-origin policy error. Add your upload host as an external service domain in the admin settings.

**Comment by sualko** [comment]
I close this due to inactivity.

**Comment by ostasevych** [comment]
Not working in the 4.0.0-rc version with nextcloud 17 :(

**Comment by sualko** [comment]
@ostasevych please open a new issue.

**Comment by ostasevych** [comment]
What do you mean? Should I re-test or just repeat this issue?
