### ISSUE TITLE
Input #jsxc_username doesn't execute getUsers function

### ISSUE THREAD

**Issue by wongttchieng** [jsxc/jsxc#717]
### Expected behavior
Execute getUsers function and populate #jsxc_userlist
### Actual behavior
Debug if (typeof jsxc.options.getUsers === 'function') return false thus doesn't execute getUsers function
### Steps to reproduce the behavior
1. Open Add Contact dialog box
2. Input a character in the Username input textbox

### Environment
- **JSXC version:** Latest
- **Host system and version:**  nodejs http-server
- **Browser vendor and version:** Chrome
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Openfire 4.2.3
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
If `typeof jsxc.options.getUsers === 'function'` is false you didn't provide a `getUsers` function. Otherwise I don't understand your issue.

**Comment by sualko** [comment]
I close this due to inactivity.
