### ISSUE TITLE
Compatibility with Nextcloud 14

### ISSUE THREAD

**Issue by ChristophWurst** [jsxc/jsxc#718]
Hi,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We usually try to keep up compatibility with previous app versions, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827. You can run occ app:check-code to validate that there are no issues with deprecated or private message calls.

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14.

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket: .

**Comment by sualko** [comment]
Thanks for your kind reminder to update ojsxc. After updating Nextcloud to 14 beta.4 my admin settings were gone. Can it be possible that I have to use different section classes for personal and admin section in NC14? Is this an intended behavior or should I open an issue?

**Comment by ChristophWurst** [comment]
> Thanks for your kind reminder to update ojsxc. After updating Nextcloud to 14 beta.4 my admin settings were gone. Can it be possible that I have to use different section classes for personal and admin section in NC14? Is this an intended behavior or should I open an issue?

cc @blizzz @juliushaertl

**Comment by juliushaertl** [comment]
@sualko We have renamed some sections. Can you link me to the code, then I can have a look it if is affected.

**Comment by sualko** [comment]
https://github.com/nextcloud/jsxc.nextcloud/blob/9f342ec4455ad67f9960a152f28894dc22bd3490/appinfo/info.xml#L45-L50

I use my own section and discovered that with the linked config only the personal section is shown. If I remove the `personal-section` element my admin section is right back.

**Comment by sualko** [comment]
Thanks for looking at it, I will open an issue.

**Comment by sualko** [comment]
OJSXC is now compatible with NC 14.

**Comment by ChristophWurst** [comment]
Thank you, @sualko :v:
