### ISSUE TITLE
can't reg by managed(beta service)

### ISSUE THREAD

**Issue by jianbosu** [jsxc/jsxc#721]
### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

Sorry we couldn't complete your registration.

Couldn't parse the response. Response code: 500

Please report this to our issue tracker and mention the request id ui347I09e2aD39J5HdW6.

nextcloud log:

Warning | no app in context | RMS: Abort with message: Couldn't parse the response. Response code: 500
-- | -- | --

**Comment by jianbosu** [comment]
JQMIGRATE: Migrate is installed, version 1.4.0
jsxc.js:184 State changed to INITIATING
jsxc.js:184 State changed to PREVCONFOUND
jsxc.js:184 check master
VM1732:1 GET https://abc.abc.com/data/.ocdata?t=1534405037008 403 ()
(anonymous) @ VM1732:1
send @ core.js?v=8281a323-2:4
ajax @ core.js?v=8281a323-2:4
checkDataProtected @ setupchecks.js?v=8281a323-2:246
(anonymous) @ admin.js?v=8281a323-2:258
j @ core.js?v=8281a323-2:2
fireWith @ core.js?v=8281a323-2:2
ready @ core.js?v=8281a323-2:2
I @ core.js?v=8281a323-2:2
jsxc.js:184 I am master.
jsxc.js:184 State changed to ESTABLISHING
jsxc.js:184 Try to attach
jsxc.js:184 SID: internal
jsxc.js:184 ATTACHED: null
jsxc.js:184 Discover muc service
jsxc.js:184 UI State changed to INITIATING
jsxc.js:184 Waiting for server capabilities
jsxc.js:184 Request server capabilities
jsxc.js:184 UI State changed to READY
jsxc.js:184 DSA key loaded
jsxc.js:184 State changed to READY
jsxc.js:184 Presence (sfy@abc.abc.com/internal): offline
jsxc.js:184 Presence (wangzx@abc.abc.com/internal): offline
jsxc.js:184 Presence (wenlang@abc.abc.com/internal): offline
VM1732:1 POST https://abc.abc.com/index.php/apps/ojsxc/managedServer/register 500 ()
(anonymous) @ VM1732:1
send @ core.js?v=8281a323-2:4
ajax @ core.js?v=8281a323-2:4
(anonymous) @ admin.js?v=8281a323-2:237
dispatch @ core.js?v=8281a323-2:3
r.handle @ core.js?v=8281a323-2:3

**Comment by MarcelWaldvogel** [comment]
Thanks for reporting it! I have already fixed one problem, but we have a follow-up problem creating the certificates. I will look into this later today.

**Comment by MarcelWaldvogel** [comment]
It should work again (the first fix introduced a bad entry in the database). Could you please try again? Sorry for the inconvenience!

**Comment by MarcelWaldvogel** [comment]
Have you already have had a chance to try it again?

**Comment by sualko** [comment]
I close this due to inactivity and the bug should be solved.
