### ISSUE TITLE
Your Nextcloud server cannot be used because we could not connect: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by kominfotomohon** [jsxc/jsxc#722]
> Sorry we couldn't complete your registration.
> 
> Your Nextcloud server cannot be used because we could not connect: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
> 
> Please report this to our issue tracker and mention the request id u31h5wNhcDgNx9W87sEp.

My nextcloud server setup:

- Using Comodo SSL cert. & Key.
- Verified A+ by [Nextcloud Security Scan](https://scan.nextcloud.com/)

**Comment by kominfotomohon** [comment]
thank you for your response @MarcelWaldvogel, very useful for me who is still a beginner. I immediately implement it and report the results.

**Comment by MarcelWaldvogel** [comment]
According to my log, registration was successful, so I am closing this. Please reopen if there is need.
