### ISSUE TITLE
Undefined index: externalConnectable at /var/www/nextcloud/apps/ojsxc/templates/settings/personal.php#36

### ISSUE THREAD

**Issue by djpremier** [jsxc/jsxc#726]
ERROR -> Undefined index: externalConnectable at /var/www/nextcloud/apps/ojsxc/templates/settings/personal.php#36

### Environment
- **JSXC version:** 3.4.2
- **Host system and version:** Nextcloud 13.0.5
- **Browser vendor and version:** Firefox and Chrome (others not testing)
- **XMPP server vendor and version:** Not

**Comment by sualko** [comment]
Thanks for reporting this PHP info message. I will fix it in the next release, but don't worry it's just a info message.

**Comment by sualko** [comment]
I got reports about similar log messages:

```
Undefined index: xmpp at ojsxc\/lib\/Settings\/Personal.php#50
Use of undefined constant Application - assumed 'Application' at ojsxc\/lib\/Settings\/Personal.php#71
Use of undefined constant INTERNAL - assumed 'INTERNAL' at ojsxc\/lib\/Settings\/Personal.php#71
```

**Comment by runasas2017** [comment]
On opening any document like ppt,odt,doc  from nextcloud 13 via onlyoffice(last release) this error((

**Comment by danger89** [comment]
Still the same error in Nextcloud 14. Which new release?

**Comment by bazsodombiandras** [comment]
Keep getting this in Nextcloud 14 several times per minute in the log:

Undefined index: externalConnectable at /var/www/html/nextcloud/apps/ojsxc/templates/settings/personal.php#36

**Comment by susobaco** [comment]
Same problem in debian stretch with nextcloud 14.

**Comment by sualko** [comment]
Please test and report.

**Comment by bazsodombiandras** [comment]
I've personally solved this temporarily by commenting out the whole PHP code that was causing the problems. I can put it back and check if it's solved. However I have no idea how to get the update...

**Comment by sualko** [comment]
The easiest way is to replace the corresponding lines from https://github.com/nextcloud/jsxc.nextcloud/commit/d2825e2b50fa98aa8b5e73060d150ec5e21add9f

**Comment by susobaco** [comment]
On my server, the log alert is gone.

**Comment by susobaco** [comment]
Bad news, here it is again:
Invalid argument supplied for foreach() at /var/www/nextcloud/apps/ojsxc/lib/Controller/SettingsController.php#305

**Comment by sualko** [comment]
@susobaco thanks for testing. As you can see from the message this is a new error. Please open a new issue. Thanks a lot.

**Comment by filisko** [comment]
Hi @sualko, 

> The easiest way is to replace the corresponding lines from nextcloud/jsxc.nextcloud@d2825e2

How much we would have to wait for an update if we don't fix it like this?

**Comment by sualko** [comment]
I'm currently working on some other fixes which should go with the next release. My hope is that I can finish this by end of the month. Sorry for the delay, it's currently quite busy.
