### ISSUE TITLE
Update the SOGO release

### ISSUE THREAD

**Issue by extremeshok** [jsxc/jsxc#727]
Hi

Its been about  a year of no updates for the sogo release

Could we have an update for it ? or are their plans to make this release sogo compatible and do away with the outdated sogo release ?

Thanks

**Comment by sualko** [comment]
Thanks for your interest in JSXC 4 Sogo. We felt and saw that there where not many downloads for the package, so we decided to put our effort at more popular releases. Additionally we had some issues with the new angular interface for which we had no time to fix. If you like to pick up development you are welcome and we will support you as good as possible.
