### ISSUE TITLE
Antivirus

### ISSUE THREAD

**Issue by runasas2017** [jsxc/jsxc#729]
### Expected behavior
Antivitus work
### Actual behavior
Don't' work
### Log
Error | files_antivirus | OCA\Files_Antivirus\BackgroundJob\BackgroundScanner::run,  exception: The antivirus executable could not be found at  /usr/bin/clamscan

### Steps to reproduce the behavior
1.Install clamscan to /usr/bin/ chmod +x
2. Install nextcloud 13
3.Install  Antivirus App for files 1.3.1

### Environment
ubuntu 16.04
Nginx
#### Javascript

no
```

#### JSXC
no
#### XMPP
no
#### Host
no

**Comment by sualko** [comment]
How is this related to our XMPP chat app?

**Comment by runasas2017** [comment]
Not related- I think I've mismatched tree( Sorry. But trouble with antivirus present.
