### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by caygri** [jsxc/jsxc#730]
Can you please update your module for new version of owncloud?

**Comment by caygri** [comment]
sorry i dont understand...

**Comment by sualko** [comment]
Sorry, but nobody from Owncloud cared about us, so we decided to stop development and to go totally with nextcloud.

**Comment by caygri** [comment]
thank you for update..can you link me nextcloud?

**Comment by MarcelWaldvogel** [comment]
https://nextcloud.com; you can pretty seamlessly upgrade from ownCloud to Nextcloud. JSXC is in the appstore directly from within your Nextcloud installation.

**Comment by DanScharon** [comment]
https://nextcloud.com/migration/
