### ISSUE TITLE
Public API design for 4.0

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#731]
The current public API is mainly available directly under the `jsxc` namespace and can be called in any order. This means people can call `jsxc.start` before they call `jsxc.init` which is obviously a bad idea. A more chain-based approach could help here. This means `jsxc.init` would return the API which can only be called after the init method. This could also be handy in a multi-account setup, where you could get account specific APIs after calling some `jsxc.getAccount` method. What are you thoughts?

**Current**
```JavaScript
jsxc.init({...});
jsxc.start();
```

**Proposal**
```JavaScript
jsxc.init({...}).start();
```

**Comment by mmoqui** [comment]
+1 for the proposal.
