### ISSUE TITLE
Can't create managed XMPP server (general and HTTP/HTTPS)

### ISSUE THREAD

**Issue by dmacpui** [jsxc/jsxc#733]
Can´t create managed XMPP server

**Comment by MarcelWaldvogel** [comment]
Thanks for reporting. We just switched to an entirely new server, reinstalling everything. And obviously, I had forgotten one change…

Could you please try again? (And: Sorry!)

**Comment by dmacpui** [comment]
Hi,

I have new issue q19xfN4jXSCzot9Nm79M

My nextcloud server is a docker installation with a nginx instance, nextcloud instance and only office instance. It has https protocol configured with positive ssl certificates:
https://faritcloud.farinter.com

But on JavaScript Xmpp Client configuration shows api url with this:
http://faritcloud.farinter.com/index.php/apps/ojsxc/ajax/externalApi.php

And error say that I should configure ssl but It is configured. 


Any ideas


Many thanks

**Comment by MarcelWaldvogel** [comment]
1. Did you log in using HTTP to the server? AFAIK, the resulting URL known to JSXC is based on how you connect to the server.
   * Including a redirect from http://… to https://… in the `nginx` config should solve this (I don't do `nginx`, so you have to look it up yourself)
   * If that alone is not enough, change `…/config/config.php` to include `  'overwrite.cli.url' => 'https://faritcloud.farinter.com/'
   * Unrelated to this: You may want to get rid of the `/index.php` in every request. For Apache, this is described in [the Nextcloud configuration documentation](https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html#pretty-urls). Again, I do not know how to do this with `nginx .
1. You do not [deliver the entire certificate chain](https://www.ssllabs.com/ssltest/analyze.html?d=faritcloud.farinter.com&hideResults=on). This is not the reason for this error, but would be the next showstopper. You need to tell `nginx` to also include the COMODO intermediate certificate (the root certificate is shipped with OSes/browsers)

**Comment by sualko** [comment]
Please reopen this issue if needed.
