### ISSUE TITLE
User can not delete himself from his own contact list

### ISSUE THREAD

**Issue by olegbolden** [jsxc/jsxc#734]
If user eventually adds himself to contact list within NextCloud chat (just by mistake) he can not delete himself from contact list anymore.

Nextcloud version: 14.0.1

**Comment by sualko** [comment]
I can't reproduce this, because my XMPP denies the add request with an "not-allowed" error. Can you enable debugging (`jsxc.enableDebugMode()` in the javascript console) and post the log if you try to delete the contact?

**Comment by olegbolden** [comment]
It seems that `jsxc` object is not intialized, because I get `undefined` for jsxc.enableDebugMode() command.

----------------------
I am master.
State changed to ESTABLISHING
Try to attach
SID: 9858a46edc7eb63b87e6a5aed1f62c2b7d235bbb
ATTACHED: null
UI State changed to INITIATING
Waiting for server capabilities
Request server capabilities
Could not determine script path for web worker.
DSA key creation started.
State changed to READY
set ice servers
Variable RTCPeerConfig doesn't exist. It was created.
DSA key creation started
discover http upload service
Load bookmarks from pubsub
Roster loaded
[webrtc] Could not update icon, because could not find jid for kursir.jsxc.ch
UI State changed to READY
No photo provided
DSA key creation finished
Discover muc service
query conference.kursir.jsxc.ch for upload service
query proxy.kursir.jsxc.ch for upload service
query pubsub.kursir.jsxc.ch for upload service
query userdata.kursir.jsxc.ch for upload service
Presence (5905@kursir.jsxc.ch/1284408296512385024115103): online
Presence (5907@kursir.jsxc.ch/Wime): online
http upload service found on userdata.kursir.jsxc.ch
Variable httpUpload doesn't exist. It was created.
No photo provided
Variable muc doesn't exist. It was created.
Variable 5905@36 doesn't exist. It was created.
No photo provided
Variable 5907@36 doesn't exist. It was created.
jsxc.enableDebugMode()
undefined

------------------
When I try to delete myself I get the following in console:

`<iq xmlns="jabber:client" to="superuser@kursir.jsxc.ch/1256147360227389440148514" from="superuser@kursir.jsxc.ch" type="set" id="push5833512122710346753">
	<query xmlns="jabber:iq:roster" ver="e04bcc6d659cb20a7653ce4adeb2b53209f1630a">
		<item subscription="both" jid="superuser@kursir.jsxc.ch">
		<group>admin</group>
		<group>all</group>
		<group>Все</group>
		</item>
	</query>
</iq>`

**Comment by sualko** [comment]
> because I get undefined

That's the intended behavior. You just have to reload the page, in order to see more log messages. It would helpful to see the roster (contact list) response and the request which resolves into the above stanza. If your log contains sensitive content, you can also send it to klaus@jsxc.org.

**Comment by sualko** [comment]
From the log I received via mail, it seems that this is an issue with xcauth, because the remove request is answered with an add response. @MarcelWaldvogel do you have an idea?

**Comment by sualko** [comment]
@olegbolden do you still have this issue?

**Comment by sualko** [comment]
Please reopen if needed.
