### ISSUE TITLE
Synchro between Nextcloud user groups (and their users) and roster content in messengers is unstable

### ISSUE THREAD

**Issue by olegbolden** [jsxc/jsxc#735]
Multiple tests shows that synchronization between groups (and their contents) created in Nextcloud and groups reflected in roster of any XMPP messenger are very unstable.
It means that you can see groups in roster that has been deleted many days ago from Nextcloud.
Also users often see in their rosters groups to which they are not belong in Nextcloud.
Relogining to accounts in most cases has no effect.

Nextcloud version: 14.0.1

**Comment by MarcelWaldvogel** [comment]
Not at all? Are they reflected after the next login?

**Comment by sualko** [comment]
Any update on this?

**Comment by djay07** [comment]
Is this related to the fact, that all users are shown in the user chat list in NC?
I hoped to be able to limit it only to the usergroups and came across this ticket.
Any way to help with feedback?

**Comment by sualko** [comment]
There is not enough information to solve this issue.
