### ISSUE TITLE
Nextcloud admin's JSXC account as seen from messengers is not synchronized with data from Nextcloud

### ISSUE THREAD

**Issue by olegbolden** [jsxc/jsxc#736]
It seems that admin's JSXC account contact list data as seen from within XMPP messengers is not synchronized with Nextcloud while other users data are processed correctly (except problem with newly created groups #735 ).
1. Groups to which admin belongs to within Nextcloud are not coincide with those in XMPP messengers (so far I tested Pidgin and Wime (PSI clone)).
2. Information about users in admin's contact list is not synchronized with actual information from Nextcloud.

Nextcloud version: 14.0.1

**Comment by MarcelWaldvogel** [comment]
Can you provide us with a sequence of instructions to repeat this problem?

**Comment by olegbolden** [comment]
I close this issue because in general it is the same as #735
