### ISSUE TITLE
Error in the nextcloud 14 log on debian stretch

### ISSUE THREAD

**Issue by susobaco** [jsxc/jsxc#740]
### Actual behavior
```
 Invalid argument supplied for foreach() at /var/www/nextcloud/apps/ojsxc/lib/Controller/SettingsController.php#305
```

### Steps to reproduce the behavior
1. This error appears in the log
2.
3.

### Environment
- **JSXC version:** The one that comes by default in nextcloud 14
- **Host system and version:** Nextcloud 14
- **Browser vendor and version:** Abrowser 63 (based in firefox 63)
- **Any browser plugins enabled?** Disconnect, Ublock Origin, Cookie Autodelete
- **XMPP server vendor and version:** The one that comes by default in nextcloud 14
- **Is your XMPP server working with other clients as expected?** Yeah, it looks like it.

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
Please test the above fix, because I was not able to reproduce your issue.

**Comment by susobaco** [comment]
Perfect, the error message hasn't come back since I applied the patch. Thank you
