### ISSUE TITLE
XEP-0333: Chat Markers

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#745]
[XEP-0333](https://xmpp.org/extensions/xep-0333.html) describes a solution of marking the last received, displayed and acknowledged message in a chat.

**Comment by dommaes** [comment]
I just created a pull request for this issue (https://github.com/jsxc/jsxc/pull/754)

My idea is to implement XEP-0333 as a plugin, as this XEP and the chat state XEP seem pretty similar.

**Comment by sualko** [comment]
As this was merged, I close this issue.
