### ISSUE TITLE
Avatar upload

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#748]
Add ability to upload avatar in use with [XEP-0084: User Avatar](https://xmpp.org/extensions/xep-0084.html) and [XEP-0153: vCard-Based Avatars](https://xmpp.org/extensions/xep-0153.html). Maybe related to [XEP-0398: User Avatar to vCard-Based Avatars Conversion](https://xmpp.org/extensions/xep-0398.html) and requires probably #304.

**Comment by mightymop** [comment]
PR: https://github.com/jsxc/jsxc/pull/976 adds ability to set PEP Avatar
