### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KrystinaMir** [jsxc/jsxc#751]
no app in context | Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "ojsxc.javascript.generalConfig" as such route does not exist.
-- | --

After the update when you start

**Comment by KrystinaMir** [comment]
/var/www/nextcloud/lib/private/Route/Router.php - line 337:

    Symfony\Component\Routing\Generator\UrlGenerator->generate("ojsxc.javas ... g", [], 1)

    /var/www/nextcloud/lib/private/Route/CachingRouter.php - line 60:

    OC\Route\Router->generate("ojsxc.javas ... g", [], false)

    /var/www/nextcloud/lib/private/URLGenerator.php - line 79:

    OC\Route\CachingRouter->generate("ojsxc.javas ... g", [])

    /var/www/nextcloud/apps/ojsxc/appinfo/app.php - line 12:

    OC\URLGenerator->linkToRoute("ojsxc.javas ... g")

    /var/www/nextcloud/lib/private/legacy/app.php - line 261:

    require_once("/var/www/cl ... p")

    /var/www/nextcloud/lib/private/legacy/app.php - line 154:

    OC_App::requireAppFile("ojsxc")

    /var/www/nextcloud/lib/private/legacy/app.php - line 951:

    OC_App::loadApp("ojsxc")

    /var/www/nextcloud/lib/private/Installer.php - line 147:

    OC_App::executeRepairSteps("ojsxc", { step: "OCA ... "})

    /var/www/nextcloud/settings/Controller/AppSettingsController.php - line 441:

    OC\Installer->installApp("ojsxc")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OC\Settings\Controller\AppSettingsController->enableApps([ "ojsxc"], [])

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "enableApps")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "enableApps")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OC\\Setting ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

    /var/www/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

    /var/www/nextcloud/lib/base.php - line 987:

    OC\Route\Router->match("/settings/apps/enable")

    /var/www/nextcloud/index.php - line 42:

    OC::handleRequest()

**Comment by sualko** [comment]
Can you explain, where you see this message? Is it in the log? Does the app still work? I need some more information, because I can't reproduce it.

**Comment by KrystinaMir** [comment]
Understood! JavaScript XMPP Chat does not start until User and Group SQL Backs are disabled. There is a lot of Debug ojsxc. If you disable User and Group SQL Backends then everything works!

**Comment by sualko** [comment]
Please answer our [issue template](https://github.com/jsxc/jsxc/blob/master/ISSUE_TEMPLATE.md) and include the output from `./occ config:list`.

> a lot of Debug ojsxc

What do mean? Can you also post it here?
