### ISSUE TITLE
jsxc-3.4.3 load older messages

### ISSUE THREAD

**Issue by blacktors** [jsxc/jsxc#755]
Hi, can you help me. 
I'm use jsxc version 3.4.3 but i cannot found load older message from user1 and user2.
I see #150 but in version 3.4.3 not working.

**Comment by blacktors** [comment]
![jsxc load older message](https://user-images.githubusercontent.com/14247433/50414217-df623900-0846-11e9-967c-6c0088aaf38a.png)

load older message is missing, please help me. thanks

**Comment by nick-denry** [comment]
Hi! Got the same issue - messages from MAM are not syncing.

**Comment by sualko** [comment]
You have to enable that function explicitly in the jsxc settings. Burger menu, settings, mam. Please close the issue if this answers your question.

**Comment by nick-denry** [comment]
@sualko this setting with 'experimetal' label is already enabled. Messages from history are missed anyway. Server has mam enabled and tested ok via another clients.

**Comment by sualko** [comment]
Can you send some test credentials to klaus@jsxc.org?

**Comment by nick-denry** [comment]
> Can you send some test credentials

Unfortunately no. Switched to another solution.
