### ISSUE TITLE
XEP-0412: XMPP Compliance Suites 2019

### ISSUE THREAD

**Issue by Neustradamus** [jsxc/jsxc#756]
Please add support of https://xmpp.org/extensions/xep-0412.html

Which replace:
- XEP-0387: XMPP Compliance Suites 2018: https://xmpp.org/extensions/xep-0387.html
- XEP-0375: XMPP Compliance Suites 2016: https://xmpp.org/extensions/xep-0375.html
- XEP-0302: XMPP Compliance Suites 2012: https://xmpp.org/extensions/xep-0302.html
- XEP-0270: XMPP Compliance Suites 2010: https://xmpp.org/extensions/xep-0270.html
- XEP-0242: XMPP Compliance Suites 2009: https://xmpp.org/extensions/xep-0242.html

**Comment by sualko** [comment]
As far as I know we are already compliant.

**Comment by Neustradamus** [comment]
No no

**Comment by sualko** [comment]
> No no

Can you elaborate a bit more on that?

**Comment by Neustradamus** [comment]
You can look all RFCs and XEPs (updated) in XEP-0412...
1/ RFC6120 is not respected: Missing SCRAM-SHA-1-PLUS
...

**Comment by MarcelWaldvogel** [comment]
The `-PLUS` indicates Channel Binding. I do not think that *any* in-browser implementation can provide this. At least I am unaware of any way to get at low-level TLS Information (the contents of the most recent TLS “finished record”) from JavaScript.

I’ll bring this to the attention of the XMPP Standards mailing list.

Anything else?

**Comment by DanScharon** [comment]
in order to fulfill the "Advanced Client" level the following features seem to be missing:

- #304 #748 (XEP-0398)
- #341 (XEP-0249)
- #746 (XEP-0308)
- XEP-0191: Blocking Command

**Comment by Neustradamus** [comment]
XMPP RFCs have been updated...
Some libraries or softwares say that it is RFC6120/6121 but it is RFC3920/3921.
...

And do not forget that all XEPs have been updated too (a lot of changes).
-> Example: XEP-0045 1.22 is different to XEP-0045 1.31.2.

It is for this that I have requested you one year ago the XEPs support page with version:
- https://github.com/jsxc/jsxc/issues/683

**Comment by Neustradamus** [comment]
@sualko, @MarcelWaldvogel, @DanScharon: Any news?

**Comment by sualko** [comment]
We don't have the man power to verify every single XEP and review all libraries if they correctly implement an XEP or RFC. If you provide us a list with things that are missing, we are happy to fix it. Otherwise there are more urgent issues or enhancement than to be compliant with a single XEP. As I said, we always appreciate contributions :+1:.
