### ISSUE TITLE
SCRAM-SHA-1 and SCRAM-SHA-1-PLUS + SCRAM-SHA-256 and SCRAM-SHA-256-PLUS supports

### ISSUE THREAD

**Issue by Neustradamus** [jsxc/jsxc#757]
SCRAM-SHA-1(-PLUS):
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

SCRAM-SHA-256(-PLUS):
- https://tools.ietf.org/html/rfc7677
- https://tools.ietf.org/html/draft-ietf-mile-xmpp-grid

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

**Comment by sualko** [comment]
This should go upstream to the XMPP lib: https://github.com/strophe/strophejs

**Comment by Neustradamus** [comment]
Maybe you can look for?
Linked to: https://github.com/strophe/strophejs/issues/314
