### ISSUE TITLE
[Request]Documentation

### ISSUE THREAD

**Issue by rfpdl** [jsxc/jsxc#758]
My issues are not related to the source code but rather than documentation.

Can we have the documentation updated? Make it more detailed? 
- Make API available (both option and events)
- Make design editable through the said API

Right now, in order to add new functionality to jsxc, we are working on the core file, how can we work outside of the library file so that if ever there will be update we can just update the library file with the new update.

Or if you have any existing documentation, can you drop it in the comment instead?

Thanks, very much appreciate it.

**Comment by sualko** [comment]
> Can we have the documentation updated? Make it more detailed?

Yes, and yes. We are currently on our way to unify our whole documentation mess at https://github.com/jsxc/documentation. It's only thought for the upcoming 4.0, but I think it should also be possible to add the 3.x documentation there. I would be awesome if you could help us with that.

> Right now, in order to add new functionality to jsxc, we are working on the core file, how can we work outside of the library file so that if ever there will be update we can just update the library file with the new update.

You can just overwrite some methods. So e.g. if you like to update the `jsxc.gui.renderMessage` method, you can just set `jsxc.gui.renderMessage = function(){}` after jsxc was loaded and before you call `jsxc.init`.
