### ISSUE TITLE
Documentation Location?

### ISSUE THREAD

**Issue by stone212** [jsxc/jsxc#759]
I am sorry if the answer is obvious but in the wiki etc. I don't see documentation that tells me how to enable File sharing, screen sharing, or video (using Local server first) for the Nextcloud 15 version of this tool.

Is there another link I should read?

**Comment by sualko** [comment]
Those things are only available if you use an external service like e.g. our managed backend.

**Comment by stone212** [comment]
@sualko Ok.  There should still be a doc that explains this.

**Comment by stone212** [comment]
@sualko But the local connections are still OTR (or OMEMO) encrypted right?  Where can I view the fingerprints?  Separate issue I know but not really an Issue so don't want to post again.

**Comment by sualko** [comment]
> But the local connections are still OTR (or OMEMO) encrypted right?

In 3.x you can enable OTR by clicking on the pad lock in the bottom right corner of your chat window. Omemo is only supported in the upcoming 4.0.

> Where can I view the fingerprints?

If you have an active session you can view the fingerprints in the chat window menu (3 little dots in the header)

**Comment by stone212** [comment]
@sualko 

> In 3.x you can enable OTR by clicking on the pad lock in the bottom right corner of your chat window. 

I saw the padlock but didn't know it was specifically OTR.  That's good but I suggest a UI addition so the user knows what type of security the lock represents.

> If you have an active session

Can I view my fingerprint without an active session?  I want to copy my fingerprint and send it over another channel before I create a session.

**Comment by sualko** [comment]
> I suggest a UI addition so the user knows what type of security the lock represents.

Pull requests welcome.

> Can I view my fingerprint without an active session?

This is currently not possible, but as I said we always appreciate pull requests.
