### ISSUE TITLE
JavaScript Xmpp chat does not show when Nextcloud user and Openfire (XMPP) user have same password

### ISSUE THREAD

**Issue by ceantuco** [jsxc/jsxc#760]
### Expected behavior
When both Nextcloud and openfire users have the same password, Nextcloud should auto login to the XMPP chat. 
### Actual behavior
The chat Icon does not show. To make it show, I have to select 'Login without Chat' on the next cloud login screen. 
### Steps to reproduce the behavior
1.Set Nextcloud and Open fire users' password the same
2. Nextcloud user: TestT pass: Testing123
3. Openfire XMPP user: TestT pass: Testing123
4. Login to Nextcloud

### Environment
- **JSXC version: 3.4.3** 
- **Host system and version:** 
- **Browser vendor and version: Chrome 71.0.3578.98, Firefox 64.0.2 and IE 11.523.17134.0** 
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Openfire 4.3.0 
- **Is your XMPP server working with other clients as expected?** Yes, when using Spark it works fine.

#### Javascript

Yes

#### JSXC

JQMIGRATE: Migrate is installed, version 1.4.0
jsxc.js:184 State changed to INITIATING
jsxc.js:184 State changed to PREVCONFOUND
jsxc.js:184 check master
jsxc.js:184 I am master.
jsxc.js:184 [WARN] xmpp.url required for login

```
```

#### XMPP

No. 
```
```

#### Host

No.
```
```

**Comment by sualko** [comment]
> [WARN] xmpp.url required for login

Did you configure a bosh url in the settings? Otherwise, please send me some test credentials to klaus@jsxc.org?
