### ISSUE TITLE
OMEMO support; version 4.0

### ISSUE THREAD

**Issue by AlexCloudDev** [jsxc/jsxc#762]
Hey guys,
thank you very much for your effort.

I'm a little bit confused.
I was looking for OMEMO support for the nextcloud JavaScript XMPP Client and found this:

https://github.com/jsxc/jsxc-plugin-omemo

But following this link, it says, OMEMO support is merged in 4.0 and therefor the plugin was removed. But i can't find no 4.0 version. 
I'm on 3.4.3 and it seems to be the latest. The plugin doesn't exist anymore either, so how am i supposed to use OMEMO support at the client?

Thx in advance,
ACD

**Comment by sualko** [comment]
Jsxc 4.0 is not released yet. Hopefully I can publish the first beta this weekend. So stay tuned.

**Comment by JokerGermany** [comment]
Waiting for OMEMO, too.

**Comment by sualko** [comment]
@JokerGermany you can help and test the [current beta release](https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v4.0.0-beta.2). We currently have some reports about issues with omemo, but we need more information to debug this issue. So your help would be appreciated.

**Comment by JokerGermany** [comment]
Ok, I will test it. (External Server)
First I have to find out how to replace the version which i get from snap nextcloud^^

**Comment by JokerGermany** [comment]
@sualko I can't get it running.
Nextcloud shows that the app is active and the version is  4.0.0-beta.2, but nextcloud didn't show the chat window anymore...

**Comment by sualko** [comment]
@JokerGermany please open an new issue and provide all the required information. Otherwise you can also send me an email with your cloud url to klaus@jsxc.org.
