### ISSUE TITLE
XEP-0191: Blocking Command

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#763]
Support [XEP-0191: Blocking Command](https://xmpp.org/extensions/xep-0191.html) in order to achieve compliance to XEP-0412 (#756).

**Comment by mightymop** [comment]
PR: https://github.com/jsxc/jsxc/pull/982

**Comment by mightymop** [comment]
This could be closed...

**Comment by mightymop** [comment]
Support added in PR #982
