### ISSUE TITLE
XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by jillian1701** [jsxc/jsxc#764]
Hello. Super excited to be testing out v4.0.0-beta.1 for OMEMO support, nice work getting this done! 

I do have a few issues. For reference, on all other devices XMPP works great, OMEMO does as well. I'm running the most recent N/C and obviously v4.0.0-beta.1. 

1. I now have to log in twice. The first simply redirects back to the login page, the second actually works. 
2. I cannot receive inbound messages, either encrypted or not. I do receive a notification that something has come in via the little yellow number, however the number does not increment like in previous versions. 
3. I cannot send outbound encrypted messages. Unencrypted seems to work just fine. 
4. Verifying a device does not seem to save. If I log out and back in, I have to re-verify the same devices. 

JavaScript output is below:

```
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 120:
```
`[OMEMO][Warn] Found 0 PreKeys which match my device id (xyz). jsxc.bundle.js:11:32008 `

```
[receipt][Info] I received an ACK and got the following problem:  Error: "Could not load message xyz"

    e https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:18 
onReceipt https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:101 
run https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:52 
_dataRecv https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:52 
forEachChild https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:52 
_dataRecv https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:52
_onRequestStateChange https://mysite.us/nextcloud/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=66c4858f-2:48 
```
`[Warn] Error during preSendMessageStanza pipe: TypeError: "e.replace is not a function"`

```
[Warn] Could not encrypt data for device with id 1886643503 Error: "Identity key changed"
    processPreKey https://mysite.us/nextcloud/apps/ojsxc/js/libsignal/libsignal-protocol.js?v=66c4858f-2:35801 
```

**Comment by sualko** [comment]
Thanks for testing :tada: and sorry for the inconvenience. Which browser do you use and can you send some test credentials to klaus@jsxc.org?

**Comment by sualko** [comment]
Was there any update on this?

**Comment by jillian1701** [comment]
Hi. I'm sorry I lost track of this. I've been very busy at work and have
just been using Gajim. I'll get back to testing out 4.0 beta very soon.
Hopefully next week or weekend.
