### ISSUE TITLE
"Not allowed to load local resource" for SVG files

### ISSUE THREAD

**Issue by andrei-pmbcn** [jsxc/jsxc#767]
### Expected behavior
Clicking on a name in the roster should load the corresponding conversation window without errors

### Actual behavior
Numerous errors with the format "Not allowed to load local resource" show up when opening the conversation window. This might be because of Chrome's default security policy, which may be preventing the opening of the emoji svg files mentioned in the error messages below.

### Steps to reproduce the behavior
1. Load jsxc with a user that has contacts
2. Click on a contact in the roster to load the corresponding conversation window
3. Check for the errors in the javascript console

### Environment
- **JSXC version:** 3.4.3
- **Host system and version:** Apache 2.4
- **Browser vendor and version:** Chrome 73
- **Any browser plugins enabled?** no
- **XMPP server vendor and version:** ejabberd 19.02
- **Is your XMPP server working with other clients as expected?** not tested

#### Javascript

```
Update file transfer icons for user@localhost
webrtc.initWindow
Not allowed to load local resource: file:///C:/Apache24/htdocs/apps/view/javascript/jsxc/lib/emojione/assets/svg/1f590.svg
Not allowed to load local resource: file:///C:/Apache24/htdocs/apps/view/javascript/jsxc/lib/emojione/assets/svg/1f4a4.svg
Not allowed to load local resource: file:///C:/Apache24/htdocs/apps/view/javascript/jsxc/lib/emojione/assets/svg/1f494.svg
Not allowed to load local resource: file:///C:/Apache24/htdocs/apps/view/javascript/jsxc/lib/emojione/assets/svg/2764.svg
Not allowed to load local resource: file:///C:/Apache24/htdocs/apps/view/javascript/jsxc/lib/emojione/assets/svg/1f60d.svg
[and so on - roughly 40 more errors like the above]
```

**Comment by sualko** [comment]
I guess this is an issue with your content security policy. Can you post the http header of your html file?

**Comment by andrei-pmbcn** [comment]
Here are the HTTP headers:
```
Request Headers
Accept | text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
--
Response Headers
Access-Control-Allow-Credentials | true
Access-Control-Allow-Origin | *
Cache-Control | no-store, no-cache, must-revalidate
Connection | Keep-Alive
Content-Type | text/html; charset=utf-8
Date | Wed, 20 Mar 2019 13:39:08 GMT
Expires | Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive | timeout=5, max=100
Pragma | no-cache
Server | Apache/2.4.38 (Win64) PHP/7.3.3
Transfer-Encoding | chunked
X-Powered-By | PHP/7.3.3
```

**Comment by sualko** [comment]
In the first post you tried opened the example via file url (`file:///C:/...`) and therefore chrome blocks those requests for security reasons.
