### ISSUE TITLE
Jsxc's own copy of jquery-ui.min.css is causing errors

### ISSUE THREAD

**Issue by andrei-pmbcn** [jsxc/jsxc#768]
### Expected behavior
Jsxc should use an external jquery-ui.min.css file, which will contain the correct image path for ui-bg_flat_0_aaaaaa_40x100.png , rather than providing its own jquery-ui.min.css file, given the error below.

### Actual behavior
Jsxc provides its own css/jquery-ui.min.css file, which contains relative paths to image files that do not exist in the jsxc installation's directories (e.g. images/ui-bg_flat_0_aaaaaa_40x100.png ), but would normally exist in jquery-ui's installation directory, had jquery-ui.min.css been present in that directory. Jquery-ui.min.css was probably moved at some point from jquery-ui's installation directory to the jsxc installation directory, without changing the paths of the image files it links to. The absence of these files causes an error when trying to load them.

The most straightforward solution is to not include jquery-ui.min.css in the jsxc installation. In addition, it should not be included in the [installation instructions](https://github.com/jsxc/jsxc/wiki/Install-jsxc), which currently specify:

`<link href="jsxc.example/jsxc/css/jquery-ui.min.css" media="all" rel="stylesheet" type="text/css" />`

### Steps to reproduce the behavior
1. load jsxc with jsxc's css/jquery-ui.min.css included as a stylesheet in the html document
2. after a while, a 404 (Not Found) error will appear for the requested resource

### Environment
- **JSXC version:** 3.4.3
- **Host system and version:** Apache 2.4
- **Browser vendor and version:** Chrome 73
- **Any browser plugins enabled?** no
- **XMPP server vendor and version:** Ejabberd 19.02
- **Is your XMPP server working with other clients as expected?** not tested

#### Javascript

```
DSA key loaded
State changed to READY
http://localhost/apps/view/javascript/jsxc/css/images/ui-bg_flat_0_aaaaaa_40x100.png 404 (Not Found)
```

**Comment by sualko** [comment]
I will remove the file and close the issue as soon as possible.
