### ISSUE TITLE
Roster groups are ignored

### ISSUE THREAD

**Issue by ssams** [jsxc/jsxc#77]
Buddies on the roster are displayed in a single list, group associations are ignored. Displaying the groups would help improving usability, especially when there are many buddies on the roster.
##

**Comment by pedrobastosz** [comment]
Authors of this library, you saved me a lot of headaches with this amazing library :).

+1 for this thread, I would love it too.

**Comment by bsv144** [comment]
Is the ability to group contacts in roster?

**Comment by cirovargas** [comment]
OK, this is possible?

**Comment by sualko** [comment]
It is possible, but not implemented. Pull request's are always welcome.

**Comment by cirovargas** [comment]
Hi @sualko, where i can do this? You can help me to do faster?

I need to implement http://www.xmpp.org/extensions/xep-0083.html too

**Comment by sualko** [comment]
@cirovargas please read our [developer notes](https://github.com/jsxc/jsxc/wiki/Developer-notes) and open an empty pull request to discuss your additions before you start to develop.

**Comment by rasos** [comment]
+1 to see which groups are available when subscribing and list where I am already a member of.
