### ISSUE TITLE
JSXC 4.0.0 is not being loaded in nextcloud

### ISSUE THREAD

**Issue by mwlczk** [jsxc/jsxc#770]
### Expected behavior
JSXC Windows open inside of nextcloud.

### Actual behavior
No JSXC windows or sidebars show up at all.

### Steps to reproduce the behavior
1. download 4.0.0-beta.zip to server
2. rm old app-folder
3. unzip downloaded package to apps-folder of nextcloud installation
4. enable JSXC in the apps menu
5. configure JSXC in the settings menu
6. log out and log in
7. No JSXC is being loaded

### Environment
- **JSXC version:** 4.0.0-beta2
- **Host system and version:** nextcloud 15.0.5 (hoellen/dockerfiles)
- **Browser vendor and version:** Firefox (newest) and Chrome  73.0.3683.75
- **Any browser plugins enabled?**  Nope
- **XMPP server vendor and version:** ejabberd 19.02
- **Is your XMPP server working with other clients as expected?** yes

#### Javascript

Could not find script element which points to jsxc.bundle.js. JSXC is maybe not working correctly. jsxc.bundle.js?v=7d911443-8:89 

#### JSXC

Uncaught ReferenceError: jsxc is not defined

#### XMPP

```
```

#### Host

```
```

**Comment by mwlczk** [comment]
https://github.com/nextcloud/jsxc.nextcloud/issues/85

**Comment by sualko** [comment]
Do you get any 404? Can you request `/apps/ojsxc/js/config.js`? Do you use pretty urls for Nextcloud?

**Comment by mwlczk** [comment]
- No 404
- this is the response for config.js
 window.jsxc_public_path = OC.generateUrl("apps/ojsxc/js/jsxc/");var OJSXC_CONFIG = {}; try{OJSXC_CONFIG = JSON.parse('{"serverType":"external","startMinimized":false,"defaultLoginFormEnable":true}');}catch(err){}
- not that i know of

**Comment by sualko** [comment]
Is `jsxc.bundle.js` loaded before `config.js`? Can you send the url of your installation to klaus@jsxc.org?

**Comment by sualko** [comment]
Ok, I guess it's the same issue as in another app of mine sualko/cloud_piwik#63. Server response with a 302 for the config file. I already have a fix for it, but I need to test it a bit more. Thanks for reporting.

**Comment by mwlczk** [comment]
@sualko :100: thank you

**Comment by sualko** [comment]
Should now be fixed in a67de8febb9327ad2332cfbe82143bfc8994e726.

**Comment by sualko** [comment]
If you don't like to create a bundle by yourself, here is one: 
[ojsxc-4.0.0-git.768ac96.tar.gz](https://github.com/jsxc/jsxc/files/3022644/ojsxc-4.0.0-git.768ac96.tar.gz)

**Comment by mwlczk** [comment]
@sualko works great, thank You
