### ISSUE TITLE
JSXC 4: give the possibility to customize the UI and some functionalities

### ISSUE THREAD

**Issue by mmoqui** [jsxc/jsxc#771]
Is it possible for the next major version of JSXC to separate the UI from the engine that motorizes JSXC and to put accessible some of the UI's classes as well as some of the functionalities of JSXC without having to write code directly into the source code of JSXC 4? 

The idea behind this issue is to be able to extend and to customize JSXC by just writing a code atop of JSXC imported as a lib. So that we can adapt it to our own way to use an XMPP chat.

For example, we customizes some hints of the UI like the roster for which we define our own template (and hence we customize the roster code to take into account that template). With the current state of the JSXC 4 code, this is not more possible as the UI is hidden in JSXC (the Roster isn't accessible and it cannot be extended).
We also adapt some of the behavior to our specific use: for example in our use a group chat is simply created by selecting first some of the buddies and then by giving a name. A direct invitation is then sent to each of the selected buddies and the group chat window is opened for all of the invited buddies.

**Comment by sualko** [comment]
> Is it possible for the next major version of JSXC to separate the UI from the engine that motorizes JSXC 

It's to late for 4.0 and I think it's a quite big step, but we always appreciate pull requests. Your changes sound interesting. Nonetheless, I would like to migrate the ui part to vue.js, because it's still a mess to sync all those class names between js and css. But first let's concentrate of the first release of 4.0 :wink:

**Comment by ostasevych** [comment]
At least, please, add the colour scheme to be followed the scheme selected in NC: if dark, than the elements should be dark and vice versa. Now they are not.
