### ISSUE TITLE
Unable to Edit HTML

### ISSUE THREAD

**Issue by mitulverma13** [jsxc/jsxc#773]
### Expected behavior
I am willing to make some UI changes so I edited the Template HTML files and build it with "Make" command

### Actual behavior
The log says the HTML file was converted to js but no changes are displayed

### Steps to reproduce the behavior
1. Edit contactDialog.html
2. run command "Make" in terminal
3. check the changes in browser

### Environment
- **JSXC version:** build v3.4.3
- **Host system and version:** 
- **Browser vendor and version:** chrome
- **Any browser plugins enabled?** No

#### Javascript

```
msbcpc069:jsxc administrator$ make
git submodule update --init
npm install
npm WARN grunt-html-convert@0.0.2 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-prettysass@0.2.3 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.

up to date in 3.107s
bower install
grunt build
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:files" (jshint) task
>> 17 files lint free.

Running "clean:0" (clean) task
>> 1 path cleaned.

Running "sass:dist" (sass) task
DEPRECATION WARNING on line 2, column 8 of /Users/administrator/Mitul/new/jsxc/scss/_dep.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.


Running "replace:imageUrl" (replace) task

Running "autoprefixer:no_dest" (autoprefixer) task
>> 1 autoprefixed stylesheet created.

Running "copy:main" (copy) task
Created 7 directories, copied 1975 files

Running "merge_data:target" (merge_data) task
File dev/lib/translation.js created.

Running "replace:locales" (replace) task

Running "htmlConvert:jsxc.gui.template" (htmlConvert) task
Successfully converted 1 html templates to js.

Running "replace:template" (replace) task

Running "concat:ww" (concat) task

Running "concat:dep" (concat) task

Running "concat:jsxc" (concat) task

```

**Comment by sualko** [comment]
:tada: thanks that you want to contribute to JSXC. That's awesome. Your log looks good you normally you should see those changes. Maybe it's an caching issue. Did you try to reload with cache disabled? Btw it's maybe a good idea to contribute to the upcoming JSXC 4.0, because it's a total rewrite. Have a look at #581 and this [blog post](https://www.jsxc.org/blog/2018/09/26/v4.0.0-first-alpha-released.html). You can install all dependencies with `yarn install` and build or watch with `yarn start` and `yarn watch`.

**Comment by sualko** [comment]
Could you solve your issue?
