### ISSUE TITLE
Nextcloud Javascript XMPP Managed Service Reinstallation

### ISSUE THREAD

**Issue by adrian-polglase** [jsxc/jsxc#775]
Nextcloud: 15.0.7
JavaScript XMPP Chat: 3.4.3

Apologies, but I had to perform a clean install of Nextcloud with Javascript XMPP Chat on my server, and due to this can no longer use the managed service, as it comes up with the error that my host was registered previously, throwing up the error:

***
Host cloud.adrianpolglase.com was registered previously. apiUrl or apiSecret must agree to allow re-registration. They both differ.

Please report this to our issue tracker and mention the request id QYD69G8sKKTRMMSr5Hwh.
***

So I am reporting as requested by the error! Is it possible to allow me to re-register with the managed service? Thank you!

**Comment by MarcelWaldvogel** [comment]
It seems you did not change the URL. I currently don't have time to track down the problem why it doesn't let you reregister, so I deleted the entry in order to allow you to register as new. Could you please try again?

**Comment by adrian-polglase** [comment]
Hi - yes, I didn't change the URL and unfortunately lost the original instance, so had to install from scratch, which would have caused the issue.

Have now tried again and all is working - so thank you!
