### ISSUE TITLE
Camera and microphone on recipient side don't turn on 

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#776]
### Expected behavior

When making a video or audio call both caller and recepient should see and hear each other

### Actual behavior
The caller can't see or hear the recepient since the camera and microphone on recepient side don't turn on. The recepient can see and hear the caller.

### Steps to reproduce the behavior
1. connect user 1 and user2  on two different devices on https.
2. initiate a video or audio call
3.

### Environment
- **JSXC version:** 4.0.0 beta2
- **Host system and version:**  Ubuntu
- **Browser vendor and version:** Chrome, safari and firefox
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** Ejabberd 18.09
- **Is your XMPP server working with other clients as expected?** Yes with version 3.4.2

#### Javascript
 No
```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

[logs.zip](https://github.com/jsxc/jsxc/files/3092200/logs.zip)

**Comment by sualko** [comment]
Please enable debugging in jsxc and post the corresponding log from your js console.

**Comment by sualko** [comment]
Sorry, I didn't see the link

**Comment by anass-jdid** [comment]
did you have the time to look into this issue

**Comment by sualko** [comment]
I hope the fix is working for you.
