### ISSUE TITLE
how to create own plugin for JSXC 4.0

### ISSUE THREAD

**Issue by pussbb** [jsxc/jsxc#777]
Hi,
Lets say I want to create some plugin but it seems that I can not do it without recompiling JSXC and ship my plugin with JSXC. 

In general I'm looking to something like this (pure JavaScript)
```javascript
class CustomPlugin extends AbstractPlugin {
      constructor(iPlugin) {
       ....
      }
};

let jsxc = JSXC({...});
jsxc.addPlugin(CustomPlugin);
```

But ``AbstractPlugin`` base class is not exported and I can not create own plugin in my environment. 

Can you please tell me how to do it without compiling my plugin with JSXC? 
If its not possible then exporting method addPlugin is useless because they always will have
``Error: XXX doesn't extend AbstractPlugin ``

**Comment by sualko** [comment]
> But AbstractPlugin base class is not exported and I can not create own plugin in my environment.

You are right. We missed that. Thanks for reporting. We will fix it asap.

**Comment by sualko** [comment]
We would love to hear your experience with JSXC 4.0 as a plugin developer.
