### ISSUE TITLE
Erreur lors de la config du serveur XMPP sur Nextcloud

### ISSUE THREAD

**Issue by Charlolotte605** [jsxc/jsxc#780]
### Erreur lorsque je clique sur Registration dans l'onglet Javascript XMPP Client sur Nextcloud

Sorry we couldn't complete your registration.

Couldn't parse the response. Response code: 500

Please report this to our issue tracker and mention the request id 0pnyTyhmoTPBdltPQBRI.

Comment puis-je résoudre cela ?
Merci, cordialement

**Comment by sualko** [comment]
cc @MarcelWaldvogel

**Comment by MarcelWaldvogel** [comment]
Sorry for the delay. The server configuration has been fixed, you can try again.
