### ISSUE TITLE
Error launching Video 

### ISSUE THREAD

**Issue by irvingwa** [jsxc/jsxc#781]
### Expected behavior
Video call is launched and local video is displayed. After the error have to refresh the page.
### Actual behavior
Error thrown in logs and 
### Steps to reproduce the behavior
1. Click the video button from a call
2.
3.

### Environment
- **JSXC version:** 4.0 beta 2
- **Host system and version:** macOS Mojave
- **Browser vendor and version:** Firefox 66.0.5
- **Any browser plugins enabled?**  No
- **XMPP server vendor and version:** ejabberd Docker (rroemhild/ejabberd)
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
Error: Could not create jingle session. Unknown session type: f jsxc.bundle.js:formatted:77248
```

#### JSXC

```
[Debug] [JINGLE][log:debug] 24559322-98ed-4014-a2d1-2b925f5452fc: session-initiate jsxc.bundle.js:11:32400
[Debug] [JINGLE][log:info] 24559322-98ed-4014-a2d1-2b925f5452fc: Initiating incoming session jsxc.bundle.js:11:32400
[Debug] [JINGLE][log:info] 24559322-98ed-4014-a2d1-2b925f5452fc: Changing session state to: pending jsxc.bundle.js:11:32400
[Debug] [JINGLE][log:info] 24559322-98ed-4014-a2d1-2b925f5452fc: Track added 
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
This has already been fixed in f607b8f1e03bc886484c4b24e55a403658f4a622 :tada:
