### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by orbitz** [jsxc/jsxc#786]
Are there updated build instructions anywhere? The build instructions on the wiki mention running make and grunt but the current version of the product does not seem to have either.

I'm interested in building locally to test the latest changes and contribute back.

https://github.com/jsxc/jsxc/wiki/Developer-notes

**Comment by orbitz** [comment]
I think I've managed to figure this out:

```
npm install
webpack --config webpack.config.json --mode=production
```

I can update the wiki if you're OK with that.

**Comment by MarcelWaldvogel** [comment]
Plesse!

**Comment by orbitz** [comment]
I've updated just the build steps, I think more could be updated but I thought it best to do the smallest change, let me know if I can delete the other grunt related stuff.

https://github.com/jsxc/jsxc/wiki/Developer-notes

**Comment by sualko** [comment]
We are moving away from github wikis to readthedocs, therefore you find the current developer notes at https://jsxc.readthedocs.io/en/latest/development/notes.html. I'm sorry for the confusion, I had no time to add a notice to all wiki pages about the change.

**Comment by sualko** [comment]
I reverted you changes and added a notice to the sidebar. If you have any changes for the new documentation, you can open a new pull request at https://github.com/jsxc/documentation
