### ISSUE TITLE
Error: There are new devices for your contact

### ISSUE THREAD

**Issue by orbitz** [jsxc/jsxc#787]
I'm running master as of yesterday, and while I could send omemo messages yesterday after logging back in I'm receiving the following error trying to send to a contact.  I believe this contact recently logged in via a new device.

```
[Warn] Error during preSendMessageStanza pipe: Error: There are new devices for your contact
    at e.<anonymous> (jsxc.bundle.js:106)
    at jsxc.bundle.js:106
    at Object.next (jsxc.bundle.js:106)
    at jsxc.bundle.js:106
    at new Promise (<anonymous>)
    at i (jsxc.bundle.js:106)
    at e.encrypt (jsxc.bundle.js:106)
    at e.encrypt (jsxc.bundle.js:95)
    at e.i.preSendMessageStanzaProcessor (jsxc.bundle.js:95)
    at jsxc.bundle.js:95
```

**Comment by sualko** [comment]
You have to accept new devices. In the menu of the chat window (3 cycles) you find an entry "OMEMO devices". There you have to decide how the new device is used.

**Comment by orbitz** [comment]
Ah ok, that fixed it.  I was under the impression devices just became trusted or something.  But works, great!
