### ISSUE TITLE
How to install jsxc on wordpress ?

### ISSUE THREAD

**Issue by mikygee** [jsxc/jsxc#791]
Hello,

I followed this page
https://github.com/jsxc/jsxc/wiki/Install-jsxc-(WordPress)

I don't understand what should I use for
             form: '#page-login-form',
             jid: '#page-user-login',
             pass: '#page-user-pass'
Is is an account that I created on my xmpp server ? What about the #page-login-form ?

On the installation page
https://github.com/jsxc/jsxc/wiki/Install-jsxc-(WordPress)
There's a dead link
https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js

On step 4 it's written
Create a jsxc-custom.css file inside of the styles directory of your site (e.g. /data/mydomain.com/webroot/wp-content/themes/mytheme/css/).
But what should I put in it ?

Thank you for help

**Comment by sualko** [comment]
The guide was written für the [3.x branch](https://github.com/jsxc/jsxc/tree/master_3). So the link should be https://github.com/jsxc/jsxc/blob/master_3/src/jsxc.lib.options.js.

I'm sorry that I can't help you, but we have currently no time to give this type of user support.
