### ISSUE TITLE
Something went wrong. We have another master.

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#792]
### Expected behavior
There should be only 1 master in a multi tab environment
### Actual behavior
There is multiple masters in a multi tab environment
### Steps to reproduce the behavior
1. Open 3 tabs or more
2. Refresh all of them at short intervals

### Environment
- **JSXC version:** 4.0.0-b3
- **Host system and version:** CentOS 7
- **Browser vendor and version:** Chrome 75.0.3770.80
- **Any browser plugins enabled?** ARC & ITHit but nothing that can alter this behavior
- **XMPP server vendor and version:** Ejabberd 19.02
- **Is your XMPP server working with other clients as expected?** This behavior is proper to JSXC

#### Javascript
[Error] Something went wrong. We have another master.

#### JSXC
[Error] Something went wrong. We have another master.

#### XMPP
Front side error

#### Host
Nope
![Capture d’écran de 2019-07-22 11-28-04](https://user-images.githubusercontent.com/22454938/61622488-2eedd380-ac75-11e9-88ce-f0a692c2033e.png)
![Capture d’écran de 2019-07-22 11-28-02](https://user-images.githubusercontent.com/22454938/61622494-31502d80-ac75-11e9-81e4-d5bc5bd3b4b5.png)

Thanks in advance !

**Comment by sualko** [comment]
Can you post the complete log of both tabs?

**Comment by jlemangarin** [comment]
I've reproduced this issue 2 times but I'm unable to reproduce it anymore :S

I will work on the new JSXC implementation all this week so I will tell you if I reproduce the issue.

**Comment by sualko** [comment]
That would be great, because I'm also not able to reproduce this and I tried 5 tabs with live-reload.

**Comment by jlemangarin** [comment]
I cannot reproduce the issue, I think you can close the issue. 

We'll have a big test session starting from next week so I'll tell you if the issue happens again ! :)

**Comment by sualko** [comment]
> We'll have a big test session starting from next week so I'll tell you if the issue happens again ! :)

That's awesome. We are looking forward to your feedback. Btw I'm currently preparing another beta version, so it would be nice if you could use the latest release of JSXC. Should probably released this afternoon.

**Comment by jlemangarin** [comment]
Beta 4 up & running on my dev server, thank you for the resize fix and the global reliability of this 4.X branch (especially the multi tab part) ! :)

**Comment by jlemangarin** [comment]
Hello !

I can reproduce this random issue by doing the following : 

- Open 4 tabs with JSXC
- Close them
- Re open them using CTRL+SHIFT+T (~ 1tab/0.5s)

**Comment by sualko** [comment]
Sorry, but I still can't reproduce this. Can you please post both complete logs? Maybe you can also show the timestamps of the log entries.
