### ISSUE TITLE
Retrieve the roster when attaching an old connection

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#794]
### Expected behavior
The roster is retrieved after attaching a non expired old connection so the contact list is refreshed in case it changed 
### Actual behavior
The roster is not reloaded after attaching an old connection
### Steps to reproduce the behavior
1.Connect to your chat
2.Close your tab
3.Add a member to a shared roster where you are
4.Open your tab again, the old connection is reattached without the new contact

### Environment
- **JSXC version:** 4.0.0-b4
- **Host system and version:** CentOS 7
- **Browser vendor and version:** Chrome 75.0.3770.80
- **Any browser plugins enabled?** ARC & ITHit but nothing that can alter this behavior
- **XMPP server vendor and version:** Ejabberd 19.05
- **Is your XMPP server working with other clients as expected?** Can't find another client that is attaching again old connections after closing the app (but it must exists)

#### Javascript
//

#### JSXC
The polling starts again without get request

#### XMPP
//

#### Host
//

Thanks ! :)

**Comment by sualko** [comment]
Thanks for the tests. We really appreciate your work. Please keep it up. :+1: 

According to [RFC6121](https://tools.ietf.org/html/rfc6121#section-2.1.6) the roster should only be queried once at login and afterwards, the server should push changes to the client. Therefore I close this issue as invalid.

**Comment by jlemangarin** [comment]
Thank you for your answer and the explaination !

Is there anything in the specification related to a session that is not polled for a moment and the re attached after a while ? Like the informations that the server should save and send when the polling restart ?

It seems really strange that Ejabberd just drops all the information during this time if it should save it to transmit it later because as a result, we have an incoherence between the server and the client informations. 

I mean, that would make their XMPP protocol implementation really not reliable when Ejabberd is the WatsApp XMPP server..

Also, considering Ejabberd saying the client should retrieve the roster and you saying the server should deliver the changes after the reattaching, is there any way to just don't use this re attaching mechanism and force JSXC to open a new connexion when there is a new master for exemple ?

Thanks in advance !

**Comment by jcbrand** [comment]
AFAIK Ejabberd is at fault here, not JSXC.

> Ejabberd is the WhatsApp XMPP server..

It might have started that way years ago, but it isn't anymore.

**Comment by jlemangarin** [comment]
> AFAIK Ejabberd is at fault here, not JSXC.
Well, I'll open an Ejabberd issue :)

> It might have started that way years ago, but it isn't anymore.
They still use a customized fork of Ejabberd, right ?

Anyway if you have any clue to don't use the re attaching mechanism while it is not compatible with Ejabberd I'm interested !

Thank you !
