### ISSUE TITLE
vcard-temp not requested anymore

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#795]
### Expected behavior
The vcard-temp is requested to load avatars
### Actual behavior
The vcard-temp is not requested anymore
### Steps to reproduce the behavior
1.Log in

### Environment
- **JSXC version:** 4.0.0-b4
- **Host system and version:** CentOS 7
- **Browser vendor and version:** //
- **Any browser plugins enabled?** //
- **XMPP server vendor and version:** Ejabberd 19.05
- **Is your XMPP server working with other clients as expected?**  Yes

#### Javascript
//

#### JSXC
It might be something that I didn't understand but in the 4.X branch, JSXC does not retrieve the vcard-temp anymore. But it requests the private storage:bookmarks (that contains a room in my case)

3.X : 
```
<body rid='695812470' xmlns='http://jabber.org/protocol/httpbind' sid='750a3e1eb27d4ff78c96ec000e86c84d99f601bc'>
   <iq type='set' xmlns='jabber:client' id='a0906859-d761-406e-992c-02ffcfc249ab:sendIQ'>
      <enable xmlns='urn:xmpp:carbons:2'/>
   </iq>
   <iq type='get' xmlns='jabber:client' id='755eeff1-6b80-48d8-86c6-b8bf80439c70:sendIQ'>
      <query xmlns='jabber:iq:roster'/>
   </iq>
   <iq type='get' xmlns='jabber:client' id='66c60eef-3097-40e4-8844-72e8bace7817:sendIQ'>
      <vCard xmlns='vcard-temp'/>
   </iq>
</body>
```

4.X :
```
<body rid="2376187432" sid="8d8afcee89fa80229debd93ba7004656a4689e14" xmlns="http://jabber.org/protocol/httpbind">
   <iq id="30ab62d9-880a-4b37-9fea-8da5640588f6:sendIQ" type="set" xmlns="jabber:client">
      <enable xmlns="urn:xmpp:carbons:2"/>
   </iq>
   <iq id="79de54bc-6d9c-4a48-bef4-c02a6dcd3276:sendIQ" type="get" xmlns="jabber:client">
      <query ver="" xmlns="jabber:iq:roster"/>
   </iq>
   <iq id="3d3036a5-ddbe-4eca-9695-b3e8c38dad9c:sendIQ" type="get" xmlns="jabber:client">
      <pubsub xmlns="http://jabber.org/protocol/pubsub">
         <items node="storage:bookmarks"/>
      </pubsub>
   </iq>
</body>
```

#### XMPP
//

#### Host
//

Thanks in advance !

**Comment by sualko** [comment]
We still request the vcard, if the user [announces an avatar](https://xmpp.org/extensions/xep-0153.html#publish) in his presence update. If you have any problems with that, please reopen this issue.

**Comment by jlemangarin** [comment]
Oh well you're right, it's a configuration mistake.

Sorry for the inconvenience !
