### ISSUE TITLE
MAM retrieving makes my browser crash after reaching the first message

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#796]
### Expected behavior
The messages are retrieved properly
### Actual behavior
After reaching the first message, the browser crashes
### Steps to reproduce the behavior
1. Write some message with MAM module enabled
2. Load older messages until it crashes

### Environment
- **JSXC version:** 4.0.0-b4
- **Host system and version:** CentOS 7
- **Browser vendor and version:** Chrome 75.0.3770.80
- **Any browser plugins enabled?** ARC & ITHit but nothing that can alter this behavior
- **XMPP server vendor and version:** Ejabberd 19.05
- **Is your XMPP server working with other clients as expected?** Yes

#### Javascript

After a refresh of the crashed tab : 
![Capture d’écran de 2019-08-05 12-33-39](https://user-images.githubusercontent.com/22454938/62458478-55cffd80-b77d-11e9-9e0c-3310b0f0966f.png)
Then I have to clear the local storage to use again the chat

#### JSXC
Each block of messages is a click on the load button and the last > entries is the crash of my browser
![Capture d’écran de 2019-08-05 12-25-49](https://user-images.githubusercontent.com/22454938/62458409-202b1480-b77d-11e9-901a-59d19e93dd43.png)

#### XMPP

2019-08-05 12:25:20.451 [info] <0.1395.0>@ejabberd_c2s:process_terminated:290 (http_bind|<0.1394.0>) Closing c2s session for jleman@gofast-comm-internal.ceo-vision.com/jsxc-747ce09c: Connection failed: connection closed

#### Host

//

**Comment by sualko** [comment]
I saw this behavior before, but was not able to reproduce it. Can you give some more information? Did you use multiple clients? Was the message history empty as you clicked on the "load older messages" button? If it's possible it would be great if you could send me the complete xmpp messages to klaus@jsxc.org.

**Comment by jlemangarin** [comment]
Hello !

I can reproduce the issue with only 1 client and nothing else open. The message history was not empty, I just have to load olders messages (the messages are well retrieved and shown) until I reach the first stored message and then, it crashes.

I'm trying to send you the complete exchange but it's difficult because of the browser crashing.

**Comment by sualko** [comment]
Do you have only plaintext messages in your history, or also messages with attachment or some encrypted ones?

**Comment by sualko** [comment]
I finally crashed my browser too. Never was so happy about an error message and I think I have an idea what is happening.

**Comment by jlemangarin** [comment]
Nice ! 

Tell me if you need any complementary informations
