### ISSUE TITLE
Desktop sharing

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#8]
##

**Comment by beccon4** [comment]
Ideas to get this to work:
1. Use the Java desktop sharing application from Openmeetings. It works while it is not perfect. Advantage: As long as you have the Java VM installed, you can share your Desktop.
2. Add a VNC connection - such as Guacamole. Well - to share your screen you would have to run a VNC server. Not all folks can do that.

**Comment by sualko** [comment]
No need for Java, check this out: https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/

**Comment by danaskallman** [comment]
Would https://jitsi.org/Projects/JitsiMeet cover this since it has desktop sharing and it's referenced in #3 and #15?

**Comment by sualko** [comment]
https://github.com/otalk/getScreenMedia
