### ISSUE TITLE
variable  videoWindow is redundant (jsxc v4)

### ISSUE THREAD

**Issue by pussbb** [jsxc/jsxc#800]
https://github.com/jsxc/jsxc/blob/299011045166d264d1dc51598e3b476e73005dc5/src/ui/VideoDialog.ts#L48

instead of
```javascript
let videoWindow = new VideoWindow(this, session);

this.videoWindows[session.getId()] = videoWindow;
```
code can be more simpler 
```javascript
this.videoWindows[session.getId()] = new VideoWindow(this, session);
```

**Comment by sualko** [comment]
It's just a different code style. I like short lines and think that the two liner is a bit more readable.
