### ISSUE TITLE
Join room programatically

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#805]
Hello !

Is there any way to join rooms programmatically ? 

I tried to add the room to the storage server side but the information won't be pushed to the client until a new session is opened.

It seems that the JSXC JS object API has been deleted for the benefit of a black box.

Thanks in advance !

**Comment by sualko** [comment]
That's right. Currently the api doesn't provide a way to join a room. I will see if I can add it to the 4.0 release.

**Comment by jlemangarin** [comment]
I really need this one so I think I will work on this and PR, just wanted to know if it was wanted to not have an API in this 4.X branch like in the 3.X branch or not.

**Comment by sualko** [comment]
:hankey:  Had no coffee yet. I wanted to push this to a feature branch. It needs some more testing and maybe it doesn't provide all functionality you need. So a pr would be appreciated.

**Comment by jlemangarin** [comment]
Nice, thank you ! I'll work on this today and do the tests.

**Comment by jlemangarin** [comment]
I have still some work to do but could you check this commit please : https://github.com/jlemangarin/jsxc/commit/b1315a27bb0eeb8478d14407d214fd2d520124c8

I tried to follow your standards, hope it will be ok !
