### ISSUE TITLE
Site ssl error https://jsxc.org/

### ISSUE THREAD

**Issue by worldworm** [jsxc/jsxc#806]
there is an ssl error on your website
https://jsxc.org/

(if you add the "www" everything works fine)

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by sualko** [comment]
Fixed. Thanks for the notice :+1:
