### ISSUE TITLE
Sorry we couldn't complete your registration.  Your Nextcloud server cannot be used because https://gbranlaw.com/nc/index.php/apps/ojsxc/ajax/externalApi.php returned HTTP status code 406  Please report this to our issue tracker and mention the request id q0VFiXT62iGCrtBYbGpC.

### ISSUE THREAD

**Issue by CSchaefer70** [jsxc/jsxc#815]
### Expected behavior
To register for XMPP account
### Actual behavior
Sorry we couldn't complete your registration.

Your Nextcloud server cannot be used because https://gbranlaw.com/nc/index.php/apps/ojsxc/ajax/externalApi.php returned HTTP status code 406

Please report this to our issue tracker and mention the request id q0VFiXT62iGCrtBYbGpC.
### Steps to reproduce the behavior
1.Install JavaScript XMPP Chat onto NextCloud v16.0.1
2.Open Settings in NextCloud and select JavaScript Client
3.Select Managed, agree to terms and select "Register"

### Environment
- **JSXC version:** JavaScript XMPP Chat Version: 3.4.4 
- **Host system and version:** BlueHost Pro Shared server LINUX  NextCloud v16.0.1
- **Browser vendor and version:** Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- **Any browser plugins enabled?** Chrome Remote Desktop
- **XMPP server vendor and version:** Yours
- **Is your XMPP server working with other clients as expected?** Unknown

### Logs
$ State changed to INITIATING
$ State changed to PREVCONFOUND
$ check master
$ I am master.
$ State changed to ESTABLISHING
$ Try to attach
$ SID: internal
$ ATTACHED: null
$ UI State changed to INITIATING
$ Waiting for server capabilities
$ Request server capabilities
$ Send presence: <presence xmlns="jabber:client"><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="http://jsxc.org/" ver="UEMHBlT9XVU7FUwfm/6rl815MUE="></c></presence>
$ UI State changed to READY
$ DSA key loaded
$ State changed to READY
$ onPresence: <presence xmlns="jabber:client" type="unavailable" from="schaeferg@gbranlaw.com/internal" to="admin@gbranlaw.com/internal"></presence>
$ Presence (schaeferg@gbranlaw.com/internal): offline
$ webrtc.onpresence: "schaeferg@gbranlaw.com/internal"
$ Update icon: "schaeferg@gbranlaw.com"
$ Discover muc service
#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

I did setup SRV record as on the BlueHost server
![2019-08-23_12-32-28](https://user-images.githubusercontent.com/26978180/63608142-353bdc00-c5a2-11e9-809e-615c7ad6e134.png)
```
Open CPanel
Select the "DNS Zone Editor" (under "Domains").
Select the desired domain from the dropdown.
Under "Type", select "SRV" from the dropdown.

Service: jabber
Protocol: tcp
Host:
TTL: 14400
Type: SRV
Priority: 0
Weight: 0
Port: 5269
Points To: xmpp.gbranlaw.com
```
![2019-08-23_12-32-28](https://user-images.githubusercontent.com/26978180/63608158-44228e80-c5a2-11e9-8291-f366e8f258ca.png)
![2019-08-23_12-34-29](https://user-images.githubusercontent.com/26978180/63608210-6c11f200-c5a2-11e9-9127-9947f7f8c8e0.png)

**Comment by sualko** [comment]
`xmpp.gbranlaw.com` do you have an own XMPP server, or why did you setup an srv records?

This issue is caused by mod_security, as your server responses with: `An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.`. I'm not aware of any way to solve this issue on our side. If you have an idea, we appreciate any help, otherwise you probably have to disable the corresponding rule.
