### ISSUE TITLE
MAM retrieving doesn't works for MUC rooms

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#819]
### Expected behavior
Messages from MAM are retrieved in MUC rooms
### Actual behavior
Messages from MAM are not retrieved in muc rooms
### Steps to reproduce the behavior
1. Have messages to retrieve in a MUC room
2. Retrieve the messages
3.

### Environment
- **JSXC version:** 4.0.0-rc.1
- **Host system and version:** CentOS 7
- **Browser vendor and version:** Chrome 75.0.3770.80
- **Any browser plugins enabled?** ARC & ITHit but nothing that can alter this behavior
- **XMPP server vendor and version:** Ejabberd 19.05
- **Is your XMPP server working with other clients as expected?** IDK, MAM management of other clients is crap.

#### Javascript
//

#### JSXC
Here is a JSXC request for MAM retrieving : 
```
<body rid="1688637519" sid="9454d738aab80e89fd3f2af2bab2a7c574c468d7" xmlns="http://jabber.org/protocol/httpbind">
  <iq type="set" to="43@conference.gofast-comm-internal.ceo-vision.com" xmlns="jabber:client" id="e4cffa94-331b-4042-a15e-2f5660c945c4:sendIQ">
    <query xmlns="urn:xmpp:mam:2" queryid="625902cc-63b8-44cf-a14c-fa99b59cf408">
      	<x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE" type="hidden">
               <value>urn:xmpp:mam:2</value>
            </field>
            <field var="with">
               <value>43@conference.gofast-comm-internal.ceo-vision.com</value>
            </field>
            <field var="end">
               <value>2019-08-28T07:58:45.140Z</value>
            </field>
         </x>
    	<set xmlns="http://jabber.org/protocol/rsm">
          <max>20</max>
          <before></before>
   		</set>
    </query>
  </iq>
</body>
```
IDK why but the..
```
            <field var="with">
               <value>43@conference.gofast-comm-internal.ceo-vision.com</value>
            </field>
```
...part is preventing the messages retrieving. Here is the result with it : 
![Capture d’écran de 2019-08-28 10-17-36](https://user-images.githubusercontent.com/22454938/63838174-26c43a80-c97d-11e9-9ca1-c7bafcca7e4f.png)

And here is the result without it : 
![Capture d’écran de 2019-08-28 10-17-03](https://user-images.githubusercontent.com/22454938/63838248-4eb39e00-c97d-11e9-9840-3cfbc42b53a9.png)
![Capture d’écran de 2019-08-28 10-17-09](https://user-images.githubusercontent.com/22454938/63839442-99ceb080-c97f-11e9-9a38-f2677fffccb9.png)

Also (and I don't know why), the "time" field is incorrect, it's set to 2019-08-28T07:58:45.140Z and it should be 2019-08-28T08:58:45.140Z, I don't know why there is 1 hour shift here

Thanks a lot for your analyze on this !

#### XMPP
//

#### Host
//

**Comment by sualko** [comment]
> MAM management of other clients is crap

Similar to MUC it's a huge XEP with a lot of stuff which you don't need and this the reason why it's hard to implement. Also there are different server implementations which handles things differently. I think this bug is such a case. It works like a charm with prosody, but I guess ejabberd has a bug here, or I have a misunderstanding of the XEP. While I'm querying the archive of the muc room, I don't need the `with` field necessarily. So I will remove it for muc contacts.

**Comment by jlemangarin** [comment]
Yep sometimes it looks like the specs are written without caring of the reality of a multiple client/server implementation.. Anyway, a huge thanks for the fix !
