### ISSUE TITLE
Send files with correct mime type

### ISSUE THREAD

**Issue by Gatak** [jsxc/jsxc#824]
### Expected behavior
Image files should be sent to the http_upload host with correct mime type. For example `image/jpeg`

### Actual behavior
Image file is uploaded as `application/octet-stream` which prevents some clients from displaying the image inline and instead shows a download link. Browsers may also not show the image but asks the user to save it to disk instead. 

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
3.4.4
- **Host system and version:** 
Nextcloud 16
- **Browser vendor and version:** 
Opera, chrome, mobile. 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
Prosody 0.11.2, mod_http_upload_external. 
- **Is your XMPP server working with other clients as expected?** 
Yes 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
We had implemented version 0.7.0 and I think there was nothing specified regarding content type. In the latest version it seams they added the content type and changed the xml schema, but I was not able to find the old version to compare the changes. I will provide a fix asap. Thanks for reporting.
