### ISSUE TITLE
XMPP Chat Can't Download and Enable on 16.0.4

### ISSUE THREAD

**Issue by frankmaszinek** [jsxc/jsxc#828]
### Expected behavior

Download & Enable

### Actual behavior

An error occured during the request. Unable to proceed.
An exception occurred while executing 'ALTER TABLE oc_ojsxc_stanzas ADD PRIMARY KEY (`id`)': SQLSTATE[42S02]: Base table or view not found: 1146 Table '@#$%$#%.oc_ojsxc_stanzas' doesn't exist

### Steps to reproduce the behavior
1.  Go to Nextcloud Apps
2.  Navigate to XMPP CHat
3.  Click download & enable on XMPP chat.

### Environment
Host system and version:  Nextcloud 16.0.4

#### Javascript
vue-settings-apps-users-management.js?v=77d0f2bb-171:7 POST https://cloud.!@#$@!#$!@.org/settings/apps/enable 500
(anonymous) @ vue-settings-apps-users-management.js?v=77d0f2bb-171:7
t.exports @ vue-settings-apps-users-management.js?v=77d0f2bb-171:7
t.exports @ vue-settings-apps-users-management.js?v=77d0f2bb-171:19
Promise.then (async)
s.request @ vue-settings-apps-users-management.js?v=77d0f2bb-171:19
s.(anonymous function) @ vue-settings-apps-users-management.js?v=77d0f2bb-171:19
(anonymous) @ vue-settings-apps-users-management.js?v=77d0f2bb-171:7
post @ vue-settings-apps-users-management.js?v=77d0f2bb-171:1
(anonymous) @ vue-settings-apps-users-management.js?v=77d0f2bb-171:66
Promise.then (async)
enableApp @ vue-settings-apps-users-management.js?v=77d0f2bb-171:66
(anonymous) @ vue-settings-apps-users-management.js?v=77d0f2bb-171:12
c.dispatch @ vue-settings-apps-users-management.js?v=77d0f2bb-171:12
dispatch @ vue-settings-apps-users-management.js?v=77d0f2bb-171:12
enable @ vue-4.js:1
click @ vue-4.js:1
qt @ vue-settings-apps-users-management.js?v=77d0f2bb-171:7
n @ vue-settings-apps-users-management.js?v=77d0f2bb-171:7
Cr.i._wrapper @ vue-settings-apps-users-management.js?v=77d0f2bb-171:7
vue-settings-apps-users-management.js?v=77d0f2bb-171:66 {…} {appId: "ojsxc", error: Error: Request failed with status code 500
    at t.exports (https://cloud.@#$@!#$@#!.org/setti…}

**Comment by sualko** [comment]
Is there a trace in your nextcloud log? I guess the table is not created for some reason.
