### ISSUE TITLE
Registration trouble

### ISSUE THREAD

**Issue by stgodjah** [jsxc/jsxc#829]
### Expected behavior
Iam successfuly registered at xmpp server.

### Actual behavior
When I check check boxes in xmpp client, and click register. I god message from screenshot.
![Screenshot from 2019-09-21 19-10-52](https://user-images.githubusercontent.com/43356590/65375986-6c2d0c80-dc8a-11e9-9e4e-9eb1b88bf8b8.png)
  

### Steps to reproduce the behavior
1. Install ojsxc
2. Select server type as: Managed (Beta service) 
3. Click Register.

### Environment
- JSXC version: 3.4.4
- Host system and version: Nextcloud version: 16.0.3.0
- Browser vendor and version: Tor browser 6.9.0 
- Yes.

#### Javascript
JQMIGRATE: Migrate is installed, version 1.4.1
jquery-migrate.min.js:2:494
State changed to INITIATING
jsxc.js:184:9
State changed to PREVCONFOUND
jsxc.js:184:9
check master
jsxc.js:184:9
I am the slave.
jsxc.js:184:9
UI State changed to INITIATING
jsxc.js:184:9
UI State changed to READY
jsxc.js:184:9
check master
jsxc.js:184:9
webrtc.initWindow
jsxc.js:184:9
check master
jsxc.js:184:9

Server logs attached in screenshot.
!
![Screenshot from 2019-09-21 19-18-24](https://user-images.githubusercontent.com/43356590/65376100-94693b00-dc8b-11e9-8bd6-e439165a1e45.png)
![Screenshot from 2019-09-21 19-31-49](https://user-images.githubusercontent.com/43356590/65376257-61c04200-dc8d-11e9-848a-1ac669288f80.png)

After that I connect to host via ssh, and check connection to server from log. And result was succesful. See next attachment
![Screenshot from 2019-09-21 19-26-53](https://user-images.githubusercontent.com/43356590/65376234-1ad24c80-dc8d-11e9-86d8-a172f79ce7a6.png)

**Comment by MarcelWaldvogel** [comment]
Can you contact https://xmpp.jsxc.ch/registration from your server? (The "missing parameters" error message is expected)

**Comment by stgodjah** [comment]
> https://xmpp.jsxc.ch/registration
Yes. You can see that from my last screenshot.

**Comment by MarcelWaldvogel** [comment]
Sorry, the GitHub notification mail did not include that screenshot (and the other information you added later).

From the logs, there seems to be an issue verifying the server’s SSL certificate. I noticed the following unusual behavior: https://dev.ssllabs.com/ssltest/analyze.html?d=xmpp.jsxc.ch&hideResults=on (two certificate chains returned, one valid, one invalid). I will try to fix this later today. It works in browsers and with curl/wget, but maybe not with your PHP setup.

**Comment by MarcelWaldvogel** [comment]
I misread the SSLlabs output. The second part is only if you contact the server without [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). This is very likely not the problem, most as HTTPS clients have been doing this for 10+ years.

Can you contact any other HTTPS sites from PHP from that server? Also sites with Let's Encrypt-issued certificates?

[Does `php -r "print_r(openssl_get_cert_locations());"` point to the certificates?](https://akrabat.com/ssl-certificate-verification-on-php-5-6/) If not, you should [change certificate settings](https://www.saotn.org/dont-turn-off-curlopt_ssl_verifypeer-fix-php-configuration/) [(`openssl.cafile` and `curl.cainfo` in `php.ini`)](https://stackoverflow.com/questions/34515120/php-verify-failed-with-letsencrypt).

**Comment by stgodjah** [comment]
> I misread the SSLlabs output. The second part is only if you contact the server without [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). This is very likely not the problem, most as HTTPS clients have been doing this for 10+ years.
> 
> Can you contact any other HTTPS sites from PHP from that server? Also sites with Let's Encrypt-issued certificates?
> 
> [Does `php -r "print_r(openssl_get_cert_locations());"` point to the certificates?](https://akrabat.com/ssl-certificate-verification-on-php-5-6/) If not, you should [change certificate settings](https://www.saotn.org/dont-turn-off-curlopt_ssl_verifypeer-fix-php-configuration/) [(`openssl.cafile` and `curl.cainfo` in `php.ini`)](https://stackoverflow.com/questions/34515120/php-verify-failed-with-letsencrypt).

god@shop:~$ php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /opt/lampp/share/openssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /opt/lampp/share/openssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /opt/lampp/share/openssl/private
    [default_default_cert_area] => /opt/lampp/share/openssl
    [ini_cafile] => 
    [ini_capath] => 
)

**Comment by MarcelWaldvogel** [comment]
Anyone with access to your "API Secret" can query user information from your server. You may want to change this as explained in nextcloud/jsxc.nextcloud#25.

**Comment by MarcelWaldvogel** [comment]
Does `/opt/lampp/share/openssl/cert.pem` or the `/opt/lampp/share/openssl/certs/` dir contain the Let's Encrypt certificate? I.e., the X1 or X3 certificates as listed [here](https://letsencrypt.org/certificates/)?

**Comment by stgodjah** [comment]
> Anyone with access to your "API Secret" can query user information from your server. You may want to change this as explained in [nextcloud/jsxc.nextcloud#25](https://github.com/nextcloud/jsxc.nextcloud/issues/25).

Thanx. It's was my miss. But now I do your recommendation. 
![Screenshot from 2019-09-23 08-02-56](https://user-images.githubusercontent.com/43356590/65402701-9502ee00-ddbf-11e9-8b28-cc67cd7014cf.png)

**Comment by stgodjah** [comment]
> Does `/opt/lampp/share/openssl/cert.pem` or the `/opt/lampp/share/openssl/certs/` dir contain the Let's Encrypt certificate? I.e., the X1 or X3 certificates as listed [here](https://letsencrypt.org/certificates/)?

No, as I know. Because I have many virtual host, and for each I was generated letsencrypt certificate manually. And as a result  letsencrypt certificates stored as configured in file httpd-ssl.conf (in attach). I mean each certificate in its own folder. 
[httpd-ssl.conf.zip](https://github.com/jsxc/jsxc/files/3640693/httpd-ssl.conf.zip)
So, I make archive of my /opt/lampp/share/openssl/ folder.
[download-2019.9.23_5.24.36-god-(shop.fastfen.club).tar.gz](https://github.com/jsxc/jsxc/files/3640726/download-2019.9.23_5.24.36-god-.shop.fastfen.club.tar.gz)

**Comment by sualko** [comment]
The issue is that php can't verify our certificate. It's not related to your certificates.

The ssl3 warning is what bugs me, because ssl3 should not be used anymore. Which php version do you use? Also answers to Marcels questions would be helpful.

**Comment by MarcelWaldvogel** [comment]
The SSL3 warning is probably an API thing. If I remember correctly, you start with an SSL2/3 compatible handshake, even though you do not want to negotiate SSL3, but only TLS1.x.

**Comment by stgodjah** [comment]
> The issue is that php can't verify our certificate. It's not related to your certificates.
> 
> The ssl3 warning is what bugs me, because ssl3 should not be used anymore. Which php version do you use? Also answers to Marcels questions would be helpful.

god@shop:~$ php -v
PHP 7.2.16 (cli) (built: Mar  8 2019 15:11:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.16, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

And what question you mean? I'am  already answered to all questions, or I'am miss something?

**Comment by stgodjah** [comment]
> The SSL3 warning is probably an API thing. If I remember correctly, you start with an SSL2/3 compatible handshake, even though you do not want to negotiate SSL3, but only TLS1.x.

So, can I fix that situation in some way?

**Comment by sualko** [comment]
PHP version looks good.

> And what question you mean? I'am already answered to all questions, or I'am missed something?

I think you missed answers to the following two questions:

> Can you contact any other HTTPS sites from PHP from that server? Also sites with Let's Encrypt-issued certificates?

> Does /opt/lampp/share/openssl/cert.pem or the /opt/lampp/share/openssl/certs/ dir contain the Let's Encrypt certificate? I.e., the X1 or X3 certificates as listed here?

**Comment by stgodjah** [comment]
> PHP version looks good.
> 
> > And what question you mean? I'am already answered to all questions, or I'am missed something?
> 
> I think you missed answers to the following two questions:
> 
> > Can you contact any other HTTPS sites from PHP from that server? Also sites with Let's Encrypt-issued certificates?
> 
> > Does /opt/lampp/share/openssl/cert.pem or the /opt/lampp/share/openssl/certs/ dir contain the Let's Encrypt certificate? I.e., the X1 or X3 certificates as listed here?

I think that answered here https://github.com/jsxc/jsxc/issues/829#issuecomment-533963427

**Comment by stgodjah** [comment]
> The SSL3 warning is probably an API thing. If I remember correctly, you start with an SSL2/3 compatible handshake, even though you do not want to negotiate SSL3, but only TLS1.x.

So Marcel, can I fix that in some way? Or I need to wait solution from you or your team ?
