### ISSUE TITLE
Improved Phone Support

### ISSUE THREAD

**Issue by Cerothen** [jsxc/jsxc#83]
Good Morning,

I have managed to get the software setup with our OpenFire server and everything is working as it should so for that one I would like to extend my appreciation of the well crafted software. I would like to indicate that usability from a phone is very limited for both Owncloud and the chat client. Owncloud isnt a big deal since you can always log in without chat however if a user wanted to go specifically for the chat then the access is very limited due to resolution issues.

Are there any plans to improve the UI when it comes to usage on a phone browser?

Thanks,

**Comment by sualko** [comment]
@Zauberstuhl @johangm90 @jhass I would like to switch to bootstraps modal window, because it is responsive. Do you have any issues with that?

**Comment by johangm90** [comment]
i think it's a good idea

**Comment by sualko** [comment]
#217 adds phone support, so stay tuned for the release of v3.0.
