### ISSUE TITLE
File transfer not working on 4.0.0

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#831]
![attachment_was_not_processed_ojsxc4](https://user-images.githubusercontent.com/5199030/66344120-ae766f00-e955-11e9-8831-fbb8d9a4e77d.png)
### Expected behavior
Files are sent successfully in the last version of the app. Works nice with other clients.

### Actual behavior
Files and pictures are not sent, while I may see the preview of sent pics with yellow triangle.

### Steps to reproduce the behavior
1. Open chat
2. Start writing private message
3. Attach some file and send it.

### Environment
- **JSXC version:** 4.0.0
- **Host system and version:** Nextcloud 17.0.0
- **Browser vendor and version:** Google Chrome
- **Any browser plugins enabled?** yes
- **XMPP server vendor and version:** Prosody 0.11
- **Is your XMPP server working with other clients as expected?** yes

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by ana-jd** [comment]
i second that, file transfer doesn't work. It did in last version 3.4.2.
@ostasevych quick question : Do video calls work for you normally ?
Thanks in advance

**Comment by ostasevych** [comment]
Oh, sorry, actually, I had to rollback to the previous version, as I had written. Do you mean to test with 3.4 or 4.0 at nc17.0.0?

**Comment by ana-jd** [comment]
i meant on 4.0.0. (The only issue i had with 3.4 is the lack of responsive design )

**Comment by ostasevych** [comment]
> i meant on 4.0.0. (The only issue i had with 3.4 is the lack of responsive design )

Not so, I am getting an error: 
`Media failure: You or your browser denied media permission (NotAllowedError)`
at Google Chrome v77, win10 x64.
![media_failure](https://user-images.githubusercontent.com/5199030/66344359-53914780-e956-11e9-93b6-97dfe4af0ae1.png)

**Comment by ostasevych** [comment]
Are any updates on this issue?...

**Comment by ostasevych** [comment]
Hey, is anything changing with this app or it is dead?

**Comment by sualko** [comment]
@ostasevych it's open source, so it's always alive. I will try to work on it this week, so I hope we can make some progress.

I close this particular issue, because it has not enough information. Without any error message (especially in the js console), I can't do anything. If you have more information, please reopen.

**Comment by ostasevych** [comment]
So, what I found in Javascript debug console:
[Warn] Attachment was not processed
https://e.tdl/apps/ojsxc/js/jsxc/jsxc.bundle.js?v=18f06fb5

jsxc.bundle.js?v=18f06fb5:11 [Warn] Attachment was not processed
e.log	@	jsxc.bundle.js?v=18f06fb5:11
e.warn	@	jsxc.bundle.js?v=18f06fb5:11
(anonymous)	@	jsxc.bundle.js?v=18f06fb5:18
Promise.then (async)		
e.sendMessage	@	jsxc.bundle.js?v=18f06fb5:18
(anonymous)	@	jsxc.bundle.js?v=18f06fb5:25
Promise.then (async)		
e.sendOutgoingMessage	@	jsxc.bundle.js?v=18f06fb5:25
onInputKeyPress	@	jsxc.bundle.js?v=18f06fb5:25
dispatch	@	jquery.js:4435
_.handle	@	jquery.js:4121
