### ISSUE TITLE
Font colour of the chat is not readable with dark theme of Nextcloud

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#834]
### Expected behavior
The chat messages are to be readable adjusting to the of selected theme of nextcloud.

### Actual behavior
When changed to the dark theme the font colour of text in the chat (both texts and input fields) becomes light grey almost not giving any chance to read what is typed there.

### Steps to reproduce the behavior
1. Change the theme of Nextcloud to dark
2. See the results in any field or text box of JSCX chat

### Environment
- **JSXC version:* 3.4.0 and 4.0.0
- **Host system and version:** Nextcloud 16 and 17
- **Browser vendor and version:** Google Chrome
- **Any browser plugins enabled?** yes
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```
![ojscx_chat_black_mode_add_contact](https://user-images.githubusercontent.com/5199030/66315591-c1ba1800-e91e-11e9-9c4e-1edfc850e650.png)
![ojscx_chat_black_mode_settings](https://user-images.githubusercontent.com/5199030/66315593-c252ae80-e91e-11e9-9c98-cb07b0352eba.png)
![ojscx_chat_black_mode](https://user-images.githubusercontent.com/5199030/66315594-c252ae80-e91e-11e9-9452-3ceca3bab9de.png)
![ojscx_chat_normal_mode](https://user-images.githubusercontent.com/5199030/66315595-c252ae80-e91e-11e9-9cfe-2dfcde4d754f.png)

**Comment by Thothorg** [comment]
Hi,
The issue still exist on nextcloud 19.0.4 with firefox

**Comment by sualko** [comment]
Hi everyone,

I just want to let you know that I'm currently working on this. As you can see I made some progress, but it needs some jsxc core changes. It should hopefully be fixed with the next release.

![image](https://user-images.githubusercontent.com/2974196/100854938-ed388400-3489-11eb-9a80-1d0acf9411ac.png)

**Comment by deusoz** [comment]
Hi Klaus,
My approach was to effectively disable the "dark theme" effects on the chat, and I just keep it light background, grey text, black as one is typing.

This is css that I am using satisfactorily:

/*  CHAT APP jsxc */
.jsxc-send-area textarea, textarea.jsxc-message-input, textarea.jsxc-message-input:active, textarea.jsxc-message-input:focus, textarea.jsxc-message-input:not(:disabled):active, textarea.jsxc-message-input:not(:disabled):hover, textarea.jsxc-message-input:not(:disabled):focus {
background-color: rgba(22,22,22,.1) !important;
color: #222 !important;
padding-left: .4rem;
padding-bottom: .7rem;
}
.jsxc-content>p {color: #777; }
.jsxc-dialog {background: black !important; }
.jsxc-list__text__secondary { margin-right: .7rem;}
.jsxc-bar{color:rgba(255,255,255,0.5)!important;}

**Comment by deusoz** [comment]
Hi Klaus,
This was my approach.  The roster bar is kept in dark mode and the chat window in a light/grey mode. 

/*  CHAT APP jsxc */
.jsxc-send-area textarea, textarea.jsxc-message-input, textarea.jsxc-message-input:active, textarea.jsxc-message-input:focus, textarea.jsxc-message-input:not(:disabled):active, textarea.jsxc-message-input:not(:disabled):hover, textarea.jsxc-message-input:not(:disabled):focus {
background-color: rgba(22,22,22,.1) !important;
color: #222 !important;
padding-left: .4rem;
padding-bottom: .7rem;
}
.jsxc-content>p {color: #777; }
.jsxc-list__text__secondary { margin-right: .7rem;}
.jsxc-bar{color:rgba(255,255,255,0.5)!important;}
.jsxc-bottom, .jsxc-dialog, #jsxc-roster {background: black !important;}
![Screenshot_2020-12-03 Settings - DB5D Cloud Console](https://user-images.githubusercontent.com/3331362/100958886-73ea7100-351d-11eb-98d2-9769980f7195.png)

**Comment by deusoz** [comment]
I'm still tweaking my approach hold on

**Comment by deusoz** [comment]
this patch to css would permanently make the roster dark mode and the chat window in light mode, as I have it tweaked at present on Nextcloud 19 with both "dark mode" and "high contrast" checked

/*  CHAT APP 
![Screenshot_2020-12-03 Settings - DB5D Cloud Console(1)](https://user-images.githubusercontent.com/3331362/100962658-0e9a7e00-3525-11eb-8585-8fb4ce4b51f5.png)
jsxc */
.jsxc-send-area textarea, textarea.jsxc-message-input, textarea.jsxc-message-input:active, textarea.jsxc-message-input:focus, textarea.jsxc-message-input:not(:disabled):active, textarea.jsxc-message-input:not(:disabled):hover, textarea.jsxc-message-input:not(:disabled):focus {
background-color: rgba(22,22,22,.1) !important;
color: #222 !important;
padding-left: .4rem;
padding-bottom: .7rem;
}
.jsxc-content>p {color: #777; }
.jsxc-list__text__secondary { margin-right: .7rem;}
.jsxc-bar{color:rgba(255,255,255,0.5)!important;}
.jsxc-bottom, .jsxc-dialog, #jsxc-roster {background: black !important;}
.jsxc-icon--menu-dark {background-image: url("../images/menu_white.svg") !important;}

**Comment by sualko** [comment]
@deusoz thanks for the workaround, but I think it's a good opportunity to clean up the code a bit. I'm currently moving the code base to css variables which allows to use the nc colors without any modification.

**Comment by sualko** [comment]
The current master uses the Nextcloud colors now. This should fix all issues. It would be great if you could test the next beta release when it's coming out (probably today or tomorrow). Thanks for your patience. 

![2020-12-08 16 22 54 localhost e2ec58377d93](https://user-images.githubusercontent.com/2974196/101504608-b4117f80-3973-11eb-88be-b9d7c6d75ce5.png)
![2020-12-08 16 29 55 localhost aa3cc2443f23](https://user-images.githubusercontent.com/2974196/101504675-c5f32280-3973-11eb-98d0-217063367855.png)
![2020-12-08 16 36 22 localhost f88a0b4ca808](https://user-images.githubusercontent.com/2974196/101504682-c8557c80-3973-11eb-8f61-f27f31c66baf.png)
