### ISSUE TITLE
Intempestive room_creation popup

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#837]
### Expected behavior
There is no intempestive popup for the final user
### Actual behavior
The "Room_creation" popup shows
### Steps to reproduce the behavior
It's random but you have to be in a room and sometimes it shows up at the connection

### Environment
- **JSXC version:** 4.0.0 RC1
- **Host system and version:** Multiple (win10, ubuntu..)
- **Browser vendor and version:** Multiple (Last Chrome & FF versions)
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Ejabberd 19.05
- **Is your XMPP server working with other clients as expected?** 
Room management is a mess on other clients but they doesn't show these kind of popup

#### Javascript

//

#### JSXC
ToDo (we reverted our test platform snapshot so we will have to reproduce it)

#### XMPP
//

#### Host
//

Do you know if there is any way to disable this popup ? It's not fully translated, not themable and incomprehensible for our final users that doesn't want to have to configure anything.. :)

Thanks in advance !

**Comment by sualko** [comment]
Sorry for the lack of communication.

I translated the missing string, but I have currently no solution to omit this popup. In a further release we could add an option to force an instant room, but my current priority is to release a stable version asap.

**Comment by jlemangarin** [comment]
Hello !

Thank you for your answer, unfortunatly the XMPP protocol is a pain to implement and understand and it hasn't been a success internally or with our customers..

Due to that, we're going to move from XMPP to Riot.im/Matrix but I'll continue to support your project as I can because you're doing a great work and have a great project.

Thank you for your support these last months ! :)

**Comment by sualko** [comment]
> the XMPP protocol is a pain to implement and understand and it hasn't been a success internally or with our customers.

Sad to hear, but thanks for your support.
