### ISSUE TITLE
file transfer between jsxc clients in nextcloud 16

### ISSUE THREAD

**Issue by drlight17** [jsxc/jsxc#839]
Hello. I give up. I have a strange behavior of jsxc web clients in my nextcloud installation.
I have my configured Openfire 4.2.2 server (in DMZ with public ip). jsxc clients in nextcloud correctly activate file transfer function in dialog, but according to the console, this function tries webrtc instead of httpupload. 1 of 10 times httpupload method works. Screenshot 1 shows when httpupload works and screenshot 2 shows when client logout and login - httpupload somehow doesn't work. Between logout and login I did absolutely nothing! Can you please help me to discover what is wrong?
![1](https://user-images.githubusercontent.com/37434652/67616885-47c2d380-f7e6-11e9-9fca-5aadd3ebc427.png)
![2](https://user-images.githubusercontent.com/37434652/67616884-47c2d380-f7e6-11e9-8d52-fad9c2a1adb2.png)
I i've also tried to force httpUpload in jsxc.jsc (file.transportMethod = 'httpUpload';), but with no luck. Console says that file transferred using httpupload, but no link and file on the server appears.
PS. Other web client like conversejs works perfectly fine with the same server. Non-web clients too.

**Comment by sualko** [comment]
I'm concentrating on 4.0, therefore I can't give any support for 3.x. Sorry.
