### ISSUE TITLE
Master request from master. Something went wrong

### ISSUE THREAD

**Issue by jlemangarin** [jsxc/jsxc#840]
### Expected behavior
The master requests are properly handeled
### Actual behavior
Master request from master. Something went wrong
### Steps to reproduce the behavior
1. I just know the issue is related to a multi tab environment and the tab have been opened all the night

### Environment
- **JSXC version:** v4.0.0-rc.1
- **Host system and version:** Win 10
- **Browser vendor and version:** Chrome updated
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Ejabberd 19.05
- **Is your XMPP server working with other clients as expected?** No multi tab management on other clients

#### Javascript

//

#### JSXC
![pnklpecifikfhlin](https://user-images.githubusercontent.com/22454938/67930040-246d9f00-fbbf-11e9-9de4-290450962b3e.png)

#### XMPP

//

#### Host

//

Closing and reopening all tabs resolves the issue

**Comment by jlemangarin** [comment]
Actually the reproductability of the "Something went wrong, we have another master" error is high :S And it totally breaks all tabs until we close all of them.

**Comment by sualko** [comment]
> Actually the reproductability of the "Something went wrong, we have another master" error is high

Mmmmhhh... The issue is that I can't reproduce this. Did you insert additional log message?

**Comment by jlemangarin** [comment]
It's a mix of multiple causes I guess...

The most frequent occurence is when you have multiple tabs in a browser (that may be freezed by the browser) and you let these tabs runs all the night.

**Comment by jlemangarin** [comment]
Yeah moderns browsers have a "freeze" mechanism when you run out of ram, this also causes a lot of issues in our application..

**Comment by sualko** [comment]
my "fix" is more a dirty workaround, because currently there is no possibility to switch from master to slave. This would require to unbind all xmpp handlers and so on.
