### ISSUE TITLE
Login only possible by klicking on login twice

### ISSUE THREAD

**Issue by mmetzmac** [jsxc/jsxc#843]
### Expected behavior
put in UserID, klick log in and Nextcloid is loggin in the user
### Actual behavior
put in UserID and PW, klick login - nothing happens. Klicking on the Button (now showing "working" again, leads one to the NC Portal. This only happens, if Managed XMPP is selected in JavaScript Xmpp Client.
### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 3.4.4 
- **Host system and version:** Nextcloud 17.0.1
- **Browser vendor and version:** ALL
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Managed XMPP Server by JSXC 
- **Is your XMPP server working with other clients as expected?** yes 

#### Javascript
[Error] TypeError: JSON.stringify cannot serialize cyclic structures.
	stringify (jsxc.min.js:1:149994)
	setItem (jsxc.min.js:1:149994)
	updateItem (jsxc.min.js:1:151544)
	set (jsxc.min.js:1:2812)
	(anonyme Funktion) (jsxc.min.js:1:11134)
	each (main.js:14:3156)
	_prepareLogin (jsxc.min.js:1:11015)
	(anonyme Funktion) (jsxc.min.js:1:9755)
	success (ojsxc.js:247)
	u (main.js:25:22745)
	fireWith (main.js:25:23548)
	k (main.js:25:70734)
	(anonyme Funktion) (main.js:25:74246)

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by rfc2822** [comment]
I can reproduce that with the "external" option.

1. Install/enable jsxc (Nextcloud 17.0.1)
2. Set "external" XMPP server.
3. Log out
4. Log-in page: enter data, "Log in" → will send an XHR, but no user-visible response
5. Click "Log in" again → works

This is very confusing for users who will often think that logging in doesn't work when there is no visible response. There is no hint that you have to click the button or hit Enter again.

**Comment by sualko** [comment]
Sorry for the issue, but we have currently deferred support for 3.x. Issue should be resolved in the next release.
