### ISSUE TITLE
NextCloud 17 support

### ISSUE THREAD

**Issue by doudz** [jsxc/jsxc#844]
Nextcloud 17.0.1 is now available in updater, would it be possible to have a release for NC 17 ?
(Currently "only" available from 9 to 16)

**Comment by DBJRdev** [comment]
The 4.0.1rc1 works very well in 17.0.1 if you install it manually (not through App Store).
Yet there have been a number of commits with fixes since rc1, maybe a release candidate 2 or even release would anyway be cool?

PS: A big thank you to Sualko and the other contributors for the great piece of software!

**Comment by poVoq** [comment]
I agree, would be really nice to finally see a 4.0 release :)

**Comment by snapet** [comment]
Me too...
Guess they just don't find the time.

**Comment by sualko** [comment]
> Guess they just don't find the time.

That's right. There is currently a lot going on in real life. I'm really sorry that I had no time in the last weeks to work on jsxc, but I promise to create a release as soon as possible and I hope you understand.

**Comment by doudz** [comment]
> There is currently a lot going on in real life

I totally understand, thank you for all you do
this issue is just a kindly reminder

**Comment by DBJRdev** [comment]
@sualko : Just a ping - is there anything we can do as non-coders in order to support the development?

**Comment by sualko** [comment]
@DBJRdev your interest in jsxc is enough. I will probably release a beta version in the next days to get a stable release in some weeks. The currently biggest issue is nextcloud/server#15943, but there was some activity in the last days, so I hope this can be resolved too.

**Comment by Gatak** [comment]
Hello, Thank you for working on the XMPP chat. It is very useful and convenient! :) Now that Nextcloud 18 is out, do you think it can be made to work with it?

**Comment by sualko** [comment]
I didn't touch NC 18 yet, but as written above NC 17 has already a real showstopper. Maybe I have time tomorrow, but the lecture period is busy.

**Comment by Gatak** [comment]
:) No hurry! There are many apps not yet transitioned to NC18, so an upgrade is not feasible for a lot of people just yet.

A little OT, but would you mind if I submit some ideas or small issues on the bug tracker?

**Comment by sualko** [comment]
I just want to inform you, that I'm working on JSXC this week. So I hope we can have a release by end of the week.

**Comment by sualko** [comment]
With the release of JSXC 4.0 this issue has been resolved.
