### ISSUE TITLE
Kick/Ban users from group chat

### ISSUE THREAD

**Issue by calinalexandru** [jsxc/jsxc#846]
Hello.
Are the commands of kick/ban implemented in group chat? It seems to me that these tools are not available, or I missed something?
https://xmpp.org/extensions/xep-0045.html#kick

**Comment by sualko** [comment]
We handle those events, but there is currently no possibility to kick/ban someone inside JSXC.

**Comment by mightymop** [comment]
PR: https://github.com/jsxc/jsxc/pull/979
