### ISSUE TITLE
Password character "$" should be allowed

### ISSUE THREAD

**Issue by deusoz** [jsxc/jsxc#848]
or perhaps warnings posted.  It seems I've gotten them to work sometimes, but just now trying out 4.0.0-rc.1 with version 17 I again found that, even though I confirmed password separately via Ejabberdctl, the password would not go through on the client app "login" and password was already set for NC user correctly, so they matched.  But the problem was there was a dollar sign "$" in the password, once I replaced that it worked as expected.

**Comment by sualko** [comment]
After a quick test it looks like it's not an issue with jsxc core. It must be something inside the NC integration.

**Comment by sualko** [comment]
Sorry, I was not able to reproduce your issue. I tested with a local prosody installation and internal backend. My password was `mydollar$` and encountered no issues. If you have further information, please reopen this issue.
