### ISSUE TITLE
Need Help with CSP Policy

### ISSUE THREAD

**Issue by Panoptis** [jsxc/jsxc#85]
BOSH server NOT reachable.

Browser: Firefox 32.0.3
ownCloud: 7.0.2 (stable) 
ejabberd.cfg (/home/panoptis/ejabberd/etc/ejabberd)

```
{loglevel, 2}.
{hosts, ["panoptis.hamal.uberspace.de","cloud.panoptis.hamal.uberspace.de"]}.
{host_config, "panoptis.hamal.uberspace.de", [{auth_method, internal}]}.
{host_config, "cloud.panoptis.hamal.uberspace.de", [{auth_method, external}]}.
{extauth_program, "/home/panoptis/ejabberd/etc/ejabberd/auth_ejabberd_oc.php"}.
{listen, [
{63836, ejabberd_c2s, [
starttls, {certfile, "/home/panoptis/.ssh/ejabberd.pem"},
{access, c2s},
{shaper, c2s_shaper},
{max_stanza_size, 65536}
]},
{63837, ejabberd_http, [
http_bind,
http_poll,
web_admin,
tls,{certfile, "/home/panoptis/.ssh/ejabberd.pem"}
]}
]}.
{s2s_use_starttls, optional}.
{s2s_certfile, "/home/panoptis/.ssh/ejabberd.pem"}.
{domain_certfile, "panoptis.hamal.uberspace.de", "/home/panoptis/.ssh/ejabberd.pem"}.
{shaper, normal, {maxrate, 1000}}.
{shaper, fast, {maxrate, 50000}}.
{max_fsm_queue, 1000}.
{acl, admin, {user, "[removed]", "panoptis.hamal.uberspace.de"}}.
{acl, local, {user_regexp, ""}}.
{access, max_user_sessions, [{10, all}]}.
{access, max_user_offline_messages, [{5000, admin}, {100, all}]}.
{access, c2s, [{deny, blocked},
{allow, all}]}.
{access, c2s_shaper, [{none, admin},
{normal, all}]}.
{access, announce, [{allow, admin}]}.
{access, configure, [{allow, admin}]}.
{access, muc_admin, [{allow, admin}]}.
{access, muc_create, [{allow, all}]}.
{access, muc, [{allow, all}]}.
{access, pubsub_createnode, [{allow, admin}]}. 
{access, register, [{allow, all}]}. 
{language, "en"}.
{modules,
[
{mod_adhoc, []},
{mod_announce, [{access, announce}]}, 
{mod_blocking,[]}, 
{mod_caps, []},
{mod_configure,[]}, 
{mod_disco, []},
{mod_irc, []},
{mod_http_bind, []},
{mod_last, []},
{mod_muc, [
{access, muc},
{access_create, muc_create},
{access_persistent, muc_create},
{access_admin, muc_admin}
]},
{mod_offline, [{access_max_user_messages, max_user_offline_messages}]},
{mod_ping, []},
{mod_privacy, []},
{mod_private, []},
{mod_admin_extra, []},
{mod_pubsub, [
{access_createnode, pubsub_createnode},
{ignore_pep_from_offline, true}, % reduces resource comsumption, but XEP incompliant
{last_item_cache, false},
{plugins, ["flat", "hometree", "pep"]} % pep requires mod_caps
]},
{mod_register, [
{welcome_message, {"Welcome!"}},
{ip_access, [{allow, "0.0.0.0/0"},
{deny, "0.0.0.0/0"}]},
{access, register}
]},
{mod_roster, []},
{mod_shared_roster,[]},
{mod_stats, []},
{mod_time, []},
{mod_vcard, []},
{mod_version, []}
]}.
%%%.
%%%'
%%% $Id$
%%% Local Variables:
%%% mode: erlang
%%% End:
%%% vim: set filetype=erlang tabstop=8 foldmarker=%%%',%%%. foldmethod=marker:
```

When i visit:
https://cloud.panoptis.hamal.uberspace.de:63837/http-bind

I get an HTML page saying:
"ejabberd mod_http_bind" [...]

(should indicate that the BOSH server is indeed running?)

my config.php (/var/www/virtual/panoptis/cloud.panoptis.hamal.uberspace.de/config) entry currently looks like this:
"custom_csp_policy" => "default-src 'self' cloud.panoptis.hamal.uberspace.de:63837; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",

I tried with and without "https://"

In the settings of your App I also tried both:

[1] cloud.panoptis.hamal.uberspace.de:63837/http-bind
[2] https://cloud.panoptis.hamal.uberspace.de:63837/http-bind

they lead to DIFFERENT errors:
(they are in german because my firefox is):

[1]
`Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf cloud.panoptis.hamal.uberspace.de:63837/http-bind blockiert ("default-src https://cloud.panoptis.hamal.uberspace.de:443 https://cloud.panoptis.hamal.uberspace.de:63837").`

(NOTE in my config.php it says "cloud.panoptis.hamal.uberspace.de:63837" without "https://" and "https://cloud.panoptis.hamal.uberspace.de:443" is not in there at all (probably 'self'?))

[2]
`Cross-Origin-Anfrage blockiert: Die Same-Origin-Regel verbietet, die externe Ressource auf https://cloud.panoptis.hamal.uberspace.de:63837/http-bind zu lesen. Dies kann gelöst werden, indem die Ressource auf die gleiche Domain geschoben wird oder CORS aktiviert wird.`

[1] seems not to work because https:// is missing in BOSH url setting whie it is automatically appended to the config.php entry
[2] roughly translates to: Cross-Origin-Request Blocked: ...solve this by activating CORS

**Comment by xeux** [comment]
I'm using prosody with cors enabled, localhost conversejs connection to xmpp remote server works okay, but jsxc return cors error.

If I use the example html (file) works okay, but for some reason return cors in my own html (localhost).

**Comment by sualko** [comment]
@xeux please do not comment on such an old issue with a new problem. Open a new issue and add a link to this issue.

**Comment by xeux** [comment]
@sualko My bad Klaus. I will get into it.
