### ISSUE TITLE
Send File option is showing as strikethrough 

### ISSUE THREAD

**Issue by ismailmohammed** [jsxc/jsxc#850]
Hi,

Can any one please help me on this, I am seeing send file option as strikethrough. what I am missing?

![image](https://user-images.githubusercontent.com/10510073/71966063-eb892080-3226-11ea-9ef8-97ef7e4e63de.png)
In my jsxc.js file........
`RTCPeerConfig: {           
            ttl: 3600,           
            url: null,           
            withCredentials: false,            
            iceServers: [
                {
                    urls: 'stun:stun.stunprotocol.org'
                }
                , {
                    urls: 'turn:35.200.158.25',
                    credential: 'AASDF1@#',
                    username: 'Admin',
                    credentialType: 'password'
                }
            ]
        },`
In My jabbered Config File......
` port: 3478
    transport: udp
    user_turn: true
    turn_ip: "35.200.158.25" 
    module: ejabberd_stun
    certfile: "C:\\ProgramData\\ejabberd\\conf\\certificate.pem"
    auth_type: anonymous

    port: 3478
    transport: tcp
    user_turn: true
    turn_ip: "35.200.158.25" 
    module: ejabberd_stun
    certfile: "C:\\ProgramData\\ejabberd\\conf\\certificate.pem"
    auth_type: anonymous`
Regards,
Md.Ismail

**Comment by ostasevych** [comment]
Is file sending working at all on the version 4.0.0?

**Comment by sualko** [comment]
Hi. We deferred support for 3.x in order to release 4.0 asap. Hope you find time to test one of the next releases.
