### ISSUE TITLE
WebRTC only work one way

### ISSUE THREAD

**Issue by sedenion** [jsxc/jsxc#852]
### Expected behavior
Bidirectional Video and Audio using WebRTC

### Actual behavior
The Video and Audio works (is received) only by the peer whos intially request the call. The other peer, who accept the call, does not receive any video or audio. The experience can be inverted (the caller become the called and the called become the caller), the symptoms are inverted.

Notice that the WebRTC work perfectly with JSXC 3.4 with the exact same configuration (server and clients), the problem appear to be specific to JSXC 4.0 version.

### Steps to reproduce the behavior
1. Call a contact for Video chat
2. The Contact accept the Request

### Environment
- JSXC 4.0 Rc1
- Standalone server, Nginx, Coturn
- Firefox Linux/Window, Chrome
- Prosody

### Logs
I am not sure this is relevant for the current bug, since the "TypeError" is not 
systematical, but there is sometimes this...

#### JSXC
onaddstream is deprecated! Use peerConnection.ontrack instead.

TypeError: t[2] is undefinedjsxc.bundle.js:57:1150511
    candidate https://<my.domain.tld>/jsxc/jsxc.bundle.js:57
    toCandidateJSON https://<my.domain.tld>/jsxc/jsxc.bundle.js:57
    _checkLocalCandidate https://<my.domain.tld>/jsxc4/jsxc.bundle.js:57
    _onIce https://<my.domain.tld>/jsxc/jsxc.bundle.js:57
    <anonyme> self-hosted:876
    o https://<my.domain.tld>/jsxc/jsxc.bundle.js:74
    dispatchEvent resource://gre/modules/media/PeerConnection.jsm:802
    dispatchEvent resource://gre/modules/media/PeerConnection.jsm:1962
    onIceCandidate resource://gre/modules/media/PeerConnection.jsm:2023

RTCPeerConnection.getLocalStreams/getRemoteStreams is deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.

#### XMPP
N/A

#### Host
Coturn is working correctly

**Comment by ostasevych** [comment]
What about 3.4 version? Does it work?..

**Comment by sualko** [comment]
I guess this is related to the jingle library and I'm not sure if there is a fix available for that. I will try my best to get it running for you, but I currently have no issues.

**Comment by sualko** [comment]
It was probably triggered by [webrtc-adapter](https://github.com/webrtc/adapter) and I get no more warnings after the latest dependency update. If it's not fixed for you, please reopen.
