### ISSUE TITLE
Add image paste

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#856]
**Is your feature request related to a problem? Please describe.**
The modern chats contain the functionality of pasting not only text, but the images. Unavailability of this function leads to additional steps to be undertaken by potential user and thus make the app less comfortable for chatting.

**Is your feature request related to a specific XEP?**
XEP-0363

**Describe the solution you'd like**
Add pasting the image directly in the window of a chat. When pasted it is automatically http-uploaded to the server and ready to be sent to an interlocutor or muc.

**Additional context**
Furthermore additional tools on resizing, turning image may be added.

**Comment by sualko** [comment]
Nice idea. Didn't know that this is possible, but it seams that the [clipboard API](https://w3c.github.io/clipboard-apis/) supports such crazy things. See also https://web.dev/image-support-for-async-clipboard/

**Comment by git-it** [comment]
This looks like a nice easy feature to learn more about this wonderful project and start contributing! I believe merge 948 should close this out. Hope this is on track and contributed correctly :)
