### ISSUE TITLE
Received images are not shown but their links

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#860]
### Expected behavior
When someone send an image to me in the chat I see the resized picture in the chat, which may be clicked to make bigger.

### Actual behavior
I see only the link to the file in the http upload folder of my xmpp server

### Steps to reproduce the behavior
1. Send an image from outside to an account of a user
2. See the results in the chat window

### Environment
- **JSXC version:** 4.0.0
- **Host system and version:** Nextcloud 18.0.3
- **Browser vendor and version:** Google Chrome 80, x64
- **Any browser plugins enabled?** yes
- **XMPP server vendor and version:** Prosody 0.11.4
- **Is your XMPP server working with other clients as expected?** yes

![image](https://user-images.githubusercontent.com/5199030/77559471-e9993a00-6ec4-11ea-9c96-bb639e756733.png)

**Comment by sualko** [comment]
That's the normal behavior, because XEP-0363 says we should just send a link to the image. Of course we could try to guess the content type based on the suffix, but there must not be an suffix at all. We also would need to consider privacy implications and so on and so on. Currently this is out of scope.

**Comment by ostasevych** [comment]
> That's the normal behavior, because XEP-0363 says we should just send a link to the image. Of course we could try to guess the content type based on the suffix, but there must not be an suffix at all. We also would need to consider privacy implications and so on and so on. Currently this is out of scope.

In normal chats the pictures are shown in the form of either thumbnails or resized images. Not having this functionality limits essentially usage of the chat... May it be possible to give opportunity for a user to decide to show or not to show pictures?

**Comment by sualko** [comment]
> In normal chats the pictures are shown in the form of either thumbnails or resized images.

What is a normal chat? :wink:

>  May it be possible to give opportunity for a user to decide to show or not to show pictures?

It is. Pull requests welcome.

**Comment by ostasevych** [comment]
> > In normal chats the pictures are shown in the form of either thumbnails or resized images.
> 
> What is a normal chat? 
> 
I mean modern and friendly user.
> > May it be possible to give opportunity for a user to decide to show or not to show pictures?
> 
> It is. Pull requests welcome.
I am more a user than developer.... But thanks for reminding.

**Comment by ostasevych** [comment]
I am just wondered, whether it is possible to use some preview libraries to parse images and possibly video? For pdf, odf, docx, xlsx, etc to show the icon of the file extension. 
Here is simple tool for that:
https://github.com/promosis/file-upload-with-preview

Additionally I suggest to parse the urls, here is one of the solutions https://andrejgajdos.com/how-to-create-a-link-preview/

**Comment by sualko** [comment]
It's possible, but we first have to implement some click-here-and-harm-your-privacy button and it only works if csp and cors is configured to allow remote downloads.

**Comment by ostasevych** [comment]
> It's possible, but we first have to implement some click-here-and-harm-your-privacy button and it only works if csp and cors is configured to allow remote downloads.

Would you mind to add key trust to all of them and show without this button? Especially, if it is about users from one organisation?

**Comment by sualko** [comment]
That's a good idea.
