### ISSUE TITLE
XEP-0384: OMEMO Encryption 0.4.0+

### ISSUE THREAD

**Issue by Neustradamus** [jsxc/jsxc#861]
Can you update the XEP-0384: OMEMO Encryption support to 0.4.0+?
- https://xmpp.org/extensions/xep-0384.html

And XEP-0454: OMEMO Media sharing:
- https://xmpp.org/extensions/xep-0454.html

Diff Tool:
- 0.3.0 to current: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&doc2=https://xmpp.org/extensions/xep-0384.html
- 0.8.3 to current: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.8.3.html&doc2=https://xmpp.org/extensions/xep-0384.html
- 0.9.0 to 0.9.1: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.9.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.9.1.html
- 0.8.3 to 0.9.0: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.8.3.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.9.0.html
- 0.8.2 to 0.8.3: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.8.2.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.8.3.html
- 0.8.1 to 0.8.2: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.8.1.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.8.2.html
- 0.8.0 to 0.8.1: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.8.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.8.1.html
- 0.7.0 to 0.8.0: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.7.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.8.0.html
- 0.6.0 to 0.7.0: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.7.0.html
- 0.5.0 to 0.6.0: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html
- 0.4.0 to 0.5.0: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- 0.3.0 to 0.4.0: https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&doc2=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

PS: Not sure that 0.3.0 was complete before:
- https://xmpp.org/extensions/attic/xep-0384-0.3.0.html

**Comment by sualko** [comment]
It's too early to implement this. It's currently more for discussion.

**Comment by Neustradamus** [comment]
@sualko: Why close an important not solved ticket?
