### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#862]
### Expected behavior
File should be transferred
### Actual behavior

when attaching and trying to send a file i have the error below and the file is not sent :

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/TREsblvKanFxFSajBzk7fuWn3Noujk15zp9x5Gu8/1409.8020.pdf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/TREsblvKanFxFSajBzk7fuWn3Noujk15zp9x5Gu8/1409.8020.pdf. (Reason: CORS request did not succeed).

[http-upload][Warn] error while uploading file to http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt
[Warn] Attachment was not processed                                                  jsxc.bundle.js:1491:28

File transfer functioned properly in the old version 3.4.2

### Steps to reproduce the behavior
1. Attach a file
2. Send it
3.

### Environment
- **JSXC version:** 4.0.0 rc 1 and 4.0.0 rc2
- **Host system and version:** 
- **Browser vendor and version:** Firefox and Chrome
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Ejjaberd
- **Is your XMPP server working with other clients as expected?** Yes jsxc version 3.4.2

### Logs
Here is the stanza : 
[Debug] > 
[Debug] < 
[http-upload][Warn] error while uploading file to http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt           jsxc.bundle.js:1483:28
​
assignedSlot: null
​
attributes: NamedNodeMap [ xmlns="http://jabber.org/protocol/httpbind" ]
​
baseURI: "http://localhost:5280/http-bind/"
​
childElementCount: 1
​
childNodes: NodeList [ iq#75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ ]
​
children: HTMLCollection { 0: iq#75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ, length: 1, … }
​
classList: DOMTokenList []
​
className: ""
​
clientHeight: 0
​
clientLeft: 0
​
clientTop: 0
​
clientWidth: 0
​
firstChild: <iq id="75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ" xml:lang="en" to="admin2@localhost/jsxc-5d4c3d58" from="upload.localhost" type="result" xmlns="jabber:client">
​
firstElementChild: <iq id="75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ" xml:lang="en" to="admin2@localhost/jsxc-5d4c3d58" from="upload.localhost" type="result" xmlns="jabber:client">
​
id: ""
​
innerHTML: "<iq xml:lang=\"en\" to=\"admin2@localhost/jsxc-5d4c3d58\" from=\"upload.localhost\" type=\"result\" id=\"75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ\" xmlns=\"jabber:client\"><slot xmlns=\"urn:xmpp:http:upload\"><get>http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt</get><put>http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt</put></slot></iq>"
​
isConnected: true
​
lastChild: <iq id="75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ" xml:lang="en" to="admin2@localhost/jsxc-5d4c3d58" from="upload.localhost" type="result" xmlns="jabber:client">
​
lastElementChild: <iq id="75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ" xml:lang="en" to="admin2@localhost/jsxc-5d4c3d58" from="upload.localhost" type="result" xmlns="jabber:client">
​
localName: "body"
​
namespaceURI: "http://jabber.org/protocol/httpbind"
​
nextElementSibling: null
​
nextSibling: null
​
nodeName: "body"
​
nodeType: 1
​
nodeValue: null
​
onfullscreenchange: null
​
onfullscreenerror: null
​
outerHTML: "<body xmlns=\"http://jabber.org/protocol/httpbind\"><iq xml:lang=\"en\" to=\"admin2@localhost/jsxc-5d4c3d58\" from=\"upload.localhost\" type=\"result\" id=\"75a4245e-6330-446f-9b0e-06dd4b0c9ab8:sendIQ\" xmlns=\"jabber:client\"><slot xmlns=\"urn:xmpp:http:upload\"><get>http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt</get><put>http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt</put></slot></iq></body>"
​
ownerDocument: XMLDocument { … }
​
parentElement: null
​
parentNode: XMLDocument { … }
​
part: DOMTokenList []
​
prefix: null
​
previousElementSibling: null
​
previousSibling: null
​
scrollHeight: 0
​
scrollLeft: 0
​
scrollLeftMax: 0
​
scrollTop: 0
​
scrollTopMax: 0
​
scrollWidth: 0
​
shadowRoot: null
​
slot: ""
​
tagName: "body"
​
textContent: "http://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txthttp://localhost:5280/3397e06f983a0331790e62bf90abe585af3dc363/CcZZZPgchJRvqdMpOWMJkiAiE2m2xoZ1zTocviF4/CN1.txt"
​
<prototype>: ElementPrototype { getAttributeNames: getAttributeNames(), getAttribute: getAttribute(), getAttributeNS: getAttributeNS(), … }
jsxc.bundle.js:1483:28

**Comment by sualko** [comment]
The solution is in your error log: "Reason: CORS header ‘Access-Control-Allow-Origin’ missing". Just fix your http upload server ;-).

I'm not sure if this is still required, but one solution could be the following: https://www.ejabberd.im/forum/25600/httpupload-cors-problem-external-web-app/index.html
