### ISSUE TITLE
Document how to setup JSXC for an anonymous domain

### ISSUE THREAD

**Issue by linkmauve** [jsxc/jsxc#863]
**Is your feature request related to a problem? Please describe.**
I’d like to use JSXC without requiring users to have an XMPP account already, for instance for a support chat. You can see an example of what I want to achieve with such a setup using [Converse.js](https://conversejs.org/) here: https://chat.jabberfr.org/converse.js/programmation@chat.jabberfr.org

**Is your feature request related to a specific XEP?**
[XEP-0175](https://xmpp.org/extensions/xep-0175.xml)

**Describe the solution you'd like**
A method just like this one but for anonymous domains, that is without a pre-existing JID nor a password: https://jsxc.readthedocs.io/en/latest/api.html#jsxc-start-boshurl-jid-password

It should probably return an error if the domain doesn’t advertise the `ANONYMOUS` SASL mechanism.

**Additional context**
None that I could think of.

**Comment by sualko** [comment]
If your jid has no node part and your server supports sasl anonymous, than everything should work just fine. For example:

```
jsxc.start('/http-bind/', 'anon.localhost', null);
```

If the server doesn't support sasl anonymous you get a normal authentication failed error.
