### ISSUE TITLE
No files can be send with new version 4.0

### ISSUE THREAD

**Issue by Thomas301263** [jsxc/jsxc#866]
Hi,
I have upgraded the app in Nextcloud from version 3.4.4 to version 4.
Since then no files can be uploaded anymore and in Nextcloud Protokollierung I am getting lots of error messages like

Error | PHP | Invalid  argument supplied for foreach() at  /var/www/XXXXX/nextcloud/apps/ojsxc/lib/Controller/SettingsController.php#333
-- | -- | --

How can this be solved?

**Comment by ostasevych** [comment]
The same situation. Which kind of error message do you see?

**Comment by sualko** [comment]
Thanks for your report. I guess the message is unrelated to your error. Please provide all information required by the [issue template](https://github.com/jsxc/jsxc/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Especially the javascript console log would be interessting. I reopen the issue as soon as the information is provided.

**Comment by ostasevych** [comment]
I have a question, is there some community discussion where I may get and share my experience of working with ojsxc?. Or some learning base.

**Comment by sualko** [comment]
@ostasevych just open an issue, or send me an email to klaus@jsxc.org.

@Thomas301263 maybe the fix from @ostasevych is also working for you: https://github.com/jsxc/jsxc/issues/857#issuecomment-614091753
