### ISSUE TITLE
PNG files are not previewed in the chat window

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#867]
When uploading PNG files their content is not previewed correctly in thumbnails comparing to JPG.
Please, compare below:

![image](https://user-images.githubusercontent.com/5199030/79353125-5000fd80-7f43-11ea-9389-e247537ca60a.png)

**Comment by sualko** [comment]
Please use always the issue template. It will save me a lot of time and therefore I have more to work on features and bug fixes.

Btw can't reproduce this behavior.

**Comment by ostasevych** [comment]
After re-test it worked. Sorry, my fault with wrong test image files.
