### ISSUE TITLE
Lack of text chat during video calls

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#871]
### Expected behavior
To chat in text when talking using video call.

### Actual behavior
When I make videocall, the video takes my whole screen and I cannot send text messages to my interlocutor. 

![image](https://user-images.githubusercontent.com/5199030/79365948-079e0b80-7f54-11ea-83b9-6b2a202108b6.png)

### Steps to reproduce the behavior
1. Initiate or receive video call.
2. Observe

### Environment
- **JSXC version:** 4.0.0
- **Host system and version:** Nextcloud 18.0.3
- **Browser vendor and version:** Google Chrome 81, x64
- **Any browser plugins enabled?** yes
- **XMPP server vendor and version:** Prosody 0.11.4
- **Is your XMPP server working with other clients as expected?** yes 

### Suggestions:
1. Add the possibility to minimise the screen in a smaller window (see Hangouts).
2. Add the possibility to have the text chat on the left of the video frame (see Jitsi).
3. Add the controls for that.

**Comment by sualko** [comment]
> Add the possibility to minimise the screen in a smaller window (see Hangouts)

For screen sharing we have a ui with a minimized screen, so this should be easy to implement.

> Add the possibility to have the text chat on the left of the video frame (see Jitsi).

We had this in a previous version, but I was never comfortable with it. Maybe I look at it again.
