### ISSUE TITLE
Lack of vertical scroll bar in the chat window

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#873]
### Expected behavior
Easy user-friendly scrolling down and up in the chat window.

### Actual behavior
No scroll bar on the right, it is possible to scroll if to adjust properly touchpad or mouse behaviour.

### Steps to reproduce the behavior
1. Open chat window with some longread, eg some muc
2. Try to scroll up to find earlier messages
3. Observe

### Environment
- **JSXC version:** 4.0.0 
- **Host system and version:** NC 18.0.3
- **Browser vendor and version:** Google Chrome x64, v81
- **Any browser plugins enabled?** yes
- **XMPP server vendor and version:** prosody 11.4
- **Is your XMPP server working with other clients as expected?** yes 

![image](https://user-images.githubusercontent.com/5199030/79395957-7e063200-7f83-11ea-9fce-1f578a7e533d.png)

**Comment by sualko** [comment]
Mh. Usually there is a small scrollbar. Do you never see a scrollbar in the chat window?

Vivaldi/Chrome:
![2020-04-16 23 43 51 localhost 3ece17b113b8](https://user-images.githubusercontent.com/2974196/79509645-355e7f80-803c-11ea-8083-3b837ef95aae.png)

Firefox:
![Screenshot from 2020-04-16 23-45-28](https://user-images.githubusercontent.com/2974196/79509778-78b8ee00-803c-11ea-99c2-a79e43d759d1.png)

**Comment by ostasevych** [comment]
> Mh. Usually there is a small scrollbar. Do you never see a scrollbar in the chat window?
> 
...cut...

Ehmmm, it is strange, but I cannot see vertical scroll bar in Google Chrome v81
![image](https://user-images.githubusercontent.com/5199030/79609456-75d30180-80ff-11ea-9cbb-d5737c8b1c92.png)

**Comment by sualko** [comment]
Even in Chromium 81 I can't reproduce your issue.

**Comment by sadaszewski** [comment]
There is no scrollbar because of this: https://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox if you could please refrain from using flexbox or use a workaround for this issue this would be great. without a scrollbar it is a sad experience.

**Comment by sualko** [comment]
The author said:

> It shows one scrollbar

So how is this related to our issue?

> without a scrollbar it is a sad experience.

That's right, but if I can't reproduce it either in chrome nor firefox, I can't fix it. If you have an idea how I could reproduce it, or how it could be fixed, any help would be appreciated.

**Comment by sualko** [comment]
Good news everybody. I can reproduce this in Nextcloud, but not on the standalone version. Therefore the question: Did you try it only on your site, or also with our example?

**Comment by poVoq** [comment]
Hmm here it used to work fine in Nextcloud/Firefox but started to not work after the latest update. including no scrolling with the mousewheel, so it isn't only a cosmetic issue.

**Comment by sualko** [comment]
The scrollbar was visible on the example page, because there we use bootstrap for the overall design. Sorry for the inconvenience.
