### ISSUE TITLE
Archive exhausted

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#874]
### Expected behavior
Normal behaviour

### Actual behavior
At the beginning of the chat window I see message Archive exhausted. What does it stand for? How to solve it?

### Steps to reproduce the behavior
1. Open any chat, scroll up and observe the message Archive exhausted

![image](https://user-images.githubusercontent.com/5199030/79398924-9a599d00-7f8a-11ea-9d82-99e954a7dd54.png)

### Environment
- **JSXC version:** 4.0.0
- **Host system and version:** NC18.0.3
- **Browser vendor and version:** Google Chrome 81, x64
- **Any browser plugins enabled?** yes
- **XMPP server vendor and version:** prosody 11.4
- **Is your XMPP server working with other clients as expected?** yes

**Comment by poVoq** [comment]
Probably it means that you reached the end of messages that could be fetched via mam from the server.

**Comment by ostasevych** [comment]
> Probably it means that you reached the end of messages that could be fetched via mam from the server.

May I ask you for advice, how to deal with it?..

**Comment by poVoq** [comment]
If you need more/longer storage you need to reconfigure Prosodie's mod_mam:
https://modules.prosody.im/mod_mam.html

**Comment by sualko** [comment]
> Probably it means that you reached the end of messages that could be fetched via mam from the server.

That's right
