### ISSUE TITLE
MUC: list rooms that are not public but I am a member of

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#878]
**Is your feature request related to a problem? Please describe.**

Some users are added as members to MUCs  that are not publicly listed and where they didn't see the invitation or dismissed it and never added it as a bookmark. In that case, when they want to join that MUC and can't remember the exact JID they can't search for it when they want to enter it via JSXC.

**Describe the solution you'd like**

In addition to public MUCs, also list MUCs that are not public but the user is a member of.

**Comment by sualko** [comment]
Room discovery [returns only public rooms](https://xmpp.org/extensions/xep-0045.html#disco-rooms) and there is no configuration option on client side for the discovery. If the server supports the `muc#roomconfig_publicroom` config option, the room admin could allow public searching even for member only rooms.
