### ISSUE TITLE
yarn start don't work 

### ISSUE THREAD

**Issue by tititeco** [jsxc/jsxc#879]
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

**Comment by sualko** [comment]
Please use the issue template and provide the output of `ls`.

**Comment by tititeco** [comment]
hello i want creat this jsxc.bundle.css i dont see this in example, and  i dont see any exemple for integrate this in my website :(. i dont see dev , lib any and compile dont work me :(. dont easy instalation for test .

**Comment by sualko** [comment]
>  dont easy installation for test

You can use the online example: https://www.jsxc.org/example/

You can download the latest release: https://github.com/jsxc/jsxc/releases/tag/v4.0.0

You can use our installation guide: https://jsxc.readthedocs.io/en/latest/getting-started/installation.html

You can also use our developer notes to build your own version: https://jsxc.readthedocs.io/en/latest/development/notes.html

And you can also test the latest nightly: https://www.jsxc.org/example-nightly/

I think there are enough possibilities.

**Comment by tititeco** [comment]
Me is website created in php. I dont have wordpress, nextcloud, illias or sogo. I have server xmpp prosody working with pidgin and converse . i have see all doc. I don't see any past with jsxc.bundle.js , and i dont see any installation for compile your appli.  in converse i am just go in paste root, i am make dev and all dev created. in jsxc make dont work yarn have error , and i dont see any paste with jsxc.bundle.css and jsxc.bundle.js for test in my instalation.
sorry for my english, your appli messeger is cute, i understand when compilation finished is easy for modify the config is clean code ! juste for me dont work compilation to integrate in my website :( 

and i have see https://jsxc.readthedocs.io/en/latest/getting-started/installation.html for because i dont have any .js and .css bundle i understend creat past css and js just i dont see bundle.js and bundle.css 

and thx for talk me ! i understend talk with newb is hard.

**Comment by sualko** [comment]
> and i have see https://jsxc.readthedocs.io/en/latest/getting-started/installation.html for because i dont have any .js and .css bundle i understend creat past css and js just i dont see bundle.js and bundle.css

You just have to do what it says: "download and extract jsxc <https://github.com/jsxc/jsxc/releases> to a folder of your choice".

The tar file (https://github.com/jsxc/jsxc/releases/download/v4.0.0/jsxc-4.0.0.tar.gz) contains all necessary files. Have fun.

**Comment by tititeco** [comment]
i can modify or juste source modify code ? later i want work just javascrypt i dont like work with jquery; with  javascrypt i understend more.

**Comment by sualko** [comment]
> i can modify or juste source modify code ?

You can, but that's a bad idea.

> later i want work just javascrypt i dont like work with jquery; with javascrypt i understend more

As every modern application our build stack is huge. We use typescript with several libraries and webpack for bundling. I guess you have to lern something new :wink:

**Comment by tititeco** [comment]
I will test the compiled .tar.gz to see the result.

i can talk later for help again?

and thank you for your time

**Comment by tititeco** [comment]
the tar.gz doesn't work either. it is missing the jquery that I took it from the source code. But it didn't work either

**Comment by tititeco** [comment]
where work just have bug in firefox no webcam ! just in crhome cam work ! and i dont understand yarn for compile and repair bugs :/

**Comment by sualko** [comment]
> t is missing the jquery

It's called a dependenciy :wink:, but you are right it's not documented in the installation guide.

> where work just have bug in firefox no webcam ! just in crhome cam work ! and i dont understand yarn for compile and repair bugs :/ . this bug is in bootstrap in firefox cache picture ....

Sorry I don't understand you.

**Comment by tititeco** [comment]
I can't compile on debian / buster. The tars compiled there is no possibility to change the avatar. I gave up. thx for your time.

**Comment by sualko** [comment]
If you search for your error message above you will find this post as first entry: https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

Means you have not installed the [yarn package manager](https://yarnpkg.com/).
