### ISSUE TITLE
Where is the JSXC logo SVG?

### ISSUE THREAD

**Issue by Neustradamus** [jsxc/jsxc#881]
I search the normal JSXC logo in SVG, where is it?

I only have found a white logo...
- https://github.com/jsxc/jsxc/blob/master/images/jsxc_white.svg

**Comment by sualko** [comment]
See https://github.com/jsxc/jsxc.org/tree/master/promo

**Comment by Neustradamus** [comment]
@sualko: Can you add the normal JSXC logo in the client?
It is the base :)
