### ISSUE TITLE
Issue track id: BPIbfNhWwSqBUsEBfmCD

### ISSUE THREAD

**Issue by veritas44** [jsxc/jsxc#883]
### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```issue id:  BPIbfNhWwSqBUsEBfmCD

#### Host
<!-- Do you have any related entries in your host system log? -->
```
```
Nextcloud  at apkhr.xyz,error  returned HTTP status code 403

**Comment by ostasevych** [comment]
Spam detected
