### ISSUE TITLE
Chat sidebar appears before TOTP

### ISSUE THREAD

**Issue by RabbitDuck** [jsxc/jsxc#885]
Chat sidebar appears before TOTP verification.
Can we disable this behaviour?

Nextcloud ver: 18.0.4
JavaScript XMPP Chat : 4.0.0

![2020-04-29_09-02](https://user-images.githubusercontent.com/31124140/80552991-dc5af800-89fa-11ea-960b-d824a218be32.png)

**Comment by sualko** [comment]
Can you give me the url of that page?

**Comment by piti-diablotin** [comment]
I experience the same behaviour on my page 
NC 18.0.3
OJSXC 4.0

**Comment by sualko** [comment]
@piti-diablotin can you please provide the url of that challenge page?

**Comment by piti-diablotin** [comment]
I cannot since I need to log in to get the challenge TOTP ...

**Comment by sualko** [comment]
> I have basic knowledge of js/html maybe I get you the information you are looking for ?

If you have the same behavior, you don't need any knowledge. You just have to copy the url / site address to this issue. It's probably `https://your.domain/index.php/login/challenge` or something like that.

**Comment by piti-diablotin** [comment]
Ok then...
Here is the url: https://www.geduld.fr/index.php/login/challenge/totp

**Comment by RabbitDuck** [comment]
Thanks sualko and piti-diablotin

**Comment by piti-diablotin** [comment]
Thanks @sualko
