### ISSUE TITLE
Nextcloud: Active Directory users cannot receive messages

### ISSUE THREAD

**Issue by AdamVenn** [jsxc/jsxc#887]
Hi there, I have a problem with jsxc 4.0.0 on Nextcloud.

It has already been reported [here](https://github.com/nextcloud/jsxc.nextcloud/issues/114), but nothing seems to have happened over on that repo, and the 'Report a bug' link took me here, so I wanted to re-report it here. Hope that's okay, I don't know what affiliation there is between the two repos.

The problem is that, when using Nextcloud's Active Directory integration, AD users are not permitted to receive messages, as shown in the log entries:

`{"reqId":"3Dtb3o38gE3D5pIv72Rk","level":2,"time":"2020-05-06T17:17:43+00:00","remoteAddr":"10.150.60.1","user":"nc-admin","app":"ojsxc","method":"POST","url":"/index.php/apps/ojsxc/http-bind","message":"User nc-admin is trying to send a message to c5a76b19-7781-40af-b192-723f1f0190ac but this isn't allowed","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}`

Since this is explicitly forbidden and logged by line 76 in lib/stanzahandlers/message.php, I expect there is a good reason! Can anyone offer any explanation/workaround?

`		if (!$this->userProvider->hasUserByUID($this->to)) {
			$this->logger->warning('User ' . $this->userId . ' is trying to send a message to ' . $this->to . ' but this isn\'t allowed');
			return;
		}`

Thank you!

**Comment by sualko** [comment]
I will answer in the other issue.
