### ISSUE TITLE
Can't get managed account from xmpp/ Hetzner account

### ISSUE THREAD

**Issue by YGMG-4429** [jsxc/jsxc#888]
### Actual behavior: error message "Sorry we couldn't complete your registration.
unknown error
Please report this to our issue tracker and mention the request id no-request-id.
### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:**  Nextcloud 
- **Browser vendor and version:** Iridium
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** JSXC 3.x
- **Is your XMPP server working with other clients as expected?** not tried yet

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by YGMG-4429** [comment]
!!! Re-tried with FireFox and it worked right away...

**Comment by sualko** [comment]
> Re-tried with FireFox and it worked right away...

:tada:
