### ISSUE TITLE
Add contact API

### ISSUE THREAD

**Issue by mreid0345** [jsxc/jsxc#892]
The issue im having is i need to be able to add to the roster programatically. I can use requests but need to be able to control the roster.

Any help or examples you could offer would be great. 

Thanks in advanced,
Matthew B Reid

**Comment by sualko** [comment]
Currently you can only [add muc contacts (aka rooms)](https://jsxc.readthedocs.io/en/latest/api.html#account-createmultiusercontact-jid-nickname-displayname-password), but if you like to have contacts from other sources, like ldap, in your roster, you should checkout the extensions for your xmpp server.

**Comment by mreid0345** [comment]
Thank you. I will try it that way
