### ISSUE TITLE
My Companies plan for JSXC (is it possible?)

### ISSUE THREAD

**Issue by mreid0345** [jsxc/jsxc#893]
We are creating, using jsxc, a global overlay chat on all pages of our site; we have a Manage Contacts page which handles the requests and basically only need the ability to launch and persist muc chat rooms. 

Were not going to be using the roster, we are wondering how that might play out if you have any ideas would be much appreciated.

Also i need to disable file transfer. 

This will be a pretty simple setup, no roster so user uses manage contacts page to launch a chatbox overlayed without redirect, but it needs to open persistantly until the close x is clicked (event handler)

My boss says he is willing to help with the cost of time.

Please let me know what you think when you have a moment, I really like jsxc, were switching from converse.js there were TONS of problems, so complicated every setup is different so they never tested their code in all ways. never deprecated..

Okay thank you for your time,
-Matthew B Reid
Senior Developer
ArtistArmor, Los Angeles

**Comment by sualko** [comment]
Thanks for the kind words about JSXC. I'm really happy that you enjoy it.

> basically only need the ability to launch and persist muc chat rooms

To understand what you mean it would be helpful to know what you try to archive. Should the windows still appear at the bottom of the screen?

> Also i need to disable file transfer.

You can just disable the http upload plugin and hide the upload button (this should be automated by jsxc in the future).

> My boss says he is willing to help with the cost of time.

Please write an mail to klaus@jsxc.org for consulting and discussion about details of your application.
