### ISSUE TITLE
X-OAUTH2 authentication failed

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#894]
### Expected behavior
when trying to test instant log in version 4.1.0 i can't connect.
On ejabberd side i have [warning] (http_bind|<0.603.0>) Failed c2s X-OAUTH2 authentication for admin@localhost from ::1: Invalid token

ERROR in jsxc_bundle.js :

  | e.log | @ | jsxc.bundle.js:4669
-- | -- | -- | --
  | e.warn | @ | jsxc.bundle.js:4655
  | (anonymous) | @ | jsxc.bundle.js:69749
  | Promise.catch (async) |   |  
  | h | @ | jsxc.bundle.js:69748
  | (anonymous) | @ | jsxc.bundle.js:69725
  | (anonymous) | @ | jsxc.bundle.js:69690
  | (anonymous) | @ | jsxc.bundle.js:69701
  | a | @ | jsxc.bundle.js:69607
  | Promise.then (async) |   |  
  | u | @ | jsxc.bundle.js:69625
  | (anonymous) | @ | jsxc.bundle.js:69627
  | i | @ | jsxc.bundle.js:69604
  | l | @ | jsxc.bundle.js:69719
  | t.start | @ | jsxc.bundle.js:69774
  | (anonymous) | @ | example.js:52
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

### Steps to reproduce the behavior
1. use instant login
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
Please provide information about your setup. Which XMPP server do you use?

As you can see from my referenced issue above, the SASL priorities changed in our used XMPP library. The easiest workaround for you would be to disable OAUTH on the server side.

**Comment by ana-jd** [comment]
I disabled the OAUTH and it does function properly. I hope this doesn't impact other functions.

Thank you !

**Comment by poVoq** [comment]
I have the same issue with ejabberd 20.04. I don't think I have oauth enabled (but I will double check) and login was working fine with JSXC version 4.0 (via the Nextcloud app).

**Comment by MarcelWaldvogel** [comment]
Add the following to `/etc/ejabberd/ejabberd.yml` and reload the config:

```yml
disable_sasl_mechanisms: ["X-OAUTH2"]
```

That fixed it for me. I think `strophe.js` should not send the password as OAUTH information.
