### ISSUE TITLE
Add outgoing and in incoming ringing tone

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#895]
**Is your feature request related to a problem? Please describe.**

When receiving an a/v call it is quite easy to miss the incoming notification, so a subtle ringing tone for incoming calls would be nice.
Also for outgoing calls a subtle ringing tone would be nice to signal to the user that JSXC is waiting for the contact to pick up the call.

**Describe the solution you'd like**

Add outgoing and in incoming ringing tones.

**Comment by ostasevych** [comment]
Please, add the option to turn this on or off, as well, and change the melody.

**Comment by sualko** [comment]
Please fill the issue template, because ringtones are included and I don't know which version you are using.
