### ISSUE TITLE
A/V call: minimizing is too extreme ;)

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#896]
### Expected behavior

When minimizing an A/V call I still want to see some parts of it, its controls for example at the very least and when having video I still want to see my chat partner albeit smaller.

### Actual behavior

1. When minimizing a video call the minimized version only shows my own video feed, not the one of my chat partner.
2. When minimizing an audio call, the call controls completely vanish. The call still goes on but I can't stop it anymore.

### Steps to reproduce the behavior
1. Create an A/V call
2. click on the minimize icon
3. See extreme minimizing ;)

### Environment
- **JSXC version:** 4.1
- **Host system and version:** Nextcloud 18.0.4
- **Browser vendor and version:**  Chromium 80
- **Any browser plugins enabled?** No

#### Javascript
No errors logged.

**Comment by sualko** [comment]
I fixed only part two, because part one is by Intention.

**Comment by ostasevych** [comment]
Not possible to move the small window on the screen, it is always stick to the left top corner, though the mouse control exist for moving it.
![image](https://user-images.githubusercontent.com/5199030/85330567-541a4000-b4dd-11ea-92b1-d082a26aa2dd.png)

Google Chrome 83, NC 19.0.0.12

**Comment by ostasevych** [comment]
With audio call I suggest to start not in a full screen, but with a small screen, as there are no video by default.
