### ISSUE TITLE
Clicking on status "online" when already set to "online" prompts for login credentials instead of ignoring

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#897]
### Expected behavior

When clicking on the status "online" while already having set the status "online", nothing should happen (just like clicking on another status that I already have).

### Actual behavior

The user is prompted for the login credentials.

### Steps to reproduce the behavior
1. Have your status as "online"
2. Click on the status "online"
3. See the prompt for login credentials.

### Environment
- **JSXC version:** 4.1
- **Host system and version:** Nextcloud 18.0.4
- **Browser vendor and version:** Chromium 80
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Prosody 11.5
- **Is your XMPP server working with other clients as expected?** Yes

#### Javascript
No errors logged.

**Comment by republicus** [comment]
I don't see this behavior. I am also on Nextcloud 18.0.4 and when I click Online, when already Online: I go Offline.
