### ISSUE TITLE
Unable to log in with version 4.1.0 

### ISSUE THREAD

**Issue by piti-diablotin** [jsxc/jsxc#898]
### Expected behavior
JSXC should log in when correct username and password are provided.

### Actual behavior
`Authentication failed with the chat server. Maybe the password is wrong?`

### Steps to reproduce the behavior
1. Log in to NC with or without chat
2. Try to lgo online with JSX
3. Fill username/password

### Environment
- **JSXC version:**  4.1.0
- **Host system and version:** NC 18, whatever the OS and browser
- **XMPP server vendor and version:** ejabberd
- **Is your XMPP server working with other clients as expected?** Yes and works with 4.0.0

###  Bosch reply is 
```
XHRPOSThttps://www.domain.fr/http-bind/
[HTTP/1.1 200 OK 29ms]
    <body xmlns='http://jabber.org/protocol/httpbind'><failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text xml:lang='en'>Invalid token</text></failure></body>
```
Not sure to understand where the problem is.
Downgrading to 4.0.0 works...

**Comment by ana-jd** [comment]
just add "disable_sasl_mechanisms: ["X-OAUTH2"]" to your ejabberd.yml and it should work. I had the same issue, they changed the auth function

**Comment by piti-diablotin** [comment]
Thks ! It works indeed.
But eventhough, my server was offering PLAIN and X-OAUTH2 mechanism, why jsxc switch from PLAIN to X-OAUTH2 as default ? (Just my curiosity)
I close the issue.
Thank you

**Comment by sualko** [comment]
> why jsxc switch from PLAIN to X-OAUTH2 as default ?

Our used xmpp library changed the sasl priorities, see https://github.com/strophe/strophejs/issues/350. We will hard code those priorities in the next release. Sorry for trouble and thank you @ana-jd for helping out.

**Comment by piti-diablotin** [comment]
Thanks for the explanation !
