### ISSUE TITLE
http upload

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#899]
### Expected behavior
On version 4.1.0 files are not sent, i have the Error: "Found no suitable http upload service. File probably too large."

i had the same issue on version 4.0.0 but i did fix it by configuring my ejabberd server and adding http_upload module. 

On the same ejabberd server jsxc 4.0.0 sends files successfully but not jsxc 4.1.0

What did change in the new version ?

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 4.1.0
- **Host system and version:** 
- **Browser vendor and version:** Chrome and firefox
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** Ejabberd 18
- **Is your XMPP server working with other clients as expected?** jsxc 4.0.0

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
You find a list of changes here: https://github.com/jsxc/jsxc/commits/master/src/plugins/httpUpload

I guess the change to http upload 1.0 https://github.com/jsxc/jsxc/commit/fdb1501de08e5392dbf761bcc56686d35228010e#diff-2d2b59c3e56bb37178b4a3d00b333306 is breaking for you. If you enable debugging you should find the root cause. Maybe you can also post it, to debug this further.

**Comment by ana-jd** [comment]
I've got nothing on  logs (see attached image)
![Screen-Shot-2020-05-22-at-8 08 42-PM](https://user-images.githubusercontent.com/49027328/82706471-2eddac00-9c69-11ea-83e0-3d5597a8937a.jpg)

Also this is my ejabberd 17.01 config :

ejabberd.yml :
.....
  port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
      "/upload": mod_http_upload
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false
    certfile: "/opt/ejabberd-17.01/conf/server.pem"
    tls: true
.....
 mod_http_upload:
       docroot: "/opt/ejabberd-17.01/upload"
       put_url: "https://@HOST@:5280/upload"
       thumbnail : true
       file_mode: "0644"
       dir_mode: "0755"
       max_size: infinity
       custom_headers:
         "Access-Control-Allow-Origin": "*"
         "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS, DELETE"
         "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"

Could it be that ejabberd 17 version that doesn't support http upload 1.0 ?

**Comment by sualko** [comment]
Please enable debug mode (`jsxc.enableDebugMode()`) and look at the stanzas. You should see the http upload slot request and the corresponding response.

**Comment by sualko** [comment]
Any update?

**Comment by ana-jd** [comment]
I  will give you a feedback very soon.

**Comment by ana-jd** [comment]
Hello,

this is what i have in debug mode : 

[Debug] < 
body
​
assignedSlot: null
​
attributes: NamedNodeMap [ xmlns="http://jabber.org/protocol/httpbind" ]
​
baseURI: "https://xyz-tlm.com:5280/http-bind/"
​
childElementCount: 1
​
childNodes: NodeList [ iq#118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ
 ]
​
children: HTMLCollection { 0: iq#118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ
, length: 1, … }
​
classList: DOMTokenList []
​
className: ""
​
clientHeight: 0
​
clientLeft: 0
​
clientTop: 0
​
clientWidth: 0
​
firstChild: <iq id="118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="upload.xyz-tlm.com" type="result" xmlns="jabber:client">​
firstElementChild: <iq id="118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="upload.xyz-tlm.com" type="result" xmlns="jabber:client">
​
id: ""
​
innerHTML: "<iq to=\"user.test2@xyz-tlm.com/jsxc-1c0af453\" from=\"upload.xyz-tlm.com\" type=\"result\" id=\"118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ\" xmlns=\"jabber:client\"><query xmlns=\"http://jabber.org/protocol/disco#info\"><identity name=\"HTTP File Upload\" type=\"file\" category=\"store\"/><feature var=\"urn:xmpp:http:upload\"/><feature var=\"eu:siacs:conversations:http:upload\"/><x type=\"result\" xmlns=\"jabber:x:data\"><field var=\"FORM_TYPE\" type=\"hidden\"><value>http://jabber.org/network/serverinfo</value></field></x></query></iq>"
​
isConnected: true
​
lastChild: <iq id="118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="upload.xyz-tlm.com" type="result" xmlns="jabber:client">​
lastElementChild: <iq id="118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="upload.xyz-tlm.com" type="result" xmlns="jabber:client">
​
localName: "body"
​
namespaceURI: "http://jabber.org/protocol/httpbind"
​
nextElementSibling: null
​
nextSibling: null
​
nodeName: "body"
​
nodeType: 1
​
nodeValue: null
​
onfullscreenchange: null
​
onfullscreenerror: null
​
outerHTML: "<body xmlns=\"http://jabber.org/protocol/httpbind\"><iq to=\"user.test2@xyz-tlm.com/jsxc-1c0af453\" from=\"upload.xyz-tlm.com\" type=\"result\" id=\"118fe7d0-88e7-4bbd-9142-eeb34de817ef:sendIQ\" xmlns=\"jabber:client\"><query xmlns=\"http://jabber.org/protocol/disco#info\"><identity name=\"HTTP File Upload\" type=\"file\" category=\"store\"/><feature var=\"urn:xmpp:http:upload\"/><feature var=\"eu:siacs:conversations:http:upload\"/><x type=\"result\" xmlns=\"jabber:x:data\"><field var=\"FORM_TYPE\" type=\"hidden\"><value>http://jabber.org/network/serverinfo</value></field></x></query></iq></body>"
​
ownerDocument: XMLDocument { … }
​
parentElement: null
​
parentNode: XMLDocument { … }
​
part: DOMTokenList []
​
prefix: null
​
previousElementSibling: null
​
previousSibling: null
​
scrollHeight: 0
​
scrollLeft: 0
​
scrollLeftMax: 0
​
scrollTop: 0
​
scrollTopMax: 0
​
scrollWidth: 0
​
shadowRoot: null
​
slot: ""
​
tagName: "body"
​
textContent: "http://jabber.org/network/serverinfo"
​
<prototype>: ElementPrototype { getAttributeNames: getAttributeNames(), getAttribute: getAttribute(), getAttributeNS: getAttributeNS(), … }
jsxc.bundle.js:4669:28
[Debug] > 
body
​
assignedSlot: null
​
attributes: NamedNodeMap(3) [ rid="439209965", xmlns="http://jabber.org/protocol/httpbind", sid="ce83fe17216cf7492c13520a844ad9a339e49445" ]
​
baseURI: "about:blank"
​
childElementCount: 0
​
childNodes: NodeList []
​
children: HTMLCollection
​​
length: 0
​​
<prototype>: HTMLCollectionPrototype { item: item(), namedItem: namedItem(), length: Getter, … }
​
classList: DOMTokenList []
​
className: ""
​
clientHeight: 0
​
clientLeft: 0
​
clientTop: 0
​
clientWidth: 0
​
firstChild: null
​
firstElementChild: null
​
id: ""
​
innerHTML: ""
​
isConnected: false
​
lastChild: null
​
lastElementChild: null
​
localName: "body"
​
namespaceURI: null
​
nextElementSibling: null
​
nextSibling: null
​
nodeName: "body"
​
nodeType: 1
​
nodeValue: null
​
onfullscreenchange: null
​
onfullscreenerror: null
​
outerHTML: "<body rid=\"439209965\" sid=\"ce83fe17216cf7492c13520a844ad9a339e49445\"/>"
​
ownerDocument: XMLDocument { … }
​
parentElement: null
​
parentNode: null
​
part: DOMTokenList []
​
prefix: null
​
previousElementSibling: null
​
previousSibling: null
​
scrollHeight: 0
​
scrollLeft: 0
​
scrollLeftMax: 0
​
scrollTop: 0
​
scrollTopMax: 0
​
scrollWidth: 0
​
shadowRoot: null
​
slot: ""
​
tagName: "body"
​
textContent: ""
​
<prototype>: ElementPrototype { getAttributeNames: getAttributeNames(), getAttribute: getAttribute(), getAttributeNS: getAttributeNS(), … }
jsxc.bundle.js:4669:28
XHRPOSThttps://xyz-tlm.com:5280/http-bind/
[HTTP/1.1 200 OK 174ms]

[Debug] < 
body
​
assignedSlot: null
​
attributes: NamedNodeMap [ xmlns="http://jabber.org/protocol/httpbind" ]
​
baseURI: "https://xyz-tlm.com:5280/http-bind/"
​
childElementCount: 2
​
childNodes: NodeList [ iq#67320677-1f5f-4c9f-ba42-861d8b239623:sendIQ, iq#8bc54f67-0143-4df6-b46e-4e25bcf4f241:sendIQ
 ]
​
children: HTMLCollection { 0: iq#67320677-1f5f-4c9f-ba42-861d8b239623:sendIQ, 1: iq#8bc54f67-0143-4df6-b46e-4e25bcf4f241:sendIQ
, length: 2, … }
​
classList: DOMTokenList []
​
className: ""
​
clientHeight: 0
​
clientLeft: 0
​
clientTop: 0
​
clientWidth: 0
​
firstChild: <iq id="67320677-1f5f-4c9f-ba42-861d8b239623:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="conference.xyz-tlm.com" type="result" xmlns="jabber:client">​
firstElementChild: <iq id="67320677-1f5f-4c9f-ba42-861d8b239623:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="conference.xyz-tlm.com" type="result" xmlns="jabber:client">
​
id: ""
​
innerHTML: "<iq to=\"user.test2@xyz-tlm.com/jsxc-1c0af453\" from=\"conference.xyz-tlm.com\" type=\"result\" id=\"67320677-1f5f-4c9f-ba42-861d8b239623:sendIQ\" xmlns=\"jabber:client\"><query xmlns=\"http://jabber.org/protocol/disco#info\"><identity name=\"Chatrooms\" type=\"text\" category=\"conference\"/><feature var=\"http://jabber.org/protocol/disco#info\"/><feature var=\"http://jabber.org/protocol/disco#items\"/><feature var=\"jabber:iq:register\"/><feature var=\"http://jabber.org/protocol/muc\"/><feature var=\"http://jabber.org/protocol/rsm\"/><feature var=\"vcard-temp\"/><feature var=\"urn:xmpp:mucsub:0\"/><feature var=\"http://jabber.org/protocol/muc#unique\"/><x type=\"result\" xmlns=\"jabber:x:data\"><field var=\"FORM_TYPE\" type=\"hidden\"><value>http://jabber.org/network/serverinfo</value></field></x></query></iq><iq to=\"user.test2@xyz-tlm.com/jsxc-1c0af453\" from=\"pubsub.xyz-tlm.com\" type=\"result\" id=\"8bc54f67-0143-4df6-b46e-4e25bcf4f241:sendIQ\" xmlns=\"jabber:client\"><query xmlns=\"http://jabber.org/protocol/disco#info\"><identity name=\"Publish-Subscribe\" type=\"service\" category=\"pubsub\"/><feature var=\"http://jabber.org/protocol/disco#info\"/><feature var=\"http://jabber.org/protocol/disco#items\"/><feature var=\"http://jabber.org/protocol/pubsub\"/><feature var=\"http://jabber.org/protocol/commands\"/><feature var=\"vcard-temp\"/><feature var=\"http://jabber.org/protocol/pubsub#access-authorize\"/><feature var=\"http://jabber.org/protocol/pubsub#access-open\"/><feature var=\"http://jabber.org/protocol/pubsub#access-presence\"/><feature var=\"http://jabber.org/protocol/pubsub#access-whitelist\"/><feature var=\"http://jabber.org/protocol/pubsub#auto-create\"/><feature var=\"http://jabber.org/protocol/pubsub#auto-subscribe\"/><feature var=\"http://jabber.org/protocol/pubsub#collections\"/><feature var=\"http://jabber.org/protocol/pubsub#config-node\"/><feature var=\"http://jabber.org/protocol/pubsub#create-and-configure\"/><feature var=\"http://jabber.org/protocol/pubsub#create-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#delete-items\"/><feature var=\"http://jabber.org/protocol/pubsub#delete-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#filtered-notifications\"/><feature var=\"http://jabber.org/protocol/pubsub#get-pending\"/><feature var=\"http://jabber.org/protocol/pubsub#instant-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#item-ids\"/><feature var=\"http://jabber.org/protocol/pubsub#last-published\"/><feature var=\"http://jabber.org/protocol/pubsub#manage-subscriptions\"/><feature var=\"http://jabber.org/protocol/pubsub#member-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#modify-affiliations\"/><feature var=\"http://jabber.org/protocol/pubsub#outcast-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#persistent-items\"/><feature var=\"http://jabber.org/protocol/pubsub#presence-notifications\"/><feature var=\"http://jabber.org/protocol/pubsub#presence-subscribe\"/><feature var=\"http://jabber.org/protocol/pubsub#publish\"/><feature var=\"http://jabber.org/protocol/pubsub#publish-only-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#publisher-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#purge-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#retract-items\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-affiliations\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-default\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-items\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-subscriptions\"/><feature var=\"http://jabber.org/protocol/pubsub#shim\"/><feature var=\"http://jabber.org/protocol/pubsub#subscribe\"/><feature var=\"http://jabber.org/protocol/pubsub#subscription-notifications\"/><x type=\"result\" xmlns=\"jabber:x:data\"><field var=\"FORM_TYPE\" type=\"hidden\"><value>http://jabber.org/network/serverinfo</value></field></x></query></iq>"
​
isConnected: true
​
lastChild: <iq id="8bc54f67-0143-4df6-b46e-4e25bcf4f241:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="pubsub.xyz-tlm.com" type="result" xmlns="jabber:client">​
lastElementChild: <iq id="8bc54f67-0143-4df6-b46e-4e25bcf4f241:sendIQ" to="user.test2@xyz-tlm.com/jsxc-1c0af453" from="pubsub.xyz-tlm.com" type="result" xmlns="jabber:client">
​
localName: "body"
​
namespaceURI: "http://jabber.org/protocol/httpbind"
​
nextElementSibling: null
​
nextSibling: null
​
nodeName: "body"
​
nodeType: 1
​
nodeValue: null
​
onfullscreenchange: null
​
onfullscreenerror: null
​
outerHTML: "<body xmlns=\"http://jabber.org/protocol/httpbind\"><iq to=\"user.test2@xyz-tlm.com/jsxc-1c0af453\" from=\"conference.xyz-tlm.com\" type=\"result\" id=\"67320677-1f5f-4c9f-ba42-861d8b239623:sendIQ\" xmlns=\"jabber:client\"><query xmlns=\"http://jabber.org/protocol/disco#info\"><identity name=\"Chatrooms\" type=\"text\" category=\"conference\"/><feature var=\"http://jabber.org/protocol/disco#info\"/><feature var=\"http://jabber.org/protocol/disco#items\"/><feature var=\"jabber:iq:register\"/><feature var=\"http://jabber.org/protocol/muc\"/><feature var=\"http://jabber.org/protocol/rsm\"/><feature var=\"vcard-temp\"/><feature var=\"urn:xmpp:mucsub:0\"/><feature var=\"http://jabber.org/protocol/muc#unique\"/><x type=\"result\" xmlns=\"jabber:x:data\"><field var=\"FORM_TYPE\" type=\"hidden\"><value>http://jabber.org/network/serverinfo</value></field></x></query></iq><iq to=\"user.test2@xyz-tlm.com/jsxc-1c0af453\" from=\"pubsub.xyz-tlm.com\" type=\"result\" id=\"8bc54f67-0143-4df6-b46e-4e25bcf4f241:sendIQ\" xmlns=\"jabber:client\"><query xmlns=\"http://jabber.org/protocol/disco#info\"><identity name=\"Publish-Subscribe\" type=\"service\" category=\"pubsub\"/><feature var=\"http://jabber.org/protocol/disco#info\"/><feature var=\"http://jabber.org/protocol/disco#items\"/><feature var=\"http://jabber.org/protocol/pubsub\"/><feature var=\"http://jabber.org/protocol/commands\"/><feature var=\"vcard-temp\"/><feature var=\"http://jabber.org/protocol/pubsub#access-authorize\"/><feature var=\"http://jabber.org/protocol/pubsub#access-open\"/><feature var=\"http://jabber.org/protocol/pubsub#access-presence\"/><feature var=\"http://jabber.org/protocol/pubsub#access-whitelist\"/><feature var=\"http://jabber.org/protocol/pubsub#auto-create\"/><feature var=\"http://jabber.org/protocol/pubsub#auto-subscribe\"/><feature var=\"http://jabber.org/protocol/pubsub#collections\"/><feature var=\"http://jabber.org/protocol/pubsub#config-node\"/><feature var=\"http://jabber.org/protocol/pubsub#create-and-configure\"/><feature var=\"http://jabber.org/protocol/pubsub#create-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#delete-items\"/><feature var=\"http://jabber.org/protocol/pubsub#delete-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#filtered-notifications\"/><feature var=\"http://jabber.org/protocol/pubsub#get-pending\"/><feature var=\"http://jabber.org/protocol/pubsub#instant-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#item-ids\"/><feature var=\"http://jabber.org/protocol/pubsub#last-published\"/><feature var=\"http://jabber.org/protocol/pubsub#manage-subscriptions\"/><feature var=\"http://jabber.org/protocol/pubsub#member-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#modify-affiliations\"/><feature var=\"http://jabber.org/protocol/pubsub#outcast-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#persistent-items\"/><feature var=\"http://jabber.org/protocol/pubsub#presence-notifications\"/><feature var=\"http://jabber.org/protocol/pubsub#presence-subscribe\"/><feature var=\"http://jabber.org/protocol/pubsub#publish\"/><feature var=\"http://jabber.org/protocol/pubsub#publish-only-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#publisher-affiliation\"/><feature var=\"http://jabber.org/protocol/pubsub#purge-nodes\"/><feature var=\"http://jabber.org/protocol/pubsub#retract-items\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-affiliations\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-default\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-items\"/><feature var=\"http://jabber.org/protocol/pubsub#retrieve-subscriptions\"/><feature var=\"http://jabber.org/protocol/pubsub#shim\"/><feature var=\"http://jabber.org/protocol/pubsub#subscribe\"/><feature var=\"http://jabber.org/protocol/pubsub#subscription-notifications\"/><x type=\"result\" xmlns=\"jabber:x:data\"><field var=\"FORM_TYPE\" type=\"hidden\"><value>http://jabber.org/network/serverinfo</value></field></x></query></iq></body>"
​
ownerDocument: XMLDocument { … }
​
parentElement: null
​
parentNode: XMLDocument { … }
​
part: DOMTokenList []
​
prefix: null
​
previousElementSibling: null
​
previousSibling: null
​
scrollHeight: 0
​
scrollLeft: 0
​
scrollLeftMax: 0
​
scrollTop: 0
​
scrollTopMax: 0
​
scrollWidth: 0
​
shadowRoot: null
​
slot: ""
​
tagName: "body"
​
textContent: "http://jabber.org/network/serverinfohttp://jabber.org/network/serverinfo"
​
<prototype>: ElementPrototype { getAttributeNames: getAttributeNames(), getAttribute: getAttribute(), getAttributeNS: getAttributeNS(), … }
jsxc.bundle.js:4669:28
[http-upload][Debug] Error: Found no suitable http upload service. File probably too large. jsxc.bundle.js:4669:28
[Warn] Attachment was not processed

**Comment by ana-jd** [comment]
i underline the fact that my ejabberd server supports http_upload with many other xmpp clients like conversations.im and jsxc 4.0.0 beta.

**Comment by ana-jd** [comment]
can you see the source of the issue in these logs ?

**Comment by ana-jd** [comment]
i upgraded to ejabberd 19 and it does work so it is not compatible with ejabberd 17.

**Comment by sualko** [comment]
Thanks for that information and sorry for your trouble.
