### ISSUE TITLE
Click avatar to change status

### ISSUE THREAD

**Issue by republicus** [jsxc/jsxc#900]
### **Is your feature request related to a problem? Please describe.**

When I try to change Online status, I often click my avatar/icon. 

This behavior is expected in Nextcloud to access Nextcloud settings etc.

Until I clicked my name, I initially thought I couldn't change status. As it appears to be a link with the hand symbol... but nothing happens

### **Describe the solution you'd like**

Expand area to include the user avatar to change online status.

**Comment by sualko** [comment]
The area is "reserved" for a change avatar dialog, but you are right that the different ui behavior can confuse people.

**Comment by mightymop** [comment]
> 
> 
> The area is "reserved" for a change avatar dialog, but you are right that the different ui behavior can confuse people.

this PR https://github.com/jsxc/jsxc/pull/976 brings XEP84 and will also open the set dialog when click on the avatar...

**Comment by sualko** [comment]
> The area is "reserved" for a change avatar dialog, but you are right that the different ui behavior can confuse people.

This means, we can close this issue.
