### ISSUE TITLE
Some letters not accepted

### ISSUE THREAD

**Issue by republicus** [jsxc/jsxc#901]
Is it possible to disable Nextcloud shortcuts/hot-keys when a chat window has focus?

In Nextcloud Mail App (others likely) several shortcut keys prevent JSXC from inputting text.

### Expected behavior
Able to type full messages across site.

### Actual behavior
Shortcut keys take priority over JSXC and no text for specific keys/letters are entered into JSXC

### Steps to reproduce the behavior
1. Open Nextcloud Mail App
2. Open JSXC chat
3. Type message. (try including letter **s**: test)

### Environment
- **JSXC version:** 4.1.0
- **Host system and version:** Nextcloud 18.0.4

**Comment by sualko** [comment]
I think there was a similar issue some time ago, but I don't find it now. If I have time I will look into it.
