### ISSUE TITLE
Iphone users can't hear and image freezes

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#904]
### Expected behavior

When trying calls on different iPhone Xs an 6s the person using iPhone can't hear and the image freezes on his side.

Browser used is Safari. IOS 13.2

Can you please help

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by ana-jd** [comment]
in jsxc_bundle.js i modified <video autoplay> by <video autoplay playsinline> and it resolved it.

**Comment by sualko** [comment]
Thanks for reporting this behavior and providing a fix. I reopen this issue until it's fixed in core.
