### ISSUE TITLE
Question : Disconnect a user progamatically

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#905]
### Expected behavior
I would like to be able to disconnect a user when i face the issue : "user with same jid already exists"

i tried jsxc.disconnect(); but it doesn't seem to work.

here is my code to try to reconnect after failed connection : 

var index=0
 //first connection
jsxc.start('https://xyz.com:5280/http-bind/', login, pass)
.then(function() {
    index=1;
}).catch(function(err) {
   index=0;
   jsxc.disconnect();
         })       
//Second connection
if(index==0) jsxc.start('https://xyz:5280/http-bind/', login, pass);

Thanks

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
> when i face the issue : "user with same jid already exists"

What do you mean? Do you try to create users on the fly? Do you maybe like to use anonymous auth?

> i tried jsxc.disconnect(); but it doesn't seem to work.

please provide the requested logs.

**Comment by ana-jd** [comment]
i just forced the user to disconnect each time he leaves the page. the issue is not related to jsxc.
I just close this ticket.
