### ISSUE TITLE
Doubt: Tls certificate expired

### ISSUE THREAD

**Issue by susobaco** [jsxc/jsxc#906]
Hello, from dino I can't connect to my nextcloud server because it tells me that the TLS certificate has expired.
Is it a problem with my server or jsxc.ch ?
https://xmpp.net/result.php?domain=palautgn.jsxc.ch&type=client

**Comment by sualko** [comment]
I think it's an issue on our side. @marcel.waldvogel is already looking at it.

**Comment by susobaco** [comment]
Ok, thanks.

**Comment by MarcelWaldvogel** [comment]
Fixed (see nextcloud/jsxc.nextcloud#151 for details).
