### ISSUE TITLE
Please display Delete chat option in JSXC chat

### ISSUE THREAD

**Issue by hdp2101** [jsxc/jsxc#907]
Hello
      I would like to request you that please provide **DELETE CHAT** option for the user and admin to avoid any misunderstand, I installed **JSXC** on my Nextcloud server 18, everything is working fine except Delete chat option, because i need to give option to user to delete their chat from the server. 

I saw link for file that i transfer to other user like **userdata.mydomain.jsxc.ch** in **CSP Content-Security-Policy** section, but when i am going to particular link i saw nothing. so i am wondering where the user data store in my server. Also i see message of **Load Older Message** option in chat window. Means after few days if any user come back and when they click on **Load Older Message** option all message shows again. 

So my user told me to show **DELETE CHAT** option in chat window, in 2 option

**1. Delete Entire Chat
2. Option to delete selected message**

So this way they can delete unwanted Message, Files, Images, Audio, Video, etc.. files.

Please note I am using **Managed (Beta service)** for **JSXC**

So i am requesting you to kindly enable **DELETE CHAT** option for smooth uses of **JSXC**

I hope this issue will resolve ASAP.

Thank you
Hemal Parikh

![Ashampoo_Snap_2020 06 06_18h43m33s_002_](https://user-images.githubusercontent.com/13566445/83945110-07b8da00-a826-11ea-9920-467d7724fbd8.png)

![Ashampoo_Snap_2020 06 06_18h53m38s_003_](https://user-images.githubusercontent.com/13566445/83945277-4dc26d80-a827-11ea-835e-a63b4eb384ad.png)

**Comment by sualko** [comment]
Neither prosody nor ejabberd is supporting XEP-0424, so there is no way to retract a message. If you like to request a removal, send a mail to marcel@jsxc.ch.
