### ISSUE TITLE
A way to redefine the look&feel of the roster

### ISSUE THREAD

**Issue by mmoqui** [jsxc/jsxc#910]
We have built a XMPP client atop of JSXC 3 by simply using the JSXC distribution as a dependency of the client: by doing so, no modification is done directly in the source code of JSXC; we have just to override some of the functions and templates of JSXC. The goal of this is to redefine the look&feel of the roster as well as some functions. For instance, the roster window is tabbed with two tabs: one for groupchats and another one for buddies.

Now, with JSXC 4, the way it is built and its deep use of the TypeScript capabilities, we don't have access to nothing from an outside project. So our approach in the JSXC customization to answer our requirements can be no more done. We have to directly modify the code source of JSXC for doing and it is a way we would like to avoid. 

Do you have any idea about a way for clients to customize the look&feel of the JSXC roster and some of its functions?

**Comment by sualko** [comment]
We plan to transform the project to react, so the core should be independent from the ui system in the future.
