### ISSUE TITLE
Thumbnails only for images/ Url link for rest of file types

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#911]
### Expected behavior
When files are received, the plateforme looks a lot more professional if they are displayed as thumbnails or at least icons instead of a long url link.

### Actual behavior

Except for images files received are displayed as url links including videos.

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 
yes 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by mightymop** [comment]
i think my PR: https://github.com/jsxc/jsxc/pull/973/files would do it... 
It changes links to open in a new window by setting target="_blank" and images (jpg,png, svg and gif) are displayed in the chatwindow...
