### ISSUE TITLE
Connected Contacts Are Not On Top of Roster

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#912]
### Expected behavior

In version 4.1.0 Connected Contacts are no longer on top of the roster as in previous versions.

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
That's now the intended behavior, but you can hide all offline contacts so you basically have the old view.
