### ISSUE TITLE
audio frame minimizing

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#913]
### Expected behavior

When i minimize audio frame it disappears in version 4.1.0

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by DanScharon** [comment]
duplicate of #896
