### ISSUE TITLE
Invalid parameter (missing name) in payload-type

### ISSUE THREAD

**Issue by iNPUTmice** [jsxc/jsxc#915]
### Expected behavior

Don’t send `<parameter/>` without a name attribute.

The name attribute is required according to 0167.

JSXC attempts to map some SDP that Firefox generates to something that currently can not be mapped to 0167.

Movim has the same issue: https://github.com/movim/movim/issues/930

### Actual behavior

Sends parameters that contains a value but no name.

### Steps to reproduce the behavior
1. Use Firefox
2. Call Conversations
3. Conversations tries to parse the name. Can’t find it and errors out with an 'Application failure'

### Environment
- **JSXC version:** 4.1.0
- **Host system and version:** Nextcloud 
- **Browser vendor and version:** Firefox

**Comment by sualko** [comment]
Thanks for the hint. As I use jingle.js for the the jingle stuff, I don't know much about the actually xep, but as the authors from otalk are not that active anymore, I guess this will change in the future. It's easy to filter those invalid elements, but do you know which purpose it has for firefox?

**Comment by iNPUTmice** [comment]
> Do you know which purpose it has for Firefox?

Not really. This is translated from SDP and if you look at the corresponding RFC for that codec it means that it can handle DTMF tones 0-15. 

https://tools.ietf.org/html/rfc4733#section-2.4.1

FWIW the current Conversations master accepts these kind of things. (Exactly one parameter with one value); In that case it just uses that as one argument for fmtp. But I still believe that this is wrong according to the XEP.

**Comment by sualko** [comment]
> But I still believe that this is wrong according to the XEP.

I think you are right here, but thanks for accepting those corrupt stanzas. I will try to fix them on the next release.

**Comment by nels83** [comment]
I came across this problem some time ago. I fixed it (temporarily using patch-package) here : https://github.com/nels83/jsxc/commit/505ea8c98443cfa642f5586cff54da3700b347e5
Maybe it can help ;-)

**Comment by sualko** [comment]
I removed the entire `telephone-event` payload, because I think it's unused. Hope that's fine. @nels83 I think your suggestion would be the right place, but the otalk team deferred there development, so I guess it's hard to get a new release. We probably have to fork the whole stuff. Btw. if you notice such things it would be much appreciated if you could open an issue :wink:

**Comment by joe-average-user** [comment]
Ok, now you closed this issue, too :-)
I wanted to add that the call-out works, but on call-in to jsxc we see no sign of the call whatsoever, no popup or anything. Tested now with Edge(Chrome Engine).

**Comment by sualko** [comment]
@joe-average-user #890 is still open :wink:

**Comment by nels83** [comment]
> I removed the entire `telephone-event` payload, because I think it's unused. Hope that's fine. @nels83 I think your suggestion would be the right place, but the otalk team deferred there development, so I guess it's hard to get a new release. We probably have to fork the whole stuff. Btw. if you notice such things it would be much appreciated if you could open an issue wink

I planned to (that's why I uploaded these commits) then forgot about it until I saw this issue :grin:
