### ISSUE TITLE
Unhandled exception when trying to enable the app

### ISSUE THREAD

**Issue by guidot** [jsxc/jsxc#916]
### Environment
jsxc 4.1.0
Nextcloud 19.0
Debian Buster
MariaDB Ver 15.1 Distrib 10.3.22-MariaDB
Nginx 1.14.2 (config from nextcloud docs)
PHP 7.3.14-1~deb10u1
ejabberd 20.04 (only installed, nothing configured yet)

### What I did
This is a fresh install of nextcloud (1 week old). I was able to install and enable jsxc once. When I played with it I realized it didn't work well in standalone mode, so I decided to install `ejabberd`.
Before I did that I switched the settings to external server to have a look at the necessary settings, but then disabled the app.
I installed ejabberd from buster-backports.
I tried to re-enable jsxc and ran into
> An error occured during the request. Unable to proceed.

So I removed the app and started over again. Same Error.
After that I tried to repair nextcloud using occ. Made no difference.
I found some jsxc related settings: `apiSecret, types, installed_version, enabled` and deleted them using occ.
Then I tried intalling jsxc again using occ. This is what I got:

### Errors in the console
```
$ php occ app:install ojsxc
ojsxc installed
An unhandled exception has been thrown:
TypeError: XMLWriter::writeAttribute() expects parameter 2 to be string, null given in /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php:229
Stack trace:
#0 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php(229): XMLWriter->writeAttribute('name', NULL)
#1 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php(209): Sabre\Xml\Writer->writeAttribute('name', NULL)
#2 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Serializer/functions.php(176): Sabre\Xml\Writer->writeAttributes(Array)
#3 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), '')
#4 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Serializer/functions.php(177): Sabre\Xml\Writer->write(Array)
#5 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Serializer/functions.php(184): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#6 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#7 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Serializer/functions.php(177): Sabre\Xml\Writer->write(Array)
#8 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Serializer/functions.php(184): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#9 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#10 /var/www/nextcloud/html/apps/ojsxc/lib/db/iqrosterpush.php(79): Sabre\Xml\Writer->write(Array)
#11 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Serializer/functions.php(160): OCA\OJSXC\Db\IQRosterPush->xmlSerialize(Object(Sabre\Xml\Writer))
#12 /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Object(OCA\OJSXC\Db\IQRosterPush))
#13 /var/www/nextcloud/html/apps/ojsxc/lib/db/stanzamapper.php(48): Sabre\Xml\Writer->write(Object(OCA\OJSXC\Db\IQRosterPush))
#14 /var/www/nextcloud/html/apps/ojsxc/lib/rosterpush.php(106): OCA\OJSXC\Db\StanzaMapper->insert(Object(OCA\OJSXC\Db\IQRosterPush))
#15 /var/www/nextcloud/html/apps/ojsxc/lib/rosterpush.php(151): OCA\OJSXC\RosterPush->removeRosterItem('Guido Schmidt')
#16 /var/www/nextcloud/html/apps/ojsxc/lib/Migration/RefreshRoster.php(69): OCA\OJSXC\RosterPush->refreshRoster()
#17 /var/www/nextcloud/html/lib/private/Repair.php(103): OCA\OJSXC\Migration\RefreshRoster->run(Object(OC\Repair))
#18 /var/www/nextcloud/html/lib/private/legacy/OC_App.php(976): OC\Repair->run()
#19 /var/www/nextcloud/html/lib/private/Installer.php(169): OC_App::executeRepairSteps('ojsxc', Array)
#20 /var/www/nextcloud/html/lib/private/legacy/OC_App.php(402): OC\Installer->installApp('ojsxc')
#21 /var/www/nextcloud/html/core/Command/App/Install.php(81): OC_App->enable('ojsxc')
#22 /var/www/nextcloud/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/html/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/nextcloud/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/nextcloud/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/nextcloud/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/nextcloud/html/console.php(100): OC\Console\Application->run()
#28 /var/www/nextcloud/html/occ(11): require_once('/var/www/nextcl...')
```
### Logs
Then I searched for errors in the logs and found some from my earlier attempts:
```
[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "ojsxc.javascript.generalConfig" as such route does not exist. at <<closure>>
 0. /var/www/nextcloud/html/lib/private/Route/Router.php line 338
    Symfony\Component\Routing\Generator\UrlGenerator->generate("ojsxc.javascript.generalConfig", [], 1)
 1. /var/www/nextcloud/html/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("ojsxc.javascript.generalConfig", [], false)
 2. /var/www/nextcloud/html/lib/private/URLGenerator.php line 83
    OC\Route\CachingRouter->generate("ojsxc.javascript.generalConfig", [])
 3. /var/www/nextcloud/html/apps/ojsxc/appinfo/app.php line 26
    OC\URLGenerator->linkToRoute("ojsxc.javascript.generalConfig")
 4. /var/www/nextcloud/html/lib/private/legacy/OC_App.php line 266
    require_once("/var/www/nextcl ... p")
 5. /var/www/nextcloud/html/lib/private/legacy/OC_App.php line 155
    OC_App::requireAppFile("ojsxc")
 6. /var/www/nextcloud/html/lib/private/legacy/OC_App.php line 961
    OC_App::loadApp("ojsxc")
 7. /var/www/nextcloud/html/lib/private/Installer.php line 169
    OC_App::executeRepairSteps("ojsxc", {step: "OCA\\OJS ... "})
 8. /var/www/nextcloud/html/apps/settings/lib/Controller/AppSettingsController.php line 447
    OC\Installer->installApp("ojsxc")
 9. /var/www/nextcloud/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["ojsxc"], [])
10. /var/www/nextcloud/html/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
11. /var/www/nextcloud/html/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
12. /var/www/nextcloud/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
13. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
14. /var/www/nextcloud/html/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
15. /var/www/nextcloud/html/lib/base.php line 1007
    OC\Route\Router->match("/settings/apps/enable")
16. /var/www/nextcloud/html/index.php line 37
    OC::handleRequest()
POST /settings/apps/enable
from [IP here] by [name] at 2020-06-17T12:32:35+00:00
```
and:
```
[PHP] Error: Undefined index: from at /var/www/nextcloud/html/apps/ojsxc/lib/stanzahandlers/iq.php#86

POST /apps/ojsxc/http-bind
from [IP here] by [name] at 2020-06-17T12:34:20+00:00
```
I checked if nextcloud was able to install apps at all and tried it with `mind map`, that worked without problems.

**Comment by sualko** [comment]
Please try to remove all `*_ojsxc_*` tables, all entries in `*_migrations` related to ojsxc and try to install it again.

**Comment by guidot** [comment]
OK, thanks. I removed the tables `oc_ojsxc_presence` and `oc_ojsxc_stanzas`, also `ojsxc` from  `oc_migrations`.
Then in the app list I was offered to update to 4.1.1, which I did. But when I tried to enable the app it bailed with the same error message.
Removed the app and deleted all above mentioned tables and rows.
Installed again using occ. The errors in the console are the same, exept that it didn't state the first line: `ojsxc installed`.

**Comment by sualko** [comment]
Do you have any special usernames (with spaces, non Latin characters,...)? Can you post the output of ``? As you can see from [our CI](https://travis-ci.org/github/nextcloud/jsxc.nextcloud) enabling the app on a fresh installation works normally just fine. Therefore it has to be something special to your installtion, but as we have another report we are maybe able to isolate the issue. Can you also post the output from `php occ config:list system` and `php occ app:list`. @rollanders can you do the same?

**Comment by rollanders** [comment]
My config:list system
 
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "korskyrkan-intra.dedyn.io"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/korskyrkan-intra.dedyn.io",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "ojsxc",
            "drop_account",
            "social",
            "gallery",
            "registration"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
--and app:list
Enabled:
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - apporder: 0.10.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - cms_pico: 1.0.7
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - data_request: 1.6.0
  - dav: 1.15.0
  - drop_account: 0.2.1
  - external: 3.6.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_external: 1.10.0
  - files_markdown: 2.3.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_texteditor: 2.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - gallery: 18.5.0
  - groupfolders: 6.0.6
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.0
  - nextbackup: 20.4.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.2.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - registration: 0.4.7
  - richdocuments: 3.7.2
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sociallogin: 2.4.8
  - spreed: 9.0.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - circles
  - encryption
  - nextcloud_announcements
  - ojsxc
  - printer
  - recommendations
  - social
  - support
  - survey_client
  - systemtags
  - terms_of_service
  - user_ldap
  - user_saml

**Comment by marcus-fleck** [comment]
Hi,

I have the same issue, 

Nextcloud 19.0.0
ojsxc: 4.1.1
MariaDB-server-10.3.22-1.el7.centos.x86_64
httpd-2.4.39-1.x86_64 (apache)
php 7.2
OS CENTOS7

**Comment by sualko** [comment]
I tried it on a fresh installation of Nextcloud 19 and had no look to reproduce this, but I continue my search. Just to make sure, you all are getting the following error?

```
TypeError: XMLWriter::writeAttribute() expects parameter 2 to be string, null given in /var/www/nextcloud/html/3rdparty/sabre/xml/lib/Writer.php:229
```

**Comment by marcus-fleck** [comment]
yes for me. What I also tried is, I moved my nextcloud folder and created a new one, just copied the config folder from the old one. 

[nextcloud]$ date
Tue Jun 30 12:18:50 CEST 2020
[nextcloud]$ php occ app:enable ojsxc
An unhandled exception has been thrown:
TypeError: XMLWriter::writeAttribute() expects parameter 2 to be string, null given in /var/www/virtual/oricloud/html/owncloud/3rdparty/sabre/xml/lib/Writer.php:229
Stack trace:
#0 /var/www/virtual/oricloud/html/owncloud/3rdparty/sabre/xml/lib/Writer.php(229): XMLWriter->writeAttribute('name', NULL)

**Comment by sualko** [comment]
@marcus-fleck thanks for that information. Can you try to apply nextcloud/jsxc.nextcloud@6ae9ad2 manually?

**Comment by marcus-fleck** [comment]
yep this fixed it for me. I could enable the app. The chat is there after login and it seems like I can write somebody.

**Comment by sualko** [comment]
Huray :tada: Thanks for testing :+1:
