### ISSUE TITLE
Hide Turn secret value in settings

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#920]
**Is your feature request related to a problem? Please describe.**
Sensitive data, eg passwords are to be hidden in settings. Turn secret field is not open.

**Is your feature request related to a specific XEP?**
No

![image](https://user-images.githubusercontent.com/5199030/85329111-92fac680-b4da-11ea-9f34-4cd15686e49a.png)

**Describe the solution you'd like**
Please, make the value of the field hidden, eg with asterisks.

**Comment by sualko** [comment]
> Sensitive data, eg passwords are to be hidden in settings

I doubt that someone is able to memorize a long random string and therefore the advantage of comparing the secret outweighs the risk for me. If someone has time for a pr, a toggle button would be nice.

**Comment by ostasevych** [comment]
> > Sensitive data, eg passwords are to be hidden in settings
> 
> I doubt that someone is able to memorize a long random string and therefore the advantage of comparing the secret outweighs the risk for me. If someone has time for a pr, a toggle button would be nice.

Hi Klaus. Just to change the type of the respective field to password.

**Comment by sualko** [comment]
> Just to change the type of the respective field to password.

As I said, in my opinion it's more important to be able to compare the secret instead of hiding it.
