### ISSUE TITLE
JavaScript Xmpp Client registration

### ISSUE THREAD

**Issue by drvsistemas2010** [jsxc/jsxc#923]
I get this issue trying to register Xmpp Client Chat with a Managed service:

Sorry we couldn't complete your registration.
Couldn't reach the registration server
Please report this to our issue tracker and mention the request id WdiFx1YAAKRPZa3ehict.

**Comment by sualko** [comment]
Do you have any entries in your Nextcloud log?

cc @MarcelWaldvogel

**Comment by drvsistemas2010** [comment]
It's running ok just now. I try to connect again and is working ok.
Thank you
