### ISSUE TITLE
User is not getting online with managed server

### ISSUE THREAD

**Issue by markkhanippbx** [jsxc/jsxc#924]
### Expected behavior

User status should be changed to online after clicking online

### Actual behavior

it keeps spinning and on top status is always offline

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 4.1.1
- **Host system and version:**  Nextcloud 18.0.2
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
Please provide the required logs, otherwise I can't help.
