### ISSUE TITLE
Creation of the group

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#925]
**Is your feature request related to a problem? Please describe.**
Quite often people would like not only join, but create private and/or public groups/channels for communication. By now JSXC allow to join but not to create the groups itself.

**Is your feature request related to a specific XEP?**
XEP-0140, XEP-0045

**Describe the solution you'd like**
Add controls to the chat to create private and public groups.

**Additional context**
Allow administrator to restrict creation of groups limiting access only from the domain.

**Comment by sualko** [comment]
You can create groups via the roster menu (burger menu, bottom right) > "Join group". Just enter your desired group name. To configure your room, just open the configuration form via the chat window menu. Have fun!

**Comment by ostasevych** [comment]
> You can create groups via the roster menu (burger menu, bottom right) > "Join group". Just enter your desired group name. To configure your room, just open the configuration form via the chat window menu. Have fun!

Thank you, Klaus! It is so not easy to understand, how to do that...
May I suggest at least to change the title of this menu item, eg New group?
Also, I suggest to simplify the whole process of creating and joining the room. Now it is a big pain.
To let users easily create new groups and add members there without tons of options to fill in on this way (by default with later configuration, when needed).

**Comment by sualko** [comment]
> May I suggest at least to change the title of this menu item, eg New group?

The same dialog is used to create a new group or to join an existing one. It would be confusing two have two labels, because you don't know if a group with the intended name already exists. Just think about it as joining an existing, but empty room.

> add members there without tons of options

Did you know that you can use drag&drop to invite members?

> Now it is a big pain

Such an application is a huge undertaking and currently I don't make any revenue from it. So I work on those things which are most urgent or which I need asap. It would be great if more developers would join to make this application even better.

**Comment by ostasevych** [comment]
> > May I suggest at least to change the title of this menu item, eg New group?
> 
> The same dialog is used to create a new group or to join an existing one. It would be confusing two have two labels, because you don't know if a group with the intended name already exists. Just think about it as joining an existing, but empty room.
My suggestion is to change the naming of the button to make it more easily understood.
> 
> > add members there without tons of options
> 
> Did you know that you can use drag&drop to invite members?
No. Thank you for this hint!
> 
> > Now it is a big pain
> 
> Such an application is a huge undertaking and currently I don't make any revenue from it. So I work on those things which are most urgent or which I need asap. It would be great if more developers would join to make this application even better.
I see, sorry for asking numerous questions... Perhaps in a some moment, I may be useful in another role :)

**Comment by sualko** [comment]
> sorry for asking numerous questions... Perhaps in a some moment, I may be useful in another role

Don't get me wrong. I appreciate your feedback, because testers and fresh ideas are equally important as code contributions. I just want to be honest, so you know that you have maybe to wait sometime to get the desired feature. Keep up your good work :+1:
