### ISSUE TITLE
Can't connect to XMPP server on Thunderbird

### ISSUE THREAD

**Issue by bdietric5** [jsxc/jsxc#928]
### Expected behavior
Be able to connect to xmpp server in thunderbird.It correctly works on nextcloud interface.
### Actual behavior
I'd register to xmpp managed server on nextcloud. After the creation of my server, i want to be able to use it in thunderbird or other xmpp client. But the connection fails ...

### Steps to reproduce the behavior
1. Register to XMPP Server beta on Nextcloud 18
2. Put ID, Password in thunderbird
3. Not able to connect to xmpp server.

### Environment
- **JSXC version:**  4.1.1
- **Host system and version:** Debian 9 Nextcloud 18  
- **Browser vendor and version:** Chrome
- **Any browser plugins enabled?**  no
- **XMPP server vendor and version:**  Managed by ejabberd.
- **Is your XMPP server working with other clients as expected?** Only work on Nextcloud

I give you the information i got on nextcloud interface and the parameters i set in [thunderbird]([url](url))

![thunderbird](https://user-images.githubusercontent.com/36158090/86339943-800f9100-bc54-11ea-87a7-9198110a835d.PNG)
![jsxc](https://user-images.githubusercontent.com/36158090/86339949-80a82780-bc54-11ea-9a02-3252df866e48.PNG)

**Comment by sualko** [comment]
Why are you posting a screenshot from your ice servers? Do you use the secret in some way? You should be able to login with your normal Nextcloud password. Your Jid also looks weird, because it's normally "Nextcloud username"@1-one.jsxc.ch, but it could be correct anyway.

**Comment by bdietric5** [comment]
I don't know when i go to JSXC it give me that weird UID... I don't really understant the part about turn secret ... do i have to use it ? Idem for URLs do i have to set it in thunderbird?

**Comment by ostasevych** [comment]
> I don't know when i go to JSXC it give me that weird UID... I don't really understant the part about turn secret ... do i have to use it ? Idem for URLs do i have to set it in thunderbird?

This how it works in my case (I have self-hosted xmpp server):

![image](https://user-images.githubusercontent.com/5199030/86523603-7a45c580-be77-11ea-84c1-6050d8b51688.png)

**Comment by sualko** [comment]
If you still have issues, please reopen.
