### ISSUE TITLE
Ejabberd 20.04 ojsxc nextcloud

### ISSUE THREAD

**Issue by Thomas301263** [jsxc/jsxc#931]
### Expected behavior
OJSXC together with Nextcloud should work like the versions before

### Actual behavior
Not working cause in Ejabberd 20.04 mod_bind is changed to mod_bosh

### Steps to reproduce the behavior
1. Upgrade from Ejabberd 18 to Ejabberd 20.04
2. Changing NGINX configuration from /http-bind/ port 5280 to  /http-bosh/ port 5443 cause the standard port for http-bosh in EJABBERD 20.04 is port 5443 in configuration file.
3.

### Environment
jsxc 4.1.1
Nextcloud 19.0
Debian Buster
MariaDB Ver 15.1 Distrib 10.3.22-MariaDB
Nginx 1.14.2
PHP 7.3.19-1
ejabberd 20.04

Before the upgrade of Ejabberd it was working perfect. 
In EJABBERD 20.04 http-bind is changed to http-bosh and I changed NGINX to http-bosh and port 5443 cause that is the new standard one in EJABBERD 20.04. 
What changes have to be done that the CHAT APP OJSXC together with NEXTCLOUD will work again.

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
Please provide any error log, because it's not obvious why jsxc should not work with the latest ejabberd release.

**Comment by MarcelWaldvogel** [comment]
Alternatively, provide a documentation update. We do not run ejabberd 20.04 here now.
