### ISSUE TITLE
MUC 'leave' message contains unexpected characters.

### ISSUE THREAD

**Issue by guusdk** [jsxc/jsxc#933]
Using JSXC 4.1.1 on Openfire 4.6.0-beta: When an occupant that is named "Dele Olajide" leaves a MUC, the 'leave' message incorrectly contains `grin:` as shown below.

![image](https://user-images.githubusercontent.com/4253898/88920189-b26cd800-d26c-11ea-9b1d-4d105ec5c746.png)

I'm assuming (but did not verify) that this happens with all nicknames that start with a D. My hypothesis is that the first letter of Dele's name (`D`) gets concatenated with a colon (`:`) forming the smiley `:)` which gets transcoded to `:grin:` from which the first character is dropped. Maybe?

**Comment by sualko** [comment]
> I'm assuming (but did not verify) that this happens with all nicknames that start with a D

You are right. The resulting string will be `:door:Dele left the building`. This will be transformed to `:door:grin:ele left the building`.

**Comment by guusdk** [comment]
Maybe add a (nonbreaking) space between `:door:` and the nickname? Beauty is in the eye of the beholder, but I didn't like how the icon was attached to the nickname in the first place.

**Comment by sualko** [comment]
I had the same idea, but I also wanted to require that emoticons need to be surrounded by spaces. Sadly this is not as easy as I thought. `\b` works only on `\w` and something like `/(^| ):D( |$)/g` also doesn't work with repeating emoticons :disappointed:

**Comment by guusdk** [comment]
Adding a space in any case will make things less bad than they were before, so that's an improvement. There might be something to say to prevent text in nicknames to be ever transformed, but that might be a standalone issue in itself.
