### ISSUE TITLE
Group chats stop working 

### ISSUE THREAD

**Issue by mlashcorp** [jsxc/jsxc#936]
### Expected behavior
Able to chat with other people in a group chat ...

### Actual behavior
When chatting, if there is a stop in the conversation, sometimes the double checkmark icons change to eyes, and then I'm unable to send any more messages. The messages after that only have one checkmark, and the other user does not get them.

### Steps to reproduce the behavior
1. connect jsxc online demo to an openfire server
2. join chat to create a new group room
3. talk with another person

### Environment
- **JSXC version:**  version provided by jsxc online demo
- **Host system and version:** docker container with openfire 4.5.2
- **Browser vendor and version:** firefox
- **Any browser plugins enabled?** grammarly
- **XMPP server vendor and version:** openfire 4.5.2
- **Is your XMPP server working with other clients as expected?** did not try

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
This is not enough information to debug this issue. Please provide proper logs with raw stanzas. Sorry, for your issues anyway.
