### ISSUE TITLE
Sorry we couldn't complete your registration - Could not perform internal changes: Error obtaining Let's Encrypt ecertificate.

### ISSUE THREAD

**Issue by ei8fdb** [jsxc/jsxc#941]
### Expected behavior

Registration takes 20-30 seconds as mentioned on config page with eventual successful registration.

### Actual behavior
Registration fails after ~47 seconds with message:

Sorry we couldn't complete your registration.

Could not perform internal changes: Error obtaining Let's Encrypt ecertificate. Mail support@jsxc.ch. Please try again later or mail support@jsxc.ch

Please report this to our issue tracker and mention the request id Zawd8NJ4ztqW5NGTvmcR.

### Steps to reproduce the behavior
1. Go to JSXC settings and register for managed beta service
2. Change nothing, enable "Enable chat on log in"
3. Check privacy and warranty boxes
4. Click register 

### Environment
- **JSXC version:  4.1.1
- **Host system and version:** 
PHP
Version: 7.3.17
Type: pgsql
Version: PostgreSQL 11.9 (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

- **Browser vendor and version:**
Firefox 80.0.1 (64-bit)
- **Any browser plugins enabled?** 
yup a few, but nothing that (I think) would cause this error message.

- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 
Not using another client.

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

I am presuming the cause of this is something similar to #939.

**Comment by ei8fdb** [comment]
I've tried registration a few times over the last hour and the server has been successfully created now. While I think the issue can be closed, I'll leave it open in case you'd like to discuss it. Feel free to close it if you like.

**Comment by MarcelWaldvogel** [comment]
Yes, the DNS-based certificate creation we are forced to use to obtain XMPP certificates sometimes takes longer and times out. However, a follow-up request often solves the problem. We should increase the timeout in the client (and mention that it takes ~1 minute).
Sorry for the inconvenience!

**Comment by ei8fdb** [comment]
@MarcelWaldvogel No problem about the length of time! It was more a case of me thinking "hmmm...if I try to register multiple times will I get banned. Let's try and see what happens."

I agree it would be helpful to increase the timeout and mention it can take longer. Also - if it were possible to mention: you can retry registeration attempts once every X minutes or hours. Otherwise people may try, see it fail and leave thinking "ah it's broken".

Thanks for providing this service.

**Comment by kwisatz** [comment]
I tried this several times on a Nextcloud 19.0.4 installation and it fails every single time with 

```
Sorry we couldn't complete your registration.

Could not perform internal changes: Error obtaining Let's Encrypt ecertificate. Mail support@jsxc.ch. Please try again later or mail support@jsxc.ch

Please report this to our issue tracker and mention the request id gMWI9jtkM2tu9Y1RqsQa.
```

P.S. note the typo in "Let's Encrypt **e**certificate"

**Comment by MarcelWaldvogel** [comment]
Thanks for reporting the typo, it is fixed.

I also changed our DNS server configuration, which should help speed up certificate generation.
