### ISSUE TITLE
Certificate error when sending a file with external client (Dino & Conversations)

### ISSUE THREAD

**Issue by susobaco** [jsxc/jsxc#943]
(Sorry, I don't know if this is the right place to send the error)

### Expected behavior
That files can be sent and received
### Actual behavior
Cannot be sent or received
### Steps to reproduce the behavior
1. Attached a file
2. I send the file
3. Send file error: HTTP upload error: Certificado TLS inaceptable

### Environment
- **JSXC version:** 4.1.1
- **Host system and version:** Nextcloud 19.0.3
- **Browser vendor and version:** Dino 1.0

Description, I am connected to an account associated with a nextcloud domain (Managed Server) from an external client (Dino and Conversations) . When I try to send a file, I get a certificate error. From dino, it doesn't let me send it (Send file error: HTTP upload error: TLS certificate unacceptable), from conversations accepting the certificate as valid, it does send it but doesn't let me receive it from dino.If I try to open the file from a browser, I see that the address it uses to send it has the form: userdata.mydomain.jsxc.ch that does not coincide with the certificate associated with the server, which is mydomain.jsxc.ch .

Do you need more data?

Thanks and Cheers!

**Comment by sualko** [comment]
Can you try to send me a file to klaus@jsxc.org? Otherwise @MarcelWaldvogel do you have an idea?

**Comment by susobaco** [comment]
Thank you, I have sent the file from conversations. From dino, I couldn't send the file, it just gives tls certificate error.

**Comment by susobaco** [comment]
News?

**Comment by MarcelWaldvogel** [comment]
Sorry, that slipped under my radar. Can you tell me the full name of your domain, so I can check the server setup? (If you prefer not to post it here, mail it to marcel@jsxc.org?)

**Comment by susobaco** [comment]
I have sent you an email with the domain name.

**Comment by MarcelWaldvogel** [comment]
Seems to have been a problem with certificate creation/renewal which I guess is fixed (personal discussion).
