### ISSUE TITLE
Chat service as customer support

### ISSUE THREAD

**Issue by lemmel** [jsxc/jsxc#946]
Hi !

I would like to know if it is possible to implement a chat system that would be used as a customer chat system (something like Tidio).

At this time, I did achieve it with a IRC server (UnrealIRCd), a web client (Kiwiirc) and a desktop client (built by myself). All run correctly.

I would want:
- the user launch the client, and see nothing (except a small text telling something like "You can ask your question") ; a client can't see other people connected
- the support desk is notified that a person did arrive, click on the person
- the support desk and the client chat

Do you think it possible without too much work ?

EDIT : I just saw #945, a ticket that is quite close to mine; the main difference is that I don't ask about adding new features, I asked if it would be possible to bent a bit JSXC, as I did with UnrealIRCd and Kiwiirc.
To me more explicit, I'll explain what I did with UnrealIRCd and Kiwiirc:
- altered a bit Kiwiirc:
  - added some CSS
  - added some JS that fills and hides some fields; the chat room's name is a random one
- just set a password and run UnrealIRCd
- I built an IRC client that:
  - check regularly that no new room did appear
  - if a room did appear, then it connects to it
  - it check if there is another "support people" in it, if not, then it says Hello

So I did nothing great (no code alteration, just settings, and adding some CSS/JS), but I did get something working quickly.

**Comment by sualko** [comment]
> Do you think it possible without too much work ?

Everything is possible, but I think it's easier to write a new client. This is definitely out of scope for us.

> So I did nothing great (no code alteration, just settings, and adding some CSS/JS), but I did get something working quickly.

:tada:
