### ISSUE TITLE
In JSXC 4.2.0, settings menu and status menu are transparent above the roster

### ISSUE THREAD

**Issue by Aquariu** [jsxc/jsxc#958]
### Expected behavior
when clicking on the status setting, the menu should not be totally transparent and I shouldn't see parts of the roster mashed up with the status choice.
When clicking on the settings menu (the 3 lines), the developping menu should not be totally transparent and I shouldn't see the roster mashed up with the settings menu.

### Actual behavior
I can see the texts from those two menus, I can see the mouse-over working ok, clicking works ok. But there is no background/transparency color that I can see.
I can see the shadow at the top of those two menus.

![NC19 and JSXC 4 2 0 bug](https://user-images.githubusercontent.com/22145986/102357501-ad57bd80-3fae-11eb-9253-2c4b1ebcb256.png)

### Steps to reproduce the behavior
1. Login to NC with JSXC enabled
2.check that you're connected, click on arrow to see roster
3. Click on "Online" or the Menu (three lines)

### Environment
- 4.2.0
- Nextcloud 19.0.6
- Firefox 83 on Windows 10, Firefox 83 on Ubuntu 20.04, Google Chrome 87 on Windows 10, Google Chromium 87 on Ubuntu 20.04 
- Browser extensions turned off for the test
- Prosody 11.2 on Debian (same host as Nextcloud instance)
- Yes. Web display issue only 

#### Javascript

None
```

#### JSXC
<!-- Which messages appear in your javascript console if you enable debugging? -->
<!-- How to enable debugging: https://github.com/jsxc/jsxc/wiki/Debugging -->

I am unable to make the debug work. the command return;

`VM11368:1 Uncaught ReferenceError: jsxc is not defined
    at <anonymous>:1:1`
while under Chrome JS console
#### XMPP
<!-- Do you have any related entries in your XMPP server log? -->

None.

#### Host
<!-- Do you have any related entries in your host system log? -->
```
```
None

**Comment by mightymop** [comment]
This PR should fix the issue: https://github.com/jsxc/jsxc/pull/961
