### ISSUE TITLE
Chat-markers in MUC breaking message delivery?

### ISSUE THREAD

**Issue by tyrex1975** [jsxc/jsxc#959]
### Expected behavior
I have two separate JSXC users in a MUC room, using separate browsers on separate PCs. Users should be able to send messages to each other continuously without issue.

### Actual behavior
Once a 'chat-marker' is received on a user's PC, they can no longer send messages until they delete the group and re-join.

### Steps to reproduce the behavior
1. Set up two JSXC instances, one for each user, log each user in.
2. Add both users to MUC room.
2. User 1 sends message to User 2 in MUC.
3. User 2 reads message.
4. User 1's client now shows the delivery receipt 'eye' icon and can no longer send messages until they delete the group and re-join.
5. User 2 sends message to User 1.
6. User 2's client also shows the 'eye' icon and can no longer send messages either.

### Environment
- **JSXC version:** 4.1.1 and 4.2.0
- **Host system and version:** Windows 10 & Android
- **Browser vendor and version:** Chrome mostly but doesn't matter
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Openfire 4.6.0
- **Is your XMPP server working with other clients as expected?** Tried Spark (Windows) and Bruno (Android) but neither seem to support sending a delivery receipt back to JSXC

#### JSXC

User 1's log - sending message to group without issue:

```
jsxc.bundle.js:2 [Debug] > <body rid=​"3143726355" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"85slxx6zph">​…​</body>​
jsxc.bundle.js:2 [Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"3143726355">​</body>​
jsxc.bundle.js:2 [Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"3143726355">​<message xmlns=​"jabber:​client" id=​"8713d06b-262b-4aa5-9b2b-069418d002e3" to=​"9061275@teletrack.biz/​jsxc-3e01d955" type=​"groupchat" from=​"fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz/​Steve (9061275)​">​<body>​Test before view​</body>​<origin-id xmlns=​"urn:​xmpp:​sid:​0" id=​"8713d06b-262b-4aa5-9b2b-069418d002e3">​</origin-id>​<stanza-id xmlns=​"urn:​xmpp:​sid:​0" id=​"8713d06b-262b-4aa5-9b2b-069418d002e3" by=​"fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz">​</stanza-id>​</message>​</body>​
jsxc.bundle.js:2 [Debug] > <body rid=​"3143726356" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"85slxx6zph">​</body>​
```

User 1's log - receiving the marker back from User 2:
```
jsxc.bundle.js:2 [Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"3143726356">​<message xmlns=​"jabber:​client" to=​"9061275@teletrack.biz/​jsxc-3e01d955" type=​"chat" from=​"fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz/​Fred (9061274)​">​<displayed xmlns=​"urn:​xmpp:​chat-markers:​0" id=​"8713d06b-262b-4aa5-9b2b-069418d002e3">​</displayed>​<store xmlns=​"urn:​xmpp:​hints">​</store>​<stanza-id xmlns=​"urn:​xmpp:​sid:​0" id=​"b18ab682-e16d-4479-a42c-aa7556831dc0" by=​"fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz/​Steve (9061275)​">​</stanza-id>​</message>​</body>​
jsxc.bundle.js:2 [chat-markers][Debug] "displayed" marker received from "fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz/Fred (9061274)" to "9061275@teletrack.biz/jsxc-3e01d955"
jsxc.bundle.js:2 [Debug] > <body rid=​"3143726357" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"85slxx6zph">​</body>​
```

User 1's log - trying to send another message after receiving marker:
```
jsxc.bundle.js:2 [Debug] > <body rid=​"3143726358" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"85slxx6zph">​…​</body>​
jsxc.bundle.js:2 [Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"3143726358">​<message xmlns=​"jabber:​client" id=​"f56cc6d1-0150-4716-b6a7-e238cbeb8126" to=​"9061275@teletrack.biz/​jsxc-3e01d955" type=​"error" from=​"fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz/​Fred (9061274)​">​<body>​Test after view​</body>​<origin-id xmlns=​"urn:​xmpp:​sid:​0" id=​"f56cc6d1-0150-4716-b6a7-e238cbeb8126">​</origin-id>​<stanza-id xmlns=​"urn:​xmpp:​sid:​0" id=​"f56cc6d1-0150-4716-b6a7-e238cbeb8126" by=​"fb63d1c53b294ff771d7478759f5b3e573eabb87@conference.teletrack.biz/​Fred (9061274)​">​</stanza-id>​<error code=​"400" type=​"modify">​<bad-request xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-stanzas">​</bad-request>​<text xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-stanzas">​Unable to process message.​</text>​</error>​</message>​</body>​
jsxc.bundle.js:2 [Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"3143726358">​</body>​
jsxc.bundle.js:2 [Debug] > <body rid=​"3143726359" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"85slxx6zph">​</body>​
```

**Comment by tyrex1975** [comment]
Just to add, this issue is present on the JSXC.org demo page too. https://www.jsxc.org/example/?

I signed in as demo0 and demo1 on separate browsers and tried chatting in one of the MUC rooms, once a delivery receipt is present for either user, they can no longer chat.

**Comment by mightymop** [comment]
I can confirm this bug... if i disable chatmarker plugin in settings it runs fine...

**Comment by tyrex1975** [comment]
> I can confirm this bug... if i disable chatmarker plugin in settings it runs fine...

Brilliant - didn't realise you could disable plugins - thank you!

```
let jsxc = new JSXC({
 disabledPlugins: ['chat-markers'],
 [remaining init config here ]
});
```

**Comment by mightymop** [comment]
> 
> 
> > I can confirm this bug... if i disable chatmarker plugin in settings it runs fine...
> 
> Brilliant - didn't realise you could disable plugins - thank you!
> 
> ```
> let jsxc = new JSXC({
>  disabledPlugins: ['chat-markers'],
>  [remaining init config here]
> });
> ```

you can also disable the plugin if go into settings in roster und click on you account.. you will get a list with plugins then... simply disable the checkbox...

**Comment by sualko** [comment]
I can confirm this issue and will provide a fix asap.
