### ISSUE TITLE
Jabber ID domain replaced with @null

### ISSUE THREAD

**Issue by frankbootmaker** [jsxc/jsxc#966]
### Expected behavior
Username in Jabber ID shall contain the domain of the system i.e. admin@<nextclouddomain>

### Actual behavior
The domain part is replaced with "null". i.e. admin@null

### Steps to reproduce the behavior
1. Upgraded to 4.2.0 version
2. Can't login (logon spinning) -> click to settings
3. Click on the username@null (i.e admin@null)

### Environment
- **JSXC version: 4.2.0** 
- **Host system and version: Nextcloud 20.0.3** 
- **Browser vendor and version: Firefox, Chrome, both latest** 
- **Any browser plugins enabled? No** 
- **XMPP server vendor and version: Internal server** 
- **Is your XMPP server working with other clients as expected? This is the internal XMPP server of the app, behaviour is same for any** 

![kép](https://user-images.githubusercontent.com/32898636/102690662-3f5a0300-4207-11eb-97b5-7a3adbfbf177.png)

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by EmJotGeh** [comment]
Same problem - circle rotates endlessly and nothing happens. Domain of other users show correct values e.g. user1@mydomain.tld

**Comment by spacyal** [comment]
I have the same issue. 

circle rotates endless - going online is not possible. 

having a view errors in the log. 

for example: 

`{"reqId":"QCWz9PQC4uLNv9ZYMSsd","level":3,"time":"2020-12-25T16:20:03+01:00","remoteAddr":"10.128.0.2","user":"patrickadmin","app":"PHP","method":"POST","url":"/apps/ojsxc/http-bind","message":{"Exception":"Error","Message":"Undefined index: from at /var/www/nextcloud/apps/ojsxc/lib/stanzahandlers/iq.php#86","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/ojsxc/lib/stanzahandlers/iq.php","line":86,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/ojsxc/lib/Controller/HttpBindController.php","line":194,"function":"handle","class":"OCA\\OJSXC\\StanzaHandlers\\IQ","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\OJSXC\\Controller\\HttpBindController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}`

**Comment by sualko** [comment]
Thanks for reporting this issue. I hope the fix is working for you. Happy holidays!

**Comment by frankbootmaker** [comment]
Many thanks for the fix, I can confirm that the fix does work for me! :-)

**Comment by EmJotGeh** [comment]
For me too, thank you very much!
