### ISSUE TITLE
Pictures not displaying as pictures

### ISSUE THREAD

**Issue by M-Stenzel** [jsxc/jsxc#989]
Hi team,

this is my setup: JavaScript XMPP Chat 4.2.1, Nextcloud 18.0.12, ejabberd 20.07, apache 2.4.46.
Web Browser is Iridium 2020.11.85 running on Linux.
On the other end there is Conversations 2.9.2 (f-droid).
I have a problem on both sides: When sending pictures I do not see the pictures but only links (see pictures below).
It does not help to turn off OMEMO. Neither in the web interface, nor in Conversations the pictures are displayed.
Sending from Conversations to Conversations (second device) works without errors.

Another phenomenon is that when I send emojis from jsxc these are displayed as als text, as well e. g. ":heart:"

There are no errors/warning in ejabberd.log, nor in apache log files.

The browser console shows me: 

Refused to load the image 'cid:f3e3bd2c-7dde-464d-ba86-61c019b3d56d' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: *". 

I do not think this is related, however, wonder where this comes from (jsxc app.php file?).

Where to go next?

Any help appreciated! Martin.

![110](https://user-images.githubusercontent.com/76916440/103486030-16d32b00-4dfb-11eb-8408-334e652d8003.jpg)
![111](https://user-images.githubusercontent.com/76916440/103486039-26527400-4dfb-11eb-92b3-4d0758a026b2.jpg)

**Comment by sualko** [comment]
To protect the users privacy we are currently not loading external images and therefore you see only the url. @mightymop is currently working on a privacy protecting solution, se #973.

Why conversation is not correctly parsing our encrypted http upload, is currently not clear to me. I have to investigate that a bit more, maybe they changed something.

**Comment by M-Stenzel** [comment]
Hi team,
I doublechecked after your comment. Messages from jsxc to jsxc work fine from both sides.
Pictures are displayed correctly. Indeed it seems to be a problem with Conversations.

**Comment by Tuxicoman2** [comment]
Dino uses https://xmpp.org/extensions/xep-0066.html#x-oob to specify the file location it has uploaded with XEP-0363: HTTP File Upload

I don't see this used by JXSC outgoing messages.

addUrlToMessage() method in HttpUploadPlugin.ts is writing an HTML description instead.
And I see also a base64 data passed into the message (which is a bit counterproductive if you pass the http URL, no?)

Maybe this is what is missing for pictures to be displayed in Dino/Conversations.

**Comment by Tuxicoman2** [comment]
Example of Dino message without encyption:

```
<body sid='83ab9aa2-7456-4d8c-890a-13abdbb00117' xmlns='http://jabber.org/protocol/httpbind' xmlns:stream='http://etherx.jabber.org/streams'>
  <message from='sender@jesuislibre.net/dino.b5ca1e35' type='chat' to='receiver@jesuislibre.net' id='586a058c-fd58-426b-95ee-0a80347fcf09' xmlns='jabber:client'>
  <body>
    https://upload.jesuislibre.net:5281/upload/K-fwu6WaoGkaNU2D/figure-fig1.png
  </body>
  <x xmlns='jabber:x:oob'>
    <url>
      https://upload.jesuislibre.net:5281/upload/K-fwu6WaoGkaNU2D/figure-fig1.png
    </url>
  </x>
  <request xmlns='urn:xmpp:receipts'/>
  <active xmlns='http://jabber.org/protocol/chatstates'/>
  <markable xmlns='urn:xmpp:chat-markers:0'/>
  <stanza-id by='receiver@jesuislibre.net' xmlns='urn:xmpp:sid:0' id='ef_CkdW_x6u4gLnY'/>
  </message>
</body>
```

**Comment by sualko** [comment]
I tried to reproduce the issue without luck. Pictures or files send to conversations are correctly displayed. As mentioned the other way around is currently not supported. EDIT if you add text to the image, than the image is not displayed by conversation. Did you send some text with the image?

oob is a good idea, but not possible with omemo. Therefore we would need stanza encryption.

The base64 contains a thumbnail for the file, but we should probably look for a more standard solution.
